/** \file dbal_init_cb_tables_hard_logic_tm_hl_tm_latency_definition.c
 * Logical DB enums \n 
 * DO NOT EDIT THIS FILE!\n 
 * This file is auto-generated.\n 
 * Edits to this file will be lost when it is regenerated.\n 
 * \n 
 */
/*
 * $Id: $
 $Copyright: (c) 2019 Broadcom.
 Broadcom Proprietary and Confidential. All rights reserved.$
 * 
 */
#ifdef BSL_LOG_MODULE
#  error "BSL_LOG_MODULE redefined"
#endif
#define BSL_LOG_MODULE BSL_LS_SOCDNX_DBALDNX

#include <src/soc/dnx/dbal/dbal_internal.h>
#include <soc/dnx/dnx_data/auto_generated/dnx_data.h>

shr_error_e
latency_voq_quartet_profile_profile_id_entryoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    dbal_entry_handle_t *  eh = (dbal_entry_handle_t *) entry_handle;
    uint32 key_value__quartet_queue;
    SHR_FUNC_INIT_VARS(unit);
    DBAL_FORMULA_CB_GET_KEY_VALUE(unit, eh, DBAL_FIELD_QUARTET_QUEUE, key_value__quartet_queue);
    *offset = key_value__quartet_queue/64;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
shr_error_e
latency_voq_quartet_profile_profile_id_dataoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    dbal_entry_handle_t *  eh = (dbal_entry_handle_t *) entry_handle;
    uint32 key_value__quartet_queue;
    /** size is calculated by the Autocoder  */
    uint32 result_size__profile_id = 0;
    SHR_FUNC_INIT_VARS(unit);
    DBAL_FORMULA_CB_GET_KEY_VALUE(unit, eh, DBAL_FIELD_QUARTET_QUEUE, key_value__quartet_queue);
    /** size of PROFILE_ID field  */
    result_size__profile_id += 3;
    *offset = key_value__quartet_queue%64*result_size__profile_id;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
shr_error_e
latency_voq_quartet_profile_map_lat_flow_profile_dataoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    dbal_entry_handle_t *  eh = (dbal_entry_handle_t *) entry_handle;
    uint32 key_value__quartet_profile;
    SHR_FUNC_INIT_VARS(unit);
    DBAL_FORMULA_CB_GET_KEY_VALUE(unit, eh, DBAL_FIELD_QUARTET_PROFILE, key_value__quartet_profile);
    *offset = key_value__quartet_profile*6;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
shr_error_e
latency_voq_quartet_profile_map_tc_map_dataoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    dbal_entry_handle_t *  eh = (dbal_entry_handle_t *) entry_handle;
    uint32 key_value__quartet_profile;
    SHR_FUNC_INIT_VARS(unit);
    DBAL_FORMULA_CB_GET_KEY_VALUE(unit, eh, DBAL_FIELD_QUARTET_PROFILE, key_value__quartet_profile);
    *offset = key_value__quartet_profile*6+3;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
shr_error_e
latency_egress_l4q_profile_null_entryoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    dbal_entry_handle_t *  eh = (dbal_entry_handle_t *) entry_handle;
    uint32 key_value__l4q_flow_id;
    SHR_FUNC_INIT_VARS(unit);
    DBAL_FORMULA_CB_GET_KEY_VALUE(unit, eh, DBAL_FIELD_L4Q_FLOW_ID, key_value__l4q_flow_id);
    *offset = key_value__l4q_flow_id;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
shr_error_e
latency_egress_l4q_map_aqm_flow_id_port_tc_l4q_flow_id_dataoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    dbal_entry_handle_t *  eh = (dbal_entry_handle_t *) entry_handle;
    uint32 key_value__tc;
    /** size is calculated by the Autocoder  */
    uint32 result_size__l4q_flow_id = 0;
    SHR_FUNC_INIT_VARS(unit);
    DBAL_FORMULA_CB_GET_KEY_VALUE(unit, eh, DBAL_FIELD_TC, key_value__tc);
    /** size of L4Q_FLOW_ID field  */
    result_size__l4q_flow_id += 8;
    *offset = key_value__tc*result_size__l4q_flow_id;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
shr_error_e
latency_egress_packet_classification_cfg_de_dataoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    dbal_entry_handle_t *  eh = (dbal_entry_handle_t *) entry_handle;
    uint32 key_value__ecn_profile;
    SHR_FUNC_INIT_VARS(unit);
    DBAL_FORMULA_CB_GET_KEY_VALUE(unit, eh, DBAL_FIELD_ECN_PROFILE, key_value__ecn_profile);
    *offset = key_value__ecn_profile;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
shr_error_e
latency_egress_maintain_average_latency_use_new_avg_dataoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    dbal_entry_handle_t *  eh = (dbal_entry_handle_t *) entry_handle;
    uint32 key_value__pkt_type_key;
    SHR_FUNC_INIT_VARS(unit);
    DBAL_FORMULA_CB_GET_KEY_VALUE(unit, eh, DBAL_FIELD_PKT_TYPE_KEY, key_value__pkt_type_key);
    *offset = key_value__pkt_type_key*2;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
shr_error_e
latency_egress_maintain_average_latency_use_new_inst_dataoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    dbal_entry_handle_t *  eh = (dbal_entry_handle_t *) entry_handle;
    uint32 key_value__pkt_type_key;
    SHR_FUNC_INIT_VARS(unit);
    DBAL_FORMULA_CB_GET_KEY_VALUE(unit, eh, DBAL_FIELD_PKT_TYPE_KEY, key_value__pkt_type_key);
    *offset = key_value__pkt_type_key*2+1;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
