/** \file dbal_init_cb_tables_hard_logic_pp_oam_hl_pp_oam_misc.c
 * Logical DB enums \n 
 * DO NOT EDIT THIS FILE!\n 
 * This file is auto-generated.\n 
 * Edits to this file will be lost when it is regenerated.\n 
 * \n 
 */
/*
 * $Id: $
 $Copyright: (c) 2019 Broadcom.
 Broadcom Proprietary and Confidential. All rights reserved.$
 * 
 */
#ifdef BSL_LOG_MODULE
#  error "BSL_LOG_MODULE redefined"
#endif
#define BSL_LOG_MODULE BSL_LS_SOCDNX_DBALDNX

#include <src/soc/dnx/dbal/dbal_internal.h>
#include <soc/dnx/dnx_data/auto_generated/dnx_data.h>

shr_error_e
egress_oam_process_map_oam_process_action_dataoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    dbal_entry_handle_t *  eh = (dbal_entry_handle_t *) entry_handle;
    uint32 full_key_value;
    /** size is calculated by the Autocoder  */
    uint32 full_result_size = 0;
    SHR_FUNC_INIT_VARS(unit);
    DBAL_FORMULA_CB_GET_FULL_KEY_VALUE(unit, eh, full_key_value);
    /** size of OAM_PROCESS_ACTION field  */
    full_result_size += 3;
    *offset = full_key_value*full_result_size;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
shr_error_e
ingress_oam_sub_type_to_data_type_map_ingress_oam_data_type_dataoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    dbal_entry_handle_t *  eh = (dbal_entry_handle_t *) entry_handle;
    uint32 full_key_value;
    /** size is calculated by the Autocoder  */
    uint32 full_result_size = 0;
    SHR_FUNC_INIT_VARS(unit);
    DBAL_FORMULA_CB_GET_FULL_KEY_VALUE(unit, eh, full_key_value);
    /** size of INGRESS_OAM_DATA_TYPE field  */
    full_result_size += 2;
    *offset = full_key_value*full_result_size;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
shr_error_e
oamp_interrupt_report_jr2_stat_event_dataoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    /** size is calculated by the Autocoder  */
    uint32 result_size__jr2_stat_event = 0;
    uint32 instance_idx;
    SHR_FUNC_INIT_VARS(unit);
    /** size of JR2_STAT_EVENT field  */
    result_size__jr2_stat_event += 32;
    DBAL_FORMULA_CB_GET_INSTANCE_IDX(unit, current_mapped_field_id, instance_idx);
    *offset = instance_idx*result_size__jr2_stat_event;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
shr_error_e
oamp_interrupt_data_jr2_oamp_event_dataoffset_0_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    /** size is calculated by the Autocoder  */
    uint32 result_size__jr2_oamp_event = 0;
    uint32 instance_idx;
    SHR_FUNC_INIT_VARS(unit);
    /** size of JR2_OAMP_EVENT field  */
    result_size__jr2_oamp_event += 48;
    DBAL_FORMULA_CB_GET_INSTANCE_IDX(unit, current_mapped_field_id, instance_idx);
    *offset = instance_idx*result_size__jr2_oamp_event;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
shr_error_e
oamp_interrupt_data_jr2_oamp_event_dataoffset_1_cb(
int unit,
void * entry_handle,
dbal_fields_e current_mapped_field_id,
uint32 * offset)
{
    /** size is calculated by the Autocoder  */
    uint32 result_size__jr2_oamp_event = 0;
    uint32 instance_idx;
    SHR_FUNC_INIT_VARS(unit);
    /** size of JR2_OAMP_EVENT field  */
    result_size__jr2_oamp_event += 48;
    DBAL_FORMULA_CB_GET_INSTANCE_IDX(unit, current_mapped_field_id, instance_idx);
    *offset = instance_idx*result_size__jr2_oamp_event+16;
    SHR_EXIT();
exit:
    SHR_FUNC_EXIT;
}
