/** \file dbal_init_field_types_auto_generated_standard_1_standard_1_virtual_tcam_field_types.c
 * Logical DB enums \n 
 * DO NOT EDIT THIS FILE!\n 
 * This file is auto-generated.\n 
 * Edits to this file will be lost when it is regenerated.\n 
 * \n 
 */
/*
 * $Id: $
 $Copyright: (c) 2019 Broadcom.
 Broadcom Proprietary and Confidential. All rights reserved.$
 * 
 */
#ifdef BSL_LOG_MODULE
#  error "BSL_LOG_MODULE redefined"
#endif
#define BSL_LOG_MODULE BSL_LS_SOCDNX_DBALDNX

#include <src/soc/dnx/dbal/dbal_internal.h>

shr_error_e
_dbal_init_field_types_auto_generated_standard_1_standard_1_virtual_tcam_field_types_prttcam_key_vp_coe_init(
int unit,
field_type_db_struct_t * cur_field_type_param,
dbal_field_types_basic_info_t * field_types_info)
{
    SHR_FUNC_INIT_VARS(unit);
    dbal_init_field_type_db_struct_clear(unit, cur_field_type_param);
    dbal_db_init_field_type_general_info_set(unit, cur_field_type_param, "PRTTCAM_KEY_VP_COE" /* name*/, "14" /* size*/, EMPTY /* resource name*/, "STRUCTURE" /* print*/, 0 /* is common*/, 1 /* is default*/, TRUE /* is_standard_1 is set by Autocoder*/);
    /** *********************  */
    /** field type interface  */
    /** *********************  */
    /** struct fields  */
    /** clear struct fields array  */
    sal_memset(cur_field_type_param->structs, 0x0, 2 * sizeof(dbal_db_struct_field_info_struct_t));
    sal_strncpy(cur_field_type_param->structs[0].name, "VID", sizeof(cur_field_type_param->structs[0].name));
    SHR_IF_ERR_EXIT(dbal_db_parse_dnx_data_indication(unit, &cur_field_type_param->structs[0].length_dnx_data, "8" /* size*/, FALSE, 0, "", ""));
    sal_strncpy(cur_field_type_param->structs[1].name, "PTC_ATTRIBUTE", sizeof(cur_field_type_param->structs[1].name));
    SHR_IF_ERR_EXIT(dbal_db_parse_dnx_data_indication(unit, &cur_field_type_param->structs[1].length_dnx_data, "6" /* size*/, FALSE, 0, "", ""));
    cur_field_type_param->nof_structs = 2;
    /** ***********************  */
    /** field type phy mapping  */
    /** ***********************  */
    /** reference field  */
    sal_strncpy(cur_field_type_param->refernce_field_name, EMPTY /* reference field*/, sizeof(cur_field_type_param->refernce_field_name));
    /** default restrict values  */
    cur_field_type_param->nof_illegal_value = 0;
    cur_field_type_param->min_value_dnx_data.int_val = DBAL_DB_INVALID;
    cur_field_type_param->max_value_dnx_data.int_val = DBAL_DB_INVALID;
    cur_field_type_param->const_value_dnx_data.int_val = DBAL_DB_INVALID;
    cur_field_type_param->default_val_dnx_data.int_val = 0;
    cur_field_type_param->default_val_valid = FALSE;
    /** add field type to dbal  */
    SHR_IF_ERR_EXIT(dbal_db_init_field_type_add(unit, cur_field_type_param, field_types_info));
exit:
    SHR_FUNC_EXIT;
}

shr_error_e
_dbal_init_field_types_auto_generated_standard_1_standard_1_virtual_tcam_field_types_prttcam_key_vp_pon_init(
int unit,
field_type_db_struct_t * cur_field_type_param,
dbal_field_types_basic_info_t * field_types_info)
{
    SHR_FUNC_INIT_VARS(unit);
    dbal_init_field_type_db_struct_clear(unit, cur_field_type_param);
    dbal_db_init_field_type_general_info_set(unit, cur_field_type_param, "PRTTCAM_KEY_VP_PON" /* name*/, "13" /* size*/, EMPTY /* resource name*/, "STRUCTURE" /* print*/, 0 /* is common*/, 1 /* is default*/, TRUE /* is_standard_1 is set by Autocoder*/);
    /** *********************  */
    /** field type interface  */
    /** *********************  */
    /** struct fields  */
    /** clear struct fields array  */
    sal_memset(cur_field_type_param->structs, 0x0, 3 * sizeof(dbal_db_struct_field_info_struct_t));
    sal_strncpy(cur_field_type_param->structs[0].name, "PON_TAG_PON_SUBPORT_ID", sizeof(cur_field_type_param->structs[0].name));
    SHR_IF_ERR_EXIT(dbal_db_parse_dnx_data_indication(unit, &cur_field_type_param->structs[0].length_dnx_data, "3" /* size*/, FALSE, 0, "", ""));
    sal_strncpy(cur_field_type_param->structs[1].name, "PTC", sizeof(cur_field_type_param->structs[1].name));
    SHR_IF_ERR_EXIT(dbal_db_parse_dnx_data_indication(unit, &cur_field_type_param->structs[1].length_dnx_data, "DNX_DATA.mdb_app_db.fields.numeric_mdb_field___217" /* size*/, FALSE, 0, "", ""));
    sal_strncpy(cur_field_type_param->structs[2].name, "ZERO_PADDING", sizeof(cur_field_type_param->structs[2].name));
    SHR_IF_ERR_EXIT(dbal_db_parse_dnx_data_indication(unit, &cur_field_type_param->structs[2].length_dnx_data, "DNX_DATA.mdb_app_db.fields.numeric_mdb_field___218" /* size*/, FALSE, 0, "", ""));
    cur_field_type_param->nof_structs = 3;
    /** ***********************  */
    /** field type phy mapping  */
    /** ***********************  */
    /** reference field  */
    sal_strncpy(cur_field_type_param->refernce_field_name, EMPTY /* reference field*/, sizeof(cur_field_type_param->refernce_field_name));
    /** default restrict values  */
    cur_field_type_param->nof_illegal_value = 0;
    cur_field_type_param->min_value_dnx_data.int_val = DBAL_DB_INVALID;
    cur_field_type_param->max_value_dnx_data.int_val = DBAL_DB_INVALID;
    cur_field_type_param->const_value_dnx_data.int_val = DBAL_DB_INVALID;
    cur_field_type_param->default_val_dnx_data.int_val = 0;
    cur_field_type_param->default_val_valid = FALSE;
    /** add field type to dbal  */
    SHR_IF_ERR_EXIT(dbal_db_init_field_type_add(unit, cur_field_type_param, field_types_info));
exit:
    SHR_FUNC_EXIT;
}

shr_error_e
_dbal_init_field_types_auto_generated_standard_1_standard_1_virtual_tcam_field_types_prttcam_key_vp_spa_init(
int unit,
field_type_db_struct_t * cur_field_type_param,
dbal_field_types_basic_info_t * field_types_info)
{
    SHR_FUNC_INIT_VARS(unit);
    dbal_init_field_type_db_struct_clear(unit, cur_field_type_param);
    dbal_db_init_field_type_general_info_set(unit, cur_field_type_param, "PRTTCAM_KEY_VP_SPA" /* name*/, "16" /* size*/, EMPTY /* resource name*/, "STRUCTURE" /* print*/, 0 /* is common*/, 1 /* is default*/, TRUE /* is_standard_1 is set by Autocoder*/);
    /** *********************  */
    /** field type interface  */
    /** *********************  */
    /** struct fields  */
    /** clear struct fields array  */
    sal_memset(cur_field_type_param->structs, 0x0, 1 * sizeof(dbal_db_struct_field_info_struct_t));
    sal_strncpy(cur_field_type_param->structs[0].name, "SYSTEM_PORT_AGGREGATE", sizeof(cur_field_type_param->structs[0].name));
    SHR_IF_ERR_EXIT(dbal_db_parse_dnx_data_indication(unit, &cur_field_type_param->structs[0].length_dnx_data, "16" /* size*/, FALSE, 0, "", ""));
    cur_field_type_param->nof_structs = 1;
    /** ***********************  */
    /** field type phy mapping  */
    /** ***********************  */
    /** reference field  */
    sal_strncpy(cur_field_type_param->refernce_field_name, EMPTY /* reference field*/, sizeof(cur_field_type_param->refernce_field_name));
    /** default restrict values  */
    cur_field_type_param->nof_illegal_value = 0;
    cur_field_type_param->min_value_dnx_data.int_val = DBAL_DB_INVALID;
    cur_field_type_param->max_value_dnx_data.int_val = DBAL_DB_INVALID;
    cur_field_type_param->const_value_dnx_data.int_val = DBAL_DB_INVALID;
    cur_field_type_param->default_val_dnx_data.int_val = 0;
    cur_field_type_param->default_val_valid = FALSE;
    /** add field type to dbal  */
    SHR_IF_ERR_EXIT(dbal_db_init_field_type_add(unit, cur_field_type_param, field_types_info));
exit:
    SHR_FUNC_EXIT;
}

shr_error_e
_dbal_init_field_types_auto_generated_standard_1_standard_1_virtual_tcam_field_types_prt_kbr_info_half_init(
int unit,
field_type_db_struct_t * cur_field_type_param,
dbal_field_types_basic_info_t * field_types_info)
{
    SHR_FUNC_INIT_VARS(unit);
    dbal_init_field_type_db_struct_clear(unit, cur_field_type_param);
    dbal_db_init_field_type_general_info_set(unit, cur_field_type_param, "PRT_KBR_INFO_HALF" /* name*/, "17" /* size*/, EMPTY /* resource name*/, "UINT32" /* print*/, 0 /* is common*/, 1 /* is default*/, TRUE /* is_standard_1 is set by Autocoder*/);
    /** *********************  */
    /** field type interface  */
    /** *********************  */
    /** child field  */
    /** clear child field array  */
    sal_memset(cur_field_type_param->childs, 0x0, 3 * sizeof(dbal_db_child_field_info_struct_t));
    sal_strncpy(cur_field_type_param->childs[0].name, "PRTTCAM_KEY_VP_COE", sizeof(cur_field_type_param->childs[0].name));
    sal_strncpy(cur_field_type_param->childs[1].name, "PRTTCAM_KEY_VP_PON", sizeof(cur_field_type_param->childs[1].name));
    sal_strncpy(cur_field_type_param->childs[2].name, "PRTTCAM_KEY_VP_SPA", sizeof(cur_field_type_param->childs[2].name));
    cur_field_type_param->nof_childs = 3;
    /** ***********************  */
    /** field type phy mapping  */
    /** ***********************  */
    /** reference field  */
    sal_strncpy(cur_field_type_param->refernce_field_name, EMPTY /* reference field*/, sizeof(cur_field_type_param->refernce_field_name));
    /** default restrict values  */
    cur_field_type_param->nof_illegal_value = 0;
    cur_field_type_param->min_value_dnx_data.int_val = DBAL_DB_INVALID;
    cur_field_type_param->max_value_dnx_data.int_val = DBAL_DB_INVALID;
    cur_field_type_param->const_value_dnx_data.int_val = DBAL_DB_INVALID;
    cur_field_type_param->default_val_dnx_data.int_val = 0;
    cur_field_type_param->default_val_valid = FALSE;
    {
        /** encode type  */
        sal_strncpy(cur_field_type_param->childs[0].encode_type, "PREFIX" /* encode type*/, DBAL_MAX_SHORT_STRING_LENGTH);
        SHR_IF_ERR_EXIT(dbal_db_parse_dnx_data_indication(unit, &cur_field_type_param->childs[0].encode_param1_dnx_data, "4" /* encode param*/, FALSE, 0, "", ""));
    }
    {
        /** encode type  */
        sal_strncpy(cur_field_type_param->childs[1].encode_type, "PREFIX" /* encode type*/, DBAL_MAX_SHORT_STRING_LENGTH);
        SHR_IF_ERR_EXIT(dbal_db_parse_dnx_data_indication(unit, &cur_field_type_param->childs[1].encode_param1_dnx_data, "10" /* encode param*/, FALSE, 0, "", ""));
    }
    {
        /** encode type  */
        sal_strncpy(cur_field_type_param->childs[2].encode_type, "PREFIX" /* encode type*/, DBAL_MAX_SHORT_STRING_LENGTH);
        SHR_IF_ERR_EXIT(dbal_db_parse_dnx_data_indication(unit, &cur_field_type_param->childs[2].encode_param1_dnx_data, "0" /* encode param*/, FALSE, 0, "", ""));
    }
    /** add field type to dbal  */
    SHR_IF_ERR_EXIT(dbal_db_init_field_type_add(unit, cur_field_type_param, field_types_info));
exit:
    SHR_FUNC_EXIT;
}

shr_error_e
dbal_init_field_types_auto_generated_standard_1_standard_1_virtual_tcam_field_types_init(
int unit,
field_type_db_struct_t* cur_field_type_param,
dbal_field_types_basic_info_t * field_types_info)
{
    SHR_FUNC_INIT_VARS(unit);
    SHR_IF_ERR_EXIT(_dbal_init_field_types_auto_generated_standard_1_standard_1_virtual_tcam_field_types_prttcam_key_vp_coe_init(unit, cur_field_type_param, field_types_info));
    SHR_IF_ERR_EXIT(_dbal_init_field_types_auto_generated_standard_1_standard_1_virtual_tcam_field_types_prttcam_key_vp_pon_init(unit, cur_field_type_param, field_types_info));
    SHR_IF_ERR_EXIT(_dbal_init_field_types_auto_generated_standard_1_standard_1_virtual_tcam_field_types_prttcam_key_vp_spa_init(unit, cur_field_type_param, field_types_info));
    SHR_IF_ERR_EXIT(_dbal_init_field_types_auto_generated_standard_1_standard_1_virtual_tcam_field_types_prt_kbr_info_half_init(unit, cur_field_type_param, field_types_info));
exit:
    SHR_FUNC_EXIT;
}
