#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = libs/kaps

include ${SDK}/make/Make.config

lib = libkaps

INCDIR += -I${SDK}/libs/kaps/include
INCDIR += -I${SDK}/libs/kaps

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
