#$Id: Makefile,v 1.3.4.1 Broadcom SDK $
# $Copyright: Copyright 2007, Broadcom Corporation All Rights Reserved.
# THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES
# OF ANY KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE.
# BROADCOM SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.$
#
LOCALDIR = systems/linux/user/fastpath_common

include ${SDK}/make/Make.config

lib = liblusrcmmsys

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

