#
# $Id$
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dpp subdirectory
#

LOCALDIR = src/appl/diag/dnxc/swstate/auto_generated

include ${SDK}/make/Make.config

lib = libdiag_dnxcswstate_auto_generated

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

