#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/ppp

include ${SDK}/make/Make.config

#subdirs = ppp

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxppp

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

