#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/bcm/dnx/algo/port

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/bcm_int/dnx/algo/mirror

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxalgoport

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
