#ifndef STRLIB_METRO_CLI_C
#define STRLIB_METRO_CLI_C
#include "datatypes.h"

extern L7_char8 *pStrInfo_metro_dot1ad;
extern L7_char8 *pStrInfo_metro_dot1ad_svid;
extern L7_char8 *pStrInfo_metro_dot1ad_svid_help;
extern L7_char8 *pStrInfo_metro_isolate_vid;
extern L7_char8 *pStrInfo_metro_isolate_vid_help;
extern L7_char8 *pStrInfo_metro_dot1ad_help ;
extern L7_char8 *pStrInfo_metro_dot1ad_help_1;
extern L7_char8 *pStrInfo_metro_service ;
extern L7_char8 *pStrInfo_metro_service_help;
extern L7_char8 *pStrInfo_metro_dot1ad_upQos;
extern L7_char8 *pStrInfo_metro_dot1ad_upQos_help;
extern L7_char8 *pStrInfo_metro_dot1ad_downQos;
extern L7_char8 *pStrInfo_metro_dot1ad_downQos_help;
extern L7_char8 *pStrInfo_metro_subscrName;
extern L7_char8 *pStrInfo_metro_subscrName_help;
extern L7_char8 *pStrInfo_metro_serviceName;
extern L7_char8 *pStrInfo_metro_serviceName_help;
extern L7_char8 *pStrInfo_metro_servicevid_help;
extern L7_char8 *pStrInfo_metro_elan;
extern L7_char8 *pStrInfo_metro_elan_help;
extern L7_char8 *pStrInfo_metro_etree;
extern L7_char8 *pStrInfo_metro_etree_help;
extern L7_char8 *pStrInfo_metro_eline;
extern L7_char8 *pStrInfo_metro_eline_help;
extern L7_char8 *pStrInfo_metro_tls;
extern L7_char8 *pStrInfo_metro_tls_help;
extern L7_char8 *pStrInfo_metro_nni;
extern L7_char8 *pStrInfo_metro_nni_help;
extern L7_char8 *pStrInfo_metro_port_list;
extern L7_char8 *pStrInfo_metro_port_list_help;
extern L7_char8 *pStrInfo_metro_subscribe;
extern L7_char8 *pStrInfo_metro_subscribe_help;
extern L7_char8 *pStrInfo_metro_match;
extern L7_char8 *pStrInfo_metro_match_help;
extern L7_char8 *pStrInfo_metro_untaggedPkt;
extern L7_char8 *pStrInfo_metro_untaggedPkt_help;
extern L7_char8 *pStrInfo_metro_assignCvid;
extern L7_char8 *pStrInfo_metro_assignCvid_help;
extern L7_char8 *pStrInfo_metro_cvid;
extern L7_char8 *pStrInfo_metro_svid;
extern L7_char8 *pStrInfo_metro_cvid_help;
extern L7_char8 *pStrInfo_metro_cvid_value_help;
extern L7_char8 *pStrInfo_metro_priority;
extern L7_char8 *pStrInfo_metro_priority_help;
extern L7_char8 *pStrInfo_metro_priorityVal_help;
extern L7_char8 *pStrInfo_metro_cvid_help1;
extern L7_char8 *pStrInfo_metro_svid_help1;
extern L7_char8 *pStrInfo_metro_svlan_range;
extern L7_char8 *pStrInfo_metro_priority_range_0_7;
extern L7_char8 *pStrInfo_metro_remark_cvid ;
extern L7_char8 *pStrInfo_metro_remove_ctag;
extern L7_char8 *pStrInfo_metro_remark_cvid_help ;
extern L7_char8 *pStrInfo_metro_remove_ctag_help;
extern L7_char8 *pStrInfo_metro_assignQueue ;
extern L7_char8 *pStrInfo_metro_assignQueue_help ;
extern L7_char8 *pStrInfo_metro_queue_0_3 ;
extern L7_char8 *pStrInfo_metro_queue_help ;
extern L7_char8 *pStrInfo_metro_PoliceSimple;
extern L7_char8 *pStrInfo_metro_PoliceSimpleHelp;
extern L7_char8 *pStrInfo_metro_Range1to2147483647;
extern L7_char8 *pStrInfo_metro_Range64to2147483647_1;
extern L7_char8 *pStrInfo_metro_DataRateKbps;
extern L7_char8 *pStrInfo_metro_DiffservDataRateKbpsRobo;
extern L7_char8 *pStrInfo_metro_Range1to128;
extern L7_char8 *pStrInfo_metro_BurstSize;
extern L7_char8 *pStrInfo_metro_ConformAction;
extern L7_char8 *pStrInfo_metro_CfgPoliceConform;
extern L7_char8 *pStrInfo_metro_Drop ;
extern L7_char8 *pStrInfo_metro_ConformDrop;
extern L7_char8 *pStrInfo_metro_ConformSend;
extern L7_char8 *pStrInfo_metro_ViolateAction;
extern L7_char8 *pStrInfo_metro_PoliceNonConform;
extern L7_char8 *pStrInfo_metro_NonConformDrop ;
extern L7_char8 *pStrInfo_metro_NonConformSend;
extern L7_char8 *pStrInfo_metro_serviceAll_help;
extern L7_char8 *pStrInfo_metro_service_subscr;
extern L7_char8 *pStrInfo_metro_Interface;
extern L7_char8 *pStrInfo_metro_Interface_help;
extern L7_char8 *pStrInfo_metro_dot1ad_service_subcr_help;
extern L7_char8 *pStrErr_metro_CfgDot1adServiceCreate;
extern L7_char8 *pStrErr_metro_CfgDot1adInvalidServiceName;
extern L7_char8 *pStrErr_metro_CfgDot1adNonAlphaNumericServiceName;
extern L7_char8 *pStrErr_metro_CfgDot1adNonAlphaNumericSubscrName;
extern L7_char8 *pStrErr_metro_CfgDot1adServiceExists;
extern L7_char8 *pStrErr_metro_CfgDot1adServiceNameDonotExists;
extern L7_char8 *pStrErr_metro_CfgDot1adServiceDeleteFail;
extern L7_char8 *pStrErr_metro_CfgDot1adSvidExists;
extern L7_char8 *pStrErr_metro_CfgDot1adSvidNotInRange;
extern L7_char8 *pStrErr_metro_CfgDot1adConfigFail;
extern L7_char8 *pStrErr_metro_CfgDot1adConfigFailTblFull;
extern L7_char8 *pStrErr_metro_CfgDot1adConfigFailSubFull;
extern L7_char8 *pStrErr_metro_CfgDot1adSvcNotConfigured;
extern L7_char8 *pStrErr_metro_dot1adServiceSyntax;
extern L7_char8 *pStrErr_metro_dot1adServiceQosSyntax;
extern L7_char8 *pStrErr_metro_dot1adSubTls;
extern L7_char8 *pStrErr_metro_dot1adSubCvid;
extern L7_char8 *pStrErr_metro_dot1adSubPriority;
extern L7_char8 *pStrErr_metro_dot1adSubUntag;
extern L7_char8 *pstrErr_metro_dot1adSVlanDefaultVlanId;
extern L7_char8 *pStrErr_metro_CfgDot1adSvidExists;
extern L7_char8 *pStrErr_metro_CfgDot1adIsolateVidExists;
extern L7_char8 *pStrErr_metro_CfgDot1adIsolateVidEqualsToSvid;
extern L7_char8 *pStrErr_metro_CfgDot1adSvidEqualsToIsolateVid;
extern L7_char8 *pStrErr_metro_CfgDot1adSvidEqualsToIsolateVid_1;
#endif
