#
# $Id:$
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC swstate types subdirectory
#
LOCALDIR = src/soc/dnxc/swstate/types

include ${SDK}/make/Make.config

lib = libsoc_dnxcswstate_types

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
