#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# $Id: Makefile,v 1.4 Broadcom SDK $
LOCALDIR = src/appl/diag/dfe

include ${SDK}/make/Make.config

lib = libdiag_dfe

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
