/* $Id: soc_pb_parser.c,v 1.7 Broadcom SDK $
 * $Copyright: Copyright 2015 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
*/

/*************
 * INCLUDES  *
 *************/
/* { */

#include <soc/dpp/SAND/Utils/sand_header.h>

#include <soc/dpp/SAND/Management/sand_general_macros.h>
#include <soc/dpp/SAND/Management/sand_error_code.h>
#include <soc/dpp/SAND/Utils/sand_os_interface.h>

#include <soc/dpp/Petra/PB_TM/pb_framework.h>
#include <soc/dpp/Petra/PB_TM/pb_parser.h>
#include <soc/dpp/Petra/PB_TM/pb_pp_chip_regs.h>
#include <soc/dpp/Petra/PB_TM/pb_pp_reg_access.h>
#include <soc/dpp/Petra/PB_TM/pb_pp_chip_tbls.h>
#include <soc/dpp/Petra/PB_TM/pb_pp_tbl_access.h>
#include <soc/dpp/Petra/PB_TM/pb_pmf_low_level.h>

/* } */
/*************
 * DEFINES   *
 *************/
/* { */

#define SOC_PB_PARSER_PROG_MULTIPLIER                        (0x0010)
#define SOC_PB_PARSER_DONT_CARE                              (0x0000) /* When action is SOC_PB_PARSER_PROG_END we don't care abut the value of the macro select */

#define SOC_PB_PARSER_PROG_FIN                               (0x0000) /* Execute instruction's command and finish */
#define SOC_PB_PARSER_PROG_END                               (0x007f) /* End and do not execute the instruction's command */

#define SOC_PB_PARSER_MACRO_SEL_0                            (0x0000)
#define SOC_PB_PARSER_MACRO_SEL_1                            (0x0001)
#define SOC_PB_PARSER_MACRO_SEL_2                            (0x0002)
#define SOC_PB_PARSER_MACRO_SEL_ETH                          (0x0004)
#define SOC_PB_PARSER_MACRO_SEL_IPV4                         (0x0005)
#define SOC_PB_PARSER_MACRO_SEL_IPV6                         (0x0006)
#define SOC_PB_PARSER_MACRO_SEL_MPLS                         (0x0007)

#define SOC_PB_PARSER_PROG_INJECTED_JUMP                     (0x000c)

#define SOC_PB_PARSER_PROG_TM_BASE                           (0x0001)
#define SOC_PB_PARSER_PROG_TM_BASE_START                     (SOC_PB_PARSER_PROG_TM_BASE * SOC_PB_PARSER_PROG_MULTIPLIER)
#define SOC_PB_PARSER_PROG_TM_IS_BASE                        (0x0003)
#define SOC_PB_PARSER_PROG_TM_IS_BASE_START                  (SOC_PB_PARSER_PROG_TM_IS_BASE * SOC_PB_PARSER_PROG_MULTIPLIER)
#define SOC_PB_PARSER_PROG_TM_NO_IS_BASE                     (0x0005)
#define SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START               (SOC_PB_PARSER_PROG_TM_NO_IS_BASE * SOC_PB_PARSER_PROG_MULTIPLIER)
#define SOC_PB_PARSER_PROG_E_BASE                            (0x0007)
#define SOC_PB_PARSER_PROG_E_BASE_START                      (SOC_PB_PARSER_PROG_E_BASE * SOC_PB_PARSER_PROG_MULTIPLIER)
#define SOC_PB_PARSER_PROG_IPV4oE_BASE                       (0x000b)
#define SOC_PB_PARSER_PROG_IPV4oE_BASE_START                 (SOC_PB_PARSER_PROG_IPV4oE_BASE * SOC_PB_PARSER_PROG_MULTIPLIER)
#define SOC_PB_PARSER_PROG_MPLSoE_BASE                       (0x000f)
#define SOC_PB_PARSER_PROG_MPLSoE_BASE_START                 (SOC_PB_PARSER_PROG_MPLSoE_BASE * SOC_PB_PARSER_PROG_MULTIPLIER)
#define SOC_PB_PARSER_PROG_TRILLoE_BASE                      (0x0020)
#define SOC_PB_PARSER_PROG_TRILLoE_BASE_START                (SOC_PB_PARSER_PROG_TRILLoE_BASE * SOC_PB_PARSER_PROG_MULTIPLIER)
#define SOC_PB_PARSER_PROG_INJECTED_E_BASE                   (SOC_PB_PARSER_PROG_E_BASE + SOC_PB_PARSER_PROG_INJECTED_JUMP)
#define SOC_PB_PARSER_PROG_INJECTED_E_BASE_START             (SOC_PB_PARSER_PROG_INJECTED_E_BASE * SOC_PB_PARSER_PROG_MULTIPLIER)
#define SOC_PB_PARSER_PROG_INJECTED_IPV4oE_BASE              (SOC_PB_PARSER_PROG_IPV4oE_BASE + SOC_PB_PARSER_PROG_INJECTED_JUMP)


#define SOC_PB_PARSER_CUSTOM_MACRO_PROTO_1                   (0x0)
#define SOC_PB_PARSER_CUSTOM_MACRO_PROTO_2                   (0x1)
#define SOC_PB_PARSER_CUSTOM_MACRO_PROTO_3                   (0x2)

#define SOC_PB_PARSER_FLOW_ID_BITS                           (0x30000)

#define SOC_PB_PARSER_NOF_ETH_REPLICATIONS                   (2)

/* } */
/*************
 * MACROS    *
 *************/
/* { */

/* } */
/*************
 * TYPE DEFS *
 *************/
/* { */

typedef struct
{
  uint32 instruction_addr;
  uint32 macro_sel;
  uint32 next_addr_base;
  uint32 packet_format_code;
  uint32 parser_pmf_profile;
}SOC_PB_PARSERR_INFO;
  
/* } */
/*************
 * GLOBALS   *
 *************/
/* { */

/* $Id: soc_pb_parser.c,v 1.7 Broadcom SDK $
 * Parser-Program-Memory map:
 * 0x0000 - 0x0004    Program entry points, indexed by PP-Context - Soc_pb_parserr_info
 * 0x0005 - 0x000f    Unused
 * 0x0010 - 0x002f    TM program, after checking for ingress shaping - Soc_pb_parserr_info_tm
 * 0x0030 - 0x004f    TM program, with ingress shaping, after checking for PPH - Soc_pb_parserr_info_tm
 * 0x0050 - 0x006f    TM program, no ingress shaping, after checking for PPH - Soc_pb_parserr_info_tm
 * 0x0070 - 0x00af    Ethernet program - Soc_pb_parserr_info_eth (1st iteration)
 * 0x00b0 - 0x00ef    IPv4oE program - Soc_pb_parserr_info_eth (1st iteration)
 * 0x00f0 - 0x010d    MPLSoE program - Soc_pb_parserr_info_eth (1st iteration)
 * 0x0130 - 0x021e    Ethernet program - Soc_pb_parserr_info_eth (2nd iteration, injected)
 * 0x0170 - 0x01af    IPv4oE program - Soc_pb_parserr_info_eth (2nd iteration, injected)
 * 0x01B0 - 0x01cd    MPLSoE program - Soc_pb_parserr_info_eth (2nd iteration, injected)
 * 0x0200 - 0x023f    TRILLoE program
 * 0x010e - 0x07ff    Unused
 */

static SOC_PB_PARSERR_INFO
  Soc_pb_parserr_info[] =
{
  {SOC_PB_PARSER_PROG_RAW_ADDR_START              , SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_RAW                        , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_RAW}, /* RAW */
  {SOC_PB_PARSER_PROG_ETH_ADDR_START              , SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_E_BASE       , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE}, /* ETH */
  {SOC_PB_PARSER_PROG_TM_ADDR_START               , SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE}, /* TM, ingress shaping off by default */
  {SOC_PB_PARSER_PROG_FTMH_ADDR_START             , SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_FTMH                       , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_FTMH}, /* FTMH  */
  {SOC_PB_PARSER_PROG_INJECTED_EXT_KEY_ADDR_START , SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_INJECTED_E_BASE, SOC_PB_PARSER_DONT_CARE                    , SOC_PB_PARSER_DONT_CARE}, /* ETH with In-LIF */
};
static SOC_PB_PARSERR_INFO
  Soc_pb_parserr_info_tm[] =
{
  /* TM, check for ingress shaping { */
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0000, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0001, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0002, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0003, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_IS_BASE   , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE}, /* Ingress shaping */
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0004, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0005, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0006, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0007, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0008, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0009, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x000a, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x000b, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x000c, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x000d, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x000e, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x000f, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0010, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0011, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0012, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0013, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0014, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0015, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0016, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0017, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0018, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x0019, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x001a, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x001b, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x001c, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x001d, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x001e, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_TM_BASE_START       + 0x001f, SOC_PB_PARSER_MACRO_SEL_1   , SOC_PB_PARSER_PROG_TM_NO_IS_BASE, SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  /* } TM, check for ingress shaping */
  /* TM with ingress shaping { */
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0000, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0001, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0002, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0003, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0004, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0005, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0006, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS_PPH                  , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS_PPH_PRESENT}, /* Ingress shaping, PPH present */
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0007, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0008, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0009, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x000a, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x000b, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x000c, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x000d, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x000e, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x000f, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0010, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0011, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0012, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0013, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0014, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0015, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0016, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0017, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0018, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x0019, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x001a, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x001b, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x001c, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x001d, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x001e, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  {SOC_PB_PARSER_PROG_TM_IS_BASE_START    + 0x001f, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_IS                      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_IS},
  /* } TM with ingress shaping */
  /* TM, no ingress shaping { */
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0000, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0001, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0002, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0003, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0004, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0005, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0006, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM_PPH                     , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_PPH_PRESENT}, /* PPH present */
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0007, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0008, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0009, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x000a, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x000b, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x000c, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x000d, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x000e, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x000f, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0010, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0011, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0012, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0013, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0014, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0015, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0016, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0017, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0018, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x0019, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x001a, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x001b, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x001c, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x001d, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x001e, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  {SOC_PB_PARSER_PROG_TM_NO_IS_BASE_START + 0x001f, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PFC_TM                         , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_TM_REGULAR},
  /* } TM, no ingress shaping */
};
static SOC_PB_PARSERR_INFO
  Soc_pb_parserr_info_eth[] =
{
  /* ETH { */
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0000, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0001, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0002, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0003, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0004, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0005, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0006, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0007, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0008, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0009, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x000a, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x000b, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x000c, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x000d, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x000e, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x000f, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0010, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0011, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0012, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0013, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0014, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0015, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0016, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0017, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0018, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0019, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x001a, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x001b, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x001c, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x001d, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x001e, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x001f, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0020, SOC_PB_PARSER_MACRO_SEL_MPLS, SOC_PB_PARSER_PROG_MPLSoE_BASE  , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0021, SOC_PB_PARSER_MACRO_SEL_MPLS, SOC_PB_PARSER_PROG_MPLSoE_BASE  , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0022, SOC_PB_PARSER_MACRO_SEL_MPLS, SOC_PB_PARSER_PROG_MPLSoE_BASE  , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0023, SOC_PB_PARSER_MACRO_SEL_MPLS, SOC_PB_PARSER_PROG_MPLSoE_BASE  , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0024, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_ETH       , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0025, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_ETH       , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0026, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_ETH       , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0027, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_ETH       , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0028, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0029, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x002a, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x002b, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x002c, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x002d, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x002e, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x002f, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0030, SOC_PB_PARSER_MACRO_SEL_IPV4, SOC_PB_PARSER_PROG_IPV4oE_BASE  , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0031, SOC_PB_PARSER_MACRO_SEL_IPV4, SOC_PB_PARSER_PROG_IPV4oE_BASE  , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0032, SOC_PB_PARSER_MACRO_SEL_IPV4, SOC_PB_PARSER_PROG_IPV4oE_BASE  , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0033, SOC_PB_PARSER_MACRO_SEL_IPV4, SOC_PB_PARSER_PROG_IPV4oE_BASE  , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0034, SOC_PB_PARSER_MACRO_SEL_IPV6, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV6_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0035, SOC_PB_PARSER_MACRO_SEL_IPV6, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV6_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0036, SOC_PB_PARSER_MACRO_SEL_IPV6, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV6_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0037, SOC_PB_PARSER_MACRO_SEL_IPV6, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV6_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0038, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x0039, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x003a, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x003b, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH           , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x003c, SOC_PB_PARSER_MACRO_SEL_2   , SOC_PB_PARSER_PROG_TRILLoE_BASE , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x003d, SOC_PB_PARSER_MACRO_SEL_2   , SOC_PB_PARSER_PROG_TRILLoE_BASE , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x003e, SOC_PB_PARSER_MACRO_SEL_2   , SOC_PB_PARSER_PROG_TRILLoE_BASE , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},
  {SOC_PB_PARSER_PROG_E_BASE_START        + 0x003f, SOC_PB_PARSER_MACRO_SEL_2   , SOC_PB_PARSER_PROG_TRILLoE_BASE , SOC_PB_PARSER_DONT_CARE                      , SOC_PB_PARSER_DONT_CARE},

  /* ETH { */
  /* TRILLoE */
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0000, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0001, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0002, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0003, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0004, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0005, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0006, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0007, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0008, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0009, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x000a, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x000b, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x000c, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x000d, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x000e, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x000f, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0010, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0011, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0012, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0013, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0014, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0015, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0016, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0017, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0018, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0019, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x001a, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x001b, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x001c, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x001d, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x001e, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x001f, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0020, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0021, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0022, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0023, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0024, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0025, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0026, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0027, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0028, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0029, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x002a, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x002b, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x002c, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x002d, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x002e, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x002f, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0030, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0031, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0032, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0033, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0034, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0035, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0036, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0037, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0038, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x0039, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x003a, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x003b, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x003c, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x003d, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x003e, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_TRILLoE_BASE_START        + 0x003f, SOC_PB_PARSER_MACRO_SEL_ETH , SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_ETH_TRILL_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},



  /* } ETH */
  /* IPv4oE { */
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0000, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0001, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0002, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0003, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0004, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0005, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0006, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0007, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0008, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0009, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x000a, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x000b, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x000c, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x000d, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x000e, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x000f, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0010, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0011, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0012, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0013, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0014, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0015, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0016, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0017, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0018, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0019, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x001a, SOC_PB_PARSER_MACRO_SEL_IPV4, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_IPV4_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x001b, SOC_PB_PARSER_MACRO_SEL_IPV4, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_IPV4_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x001c, SOC_PB_PARSER_MACRO_SEL_IPV6, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV6_IPV4_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x001d, SOC_PB_PARSER_MACRO_SEL_IPV6, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV6_IPV4_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x001e, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x001f, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0020, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0021, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0022, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0023, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0024, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0025, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0026, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0027, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0028, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0029, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x002a, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x002b, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x002c, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x002d, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x002e, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x002f, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0030, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0031, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0032, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0033, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0034, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0035, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0036, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0037, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0038, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x0039, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x003a, SOC_PB_PARSER_MACRO_SEL_IPV4, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_IPV4_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x003b, SOC_PB_PARSER_MACRO_SEL_IPV4, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_IPV4_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x003c, SOC_PB_PARSER_MACRO_SEL_IPV6, SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV6_IPV4_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x003d, SOC_PB_PARSER_MACRO_SEL_IPV6, SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV6_IPV4_ETH , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x003e, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_IPV4oE_BASE_START   + 0x003f, SOC_PB_PARSER_DONT_CARE     , SOC_PB_PARSER_PROG_END          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_IPV4_ETH      , SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  /* } IPv4oE */
  /* MPLSoE { */
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0000, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS1_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0001, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS1_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0002, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS2_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0003, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS2_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0004, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS3_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0005, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS3_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0008, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS1_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0009, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS1_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x000a, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS2_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x000b, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS2_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x000c, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS3_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x000d, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS3_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0010, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS1_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0011, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS1_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0012, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS2_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0013, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS2_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0014, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS3_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0015, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS3_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0018, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS1_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x0019, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS1_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x001a, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS2_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x001b, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS2_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x001c, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS3_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  {SOC_PB_PARSER_PROG_MPLSoE_BASE_START   + 0x001d, SOC_PB_PARSER_DONT_CARE, SOC_PB_PARSER_PROG_FIN          , SOC_PB_PARSER_PKT_HDR_STK_TYPE_MPLS3_ETH, SOC_PB_PMF_PGM_SEL_PARSER_PROFILE_PP},
  /* } MPLSoE */
};

/* } */
/*************
 * FUNCTIONS *
 *************/
/* { */

uint32
  soc_pb_parser_init(
    SOC_SAND_IN  int                                 unit
  )
{
  uint32
    res = SOC_SAND_OK,
    idx,
    instr_addr,
    table_line,
    eth_rep_ndx;
  SOC_PB_PP_REGS
    *regs = soc_pb_pp_regs();
  SOC_PB_PP_IHP_PARSER_PROGRAM1_TBL_DATA
    ihp_parser_program1_tbl_data;
  SOC_PB_PP_IHP_PARSER_PROGRAM2_TBL_DATA
    ihp_parser_program2_tbl_data;
  SOC_PB_PP_IHP_PACKET_FORMAT_TABLE_TBL_DATA
    ihp_packet_format_table_tbl_data;
  SOC_PB_PP_IHP_PARSER_CUSTOM_MACRO_PARAMETERS_TBL_DATA
    ihp_parser_custom_macro_parameters_tbl_data;
  SOC_PB_PP_IHP_PARSER_CUSTOM_MACRO_PROTOCOLS_TBL_DATA
    ihp_parser_custom_macro_protocols_tbl_data;

  SOC_SAND_INIT_ERROR_DEFINITIONS(SOC_PB_PARSER_INIT);

  SOC_PB_PP_FLD_SET(regs->ihp.ihp_enablers_reg.enable_data_path, 0x1, 10, exit);
  SOC_PB_PP_FLD_SET(regs->ihp.ihp_enablers_reg.max_header_stack, 0x5, 10, exit);

  idx = 0;
  for (table_line = 0; table_line < (sizeof(Soc_pb_parserr_info) + sizeof(Soc_pb_parserr_info_tm)) / sizeof(SOC_PB_PARSERR_INFO); ++table_line)
  {
   if (table_line == sizeof(Soc_pb_parserr_info) / sizeof(SOC_PB_PARSERR_INFO))
    {
      idx = 0;
    }

    /*
     *	First instructions
     */
    if (table_line < sizeof(Soc_pb_parserr_info) / sizeof(SOC_PB_PARSERR_INFO))
    {
      instr_addr = Soc_pb_parserr_info[idx].instruction_addr;
      ihp_parser_program1_tbl_data.macro_sel = Soc_pb_parserr_info[idx].macro_sel;
      ihp_parser_program1_tbl_data.next_addr_base = Soc_pb_parserr_info[idx].next_addr_base;
      ihp_parser_program2_tbl_data.macro_sel = Soc_pb_parserr_info[idx].macro_sel;
      ihp_parser_program2_tbl_data.next_addr_base = Soc_pb_parserr_info[idx].next_addr_base;
      ihp_packet_format_table_tbl_data.key_program_profile = (idx != SOC_PB_PARSER_PROG_ETH_ADDR_START)?SOC_PB_PARSER_NON_ETH_KEY_PROGRAM_PROFILE:SOC_PB_PARSER_DEFAULT_KEY_PROGRAM_PROFILE;
      ihp_packet_format_table_tbl_data.packet_format_code = Soc_pb_parserr_info[idx].packet_format_code;
      ihp_packet_format_table_tbl_data.parser_pmf_profile = Soc_pb_parserr_info[idx].parser_pmf_profile;

    }
    else
    {
      /*
       *	TM
       */
      instr_addr = Soc_pb_parserr_info_tm[idx].instruction_addr;
      ihp_parser_program1_tbl_data.macro_sel = Soc_pb_parserr_info_tm[idx].macro_sel;
      ihp_parser_program1_tbl_data.next_addr_base = Soc_pb_parserr_info_tm[idx].next_addr_base;
      ihp_parser_program2_tbl_data.macro_sel = Soc_pb_parserr_info_tm[idx].macro_sel;
      ihp_parser_program2_tbl_data.next_addr_base = Soc_pb_parserr_info_tm[idx].next_addr_base;
      ihp_packet_format_table_tbl_data.key_program_profile = SOC_PB_PARSER_NON_ETH_KEY_PROGRAM_PROFILE;
      ihp_packet_format_table_tbl_data.packet_format_code = Soc_pb_parserr_info_tm[idx].packet_format_code;
      ihp_packet_format_table_tbl_data.parser_pmf_profile = Soc_pb_parserr_info_tm[idx].parser_pmf_profile;
    }

    res = soc_pb_pp_ihp_parser_program1_tbl_set_unsafe(
            unit,
            instr_addr,
            &ihp_parser_program1_tbl_data
          );
    SOC_SAND_CHECK_FUNC_RESULT(res, 10, exit);

    res = soc_pb_pp_ihp_parser_program2_tbl_set_unsafe(
            unit,
            instr_addr,
            &ihp_parser_program2_tbl_data
          );
    SOC_SAND_CHECK_FUNC_RESULT(res, 20, exit);

    res = soc_pb_pp_ihp_packet_format_table_tbl_set_unsafe(
            unit,
            instr_addr,
            &ihp_packet_format_table_tbl_data
          );
    SOC_SAND_CHECK_FUNC_RESULT(res, 30, exit);

    idx ++;
  }

  /*
   * Ethernet replications
   */
  idx = 0;
  for (eth_rep_ndx = 0; eth_rep_ndx < SOC_PB_PARSER_NOF_ETH_REPLICATIONS; ++eth_rep_ndx)
  {
    if (table_line == sizeof(Soc_pb_parserr_info_eth) / sizeof(SOC_PB_PARSERR_INFO))
    {
      idx = 0;
    }
    for (table_line = 0; table_line < sizeof(Soc_pb_parserr_info_eth) / sizeof(SOC_PB_PARSERR_INFO); ++table_line)
    {
      /*
       *	Eth - 2 replications
       */
      instr_addr = Soc_pb_parserr_info_eth[idx].instruction_addr
        + (eth_rep_ndx * (SOC_PB_PARSER_PROG_INJECTED_E_BASE_START - SOC_PB_PARSER_PROG_E_BASE_START));
      ihp_parser_program1_tbl_data.macro_sel = Soc_pb_parserr_info_eth[idx].macro_sel;

      if (
          (Soc_pb_parserr_info_eth[idx].next_addr_base == SOC_PB_PARSER_PROG_MPLSoE_BASE)
          || (Soc_pb_parserr_info_eth[idx].next_addr_base == SOC_PB_PARSER_PROG_IPV4oE_BASE)
         )
      {
        ihp_parser_program1_tbl_data.next_addr_base = Soc_pb_parserr_info_eth[idx].next_addr_base
          + (eth_rep_ndx * (SOC_PB_PARSER_PROG_INJECTED_IPV4oE_BASE - SOC_PB_PARSER_PROG_IPV4oE_BASE));
      }
      else
      {
        ihp_parser_program1_tbl_data.next_addr_base = Soc_pb_parserr_info_eth[idx].next_addr_base;
      }

      ihp_parser_program2_tbl_data.macro_sel = Soc_pb_parserr_info_eth[idx].macro_sel;
      ihp_parser_program2_tbl_data.next_addr_base = Soc_pb_parserr_info_eth[idx].next_addr_base;
      if (eth_rep_ndx % 2 == 0)
      {
        ihp_packet_format_table_tbl_data.key_program_profile = SOC_PB_PARSER_DEFAULT_KEY_PROGRAM_PROFILE;
      }
      else
      {
        ihp_packet_format_table_tbl_data.key_program_profile = SOC_PB_PARSER_INJECTED_KEY_PROGRAM_PROFILE;
      }

      ihp_packet_format_table_tbl_data.packet_format_code = Soc_pb_parserr_info_eth[idx].packet_format_code;
      ihp_packet_format_table_tbl_data.parser_pmf_profile = Soc_pb_parserr_info_eth[idx].parser_pmf_profile;

      res = soc_pb_pp_ihp_parser_program1_tbl_set_unsafe(
              unit,
              instr_addr,
              &ihp_parser_program1_tbl_data
           );
      SOC_SAND_CHECK_FUNC_RESULT(res, 40, exit);

      res = soc_pb_pp_ihp_parser_program2_tbl_set_unsafe(
              unit,
              instr_addr,
              &ihp_parser_program2_tbl_data
            );
      SOC_SAND_CHECK_FUNC_RESULT(res, 50, exit);


      res = soc_pb_pp_ihp_packet_format_table_tbl_set_unsafe(
              unit,
              instr_addr,
              &ihp_packet_format_table_tbl_data
            );
      SOC_SAND_CHECK_FUNC_RESULT(res, 60, exit);

      idx++;
    }
  }



  /*
   *  Configure the a macro to identify whether the destination is an ingress shaping queue or not
   *  (macro 0). This is done by comparing the ITMH destination (including the destination type) to
   *  to custom protocols 1 and 2, which are set according to the ingress shaping queue range.
   */
  ihp_parser_custom_macro_parameters_tbl_data.cstm_shift_a = 4;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_shift_b = 0;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_comparator_mask = 0x3; /* Use protocols 1 and 2 */
  ihp_parser_custom_macro_parameters_tbl_data.cstm_comparator_mode = 0x3; /* Compare 32 bits */
  ihp_parser_custom_macro_parameters_tbl_data.cstm_condition_select = 3; /* Between protocol 1 and 2 */
  ihp_parser_custom_macro_parameters_tbl_data.cstm_mask_right = 0;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_mask_left = 14;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_word_select = 0;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_shift_sel = 0;

  res = soc_pb_pp_ihp_parser_custom_macro_parameters_tbl_set_unsafe(
          unit,
          SOC_PB_PARSER_MACRO_SEL_0,
          &ihp_parser_custom_macro_parameters_tbl_data
        );
  SOC_SAND_CHECK_FUNC_RESULT(res, 50, exit);

  /*
   *	Configure the Parser Custom Macro to identify if PPH is present (Macro 1)
   *  if PPH-Present set in the ITMH, it goes to TM parser instruction 6
   */
  ihp_parser_custom_macro_parameters_tbl_data.cstm_shift_b = 4;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_shift_a = 4;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_comparator_mask = 0x4; /* Use protocol 3 */
  ihp_parser_custom_macro_parameters_tbl_data.cstm_comparator_mode = 0;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_condition_select = 0;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_mask_right = 30; /* Need only bit 30 of ITMH */
  ihp_parser_custom_macro_parameters_tbl_data.cstm_mask_left = 1;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_word_select = 0;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_shift_sel = 0;

  res = soc_pb_pp_ihp_parser_custom_macro_parameters_tbl_set_unsafe(
          unit,
          SOC_PB_PARSER_MACRO_SEL_1,
          &ihp_parser_custom_macro_parameters_tbl_data
        );
  SOC_SAND_CHECK_FUNC_RESULT(res, 80, exit);

  /*
   *  Configure the a macro to identify TRILL present
   *  (macro 2). only the shift matters.
   */
  ihp_parser_custom_macro_parameters_tbl_data.cstm_shift_a = 6;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_shift_b = 6;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_comparator_mask = 0; /* Use protocols 1 and 2 */
  ihp_parser_custom_macro_parameters_tbl_data.cstm_comparator_mode = 0; /* Compare 32 bits */
  ihp_parser_custom_macro_parameters_tbl_data.cstm_condition_select = 0; /* Between protocol 1 and 2 */
  ihp_parser_custom_macro_parameters_tbl_data.cstm_mask_right = 0;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_mask_left = 0;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_word_select = 0;
  ihp_parser_custom_macro_parameters_tbl_data.cstm_shift_sel = 0;

  res = soc_pb_pp_ihp_parser_custom_macro_parameters_tbl_set_unsafe(
          unit,
          SOC_PB_PARSER_MACRO_SEL_2,
          &ihp_parser_custom_macro_parameters_tbl_data
        );
  SOC_SAND_CHECK_FUNC_RESULT(res, 50, exit);

  ihp_parser_custom_macro_protocols_tbl_data.cstm_protocol = 1<<30;
  res = soc_pb_pp_ihp_parser_custom_macro_protocols_tbl_set_unsafe(
          unit,
          SOC_PB_PARSER_CUSTOM_MACRO_PROTO_3,
          &ihp_parser_custom_macro_protocols_tbl_data
        );
  SOC_SAND_CHECK_FUNC_RESULT(res, 90, exit);

exit:
  SOC_SAND_EXIT_AND_SEND_ERROR("error in soc_pb_parser_init()", 0, 0);
}

uint32
  soc_pb_parser_ingress_shape_state_set(
    SOC_SAND_IN int                                 unit,
    SOC_SAND_IN uint8                                 enable,
    SOC_SAND_IN uint32                                  q_low,
    SOC_SAND_IN uint32                                  q_high
  )
{
  uint32
    res = SOC_SAND_OK;
  SOC_PB_PP_IHP_PARSER_PROGRAM1_TBL_DATA
    ihp_parser_program1_tbl_data;
  SOC_PB_PP_IHP_PARSER_PROGRAM2_TBL_DATA
    ihp_parser_program2_tbl_data;
  SOC_PB_PP_IHP_PARSER_CUSTOM_MACRO_PROTOCOLS_TBL_DATA
    custom_macro_protocols_tbl_data;

  SOC_SAND_INIT_ERROR_DEFINITIONS(SOC_PB_PARSER_INGRESS_SHAPE_STATE_SET);

  /*
   * Change the program entry point according to the new state
   */
  if (enable)
  {
    ihp_parser_program1_tbl_data.macro_sel = SOC_PB_PARSER_MACRO_SEL_0;
    ihp_parser_program1_tbl_data.next_addr_base = SOC_PB_PARSER_PROG_TM_BASE;
    ihp_parser_program2_tbl_data.macro_sel = SOC_PB_PARSER_MACRO_SEL_0;
    ihp_parser_program2_tbl_data.next_addr_base = SOC_PB_PARSER_PROG_TM_BASE;
  }
  else
  {
    ihp_parser_program1_tbl_data.macro_sel = SOC_PB_PARSER_MACRO_SEL_1;
    ihp_parser_program1_tbl_data.next_addr_base = SOC_PB_PARSER_PROG_TM_NO_IS_BASE;
    ihp_parser_program2_tbl_data.macro_sel = SOC_PB_PARSER_MACRO_SEL_1;
    ihp_parser_program2_tbl_data.next_addr_base = SOC_PB_PARSER_PROG_TM_NO_IS_BASE;
  }

  res = soc_pb_pp_ihp_parser_program1_tbl_set_unsafe(
          unit,
          SOC_PB_PARSER_PROG_TM_ADDR_START,
          &ihp_parser_program1_tbl_data
        );
  SOC_SAND_CHECK_FUNC_RESULT(res, 10, exit);

  res = soc_pb_pp_ihp_parser_program2_tbl_set_unsafe(
          unit,
          SOC_PB_PARSER_PROG_TM_ADDR_START,
          &ihp_parser_program2_tbl_data
        );
  SOC_SAND_CHECK_FUNC_RESULT(res, 20, exit);

  /*
   * Write the encoded ingress shaping queue range to the custom macro protocols table
   */
  custom_macro_protocols_tbl_data.cstm_protocol = (SOC_PB_PARSER_FLOW_ID_BITS | q_low) - 1;
  res = soc_pb_pp_ihp_parser_custom_macro_protocols_tbl_set_unsafe(
          unit,
          SOC_PB_PARSER_CUSTOM_MACRO_PROTO_1,
          &custom_macro_protocols_tbl_data
        );
  SOC_SAND_CHECK_FUNC_RESULT(res, 30, exit);

  custom_macro_protocols_tbl_data.cstm_protocol = (SOC_PB_PARSER_FLOW_ID_BITS | q_high) + 1;
  res = soc_pb_pp_ihp_parser_custom_macro_protocols_tbl_set_unsafe(
          unit,
          SOC_PB_PARSER_CUSTOM_MACRO_PROTO_2,
          &custom_macro_protocols_tbl_data
        );
  SOC_SAND_CHECK_FUNC_RESULT(res, 40, exit);

exit:
  SOC_SAND_EXIT_AND_SEND_ERROR("error in soc_pb_parser_ingress_shaping_enable_set()", 0, 0);
}

uint32
  soc_pb_parser_nof_bytes_to_remove_set(
    SOC_SAND_IN int      unit,
    SOC_SAND_IN uint32      pp_port_ndx,
    SOC_SAND_IN uint32      nof_bytes_to_skip
  )
{
  uint32
    res = SOC_SAND_OK;
  SOC_PB_PP_IHP_PP_PORT_INFO_TBL_DATA
    pp_port_info_tbl_data;

  SOC_SAND_INIT_ERROR_DEFINITIONS(SOC_PB_PARSER_FAT_PIPE_SET);

  res = soc_pb_pp_ihp_pp_port_info_tbl_get_unsafe(
          unit,
          pp_port_ndx,
          &pp_port_info_tbl_data
        );
  SOC_SAND_CHECK_FUNC_RESULT(res, 9, exit);

  pp_port_info_tbl_data.outer_header_start = nof_bytes_to_skip;

  res = soc_pb_pp_ihp_pp_port_info_tbl_set_unsafe(
          unit,
          pp_port_ndx,
          &pp_port_info_tbl_data
        );
  SOC_SAND_CHECK_FUNC_RESULT(res, 10, exit);

exit:
  SOC_SAND_EXIT_AND_SEND_ERROR("error in soc_pb_parser_nof_bytes_to_remove_set()", 0, 0);
}
/* } */

#include <soc/dpp/SAND/Utils/sand_footer.h>

