#
# $Id: Makefile,v 1.4 Exp $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/diag/dnx/stif

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxstif

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend



