#
# $Id$
# $Copyright: (c) 2017 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dfe subdirectory
#

LOCALDIR = src/soc/sand

include ${SDK}/make/Make.config

#macros used in this library need C99 support
CFGFLAGS += -std=gnu99 -D_GNU_SOURCE

lib = libsoc_sand

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
