# $Id: $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM MONTEREY driver Library
#

LOCALDIR = src/bcm/esw/monterey

include ${SDK}/make/Make.config

lib = libmonterey

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

