#
# $Id:$
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC swstate infrastructure subdirectory
#
LOCALDIR = src/shared/swstate/infrastructure

# enable optimization & disable debugging for this lib
DEBUG_OPTIMIZE = TRUE
DEBUG_CFLAGS += -g0
include ${SDK}/make/Make.config

lib = libshared_swstate_infrastructure

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
