# $Id: Makefile,v 1.1.6.2 2012/12/13 07:04:46 kirankum Exp $
# $Copyright: (c) 2011 Broadcom Corp.
# All Rights Reserved.$

LOCALDIR = src/soc/kbp/nlm3/nlmdevmgr

include ${SDK}/make/Make.config

lib = libsoc_kbp_nlm3_dm

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
