/*
 * $Id: interrupt_handler.c,v 1.17 Broadcom SDK $
 *
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 */


#ifdef _ERR_MSG_MODULE_NAME
#error "_ERR_MSG_MODULE_NAME redefined"
#endif
#define _ERR_MSG_MODULE_NAME BSL_BCM_INTR

/* 
 *  include  
 */ 
#include <sal/core/time.h>

#include <soc/dpp/ARAD/arad_interrupts.h>
#include <soc/intr.h>
#include <soc/drv.h>
#include <soc/dpp/ARAD/arad_sw_db.h>

#include <soc/dpp/drv.h>

#include <bcm/error.h>
#include <bcm/debug.h>
#include <bcm/switch.h>

#include <bcm_int/common/debug.h>

#include <appl/diag/system.h>

#include <appl/dpp/interrupts/interrupt_handler.h>
#include <appl/dpp/interrupts/interrupt_handler_cb_func.h>
#include <appl/dpp/interrupts/interrupt_handler_corr_act_func.h>

#include <appl/dcmn/interrupts/interrupt_handler.h>


arad_interrupt_type arad_int_disable_on_init[] = {
    ARAD_INT_LAST
};


arad_interrupt_type arad_int_active_on_init[] = {
/*
 * List of interrupts that are vectors pointing to other interrupt registers
 */
    ARAD_INT_FDR_INTREG1,
    ARAD_INT_FDR_INTREG2,
    ARAD_INT_FDR_INTREG3,
    ARAD_INT_FMAC_INTREG1,
    ARAD_INT_FMAC_INTREG2,
    ARAD_INT_FMAC_INTREG3,
    ARAD_INT_FMAC_INTREG4,
    ARAD_INT_FMAC_INTREG5,
    ARAD_INT_FMAC_INTREG6,
    ARAD_INT_FMAC_INTREG7,
    ARAD_INT_FMAC_INTREG8,
    ARAD_INT_FMAC_INTREG9,
    ARAD_INT_FSRD_INTREG0,
    ARAD_INT_FSRD_INTREG1,
    ARAD_INT_FSRD_INTREG2,
    ARAD_INT_NBI_ECCPARITYINT,
    ARAD_INT_NBI_STATINT,
    ARAD_INT_NBI_LINKSTATUSCHANGEINT,
    ARAD_INT_NBI_ILKNINT,
    ARAD_INT_NBI_STATCNT75P,
    ARAD_INT_NBI_NBITHROWNBURSTSCOUNTERS0_75PINTERRUPT,
    ARAD_INT_EGQ_ERPPDISCARDINTVEC,
    ARAD_INT_EGQ_PKTREASINTVEC,
    ARAD_INT_EGQ_ERPPDISCARDINTVEC2,
    ARAD_INT_EGQ_ERRORECC,
    ARAD_INT_EPNI_ERRORECC,
    ARAD_INT_EPNI_PPINTVEC,
    ARAD_INT_EPNI_ESEMINTERRUPTONE,
    ARAD_INT_CRPS_SRCINVLIDACCESS,
    ARAD_INT_CRPS_PARERRINTERRUPT,
    ARAD_INT_IPT_ECCERRINTERRUPT,
    ARAD_INT_IQM_ECCINTRERR,
    ARAD_INT_IRE_ERRORECC,
    ARAD_INT_IDR_ERRORECC,
    ARAD_INT_IDR_ERRORREASSEMBLY,
    ARAD_INT_IRR_ERRORECC,
    ARAD_INT_IHP_MACTINTERRUPTONE,
    ARAD_INT_IHP_ISAINTERRUPTONE,
    ARAD_INT_IHP_ISBINTERRUPTONE,
    ARAD_INT_IHP_MACTINTERRUPTTWO,
    ARAD_INT_IHB_OEMAINTERRUPTONE,
    ARAD_INT_IHB_OEMBINTERRUPTONE,
    ARAD_INT_SCH_ECCERRORFIXED,
    ARAD_INT_SCH_ECCERROR,
    ARAD_INT_SCH_PARITYERROR,
    ARAD_INT_OAMP_RMAPEMINTERRUPTONE,
    ARAD_INT_OAMP_ERRECC,
    ARAD_INT_MMU_ERRORECC,
    ARAD_INT_OLP_ERRORECC,
/*
 * Parity & ECC error interrupts
 */
    ARAD_INT_RTP_LINKMASKCHANGE,
    ARAD_INT_CFC_PARITYERRINT,
    ARAD_INT_CRPS_PARERRINTERRUPT,
    ARAD_INT_CRPS_PARITYERRINT,
    ARAD_INT_EGQ_PARITYERRINT,
    ARAD_INT_EGQ_DBFECC_1BERRINT,
    ARAD_INT_EGQ_DBFECC_2BERRINT,
    ARAD_INT_EGQ_ECC_1BERRINT,
    ARAD_INT_EGQ_ECC_2BERRINT,
    ARAD_INT_EPNI_ECC_1BERRINT,
    ARAD_INT_EPNI_ECC_2BERRINT,
    ARAD_INT_EPNI_PARITYERRINT,
    ARAD_INT_FCR_ECC_1BERRINT,
    ARAD_INT_FCR_ECC_2BERRINT,
    ARAD_INT_FDR_PRMECC_1BERRINT,
    ARAD_INT_FDR_PRMECC_2BERRINT,
    ARAD_INT_FDR_SECECC_1BERRINT,
    ARAD_INT_FDR_SECECC_2BERRINT,
    ARAD_INT_FDT_ECC_1BERRINT,
    ARAD_INT_FDT_ECC_2BERRINT,
    ARAD_INT_FDT_PARITYERRINT,
    ARAD_INT_FMAC_ECC_1BERRINT,
    ARAD_INT_FMAC_ECC_2BERRINT,
    ARAD_INT_IDR_ECC_1BERRINT,
    ARAD_INT_IDR_ECC_2BERRINT,
    ARAD_INT_IDR_PARITYERRINT,
    ARAD_INT_IHB_ECC_1BERRINT,
    ARAD_INT_IHB_ECC_2BERRINT,
    ARAD_INT_IHB_PARITYERRINT,
    ARAD_INT_IHP_ECC_1BERRINT,
    ARAD_INT_IHP_ECC_2BERRINT,
    ARAD_INT_IHP_PARITYERRINT,
    ARAD_INT_IPS_ECC_1BERRINT,
    ARAD_INT_IPS_ECC_2BERRINT,
    ARAD_INT_IPS_PARITYERRINT,
    ARAD_INT_IPT_ECC_1BERRINT,
    ARAD_INT_IPT_ECC_2BERRINT,
    ARAD_INT_IPT_PARITYERRINT,
    ARAD_INT_IQM_ECC_1BERRINT,
    ARAD_INT_IQM_ECC_2BERRINT,
    ARAD_INT_IQM_PARITYERRINT,
    ARAD_INT_IRE_ECC_1BERRINT,
    ARAD_INT_IRE_ECC_2BERRINT,
    ARAD_INT_IRE_PARITYERRINT,
    ARAD_INT_IRR_ECC_1BERRINT,
    ARAD_INT_IRR_ECC_2BERRINT,
    ARAD_INT_IRR_PARITYERRINT,
    ARAD_INT_MMU_ECC_1BERRINT,
    ARAD_INT_MMU_ECC_2BERRINT,
    ARAD_INT_NBI_ECC_1BERRINT,
    ARAD_INT_NBI_ECC_2BERRINT,
    ARAD_INT_NBI_PARITYERRINT,
    ARAD_INT_NBI_ILKNRXPARITYERRINT,
    ARAD_INT_NBI_ILKNTXPARITYERRINT,
    ARAD_INT_OAMP_ECC_1BERRINT,
    ARAD_INT_OAMP_ECC_2BERRINT,
    ARAD_INT_OAMP_PARITYERRINT,
    ARAD_INT_OLP_ECC_1BERRINT,
    ARAD_INT_OLP_ECC_2BERRINT,
    ARAD_INT_OLP_PARITYERRINT,
    ARAD_INT_SCH_DCDECCERRORFIXED,
    ARAD_INT_SCH_DHDECCERRORFIXED,
    ARAD_INT_SCH_FDMDECCERRORFIXED,
    ARAD_INT_SCH_FLHCLECCERRORFIXED,
    ARAD_INT_SCH_FLHFQECCERRORFIXED,
    ARAD_INT_SCH_FLHHRECCERRORFIXED,
    ARAD_INT_SCH_FLTCLECCERRORFIXED,
    ARAD_INT_SCH_FLTFQECCERRORFIXED,
    ARAD_INT_SCH_FLTHRECCERRORFIXED,
    ARAD_INT_SCH_FSMECCERRORFIXED,
    ARAD_INT_SCH_SHDDECCERRORFIXED,
    ARAD_INT_SCH_DCDECCERROR,
    ARAD_INT_SCH_DHDECCERROR,
    ARAD_INT_SCH_FDMDECCERROR,
    ARAD_INT_SCH_FLHCLECCERROR,
    ARAD_INT_SCH_FLHFQECCERROR,
    ARAD_INT_SCH_FLHHRECCERROR,
    ARAD_INT_SCH_FLTCLECCERROR,
    ARAD_INT_SCH_FLTFQECCERROR,
    ARAD_INT_SCH_FLTHRECCERROR,
    ARAD_INT_SCH_FSMECCERROR,
    ARAD_INT_SCH_SHDDECCERROR,
    ARAD_INT_SCH_CAL0PARERROR,
    ARAD_INT_SCH_CAL1PARERROR,
    ARAD_INT_SCH_CAL2PARERROR,
    ARAD_INT_SCH_CAL3PARERROR,
    ARAD_INT_SCH_CAL4PARERROR,
    ARAD_INT_SCH_CSDTPARERROR,
    ARAD_INT_SCH_CSSTPARERROR,
    ARAD_INT_SCH_DPNPARERROR,
    ARAD_INT_SCH_DRMPARERROR,
    ARAD_INT_SCH_DSMPARERROR,
    ARAD_INT_SCH_FDMSPARERROR,
    ARAD_INT_SCH_FFMPARERROR,
    ARAD_INT_SCH_FGMPARERROR,
    ARAD_INT_SCH_FIMPARERROR,
    ARAD_INT_SCH_FQMPARERROR,
    ARAD_INT_SCH_FSFPARERROR,
    ARAD_INT_SCH_PSDDPARERROR,
    ARAD_INT_SCH_PSDTPARERROR,
    ARAD_INT_SCH_PSSTPARERROR,
    ARAD_INT_SCH_PSWPARERROR,
    ARAD_INT_SCH_SCCPARERROR,
    ARAD_INT_SCH_SCTPARERROR,
    ARAD_INT_SCH_SEMPARERROR,
    ARAD_INT_SCH_SHCPARERROR,
    ARAD_INT_SCH_SHDSPARERROR,
    ARAD_INT_SCH_SIMPARERROR,
    ARAD_INT_SCH_TMCPARERROR,
    ARAD_INT_IDR_MMUECC_1BERRINT,
    ARAD_INT_IDR_MMUECC_2BERRINT,
    ARAD_INT_LAST
};

arad_interrupt_type ardon_int_active_on_init[] = {
/*
 * List of interrupts that are vectors pointing to other interrupt registers
 */
    ARAD_INT_FDR_INTREG1,
    ARAD_INT_FDR_INTREG2,
    ARAD_INT_FDR_INTREG3,
    ARAD_INT_FMAC_INTREG1,
    ARAD_INT_FMAC_INTREG2,
    ARAD_INT_FMAC_INTREG3,
    ARAD_INT_FMAC_INTREG4,
    ARAD_INT_FMAC_INTREG5,
    ARAD_INT_FMAC_INTREG6,
    ARAD_INT_FMAC_INTREG7,
    ARAD_INT_FMAC_INTREG8,
    ARAD_INT_FMAC_INTREG9,
    ARAD_INT_FSRD_INTREG0,
    ARAD_INT_FSRD_INTREG1,
    ARAD_INT_FSRD_INTREG2,
    ARAD_INT_NBI_ECCPARITYINT,
    ARAD_INT_EGQ_ERPPDISCARDINTVEC,
    ARAD_INT_EGQ_PKTREASINTVEC,
    ARAD_INT_EGQ_ERPPDISCARDINTVEC2,
    ARAD_INT_EGQ_ERRORECC,
    ARAD_INT_EPNI_ERRORECC,
    ARAD_INT_EPNI_PPINTVEC,
    ARAD_INT_CRPS_SRCINVLIDACCESS,
    ARAD_INT_CRPS_PARERRINTERRUPT,
    ARAD_INT_IPT_ECCERRINTERRUPT,
    ARAD_INT_IQM_ECCINTRERR,
    ARAD_INT_IRE_ERRORECC,
    ARAD_INT_IDR_ERRORECC,
    ARAD_INT_IDR_ERRORREASSEMBLY,
    ARAD_INT_IRR_ERRORECC,
    ARAD_INT_SCH_ECCERRORFIXED,
    ARAD_INT_SCH_ECCERROR,
    ARAD_INT_SCH_PARITYERROR,
    ARAD_INT_OAMP_RMAPEMINTERRUPTONE,
    ARAD_INT_OAMP_ERRECC,
    ARAD_INT_MMU_ERRORECC,
    ARAD_INT_OLP_ERRORECC,
    ARAD_INT_CFC_PARITYERRINT,
    ARAD_INT_CRPS_PARERRINTERRUPT,
    ARAD_INT_EGQ_PARITYERRINT,
    ARAD_INT_EGQ_DBFECC_1BERRINT,
    ARAD_INT_EGQ_DBFECC_2BERRINT,
    ARAD_INT_EGQ_ECC_1BERRINT,
    ARAD_INT_EGQ_ECC_2BERRINT,
    ARAD_INT_EPNI_ECC_1BERRINT,
    ARAD_INT_EPNI_ECC_2BERRINT,
    ARAD_INT_FCR_ECC_1BERRINT,
    ARAD_INT_FCR_ECC_2BERRINT,
    ARAD_INT_FDR_PRMECC_1BERRINT,
    ARAD_INT_FDR_PRMECC_2BERRINT,
    ARAD_INT_FDR_SECECC_1BERRINT,
    ARAD_INT_FDR_SECECC_2BERRINT,
    ARAD_INT_FDT_ECC_1BERRINT,
    ARAD_INT_FDT_ECC_2BERRINT,
    ARAD_INT_FMAC_ECC_1BERRINT,
    ARAD_INT_FMAC_ECC_2BERRINT,
    ARAD_INT_IDR_ECC_1BERRINT,
    ARAD_INT_IDR_ECC_2BERRINT,
    ARAD_INT_IDR_PARITYERRINT,
    ARAD_INT_IHP_PARITYERRINT,
    ARAD_INT_IPS_ECC_1BERRINT,
    ARAD_INT_IPS_ECC_2BERRINT,
    ARAD_INT_IPS_PARITYERRINT,
    ARAD_INT_IPT_ECC_1BERRINT,
    ARAD_INT_IPT_ECC_2BERRINT,
    ARAD_INT_IPT_PARITYERRINT,
    ARAD_INT_IQM_ECC_1BERRINT,
    ARAD_INT_IQM_ECC_2BERRINT,
    ARAD_INT_IQM_PARITYERRINT,
    ARAD_INT_IRE_ECC_1BERRINT,
    ARAD_INT_IRE_ECC_2BERRINT,
    ARAD_INT_IRE_PARITYERRINT,
    ARAD_INT_IRR_ECC_1BERRINT,
    ARAD_INT_IRR_ECC_2BERRINT,
    ARAD_INT_IRR_PARITYERRINT,
    ARAD_INT_MMU_ECC_1BERRINT,
    ARAD_INT_MMU_ECC_2BERRINT,
    ARAD_INT_NBI_ECC_1BERRINT,
    ARAD_INT_NBI_ECC_2BERRINT,
    ARAD_INT_NBI_PARITYERRINT,
    ARAD_INT_NBI_ILKNRXPARITYERRINT,
    ARAD_INT_NBI_ILKNTXPARITYERRINT,
    ARAD_INT_OAMP_ECC_1BERRINT,
    ARAD_INT_OAMP_ECC_2BERRINT,
    ARAD_INT_OAMP_PARITYERRINT,
    ARAD_INT_OLP_ECC_1BERRINT,
    ARAD_INT_OLP_ECC_2BERRINT,
    ARAD_INT_OLP_PARITYERRINT,
    ARAD_INT_SCH_DCDECCERRORFIXED,
    ARAD_INT_SCH_DHDECCERRORFIXED,
    ARAD_INT_SCH_FDMDECCERRORFIXED,
    ARAD_INT_SCH_FLHCLECCERRORFIXED,
    ARAD_INT_SCH_FLHFQECCERRORFIXED,
    ARAD_INT_SCH_FLHHRECCERRORFIXED,
    ARAD_INT_SCH_FLTCLECCERRORFIXED,
    ARAD_INT_SCH_FLTFQECCERRORFIXED,
    ARAD_INT_SCH_FLTHRECCERRORFIXED,
    ARAD_INT_SCH_FSMECCERRORFIXED,
    ARAD_INT_SCH_SHDDECCERRORFIXED,
    ARAD_INT_LAST
};

arad_interrupt_type arad_int_disable_print_on_init[] = {
    ARAD_INT_RTP_LINKMASKCHANGE,
    ARAD_INT_LAST
};

soc_mem_t ardon_cached_mem[] = {
    NUM_SOC_MEM
};

soc_mem_t arad_cached_mem[] = {
    CFC_CAT_2_TC_MAP_HCFCm,
    CFC_CAT_2_TC_MAP_NIFm,
    CFC_ILKN_RX_0_CALm,
    CFC_ILKN_RX_1_CALm,
    CFC_ILKN_TX_0_CALm,
    CFC_ILKN_TX_1_CALm,
    CFC_NIF_PFC_MAPm,
    CFC_RCL_VSQ_MAPm,
    CFC_SPI_OOB_RX_0_CALm,
    CFC_SPI_OOB_RX_1_CALm,
    CFC_SPI_OOB_TX_0_CALm,
    CFC_SPI_OOB_TX_1_CALm,
    EGQ_CCMm,
    EGQ_CH_0_SCMm,
    EGQ_CH_1_SCMm,
    EGQ_CH_2_SCMm,
    EGQ_CH_3_SCMm,
    EGQ_CH_4_SCMm,
    EGQ_CH_5_SCMm,
    EGQ_CH_6_SCMm,
    EGQ_CH_7_SCMm,
    EGQ_CH_8_SCMm,
    EGQ_CH_9_SCMm,
    EGQ_DSP_PTR_MAPm,
    EGQ_DWM_8Pm,
    EGQ_DWMm,
    EGQ_HEADER_MAPm,
    EGQ_MAP_OUTLIF_TO_DSPm,
    EGQ_NONCH_SCMm,
    EGQ_PDCT_TABLEm,
    EGQ_PMCm,
    EGQ_PPCTm,
    EGQ_PQST_TABLEm,
    EGQ_QDCT_TABLEm,
    EGQ_QP_PMCm,
    EGQ_QP_SCMm,
    EGQ_QQST_TABLEm,
    EGQ_TCG_PMCm,
    EGQ_TCG_SCMm,
    EGQ_VLAN_TABLEm,
    EGQ_VSI_MEMBERSHIPm,
    EPNI_ACE_TABLEm,
    EPNI_ACE_TO_FHEIm,
    EPNI_ACE_TO_OUT_LIFm,
    EPNI_ACE_TO_OUT_PP_PORTm,
    EPNI_DSCP_EXP_TO_PCP_DEIm,
    EPNI_DSCP_REMARKm,
    EPNI_EVEC_TABLEm,
    EPNI_EXP_REMARKm,
    EPNI_HEADER_MAPm,
    EPNI_ISID_TABLEm,
    EPNI_MIRROR_PROFILE_TABLEm,
    EPNI_MY_CFM_MAC_TABLEm,
    EPNI_PP_COUNTER_TABLEm,
    EPNI_PRGE_DATAm,
    EPNI_REMARK_IPV4_TO_DSCPm,
    EPNI_REMARK_IPV4_TO_EXPm,
    EPNI_REMARK_IPV6_TO_DSCPm,
    EPNI_REMARK_IPV6_TO_EXPm,
    EPNI_TX_TAG_TABLEm,
    FDT_IN_BAND_MEMm,
    IDR_CONTEXT_MRUm,
    IDR_ETHERNET_METER_CONFIGm,
    IHB_DESTINATION_STATUSm,
    IHB_FEC_ECMPm,
    IHB_FEC_SUPER_ENTRYm,
    IHB_FLP_KEY_CONSTRUCTIONm,
    IHB_FLP_PROCESSm,
    IHB_FWD_ACT_PROFILEm,
    IHB_IN_PORT_KEY_GEN_VARm,
    IHB_IPP_LAG_TO_LAG_RANGEm,
    IHB_LB_PFC_PROFILEm,
    IHB_LPM_2m,
    IHB_LPM_3m,
    IHB_LPM_4m,
    IHB_LPM_5m,
    IHB_LPM_6m,
    IHB_LPMm,
    IHB_OAMAm,
    IHB_OAMBm,
    IHB_PATH_SELECTm,
    IHB_PINFO_COUNTERSm,
    IHB_PINFO_FERm,
    IHB_PINFO_FLPm,
    IHB_PINFO_LBPm,
    IHB_PINFO_PMFm,
    IHB_PMF_FEM_PROGRAMm,
    IHB_PMF_FES_PROGRAMm,
    IHB_PMF_INITIAL_KEY_2ND_PASSm,
    IHB_PMF_PASS_1_KEY_GEN_LSBm,
    IHB_PMF_PASS_1_KEY_GEN_MSBm,
    IHB_PMF_PASS_1_LOOKUPm,
    IHB_PMF_PASS_2_KEY_GEN_LSBm,
    IHB_PMF_PASS_2_KEY_GEN_MSBm,
    IHB_PMF_PASS_2_LOOKUPm,
    IHB_PMF_PROGRAM_COUNTERSm,
    IHB_PMF_PROGRAM_GENERALm,
    IHB_PROGRAM_KEY_GEN_VARm,
    IHB_PTC_INFO_PMFm,
    IHB_PTC_KEY_GEN_VARm,
    IHB_SNOOP_ACTIONm,
    IHB_VRF_CONFIGm,
    IHP_BVD_CFGm,
    IHP_BVD_FID_CLASSm,
    IHP_BVD_TOPOLOGY_IDm,
    IHP_DEFAULT_COUNTER_SOURCEm,
    IHP_INGRESS_VLAN_EDIT_COMMAND_TABLEm,
    IHP_IN_RIF_CONFIG_TABLEm,
    IHP_LLR_LLVPm,
    IHP_LL_MIRROR_PROFILEm,
    IHP_PACKET_FORMAT_TABLEm,
    IHP_PINFO_LLRm,
    IHP_PORT_PROTOCOLm,
    IHP_PP_PORT_INFOm,
    IHP_PTC_INFOm,
    IHP_PTC_PARSER_PROGRAM_POINTER_CONFIGm,
    IHP_PTC_PFQ_0_CONFIGm,
    IHP_PTC_SYS_PORT_CONFIGm,
    IHP_PTC_VIRTUAL_PORT_CONFIGm,
    IHP_RECYCLE_COMMANDm,
    IHP_RESERVED_MCm,
    IHP_STP_TABLEm,
    IHP_TC_DP_MAP_TABLEm,
    IHP_TOS_2_COSm,
    IHP_VIRTUAL_PORT_TABLEm,
    IHP_VLAN_EDIT_PCP_DEI_MAPm,
    IHP_VRID_MY_MAC_MAPm,
    IHP_VRID_TO_VRF_MAPm,
    IHP_VSI_HIGH_DA_NOT_FOUND_DESTINATIONm,
    IHP_VSI_HIGH_MY_MACm,
    IHP_VSI_HIGH_PROFILEm,
    IHP_VSI_LOW_CFG_1m,
    IHP_VSI_LOW_CFG_2m,
    IHP_VTT_1ST_LOOKUP_PROGRAM_1m,
    IHP_VTT_2ND_LOOKUP_PROGRAM_1m,
    IHP_VTT_IN_PP_PORT_CONFIGm,
    IHP_VTT_IN_PP_PORT_VLAN_CONFIGm,
    IHP_VTT_LLVPm,
    IHP_VTT_PP_PORT_TT_KEY_VARm,
    IHP_VTT_PP_PORT_VSI_PROFILESm,
    IHP_VTT_PP_PORT_VT_KEY_VARm,
    IHP_VTT_PTC_CONFIGm,
    IPS_CRBALTHm,
    IPS_EMPTYQCRBALm,
    IPS_QPRISELm,
    IPS_QSZTHm,
    IPS_QTYPEm,
    IPT_SNP_MIR_CMD_MAPm,
    IQM_CNREDm,
    IQM_CPDMSm,
    IQM_OCBPRMm,
    IQM_PQDMSm,
    IQM_PQREDm,
    IQM_PQWQm,
    IQM_SCRBUFFTHm,
    IQM_SPRDPRMm,
    IQM_SRCQRNGm,
    IQM_VQFCPR_MAm,
    IQM_VQFCPR_MBm,
    IQM_VQFCPR_MCm,
    IQM_VQFCPR_MDm,
    IQM_VQFCPR_MEm,
    IQM_VQFCPR_MFm,
    IQM_VQPR_MAm,
    IQM_VQPR_MBm,
    IQM_VQPR_MCm,
    IQM_VQPR_MDm,
    IQM_VQPR_MEm,
    IQM_VQPR_MFm,
    IRE_CPU_CTXT_MAPm,
    IRE_NIF_CTXT_MAPm,
    IRE_NIF_PORT_TO_CTXT_BIT_MAPm,
    IRE_RCY_CTXT_MAPm,
    IRE_TDM_CONFIGm,
    IRR_DESTINATION_TABLEm,
    IRR_FLOW_TABLEm,
    IDR_IRDBm,
    IRR_LAG_MAPPINGm,
    IRR_LAG_TO_LAG_RANGEm,
    IRR_SMOOTH_DIVISIONm,
    IRR_SNOOP_MIRROR_TABLE_1m,
    IRR_STACK_FEC_RESOLVEm,
    IRR_STACK_TRUNK_RESOLVEm,
    OAMP_MEP_DB_BFD_CC_ON_MPLSTPm,
    OAMP_MEP_DB_BFD_ON_PWEm,
    OAMP_PE_PROGRAMm,
    OAMP_UMC_TABLEm,
    SCH_CIR_SHAPERS_STATIC_TABEL__CSSTm,
    SCH_CL_SCHEDULERS_CONFIGURATION__SCCm,
    SCH_CL_SCHEDULERS_TYPE__SCTm,
    SCH_DEVICE_RATE_MEMORY__DRMm,
    SCH_DUAL_SHAPER_MEMORY__DSMm,
    SCH_FLOW_DESCRIPTOR_MEMORY_STATIC__FDMSm,
    SCH_FLOW_GROUP_MEMORY__FGMm,
    SCH_FLOW_SUB_FLOW__FSFm,
    SCH_FLOW_TO_FIP_MAPPING__FFMm,
    SCH_FLOW_TO_QUEUE_MAPPING__FQMm,
    SCH_HR_SCHEDULER_CONFIGURATION__SHCm,
    SCH_PIR_SHAPERS_STATIC_TABEL__PSSTm,
    SCH_PORT_SCHEDULER_WEIGHTS__PSWm,
    SCH_SCHEDULER_CREDIT_GENERATION_CALENDAR__CALm,
    SCH_SCHEDULER_ENABLE_MEMORY__SEMm,
    /* parity multi element memories. */    
    IDR_MCDA_PRFSELm,
    IDR_MCDB_PRFSELm,
    IHB_FEC_ENTRYm,
    IHP_PARSER_PROGRAMm,

    /* parity multi element memories with alias*/
/*  EPNI_EEDB_BANKm,
    IHB_TCAM_ACTIONm,
    IHP_LIF_TABLEm,
    IHP_VLAN_PORT_MEMBERSHIP_TABLEm,*/

    NUM_SOC_MEM
};

int
arad_interrupt_handler_init_cmn_param(int unit, interrupt_common_params_t* common_params)
{
    int nof_interrupts;
    int rc;

    SOCDNX_INIT_FUNC_DEFS;

    SOCDNX_NULL_CHECK(common_params);

    rc = soc_arad_nof_interrupts(unit, &nof_interrupts);
    SOCDNX_IF_ERR_EXIT(rc);

    common_params->nof_interrupts = nof_interrupts;
    common_params->interrupt_add_interrupt_handler_init = arad_interrupt_add_interrupt_handler_init;
    common_params->interrupt_handle_block_instance = soc_dpp_nof_block_instances;
    common_params->int_disable_on_init = arad_int_disable_on_init;
    common_params->int_disable_print_on_init = arad_int_disable_print_on_init;
    if(SOC_IS_ARDON(unit)) {
        common_params->int_active_on_init = ardon_int_active_on_init;
        common_params->cached_mem = ardon_cached_mem;
    } else {
        common_params->int_active_on_init = arad_int_active_on_init;
        common_params->cached_mem = arad_cached_mem;
    }


exit:
    SOCDNX_FUNC_RETURN;
}

#undef _ERR_MSG_MODULE_NAME

