/* $Id: pb_api_interrupt_service.h,v 1.8 Broadcom SDK $
 * $Copyright: Copyright 2015 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
*/


#ifndef __SOC_PB_API_INTERRUPT_SERVICE_INCLUDED__
/* { */
#define __SOC_PB_API_INTERRUPT_SERVICE_INCLUDED__

/*************
 * INCLUDES  *
 *************/
/* { */

#include <soc/dpp/SAND/Utils/sand_header.h>
#include <soc/dpp/SAND/Utils/sand_framework.h>
#include <soc/dpp/SAND/Utils/sand_integer_arithmetic.h>

#include <soc/dpp/Petra/petra_general.h>

/* } */
/*************
 * DEFINES   *
 *************/
/* { */

#define SOC_PB_INTERRUPT_MAX_NOF_REG_IN_MOD             (7)
#define SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG           (SOC_SAND_NOF_BITS_IN_UINT32)
#define SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD           (SOC_PB_INTERRUPT_MAX_NOF_REG_IN_MOD * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG)

#define SOC_PB_INTERRUPT_MAX_MONITORED_CAUSES           MAX_INTERRUPT_CAUSE
#define SOC_PB_INTERRUPT_MAX_MONITORED_CAUSES_IN_UINT32   SIZE_OF_BITSTRAEM_IN_UINT32S

#define SOC_PB_INTERRUPT_SINGLE_MAX_NOF_INTERRUPT_DATA  (5)

/* } */

/*************
 * MACROS    *
 *************/
/* { */

/* } */

/*************
 * TYPE DEFS *
 *************/
/* { */

typedef uint32 SOC_PB_INTERRUPT_MONITORED_CAUSE;

typedef enum
{
  SOC_PB_INTERRUPT_OLP_ID = 0,
  SOC_PB_INTERRUPT_NIF_ID,
  SOC_PB_INTERRUPT_MAL_ID,
  SOC_PB_INTERRUPT_IRE_ID,
  SOC_PB_INTERRUPT_IDR_ID,
  SOC_PB_INTERRUPT_IRR_ID,
  SOC_PB_INTERRUPT_IQM_ID,
  SOC_PB_INTERRUPT_IPS_ID,
  SOC_PB_INTERRUPT_IPT_ID,
  SOC_PB_INTERRUPT_MMU_ID,
  SOC_PB_INTERRUPT_DPI_ID,
  SOC_PB_INTERRUPT_FDR_ID,
  SOC_PB_INTERRUPT_FDT_ID,
  SOC_PB_INTERRUPT_FCR_ID,
  SOC_PB_INTERRUPT_FCT_ID,
  SOC_PB_INTERRUPT_RTP_ID,
  SOC_PB_INTERRUPT_FABRIC_MAC_ID,
  SOC_PB_INTERRUPT_MSW_ID,
  SOC_PB_INTERRUPT_EGQ_ID,
  SOC_PB_INTERRUPT_EPN_ID,
  SOC_PB_INTERRUPT_CFC_ID,
  SOC_PB_INTERRUPT_SCH_ID,
  SOC_PB_INTERRUPT_QDR_ID,
  SOC_PB_INTERRUPT_NBI_ID,
  SOC_PB_INTERRUPT_IHP_ID,
  SOC_PB_INTERRUPT_EPNI_ID,
  SOC_PB_INTERRUPT_IHB_ID,
  SOC_PB_INTERRUPT_NOF_MODULES
} SOC_PB_INTERRUPT_MODULES;

typedef enum
{
  SOC_PB_OLP_END_READ_ERR        = SOC_PB_INTERRUPT_OLP_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_OLP_END_WRITE_ERR,
  SOC_PB_OLP_START_ERR,
  SOC_PB_OLP_END_READ_EXP_ERR,
  SOC_PB_OLP_END_WRITE_EXP_ERR,
  SOC_PB_OLP_START_EXP_ERR,

  SOC_PB_NIF_MAL_INT            = SOC_PB_INTERRUPT_NIF_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),  
  SOC_PB_NIF_SRD_INT,
  SOC_PB_NIF_PAEB_INT,
  SOC_PB_NIF_SYNC_ETH_INT,
  SOC_PB_NIF_SRD_LANE_INT        = SOC_PB_INTERRUPT_NIF_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 1),
  SOC_PB_NIF_SRD_IPU_INT,
  SOC_PB_NIF_SRD_EPB_INT,
  SOC_PB_NIF_RX_PAEB_INT         = SOC_PB_INTERRUPT_NIF_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 2),

  SOC_PB_MAL_LINK_STATUS_CHANGE_INT         = SOC_PB_INTERRUPT_MAL_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_MAL_RX_PCS_LN_SYNC_STAT_CHANGE_INT,
  SOC_PB_MAL_RX_PCS_LOCAL_FAULT_INT,
  SOC_PB_MAL_RX_PCS_LOCAL_FAULT_PHY_INT,
  SOC_PB_MAL_RX_PCS_REMOTE_FAULT_INT,
  SOC_PB_MAL_RX_PCS_UNKNOWN_FAULT_INT,
  SOC_PB_MAL_STAT_COUNTER_AF_INT,
  SOC_PB_MAL_AN_RESTART_INT,
  SOC_PB_MAL_AN_COMPLETE_INT,
  SOC_PB_MAL_AN_ERROR_INT,
  SOC_PB_MAL_ERROR_INT,
  
  SOC_PB_MAL_MAC_TX_ERR_INT = SOC_PB_INTERRUPT_MAL_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 1),
  SOC_PB_MAL_MAC_RX_ERR_INT,  
  SOC_PB_MAL_RX_ALNR_OVF_INT,
  SOC_PB_MAL_TX_PTP_1588_STAMPING_ERR_INT,
  SOC_PB_MAL_RX_PTP_1588_STAMPING_ERR_INT,
  SOC_PB_MAL_TX_TAF_OVERFLOW_ERR_INT,
  SOC_PB_MAL_RX_RAF_OVERFLOW_ERR_INT,
  SOC_PB_MAL_RX_PCS_DESKEW_ERR_INT,
  SOC_PB_MAL_RX_PCS_BOM_ERR_INT,
  SOC_PB_MAL_RX_PCS_DESKEW_ERR_FATAL_INT,
  SOC_PB_MAL_RX_MAC_BCT_CRC_ERR_INT,

  SOC_PB_NBI_TX_FIFO_OVERFLOW_INT = SOC_PB_INTERRUPT_NBI_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_NBI_RX_FIFO_OVERFLOW_INT,
  SOC_PB_NBI_ILEGAL_ILKN_INPUT_FROM_RX0_INT,
  SOC_PB_NBI_ILEGAL_ILKN_INPUT_FROM_RX1_INT,
  SOC_PB_NBI_ERR_BITS_FROM_EGQ_INT,
  SOC_PB_NBI_WRONG_MALG_WORD_INT,
  SOC_PB_NBI_WRONG_EGQ_WORD_INT,
  SOC_PB_NBI_WRONG_PORT_FROM_EGQ_INT,
  SOC_PB_NBI_RX_PORT_DISCARDED_PACKET_INT,
  SOC_PB_NBI_RX_NUM_THROWN_EOPS_INT,
  SOC_PB_NBI_RX_NUM_THROWN_EOPS_75P_INT,
  SOC_PB_NBI_STAT_INTERRUPT,
  SOC_PB_NBI_ILKN_INTERRUPT,
  SOC_PB_NBI_THROWN_BURSTS_COUNTERS0_75P_INTERRUPT,
  SOC_PB_NBI_THROWN_BURSTS_COUNTERS1_75P_INTERRUPT,
  SOC_PB_NBI_ILKN_TX0_ECC_ERR0_INT,
  SOC_PB_NBI_ILKN_TX0_ECC_ERR1_INT,
  SOC_PB_NBI_ILKN_TX1_ECC_ERR0_INT,
  SOC_PB_NBI_ILKN_TX1_ECC_ERR1_INT,
  SOC_PB_NBI_STAT_READ_ERR_INT = SOC_PB_INTERRUPT_NBI_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 1),
  SOC_PB_NBI_STAT_RX_FRAME_ERR_INT,
  SOC_PB_NBI_STAT_TX_FRAME_ERR_INT,
  SOC_PB_NBI_STAT_RX_BURST_LENGTH_OVERFLOW_INT,
  SOC_PB_NBI_STAT_TX_BURST_LENGTH_OVERFLOW_INT,
  SOC_PB_NBI_STAT_CNT75P_PORT0_31,
  SOC_PB_NBI_STAT_CNT75P_PORT32_63,
  SOC_PB_NBI_STAT_CNT75P_PORT0_31_INT = SOC_PB_INTERRUPT_NBI_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 2),
  SOC_PB_NBI_STAT_CNT75P_PORT32_63_INT = SOC_PB_INTERRUPT_NBI_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 3),
  SOC_PB_NBI_ILKN_RX_PORT0_STATUS_CHANGE_INT = SOC_PB_INTERRUPT_NBI_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 4),
  SOC_PB_NBI_ILKN_RX_PORT1_STATUS_CHANGE_INT,
  SOC_PB_NBI_ILKN_LINK_PARTNER_STATUS_CHANGE_LANES0_11_INT,
  SOC_PB_NBI_ILKN_LINK_PARTNER_STATUS_CHANGE_LANES12_23_INT,
  SOC_PB_NBI_ILKN_RX_PORT0_ALIGN_ERR_INT,
  SOC_PB_NBI_ILKN_RX_PORT1_ALIGN_ERR_INT,
  SOC_PB_NBI_ILKN_CRC32_LANE_ERR_INDICATION_LANES0_11_INT,
  SOC_PB_NBI_ILKN_CRC32_LANE_ERR_INDICATION_LANES12_23_INT,
  SOC_PB_NBI_ILKN_LANE_SYNCH_ERR_LANES0_11_INT,
  SOC_PB_NBI_ILKN_LANE_SYNCH_ERR_LANES12_23_INT,
  SOC_PB_NBI_ILKN_LANE_FRAMING_ERR_LANES0_11_INT,
  SOC_PB_NBI_ILKN_LANE_FRAMING_ERR_LANES12_23_INT,
  SOC_PB_NBI_ILKN_LANE_BAD_FRAMING_TYPE_ERR_LANES0_11_INT,
  SOC_PB_NBI_ILKN_LANE_BAD_FRAMING_TYPE_ERR_LANES12_23_INT,
  SOC_PB_NBI_ILKN_LANE_META_FRAME_SYNC_WORD_ERR_LANES0_11_INT,
  SOC_PB_NBI_ILKN_LANE_META_FRAME_SYNC_WORD_ERR_LANES12_23_INT,
  SOC_PB_NBI_ILKN_LANE_SCRAMBLER_STATE_ERR_LANES0_11_INT,
  SOC_PB_NBI_ILKN_LANE_SCRAMBLER_STATE_ERR_LANES12_23_INT,
  SOC_PB_NBI_ILKN_LANE_META_FRAME_LENGTH_ERR_LANES0_11_INT,
  SOC_PB_NBI_ILKN_LANE_META_FRAME_LENGTH_ERR_LANES12_23_INT,
  SOC_PB_NBI_ILKN_LANE_META_FRAME_REPEAT_ERR_LANES0_11_INT,
  SOC_PB_NBI_ILKN_LANE_META_FRAME_REPEAT_ERR_LANES12_23_INT,
  SOC_PB_NBI_ILKN_RX_PARITY_ERR_INT,
  SOC_PB_NBI_ILKN_TX_PARITY_ERR_INT,
  SOC_PB_NBI_ILKN_RX_PORT0_STATUS_ERR_INT,
  SOC_PB_NBI_ILKN_RX_PORT1_STATUS_ERR_INT,
  SOC_PB_NBI_ILKN_TX_PORT0_STATUS_ERR_INT,  
  SOC_PB_NBI_ILKN_TX_PORT1_STATUS_ERR_INT,  
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX0_PORT0_INT = SOC_PB_INTERRUPT_NBI_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 5),
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX0_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX0_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX0_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX1_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX1_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX1_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX1_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX2_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX2_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX2_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX2_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX3_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX3_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX3_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX3_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX4_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX4_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX4_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX4_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX5_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX5_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX5_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX5_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX6_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX6_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX6_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX6_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX7_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX7_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX7_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX7_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX8_PORT0_INT = SOC_PB_INTERRUPT_NBI_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 6),
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX8_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX8_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX8_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX9_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX9_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX9_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX9_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX10_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX10_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX10_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX10_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX11_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX11_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX11_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX11_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX12_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX12_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX12_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX12_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX13_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX13_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX13_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX13_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX14_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX14_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX14_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX14_PORT3_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX15_PORT0_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX15_PORT1_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX15_PORT2_INT,
  SOC_PB_NBI_NUM_THROWN_BURSTS_COUNTER_75P_RX15_PORT3_INT,

  SOC_PB_IRE_CPU_IF_ERR_DATA_ARRIVED = SOC_PB_INTERRUPT_IRE_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_IRE_CPU_IF_32BYTES_PACK_ERR,
  SOC_PB_IRE_CPU_IF_PACKET_SIZE_ERR,
  SOC_PB_IRE_CPU_IF_64BYTES_PACK_ERR,
  SOC_PB_IRE_OLP_IF_ERR_DATA_ARRIVED,
  SOC_PB_IRE_OLP_IF_32BYTES_PACK_ERR,
  SOC_PB_IRE_OLP_IF_PACKET_SIZE_ERR,
  SOC_PB_IRE_OLP_IF_64BYTES_PACK_ERR,
  SOC_PB_IRE_NIFA_PACKET_SIZE_ERR,
  SOC_PB_IRE_RCY_ERR_DATA_ARRIVED,
  SOC_PB_IRE_RCY_PACKET_SIZE_ERR,
  SOC_PB_IRE_RCY_64BYTES_PACK_ERR,
  SOC_PB_IRE_BURST_ERR_FOLLOW_SOP_NOT_VALID,
  SOC_PB_IRE_BURST_ERR_FOLLOW_SOP_DIF_CONTEXT,
  SOC_PB_IRE_BURST_ERR_FOLLOW_SOP_IS_SOP,
  SOC_PB_IRE_BURST_ERR_FOLLOW_SOP_IS_ERR,
  SOC_PB_IRE_FAP_PORT_ERR,
  SOC_PB_IRE_TDM_ERR,
  SOC_PB_IRE_TDM_SIZE_ERR,

  SOC_PB_IDR_ERROR_UNICAST_RECYCLE = SOC_PB_INTERRUPT_IDR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_IDR_ERROR_MINI_MULTICAST_RECYCLE,
  SOC_PB_IDR_ERROR_FULL_MULTICAST_RECYCLE,
  SOC_PB_IDR_ERROR_REASSEMBLY,
  SOC_PB_IDR_ERROR_TIMEOUT,
  SOC_PB_IDR_ERROR_MEMORY0,
  SOC_PB_IDR_ERROR_MEMORY1,
  SOC_PB_IDR_ERROR_MEMORY2,
  SOC_PB_IDR_REASSEMBLY_ERROR_MINIMUM_ORIGINAL_SIZE = SOC_PB_INTERRUPT_IDR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 1),
  SOC_PB_IDR_REASSEMBLY_ERROR_MINIMUM_SIZE,
  SOC_PB_IDR_REASSEMBLY_ERROR_MAXIMUM_ORIGINAL_SIZE,
  SOC_PB_IDR_REASSEMBLY_ERROR_MAXIMUM_SIZE,
  SOC_PB_IDR_REASSEMBLY_ERROR_MAXIMUM_DP,
  SOC_PB_IDR_REASSEMBLY_ERROR_NO_PCB,
  SOC_PB_IDR_REASSEMBLY_ERROR_NO_SOP_PCB,
  SOC_PB_IDR_REASSEMBLY_ERROR_NO_DP,
  SOC_PB_IDR_REASSEMBLY_ERROR_UNEXPECTED_EOP,
  SOC_PB_IDR_REASSEMBLY_ERROR_UNEXPECTED_MOP,
  SOC_PB_IDR_REASSEMBLY_ERROR_UNEXPECTED_SOP,
  SOC_PB_IDR_REASSEMBLY_ERROR_GENERAL_MOP,
  SOC_PB_IDR_REASSEMBLY_ERROR_GENERAL_IDLE,
  SOC_PB_IDR_REASSEMBLY4_BIT_ERROR = SOC_PB_INTERRUPT_IDR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 2),
  SOC_PB_IDR_ETHERNET_METER_PROFILES_BIT_ERROR,
  SOC_PB_IDR_ETHERNET_METER_STATUS_BIT_ERROR,
  SOC_PB_IDR_CONTEXT_STATUS_BIT_ERROR,
  SOC_PB_IDR_ERROR_CHUNK_STATUS_ECC = SOC_PB_INTERRUPT_IDR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 3),
  SOC_PB_IDR_ERROR_CHUNK_FIFO_ECC,
  SOC_PB_IDR_DBUFF_POINTER_CACHE01_ECC_ERROR,
  SOC_PB_IDR_DBUFF_POINTER_CACHE23_ECC_ERROR,
  SOC_PB_IDR_DBUFF_POINTER_CACHE45_ECC_ERROR,
  SOC_PB_IDR_ERROR_FREE_PCBS_ECC,
  SOC_PB_IDR_ERROR_PCB_LINK_TABLE_ECC,  
  SOC_PB_IDR_ERROR_PRM_DP_ECC,
  SOC_PB_IDR_ERROR_PRM_CD_ECC,
  SOC_PB_IDR_ERROR_REASSEMBLY_STATUS_ECC,
  SOC_PB_IDR_ERROR_WORD_INDEX_ECC,
  SOC_PB_IDR_ERROR_COMPLETE_PC_ECC,
  SOC_PB_IDR_MMU_ECC_ERROR,
  SOC_PB_IDR_ERROR_CHUNK_STATUS_ECC_2 = SOC_PB_INTERRUPT_IDR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 4),
  SOC_PB_IDR_ERROR_CHUNK_FIFO_ECC_2,
  SOC_PB_IDR_DBUFF_POINTER_CACHE01_ECC_ERROR_2,
  SOC_PB_IDR_DBUFF_POINTER_CACHE23_ECC_ERROR_2,
  SOC_PB_IDR_DBUFF_POINTER_CACHE45_ECC_ERROR_2,
  SOC_PB_IDR_ERROR_FREE_PCBS_ECC_2,
  SOC_PB_IDR_ERROR_PCB_LINK_TABLE_ECC_2,  
  SOC_PB_IDR_ERROR_PRM_DP_ECC_2,
  SOC_PB_IDR_ERROR_PRM_CD_ECC_2,
  SOC_PB_IDR_ERROR_REASSEMBLY_STATUS_ECC_2,
  SOC_PB_IDR_ERROR_WORD_INDEX_ECC_2,
  SOC_PB_IDR_ERROR_COMPLETE_PC_ECC_2,
  SOC_PB_IDR_MMU_ECC_ERROR_2,

  SOC_PB_IRR_ERR_MAX_REPLICATION = SOC_PB_INTERRUPT_IRR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_IRR_ERROR_MAX_REPLICATION,
  SOC_PB_IRR_ERROR_RESEQUENCER0_OUT_OF_SEQ,
  SOC_PB_IRR_ERROR_RESEQUENCER1_OUT_OF_SEQ,
  SOC_PB_IRR_ERROR_RESEQUENCER2_OUT_OF_SEQ,
  SOC_PB_IRR_ERROR_RESEQUENCER0_OUT_OF_SYNC,
  SOC_PB_IRR_ERROR_RESEQUENCER1_OUT_OF_SYNC,
  SOC_PB_IRR_ERROR_RESEQUENCER2_OUT_OF_SYNC,
  SOC_PB_IRR_ERROR_MEMORY0,
  SOC_PB_IRR_ERROR_MEMORY1,
  SOC_PB_IRR_ERROR_MEMORY2,
  SOC_PB_IRR_LAG_MAPPING_BIT_ERROR = SOC_PB_INTERRUPT_IRR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 1),
  SOC_PB_IRR_LAG_NEXT_MEMBER_BIT_ERROR,
  SOC_PB_IRR_LAG_TO_LAG_RANGE_BIT_ERROR,
  SOC_PB_IRR_MCDB_BIT_ERROR,
  SOC_PB_IRR_IRDB_BIT_ERROR,
  SOC_PB_IRR_DESTINATION_TABLE_BIT_ERROR,
  SOC_PB_IRR_SMOOTH_DIVISION_BIT_ERROR,
  SOC_PB_IRR_SNOOP_MIRROR_TABLE0_BIT_ERROR,
  SOC_PB_IRR_SNOOP_MIRROR_TABLE1_BIT_ERROR,
  SOC_PB_IRR_ERROR_FREE_PCP_ECC = SOC_PB_INTERRUPT_IRR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 2),
  SOC_PB_IRR_ERROR_IS_FREE_PCP_ECC,
  SOC_PB_IRR_IS_PC_MEMORY_ECC_ERROR,
  SOC_PB_IRR_IS_PCB_LINK_TABLE_ECC_ERROR,
  SOC_PB_IRR_ERROR_ISF_ECC,
  SOC_PB_IRR_MCR_MEMORY_ECC_ERROR,
  SOC_PB_IRR_PC_MEMORY_ECC_ERROR,
  SOC_PB_IRR_PCB_LINK_TABLE_ECC_ERROR,
  SOC_PB_IRR_RPF_MEMORY_ECC_ERROR,
  SOC_PB_IRR_RSQ_FIFO_ECC_ERROR,
  SOC_PB_IRR_ERROR_FREE_PCP_ECC_2 = SOC_PB_INTERRUPT_IRR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 3),
  SOC_PB_IRR_ERROR_IS_FREE_PCP_ECC_2,
  SOC_PB_IRR_IS_PC_MEMORY_ECC_ERROR_2,
  SOC_PB_IRR_IS_PCB_LINK_TABLE_ECC_ERROR_2,
  SOC_PB_IRR_ERROR_ISF_ECC_2,
  SOC_PB_IRR_MCR_MEMORY_ECC_ERROR_2,
  SOC_PB_IRR_PC_MEMORY_ECC_ERROR_2,
  SOC_PB_IRR_PCB_LINK_TABLE_ECC_ERROR_2,
  SOC_PB_IRR_RPF_MEMORY_ECC_ERROR_2,
  SOC_PB_IRR_RSQ_FIFO_ECC_ERROR_2,
  
  SOC_PB_IHP_ISEM_INTERRUPT = SOC_PB_INTERRUPT_IHP_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_IHP_LARGE_EM_INTERRUPT,
  SOC_PB_IHP_ISEM_ERROR_CAM_TABLE_FULL = SOC_PB_INTERRUPT_IHP_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 1),
  SOC_PB_IHP_ISEM_ERROR_TABLE_COHERENCY,
  SOC_PB_IHP_ISEM_ERROR_DELETE_UNKNOWN_KEY,
  SOC_PB_IHP_ISEM_ERROR_REACHED_MAX_ENTRY_LIMIT,
  SOC_PB_IHP_ISEM_WARNING_INSERTED_EXISTING,
  SOC_PB_IHP_ISEM_MANAGEMENT_UNIT_FAILURE_VALID,
  SOC_PB_IHP_ISEM_MANAGEMENT_COMPLETED,
  SOC_PB_IHP_LARGE_EM_ERROR_CAM_TABLE_FULL = SOC_PB_INTERRUPT_IHP_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 2),
  SOC_PB_IHP_LARGE_EM_ERROR_TABLE_COHERENCY,
  SOC_PB_IHP_LARGE_EM_ERROR_DELETE_UNKNOWN_KEY,
  SOC_PB_IHP_LARGE_EM_ERROR_REACHED_MAX_ENTRY_LIMIT,
  SOC_PB_IHP_LARGE_EM_WARNING_INSERTED_EXISTING,
  SOC_PB_IHP_LARGE_EM_ERROR_LEARN_REQUEST_OVER_STATIC,
  SOC_PB_IHP_LARGE_EM_WARNING_LEARN_OVER_EXISTING,
  SOC_PB_IHP_LARGE_EM_ERROR_CHANGE_FAIL_NON_EXIST,
  SOC_PB_IHP_LARGE_EM_ERROR_CHANGE_REQUEST_OVER_STATIC,
  SOC_PB_IHP_LARGE_EM_WARNING_CHANGE_NON_EXIST_FROM_OTHER,
  SOC_PB_IHP_LARGE_EM_WARNING_CHANGE_NON_EXIST_FROM_SELF,
  SOC_PB_IHP_LARGE_EM_MANAGEMENT_UNIT_FAILURE_VALID,
  SOC_PB_IHP_LARGE_EM_MNGMNT_REQ_FID_EXCEED_LIMIT,
  SOC_PB_IHP_LARGE_EM_MNGMNT_REQ_FID_EXCEED_LIMIT_STATIC_ALLOWED,
  SOC_PB_IHP_LARGE_EM_MNGMNT_REQ_SYSTEM_VSI_NOT_FOUND,
  SOC_PB_IHP_LARGE_EM_EVENT_READY,
  SOC_PB_IHP_LARGE_EM_EVENT_FIFO_EVENT_DROP,
  SOC_PB_IHP_LARGE_EM_EVENT_FIFO_HIGH_THRESHOLD_REACHED,
  SOC_PB_IHP_LARGE_EM_REPLY_READY,
  SOC_PB_IHP_LARGE_EM_REPLY_FIFO_REPLY_DROP,
  SOC_PB_IHP_LARGE_EM_LOOKUP_BURST_FIFO_DROP,
  SOC_PB_IHP_LARGE_EM_AGE_REACHED_END_INDEX,
  SOC_PB_IHP_LARGE_EM_FLU_REACHED_END_INDEX,
  SOC_PB_IHP_LARGE_EM_AMSG_DROP,
  SOC_PB_IHP_LARGE_EM_FMSG_DROP,
  SOC_PB_IHP_LARGE_EM_LOOKUP_REQUEST_CONTENTION,
  SOC_PB_IHP_LARGE_EM_SRC_OR_LL_LOOKUP_ON_WRONG_CYCLE,

  SOC_PB_IHB_INVALID_DESTINATION_VALID = SOC_PB_INTERRUPT_IHB_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),

  SOC_PB_IQM_FREE_BDB_OVF        = SOC_PB_INTERRUPT_IQM_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_IQM_FREE_BDB_UNF,
  SOC_PB_IQM_FULL_USCNT_OVF,
  SOC_PB_IQM_MINI_USCNT_OVF,
  SOC_PB_IQM_QDR_SFT_ERR,
  SOC_PB_IQM_PKT_ENQ_RSRC_ERR,
  SOC_PB_IQM_PKT_ENQ_SN_ERR,
  SOC_PB_IQM_PKT_ENQ_MC_ERR,
  SOC_PB_IQM_PKT_ENQ_QNVALID_ERR,
  SOC_PB_IQM_ST_RPT_OVF,
  SOC_PB_IQM_QROLL_OVER,
  SOC_PB_IQM_VSQ_ROLL_OVER,
  SOC_PB_IQM_DRAM_DYN_SIZE_ROLL_OVER,
  SOC_PB_IQM_CNM_PKT_RJCT,
  SOC_PB_IQM_DOUBLE_CD_ERR,
  SOC_PB_IQM_MTRPA_PACKET_SIZE_ERR,
  SOC_PB_IQM_MTRPB_PACKET_SIZE_ERR,
  SOC_PB_IQM_CRPS_INTR,
  SOC_PB_IQM_ECC_INTR_ERR,
  SOC_PB_IQM_PQDMD_TWO_BERR = SOC_PB_INTERRUPT_IQM_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 1),
  SOC_PB_IQM_TAIL_DSCR_SFT_ERR,
  SOC_PB_IQM_BDBLL_SFT_ERR,
  SOC_PB_IQM_FLUSCNT_SFT_ERR,
  SOC_PB_IQM_MNUSCNT_SFT_ERR,
  SOC_PB_IQM_TXPDM_SFT_ERR,
  SOC_PB_IQM_TXDSCRM_SFT_ERR,
  SOC_PB_IQM_DBFFM_SFT_ERR,
  SOC_PB_IQM_DELFFM_SFT_ERR,
  SOC_PB_IQM_VSQB_QSZ_SFT_ERR,
  SOC_PB_IQM_VSQC_QSZ_SFT_ERR,
  SOC_PB_IQM_VSQD_QSZ_SFT_ERR,
  SOC_PB_IQM_CPDMD_TWO_BERR,
  SOC_PB_IQM_PQDMD_ONE_BERR_FIXED,
  SOC_PB_IQM_TAILDSCR_ONE_BERR_FIXED,
  SOC_PB_IQM_BDBLL_ONE_BERR_FIXED,
  SOC_PB_IQM_FLUSCNT_ONE_BERR_FIXED,
  SOC_PB_IQM_MNUSCNT_ONE_BERR_FIXED,
  SOC_PB_IQM_TXPDM_ONE_BERR_FIXED,
  SOC_PB_IQM_TXDSCRM_ONE_BERR_FIXED,
  SOC_PB_IQM_DBFFM_ONE_BERR_FIXED,
  SOC_PB_IQM_DELFFM_ONE_BERR_FIXED,
  SOC_PB_IQM_VSQB_QSZ_ONE_BERR_FIXED,
  SOC_PB_IQM_VSQC_QSZ_ONE_BERR_FIXED,
  SOC_PB_IQM_VSQD_QSZ_ONE_BERR_FIXED,
  SOC_PB_IQM_CPDMD_ONE_BERR_FIXED,
  SOC_PB_IQM_CRPSA_CNT_OVF				= SOC_PB_INTERRUPT_IQM_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 2),
  SOC_PB_IQM_CRPSA_INVLD_AD_ACC,
  SOC_PB_IQM_CRPSA_INVLD_PTR_ACC,
  SOC_PB_IQM_CRPSA_PRE_READ_FIFO_FULL,
  SOC_PB_IQM_CRPSA_PRE_READ_FIFO_NOT_EMPTY,
  SOC_PB_IQM_CRPSA_DIRECT_RD_WHEN_WAITING,
  SOC_PB_IQM_CRPSA_STATIC_RD_WHEN_WAITING,
  SOC_PB_IQM_CRPSB_CNT_OVF,
  SOC_PB_IQM_CRPSB_INVLD_AD_ACC,
  SOC_PB_IQM_CRPSB_INVLD_PTR_ACC,
  SOC_PB_IQM_CRPSB_PRE_READ_FIFO_FULL,
  SOC_PB_IQM_CRPSB_PRE_READ_FIFO_NOT_EMPTY,
  SOC_PB_IQM_CRPSB_DIRECT_RD_WHEN_WAITING,
  SOC_PB_IQM_CRPSB_STATIC_RD_WHEN_WAITING,

  SOC_PB_QDR_QDR_ECC_INT = SOC_PB_INTERRUPT_QDR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),

  SOC_PB_IPS_DQCQ_DEPTH_OVF      = SOC_PB_INTERRUPT_IPS_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_IPS_EMPTY_DQCQ_WRITE,
  SOC_PB_IPS_QUEUE_ENTERED_DEL,
  SOC_PB_IPS_CREDIT_LOST,
  SOC_PB_IPS_CREDIT_OVERFLOW,
  SOC_PB_IPS_DEQ_COMMAND_TIMEOUT,
  SOC_PB_IPS_DQCQ_OVERFLOW,
  SOC_PB_IPS_PUSH_QUEUE_ACTIVE,
  SOC_PB_IPS_QDESC_ECC_ERR,
  SOC_PB_IPS_QDESC_ECC_ONE_ERR_FIXED,
  SOC_PB_IPS_DQCQMEM_ECC_ERR,
  SOC_PB_IPS_DQCQMEM_ECC_ONE_ERR_FIXED,
  SOC_PB_IPS_FSMRQMEM_ECC_ERR,
  SOC_PB_IPS_FSMRQMEM_ECC_ONE_ERR_FIXED,

  SOC_PB_IPT_SOP_ECC_ERROR         = SOC_PB_INTERRUPT_IPT_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_IPT_MOP_ECC_ERROR,
  SOC_PB_IPT_FDTC_ECC_ERROR,
  SOC_PB_IPT_BDQ_ECC_ERROR,
  SOC_PB_IPT_PDQ_ECC_ERROR,
  SOC_PB_IPT_SOP_ECC_FIXED,
  SOC_PB_IPT_MOP_ECC_FIXED,
  SOC_PB_IPT_FDTC_ECC_FIXED,
  SOC_PB_IPT_BDQ_ECC_FIXED,
  SOC_PB_IPT_PDQ_ECC_FIXED,
  SOC_PB_IPT_CRC_ERR_PKT,
  
  SOC_PB_MMU_ERROR_ECC           = SOC_PB_INTERRUPT_MMU_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_MMU_WAFAA_ECC_ERR       = SOC_PB_INTERRUPT_MMU_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 1),
  SOC_PB_MMU_WAFAB_ECC_ERR,
  SOC_PB_MMU_WAFAC_ECC_ERR,
  SOC_PB_MMU_WAFAD_ECC_ERR,
  SOC_PB_MMU_WAFAE_ECC_ERR,
  SOC_PB_MMU_WAFAF_ECC_ERR,
  SOC_PB_MMU_WAFBA_ECC_ERR,
  SOC_PB_MMU_WAFBB_ECC_ERR,
  SOC_PB_MMU_WAFBC_ECC_ERR,
  SOC_PB_MMU_WAFBD_ECC_ERR,
  SOC_PB_MMU_WAFBE_ECC_ERR,
  SOC_PB_MMU_WAFBF_ECC_ERR,
  SOC_PB_MMU_RAFA_ECC_ERR,
  SOC_PB_MMU_RAFB_ECC_ERR,
  SOC_PB_MMU_RAFC_ECC_ERR,
  SOC_PB_MMU_RAFD_ECC_ERR,
  SOC_PB_MMU_RAFE_ECC_ERR,
  SOC_PB_MMU_RAFF_ECC_ERR,
  SOC_PB_MMU_WFAFA_ECC_ERR,
  SOC_PB_MMU_WFAFB_ECC_ERR,
  SOC_PB_MMU_WFAFC_ECC_ERR,
  SOC_PB_MMU_WFAFD_ECC_ERR,
  SOC_PB_MMU_WFAFE_ECC_ERR,
  SOC_PB_MMU_WFAFF_ECC_ERR,
  SOC_PB_MMU_RFAFA_ECC_ERR,
  SOC_PB_MMU_RFAFB_ECC_ERR,
  SOC_PB_MMU_RFAFC_ECC_ERR,
  SOC_PB_MMU_RFAFD_ECC_ERR,
  SOC_PB_MMU_RFAFE_ECC_ERR,
  SOC_PB_MMU_RFAFF_ECC_ERR,
  SOC_PB_MMU_IDF_ECC_ERR,
  SOC_PB_MMU_FDF_ECC_ERR,

  SOC_PB_DPI_DPI_ERROR_INT       = SOC_PB_INTERRUPT_DPI_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),

  SOC_PB_FDR_FDRADESCCNTO_A      = SOC_PB_INTERRUPT_FDR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_FDR_FDRAUN_EXP_CELL,
  SOC_PB_FDR_IFMAFO_A,
  SOC_PB_FDR_IFMBFO_A,
  SOC_PB_FDR_CPUDATACELLFNE_A0,
  SOC_PB_FDR_CPUDATACELLFNE_A1,
  SOC_PB_FDR_ALTO_A,
  SOC_PB_FDR_FDRA_OUT_OF_SYNC,
  SOC_PB_FDR_FDRA_TAG_ECC_ERR,
  SOC_PB_FDR_FDRA_FILRTER_DROP_INTA,
  SOC_PB_FDR_FDRA_FILRTER_DROP_INTB,
  SOC_PB_FDR_FDRADESCCNTO_B,
  SOC_PB_FDR_FDRBUN_EXP_CELL,
  SOC_PB_FDR_IFMAFO_B,
  SOC_PB_FDR_IFMBFO_B,
  SOC_PB_FDR_CPUDATACELLFNE_B0,
  SOC_PB_FDR_CPUDATACELLFNE_B1,
  SOC_PB_FDR_ALTO_B_,
  SOC_PB_FDR_FDRB_OUT_OF_SYNC_,
  SOC_PB_FDR_FDRB_TAG_ECC_ERR,
  SOC_PB_FDR_FDRB_FILRTER_DROP_INTA,
  SOC_PB_FDR_FDRB_FILRTER_DROP_INTB,
  SOC_PB_FDR_FDR_OUTPU_OUT_OF_SYNC,
  SOC_PB_FDR_FDR_OUT_TAG_ECC_ERR,

  SOC_PB_FDT_UNRCH_DEST_EVT      = SOC_PB_INTERRUPT_FDT_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_FDT_ECC_ERROR,
  SOC_PB_FDT_ECC_ERROR_FIXED,

  SOC_PB_FCR_SRC_DV_CNG_LINK_EV  = SOC_PB_INTERRUPT_FCR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_FCR_CPUCNT_CELL_FNE,
  SOC_PB_FCR_LOCAL_ROUT_FS_OVF,
  SOC_PB_FCR_LOCAL_ROUTRC_OVF,
  SOC_PB_FCR_REACH_FIFO_OVF,
  SOC_PB_FCR_FLOW_FIFO_OVF,
  SOC_PB_FCR_CREDIT_FIFO_OVF,

  SOC_PB_FCT_UNRCH_DEST_EVT      = SOC_PB_INTERRUPT_FCT_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),

  SOC_PB_RTP_LINK_MASK_CHANGE    = SOC_PB_INTERRUPT_RTP_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),

  SOC_PB_FABRIC_MAC_RX_CRCERR    = SOC_PB_INTERRUPT_FABRIC_MAC_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_FABRIC_MAC_WRONG_SIZE   = SOC_PB_INTERRUPT_FABRIC_MAC_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 1),
  SOC_PB_FABRIC_MAC_LOS_INT      = SOC_PB_INTERRUPT_FABRIC_MAC_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 2),
  SOC_PB_FABRIC_MAC_RX_MIS_AERR,
  SOC_PB_FABRIC_MAC_LNKLVL_AGE  = SOC_PB_INTERRUPT_FABRIC_MAC_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 3),
  SOC_PB_FABRIC_MAC_LNKLVL_HALT,   
  SOC_PB_FABRIC_MAC_OOF			= SOC_PB_INTERRUPT_FABRIC_MAC_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 4),
  SOC_PB_FABRIC_MAC_DEC_ERR,
  SOC_PB_FABRIC_MAC_TRANSMIT_ERR = SOC_PB_INTERRUPT_FABRIC_MAC_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 5),
  SOC_PB_FABRIC_MAC_RX_CTRL_OVERFLOW,   

  SOC_PB_MSW_SRD_INTERRUPT       = SOC_PB_INTERRUPT_MSW_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_MSW_SRD0_MACRO_INTERRUPT,
  SOC_PB_MSW_SRD1_MACRO_INTERRUPT,
  SOC_PB_MSW_SRD2_MACRO_INTERRUPT,
  SOC_PB_MSW_SRD3_MACRO_INTERRUPT,
  SOC_PB_MSW_SRD_IPU_INTERRUPT_GROUP_A,
  SOC_PB_MSW_SRD_EPB_INTERRUPT_GROUP_A,
  SOC_PB_MSW_SRD4_MACRO_INTERRUPT,
  SOC_PB_MSW_SRD5_MACRO_INTERRUPT,
  SOC_PB_MSW_SRD6_MACRO_INTERRUPT,
  SOC_PB_MSW_SRD_IPU_INTERRUPT_GROUP_B,
  SOC_PB_MSW_SRD_EPB_INTERRUPT_GROUP_B,
  SOC_PB_MSW_SRD_LANE_INTERRUPT  = SOC_PB_INTERRUPT_MSW_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 1),

  SOC_PB_EGQ_CPU_PACK32_BYTES_ERR = SOC_PB_INTERRUPT_EGQ_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_EGQ_CPU_DATA_ARRIVED_ERR,
  SOC_PB_EGQ_PDM_PAR_ERR,
  SOC_PB_EGQ_PLM_PAR_ERR,
  SOC_PB_EGQ_PACKET_AGED,
  SOC_PB_EGQ_INT_VLANTABLE_OOR,
  SOC_PB_EGQ_VLAN_EMPTY_INT,
  SOC_PB_EGQ_INT_DIF_AF,
  SOC_PB_EGQ_CFC_FC_INT,
  SOC_PB_EGQ_NIFA_FC_INT,
  SOC_PB_EGQ_NIFB_FC_INT,
  SOC_PB_EGQ_SVEM_ERROR_CAM_TABLE_FULL,
  SOC_PB_EGQ_SVEM_ERROR_TABLE_COHERENCY,
  SOC_PB_EGQ_SVEM_ERROR_DELETE_UNKNOWN_KEY,
  SOC_PB_EGQ_SVEM_ERROR_REACHED_MAX_ENTRY_LIMIT,
  SOC_PB_EGQ_SVEM_WARNING_INSERTED_EXISTING,
  SOC_PB_EGQ_SVEM_MANAGEMENT_UNIT_FAILURE_VALID,
  SOC_PB_EGQ_SVEM_MANAGEMENT_COMPLETED,
  SOC_PB_EGQ_ERPP_ERROR_CODE_INT,
  SOC_PB_EGQ_ERPP_DISCARD_INT_VEC,
  SOC_PB_EGQ_PKT_REAS_INT_VEC,
  SOC_PB_EGQ_CNT_OVF_INT_VEC,
  SOC_PB_EGQ_ECC_ERR_VEC,
  SOC_PB_EGQ_CNM_INTERCEPT_DISCARD     = SOC_PB_INTERRUPT_EGQ_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 1),
  SOC_PB_EGQ_CFM_TRAP_DISCARD,
  SOC_PB_EGQ_NO_VSI_TRANSLATION_DISCARD,
  SOC_PB_EGQ_DSS_STACKING_DISCARD,
  SOC_PB_EGQ_LAG_MULTICAST_DISCARD,
  SOC_PB_EGQ_EXCLUDE_SRC_DISCARD,
  SOC_PB_EGQ_VLAN_MEMBERSHIP_DISCARD,
  SOC_PB_EGQ_UNACCEPTABLE_FRAME_TYPE_DISCARD,
  SOC_PB_EGQ_SRC_EQUAL_DEST_DISCARD,
  SOC_PB_EGQ_UNKNOWN_DA_DISCARD,
  SOC_PB_EGQ_SPLIT_HORIZON_DISCARD,
  SOC_PB_EGQ_PRIVATE_VLAN_DISCARD,
  SOC_PB_EGQ_TTL_SCOPE_DISCARD,
  SOC_PB_EGQ_MTU_VIOLATION_DISCARD,
  SOC_PB_EGQ_TRILL_TTL_ZERO_DISCARD,
  SOC_PB_EGQ_TRILL_SAME_INTERFACE_DISCARD,
  SOC_PB_EGQ_BOUNCE_BACK_DISCARD,
  SOC_PB_EGQ_ILLEGAL_EEP_DISCARD,
  SOC_PB_EGQ_VSC_PKT_SIZE_ERR = SOC_PB_INTERRUPT_EGQ_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 2),
  SOC_PB_EGQ_VSC_MISSING_SOP_ERR,
  SOC_PB_EGQ_VSC_FRAG_NUM_ERR,
  SOC_PB_EGQ_VSC_PKT_CRC_ERR,
  SOC_PB_EGQ_VSC_SOP_INTR_MOP_ERR,
  SOC_PB_EGQ_VSC_FIX129_ERR,
  SOC_PB_EGQ_VSC_EOP_SIZE_ERR,
  SOC_PB_EGQ_FSC_SONTS_ERR,
  SOC_PB_EGQ_FSC_PKT_SIZE_ERR,
  SOC_PB_EGQ_FSC_MISSING_SOP_ERR,
  SOC_PB_EGQ_FSC_FRAG_NUM_ERR,
  SOC_PB_EGQ_FSC_SOP_INTR_MOP_ERR,
  SOC_PB_EGQ_FSC_EOP_SIZE_ERR,
  SOC_PB_EGQ_FSC_SEQUENCE_ERR,
  SOC_PB_EGQ_CSR_PKT_SIZE_ERR,
  SOC_PB_EGQ_CSR_UNEXPECTED_EOP_ERR,
  SOC_PB_EGQ_CSR_MISSING_EOP_ERR,
  SOC_PB_EGQ_CSR_SOP_AND_EOP_ERR,
  SOC_PB_EGQ_CSR_SIZE_PARITY_ERR,
  SOC_PB_EGQ_REJ_BUFF_SCH,
  SOC_PB_EGQ_REJ_BUFF_USC,
  SOC_PB_EGQ_REJ_DESC_SCH,
  SOC_PB_EGQ_REJ_DESC_USC,
  SOC_PB_EGQ_PRP_SOP_CNT_OVF_INT = SOC_PB_INTERRUPT_EGQ_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 3),
  SOC_PB_EGQ_BUFLINK_ECC_ERR = SOC_PB_INTERRUPT_EGQ_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 4),
  SOC_PB_EGQ_BUFLINK_ECC_FIX,
  SOC_PB_EGQ_RCNT_ECC_ERR,
  SOC_PB_EGQ_RCNT_ECC_FIX,  

  SOC_PB_EPNI_MIRR_OVF_INT = SOC_PB_INTERRUPT_EPNI_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_EPNI_INVALID_MPLS_CMD_INT,
  SOC_PB_EPNI_INVALID_IP_TUNNEL_CMD_INT,
  SOC_PB_EPNI_INVALID_ETH_CODE_INT,
  SOC_PB_EPNI_ESEM_INT_VEC,
  SOC_PB_EPNI_ECC_ERR_VEC,

  SOC_PB_CFC_OBRXA_LOCK_ERR      = SOC_PB_INTERRUPT_CFC_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_CFC_OBRXB_LOCK_ERR,
  SOC_PB_CFC_OBRXA_OUT_OF_FRM,
  SOC_PB_CFC_OBRXB_OUT_OF_FRM,
  SOC_PB_CFC_OBRXA_DIP2_ALARM,
  SOC_PB_CFC_OBRXB_DIP2_ALARM,
  SOC_PB_CFC_OBRXA_FRM_ERR,
  SOC_PB_CFC_OBRXB_FRM_ERR,
  SOC_PB_CFC_OBRXA_DIP2_ERR,
  SOC_PB_CFC_OBRXB_DIP2_ERR,
  SOC_PB_CFC_ILKN0_OOB_RX_CRC_ERR,     
  SOC_PB_CFC_ILKN0_OOB_RX_OVERFLOW,
  SOC_PB_CFC_ILKN0_OOB_RX_IF_STAT_ERR,
  SOC_PB_CFC_ILKN0_OOB_RX_LANES_STAT_ERR,
  SOC_PB_CFC_ILKN1_OOB_RX_CRC_ERR,
  SOC_PB_CFC_ILKN1_OOB_RX_OVERFLOW,
  SOC_PB_CFC_ILKN1_OOB_RX_IF_STAT_ERR,
  SOC_PB_CFC_ILKN1_OOB_RX_LANES_STAT_ERR,


  SOC_PB_SCH_ACT_FLOW_BAD_PARAMS = SOC_PB_INTERRUPT_SCH_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),
  SOC_PB_SCH_SHP_FLOW_BAD_PARAMS,
  SOC_PB_SCH_RESTART_FLOW_EVENT,
  SOC_PB_SCH_SMPTHROW_SCL_MSG,
  SOC_PB_SCH_SMPFULL_LEVEL1,
  SOC_PB_SCH_SMPFULL_LEVEL2,
  SOC_PB_SCH_FCTFIFOOVF,
  SOC_PB_SCH_ECC_ERROR,


  SOC_PB_QDR_ECC = SOC_PB_INTERRUPT_QDR_ID * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0),

  SOC_PB_INTERRUPT_NOF_CAUSES = (SOC_PB_INTERRUPT_NOF_MODULES * SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_MOD + (SOC_PB_INTERRUPT_MAX_NOF_FIELD_IN_REG * 0))
} SOC_PB_INTERRUPT_CAUSE;

typedef struct
{
  uint32 nof_interrupts;

  struct
  {
    uint32 addr;
    uint32 data;
  } interrupt_data[SOC_PB_INTERRUPT_SINGLE_MAX_NOF_INTERRUPT_DATA];

} SOC_PB_INTERRUPT_SINGLE_STRUCT;

typedef enum
{
  /*
   *  Recommended action: ingress quick recovery
   */
  SOC_PB_INT_RECOVERY_ACTION_QUICK_RECOVERY = 0,
  /*
   *  Recommended action: full reset to Soc_petra.
   */
  SOC_PB_INT_RECOVERY_ACTION_FULL_DEVICE_RESET,
  /*
   *  Represents that there isn't defined a recovery action.
   */
  SOC_PB_INT_RECOVERY_ACTION_UNKNOWN_ACTION,
  /*
   *  Total number of recommended recovery actions.
   */
  SOC_PB_INT_NOF_RECOVERY_ACTIONS
} SOC_PB_INT_RECOVERY_ACTION;

/* } */

/*************
 * GLOBALS   *
 *************/
/* { */

/* } */

/*************
 * FUNCTIONS *
 *************/
/* { */

/* } */

#include <soc/dpp/SAND/Utils/sand_footer.h>

/* } __SOC_PB_API_INTERRUPT_SERVICE_INCLUDED__*/
#endif
