#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/cosq

include ${SDK}/make/Make.config
subdirs += flow_control egress ingress scheduler latency

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxcosq

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

