/*********************************************************************
*
* (C) Copyright Broadcom Corporation 2006-2007
*
**********************************************************************
*                                                                     
* @filename   src/nls/web/routing/strlib_routing_web.c                                                      
*                                                                     
* @purpose    Strings Library                                                      
*                                                                     
* @component  Common Strings Library                                                      
*                                                                     
* @comments   none                                                    
*                                                                     
* @create     01/10/2007                                                      
*                                                                     
* @author     Rama Sasthri, Kristipati                                
*                                                                     
* @end                                                                
*                                                                     
*********************************************************************/

#include "strlib_routing_web.h"

L7_char8 *pStrInfo_routing_Mbps = "%d mbps";
L7_char8 *pStrInfo_routing_0None = "0 - None";
L7_char8 *pStrInfo_routing_000_1 = "0.0.0";
L7_char8 *pStrInfo_routing_01 = "0.1";
L7_char8 *pStrInfo_routing_1Simple = "1 - Simple";
L7_char8 *pStrInfo_routing_DynRenewModeInvalid = ": Dynamic Renew Mode Invalid";
L7_char8 *pStrInfo_routing_TdClassTbldata = "<   td CLASS=\"tabledata\">";
L7_char8 *pStrInfo_routing_OptionValExternalImportExternalLsasOption = "<OPTION VALUE = \"external\">Import External LSAs</OPTION>";
L7_char8 *pStrInfo_routing_OptionValNoLsasImportNoLsasOption = "<OPTION VALUE = \"no_lsas\">Import No LSAs</OPTION>";
L7_char8 *pStrInfo_routing_OptionValNssasImportNssasOption = "<OPTION VALUE = \"nssas\">Import NSSAs</OPTION>";
L7_char8 *pStrInfo_routing_ArpCreate = "ARP Create";
L7_char8 *pStrInfo_routing_ArpTblCfg = "ARP Table Configuration";
L7_char8 *pStrInfo_routing_ActiveRoutes = "Active Routes";
L7_char8 *pStrInfo_routing_AddSecondary = "Add Secondary";
L7_char8 *pStrInfo_routing_AdministrativeState = "Administrative State";
L7_char8 *pStrInfo_routing_AdvertiseAddr = "Advertise Address";
L7_char8 *pStrInfo_routing_AdvertiseAddrCanBeEither224001Or255255255255 = "Advertise Address (Can be either 224.0.0.1 or 255.255.255.255)";
L7_char8 *pStrInfo_routing_AdvertiseLifetimeSecs = "Advertise Lifetime (secs)";
L7_char8 *pStrInfo_routing_AdvertiseMode = "Advertise Mode";
L7_char8 *pStrInfo_routing_AgeTimeSecs = "Age Time (secs)";
L7_char8 *pStrInfo_routing_AllDynEntries = "All Dynamic Entries";
L7_char8 *pStrInfo_routing_AllDynAndGatewayEntries = "All Dynamic and Gateway Entries";
L7_char8 *pStrInfo_routing_Area_1 = "Area";
L7_char8 *pStrInfo_routing_AuthType = "Auth Type";
L7_char8 *pStrInfo_routing_AuthData = "Authentication Data";
L7_char8 *pStrInfo_routing_BootpDhcpRelayAgentCfg = "BOOTP/DHCP Relay Agent Configuration";
L7_char8 *pStrInfo_routing_BootpDhcpRelayAgentStatus = "BOOTP/DHCP Relay Agent Status";
L7_char8 *pStrInfo_routing_BadRipPktsRcvd = "Bad RIP Packets Received";
L7_char8 *pStrInfo_routing_BridgingCfg = "Bridging Configuration";
L7_char8 *pStrInfo_routing_BridgingPort = "Bridging Port";
L7_char8 *pStrInfo_routing_BridgingState = "Bridging State";
L7_char8 *pStrInfo_routing_BridgingSwitch = "Bridging Switch";
L7_char8 *pStrInfo_routing_CheckCondMinAdvertiseIntvlMaxAdvertiseIntvlAdvertiseLifetime = "Check condition - Minimum Advertise Interval <= Maximum Advertise Interval <= Advertise Lifetime.";
L7_char8 *pStrInfo_routing_CircuitIdOptionMode = "Circuit ID Option Mode";
L7_char8 *pStrInfo_routing_CfgureAuth = "Configure Authentication";
L7_char8 *pStrInfo_routing_CfguredRoutes = "Configured Routes";
L7_char8 *pStrInfo_routing_DelIpAddr = "Delete IP Address";
L7_char8 *pStrInfo_routing_DelLoopback = "Delete Loopback";
L7_char8 *pStrInfo_routing_DelPrimary = "Delete Primary";
L7_char8 *pStrInfo_routing_DelSelectedAddr = "Delete Selected Address";
L7_char8 *pStrInfo_routing_DelSelectedSecondary = "Delete Selected Secondary";
L7_char8 *pStrInfo_routing_DelTunnel = "Delete Tunnel";
L7_char8 *pStrInfo_routing_DeletingPrimaryIpAddr = "Deleting the Primary IP Address";
L7_char8 *pStrInfo_routing_DeletingSpecifiedSecondaryIpAddr = "Deleting the specified Secondary IP Address";
L7_char8 *pStrInfo_routing_DeletingSpecifiedHelperIpAddr = "Deleting the specified Helper  IP Address";
L7_char8 *pStrInfo_routing_DemandAging = "Demand Aging";
L7_char8 *pStrInfo_routing_DynRenew = "Dynamic Renew";
L7_char8 *pStrErr_routing_FailedTo = "Failed to %s.";
L7_char8 *pStrErr_routing_FailedToClrDeflMetric = "Failed to clear Default Metric";
L7_char8 *pStrErr_routing_FailedToCreateStaticRoute = "Failed to create the static route.";
L7_char8 *pStrErr_routing_FailedToSet_2 = "Failed to set";
L7_char8 *pStrErr_routing_FailedToSetAdvertiseLifetime = "Failed to set Advertise Lifetime";
L7_char8 *pStrErr_routing_FailedToSetAdvertiseIntvls = "Failed to set Advertise intervals";
L7_char8 *pStrErr_routing_FailedToSetMaxAdvertiseIntvl = "Failed to set Maximum Advertise Interval";
L7_char8 *pStrErr_routing_FailedToSetMinAdvertiseIntvl = "Failed to set Minimum Advertise Interval";
L7_char8 *pStrErr_routing_FailedToSetProxyArp = "Failed to set Proxy ARP";
L7_char8 *pStrInfo_routing_GlobalQueries = "Global Queries";
L7_char8 *pStrInfo_routing_GlobalRouteChgs = "Global Route Changes";
L7_char8 *pStrInfo_routing_HellosSuppressed = "Hellos Suppressed";
L7_char8 *pStrInfo_routing_Help_1 = "Help";
L7_char8 *pStrInfo_routing_HelpForBcastStormRecovery = "Help for Broadcast Storm Recovery";
L7_char8 *pStrInfo_routing_IpAddrAndSubnetMask = "IP Address and Subnet Mask";
L7_char8 *pStrInfo_routing_IpCfg = "IP Configuration";
L7_char8 *pStrInfo_routing_IpIntfCfg = "IP Interface Configuration";
L7_char8 *pStrInfo_routing_IpIntfHelperAddrCfg = " Helper IP Interface Configuration";
L7_char8 *pStrInfo_routing_IpIntfSecondaryAddrCfg = "IP Interface Secondary Address Configuration";
L7_char8 *pStrInfo_routing_IpSpoofingMode = "IP Spoofing Mode";
L7_char8 *pStrInfo_routing_IpStats = "IP Statistics";
L7_char8 *pStrInfo_routing_IpAddrConflictsWithAnotherIpAddrOnIntf = "IP address conflicts with another IP address on this interface.";
L7_char8 *pStrInfo_routing_Ipv6InIpv4 = "6-in-4-configured";
L7_char8 *pStrInfo_routing_Ipv6ToIpv4 = "6-to-4";
L7_char8 *pStrInfo_routing_Ipv4AddrAssignmentFailed = "IPv4 Address Assignment Failed";
L7_char8 *pStrInfo_routing_Ipv6Mode_1 = "IPv6 Mode";
L7_char8 *pStrInfo_routing_Icmpoutaddrmaskreps = "IcmpOutAddrMaskReps";
L7_char8 *pStrInfo_routing_Icmpoutechos = "IcmpOutEchos";
L7_char8 *pStrErr_routing_IpAddrAddrOfDynGatewayEntryDesired = "Incorrect IP Address. Address of Dynamic/Gateway Entry desired.";
L7_char8 *pStrInfo_routing_IntfBridging = "Interface Bridging";
L7_char8 *pStrInfo_routing_IntfIpAddr = "Interface IP Address";
L7_char8 *pStrErr_routing_MetricValValidRange015 = "Invalid Metric Value:  Valid Range 0 - 15";
L7_char8 *pStrErr_routing_MetricValValidRange016777214_1 = "Invalid Metric Value:  Valid Range 0 - 16777214.";
L7_char8 *pStrErr_routing_PrefChg = "Invalid Preference Change";
L7_char8 *pStrErr_routing_ValForDeflMetricValidRange116777214 = "Invalid Value for Default Metric..Valid Range 1 - 16777214";
L7_char8 *pStrErr_routing_PrefValConflictsWithOspfSpecification = "Invalid preference value conflicts with OSPF specification.";
L7_char8 *pStrInfo_routing_LocalProxyArp = "Local Proxy ARP";
L7_char8 *pStrInfo_routing_LoopbackCfg = "Loopback Configuration";
L7_char8 *pStrInfo_routing_LoopbackId = "Loopback ID";
L7_char8 *pStrInfo_routing_LoopbackSummary = "Loopback Summary";
L7_char8 *pStrInfo_routing_MaxAdvertiseIntvlSecs = "Maximum Advertise Interval (secs)";
L7_char8 *pStrInfo_routing_MetricDefl = "Metric Default";
L7_char8 *pStrInfo_routing_MetricDelay = "Metric Delay";
L7_char8 *pStrInfo_routing_MetricMonetary = "Metric Monetary";
L7_char8 *pStrInfo_routing_MetricThroughput = "Metric Throughput";
L7_char8 *pStrInfo_routing_MinAdvertiseIntvlSecs = "Minimum Advertise Interval (secs)";
L7_char8 *pStrInfo_routing_MinWaitTimeSecs = "Minimum Wait Time (secs)";
L7_char8 *pStrInfo_routing_Missing12702 = "Missing 12702";
L7_char8 *pStrInfo_routing_Missing1287 = "Missing 1287";
L7_char8 *pStrInfo_routing_NbmaPollIntvlSecs = "NBMA Poll Interval (secs)";
L7_char8 *pStrInfo_routing_NeighborIntfIdx = "Neighbor Interface Index";
L7_char8 *pStrInfo_routing_NwAddr = "Network Address";
L7_char8 *pStrInfo_routing_NoVirtualRtrIntfsAvailable = "No Virtual Router Interfaces Available";
L7_char8 *pStrInfo_routing_NoRoutingPortsDefinedAtTime = "No routing ports defined at this time";
L7_char8 *pStrInfo_routing_NoteAdvertiseLifetimeValSetToDefl = "Note: Advertise Lifetime value set to default.";
L7_char8 *pStrInfo_routing_NoteMaxAdvertiseIntvlValSetToDefl = "Note: Maximum Advertise Interval value set to default.";
L7_char8 *pStrInfo_routing_NoteMinAdvertiseIntvlValSetToDefl = "Note: Minimum Advertise Interval value set to default.";
L7_char8 *pStrInfo_routing_OspfAdminState = "OSPF Admin State";
L7_char8 *pStrInfo_routing_OspfAreaCfg = "OSPF Area Configuration";
L7_char8 *pStrInfo_routing_OspfAreaRangeCfg = "OSPF Area Range Configuration";
L7_char8 *pStrInfo_routing_OspfCfg = "OSPF Configuration";
L7_char8 *pStrInfo_routing_OspfIntfAuthCfg = "OSPF Interface Authentication Configuration";
L7_char8 *pStrInfo_routing_OspfIntfCfg = "OSPF Interface Configuration";
L7_char8 *pStrInfo_routing_OspfIntfStats = "OSPF Interface Statistics";
L7_char8 *pStrInfo_routing_OspfLsaDbase = "OSPF LSA Database";
L7_char8 *pStrInfo_routing_OspfLinkStateDbase = "OSPF Link State Database";
L7_char8 *pStrInfo_routing_OspfLinkStateDbaseDetailed = "OSPF Link State Database Detailed";
L7_char8 *pStrInfo_routing_OspfNssaType1 = "OSPF NSSA Type-1";
L7_char8 *pStrInfo_routing_OspfNssaType2 = "OSPF NSSA Type-2";
L7_char8 *pStrInfo_routing_OspfNeighborCfg = "OSPF Neighbor Configuration";
L7_char8 *pStrInfo_routing_OspfNeighborTbl = "OSPF Neighbor Table";
L7_char8 *pStrInfo_routing_OspfRouteRedistributionCfg = "OSPF Route Redistribution Configuration";
L7_char8 *pStrInfo_routing_OspfRouteRedistributionSummary = "OSPF Route Redistribution Summary";
L7_char8 *pStrInfo_routing_OspfStubAreaSummary = "OSPF Stub Area Summary";
L7_char8 *pStrInfo_routing_OspfVirtualLinkCfg = "OSPF Virtual Link Configuration";
L7_char8 *pStrInfo_routing_OspfVirtualLinkSummary = "OSPF Virtual Link Summary";
L7_char8 *pStrInfo_routing_OpaqueLsaStatus = "Opaque LSA Status";
L7_char8 *pStrInfo_routing_Owner = "Address Owner";
L7_char8 *pStrInfo_routing_ParseFailure = "Parse failure";
L7_char8 *pStrInfo_routing_PeerRtrIpAddr = "Peer Router IP Address";
L7_char8 *pStrInfo_routing_Permanence = "Permanence";
L7_char8 *pStrInfo_routing_Permanent = "Permanent";
L7_char8 *pStrInfo_routing_PleaseEnterAuthData = "Please Enter Authentication Data";
L7_char8 *pStrInfo_routing_PointToMultipoint = "Point-to-Multipoint";
L7_char8 *pStrInfo_routing_PrefLvl = "Preference Level";
L7_char8 *pStrInfo_routing_PriSetToVirtualIpAddrSameAsIntfIpAddr = "Priority being set to %d: Virtual IP address same as Interface IP address";
L7_char8 *pStrInfo_routing_PriSetToDefl = "Priority being set to the default: %s";
L7_char8 *pStrInfo_routing_RipCfg = "RIP Configuration";
L7_char8 *pStrInfo_routing_RipDeflMetric = "RIP Default Metric";
L7_char8 *pStrInfo_routing_RipIntfAuthCfg = "RIP Interface Authentication Configuration";
L7_char8 *pStrInfo_routing_RipIntfCfg = "RIP Interface Configuration";
L7_char8 *pStrInfo_routing_RipIntfSummary = "RIP Interface Summary";
L7_char8 *pStrInfo_routing_RipRouteRedistributionCfg = "RIP Route Redistribution Configuration";
L7_char8 *pStrInfo_routing_RipRouteRedistributionSummary = "RIP Route Redistribution Summary";
L7_char8 *pStrInfo_routing_RipVer = "RIP Version";
L7_char8 *pStrInfo_routing_ReceiveVer = "Receive Version";
L7_char8 *pStrInfo_routing_Reliability = "Reliability";
L7_char8 *pStrInfo_routing_RemoveIpAddr = "Remove IP Address";
L7_char8 *pStrInfo_routing_RemoveFromTbl = "Remove from Table";
L7_char8 *pStrInfo_routing_RouteType = "Route Type";
L7_char8 *pStrInfo_routing_RtrBestRoutesTbl = "Router Best Routes Table";
L7_char8 *pStrInfo_routing_RtrDisc_1 = "Router Discovery";
L7_char8 *pStrInfo_routing_RtrDiscCfg = "Router Discovery Configuration";
L7_char8 *pStrInfo_routing_RtrDiscStatus = "Router Discovery Status";
L7_char8 *pStrInfo_routing_RtrRipPeers = "Router RIP Peers";
L7_char8 *pStrInfo_routing_RtrRouteEntryCfg = "Router Route Entry Configuration";
L7_char8 *pStrInfo_routing_RtrRouteEntryCreate = "Router Route Entry Create";
L7_char8 *pStrInfo_routing_RtrRoutePrefsCfg = "Router Route Preferences Configuration";
L7_char8 *pStrInfo_routing_RtrRouteTbl = "Router Route Table";
L7_char8 *pStrInfo_routing_RoutingState = "Routing State";
L7_char8 *pStrInfo_routing_SpfDelaytime = "SPF DelayTime";
L7_char8 *pStrInfo_routing_SpfHoldtime = "SPF HoldTime";
L7_char8 *pStrInfo_routing_SecondaryIpAddr = "Secondary IP Address";
L7_char8 *pStrInfo_routing_SendVer = "Send Version";
L7_char8 *pStrInfo_routing_SlotId_1 = "Slot ID";
L7_char8 *pStrInfo_routing_SpecificDynGatewayEntry = "Specific Dynamic/Gateway Entry";
L7_char8 *pStrInfo_routing_SpecificStaticEntry = "Specific Static Entry";
L7_char8 *pStrInfo_routing_SubnetMaskMustBeContiguous = "Subnet mask must be contiguous.";
L7_char8 *pStrInfo_routing_SubnetMaskMustHaveContiguousOnesAndBe30BitsOrShorter = "Subnet mask must have contiguous ones and be 30 bits or shorter.";
L7_char8 *pStrInfo_routing_SubnetsModeForSelectedSrc = "Subnets Mode for Selected Source";
L7_char8 *pStrInfo_routing_DeflRouteWillNotTakeEffectUntilARoutingIntfBelongingToSameSubnetAsNextHopAddrIsCreatedAndActivated = "The default route will not take effect until a routing interface belonging to the same subnet as the next hop address is created and activated.";
L7_char8 *pStrInfo_routing_SpecifiedIpAndSubnetMaskAreInvalidForStaticRoutesToCreateADeflRouteSelectDeflInRouteTypeField = "The specified IP and subnet mask are invalid for static routes.  To create a default route, select 'Default' in the Route Type field.";
L7_char8 *pStrInfo_routing_SpecifiedStaticRouteAddrIsInvalid = "The specified static route address is invalid.";
L7_char8 *pStrInfo_routing_VrrpCfgAlreadyExists = "This Vrrp Configuration already exists.";
L7_char8 *pStrInfo_routing_Throughput = "Throughput";
L7_char8 *pStrInfo_routing_ToSetPriTo255VirtualIpAddrShldBeSameAsIntfIpAddr = "To set priority to 255, Virtual IP Address should be the same as Interface IP Address.";
L7_char8 *pStrInfo_routing_TrackInterface = "Track Interface";
L7_char8 *pStrInfo_routing_TrackRoute = "Track Route";
L7_char8 *pStrInfo_routing_TrackRoutePfxLen = "Track Route PfxLen";
L7_char8 *pStrInfo_routing_TrackRoutePfx = "Track Route Pfx";
L7_char8 *pStrInfo_routing_TunnelCfg = "Tunnel Configuration";
L7_char8 *pStrInfo_routing_TunnelDstIpv4Addr = "Tunnel Destination IPv4 Address";
L7_char8 *pStrInfo_routing_TunnelId = "Tunnel ID";
L7_char8 *pStrInfo_routing_TunnelMode_1 = "Tunnel Mode";
L7_char8 *pStrInfo_routing_TunnelSrcIpv4Addr = "Tunnel Source IPv4 Address";
L7_char8 *pStrInfo_routing_TunnelSrcIntf = "Tunnel Source Interface";
L7_char8 *pStrInfo_routing_TunnelSummary = "Tunnel Summary";
L7_char8 *pStrInfo_routing_TypeOfService = "Type of Service";
L7_char8 *pStrInfo_routing_VlanRoutingCfg = "VLAN Routing Configuration";
L7_char8 *pStrInfo_routing_VlanRoutingSummary = "VLAN Routing Summary";
L7_char8 *pStrInfo_routing_VlanRoutingModeCantBeEnbldOnMgmtVlan = "VLAN Routing mode cannot be enabled on management vlan";
L7_char8 *pStrInfo_routing_VlanTagging_2 = "VLAN Tagging";
L7_char8 *pStrInfo_routing_Vrid_1 = "VRID";
L7_char8 *pStrInfo_routing_VrrpCfg = "VRRP Configuration";
L7_char8 *pStrInfo_routing_VrrpSecondaryAddrCfg = "VRRP Secondary Address Configuration";
L7_char8 *pStrInfo_routing_VrrpIntfTrackCfg = "VRRP Interface Tracking Configuration";
L7_char8 *pStrInfo_routing_VrrpIntfTrackCfgAdd = "VRRP Interface Tracking";
L7_char8 *pStrInfo_routing_VrrpRoutTrackCfg = "VRRP Route Tracking Configuration";
L7_char8 *pStrInfo_routing_VrrpRoutTrackCfgAdd = "VRRP Route Tracking";
L7_char8 *pStrErr_routing_FieldOutOfRangeLong = "Value (%ld) is out of range for %s. The valid range is %d to %d.";
L7_char8 *pStrInfo_routing_ValsForOspfIntraMustBeLessThanOspfInter = "Values for ''OSPF Intra'' must be less than ''OSPF Inter''.";
L7_char8 *pStrInfo_routing_ValsForOspfType1MustBeLessThanOspfType2 = "Values for ''OSPF Type-1'' must be less than ''OSPF Type-2''.";
L7_char8 *pStrInfo_routing_Virtual = "Virtual";
L7_char8 *pStrInfo_routing_VirtualIpAddr = "Virtual IP Address";
L7_char8 *pStrInfo_routing_VirtualRtrCfg = "Virtual Router Configuration";
L7_char8 *pStrInfo_routing_VirtualRtrStats = "Virtual Router Statistics";
L7_char8 *pStrInfo_routing_VirtualRtrStatus = "Virtual Router Status";
L7_char8 *pStrInfo_routing_Error_4 = "[error]";
L7_char8 *pStrInfo_routing_AddingSecondaryIpAddr = "adding the Secondary IP Address";
L7_char8 *pStrInfo_routing_AddingHelperIpAddr = "adding the Helper IP Address";
L7_char8 *pStrInfo_routing_AdvertiseLife = "advertise_life";
L7_char8 *pStrInfo_routing_AdvertiseMax = "advertise_max";
L7_char8 *pStrInfo_routing_AdvertiseMin = "advertise_min";
L7_char8 *pStrInfo_routing_HtmlFileArpCreate1 = "arp_create1.html";
L7_char8 *pStrInfo_routing_HtmlFileArpTblCfg = "arp_table_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileBridgingCfg = "bridging_cfg.html";
L7_char8 *pStrInfo_routing_DelSpecifiedVirtualRtrCfgStatusMayBeActive = "delete the specified virtual router configuration.  Status may be Active.";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingIpHelpLayer3ipArpCreate = "href=\"/routing/ip/help_layer3ip.html#arp_create\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingIpHelpLayer3ipArpTbl = "href=\"/routing/ip/help_layer3ip.html#arp_table\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingIpHelpLayer3ipIntfipcfg = "href=\"/routing/ip/help_layer3ip.html#intfipcfg\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingIpHelpLayer3ipHelperIpCfg = "href=\"/routing/ip/help_layer3ip.html#intfhelperipcfg\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingIpHelpLayer3ipIpcfg = "href=\"/routing/ip/help_layer3ip.html#ipcfg\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingIpHelpLayer3ipIpstats = "href=\"/routing/ip/help_layer3ip.html#ipstats\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingIpHelpLayer3ipSecIpCfg = "href=\"/routing/ip/help_layer3ip.html#sec_ip_cfg\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingLoopbackHelpLoopbackLoopbackconfig = "href=\"/routing/loopback/help_loopback.html#loopbackconfig\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingLoopbackHelpLoopbackLoopbacksumm = "href=\"/routing/loopback/help_loopback.html#loopbacksumm\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfAreaRange = "href=\"/routing/ospf/help_ospf.html#area_range\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfLsadb = "href=\"/routing/ospf/help_ospf.html#lsadb\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfLsdbDet = "href=\"/routing/ospf/help_ospf.html#lsdb_det\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfLsdbSumm = "href=\"/routing/ospf/help_ospf.html#lsdb_summ\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfOspfRtRdstrbtnCfg = "href=\"/routing/ospf/help_ospf.html#ospf_rt_rdstrbtn_cfg\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfOspfRtRdstrbtnSumm = "href=\"/routing/ospf/help_ospf.html#ospf_rt_rdstrbtn_summ\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfOspfarea = "href=\"/routing/ospf/help_ospf.html#ospfarea\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfOspfinfo = "href=\"/routing/ospf/help_ospf.html#ospfinfo\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfOspfintfcfg = "href=\"/routing/ospf/help_ospf.html#ospfintfcfg\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfOspfintfstats = "href=\"/routing/ospf/help_ospf.html#ospfintfstats\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfStubsummary = "href=\"/routing/ospf/help_ospf.html#stubSummary\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfVirtLink = "href=\"/routing/ospf/help_ospf.html#virt_link\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfVirtLinkSumm = "href=\"/routing/ospf/help_ospf.html#virt_link_summ\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRelayRelayHelpCfg = "href=\"/routing/relay/relay_help.html#cfg\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRelayRelayHelpStatus = "href=\"/routing/relay/relay_help.html#status\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRipHelpRipRipDet = "href=\"/routing/rip/help_rip.html#rip_det\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRipHelpRipRipInfo = "href=\"/routing/rip/help_rip.html#rip_info\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRipHelpRipRipRtRdstrbtnCfg = "href=\"/routing/rip/help_rip.html#rip_rt_rdstrbtn_cfg\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRipHelpRipRipRtRdstrbtnSumm = "href=\"/routing/rip/help_rip.html#rip_rt_rdstrbtn_summ\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRipHelpRipRipSumm = "href=\"/routing/rip/help_rip.html#rip_summ\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRtrDiscHelpRtrDiscRtrDisc = "href=\"/routing/router_discovery/help_rtr_discovery.html#rtr_discovery\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRtrDiscHelpRtrDiscRtrDiscStatus = "href=\"/routing/router_discovery/help_rtr_discovery.html#rtr_discovery_status\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRoutingHelpLayer3NbrNbrDt = "href=\"/routing/ospf/help_layer3_nbr.html#nbr_dt\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRoutingHelpLayer3NbrNbrSumm = "href=\"/routing/ospf/help_layer3_nbr.html#nbr_summ\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRoutingHelpRtrBestRtTbl = "href=\"/routing/routing/help_router.html#best_rt_table\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRoutingHelpRtrRtCfgured = "href=\"/routing/routing/help_router.html#rt_configured\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRoutingHelpRtrRtEntry = "href=\"/routing/routing/help_router.html#rt_entry\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRoutingHelpRtrRtEntryCreate = "href=\"/routing/routing/help_router.html#rt_entry_create\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRoutingHelpRtrRtPrefs = "href=\"/routing/routing/help_router.html#rt_prefs\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingRoutingHelpRtrRtTbl = "href=\"/routing/routing/help_router.html#rt_table\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingTunnelHelpTunnelTunnelcfg = "href=\"/routing/tunnel/help_tunnel.html#tunnelcfg\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingTunnelHelpTunnelTunnelsumm = "href=\"/routing/tunnel/help_tunnel.html#tunnelsumm\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingVlanRoutingHelpVlanRoutingVrcfg = "href=\"/routing/vlan_routing/help_vlan_routing.html#vrcfg\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingVlanRoutingHelpVlanRoutingVrsum = "href=\"/routing/vlan_routing/help_vlan_routing.html#vrsum\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingVrrpHelpVrrpVrcfg = "href=\"/routing/vrrp/help_vrrp.html#vrcfg\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingVrrpHelpVrrpVrrpcfg = "href=\"/routing/vrrp/help_vrrp.html#vrrpcfg\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingVrrpHelpVrrpVrsecondary = "href=\"/routing/vrrp/help_vrrp.html#vrsecondary\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingVrrpHelpVrrpVrtrackintf = "href=\"/routing/vrrp/help_vrrp.html#vrtrackintf\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingVrrpHelpVrrpVrtrackintfAdd = "href=\"/routing/vrrp/help_vrrp.html#vrtrackintfAdd\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingVrrpHelpVrrpVrtrackroute = "href=\"/routing/vrrp/help_vrrp.html#vrtrackroute\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingVrrpHelpVrrpVrtrackrouteAdd =  "href=\"/routing/vrrp/help_vrrp.html#vrtrackrouteAdd\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingVrrpHelpVrrpVrstats = "href=\"/routing/vrrp/help_vrrp.html#vrstats\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingVrrpHelpVrrpVrstatus = "href=\"/routing/vrrp/help_vrrp.html#vrstatus\"";
L7_char8 *pStrInfo_routing_ArpTblCfgXUI = "href=\"/help_ARPTableConfig.html\"";
L7_char8 *pStrInfo_routing_RtrRouteTblXUI = "href=\"/help_ipRouteTable.html\"";
L7_char8 *pStrInfo_routing_RtrBestRoutesTblXUI = "href=\"/help_ipGoodRouteTable.html\"";
L7_char8 *pStrInfo_routing_HtmlLinkRoutingOspfHelpOspfLsadbXUI = "href=\"/help_OSPFLinkStateDB.html\"";
L7_char8 *pStrInfo_routing_InSpecifyingIpAddrToBeRemovedFromArpCache = "in specifying the IP Address to be removed from ARP Cache.";
L7_char8 *pStrInfo_routing_HtmlFileIntfIpCfg = "interface_ip_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileIntfIpInfo = "interface_ip_info.html";
L7_char8 *pStrInfo_routing_HtmlFileIpCfg = "ip_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileIpStatsInfo = "ip_stats_info.html";
L7_char8 *pStrInfo_routing_HtmlFileLoopbackCfg = "loopback_config.html";
L7_char8 *pStrInfo_routing_HtmlFileLoopbackSumm = "loopback_summ.html";
L7_char8 *pStrInfo_routing_HtmlFileLsaDbase = "lsa_database.html";
L7_char8 *pStrInfo_routing_HtmlFileMultinetCfg = "multinet_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileHelperCfg = "helperip_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileOspfArea = "ospf_area.html";
L7_char8 *pStrInfo_routing_HtmlFileOspfAreaRange = "ospf_area_range.html";
L7_char8 *pStrInfo_routing_HtmlFileOspfIntfAuthCfg = "ospf_interface_auth_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileOspfIntfCfg = "ospf_interface_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileOspfIntfStats = "ospf_interface_stats.html";
L7_char8 *pStrInfo_routing_HtmlFileOspfLsdbSumm = "ospf_lsdb_summ.html";
L7_char8 *pStrInfo_routing_HtmlFileOspfRtRdstrbtnCfgNew1 = "ospf_rt_rdstrbtn_cfg_new1.html";
L7_char8 *pStrInfo_routing_HtmlFileOspfRtRdstrbtnCfgOld1 = "ospf_rt_rdstrbtn_cfg_old1.html";
L7_char8 *pStrInfo_routing_HtmlFileOspfRtRdstrbtnSumm = "ospf_rt_rdstrbtn_summ.html";
L7_char8 *pStrInfo_routing_HtmlFileOspfStubAreaSummary = "ospf_stub_area_summary.html";
L7_char8 *pStrInfo_routing_HtmlFileOspfVirtLinks = "ospf_virt_links.html";
L7_char8 *pStrInfo_routing_HtmlFileOspfVirtLinksAuth = "ospf_virt_links_auth.html";
L7_char8 *pStrInfo_routing_HtmlFileRelayCfg = "relay_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileRipIntfAuthCfg = "rip_intf_auth_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileRipIntfCfg = "rip_intf_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileRipIntfSummCfg = "rip_intf_summ_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileRipRtRdstrbtnCfgNew1 = "rip_rt_rdstrbtn_cfg_new1.html";
L7_char8 *pStrInfo_routing_HtmlFileRipRtRdstrbtnCfgNew2 = "rip_rt_rdstrbtn_cfg_new2.html";
L7_char8 *pStrInfo_routing_HtmlFileRipRtRdstrbtnCfgOld1 = "rip_rt_rdstrbtn_cfg_old1.html";
L7_char8 *pStrInfo_routing_HtmlFileRipRtRdstrbtnCfgOld2 = "rip_rt_rdstrbtn_cfg_old2.html";
L7_char8 *pStrInfo_routing_HtmlFileRipRtRdstrbtnSumm = "rip_rt_rdstrbtn_summ.html";
L7_char8 *pStrInfo_routing_HtmlFileRouteCfg = "route_configuration.html";
L7_char8 *pStrInfo_routing_HtmlFileRouteEntryCfg = "route_entry_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileRouteEntryCfg2 = "route_entry_cfg2.html";
L7_char8 *pStrInfo_routing_HtmlFileRouteEntryCfgRw2 = "route_entry_cfg_rw2.html";
L7_char8 *pStrInfo_routing_HtmlFileRouteNbrDetailed = "route_nbr_detailed.html";
L7_char8 *pStrInfo_routing_HtmlFileRouteNbrSumm = "route_nbr_summ.html";
L7_char8 *pStrInfo_routing_HtmlFileRoutePrefsCfg = "route_prefs_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileRouteTbl = "route_table.html";
L7_char8 *pStrInfo_routing_HtmlFileRouteTblGood = "route_table_good.html";
L7_char8 *pStrInfo_routing_RtrOspfInfo = "router_ospf_info";
L7_char8 *pStrInfo_routing_HtmlFileRtrOspfInfo = "router_ospf_info.html";
L7_char8 *pStrInfo_routing_HtmlFileRtrDiscCfg1 = "rtr_discovery_cfg1.html";
L7_char8 *pStrInfo_routing_HtmlFileRtrRipCfg = "rtr_rip_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileRtrRipPeers = "rtr_rip_peers.html";
L7_char8 *pStrInfo_routing_HtmlFileTunnelCfg = "tunnel_config.html";
L7_char8 *pStrInfo_routing_HtmlFileTunnelSumm = "tunnel_summ.html";
L7_char8 *pStrInfo_routing_Unconfigured_1 = "unconfigured";
L7_char8 *pStrInfo_routing_HtmlFileVlanRoutingCfg = "vlan_routing_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileVrCfg = "vr_cfg.html";
L7_char8 *pStrInfo_routing_HtmlFileVrSecondary = "vr_secondary.html";
L7_char8 *pStrInfo_routing_HtmlFileVrTrackIntf = "vr_track_intf.html";
L7_char8 *pStrInfo_routing_HtmlFileVrTrackIntfAdd = "vr_track_intf_add.html";
L7_char8 *pStrInfo_routing_HtmlFileVrTrackRoute = "vr_track_route.html";
L7_char8 *pStrInfo_routing_HtmlFileVrTrackRouteAdd = "vr_track_route_add.html";
L7_char8 *pStrInfo_routing_HtmlFileVrStats = "vr_stats.html";
L7_char8 *pStrInfo_routing_HtmlFileVrStatus = "vr_status.html";
L7_char8 *pStrInfo_routing_HtmlFileVrrpCfg = "vrrp_cfg.html";
L7_char8 *pStrErr_routing_FailedToSetIpOspfNetworkWeb = "OSPF network type";
L7_char8 *pStrInfo_base_HtmlFileRelayCfgRo = "relay_cfg_ro.html";
L7_char8 *pStrInfo_base_HtmlFileRouterDiscoveryStatus = "rtr_discovery_status.html";
L7_char8 *pStrInfo_base_HtmlFileVlanRoutingSumm = "vlan_routing_summ.html";

