#
# $Id:$
# $Copyright: (c) 2018 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC swstate subdirectory
#
LOCALDIR = src/soc/dnxf/swstate/auto_generated/diagnostic

include ${SDK}/make/Make.config

lib = libsoc_dnxfswstate_auto_generated_diagnostic

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
