# $Id$
#
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for MONTEREY SOC driver Library
#

LOCALDIR = src/soc/esw/tdm/monterey/

include ${SDK}/make/Make.config

lib = libsoc_tdm_monterey

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

