#!/bin/sh

thisapp=$0
mode="run"
app_name=switchdrvr
app_path=/usr/local/ptin/sbin/$app_name
cli=/usr/local/ptin/sbin/fp.cli
proc_txt=/usr/local/ptin/log/fastpath/proc.txt
ntry=0
cpld_gpr=fe000001fh
db=/usr/local/ptin/bin/db64
sb=/usr/local/ptin/bin/sb64

insert_modules()
{
    echo Inserting modules...
    insmod /usr/local/ptin/sbin/linux-kernel-bde.ko debug=1
    insmod /usr/local/ptin/sbin/linux-user-bde.ko
    sleep 1
}

startup()
{
    # get switch port mapping from unicom
    #SLOT=`/usr/local/ptin/bin/getslotid`
    #ftpget -u root -p lampada 192.168.200.`expr $SLOT + 100` /usr/local/ptin/var/bcm_port_map

    insert_modules;

    # Launch app
#    nice -n -19 $app_path 0>/dev/null &
    $app_path 0>/dev/null &

    # Wait 200 seconds for FP to boot up
    $cli ping 10 20

    # Redirect output to the default pipes
    exec 1>&- 2>&-

    let "ntry=ntry+1"
}

wait4cxp()
{
    echo "Waiting for HW to be successfully configured..."
    while [ 1 ]
    do
        reg=`$db $cpld_gpr 1 | awk '{print $2}'`
	if [ $reg == "00" ]; then
	    sleep 1;
        elif [ $reg == "01" ]; then
            echo "Hardware is configured! Launching Fastpath..."
	    break;
        else
	    break;
	fi
    done
}

signalcxp()
{
    $sb $cpld_gpr 2
}


# If no options, define default mode
if [ ! -z $1 ]; then
    mode=$1
fi

# Option: stop
if [ $mode = "stop" ]; then

    # Kill fastpath script process
    ps > proc.tmp
    pid_proc=`cat proc.tmp | grep $thisapp" boot" | awk '{print $1}'`
    if [ ! -z $pid_proc ]; then
        kill $pid_proc
    fi
    rm proc.tmp

    # Now, kill the switchdrvr application
    killall $app_name
    killall tail

# Option: boot
elif [ $mode = "boot" ]; then
    # Check if file exists
    if [ ! -e $app_path ]; then
        echo "File $app_path does not exist!"
        echo "Aborting FastPath launch!"
        exit 1;
    fi
    
    # Wait for CXP to boot up and configure the hardware                                  
    wait4cxp

    # Query application to determine if it is running or not
    $cli ping 6 4 > /dev/null
    # Start application
    if [ $? -lt 0 -o $? -gt 1 ]; then
        echo "Going to start application"
        startup;
        signalcxp   # Signal CXP FW that Fastpath is launched
    fi

    # Working loop...
    while [ 1 ]
    do
        # Query application to determine if it is running or not
        $cli ping 10 12 > /dev/null
        if [ $? -lt 0 -o $? -gt 1 ]; then
            echo "Transferring LOGs to Matrix board..."
            echo "Fastpath watchdog fired after 10x12 seconds of inactivity!" > /var/log/system_error_info.log
            /bin/sh /usr/local/ptin/scripts/transfer_logs.sh
            echo "Going to reboot"
            /sbin/reboot;
            exit;
        else
            sleep 30
        fi

    done

# No option (normal launch)
else
    # Check if file exists
    if [ ! -e $app_path ]; then
        echo "File $app_path does not exist!"
        echo "Aborting FastPath launch!"
        exit 1;
    fi
    
    # Check if app or script is already running
    ps > $proc_txt
    nproc1=$(cat $proc_txt | grep -c $app_name)
    nproc2=$(cat $proc_txt | grep -c $thisapp" boot")

    if [ $nproc1 != 0 ]; then
        echo "$app_name is already running! ($nproc)"
        exit 1
    elif [ $nproc2 != 0 ]; then
        echo "There is already a deamon responsible to startup $app_name ($nproc2)"
        exit 1
    fi

    # get switch port mapping from unicom
    #SLOT=`/usr/local/ptin/bin/getslotid`
    #ftpget -u root -p lampada 192.168.200.`expr $SLOT + 100` /usr/local/ptin/var/bcm_port_map

    insert_modules;

    # Launch app
#    nice -n -19 $app_path 0>/dev/null &
    $app_path 0>/dev/null &

    signalcxp;
fi
