#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/ctest/dnx/switch

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libctest_dnxswitch

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

