# $Id
#
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for Hurricane4 SOC driver Library
#

LOCALDIR = src/soc/esw/firebolt6

include ${SDK}/make/Make.config

SUBDIR_FIREBOLT6_FLEXPORT = flexport

subdirs := $(SUBDIR_FIREBOLT6_FLEXPORT)

lib = libsoc_firebolt6

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

