# -*- Makefile -*-
# $Id: Makefile,v 1.9 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for StrataXGS SDK and diagnostics
#

include $(SDK)/make/Make.config

ifeq ($(HOSTTYPE),i386-linux)
subdirs= 
endif

include $(SDK)/make/Make.subdirs

include $(SDK)/make/Make.depend
