# $Id: Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/dnx/time

include ${SDK}/make/Make.config

#subdirs =

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxtime

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
