BOARD=TC16SXG
CPU=td3x3arm

TOOLCHAIN_BASE_DIR=/opt/eldk/usr
TOOLCHAIN_BIN_DIR=$(TOOLCHAIN_BASE_DIR)/bin
LD_LIBRARY_PATH=$(TOOLCHAIN_BASE_DIR)/lib
CROSS_COMPILE=$(TOOLCHAIN_BIN_DIR)/ppc_85xxDP-

include fp.shell-common.make
