BOARD=AG16GA
CPU=katanaarm

TOOLCHAIN_BASE_DIR=/opt/xldk/5.0.3/kt2/usr
TOOLCHAIN_BIN_DIR=$(TOOLCHAIN_BASE_DIR)/bin
LD_LIBRARY_PATH=$(TOOLCHAIN_BASE_DIR)/lib
CROSS_COMPILE=$(TOOLCHAIN_BIN_DIR)/arm-linux-

include fp.shell-common.make
