PHONY: all clean cleanall

help h:
	@echo ""
	@echo "Makefile Help "
	@echo ""
	@echo " make all     "
	@echo " make clean   "
	@echo " make cleanall"
	@echo ""

all clean cleanall:
	@$(MAKE) -f fp.shell-cxo640g.make $@
	@$(MAKE) -f fp.shell-cxo160g.make $@
	@$(MAKE) -f fp.shell-ta48ge.make $@
	@$(MAKE) -f fp.shell-tg16g.make $@
	@$(MAKE) -f fp.shell-tg16gf.make $@
	@$(MAKE) -f fp.shell-olt1t0.make $@
	@$(MAKE) -f fp.shell-olt1t0f.make $@
	@$(MAKE) -f fp.shell-tt04sxg.make $@

