PHONY: all clean cleanall

help h:
	@echo ""
	@echo "Makefile Help "
	@echo ""
	@echo " make all     "
	@echo " make clean   "
	@echo " make cleanall"
	@echo ""

all clean cleanall:
	@$(MAKE) -f fp.shell-ae48ge.make $@
	@$(MAKE) -f fp.shell-ag16ga.make $@

