/*********************************************************************
*
* (C) Copyright Broadcom Corporation 2001-2007
*
**********************************************************************
*
* @filename src\application\unitmgr\umdb\public\usmdb_counters.h
*
* @purpose defines for the counter section of the USMDB layer
*
* @component unitmgr
*
* @comments tba
*
* @create 12/07/2000
*
* @author bmutz
* @end
*
**********************************************************************/

/*************************************************************
                    
*************************************************************/




#ifndef USMDB_COUNTERS_H
#define USMDB_COUNTERS_H

#include "platform_counters.h"
#include "statsapi.h"

/* Define the categories of user statistics created by USMDB */
typedef enum
{
  L7_USMDB_USER_STAT_FAST_ENET = 1,                                       /* fast and gigabit ethernet ports */
  L7_USMDB_USER_STAT_CPU,                                                 /* CPU port */
  L7_USMDB_USER_STAT_LAG,                                                 /* LAG interfaces */
  L7_USMDB_USER_STAT_DOT1Q                                                /* DOT1Q port stats */
} usmdbUserStatsCat_t;


/*************************************************************************
* 
* @structures usmdbPortCounterIndex_t
*
* @purpose    List of all port-based counters exported by USMDB 
*
* @notes      Contains both base and user counter types for port-based
*             statistics.  These are abstracted to allow USMDB to 
*             choose the proper Stats Mgr counter ID depending on 
*             whether the interface is a physical port, LAG port, etc.
*
* @notes      Must be specified along with an internal interface number,
*             which USMDB uses to determine the port type.
*
* @notes      CAUTION!! Do not put other types of interface counters in 
*             this list, such as those created by DOT1Q, IP, etc.  They 
*             are already defined uniquely per interface and can be 
*             properly refereced using the stand-alone L7_CTR_xxx name
*             defined above.  
*
**************************************************************************/

typedef enum
{
  L7_USMDB_RESERVED = 0,                                                  /* don't use 0 as a counter index */
  L7_CTR_RX_TOTAL_BYTES,
  L7_CTR_RX_64,
  L7_CTR_RX_65_127,
  L7_CTR_RX_128_255,
  L7_CTR_RX_256_511,
  L7_CTR_RX_512_1023,
  L7_CTR_RX_1024_1518,
  L7_CTR_RX_1519_1530,
  L7_CTR_RX_GOOD_OVERSIZE,
  L7_CTR_RX_ERROR_OVERSIZE,
  L7_CTR_RX_GOOD_UNDERSIZE,
  L7_CTR_RX_ERROR_UNDERSIZE,
  L7_CTR_RX_UCAST_FRAMES,
  L7_CTR_RX_MCAST_FRAMES,
  L7_CTR_RX_BCAST_FRAMES,
  L7_CTR_RX_ALIGN_ERRORS,
  L7_CTR_RX_FCS_ERRORS,
  L7_CTR_RX_OVERRUNS,
  L7_CTR_RX_FRAME_TOO_LONG,

  L7_CTR_TX_TOTAL_BYTES,
  L7_CTR_TX_64,
  L7_CTR_TX_65_127,
  L7_CTR_TX_128_255,
  L7_CTR_TX_256_511,
  L7_CTR_TX_512_1023,
  L7_CTR_TX_1024_1518,
  L7_CTR_TX_1519_1530,
  L7_CTR_TX_UCAST_FRAMES,
  L7_CTR_TX_MCAST_FRAMES,
  L7_CTR_TX_BCAST_FRAMES,
  L7_CTR_TX_FCS_ERRORS,
  L7_CTR_TX_OVERSIZED,
  L7_CTR_TX_UNDERRUN_ERRORS,
  L7_CTR_TX_ONE_COLLISION,
  L7_CTR_TX_MULTIPLE_COLLISION,
  L7_CTR_TX_EXCESSIVE_COLLISION,
  L7_CTR_TX_LATE_COLLISION,

  L7_CTR_TX_RX_64,
  L7_CTR_TX_RX_65_127,
  L7_CTR_TX_RX_128_255,
  L7_CTR_TX_RX_256_511,
  L7_CTR_TX_RX_512_1023,
  L7_CTR_TX_RX_1024_1518,
  L7_CTR_TX_RX_1519_1522,
  L7_CTR_TX_RX_1523_2047,
  L7_CTR_TX_RX_2048_4095,
  L7_CTR_TX_RX_4096_9216,
  /* RMON */
  L7_CTR_ETHER_STATS_DROP_EVENTS,

  L7_CTR_SNMPIFOUTDISCARD_FRAMES,
  L7_CTR_SNMPIFINDISCARD_FRAMES,

  L7_CTR_RX_TOTAL_FRAMES,
  L7_CTR_RX_TOTAL_ERROR_FRAMES,
  L7_CTR_TX_TOTAL_FRAMES,
  L7_CTR_TX_TOTAL_ERROR_FRAMES,
  L7_CTR_TX_TOTAL_COLLISION_FRAMES,
  L7_CTR_RX_CRC_ERRORS,
  L7_CTR_RX_TOTAL_MAC_ERROR_FRAMES,


  /* ------------------------------------------------------------------------ */
  L7_USMDB_NUM_OF_CTRS               /* total number of counters here (for error checking) */

} usmdbPortCounterIndex_t;

/* USMDB counter ID definition for VLAN Ingress Statistics */
#define L7_CTR_DOT1Q_RX_TOTAL_NOT_FORWARDED_FRAMES    (L7_USMDB_COMPONENT_ID << 16) | 0x0000


/* system BASE counters for all types of Interfaces */
#define L7_CTR_TX_GVRP_PDU_COUNT          L7_PLATFORM_CTR_GVRP_PDU_SND_COUNT
#define L7_CTR_RX_GVRP_PDU_COUNT          L7_PLATFORM_CTR_GVRP_PDU_RCV_COUNT
#define L7_CTR_GVRP_FAILED_REGISTRATIONS  L7_PLATFORM_CTR_GVRP_FAILED_REGISTRATIONS
#define L7_CTR_TX_GMRP_PDU_COUNT          L7_PLATFORM_CTR_GMRP_PDU_SND_COUNT
#define L7_CTR_RX_GMRP_PDU_COUNT          L7_PLATFORM_CTR_GMRP_PDU_RCV_COUNT
#define L7_CTR_GMRP_FAILED_REGISTRATIONS  L7_PLATFORM_CTR_GMRP_FAILED_REGISTRATIONS
#define L7_CTR_TX_BPDU_COUNT              L7_PLATFORM_CTR_BPDU_SND_COUNT
#define L7_CTR_RX_BPDU_COUNT              L7_PLATFORM_CTR_BPDU_RCV_COUNT


/* Switch - Receive Routing Function Counters */
#define L7_CTR_RX_IP_IN_RECEIVES            L7_PLATFORM_CTR_RX_IP_IN_RECEIVES
#define L7_CTR_RX_IP_IN_HDR_ERRORS          L7_PLATFORM_CTR_RX_IP_IN_HDR_ERRORS      
#define L7_CTR_RX_IP_IN_ADDR_ERRORS         L7_PLATFORM_CTR_RX_IP_IN_ADDR_ERRORS
#define L7_CTR_RX_IP_FORW_DATAGRAMS         L7_PLATFORM_CTR_RX_IP_FORW_DATAGRAMS
#define L7_CTR_RX_IP_IN_UNKNOWN_PROTOS      L7_PLATFORM_CTR_RX_IP_IN_UNKNOWN_PROTOS
#define L7_CTR_RX_IP_IN_DISCARDS            L7_PLATFORM_CTR_RX_IP_IN_DISCARDS
#define L7_CTR_RX_IP_IN_DELIVERS            L7_PLATFORM_CTR_RX_IP_IN_DELIVERS
#define L7_CTR_RX_IP_REASM_REQDS            L7_PLATFORM_CTR_RX_IP_REASM_REQDS
#define L7_CTR_RX_IP_REASM_OKS              L7_PLATFORM_CTR_RX_IP_REASM_OKS
#define L7_CTR_RX_IP_REASM_FAILS            L7_PLATFORM_CTR_RX_IP_REASM_FAILS
#define L7_CTR_RX_IP_FRAG_OKS               L7_PLATFORM_CTR_RX_IP_FRAG_OKS
#define L7_CTR_RX_IP_FRAG_FAILS             L7_PLATFORM_CTR_RX_IP_FRAG_FAILS
#define L7_CTR_RX_IP_FRAG_CREATES           L7_PLATFORM_CTR_RX_IP_FRAG_CREATES
#define L7_CTR_RX_ICMP_IN_MSGS              L7_PLATFORM_CTR_RX_ICMP_IN_MSGS
#define L7_CTR_RX_ICMP_IN_ERRORS            L7_PLATFORM_CTR_RX_ICMP_IN_ERRORS
#define L7_CTR_RX_ICMP_IN_DEST_UNREACHS     L7_PLATFORM_CTR_RX_ICMP_IN_DEST_UNREACHS
#define L7_CTR_RX_ICMP_IN_TIME_EXCDS        L7_PLATFORM_CTR_RX_ICMP_IN_TIME_EXCDS
#define L7_CTR_RX_ICMP_IN_PARM_PROBS        L7_PLATFORM_CTR_RX_ICMP_IN_PARM_PROBS
#define L7_CTR_RX_ICMP_IN_SRC_QUENCHS       L7_PLATFORM_CTR_RX_ICMP_IN_SRC_QUENCHS
#define L7_CTR_RX_ICMP_IN_REDIRECTS         L7_PLATFORM_CTR_RX_ICMP_IN_REDIRECTS
#define L7_CTR_RX_ICMP_IN_ECHOS             L7_PLATFORM_CTR_RX_ICMP_IN_ECHOS
#define L7_CTR_RX_ICMP_IN_ECHO_REPS         L7_PLATFORM_CTR_RX_ICMP_IN_ECHO_REPS
#define L7_CTR_RX_ICMP_IN_TIMESTAMPS        L7_PLATFORM_CTR_RX_ICMP_IN_TIMESTAMPS
#define L7_CTR_RX_ICMP_IN_TIMESTAMP_REPS    L7_PLATFORM_CTR_RX_ICMP_IN_TIMESTAMP_REPS
#define L7_CTR_RX_ICMP_IN_ADDR_MASKS        L7_PLATFORM_CTR_RX_ICMP_IN_ADDR_MASKS
#define L7_CTR_RX_ICMP_IN_ADDR_MASK_REPS    L7_PLATFORM_CTR_RX_ICMP_IN_ADDR_MASK_REPS
#define L7_CTR_RX_TCP_IN_SEGS               L7_PLATFORM_CTR_RX_TCP_IN_SEGS
#define L7_CTR_RX_TCP_IN_ERRS               L7_PLATFORM_CTR_RX_TCP_IN_ERRS
#define L7_CTR_RX_UDP_IN_DATAGRAMS          L7_PLATFORM_CTR_RX_UDP_IN_DATAGRAMS
#define L7_CTR_RX_UDP_IN_ERRORS             L7_PLATFORM_CTR_RX_UDP_IN_ERRORS
#define L7_CTR_RX_EGP_IN_MSGS               L7_PLATFORM_CTR_RX_EGP_IN_MSGS
#define L7_CTR_RX_EGP_IN_ERRORS             L7_PLATFORM_CTR_RX_EGP_IN_ERRORS
#define L7_CTR_RX_EGP_NEIGH_IN_MSGS         L7_PLATFORM_CTR_RX_EGP_NEIGH_IN_MSGS
#define L7_CTR_RX_EGP_NEIGH_IN_ERRS         L7_PLATFORM_CTR_RX_EGP_NEIGH_IN_ERRS
#define L7_CTR_RX_EGP_NEIGH_ERR_MSGS        L7_PLATFORM_CTR_RX_EGP_NEIGH_IN_ERR_MSGS



/* Switch - Transmit Routing Function Counters */
#define L7_CTR_TX_IP_OUT_REQUESTS           L7_PLATFORM_CTR_TX_IP_OUT_REQUESTS
#define L7_CTR_TX_IP_OUT_DISCARDS           L7_PLATFORM_CTR_TX_IP_OUT_DISCARDS
#define L7_CTR_TX_IP_OUT_NO_ROUTES          L7_PLATFORM_CTR_TX_IP_OUT_NO_ROUTES
#define L7_CTR_TX_ICMP_OUT_MSGS             L7_PLATFORM_CTR_TX_ICMP_OUT_MSGS
#define L7_CTR_TX_ICMP_OUT_ERRORS           L7_PLATFORM_CTR_TX_ICMP_OUT_ERRORS
#define L7_CTR_TX_ICMP_OUT_DEST_UNREACHS    L7_PLATFORM_CTR_TX_ICMP_OUT_DEST_UNREACHS
#define L7_CTR_TX_ICMP_OUT_TIME_EXCDS       L7_PLATFORM_CTR_TX_ICMP_OUT_TIME_EXCDS
#define L7_CTR_TX_ICMP_OUT_PARM_PROBS       L7_PLATFORM_CTR_TX_ICMP_OUT_PARM_PROBS
#define L7_CTR_TX_ICMP_OUT_SRC_QUENCHS      L7_PLATFORM_CTR_TX_ICMP_OUT_SRC_QUENCHS
#define L7_CTR_TX_ICMP_OUT_REDIRECTS        L7_PLATFORM_CTR_TX_ICMP_OUT_REDIRECTS
#define L7_CTR_TX_ICMP_OUT_ECHOS            L7_PLATFORM_CTR_TX_ICMP_OUT_ECHOS
#define L7_CTR_TX_ICMP_OUT_ECHO_REPS        L7_PLATFORM_CTR_TX_ICMP_OUT_ECHO_REPS
#define L7_CTR_TX_ICMP_OUT_TIMESTAMPS       L7_PLATFORM_CTR_TX_ICMP_OUT_TIMESTAMPS
#define L7_CTR_TX_ICMP_OUT_TIMESTAMP_REPS   L7_PLATFORM_CTR_TX_ICMP_OUT_TIMESTAMP_REPS
#define L7_CTR_TX_ICMP_OUT_ADDR_MASKS       L7_PLATFORM_CTR_TX_ICMP_OUT_ADDR_MASKS
#define L7_CTR_TX_ICMP_OUT_ADDR_MASK_REPS   L7_PLATFORM_CTR_TX_ICMP_OUT_ADDR_MASK_REPS
#define L7_CTR_TX_TCP_OUT_SEGS              L7_PLATFORM_CTR_TX_TCP_OUT_SEGS
#define L7_CTR_TX_TCP_OUT_RSTS              L7_PLATFORM_CTR_TX_TCP_OUT_RSTS
#define L7_CTR_TX_UDP_OUT_DATAGRAMS         L7_PLATFORM_CTR_TX_UDP_OUT_DATAGRAMS
#define L7_CTR_TX_EGP_OUT_MSGS              L7_PLATFORM_CTR_TX_EGP_OUT_MSGS
#define L7_CTR_TX_EGP_OUT_ERRORS            L7_PLATFORM_CTR_TX_EGP_OUT_ERRORS
#define L7_CTR_TX_EGP_NEIGH_OUT_MSGS        L7_PLATFORM_CTR_TX_EGP_NEIGH_OUT_MSGS
#define L7_CTR_TX_EGP_NEIGH_OUT_ERRS        L7_PLATFORM_CTR_TX_EGP_NEIGH_OUT_ERRS
#define L7_CTR_TX_EGP_NEIGH_OUT_ERR_MSGS    L7_PLATFORM_CTR_TX_EGP_NEIGH_OUT_ERR_MSGS


/* Switch - Miscellaneous counters */
#define L7_CTR_IP_ROUTING_DISCARDS          L7_PLATFORM_CTR_IP_ROUTING_DISCARDS
#define L7_CTR_IP_REASM_TIMEOUTS            L7_PLATFORM_CTR_IP_REASM_TIMEOUTS
#define L7_CTR_TCP_ACTIVE_OPENS             L7_PLATFORM_CTR_TCP_ACTIVE_OPENS
#define L7_CTR_TCP_PASSIVE_OPENS            L7_PLATFORM_CTR_TCP_PASSIVE_OPENS
#define L7_CTR_TCP_ATTEMPT_FAILS            L7_PLATFORM_CTR_TCP_ATTEMPT_FAILS
#define L7_CTR_TCP_ESTAB_RESETS             L7_PLATFORM_CTR_TCP_ESTAB_RESETS
#define L7_CTR_TCP_RETRANS_SEGS             L7_PLATFORM_CTR_TCP_RETRANS_SEGS
#define L7_CTR_UDP_NO_PORTS                 L7_PLATFORM_CTR_UDP_NO_PORTS
#define L7_CTR_EGP_NEIGH_STATE_UPS          L7_PLATFORM_CTR_EGP_NEIGH_STATE_UPS
#define L7_CTR_EGP_NEIGH_STATE_DOWNS        L7_PLATFORM_CTR_EGP_NEIGH_STATE_DOWNS


/* VLAN Statistics */
#define L7_CTR_DOT1Q_DYNAMIC_VLAN_COUNT      L7_PLATFORM_CTR_DYNAMIC_VLAN_COUNT
#define L7_CTR_DOT1Q_MOST_VLAN_COUNT         L7_PLATFORM_CTR_MOST_VLAN_COUNT
#define L7_CTR_DOT1Q_FAILED_VLAN_CREATIONS   L7_PLATFORM_CTR_FAILED_VLAN_CREATIONS
#define L7_CTR_DOT1Q_VLAN_DELETION_COUNT     L7_PLATFORM_CTR_VLAN_DELETION_COUNT


/* VLAN Ingress Statistics */
#define L7_CTR_DOT1Q_LOCAL_TRAFFIC_DISCARDS             L7_PLATFORM_CTR_LOCAL_TRAFFIC_DISCARDS          
#define L7_CTR_DOT1Q_RX_PAUSE_FRAMES                    L7_PLATFORM_CTR_RX_PAUSE_FRAMES       
#define L7_CTR_DOT1Q_UNACCEPTABLE_FRAME_TYPE_DISCARDS   L7_PLATFORM_CTR_UNACCEPTABLE_FRAME_TYPE_DISCARDS
#define L7_CTR_DOT1Q_INGRESS_FILTER_DISCARDS            L7_PLATFORM_CTR_INGRESS_FILTER_DISCARDS         
#define L7_CTR_DOT1Q_INGRESS_VLAN_VIABLE_DISCARDS       L7_PLATFORM_CTR_INGRESS_VLAN_VIABLE_DISCARDS    
#define L7_CTR_DOT1Q_MULTICAST_TREE_VIABLE_DISCARDS     L7_PLATFORM_CTR_MULTICAST_TREE_VIABLE_DISCARDS  
#define L7_CTR_DOT1Q_RESERVED_ADDRESS_DISCARDS          L7_PLATFORM_CTR_RESERVED_ADDRESS_DISCARDS       
#define L7_CTR_DOT1Q_BCAST_STORM_RECOVERY_DISCARDS      L7_PLATFORM_CTR_BCAST_STORM_RECOVERY_DISCARDS   
#define L7_CTR_DOT1Q_CFI_DISCARDS                       L7_PLATFORM_CTR_CFI_DISCARDS
#define L7_CTR_DOT1Q_UPSTREAM_THRESHOLD_DISCARDS        L7_PLATFORM_CTR_UPSTREAM_THRESHOLD_DISCARDS                    


/* VLAN Egress Statistics */
#define L7_CTR_DOT1Q_TX_PAUSE_FRAMES                    L7_PLATFORM_CTR_TX_PAUSE_FRAMES                 
#define L7_CTR_DOT1Q_PORT_MEMBERSHIP_DISCARDS           L7_PLATFORM_CTR_PORT_MEMBERSHIP_DISCARDS        
#define L7_CTR_DOT1Q_EGRESS_VLAN_VIABLE_DISCARDS        L7_PLATFORM_CTR_EGRESS_VLAN_VIABLE_DISCARDS     


/* DTL Discards Statistics*/
#define L7_CTR_DTL_RX_DISCARDS                          L7_PLATFORM_CTR_RX_DISCARDS
#define L7_CTR_DTL_TX_DISCARDS                          L7_PLATFORM_CTR_TX_DISCARDS


/* Policy Statistics */
#define L7_CTR_POLICY_RX_TOTAL_DISCARDS                 L7_PLATFORM_CTR_RX_TOTAL_DISCARDS


/*-------------------------------------*/
/* TRAFFIC SERVICES FLEX PACKAGE STATS */
/*-------------------------------------*/

/* MPLS Application Statistics */

#define L7_CTR_MPLS_FTN_MATCHED_PACKETS           L7_PLATFORM_CTR_MPLS_FTN_MATCHED_PACKETS
#define L7_CTR_MPLS_FTN_MATCHED_OCTETS            L7_PLATFORM_CTR_MPLS_FTN_MATCHED_OCTETS
#define L7_CTR_MPLS_FTN_MATCHED_HC_PACKETS        L7_PLATFORM_CTR_MPLS_FTN_MATCHED_HC_PACKETS
#define L7_CTR_MPLS_FTN_MATCHED_HC_OCTETS         L7_PLATFORM_CTR_MPLS_FTN_MATCHED_HC_OCTETS

#define L7_CTR_MPLS_LSR_INTF_IN_LABELS_USED       L7_PLATFORM_CTR_MPLS_LSR_INTF_IN_LABELS_USED
#define L7_CTR_MPLS_LSR_INTF_FAILED_LABEL_LOOKUP  L7_PLATFORM_CTR_MPLS_LSR_INTF_FAILED_LABEL_LOOKUP   
#define L7_CTR_MPLS_LSR_INTF_OUT_LABELS_USED      L7_PLATFORM_CTR_MPLS_LSR_INTF_OUT_LABELS_USED
#define L7_CTR_MPLS_LSR_INTF_OUT_FRAGMENTS        L7_PLATFORM_CTR_MPLS_LSR_INTF_OUT_FRAGMENTS

#define L7_CTR_MPLS_LSR_IN_SEG_OCTETS             L7_PLATFORM_CTR_MPLS_LSR_IN_SEG_OCTETS
#define L7_CTR_MPLS_LSR_IN_SEG_PACKETS            L7_PLATFORM_CTR_MPLS_LSR_IN_SEG_PACKETS
#define L7_CTR_MPLS_LSR_IN_SEG_ERRORS             L7_PLATFORM_CTR_MPLS_LSR_IN_SEG_ERRORS
#define L7_CTR_MPLS_LSR_IN_SEG_DISCARDS           L7_PLATFORM_CTR_MPLS_LSR_IN_SEG_DISCARDS
#define L7_CTR_MPLS_LSR_IN_SEG_HC_OCTETS          L7_PLATFORM_CTR_MPLS_LSR_IN_SEG_HC_OCTETS
#define L7_CTR_MPLS_LSR_IN_SEG_PERF_DISCONTINUITY_TIME  L7_PLATFORM_CTR_MPLS_LSR_IN_SEG_PERF_DISCONTINUITY_TIME

#define L7_CTR_MPLS_LSR_OUT_SEG_OCTETS            L7_PLATFORM_CTR_MPLS_LSR_OUT_SEG_OCTETS
#define L7_CTR_MPLS_LSR_OUT_SEG_PACKETS           L7_PLATFORM_CTR_MPLS_LSR_OUT_SEG_PACKETS
#define L7_CTR_MPLS_LSR_OUT_SEG_ERRORS            L7_PLATFORM_CTR_MPLS_LSR_OUT_SEG_ERRORS
#define L7_CTR_MPLS_LSR_OUT_SEG_DISCARDS          L7_PLATFORM_CTR_MPLS_LSR_OUT_SEG_DISCARDS
#define L7_CTR_MPLS_LSR_OUT_SEG_HC_OCTETS         L7_PLATFORM_CTR_MPLS_LSR_OUT_SEG_HC_OCTETS
#define L7_CTR_MPLS_LSR_OUT_SEG_PERF_DISCONTINUITY_TIME  L7_PLATFORM_CTR_MPLS_LSR_OUT_SEG_PERF_DISCONTINUITY_TIME


/*--------------*/
/* 802.1X STATS */
/*--------------*/

/* Authenticator Stats (9.4.2) */
#define L7_CTR_DOT1X_AUTH_EAPOL_FRAMES_RX             L7_PLATFORM_CTR_DOT1X_AUTH_EAPOL_FRAMES_RX
#define L7_CTR_DOT1X_AUTH_EAPOL_FRAMES_TX             L7_PLATFORM_CTR_DOT1X_AUTH_EAPOL_FRAMES_TX
#define L7_CTR_DOT1X_AUTH_EAPOL_START_FRAMES_RX       L7_PLATFORM_CTR_DOT1X_AUTH_EAPOL_START_FRAMES_RX
#define L7_CTR_DOT1X_AUTH_EAPOL_LOGOFF_FRAMES_RX      L7_PLATFORM_CTR_DOT1X_AUTH_EAPOL_LOGOFF_FRAMES_RX
#define L7_CTR_DOT1X_AUTH_EAP_RESP_ID_FRAMES_RX       L7_PLATFORM_CTR_DOT1X_AUTH_EAP_RESP_ID_FRAMES_RX
#define L7_CTR_DOT1X_AUTH_EAP_RESPONSE_FRAMES_RX      L7_PLATFORM_CTR_DOT1X_AUTH_EAP_RESPONSE_FRAMES_RX
#define L7_CTR_DOT1X_AUTH_EAP_REQ_ID_FRAMES_TX        L7_PLATFORM_CTR_DOT1X_AUTH_EAP_REQ_ID_FRAMES_TX
#define L7_CTR_DOT1X_AUTH_EAP_REQ_FRAMES_TX           L7_PLATFORM_CTR_DOT1X_AUTH_EAP_REQ_FRAMES_TX
#define L7_CTR_DOT1X_AUTH_INVALID_EAPOL_FRAMES_RX     L7_PLATFORM_CTR_DOT1X_AUTH_INVALID_EAPOL_FRAMES_RX
#define L7_CTR_DOT1X_AUTH_EAP_LENGTH_ERROR_FRAMES_RX  L7_PLATFORM_CTR_DOT1X_AUTH_EAP_LENGTH_ERROR_FRAMES_RX

/* Authenticator Diagnostics (9.4.3) */
#define L7_CTR_DOT1X_AUTH_ENTERS_CONNECTING                          L7_PLATFORM_CTR_DOT1X_AUTH_ENTERS_CONNECTING
#define L7_CTR_DOT1X_AUTH_LOGOFFS_WHILE_CONNECTING                   L7_PLATFORM_CTR_DOT1X_AUTH_LOGOFFS_WHILE_CONNECTING
#define L7_CTR_DOT1X_AUTH_ENTERS_AUTHENTICATING                      L7_PLATFORM_CTR_DOT1X_AUTH_ENTERS_AUTHENTICATING
#define L7_CTR_DOT1X_AUTH_AUTH_SUCCESS_WHILE_AUTHENTICATING          L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_SUCCESS_WHILE_AUTHENTICATING
#define L7_CTR_DOT1X_AUTH_AUTH_TIMEOUTS_WHILE_AUTHENTICATING         L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_TIMEOUTS_WHILE_AUTHENTICATING
#define L7_CTR_DOT1X_AUTH_AUTH_FAIL_WHILE_AUTHENTICATING             L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_FAIL_WHILE_AUTHENTICATING
#define L7_CTR_DOT1X_AUTH_AUTH_REAUTHS_WHILE_AUTHENTICATING          L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_REAUTHS_WHILE_AUTHENTICATING
#define L7_CTR_DOT1X_AUTH_AUTH_EAP_STARTS_WHILE_AUTHENTICATING       L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_EAP_STARTS_WHILE_AUTHENTICATING
#define L7_CTR_DOT1X_AUTH_AUTH_EAP_LOGOFF_WHILE_AUTHENTICATING       L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_EAP_LOGOFF_WHILE_AUTHENTICATING
#define L7_CTR_DOT1X_AUTH_AUTH_REAUTHS_WHILE_AUTHENTICATED           L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_REAUTHS_WHILE_AUTHENTICATED
#define L7_CTR_DOT1X_AUTH_AUTH_EAP_STARTS_WHILE_AUTHENTICATED        L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_EAP_STARTS_WHILE_AUTHENTICATED
#define L7_CTR_DOT1X_AUTH_AUTH_EAP_LOGOFF_WHILE_AUTHENTICATED        L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_EAP_LOGOFF_WHILE_AUTHENTICATED
#define L7_CTR_DOT1X_AUTH_BACKEND_RESPONSES                          L7_PLATFORM_CTR_DOT1X_AUTH_BACKEND_RESPONSES
#define L7_CTR_DOT1X_AUTH_BACKEND_ACCESS_CHALLENGES_COUNT            L7_PLATFORM_CTR_DOT1X_AUTH_BACKEND_ACCESS_CHALLENGES_COUNT
#define L7_CTR_DOT1X_AUTH_BACKEND_OTHER_REQUESTS_TO_SUPPLICANT       L7_PLATFORM_CTR_DOT1X_AUTH_BACKEND_OTHER_REQUESTS_TO_SUPPLICANT
#define L7_CTR_DOT1X_AUTH_BACKEND_NON_NAK_RESPONSES_FROM_SUPPLICANT  L7_PLATFORM_CTR_DOT1X_AUTH_BACKEND_NON_NAK_RESPONSES_FROM_SUPPLICANT
#define L7_CTR_DOT1X_AUTH_BACKEND_AUTH_SUCCESSES                     L7_PLATFORM_CTR_DOT1X_AUTH_BACKEND_AUTH_SUCCESSES
#define L7_CTR_DOT1X_AUTH_BACKEND_AUTH_FAILS                         L7_PLATFORM_CTR_DOT1X_AUTH_BACKEND_AUTH_FAILS

#endif

