#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dnx/dnx_data/auto_generated subdirectory
#

LOCALDIR = src/soc/dnx/intr/auto_generated/jr2

include ${SDK}/make/Make.config


include ${SDK}/make/Make.subdirs

lib = libsoc_dnxintragjer2

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

