# $Id: Makefile,v 1.18 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for Switch on a Chip (SOC) driver and diagnostics
#

include ${SDK}/make/Make.config

subdirs = dbg std

include ${SDK}/make/Make.subdirs
