# $Id: $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for streamlined packet I/O drivers
#

LOCALDIR = src/bcm/esw/pktio/bcmpkt/gih

PKTIO_IMPL = 1
CFLAGS =
include ${SDK}/make/Make.config

lib = libesw_pktio_bcmpkt_gih

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

