/* $Id: chip_sim_PB_TM.h,v 1.6 Broadcom SDK $
 * $Copyright: Copyright 2015 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
*/
/******************************************************************
*
* FILENAME:       chip_sim_PB.h
*
* MODULE PREFIX:  chip_sim
*
* FILE DESCRIPTION:
*
* REMARKS:
* SW License Agreement: Dune Networks (c). CONFIDENTIAL PROPRIETARY INFORMATION.
* Any use of this Software is subject to Software License Agreement
* included in the Driver User Manual of this device.
* Any use of this Software constitutes an agreement to the terms
* of the above Software License Agreement.
******************************************************************/


#ifndef __CHIP_SIM_PB_TM_H_INCLUDED__
/* { */ 
#define __CHIP_SIM_PB_TM_H_INCLUDED__


/*************
 *  MACROS   *
 *************/
/* { */

/* } */

/*************
 * TYPE DEFS *
 *************/
/* { */

/* } */

/*************
 * INCLUDES  *
 *************/
/* { */
#include <soc/dpp/SAND/Utils/sand_header.h> 

#include "chip_sim.h"
#include "chip_sim_counter.h"
#include "chip_sim_interrupts.h"
#include "chip_sim_indirect.h"
/* } */

/*************
 * DEFINES   *
 *************/
/* { */

/* table index definitions { */
#define SOC_PB_OLP_PGE_MEM_TBL_ID                    0
#define SOC_PB_IRE_NIF_CTXT_MAP_TBL_ID               1
#define SOC_PB_IRE_NIF_PORT_TO_CTXT_BIT_MAP_TBL_ID   2
#define SOC_PB_IRE_RCY_CTXT_MAP_TBL_ID               3
#define SOC_PB_IRE_TDM_CONFIG_TBL_ID                 4
#define SOC_PB_IDR_CONTEXT_MRU_TBL_ID                5
#define SOC_PB_IDR_COMPLETE_PC_TBL_ID                6
#define SOC_PB_IDR_ETHERNET_METER_PROFILES_TBL_ID    7
#define SOC_PB_IDR_ETHERNET_METER_CONFIG_TBL_ID      8
#define SOC_PB_IDR_GLOBAL_METER_PROFILES_TBL_ID      9
#define SOC_PB_IDR_GLOBAL_METER_STATUS_TBL_ID        10
#define SOC_PB_IRR_IRDB_TBL_ID                       11
#define SOC_PB_IRR_MCDB_TBL_ID                       12
#define SOC_PB_IRR_SNOOP_MIRROR_TABLE0_TBL_ID        13
#define SOC_PB_IRR_SNOOP_MIRROR_TABLE1_TBL_ID        14
#define SOC_PB_IRR_DESTINATION_TABLE_TBL_ID          15
#define SOC_PB_IRR_LAG_TO_LAG_RANGE_TBL_ID           16
#define SOC_PB_IRR_LAG_MAPPING_TBL_ID                17
#define SOC_PB_IRR_LAG_NEXT_MEMBER_TBL_ID            18
#define SOC_PB_IRR_SMOOTH_DIVISION_TBL_ID            19
#define SOC_PB_IRR_TRAFFIC_CLASS_MAPPING_TBL_ID      20
#define SOC_PB_IHP_TM_PORT_PP_PORT_CONFIG_TBL_ID     21
#define SOC_PB_IHP_TM_PORT_SYS_PORT_CONFIG_TBL_ID    22
#define SOC_PB_IHP_PP_PORT_INFO_TBL_ID               23
#define SOC_PB_IHP_PP_PORT_VALUES_TBL_ID             24
#define SOC_PB_IHP_PORT_MINE_TABLE_LAG_PORT_TBL_ID   25
#define SOC_PB_IHB_PINFO_PMF_TBL_ID                  26
#define SOC_PB_IHB_PACKET_FORMAT_CODE_PROFILE_TBL_ID 27
#define SOC_PB_IHB_SRC_DEST_PORT_FOR_L3_ACL_KEY_TBL_ID 28
#define SOC_PB_IHB_DIRECT_1ST_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 29
#define SOC_PB_IHB_DIRECT_2ND_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 30
#define SOC_PB_IHB_FEM0_4B_1ST_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 31
#define SOC_PB_IHB_FEM0_4B_1ST_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 32
#define SOC_PB_IHB_FEM0_4B_1ST_PASS_MAP_INDEX_TABLE_TBL_ID 33
#define SOC_PB_IHB_FEM0_4B_1ST_PASS_MAP_TABLE_TBL_ID 34
#define SOC_PB_IHB_FEM1_4B_1ST_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 35
#define SOC_PB_IHB_FEM1_4B_1ST_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 36
#define SOC_PB_IHB_FEM1_4B_1ST_PASS_MAP_INDEX_TABLE_TBL_ID 37
#define SOC_PB_IHB_FEM1_4B_1ST_PASS_MAP_TABLE_TBL_ID 38
#define SOC_PB_IHB_FEM2_14B_1ST_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 39
#define SOC_PB_IHB_FEM2_14B_1ST_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 40
#define SOC_PB_IHB_FEM2_14B_1ST_PASS_MAP_INDEX_TABLE_TBL_ID 41
#define SOC_PB_IHB_FEM2_14B_1ST_PASS_MAP_TABLE_TBL_ID 42
#define SOC_PB_IHB_FEM2_14B_1ST_PASS_OFFSET_TABLE_TBL_ID 43
#define SOC_PB_IHB_FEM3_14B_1ST_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 44
#define SOC_PB_IHB_FEM3_14B_1ST_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 45
#define SOC_PB_IHB_FEM3_14B_1ST_PASS_MAP_INDEX_TABLE_TBL_ID 46
#define SOC_PB_IHB_FEM3_14B_1ST_PASS_MAP_TABLE_TBL_ID 47
#define SOC_PB_IHB_FEM3_14B_1ST_PASS_OFFSET_TABLE_TBL_ID 48
#define SOC_PB_IHB_FEM4_14B_1ST_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 49
#define SOC_PB_IHB_FEM4_14B_1ST_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 50
#define SOC_PB_IHB_FEM4_14B_1ST_PASS_MAP_INDEX_TABLE_TBL_ID 51
#define SOC_PB_IHB_FEM4_14B_1ST_PASS_MAP_TABLE_TBL_ID 52
#define SOC_PB_IHB_FEM4_14B_1ST_PASS_OFFSET_TABLE_TBL_ID 53
#define SOC_PB_IHB_FEM5_17B_1ST_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 54
#define SOC_PB_IHB_FEM5_17B_1ST_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 55
#define SOC_PB_IHB_FEM5_17B_1ST_PASS_MAP_INDEX_TABLE_TBL_ID 56
#define SOC_PB_IHB_FEM5_17B_1ST_PASS_MAP_TABLE_TBL_ID 57
#define SOC_PB_IHB_FEM5_17B_1ST_PASS_OFFSET_TABLE_TBL_ID 58
#define SOC_PB_IHB_FEM6_17B_1ST_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 59
#define SOC_PB_IHB_FEM6_17B_1ST_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 60
#define SOC_PB_IHB_FEM6_17B_1ST_PASS_MAP_INDEX_TABLE_TBL_ID 61
#define SOC_PB_IHB_FEM6_17B_1ST_PASS_MAP_TABLE_TBL_ID 62
#define SOC_PB_IHB_FEM6_17B_1ST_PASS_OFFSET_TABLE_TBL_ID 63
#define SOC_PB_IHB_FEM7_17B_1ST_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 64
#define SOC_PB_IHB_FEM7_17B_1ST_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 65
#define SOC_PB_IHB_FEM7_17B_1ST_PASS_MAP_INDEX_TABLE_TBL_ID 66
#define SOC_PB_IHB_FEM7_17B_1ST_PASS_MAP_TABLE_TBL_ID 67
#define SOC_PB_IHB_FEM7_17B_1ST_PASS_OFFSET_TABLE_TBL_ID 68
#define SOC_PB_IHB_FEM0_4B_2ND_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 69
#define SOC_PB_IHB_FEM0_4B_2ND_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 70
#define SOC_PB_IHB_FEM0_4B_2ND_PASS_MAP_INDEX_TABLE_TBL_ID 71
#define SOC_PB_IHB_FEM0_4B_2ND_PASS_MAP_TABLE_TBL_ID 72
#define SOC_PB_IHB_FEM1_4B_2ND_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 73
#define SOC_PB_IHB_FEM1_4B_2ND_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 74
#define SOC_PB_IHB_FEM1_4B_2ND_PASS_MAP_INDEX_TABLE_TBL_ID 75
#define SOC_PB_IHB_FEM1_4B_2ND_PASS_MAP_TABLE_TBL_ID 76
#define SOC_PB_IHB_FEM2_14B_2ND_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 77
#define SOC_PB_IHB_FEM2_14B_2ND_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 78
#define SOC_PB_IHB_FEM2_14B_2ND_PASS_MAP_INDEX_TABLE_TBL_ID 79
#define SOC_PB_IHB_FEM2_14B_2ND_PASS_MAP_TABLE_TBL_ID 80
#define SOC_PB_IHB_FEM2_14B_2ND_PASS_OFFSET_TABLE_TBL_ID 81
#define SOC_PB_IHB_FEM3_14B_2ND_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 82
#define SOC_PB_IHB_FEM3_14B_2ND_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 83
#define SOC_PB_IHB_FEM3_14B_2ND_PASS_MAP_INDEX_TABLE_TBL_ID 84
#define SOC_PB_IHB_FEM3_14B_2ND_PASS_MAP_TABLE_TBL_ID 85
#define SOC_PB_IHB_FEM3_14B_2ND_PASS_OFFSET_TABLE_TBL_ID 86
#define SOC_PB_IHB_FEM4_14B_2ND_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 87
#define SOC_PB_IHB_FEM4_14B_2ND_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 88
#define SOC_PB_IHB_FEM4_14B_2ND_PASS_MAP_INDEX_TABLE_TBL_ID 89
#define SOC_PB_IHB_FEM4_14B_2ND_PASS_MAP_TABLE_TBL_ID 90
#define SOC_PB_IHB_FEM4_14B_2ND_PASS_OFFSET_TABLE_TBL_ID 91
#define SOC_PB_IHB_FEM5_17B_2ND_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 92
#define SOC_PB_IHB_FEM5_17B_2ND_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 93
#define SOC_PB_IHB_FEM5_17B_2ND_PASS_MAP_INDEX_TABLE_TBL_ID 94
#define SOC_PB_IHB_FEM5_17B_2ND_PASS_MAP_TABLE_TBL_ID 95
#define SOC_PB_IHB_FEM5_17B_2ND_PASS_OFFSET_TABLE_TBL_ID 96
#define SOC_PB_IHB_FEM6_17B_2ND_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 97
#define SOC_PB_IHB_FEM6_17B_2ND_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 98
#define SOC_PB_IHB_FEM6_17B_2ND_PASS_MAP_INDEX_TABLE_TBL_ID 99
#define SOC_PB_IHB_FEM6_17B_2ND_PASS_MAP_TABLE_TBL_ID 100
#define SOC_PB_IHB_FEM6_17B_2ND_PASS_OFFSET_TABLE_TBL_ID 101
#define SOC_PB_IHB_FEM7_17B_2ND_PASS_KEY_PROFILE_RESOLVED_DATA_TBL_ID 102
#define SOC_PB_IHB_FEM7_17B_2ND_PASS_PROGRAM_RESOLVED_DATA_TBL_ID 103
#define SOC_PB_IHB_FEM7_17B_2ND_PASS_MAP_INDEX_TABLE_TBL_ID 104
#define SOC_PB_IHB_FEM7_17B_2ND_PASS_MAP_TABLE_TBL_ID 105
#define SOC_PB_IHB_FEM7_17B_2ND_PASS_OFFSET_TABLE_TBL_ID 106
#define SOC_PB_IHB_PINFO_LBP_TBL_ID                  107
#define SOC_PB_IHB_HEADER_PROFILE_TBL_ID             108
#define SOC_PB_IQM_BDB_LINK_LIST_TBL_ID              109
#define SOC_PB_IQM_DYNAMIC_TBL_ID                    110
#define SOC_PB_IQM_STATIC_TBL_ID                     111
#define SOC_PB_IQM_PACKET_QUEUE_TAIL_POINTER_TBL_ID  112
#define SOC_PB_IQM_PACKET_QUEUE_RED_WEIGHT_TABLE_TBL_ID 113
#define SOC_PB_IQM_CREDIT_DISCOUNT_TABLE_TBL_ID      114
#define SOC_PB_IQM_FULL_USER_COUNT_MEMORY_TBL_ID     115
#define SOC_PB_IQM_MINI_MULTICAST_USER_COUNT_MEMORY_TBL_ID 116
#define SOC_PB_IQM_PACKET_QUEUE_RED_PARAMETERS_TABLE_TBL_ID 117
#define SOC_PB_IQM_VSQ_DESCRIPTOR_RATE_CLASS_GROUP_A_TBL_ID 118
#define SOC_PB_IQM_VSQ_DESCRIPTOR_RATE_CLASS_GROUP_B_TBL_ID 119
#define SOC_PB_IQM_VSQ_DESCRIPTOR_RATE_CLASS_GROUP_C_TBL_ID 120
#define SOC_PB_IQM_VSQ_DESCRIPTOR_RATE_CLASS_GROUP_D_TBL_ID 121
#define SOC_PB_IQM_VSQ_QSIZE_MEMORY_GROUP_A_TBL_ID   122
#define SOC_PB_IQM_VSQ_QSIZE_MEMORY_GROUP_B_TBL_ID   123
#define SOC_PB_IQM_VSQ_QSIZE_MEMORY_GROUP_C_TBL_ID   124
#define SOC_PB_IQM_VSQ_QSIZE_MEMORY_GROUP_D_TBL_ID   125
#define SOC_PB_IQM_VSQ_AVERAGE_QSIZE_MEMORY_GROUP_A_TBL_ID 126
#define SOC_PB_IQM_VSQ_AVERAGE_QSIZE_MEMORY_GROUP_B_TBL_ID 127
#define SOC_PB_IQM_VSQ_AVERAGE_QSIZE_MEMORY_GROUP_C_TBL_ID 128
#define SOC_PB_IQM_VSQ_AVERAGE_QSIZE_MEMORY_GROUP_D_TBL_ID 129
#define SOC_PB_IQM_VSQ_FLOW_CONTROL_PARAMETERS_TABLE_GROUP_A_TBL_ID 130
#define SOC_PB_IQM_VSQ_FLOW_CONTROL_PARAMETERS_TABLE_GROUP_B_TBL_ID 131
#define SOC_PB_IQM_VSQ_FLOW_CONTROL_PARAMETERS_TABLE_GROUP_C_TBL_ID 132
#define SOC_PB_IQM_VSQ_FLOW_CONTROL_PARAMETERS_TABLE_GROUP_D_TBL_ID 133
#define SOC_PB_IQM_VSQ_QUEUE_PARAMETERS_TABLE_GROUP_A_TBL_ID 134
#define SOC_PB_IQM_VSQ_QUEUE_PARAMETERS_TABLE_GROUP_B_TBL_ID 135
#define SOC_PB_IQM_VSQ_QUEUE_PARAMETERS_TABLE_GROUP_C_TBL_ID 136
#define SOC_PB_IQM_VSQ_QUEUE_PARAMETERS_TABLE_GROUP_D_TBL_ID 137
#define SOC_PB_IQM_SYSTEM_RED_PARAMETERS_TABLE_TBL_ID 138
#define SOC_PB_IQM_SYSTEM_RED_DROP_PROBABILITY_VALUES_TBL_ID 139
#define SOC_PB_IQM_SYSTEM_RED_TBL_ID                 140
#define SOC_PB_IQM_CNM_DESCRIPTOR_STATIC_TBL_ID      141
#define SOC_PB_IQM_CNM_DESCRIPTOR_DYNAMIC_TBL_ID     142
#define SOC_PB_IQM_CNM_PARAMETERS_TABLE_TBL_ID       143
#define SOC_PB_IQM_METER_PROCESSOR_RESULT_RESOLVE_TABLE_STATIC_TBL_ID 144
#define SOC_PB_IQM_PRFSELA_TBL_ID                    145
#define SOC_PB_IQM_PRFSELB_TBL_ID                    146
#define SOC_PB_IQM_PRFCFGA_TBL_ID                    147
#define SOC_PB_IQM_PRFCFGB_TBL_ID                    148
#define SOC_PB_IQM_NORMAL_DYNAMICA_TBL_ID            149
#define SOC_PB_IQM_NORMAL_DYNAMICB_TBL_ID            150
#define SOC_PB_IQM_HIGH_DYNAMICA_TBL_ID              151
#define SOC_PB_IQM_HIGH_DYNAMICB_TBL_ID              152
#define SOC_PB_IQM_CNTS_MEMA_TBL_ID                  153
#define SOC_PB_IQM_CNTS_MEMB_TBL_ID                  154
#define SOC_PB_IQM_OVTH_MEMA_TBL_ID                  155
#define SOC_PB_IQM_OVTH_MEMB_TBL_ID                  156
#define SOC_PB_QDR_QDR_MEM_TBL_ID                    157
#define SOC_PB_QDR_QDR_DLL_MEM_TBL_ID                158
#define SOC_PB_IPS_SYSTEM_PHYSICAL_PORT_LOOKUP_TABLE_TBL_ID 159
#define SOC_PB_IPS_DESTINATION_DEVICE_AND_PORT_LOOKUP_TABLE_TBL_ID 160
#define SOC_PB_IPS_FLOW_ID_LOOKUP_TABLE_TBL_ID       161
#define SOC_PB_IPS_QUEUE_TYPE_LOOKUP_TABLE_TBL_ID    162
#define SOC_PB_IPS_QUEUE_PRIORITY_MAP_SELECT_TBL_ID  163
#define SOC_PB_IPS_QUEUE_PRIORITY_MAPS_TABLE_TBL_ID  164
#define SOC_PB_IPS_QUEUE_SIZE_BASED_THRESHOLDS_TABLE_TBL_ID 165
#define SOC_PB_IPS_CREDIT_BALANCE_BASED_THRESHOLDS_TABLE_TBL_ID 166
#define SOC_PB_IPS_EMPTY_QUEUE_CREDIT_BALANCE_TABLE_TBL_ID 167
#define SOC_PB_IPS_CREDIT_WATCHDOG_THRESHOLDS_TABLE_TBL_ID 168
#define SOC_PB_IPS_QUEUE_DESCRIPTOR_TABLE_TBL_ID     169
#define SOC_PB_IPS_QUEUE_SIZE_TABLE_TBL_ID           170
#define SOC_PB_IPS_SYSTEM_RED_MAX_QUEUE_SIZE_TABLE_TBL_ID 171
#define SOC_PB_IPT_BDQ_TBL_ID                        172
#define SOC_PB_IPT_PCQ_TBL_ID                        173
#define SOC_PB_IPT_SOP_MMU_TBL_ID                    174
#define SOC_PB_IPT_MOP_MMU_TBL_ID                    175
#define SOC_PB_IPT_FDTCTL_TBL_ID                     176
#define SOC_PB_IPT_FDTDATA_TBL_ID                    177
#define SOC_PB_IPT_EGQCTL_TBL_ID                     178
#define SOC_PB_IPT_EGQDATA_TBL_ID                    179
#define SOC_PB_IPT_SELECT_SOURCE_COUNTER_TBL_ID      180
#define SOC_PB_IPT_SELECT_SOURCE_SUM_TBL_ID          181
#define SOC_PB_MMU_DRAM_ADDRESS_SPACE_TBL_ID         182
#define SOC_PB_MMU_IDF_TBL_ID                        183
#define SOC_PB_MMU_FDF_TBL_ID                        184
#define SOC_PB_MMU_WAF_HALFA_WADDR_TBL_ID            185
#define SOC_PB_MMU_WAF_HALFB_WADDR_TBL_ID            186
#define SOC_PB_MMU_WAFA_HALFA_RADDR_STATUS_TBL_ID    187
#define SOC_PB_MMU_WAFB_HALFA_RADDR_STATUS_TBL_ID    188
#define SOC_PB_MMU_WAFC_HALFA_RADDR_STATUS_TBL_ID    189
#define SOC_PB_MMU_WAFD_HALFA_RADDR_STATUS_TBL_ID    190
#define SOC_PB_MMU_WAFE_HALFA_RADDR_STATUS_TBL_ID    191
#define SOC_PB_MMU_WAFF_HALFA_RADDR_STATUS_TBL_ID    192
#define SOC_PB_MMU_WAFA_HALFB_RADDR_STATUS_TBL_ID    193
#define SOC_PB_MMU_WAFB_HALFB_RADDR_STATUS_TBL_ID    194
#define SOC_PB_MMU_WAFC_HALFB_RADDR_STATUS_TBL_ID    195
#define SOC_PB_MMU_WAFD_HALFB_RADDR_STATUS_TBL_ID    196
#define SOC_PB_MMU_WAFE_HALFB_RADDR_STATUS_TBL_ID    197
#define SOC_PB_MMU_WAFF_HALFB_RADDR_STATUS_TBL_ID    198
#define SOC_PB_MMU_RAF_WADDR_TBL_ID                  199
#define SOC_PB_MMU_RAFA_RADDR_STATUS_TBL_ID          200
#define SOC_PB_MMU_RAFB_RADDR_STATUS_TBL_ID          201
#define SOC_PB_MMU_RAFC_RADDR_STATUS_TBL_ID          202
#define SOC_PB_MMU_RAFD_RADDR_STATUS_TBL_ID          203
#define SOC_PB_MMU_RAFE_RADDR_STATUS_TBL_ID          204
#define SOC_PB_MMU_RAFF_RADDR_STATUS_TBL_ID          205
#define SOC_PB_MMU_RDFA_WADDR_STATUS_TBL_ID          206
#define SOC_PB_MMU_RDFB_WADDR_STATUS_TBL_ID          207
#define SOC_PB_MMU_RDFC_WADDR_STATUS_TBL_ID          208
#define SOC_PB_MMU_RDFD_WADDR_STATUS_TBL_ID          209
#define SOC_PB_MMU_RDFE_WADDR_STATUS_TBL_ID          210
#define SOC_PB_MMU_RDFF_WADDR_STATUS_TBL_ID          211
#define SOC_PB_MMU_RDF_RADDR_TBL_ID                  212
#define SOC_PB_DPI_DLL_RAM_TBL_A_ID                  213
#define SOC_PB_DPI_DLL_RAM_TBL_B_ID                  214
#define SOC_PB_DPI_DLL_RAM_TBL_C_ID                  215
#define SOC_PB_DPI_DLL_RAM_TBL_D_ID                  216
#define SOC_PB_DPI_DLL_RAM_TBL_E_ID                  217
#define SOC_PB_DPI_DLL_RAM_TBL_F_ID                  218
#define SOC_PB_RTP_UNICAST_DISTRIBUTION_MEMORY_FOR_DATA_CELLS_TBL_ID 219
#define SOC_PB_RTP_UNICAST_DISTRIBUTION_MEMORY_FOR_CONTROL_CELLS_TBL_ID 220
#define SOC_PB_EGQ_NIF_MAL0_SCM_TBL_ID               221
#define SOC_PB_EGQ_NIF_MAL1_SCM_TBL_ID               222
#define SOC_PB_EGQ_NIF_MAL2_SCM_TBL_ID               223
#define SOC_PB_EGQ_NIF_MAL3_SCM_TBL_ID               224
#define SOC_PB_EGQ_NIF_MAL4_SCM_TBL_ID               225
#define SOC_PB_EGQ_NIF_MAL5_SCM_TBL_ID               226
#define SOC_PB_EGQ_NIF_MAL6_SCM_TBL_ID               227
#define SOC_PB_EGQ_NIF_MAL7_SCM_TBL_ID               228
#define SOC_PB_EGQ_NIF_MAL8_SCM_TBL_ID               229
#define SOC_PB_EGQ_NIF_MAL9_SCM_TBL_ID               230
#define SOC_PB_EGQ_NIF_MAL10_SCM_TBL_ID              231
#define SOC_PB_EGQ_NIF_MAL11_SCM_TBL_ID              232
#define SOC_PB_EGQ_NIF_MAL12_SCM_TBL_ID              233
#define SOC_PB_EGQ_NIF_MAL13_SCM_TBL_ID              234
#define SOC_PB_EGQ_NIF_MAL14_SCM_TBL_ID              235
#define SOC_PB_EGQ_NIF_MAL15_SCM_TBL_ID              236
#define SOC_PB_EGQ_RCY_SCM_TBL_ID                    237
#define SOC_PB_EGQ_CPU_SCM_TBL_ID                    238
#define SOC_PB_EGQ_CCM_TBL_ID                        239
#define SOC_PB_EGQ_PMC_TBL_ID                        240
#define SOC_PB_EGQ_CBM_TBL_ID                        241
#define SOC_PB_EGQ_FBM_TBL_ID                        242
#define SOC_PB_EGQ_FDM_TBL_ID                        243
#define SOC_PB_EGQ_QM_TBL_ID                         244
#define SOC_PB_EGQ_QSM_TBL_ID                        245
#define SOC_PB_EGQ_DCM_TBL_ID                        246
#define SOC_PB_EGQ_DWM0_TBL_ID                       247
#define SOC_PB_EGQ_DWM1_TBL_ID                       248
#define SOC_PB_EGQ_RRDM_TBL_ID                       249
#define SOC_PB_EGQ_RPDM_TBL_ID                       250
#define SOC_PB_EGQ_PCT_TBL_ID                        251
#define SOC_PB_EGQ_VLAN_TABLE_TBL_ID                 252
#define SOC_PB_EGQ_TC_DP_MAP_TBL_ID                  253
#define SOC_PB_EGQ_CFC_FLOW_CONTROL_TBL_ID           254
#define SOC_PB_EGQ_NIFA_FLOW_CONTROL_TBL_ID          255
#define SOC_PB_EGQ_NIFB_FLOW_CONTROL_TBL_ID          256
#define SOC_PB_EGQ_CPU_LAST_HEADER_TBL_ID            257
#define SOC_PB_EGQ_IPT_LAST_HEADER_TBL_ID            258
#define SOC_PB_EGQ_FDR_LAST_HEADER_TBL_ID            259
#define SOC_PB_EGQ_CPU_PACKET_COUNTER_TBL_ID         260
#define SOC_PB_EGQ_IPT_PACKET_COUNTER_TBL_ID         261
#define SOC_PB_EGQ_FDR_PACKET_COUNTER_TBL_ID         262
#define SOC_PB_EGQ_RQP_PACKET_COUNTER_TBL_ID         263
#define SOC_PB_EGQ_RQP_DISCARD_PACKET_COUNTER_TBL_ID 264
#define SOC_PB_EGQ_EHP_UNICAST_PACKET_COUNTER_TBL_ID 265
#define SOC_PB_EGQ_EHP_MULTICAST_HIGH_PACKET_COUNTER_TBL_ID 266
#define SOC_PB_EGQ_EHP_MULTICAST_LOW_PACKET_COUNTER_TBL_ID 267
#define SOC_PB_EGQ_EHP_DISCARD_PACKET_COUNTER_TBL_ID 268
#define SOC_PB_EGQ_PQP_UNICAST_HIGH_PACKET_COUNTER_TBL_ID 269
#define SOC_PB_EGQ_PQP_UNICAST_LOW_PACKET_COUNTER_TBL_ID 270
#define SOC_PB_EGQ_PQP_MULTICAST_HIGH_PACKET_COUNTER_TBL_ID 271
#define SOC_PB_EGQ_PQP_MULTICAST_LOW_PACKET_COUNTER_TBL_ID 272
#define SOC_PB_EGQ_PQP_UNICAST_HIGH_BYTES_COUNTER_TBL_ID 273
#define SOC_PB_EGQ_PQP_UNICAST_LOW_BYTES_COUNTER_TBL_ID 274
#define SOC_PB_EGQ_PQP_MULTICAST_HIGH_BYTES_COUNTER_TBL_ID 275
#define SOC_PB_EGQ_PQP_MULTICAST_LOW_BYTES_COUNTER_TBL_ID 276
#define SOC_PB_EGQ_PQP_DISCARD_UNICAST_PACKET_COUNTER_TBL_ID 277
#define SOC_PB_EGQ_PQP_DISCARD_MULTICAST_PACKET_COUNTER_TBL_ID 278
#define SOC_PB_EGQ_FQP_PACKET_COUNTER_TBL_ID         279
#define SOC_PB_EGQ_FQP_NIF_PORT_MUX_TBL_ID           280
#define SOC_PB_EGQ_CFM_TRAP_TBL_ID                   281
#define SOC_PB_EGQ_KEY_PROFILE_MAP_INDEX_TBL_ID      282
#define SOC_PB_EGQ_TCAM_KEY_RESOLUTION_PROFILE_TBL_ID 283
#define SOC_PB_EPNI_EPE_PACKET_COUNTER_TBL_ID        284
#define SOC_PB_EPNI_EPE_BYTES_COUNTER_TBL_ID         285
#define SOC_PB_EPNI_ENCAPSULATION_DB_BANK1_TBL_ID    286
#define SOC_PB_EPNI_ENCAPSULATION_DB_BANK2_TBL_ID    287
#define SOC_PB_EPNI_TX_TAG_TABLE_TBL_ID              288
#define SOC_PB_EPNI_COPY_ENGINE0_PROGRAM_TBL_ID      289
#define SOC_PB_EPNI_COPY_ENGINE1_PROGRAM_TBL_ID      290
#define SOC_PB_EPNI_COPY_ENGINE2_PROGRAM_TBL_ID      291
#define SOC_PB_CFC_RCL2_OFP_TBL_ID                   292
#define SOC_PB_CFC_NIFCLSB2_OFP_TBL_ID               293
#define SOC_PB_CFC_CALRXA_TBL_ID                     294
#define SOC_PB_CFC_CALRXB_TBL_ID                     295
#define SOC_PB_CFC_OOB0_SCH_MAP_TBL_ID               296
#define SOC_PB_CFC_OOB1_SCH_MAP_TBL_ID               297
#define SOC_PB_CFC_CALTX_TBL_ID                      298
#define SOC_PB_CFC_ILKN0_CALRX_TBL_ID                299
#define SOC_PB_CFC_ILKN1_CALRX_TBL_ID                300
#define SOC_PB_CFC_ILKN0_SCH_MAP_TBL_ID              301
#define SOC_PB_CFC_ILKN1_SCH_MAP_TBL_ID              302
#define SOC_PB_CFC_ILKN0_CALTX_TBL_ID                303
#define SOC_PB_CFC_ILKN1_CALTX_TBL_ID                304
#define SOC_PB_SCH_CAL_TBL_ID                        305
#define SOC_PB_SCH_DRM_TBL_ID                        306
#define SOC_PB_SCH_DSM_TBL_ID                        307
#define SOC_PB_SCH_FDMS_TBL_ID                       308
#define SOC_PB_SCH_SHDS_TBL_ID                       309
#define SOC_PB_SCH_SEM_TBL_ID                        310
#define SOC_PB_SCH_FSF_TBL_ID                        311
#define SOC_PB_SCH_FGM_TBL_ID                        312
#define SOC_PB_SCH_SHC_TBL_ID                        313
#define SOC_PB_SCH_SCC_TBL_ID                        314
#define SOC_PB_SCH_SCT_TBL_ID                        315
#define SOC_PB_SCH_FQM_TBL_ID                        316
#define SOC_PB_SCH_FFM_TBL_ID                        317
#define SOC_PB_SCH_TMC_TBL_ID                        318
#define SOC_PB_SCH_PQS_TBL_ID                        319
#define SOC_PB_SCH_SCHEDULER_INIT_TBL_ID             320
#define SOC_PB_SCH_FORCE_STATUS_MESSAGE_TBL_ID       321
#define SOC_PB_EPNI_LFEM_FIELD_SELECT_MAP_TBL_ID0    322
#define SOC_PB_EPNI_LFEM_FIELD_SELECT_MAP_TBL_ID1    323
#define SOC_PB_EPNI_LFEM_FIELD_SELECT_MAP_TBL_ID2    324
#define SOC_PB_IDR_ETHERNET_METER_STATUS_TBL_ID      325
#define SOC_PB_FDT_IPT_CONTRO_L_FIFO_TBL_ID          326
#define SOC_PB_TBL_ID_LAST                           327
/* table index definitions } */
/* } */

/*************
 * GLOBALS   *
 *************/
/* { */
/* } */

/*************
 * FUNCTIONS *
 *************/
/* { */
/*****************************************************
*NAME
* soc_pb_tm_indirect_blocks_init
*TYPE:
*  PROC
*FUNCTION:
*INPUT:
*  SOC_SAND_DIRECT:
*    None.
*  SOC_SAND_INDIRECT:
*    None.
*OUTPUT:
*  SOC_SAND_DIRECT:
*    error indication
*  SOC_SAND_INDIRECT:
*    *soc_pb_tbls.
*REMARKS:
*    None.
*SEE ALSO:
*****************************************************/
void
  soc_pb_tm_indirect_blocks_init(
  );
/* } */

#include <soc/dpp/SAND/Utils/sand_footer.h>

/* } __CHIP_SIM_PB_TM_INCLUDED__*/
#endif
