#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/field/map/auto_generated

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/shared

lib = libbcm_dnxfieldmap_auto_generated

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

