

FP_BASE=../../../..

FPLIB=fp_dai.a

#
# DHCP Filtering Public Make file.
#

# Do not change this line.
#
include $(FP_BASE)/src/l7tools/build/make.cfg

# Specify the correct relative path for libsw.a file.
LIBDIR=../lib

# Specify compile flags.
#
CFLAGSLOCAL= -I.  $(GFLAG) 

# Specify modules that need to be compiled.
#
LIBOBJS=usmdb_dai.o 

# Do not change this line.
#
include $(FP_BASE)/src/l7tools/build/make.footer

