#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/diag/dnx/fabric

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxfabric

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

