# $Id: $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for streamlined packet I/O drivers
#

include ${SDK}/make/Make.config

subdirs := buf dev gih higig3 lbpmd net rxpmd socket sym txpmd unet
include ${SDK}/make/Make.subdirs
