# $Id: Makefile Exp $
#
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Helix5 SOC driver Library
#

LOCALDIR = src/soc/esw/tdm/helix5/

include ${SDK}/make/Make.config

lib = libsoc_tdm_hx5

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

