# $Id: $
#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# $Id$
# Makefile for Firelight SOC driver Library
#

LOCALDIR = src/soc/esw/firelight

include ${SDK}/make/Make.config

lib = libsoc_firelight

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
