#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/init

include ${SDK}/make/Make.config

lib = libbcm_dnxinit

subdirs = auto_generated


include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

