#!/bin/sh

thisapp=$0
mode="run"
app_name=switchdrvr
app_path=/usr/local/ptin/sbin/$app_name
cli=/usr/local/ptin/sbin/fp.cli
startup_log=/usr/local/ptin/log/fastpath/startup.log
proc_txt=/usr/local/ptin/log/fastpath/proc.txt
ntry=0

insert_modules()
{
    echo "Creating character device..."
    if [ ! -c /dev/linux-kernel-bde ]; then
      mknod /dev/linux-kernel-bde c 127 0
    fi
    if [ ! -c /dev/linux-user-bde ]; then
      mknod /dev/linux-user-bde c 126 0
    fi
    echo "Inserting modules..."
    insmod /usr/local/ptin/sbin/linux-kernel-bde.ko dmasize=16M debug=1
    insmod /usr/local/ptin/sbin/linux-user-bde.ko
    sleep 1
    echo "Ready to start Fastpath..."
}


startup()
{
    # Add header info to startup log file
    echo "*************************************************************" >> $startup_log
    echo "FASTPATH STARTED AT: `date` [retry $ntry]" >> $startup_log
    ps >> $startup_log
    free >> $startup_log

    # Insert modules
    insert_modules;

    # Launch app
    $app_path 0>/dev/null &

    # Wait 200 seconds for FP to boot up
    $cli ping 10 20

    let "ntry=ntry+1"
}

# If no options, define default mode
if [ ! -z $1 ]; then
    mode=$1
fi

# Option: insert modules
if [ $mode = "insmod" ]; then
    insert_modules;

# Option: stop
elif [ $mode = "stop" ]; then

    # Kill fastpath script process
    ps > proc.tmp
    pid_proc=`cat proc.tmp | grep $thisapp" boot" | awk '{print $1}'`
    if [ ! -z $pid_proc ]; then
        kill $pid_proc
    fi
    rm proc.tmp

    # Now, kill the switchdrvr application
    killall $app_name
    killall tail

# Option: boot
elif [ $mode = "boot" ]; then
    # Check if file exists
    if [ ! -e $app_path ]; then
        echo "File $app_path does not exist!"
        echo "Aborting FastPath launch!"
        exit 1;
    fi
    
    # Handle startup log oversize issues
    filesize=`du $startup_log`
    if [ "$?" -eq "0" ]; then
        filesize=`echo $filesize | awk '{print $1}'`
        echo "File $startup_log has a size of $filesize KB"
    else
        filesize=0;
    fi
    if [ $filesize -gt "2048" ]; then
      echo "Move file $startup_log => startup_log.old"
      mv -f $startup_log $startup_log.old
    fi

    # Query application to determine if it is running or not
    $cli ping 6 4 > /dev/null
    # Start application
    if [ "$?" -ne "0" ]; then
        echo "Going to start application"
        startup;
    fi

    # Working loop...
    while [ 1 ]
    do
        # Query application to determine if it is running or not
        $cli ping 10 12 > /dev/null
        if [ "$?" -ne "0" ]; then
            echo "Transferring LOGs to Matrix board..."
            echo "Fastpath watchdog fired after 10x12 seconds of inactivity!" > /var/log/system_error_info.log
            /bin/sh /usr/local/ptin/scripts/transfer_logs.sh
            echo "Rebooting board"
            reboot;
            exit;
        else
            sleep 30
        fi
    done

# No option (normal launch)
else
    # Check if file exists
    if [ ! -e $app_path ]; then
        echo "File $app_path does not exist!"
        echo "Aborting FastPath launch!"
        exit 1;
    fi
    
    # Check if app or script is already running
    ps > $proc_txt
    nproc1=$(cat $proc_txt | grep -c $app_name)
    nproc2=$(cat $proc_txt | grep -c $thisapp" boot")

    if [ $nproc1 != 0 ]; then
        echo "$app_name is already running! ($nproc)"
        exit 1
    elif [ $nproc2 != 0 ]; then
        echo "There is already a deamon responsible to startup $app_name ($nproc2)"
        exit 1
    fi

    # Launch app
#    nice -n -19 $app_path 0>/dev/null &
    $app_path 0>/dev/null &
fi

