/**
 * \file diag_sand_resource.c
 *
 * Framework for sand shell commands development
 *
 */
/*
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */

#include <appl/diag/sand/diag_sand_framework.h>
#include <appl/diag/sand/diag_sand_utils.h>

sh_sand_option_t sh_sand_sys_options[] = {
    {"CoLuMNs",  SAL_FIELD_TYPE_INT32, "Maximum columns number for output",                                 "80"},
    {"core",     SAL_FIELD_TYPE_INT32, "Core ID for multi-core devices",                                    "-1"},
    {"file",     SAL_FIELD_TYPE_STR,   "File name where command output will be placed",                     ""},
    {"MaRGin",   SAL_FIELD_TYPE_INT32, "Left&Right margin of defined display width",                        "7"},
    {"reset",    SAL_FIELD_TYPE_BOOL,  "Either enforce reset after failure or not",                         "Yes"},
    {"pre",      SAL_FIELD_TYPE_BOOL,  "Export only tests with precommit flag",                             "No"},
    {"TABular",  SAL_FIELD_TYPE_BOOL,  "Print usage in tabular view",                                       "No"},
    {"VERbose",  SAL_FIELD_TYPE_BOOL,  "Print all options",                                                 "No"},
    {NULL}
};

/*
 * All command and option keywords should be present to below global keyword list.
 * Before adding new keywords to this list:
 *      Please verify that there are no already existing keywords that may fit your needs
 * Capital letters will represent shortcut that may be used instead of full keyword
 * List should be arranged in alphabet order
 */
sh_sand_keyword_t sh_sand_keywords[] = {
    {"ACCess"},
    {"ACTion"},
    {"Add"},
    {"ADdRess"},
    {"ALL"},
    {"ALLOCate"},
    {"alloc_after_init"},
    {"APPLication"},
    {"app_id"},
    {"ARR"},
    {"array_range"},
    {"bcm"},
    {"bitmap"},
    {"BLock"},
    {"bool"},
    {"buffer"},
    {"cache"},
    {"CHanGed"},
    {"CLear"},
    {"CoMmit"},
    {"ConFiG"},
    {"CoNGeSTion"},
    {"CONnectivity"},
    {"ConTeXt"},
    {"ContextSelect"},
    {"CouNT"},
    {"counter"},
    {"CounteRProceSsor"},	
    {"CuSToM"},
    {"DaTa"},
    {"DBaL"},
    {"DeCoDe"},
    {"DEFine"},
    {"DeINiT"},
    {"DeLeTe"},
    {"DESC"},
    {"dir"},
    {"DeSTination"},
    {"DIRECT"},
    {"DNX"},
    {"DNXData"},
    {"DuMP"},
    {"EEDB"},
    {"EM"},
    {"engine"},
    {"ENTry"},
    {"enum"},
    {"ETHernet"},
    {"export"},
    {"Fabric"},
    {"FEATURE"},
    {"FieLD"},
    {"file"},
    {"FLaGs"},
    {"from"},
    {"full"},
    {"Get"},
    {"HanDLe"},
    {"hit"},
    {"HL"},
    {"HWElement"},
    {"ID"},
    {"INDex"},
    {"INFO"},
    {"INGress"},
    {"int"},
    {"input_value"},
    {"ip"},
    {"ip4"},
    {"ip6"},
    {"itmh_start"},
    {"KBR"},
    {"Key"},
    {"Key_SIZE"},
    {"KLeaP"},
    {"LaBeL"},
    {"Last"},
    {"link"},
    {"List"},
    {"LPM"},
    {"LoGger"},
    {"Ltt"},
    {"Ltt_Full"},
    {"mac"},
    {"MaCRo"},
    {"MAPping"},
    {"MaTuRity"},
    {"MDB"},
    {"mesh_topology"},
    {"MoDe"},
    {"modid"},
    {"mgmt"},
    {"mutex"},
    {"NaMe"},
    {"NUMERIC"},
    {"num_cos"},
    {"order"},
    {"over"},
    {"overwrite"},
    {"PARAMeter"},
    {"PaRSer"},
    {"PayLoad"},
    {"PayLoad_SIZE"},
    {"pfc"},
    {"pipe"},
    {"PhyDB"},
    {"plc"},
    {"pointer"},
    {"Port"},
    {"PPaRSe"},
    {"prefix_length"},
    {"PRIOrity"},
    {"PRoPerty"},
    {"PROTOcol"},
    {"QUALifier"},
    {"Queue"},
    {"raw"},
    {"Read"},
    {"REASSembly"},
    {"REACHability"},
    {"ReSeT"},
    {"ReSouRCe"},
    {"Run"},
    {"search"},
    {"SeGMent"},
    {"Set"},
    {"SeVeRity"},
    {"SHow"},
    {"SIGnal"},
    {"size"},
    {"SouRCe"},
    {"STAGE"},
    {"StaTuS"},
    {"STRUCTure"},
    {"swstate"},
    {"TaBLe"},
    {"TeMPLate"},
    {"TeST"},
    {"THreShold"},
    {"TO"},
    {"tm"},
    {"traffic_profile"},
    {"Type"},
    {"TYPes"},
    {"VALue"},
    {"variable"},
    {"WB"},
    {"with_id"},
    {NULL}
};
