# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM Trident3 driver Library
#

LOCALDIR = src/bcm/esw/trident3

include ${SDK}/make/Make.config

lib = libtrident3

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
