#
# $Id$
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dpp subdirectory
#

LOCALDIR = src/soc/dnxc/swstate

include ${SDK}/make/Make.config

#
# Take the subdirs 'auto_generated utils'
#
subdirs = auto_generated utils types

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxcswstate

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

