#!/bin/sh

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <binary unstripped> <error file>"
  exit 1
fi

ADDR2LINE="/opt/broadcom_kt2_hx4/usr/bin/arm-linux-addr2line"
OPTIONS="--exe=$1 -fs"

cat $2 | grep '^0x' | xargs $ADDR2LINE $OPTIONS
