#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/instru

include ${SDK}/make/Make.config

lib = libbcm_dnxinstru

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

