/* $Id: $
 * 
 * $Copyright: Copyright 2016 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * search for 'sw_state_cbs_t' for the root of the struct
 */

#ifndef _SHR_SW_STATE_DPP_BCM_L3_ACCESS_H_
#define _SHR_SW_STATE_DPP_BCM_L3_ACCESS_H_

/********************************* access calbacks definitions *************************************/
/* this set of callbacks, are the callbacks used in the access calbacks struct 'sw_state_cbs_t' to */
/* access the data in 'sw_state_t'.                                                                */
/* the calbacks are inserted into the access struct by 'sw_state_access_cb_init'.                  */
/***************************************************************************************************/

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_alloc */
typedef int (*sw_state_dpp_bcm_l3_alloc_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_is_allocated */
typedef int (*sw_state_dpp_bcm_l3_is_allocated_cb)(
    int unit, uint8 *is_allocated);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_free */
typedef int (*sw_state_dpp_bcm_l3_free_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_verify */
typedef int (*sw_state_dpp_bcm_l3_verify_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_used_intf_set */
typedef int (*sw_state_dpp_bcm_l3_used_intf_set_cb)(
    int unit, int used_intf);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_used_intf_get */
typedef int (*sw_state_dpp_bcm_l3_used_intf_get_cb)(
    int unit, int *used_intf);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_used_intf_verify */
typedef int (*sw_state_dpp_bcm_l3_used_intf_verify_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_used_vrf_set */
typedef int (*sw_state_dpp_bcm_l3_used_vrf_set_cb)(
    int unit, int used_vrf);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_used_vrf_get */
typedef int (*sw_state_dpp_bcm_l3_used_vrf_get_cb)(
    int unit, int *used_vrf);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_used_vrf_verify */
typedef int (*sw_state_dpp_bcm_l3_used_vrf_verify_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_used_host_set */
typedef int (*sw_state_dpp_bcm_l3_used_host_set_cb)(
    int unit, int used_host);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_used_host_get */
typedef int (*sw_state_dpp_bcm_l3_used_host_get_cb)(
    int unit, int *used_host);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_used_host_verify */
typedef int (*sw_state_dpp_bcm_l3_used_host_verify_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_used_route_set */
typedef int (*sw_state_dpp_bcm_l3_used_route_set_cb)(
    int unit, int used_route);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_used_route_get */
typedef int (*sw_state_dpp_bcm_l3_used_route_get_cb)(
    int unit, int *used_route);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_used_route_verify */
typedef int (*sw_state_dpp_bcm_l3_used_route_verify_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_alloc */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_alloc_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_is_allocated */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_is_allocated_cb)(
    int unit, uint8 *is_allocated);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_free */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_free_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_verify */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_verify_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_init_set */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_init_set_cb)(
    int unit, int init);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_init_get */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_init_get_cb)(
    int unit, int *init);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_init_verify */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_init_verify_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_urpf_mode_set */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_urpf_mode_set_cb)(
    int unit, int urpf_mode);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_urpf_mode_get */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_urpf_mode_get_cb)(
    int unit, int *urpf_mode);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_urpf_mode_verify */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_urpf_mode_verify_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_set */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_set_cb)(
    int unit, int bcm_tunnel_intf_to_eep_idx_0, int bcm_tunnel_intf_to_eep);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_get */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_get_cb)(
    int unit, int bcm_tunnel_intf_to_eep_idx_0, int *bcm_tunnel_intf_to_eep);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_alloc */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_alloc_cb)(
    int unit, int nof_instances_to_alloc);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_is_allocated */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_is_allocated_cb)(
    int unit, uint8 *is_allocated);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_free */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_free_cb)(
    int unit);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_verify */
typedef int (*sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_verify_cb)(
    int unit, int bcm_tunnel_intf_to_eep_idx_0);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_vrrp_protocol_set_types_set */
typedef int (*sw_state_dpp_bcm_l3_vrrp_protocol_set_types_set_cb)(
    int unit, int vrrp_protocol_set_types_idx_0, uint32 vrrp_protocol_set_types);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_vrrp_protocol_set_types_get */
typedef int (*sw_state_dpp_bcm_l3_vrrp_protocol_set_types_get_cb)(
    int unit, int vrrp_protocol_set_types_idx_0, uint32 *vrrp_protocol_set_types);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_vrrp_protocol_set_types_verify */
typedef int (*sw_state_dpp_bcm_l3_vrrp_protocol_set_types_verify_cb)(
    int unit, int vrrp_protocol_set_types_idx_0);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_vrrp_protocol_set_counts_set */
typedef int (*sw_state_dpp_bcm_l3_vrrp_protocol_set_counts_set_cb)(
    int unit, int vrrp_protocol_set_counts_idx_0, uint32 vrrp_protocol_set_counts);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_vrrp_protocol_set_counts_get */
typedef int (*sw_state_dpp_bcm_l3_vrrp_protocol_set_counts_get_cb)(
    int unit, int vrrp_protocol_set_counts_idx_0, uint32 *vrrp_protocol_set_counts);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
/* implemented by: sw_state_dpp_bcm_l3_vrrp_protocol_set_counts_verify */
typedef int (*sw_state_dpp_bcm_l3_vrrp_protocol_set_counts_verify_cb)(
    int unit, int vrrp_protocol_set_counts_idx_0);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

/*********************************** access calbacks struct ****************************************/
/* this set of structs, rooted at 'sw_state_cbs_t' define the access layer for the entire SW state.*/
/* use this tree to alloc/free/set/get fields in the sw state rooted at 'sw_state_t'.              */
/* NOTE: 'sw_state_t' data should not be accessed directly.                                        */
/***************************************************************************************************/

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
typedef struct sw_state_dpp_bcm_l3_used_intf_cbs_s {
    sw_state_dpp_bcm_l3_used_intf_set_cb set;
    sw_state_dpp_bcm_l3_used_intf_get_cb get;
    sw_state_dpp_bcm_l3_used_intf_verify_cb verify;
} sw_state_dpp_bcm_l3_used_intf_cbs_t;
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
typedef struct sw_state_dpp_bcm_l3_used_vrf_cbs_s {
    sw_state_dpp_bcm_l3_used_vrf_set_cb set;
    sw_state_dpp_bcm_l3_used_vrf_get_cb get;
    sw_state_dpp_bcm_l3_used_vrf_verify_cb verify;
} sw_state_dpp_bcm_l3_used_vrf_cbs_t;
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
typedef struct sw_state_dpp_bcm_l3_used_host_cbs_s {
    sw_state_dpp_bcm_l3_used_host_set_cb set;
    sw_state_dpp_bcm_l3_used_host_get_cb get;
    sw_state_dpp_bcm_l3_used_host_verify_cb verify;
} sw_state_dpp_bcm_l3_used_host_cbs_t;
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
typedef struct sw_state_dpp_bcm_l3_used_route_cbs_s {
    sw_state_dpp_bcm_l3_used_route_set_cb set;
    sw_state_dpp_bcm_l3_used_route_get_cb get;
    sw_state_dpp_bcm_l3_used_route_verify_cb verify;
} sw_state_dpp_bcm_l3_used_route_cbs_t;
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
typedef struct sw_state_dpp_bcm_l3_dpp_l3_state_init_cbs_s {
    sw_state_dpp_bcm_l3_dpp_l3_state_init_set_cb set;
    sw_state_dpp_bcm_l3_dpp_l3_state_init_get_cb get;
    sw_state_dpp_bcm_l3_dpp_l3_state_init_verify_cb verify;
} sw_state_dpp_bcm_l3_dpp_l3_state_init_cbs_t;
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
typedef struct sw_state_dpp_bcm_l3_dpp_l3_state_urpf_mode_cbs_s {
    sw_state_dpp_bcm_l3_dpp_l3_state_urpf_mode_set_cb set;
    sw_state_dpp_bcm_l3_dpp_l3_state_urpf_mode_get_cb get;
    sw_state_dpp_bcm_l3_dpp_l3_state_urpf_mode_verify_cb verify;
} sw_state_dpp_bcm_l3_dpp_l3_state_urpf_mode_cbs_t;
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
typedef struct sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_cbs_s {
    sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_set_cb set;
    sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_get_cb get;
    sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_alloc_cb alloc;
    sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_is_allocated_cb is_allocated;
    sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_free_cb free;
    sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_verify_cb verify;
} sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_cbs_t;
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
typedef struct sw_state_dpp_bcm_l3_dpp_l3_state_cbs_s {
    sw_state_dpp_bcm_l3_dpp_l3_state_alloc_cb alloc;
    sw_state_dpp_bcm_l3_dpp_l3_state_is_allocated_cb is_allocated;
    sw_state_dpp_bcm_l3_dpp_l3_state_free_cb free;
    sw_state_dpp_bcm_l3_dpp_l3_state_verify_cb verify;
    sw_state_dpp_bcm_l3_dpp_l3_state_init_cbs_t init;
    sw_state_dpp_bcm_l3_dpp_l3_state_urpf_mode_cbs_t urpf_mode;
    sw_state_dpp_bcm_l3_dpp_l3_state_bcm_tunnel_intf_to_eep_cbs_t bcm_tunnel_intf_to_eep;
} sw_state_dpp_bcm_l3_dpp_l3_state_cbs_t;

#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 
#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
typedef struct sw_state_dpp_bcm_l3_vrrp_protocol_set_types_cbs_s {
    sw_state_dpp_bcm_l3_vrrp_protocol_set_types_set_cb set;
    sw_state_dpp_bcm_l3_vrrp_protocol_set_types_get_cb get;
    sw_state_dpp_bcm_l3_vrrp_protocol_set_types_verify_cb verify;
} sw_state_dpp_bcm_l3_vrrp_protocol_set_types_cbs_t;
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
typedef struct sw_state_dpp_bcm_l3_vrrp_protocol_set_counts_cbs_s {
    sw_state_dpp_bcm_l3_vrrp_protocol_set_counts_set_cb set;
    sw_state_dpp_bcm_l3_vrrp_protocol_set_counts_get_cb get;
    sw_state_dpp_bcm_l3_vrrp_protocol_set_counts_verify_cb verify;
} sw_state_dpp_bcm_l3_vrrp_protocol_set_counts_cbs_t;
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
typedef struct sw_state_dpp_bcm_l3_cbs_s {
#if defined(BCM_PETRA_SUPPORT)
    sw_state_dpp_bcm_l3_alloc_cb alloc;
#endif /* defined(BCM_PETRA_SUPPORT)*/ 
#if defined(BCM_PETRA_SUPPORT)
    sw_state_dpp_bcm_l3_is_allocated_cb is_allocated;
#endif /* defined(BCM_PETRA_SUPPORT)*/ 
#if defined(BCM_PETRA_SUPPORT)
    sw_state_dpp_bcm_l3_free_cb free;
#endif /* defined(BCM_PETRA_SUPPORT)*/ 
#if defined(BCM_PETRA_SUPPORT)
    sw_state_dpp_bcm_l3_verify_cb verify;
#endif /* defined(BCM_PETRA_SUPPORT)*/ 
    sw_state_dpp_bcm_l3_used_intf_cbs_t used_intf;
    sw_state_dpp_bcm_l3_used_vrf_cbs_t used_vrf;
    sw_state_dpp_bcm_l3_used_host_cbs_t used_host;
    sw_state_dpp_bcm_l3_used_route_cbs_t used_route;
    sw_state_dpp_bcm_l3_dpp_l3_state_cbs_t dpp_l3_state;
    sw_state_dpp_bcm_l3_vrrp_protocol_set_types_cbs_t vrrp_protocol_set_types;
    sw_state_dpp_bcm_l3_vrrp_protocol_set_counts_cbs_t vrrp_protocol_set_counts;
} sw_state_dpp_bcm_l3_cbs_t;

#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

int sw_state_dpp_bcm_l3_access_cb_init(int unit);

#endif /* _SHR_SW_STATE_DPP_BCM_L3_ACCESS_H_ */
