/* $Id: ui_pure_defi_line_tevb.h,v 1.2 Broadcom SDK $
 * $Copyright: Copyright 2015 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
*/
#ifndef UI_PURE_DEFI_LINE_TEVB_INCLUDED
/* { */
#define UI_PURE_DEFI_LINE_TEVB_INCLUDED
/*
 * Note:
 * the following definitions must range between PARAM_LINE_TEVB_START_RANGE_ID (9100)
 * and PARAM_LINE_TEVB_END_RANGE_ID (9200).
 * See ui_pure_defi.h
 */
#define PARAM_TEVB_MEM_ID                       (PARAM_LINE_TEVB_START_RANGE_ID + 0)
#define PARAM_TEVB_MEM_READ_ID                  (PARAM_LINE_TEVB_START_RANGE_ID + 1)
#define PARAM_TEVB_MEM_WRITE_ID                 (PARAM_LINE_TEVB_START_RANGE_ID + 2)
#define PARAM_TEVB_MEM_DATA_ID                  (PARAM_LINE_TEVB_START_RANGE_ID + 3)
#define PARAM_TEVB_VERBOSE_ID                   (PARAM_LINE_TEVB_START_RANGE_ID + 4)
#define PARAM_TEVB_FPGA_ID                      (PARAM_LINE_TEVB_START_RANGE_ID + 5)
#define PARAM_TEVB_FPGA_DOWNLOAD_ID             (PARAM_LINE_TEVB_START_RANGE_ID + 6)

#define PARAM_TEVB_FLASH_ID                     (PARAM_LINE_TEVB_START_RANGE_ID + 7)
#define PARAM_TEVB_FLASH_BURN_ID                (PARAM_LINE_TEVB_START_RANGE_ID + 8)
#define PARAM_TEVB_FLASH_DOWNLOAD_ID            (PARAM_LINE_TEVB_START_RANGE_ID + 9)
#define PARAM_TEVB_FLASH_ERASE_ID               (PARAM_LINE_TEVB_START_RANGE_ID + 10)
#define PARAM_TEVB_FLASH_FILENAME_ID            (PARAM_LINE_TEVB_START_RANGE_ID + 11)

#define PARAM_TEVB_FLASH_DFFS_ID                (PARAM_LINE_TEVB_START_RANGE_ID + 12)
#define PARAM_TEVB_FLASH_DFFS_ADD_ATTR_ID       (PARAM_LINE_TEVB_START_RANGE_ID + 13)
#define PARAM_TEVB_FLASH_DFFS_DIR_ID            (PARAM_LINE_TEVB_START_RANGE_ID + 17)
#define PARAM_TEVB_FLASH_DFFS_PRINT_ID          (PARAM_LINE_TEVB_START_RANGE_ID + 19)
#define PARAM_TEVB_FLASH_DFFS_DIR_FORMAT_ID     (PARAM_LINE_TEVB_START_RANGE_ID + 21)
#define PARAM_TEVB_FLASH_DFFS_DEL_ID            (PARAM_LINE_TEVB_START_RANGE_ID + 22)
#define PARAM_TEVB_FLASH_DFFS_DIAGNOSTICS_ID    (PARAM_LINE_TEVB_START_RANGE_ID + 23)
#define PARAM_TEVB_FLASH_DFFS_ATTR1_ID          (PARAM_LINE_TEVB_START_RANGE_ID + 24)
#define PARAM_TEVB_FLASH_DFFS_ATTR2_ID          (PARAM_LINE_TEVB_START_RANGE_ID + 25)
#define PARAM_TEVB_FLASH_DFFS_ATTR3_ID          (PARAM_LINE_TEVB_START_RANGE_ID + 26)
#define PARAM_TEVB_FLASH_DFFS_NAME_ID           (PARAM_LINE_TEVB_START_RANGE_ID + 27)
#define PARAM_TEVB_FLASH_DFFS_PRINT_SIZE_ID     (PARAM_LINE_TEVB_START_RANGE_ID + 28)
#define PARAM_TEVB_FLASH_DFFS_COMMENT_ID        (PARAM_LINE_TEVB_START_RANGE_ID + 29)
#define PARAM_TEVB_FLASH_DFFS_VER_ID            (PARAM_LINE_TEVB_START_RANGE_ID + 30)
#define PARAM_TEVB_FLASH_DFFS_SHOW_COMMENT_ID   (PARAM_LINE_TEVB_START_RANGE_ID + 31)
#define PARAM_TEVB_FLASH_DFFS_DATE_ID           (PARAM_LINE_TEVB_START_RANGE_ID + 32)
#define PARAM_TEVB_FLASH_DFFS_ADD_COMMENT_ID    (PARAM_LINE_TEVB_START_RANGE_ID + 33)
#define PARAM_TEVB_FLASH_DFFS_DLD_ID            (PARAM_LINE_TEVB_START_RANGE_ID + 34)

#define PARAM_TEVB_COMPRESSED_ID                (PARAM_LINE_TEVB_START_RANGE_ID + 35)
#define PARAM_TEVB_FLASH_DIAGNOSTICS_ID         (PARAM_LINE_TEVB_START_RANGE_ID + 36)

/* } */
#endif
