# $Id$
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM Maverick2 driver Library
#

LOCALDIR = src/bcm/esw/maverick2

include ${SDK}/make/Make.config

lib = libmaverick2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
