#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/fabric

include ${SDK}/make/Make.config

#subdirs =

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxfabric

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

