FP_BASE=../../../..

bldlib installexe clean:
	$(MAKE) -C $(FP_BASE)/src/application/switching/spanning_tree/dot1s/encryption $@
	$(MAKE) -C $(FP_BASE)/src/application/switching/spanning_tree/dot1s $@
