#
# $Id: Makefile,v 1.4 2020/02/14 10:43:54 Exp $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/flow

include ${SDK}/make/Make.config

lib = libbcm_dnxflow

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

