/** \file dnx_data_max_ecgm.h
 * 
 * MODULE DATA MAX - 
 * Maintain max value (of all devices) per define
 * 
 * Device Data
 * SW component that maintains per device data
 * For additional details about Device Data Component goto 'dnxc_data_mgmt.h'
 *        
 *     
 * 
 * AUTO-GENERATED BY AUTOCODER!
 * DO NOT EDIT THIS FILE!
 */
/* *INDENT-OFF* */
/*
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */
#ifndef _DNX_DATA_MAX_ECGM_H_
/*{*/
#define _DNX_DATA_MAX_ECGM_H_
/*
 * INCLUDE FILES:
 * {
 */
/*
 * }
 */

/*!
* \brief This file is only used by DNX (JR2 family). Including it by
* software that is not specific to DNX is an error.
*/
#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif

/*
 * MAX DEFINES:
 * {
 */
/**
 * \brief
 * number of service pools
 */
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_SP (2)

/**
 * \brief
 * total interface profiles per core
 */
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_INTERFACE_PROFILES (8)

/**
 * \brief
 * total port profiles per core
 */
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_PORT_PROFILES (16)

/**
 * \brief
 * total packet descriptors per core
 */
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_PDS (76000)

/**
 * \brief
 * number of bits for total packet descriptors
 */
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_PDS_NOF_BITS (17)

/**
 * \brief
 * total data buffers per core
 */
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_DBS (32000)

/**
 * \brief
 * number of bits for total data buffers
 */
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_DBS_NOF_BITS (15)

/**
 * \brief
 * max value for FADT alpha
 */
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_MAX_ALPHA_VALUE (7)

/**
 * \brief
 * min value for FADT alpha
 */
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_MIN_ALPHA_VALUE (0)

/**
 * \brief
 * maximum bandwidth pec core in Mbps for ecgm calculation
 */
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_MAX_CORE_BANDWIDTH_MBPS (5000000)

/**
 * \brief
 * maximum num of ports per core for ecgm calculation
 */
#define DNX_DATA_MAX_ECGM_PORT_RESOURCES_MAX_NOF_PORTS (160)

/**
 * \brief
 * number of reasons for the dropped packets in RQP
 */
#define DNX_DATA_MAX_ECGM_INFO_NOF_DROPPED_REASONS_RQP (11)

/**
 * \brief
 * number of reasons for the dropped packets in PQP
 */
#define DNX_DATA_MAX_ECGM_INFO_NOF_DROPPED_REASONS_PQP (16)

/**
 * \brief
 * number of bits in PD COUNT
 */
#define DNX_DATA_MAX_ECGM_INFO_NOF_BITS_IN_PD_COUNT (16)

/*
 * }
 */

/*}*/
#endif /*_DNX_DATA_MAX_ECGM_H_*/
/* *INDENT-ON* */
