# $Id: Makefile,v 1.23 Broadcom SDK $
# $Copyright: (c) 2018 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC driver Library
#
include ${SDK}/make/Make.config

CFGFLAGS += -std=gnu99
export CFGFLAGS

subdirs = cmn ramon swstate dnxf_data dnxf_data/auto_generated dnxf_data/auto_generated/ramon_a0

include ${SDK}/make/Make.subdirs
