#
# $Id$
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dpp subdirectory
#

LOCALDIR = src/appl/diag/dnxf/swstate/auto_generated

include ${SDK}/make/Make.config

lib = libdiag_dnxfswstate_auto_generated

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

