# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM Tomahawk driver Library
#

LOCALDIR = src/bcm/esw/tomahawk3

include ${SDK}/make/Make.config

subdirs := $(SUBDIR_NONE)
include ${SDK}/make/Make.subdirs

lib = libtomahawk3

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
