#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for portlib subdirectory
#

LOCALDIR = src/soc/cprimod

include ${SDK}/make/Make.config

subdirs := cpms
include ${SDK}/make/Make.subdirs

lib = libsoc_cprimod

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
