/*********************************************************************
*
* (C) Copyright Broadcom Corporation 2006-2007
*
**********************************************************************
*                                                                     
* @filename   src/nls/web/qos/strlib_qos_web.c                                                      
*                                                                     
* @purpose    Strings Library                                                      
*                                                                     
* @component  Common Strings Library                                                      
*                                                                     
* @comments   none                                                    
*                                                                     
* @create     01/10/2007                                                      
*                                                                     
* @author     Rama Sasthri, Kristipati                                
*                                                                     
* @end                                                                
*                                                                     
*********************************************************************/

#include "strlib_qos_web.h"

L7_char8 *pStrErr_qos_FailedToSetNbr = "%s %d.";
L7_char8 *pStrInfo_qos_NbspNbsp = "%s:&nbsp";
L7_char8 *pStrInfo_qos_StringDecimal = "%s: %d";
L7_char8 *pStrInfo_qos_StringString = "%s: %s";
L7_char8 *pStrInfo_qos_Br_1 = "%s<br>";
L7_char8 *pStrInfo_qos_Hex = "(%4x %s %4x hex)";
L7_char8 *pStrInfo_qos_Kbps = "(%d %s %lu) Kbps";
L7_char8 *pStrInfo_qos_KbpsOrPercent = "(%d %s %lu) Kbps or (%d %s %d) Percent";
L7_char8 *pStrInfo_qos_Kbytes = "(%d %s %u) KBytes";
L7_char8 *pStrInfo_qos_To_2 = "(%d to %d)";
L7_char8 *pStrInfo_qos_To_3 = "(%2.2x to %2.2x)";
L7_char8 *pStrInfo_qos_Ipv4 = "(IPv4)";
L7_char8 *pStrInfo_qos_Ipv6 = "(IPv6)";
L7_char8 *pStrErr_qos_InvalidIpv6Acl = ": Invalid IPv6 ACL";
L7_char8 *pStrInfo_qos_BrNbspNbsp = "<br>%s:&nbsp";
L7_char8 *pStrInfo_qos_AColorConformClassSelectionIsRequiredForColorAwareMode = "A Color Conform Class selection is required for Color Aware Mode.";
L7_char8 *pStrInfo_qos_AclIdAlreadyInUse = "ACL ID already in use";
L7_char8 *pStrInfo_qos_AclIntfCfg = "ACL Interface Configuration";
L7_char8 *pStrInfo_qos_AclNameAlreadyExists = "ACL Name already exists";
L7_char8 *pStrInfo_qos_AclRuleLogging = "ACL Rule Logging";
L7_char8 *pStrInfo_qos_AclServiceTypeCfg = "ACL Service Type Configuration";
L7_char8 *pStrInfo_qos_AclMatchCond = "ACL match condition";
L7_char8 *pStrInfo_qos_AclIp = "ACL(IP)";
L7_char8 *pStrInfo_qos_AclIpv6 = "ACL(IPv6)";
L7_char8 *pStrInfo_qos_AclMac = "ACL(MAC)";
L7_char8 *pStrInfo_qos_Af11_1 = "AF-11";
L7_char8 *pStrInfo_qos_Af12_1 = "AF-12";
L7_char8 *pStrInfo_qos_Af13_1 = "AF-13";
L7_char8 *pStrInfo_qos_Af21_1 = "AF-21";
L7_char8 *pStrInfo_qos_Af22_1 = "AF-22";
L7_char8 *pStrInfo_qos_Af23_1 = "AF-23";
L7_char8 *pStrInfo_qos_Af31_1 = "AF-31";
L7_char8 *pStrInfo_qos_Af32_1 = "AF-32";
L7_char8 *pStrInfo_qos_Af33_1 = "AF-33";
L7_char8 *pStrInfo_qos_Af41_1 = "AF-41";
L7_char8 *pStrInfo_qos_Af42_1 = "AF-42";
L7_char8 *pStrInfo_qos_Af43_1 = "AF-43";
L7_char8 *pStrInfo_qos_AddMatchCriteria = "Add Match Criteria";
L7_char8 *pStrInfo_qos_AddSelectedClass = "Add Selected Class";
L7_char8 *pStrInfo_qos_Appletalk_1 = "Appletalk";
L7_char8 *pStrInfo_qos_AssignQueueId = "Assign Queue ID";
L7_char8 *pStrInfo_qos_Attr = "Attribute";
L7_char8 *pStrInfo_qos_AttrDetails = "Attribute Details";
L7_char8 *pStrInfo_qos_AvailableClassList = "Available Class List";
L7_char8 *pStrInfo_qos_Be = "BE";
L7_char8 *pStrInfo_qos_BestEffortWillBeUsed = "Best Effort will be used";
L7_char8 *pStrInfo_qos_CosVal = "COS value";
L7_char8 *pStrInfo_qos_Cs1_1 = "CS-1";
L7_char8 *pStrInfo_qos_Cs2_1 = "CS-2";
L7_char8 *pStrInfo_qos_Cs3_1 = "CS-3";
L7_char8 *pStrInfo_qos_Cs4_1 = "CS-4";
L7_char8 *pStrInfo_qos_Cs5_1 = "CS-5";
L7_char8 *pStrInfo_qos_Cs6_1 = "CS-6";
L7_char8 *pStrInfo_qos_Cs7_1 = "CS-7";
L7_char8 *pStrInfo_qos_Class = "Class";
L7_char8 *pStrInfo_qos_ClassLayer3Proto = "Class Layer 3 Protocol";
L7_char8 *pStrInfo_qos_ClassMatchCriteriaFull = "Class Match Criteria full";
L7_char8 *pStrInfo_qos_ClassMatchSelector = "Class Match Selector";
L7_char8 *pStrInfo_qos_ClassRule = "Class Rule";
L7_char8 *pStrErr_qos_ClassRuleNotCreated = "Class Rule Not Created";
L7_char8 *pStrInfo_qos_ClassRuleTbl = "Class Rule table";
L7_char8 *pStrInfo_qos_ClassRuleTblIsFull = "Class Rule table is full";
L7_char8 *pStrInfo_qos_ClassSelector = "Class Selector";
L7_char8 *pStrInfo_qos_ClassOfServiceValOutOfRange = "Class of Service value out of range.";
L7_char8 *pStrInfo_qos_ClassTbl = "Class table";
L7_char8 *pStrInfo_qos_ClassesShldHaveSameLayer3Proto = "Classes should have same Layer 3 Protocol.";
L7_char8 *pStrInfo_qos_CosIntfCfg = "CoS Interface Configuration";
L7_char8 *pStrInfo_qos_CosIntfQueueCfg = "CoS Interface Queue Configuration";
L7_char8 *pStrInfo_qos_CosIntfQueueDropPrecedenceCfg = "CoS Interface Queue Drop Precedence Configuration";
L7_char8 *pStrInfo_qos_CosIntfQueueDropPrecedenceStatus = "CoS Interface Queue Drop Precedence Status";
L7_char8 *pStrInfo_qos_CosIntfQueueStatus = "CoS Interface Queue Status";
L7_char8 *pStrInfo_qos_ColorAwareCos = "Color Aware COS";
L7_char8 *pStrInfo_qos_ColorAwareIpDscp = "Color Aware IP DSCP";
L7_char8 *pStrInfo_qos_ColorAwareIpPrec = "Color Aware IP Prec";
L7_char8 *pStrInfo_qos_ColorAwareSecCos = "Color Aware Sec COS";
L7_char8 *pStrInfo_qos_ColorAwareModeRequiresExistenceOfOneOrMoreColorClassesThatAreValidForUseWithPolicyInstPressHelpForMoreDetails = "Color Aware mode requires the existence of one or more color classes that are valid for use with this policy instance.  Press \'Help\' for more details.";
L7_char8 *pStrInfo_qos_ColorBlind = "Color Blind";
L7_char8 *pStrInfo_qos_ColorConformMode = "Color Conform Mode";
L7_char8 *pStrInfo_qos_ColorExceedMode = "Color Exceed Mode";
L7_char8 *pStrInfo_qos_CommittedBurstSizeKb = "Committed Burst Size (KB)";
L7_char8 *pStrInfo_qos_CommittedRateKbps = "Committed Rate (Kbps)";
L7_char8 *pStrInfo_qos_CfgureSelectedAttr = "Configure Selected Attribute";
L7_char8 *pStrInfo_qos_Confirm = "Confirm";
L7_char8 *pStrInfo_qos_ConformActionSelector = "Conform Action Selector";
L7_char8 *pStrInfo_qos_ConformCosVal_1 = "Conform CoS Value";
L7_char8 *pStrInfo_qos_ConformCos2Val = "Conform CoS2 Value";
L7_char8 *pStrInfo_qos_ConformDscpKeyword = "Conform DSCP Keyword";
L7_char8 *pStrInfo_qos_CounterModeSelector = "Counter Mode Selector";
L7_char8 *pStrInfo_qos_CreateNewExtendedIpAcl = "Create New Extended IP ACL";
L7_char8 *pStrInfo_qos_CreateNewExtendedMacAcl = "Create New Extended MAC ACL";
L7_char8 *pStrInfo_qos_CreateNewIpv6Acl = "Create New IPv6 ACL";
L7_char8 *pStrInfo_qos_CreateNewRule = "Create New Rule";
L7_char8 *pStrInfo_qos_CreateNewStandardIpAcl = "Create New Standard IP ACL";
L7_char8 *pStrInfo_qos_CreateRule = "Create Rule";
L7_char8 *pStrInfo_qos_Current8021pPriMapping = "Current 802.1p Priority Mapping";
L7_char8 *pStrInfo_qos_CurrentSizeMaxSize = "Current Size / Max Size";
L7_char8 *pStrInfo_qos_DscpKeyword = "DSCP Keyword";
L7_char8 *pStrInfo_qos_DscpVal = "DSCP Value";
L7_char8 *pStrInfo_qos_DstIpAndDstMask = "Destination IP and Destination Mask";
L7_char8 *pStrInfo_qos_DstIpv6Prefix = "Destination IPv6 Prefix";
L7_char8 *pStrInfo_qos_DstL4PortNum = "Destination L4 Port Number";
L7_char8 *pStrInfo_qos_DstL4PortRange = "Destination L4 Port Range";
L7_char8 *pStrInfo_qos_DstMacAndDstMacMask = "Destination MAC and Destination MAC Mask";
L7_char8 *pStrInfo_qos_DstMacAndDstMacMaskDstMacMaskIsAnInvalidMacAddr = "Destination MAC and Destination MAC Mask. Destination MAC Mask is an invalid MAC address";
L7_char8 *pStrInfo_qos_DstMacAndDstMacMaskDstMacIsAnInvalidMacAddr = "Destination MAC and Destination MAC Mask. Destination MAC is an invalid MAC address";
L7_char8 *pStrInfo_qos_DstPortRange = "Destination Port Range.";
L7_char8 *pStrInfo_qos_DstPort_1 = "Destination Port.";
L7_char8 *pStrInfo_qos_DstPrefixPrefixLen = "Destination Prefix/Prefix Length.";
L7_char8 *pStrInfo_qos_DiffservClassCfg = "DiffServ Class Configuration";
L7_char8 *pStrInfo_qos_DiffservClassSummary = "DiffServ Class Summary";
L7_char8 *pStrInfo_qos_DiffservCfg = "DiffServ Configuration";
L7_char8 *pStrInfo_qos_DiffservPolicyAttrSummary = "DiffServ Policy Attribute Summary";
L7_char8 *pStrInfo_qos_DiffservPolicyClassDefinition = "DiffServ Policy Class Definition";
L7_char8 *pStrInfo_qos_DiffservPolicyCfg = "DiffServ Policy Configuration";
L7_char8 *pStrInfo_qos_DiffservPolicySummary = "DiffServ Policy Summary";
L7_char8 *pStrInfo_qos_DiffservServiceCfg = "DiffServ Service Configuration";
L7_char8 *pStrInfo_qos_DiffservServiceDetailedStats = "DiffServ Service Detailed Statistics";
L7_char8 *pStrInfo_qos_DiffservServiceStats = "DiffServ Service Statistics";
L7_char8 *pStrInfo_qos_DiffservServiceSummary = "DiffServ Service Summary";
L7_char8 *pStrInfo_qos_DiffservClassNameAlreadyExists = "Diffserv Class Name already exists.";
L7_char8 *pStrInfo_qos_DiffservDstPrefixCfg = "Diffserv Destination Prefix Configuration";
L7_char8 *pStrInfo_qos_DiffservSrcPrefixCfg = "Diffserv Source Prefix Configuration";
L7_char8 *pStrInfo_qos_DiscardedOctets = "Discarded Octets";
L7_char8 *pStrInfo_qos_DiscardedPkts = "Discarded Packets";
L7_char8 *pStrInfo_qos_DropPolicyAttrs = "Drop Policy Attributes";
L7_char8 *pStrInfo_qos_HtmlFileDrop = "Drop.html";
L7_char8 *pStrInfo_qos_Ef_1 = "EF";
L7_char8 *pStrInfo_qos_EitherSecondaryVlanRangeOrSecondaryVlanCanBeCfguredSecondaryVlanRangeNotSet = "Either Secondary VLAN Range or Secondary VLAN can be configured. Secondary VLAN Range not set.";
L7_char8 *pStrInfo_qos_EitherVlanRangeOrVlanCanBeCfguredVlanRangeNotSet = "Either VLAN Range or VLAN can be configured. VLAN Range not set.";
L7_char8 *pStrInfo_qos_EndPortNum = "End Port Number";
L7_char8 *pStrInfo_qos_EndPortMustBeGreaterThanOrEqualToStartPort = "End port must be greater than or equal to Start port.";
L7_char8 *pStrInfo_qos_EthertypeKey = "Ethertype Key";
L7_char8 *pStrInfo_qos_EthertypeKeyAndEthertypeUsrVal = "Ethertype Key and Ethertype User Value";
L7_char8 *pStrInfo_qos_EthertypeUsrVal = "Ethertype User Value";
L7_char8 *pStrInfo_qos_EthertypeUsrValEthertypeUsrValIsAnInvalidHex = "Ethertype User Value. Ethertype User Value is an invalid hex";
L7_char8 *pStrInfo_qos_EthertypeValIsInvalidHexadecimalNum = "Ethertype Value is invalid hexadecimal number.";
L7_char8 *pStrInfo_qos_EthertypeValOutOfRange = "Ethertype Value out of range.";
L7_char8 *pStrInfo_qos_ExceedActionSelector = "Exceed Action Selector";
L7_char8 *pStrInfo_qos_ExceedCosVal_1 = "Exceed CoS Value";
L7_char8 *pStrInfo_qos_ExceedCos2Val = "Exceed CoS2 Value";
L7_char8 *pStrInfo_qos_ExceedDscpKeyword = "Exceed DSCP Keyword";
L7_char8 *pStrInfo_qos_ExcessBurstSizeKb = "Excess Burst Size (KB)";
L7_char8 *pStrInfo_qos_ExcessBurstSizeMustBeEqualToOrGreaterThanCommittedBurstSize = "Excess Burst Size must be equal to or greater than Committed Burst Size.";
L7_char8 *pStrInfo_qos_ExpediteKbps = "Expedite (Kbps)";
L7_char8 *pStrErr_qos_FailedToAssignAcl = "Failed to assign ACL.";
L7_char8 *pStrErr_qos_FailedToAssignIpAcl = "Failed to assign IP ACL.";
L7_char8 *pStrErr_qos_FailedToAssignIpv6Acl = "Failed to assign IPv6 ACL.";
L7_char8 *pStrErr_qos_FailedToAssignMacAcl = "Failed to assign MAC ACL.";
L7_char8 *pStrErr_qos_FailedToDelClassFromPolicy = "Failed to delete class from policy.";
L7_char8 *pStrErr_qos_FailedToDelPolicy = "Failed to delete policy.";
L7_char8 *pStrErr_qos_FailedToFindPolicyInstIdxForClass = "Failed to find the policy instance index for this class";
L7_char8 *pStrErr_qos_FailedToRemoveClassRef = "Failed to remove class reference.";
L7_char8 *pStrErr_qos_FailedToResetNbr = "Failed to reset %s %d.";
L7_char8 *pStrErr_qos_FailedToRestoreOriginalRuleCfg = "Failed to restore original rule configuration";
L7_char8 *pStrInfo_qos_FlowLabelCfg = "Flow Label Configuration";
L7_char8 *pStrInfo_qos_FlowLabelVal = "Flow Label value.";
L7_char8 *pStrInfo_qos_IbmSna = "IBM SNA";
L7_char8 *pStrInfo_qos_IpAcl = "IP ACL";
L7_char8 *pStrInfo_qos_IpAclCfg = "IP ACL Configuration";
L7_char8 *pStrInfo_qos_IpAclId = "IP ACL ID";
L7_char8 *pStrInfo_qos_IpAclRuleCfg = "IP ACL Rule Configuration";
L7_char8 *pStrInfo_qos_IpAclSummary = "IP ACL Summary";
L7_char8 *pStrInfo_qos_IpDscp_1 = "IP DSCP : %d";
L7_char8 *pStrInfo_qos_IpDscpMappingCfg = "IP DSCP Mapping Configuration";
L7_char8 *pStrInfo_qos_IpDscpValOutOfRange = "IP DSCP value out of range.";
L7_char8 *pStrInfo_qos_IpDscp_2 = "IP DSCP: %d";
L7_char8 *pStrInfo_qos_IpMask = "IP Mask";
L7_char8 *pStrInfo_qos_IpPrecedence_1 = "IP Precedence : %d";
L7_char8 *pStrInfo_qos_IpPrecedenceMappingCfg = "IP Precedence Mapping Configuration";
L7_char8 *pStrInfo_qos_IpPrecedenceVal = "IP Precedence Value";
L7_char8 *pStrInfo_qos_IpPrecedenceValOutOfRange = "IP Precedence value out of range.";
L7_char8 *pStrInfo_qos_IpPrecedence_2 = "IP Precedence: %d";
L7_char8 *pStrInfo_qos_IpTosBitsValOutOfRange = "IP TOS Bits value out of range.";
L7_char8 *pStrInfo_qos_IpTosMaskValOutOfRange = "IP TOS Mask value out of range.";
L7_char8 *pStrInfo_qos_Ipv6Acl = "IPv6 ACL";
L7_char8 *pStrInfo_qos_Ipv6AclCfg = "IPv6 ACL Configuration";
L7_char8 *pStrInfo_qos_Ipv6AclNameAlreadyExists = "IP ACL Name already exists.";
L7_char8 *pStrInfo_qos_Ipv6AclRuleCfg = "IPv6 ACL Rule Configuration";
L7_char8 *pStrInfo_qos_Ipv6AclRuleLogging = "IPv6 ACL Rule Logging";
L7_char8 *pStrInfo_qos_Ipv6AclSummary = "IPv6 ACL Summary";
L7_char8 *pStrInfo_qos_Ipv6AclDoesnTExists = "IPv6 ACL doesn't exists.";
L7_char8 *pStrInfo_qos_Ipv6QosIsNotSupported = "IPv6 QoS is not supported.";
L7_char8 *pStrInfo_qos_Ipv6SrcEndPortShldBeGreaterThanIpv6SrcStartPort = "IPv6 Source End Port should be greater than IPv6 Source Start Port.";
L7_char8 *pStrInfo_qos_Ipv6SrcPortRange = "IPv6 Source Port Range.";
L7_char8 *pStrInfo_qos_Ipv6SrcPortVal = "IPv6 Source Port value.";
L7_char8 *pStrInfo_qos_Ipv6MatchCond = "IPv6 match condition.";
L7_char8 *pStrInfo_qos_IntfShapingRateFeatNotSupported = "Interface Shaping Rate: Feature not Supported";
L7_char8 *pStrInfo_qos_IntfOrVlanBasedAclSSummary = "Interface or VLAN based ACL(s) Summary";
L7_char8 *pStrErr_qos_ClassAclType = "Invalid Class ACL Type";
L7_char8 *pStrErr_qos_ClassName_3 = "Invalid Class Name";
L7_char8 *pStrErr_qos_ClassType_1 = "Invalid Class Type";
L7_char8 *pStrErr_qos_ClassType_2 = "Invalid Class type";
L7_char8 *pStrErr_qos_FlowLabelRange = "Invalid Flow Label range.";
L7_char8 *pStrErr_qos_IpAcl_1 = "Invalid IP ACL";
L7_char8 *pStrErr_qos_IpAddr_2 = "Invalid IP Address";
L7_char8 *pStrErr_qos_Ipv6AclNameString = "Invalid IPv6 ACL name string.";
L7_char8 *pStrErr_qos_Ipv6SrcPrefixPrefixlength = "Invalid IPv6 Source Prefix / PrefixLength.";
L7_char8 *pStrErr_qos_Layer4PortRange = "Invalid Layer 4 Port Range";
L7_char8 *pStrErr_qos_MacAcl = "Invalid MAC ACL";
L7_char8 *pStrErr_qos_MacAddrMask = "Invalid MAC Address Mask";
L7_char8 *pStrErr_qos_PolicyAttrSelector = "Invalid Policy attribute selector";
L7_char8 *pStrErr_qos_PrefixPrefixlength_1 = "Invalid Prefix/PrefixLength.";
L7_char8 *pStrErr_qos_ProtoNum = "Invalid Protocol Number.";
L7_char8 *pStrErr_qos_ServiceTypeSelected = "Invalid Service Type selected";
L7_char8 *pStrErr_qos_SubnetMask_1 = "Invalid Subnet Mask";
L7_char8 *pStrErr_qos_FmtOfDstPortNum = "Invalid format of Destination Port Number.";
L7_char8 *pStrErr_qos_FmtOfDstPort = "Invalid format of Destination Port.";
L7_char8 *pStrErr_qos_FmtOfFlowLabelRange = "Invalid format of Flow Label range.";
L7_char8 *pStrErr_qos_FmtOfIpv6SrcPort = "Invalid format of IPv6 Source Port.";
L7_char8 *pStrErr_qos_FmtOfIpv6SrcStartOrEndPort = "Invalid format of IPv6 Source Start or End port.";
L7_char8 *pStrErr_qos_FmtOfProtoNum = "Invalid format of Protocol Number.";
L7_char8 *pStrErr_qos_RangeOfDstPort = "Invalid range of Destination Port.";
L7_char8 *pStrErr_qos_RangeOfDstStartPortOrEndPort = "Invalid range of Destination Start Port or End Port.";
L7_char8 *pStrErr_qos_RangeOfIpv6SrcPortRange = "Invalid range of IPv6 Source Port Range.";
L7_char8 *pStrErr_qos_RangeOfIpv6SrcPort = "Invalid range of IPv6 Source Port.";
L7_char8 *pStrErr_qos_RangeOfProtoNum = "Invalid range of Protocol Number.";
L7_char8 *pStrInfo_qos_Ipv6AccessListDoesntExist = "Ipv6 Access-list does not exist.";
L7_char8 *pStrInfo_qos_Kbps_1 = "Kbps";
L7_char8 *pStrInfo_qos_Layer3Proto = "Layer 3 Protocol.";
L7_char8 *pStrInfo_qos_MacAcl_1 = "MAC ACL";
L7_char8 *pStrInfo_qos_MacAclCfg = "MAC ACL Configuration";
L7_char8 *pStrInfo_qos_MacAclRuleCfg = "MAC ACL Rule Configuration";
L7_char8 *pStrInfo_qos_MacAclSummary = "MAC ACL Summary";
L7_char8 *pStrInfo_qos_MacAclCantBeRenamed = "MAC ACL could not be renamed";
L7_char8 *pStrInfo_qos_MacMask_1 = "MAC Mask";
L7_char8 *pStrInfo_qos_MibTbl = "MIB Table";
L7_char8 *pStrInfo_qos_MplsMcast = "MPLS multicast";
L7_char8 *pStrInfo_qos_MplsUcast = "MPLS unicast";
L7_char8 *pStrInfo_qos_MakeSureClassIsNotUsedByAnyPolicy = "Make sure Class is not being used by any Policy.";
L7_char8 *pStrInfo_qos_MaxBandwidth_1 = "Maximum Bandwidth";
L7_char8 *pStrInfo_qos_MaxBandwidthMustBeGreaterThanOrEqualToMinBandwidth = "Maximum Bandwidth must be greater than or equal to Minimum Bandwidth";
L7_char8 *pStrInfo_qos_MaxBandwidthFeatNotSupported = "Maximum Bandwidth: Feature not Supported";
L7_char8 *pStrInfo_qos_MaxThreshMustBeEqualToOrGreaterThanMinThresh = "Maximum Threshold must be equal to or greater than Minimum Threshold.";
L7_char8 *pStrInfo_qos_MaxNumOfMacAclsAlreadyCreated = "Maximum number of MAC ACLs already created";
L7_char8 *pStrInfo_qos_MbrClassList = "Member Class List";
L7_char8 *pStrInfo_qos_MbrClasses = "Member Classes";
L7_char8 *pStrInfo_qos_MinBandwidth_1 = "Minimum Bandwidth";
L7_char8 *pStrInfo_qos_MinBandwidthFeatNotSupported = "Minimum Bandwidth: Feature not Supported";
L7_char8 *pStrInfo_qos_MirrorIntfAndRedirectIntfCantBeSpecifiedForSameAclRule = "Mirror Interface and Redirect Interface cannot be specified for the same ACL rule.";
L7_char8 *pStrInfo_qos_MirrorIntfAndRedirectIntfCantBeSpecifiedForSamePolicyClassDefinition = "Mirror Interface and Redirect Interface cannot be specified for the same policy class definition.";
L7_char8 *pStrInfo_qos_NameMustBeAlnum = "Name must be alpha-numeric";
L7_char8 *pStrInfo_qos_NameMustBeAlnum_1 = "Name must be alpha-numeric.";
L7_char8 *pStrInfo_qos_Netbios = "NetBIOS";
L7_char8 *pStrInfo_qos_NoAclsAreCfgured = "No ACLs Are Configured";
L7_char8 *pStrInfo_qos_NoClassMatchCriteriaSelected = "No Class Match Criteria selected";
L7_char8 *pStrInfo_qos_NoClassesToAdd = "No Classes to Add";
L7_char8 *pStrInfo_qos_NoIpAclsAreCurrentlyCfgured = "No IP ACLs are currently configured.";
L7_char8 *pStrInfo_qos_NoIpv6AclsAreCurrentlyCfgured = "No IPv6 ACLs are currently configured.";
L7_char8 *pStrInfo_qos_NoMacAclsAreCurrentlyCfgured = "No MAC ACLs are currently configured.";
L7_char8 *pStrInfo_qos_NoMbrClasses = "No Member Classes";
L7_char8 *pStrInfo_qos_NoRulesExist = "No Rules Exist";
L7_char8 *pStrInfo_qos_NoMoreClassesCanBeAdded = "No more classes can be added.";
L7_char8 *pStrInfo_qos_NoUsableRefClassesExistRefClassesMustBeOfSameClassTypeAndCantBeCurrentlySelectedClass = "No usable Reference Classes exist.\nReference classes must be of the same \nClass Type and cannot be the currently selected class.";
L7_char8 *pStrInfo_qos_NonIpTrafficClass = "Non-IP Traffic Class";
L7_char8 *pStrInfo_qos_Novell = "Novell";
L7_char8 *pStrInfo_qos_Octets = "Octets";
L7_char8 *pStrInfo_qos_OfferedOctets = "Offered Octets";
L7_char8 *pStrInfo_qos_OfferedPkts = "Offered Packets";
L7_char8 *pStrInfo_qos_OriginalRuleCfgRestored = "Original rule configuration restored";
L7_char8 *pStrInfo_qos_Pppoe = "PPPoE";
L7_char8 *pStrInfo_qos_PeakBurstSizeKb = "Peak Burst Size (KB)";
L7_char8 *pStrInfo_qos_PeakBurstSizeMustBeEqualToOrGreaterThanCommittedBurstSize = "Peak Burst Size must be equal to or greater than Committed Burst Size.";
L7_char8 *pStrInfo_qos_PeakRateKbps = "Peak Rate (Kbps)";
L7_char8 *pStrInfo_qos_Percent = "Percent";
L7_char8 *pStrInfo_qos_Permit = "Permit";
L7_char8 *pStrInfo_qos_PolicingAttrs = "Policing Attributes";
L7_char8 *pStrInfo_qos_PolicingCfg = "Policing Configuration";
L7_char8 *pStrInfo_qos_PolicyAttrSelector_1 = "Policy Attribute Selector";
L7_char8 *pStrInfo_qos_PolicyAttrsTbl = "Policy Attributes table";
L7_char8 *pStrInfo_qos_PolicyIn = "Policy In";
L7_char8 *pStrInfo_qos_PolicyInstTbl = "Policy Instance table";
L7_char8 *pStrInfo_qos_PolicyOut = "Policy Out";
L7_char8 *pStrInfo_qos_PolicySelector = "Policy Selector";
L7_char8 *pStrInfo_qos_PolicyTbl = "Policy table";
L7_char8 *pStrInfo_qos_PortKeyword = "Port Keyword";
L7_char8 *pStrInfo_qos_PortNum_1 = "Port Number";
L7_char8 *pStrInfo_qos_PrecedenceVal = "Precedence Value";
L7_char8 *pStrInfo_qos_ProtoKeyword = "Protocol Keyword";
L7_char8 *pStrInfo_qos_ProtoNum_1 = "Protocol Number";
L7_char8 *pStrInfo_qos_ProtoNum_2 = "Protocol Number.";
L7_char8 *pStrInfo_qos_QueueIdVal = "Queue Id Value";
L7_char8 *pStrInfo_qos_QueueMgmtTypeFeatNotSupported = "Queue Management Type: Feature not Supported";
L7_char8 *pStrInfo_qos_QueueParams = "Queue Parameters";
L7_char8 *pStrInfo_qos_RandomDroppedOctets = "Random Dropped Octets";
L7_char8 *pStrInfo_qos_RandomDroppedPkts = "Random Dropped Packets";
L7_char8 *pStrInfo_qos_RefClassRuleNotCreated = "Reference class rule not created.";
L7_char8 *pStrInfo_qos_RemoveClassRef = "Remove Class Reference";
L7_char8 *pStrInfo_qos_RemoveSelectedClass = "Remove Selected Class";
L7_char8 *pStrInfo_qos_Rename = "Rename";
L7_char8 *pStrInfo_qos_RestoreDefls = "Restore Defaults";
L7_char8 *pStrInfo_qos_ReverseArp = "Reverse ARP";
L7_char8 *pStrInfo_qos_Rule = "Rule";
L7_char8 *pStrInfo_qos_RuleId = "Rule ID";
L7_char8 *pStrInfo_qos_RuleLoggingNotSupportedForCurrentRuleAction = "Rule Logging not supported for the current rule Action.";
L7_char8 *pStrInfo_qos_RuleNumDoesntExist = "Rule number does not exist.";
L7_char8 *pStrInfo_qos_SecondaryCosValOutOfRange = "Secondary COS Value out of range.";
L7_char8 *pStrInfo_qos_SecondaryCosVal = "Secondary COS value";
L7_char8 *pStrInfo_qos_SecondaryVlanId = "Secondary VLAN Identifier";
L7_char8 *pStrInfo_qos_SecondaryVlanIdEnd = "Secondary VLAN Identifier End";
L7_char8 *pStrInfo_qos_SecondaryVlanIdEndValOutOfRange = "Secondary VLAN Identifier End value out of range.";
L7_char8 *pStrInfo_qos_SecondaryVlanIdEndValShldBeMoreThanSecondaryVlanIdStartVal = "Secondary VLAN Identifier End value should be more than Secondary VLAN Identifier Start value.";
L7_char8 *pStrInfo_qos_SecondaryVlanIdStart = "Secondary VLAN Identifier Start";
L7_char8 *pStrInfo_qos_SecondaryVlanIdStartValOutOfRange = "Secondary VLAN Identifier Start value out of range.";
L7_char8 *pStrInfo_qos_SecondaryVlanIdValOutOfRange = "Secondary VLAN Identifier value out of range.";
L7_char8 *pStrInfo_qos_SecondaryVlanRangeFrom = "Secondary VLAN Range : From";
L7_char8 *pStrInfo_qos_SecondaryVlanRangeFromShldBeLessThanSecondaryVlanRangeTo = "Secondary VLAN Range : From should be less than Secondary VLAN Range : To";
L7_char8 *pStrInfo_qos_SecondaryVlanRangeTo = "Secondary VLAN Range : To";
L7_char8 *pStrInfo_qos_ServiceType = "Service Type";
L7_char8 *pStrInfo_qos_ServiceTbl = "Service table";
L7_char8 *pStrInfo_qos_ShapeAverageKbps = "Shape Average (Kbps)";
L7_char8 *pStrInfo_qos_ShapePeak = "Shape Peak";
L7_char8 *pStrInfo_qos_ShapePeakKbps = "Shape Peak (Kbps)";
L7_char8 *pStrInfo_qos_SrcIpAndSrcMask = "Source IP and Source Mask";
L7_char8 *pStrInfo_qos_SrcIpv6Prefix = "Source IPv6 Prefix";
L7_char8 *pStrInfo_qos_SrcL4PortNum = "Source L4 Port Number";
L7_char8 *pStrInfo_qos_SrcL4PortRange = "Source L4 Port Range";
L7_char8 *pStrInfo_qos_SrcMacAndSrcMacMask = "Source MAC and Source MAC Mask";
L7_char8 *pStrInfo_qos_SrcMacAndSrcMacMaskSrcMacMaskIsAnInvalidMacAddr = "Source MAC and Source MAC Mask. Source MAC Mask is an invalid MAC address";
L7_char8 *pStrInfo_qos_SrcMacAndSrcMacMaskSrcMacIsAnInvalidMacAddr = "Source MAC and Source MAC Mask. Source MAC is an invalid MAC address";
L7_char8 *pStrInfo_qos_SrcPrefixPrefixLen = "Source Prefix/Prefix Length.";
L7_char8 *pStrInfo_qos_StartPortNum = "Start Port Number";
L7_char8 *pStrInfo_qos_SumOfIndividualMinBandwidthValsForAllQueuesInSelectedIntfMinBandwidthAllocatedCantExceedDefinedMax = "Sum of individual Minimum Bandwidth values for all queues in the selected interface(Minimum Bandwidth Allocated) cannot exceed defined maximum";
L7_char8 *pStrInfo_qos_TosBitsOnly = "TOS Bits : %2.2x";
L7_char8 *pStrInfo_qos_TosBitsTosMask = "TOS Bits : %2.2x  TOS Mask : %2.2x";
L7_char8 *pStrInfo_qos_Tbl_1 = "Table";
L7_char8 *pStrInfo_qos_TblIsFullNoMoreIdxesAvailable = "Table is full, no more indexes available";
L7_char8 *pStrInfo_qos_TailDropParams = "Tail Drop Parameters";
L7_char8 *pStrInfo_qos_TailDroppedOctets = "Tail Dropped Octets";
L7_char8 *pStrInfo_qos_TailDroppedPkts = "Tail Dropped Packets";
L7_char8 *pStrInfo_qos_ColorConformAndExceedClassesMustNotDefineAnEquivalentModeAndVal = "The Color Conform and Exceed Classes must not define an equivalent mode and value.";
L7_char8 *pStrInfo_qos_AclAlreadyExists_1 = "This ACL already exists";
L7_char8 *pStrInfo_qos_DiffservPolicyAlreadyExists = "This DiffServ Policy already exists.";
L7_char8 *pStrInfo_qos_DiffservClassIsAlreadyAssociatedWithPolicy = "This Diffserv Class is already associated with this policy.";
L7_char8 *pStrInfo_qos_DiffservClassIsNotAssociatedWithPolicy = "This Diffserv Class is not associated with this policy.";
L7_char8 *pStrInfo_qos_TrafficClassForDscpVal = "Traffic Class for DSCP Value";
L7_char8 *pStrInfo_qos_TrafficClassForPrecedence = "Traffic Class for Precedence";
L7_char8 *pStrInfo_qos_TrustModeCfg = "Trust Mode Configuration";
L7_char8 *pStrInfo_qos_UnableToDelAclRule = "Unable to delete ACL Rule.";
L7_char8 *pStrInfo_qos_UnableToDelIpv6AccessList = "Unable to delete IPv6 Access List.";
L7_char8 *pStrInfo_qos_UnableToGetClassLayer3Proto = "Unable to get Class Layer3 Protocol.";
L7_char8 *pStrInfo_qos_UntrustedTrafficClass = "Untrusted Traffic Class";
L7_char8 *pStrInfo_qos_UsrVal = "User Value";
L7_char8 *pStrInfo_qos_VlanBasedAclCfg = "VLAN Based ACL Configuration";
L7_char8 *pStrInfo_qos_VlanIdEnd = "VLAN Identifier End";
L7_char8 *pStrInfo_qos_VlanIdEndValOutOfRange = "VLAN Identifier End value out of range.";
L7_char8 *pStrInfo_qos_VlanIdEndValShldBeMoreThanVlanIdStartVal = "VLAN Identifier End value should be more than VLAN Identifier Start value.";
L7_char8 *pStrInfo_qos_VlanIdStart = "VLAN Identifier Start";
L7_char8 *pStrInfo_qos_VlanIdStartValOutOfRange = "VLAN Identifier Start value out of range.";
L7_char8 *pStrInfo_qos_VlanIdValOutOfRange = "VLAN Identifier value out of range.";
L7_char8 *pStrInfo_qos_VlanRangeFrom = "VLAN Range : From";
L7_char8 *pStrInfo_qos_VlanRangeFromShldBeLessThanVlanRangeTo = "VLAN Range : From should be less than VLAN Range : To";
L7_char8 *pStrInfo_qos_VlanRangeTo = "VLAN Range : To";
L7_char8 *pStrErr_qos_FieldInvalidInput_2 = "Value (%d) is invalid for %s. %s (%d).";
L7_char8 *pStrErr_qos_FieldInvalidInput_3 = "Value (%d) is invalid for %s. Valid range is %d to %d in increments of %d.";
L7_char8 *pStrErr_qos_FieldOutOfRangeHex = "Value (%x) is out of range for %s. The valid range is %x to %x.";
L7_char8 *pStrInfo_qos_ValIsOutOfRangeForSeqNumValidRangeIsTo = "Value is out of range for Sequence Number. The valid range is %u to %u.";
L7_char8 *pStrInfo_qos_ValOfEndPortShldAlwaysBeGreaterThanStartPort = "Value of end port should always be greater than Start Port.";
L7_char8 *pStrInfo_qos_ViolateAction = "Violate Action";
L7_char8 *pStrInfo_qos_ViolateCosVal = "Violate CoS Value";
L7_char8 *pStrInfo_qos_ViolateCos2Val = "Violate CoS2 Value";
L7_char8 *pStrInfo_qos_ViolateDscpKeyword = "Violate DSCP Keyword";
L7_char8 *pStrInfo_qos_ViolateDscpVal = "Violate DSCP Value";
L7_char8 *pStrInfo_qos_ViolateIpPrecedenceVal = "Violate IP Precedence Value";
L7_char8 *pStrInfo_qos_WredDecayExponentFeatNotSupported = "WRED Decay Exponent: Feature not Supported";
L7_char8 *pStrInfo_qos_WredDropProbabilityScale = "WRED Drop Probability Scale";
L7_char8 *pStrInfo_qos_WredMaxThresh = "WRED Maximum Threshold";
L7_char8 *pStrInfo_qos_WredMaxThreshMustBeGreaterThanOrEqualToWredMinThreshOrSetTo0 = "WRED Maximum Threshold must be greater than or equal to WRED Minimum Threshold, or set to 0";
L7_char8 *pStrInfo_qos_WredMinThresh = "WRED Minimum Threshold";
L7_char8 *pStrInfo_qos_WredParams = "WRED Parameters";
L7_char8 *pStrInfo_qos_HtmlFileAclCfg = "acl_config.html";
L7_char8 *pStrInfo_qos_HtmlFileAclIntfVlanSummary = "acl_intf_vlan_summary.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfg = "acl_rule_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgAction = "acl_rule_cfg_action.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgAssignQId = "acl_rule_cfg_assign_q_id.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgDstip = "acl_rule_cfg_dstip.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgDstl4port = "acl_rule_cfg_dstl4port.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgDstl4portrange = "acl_rule_cfg_dstl4portrange.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgEvery = "acl_rule_cfg_every.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgLog = "acl_rule_cfg_log.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgMirrorIntfc = "acl_rule_cfg_mirror_intfc.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgProto = "acl_rule_cfg_protocol.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgRedirectIntfc = "acl_rule_cfg_redirect_intfc.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgSrcip = "acl_rule_cfg_srcip.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgSrcl4port = "acl_rule_cfg_srcl4port.html";
L7_char8 *pStrInfo_qos_HtmlFileAclRuleCfgSrcl4portrange = "acl_rule_cfg_srcl4portrange.html";
L7_char8 *pStrInfo_qos_HtmlFileAclServtypeCfg = "acl_servtype_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileAclSummary = "acl_summary.html";
L7_char8 *pStrInfo_qos_AddDiffservClassCreate = "add the DiffServ class._create";
L7_char8 *pStrInfo_qos_AddDiffservClassIdx = "add the DiffServ class._index";
L7_char8 *pStrInfo_qos_AddDiffservClassName = "add the DiffServ class._name";
L7_char8 *pStrInfo_qos_HtmlFileAssignQueue = "assign_queue.html";
L7_char8 *pStrInfo_qos_AttachPolicyIdx = "attach the policy index";
L7_char8 *pStrInfo_qos_HtmlFileBandwidth = "bandwidth.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfg = "class_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleCos = "class_cfg_rule_cos.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleCos2 = "class_cfg_rule_cos2.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleDstip = "class_cfg_rule_dstip.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleDstipPrefix = "class_cfg_rule_dstip_prefix.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleDstl4port = "class_cfg_rule_dstl4port.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleDstmac = "class_cfg_rule_dstmac.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleEthertyp = "class_cfg_rule_ethertyp.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleFlowLabel = "class_cfg_rule_flow_label.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleIpdscp = "class_cfg_rule_ipdscp.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleIpprecedence = "class_cfg_rule_ipprecedence.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleIptos = "class_cfg_rule_iptos.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleProto = "class_cfg_rule_protocol.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleRefclass = "class_cfg_rule_refclass.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleSrcip = "class_cfg_rule_srcip.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleSrcipPrefix = "class_cfg_rule_srcip_prefix.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleSrcl4port = "class_cfg_rule_srcl4port.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleSrcmac = "class_cfg_rule_srcmac.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleVlan = "class_cfg_rule_vlan.html";
L7_char8 *pStrInfo_qos_HtmlFileClassCfgRuleVlan2 = "class_cfg_rule_vlan2.html";
L7_char8 *pStrInfo_qos_HtmlFileClassSummary = "class_summary.html";
L7_char8 *pStrInfo_qos_HtmlFileCosIntfCfg = "cos_intf_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileCosIntfQueueCfg = "cos_intf_queue_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileCosIntfQueueCfgRo = "cos_intf_queue_cfg_ro.html";
L7_char8 *pStrInfo_qos_HtmlFileCosIntfQueueDropprecCfg = "cos_intf_queue_dropprec_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileCosIntfQueueDropprecCfgRo = "cos_intf_queue_dropprec_cfg_ro.html";
L7_char8 *pStrInfo_qos_HtmlFileCosIntfQueueDropprecStatus = "cos_intf_queue_dropprec_status.html";
L7_char8 *pStrInfo_qos_HtmlFileCosIntfQueueStatus = "cos_intf_queue_status.html";
L7_char8 *pStrInfo_qos_HtmlFileCosIntfTrustedMode = "cos_intf_trusted_mode.html";
L7_char8 *pStrInfo_qos_HtmlFileCosIpDscpTblCfg = "cos_ip_dscp_table_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileCosIpPrecTblCfg = "cos_ip_prec_table_cfg.html";
L7_char8 *pStrInfo_qos_CreatePolicyAttr = "create the policy attribute.";
L7_char8 *pStrInfo_qos_HtmlFileDiffservCfg = "diffserv_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileDiffservPolicyAttrSumm = "diffserv_policy_attr_summ.html";
L7_char8 *pStrInfo_qos_HtmlFileDiffservPolicyCfg = "diffserv_policy_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileDiffservPolicyDef = "diffserv_policy_def.html";
L7_char8 *pStrInfo_qos_HtmlFileDiffservPolicySumm = "diffserv_policy_summ.html";
L7_char8 *pStrInfo_qos_EndPort = "end port:";
L7_char8 *pStrInfo_qos_HtmlFileExpedite = "expedite.html";
L7_char8 *pStrInfo_qos_Ff = "ff";
L7_char8 *pStrInfo_qos_FindAFreeIdxInPolicyAttrTbl = "find a free index in policy attribute table.";
L7_char8 *pStrInfo_qos_GetClassName = "get Class Name";
L7_char8 *pStrInfo_qos_GetPolicyInstFromClass = "get Policy Instance from class.";
L7_char8 *pStrInfo_qos_HtmlLinkQosAclHelpAclAclintifvlansumm = "href=\"/qos/acl/help_acl.html#aclIntIfVlanSumm\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAclHelpAclAclrulecfg = "href=\"/qos/acl/help_acl.html#aclRuleCfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAclHelpAclAclsum = "href=\"/qos/acl/help_acl.html#aclSum\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAclHelpAclAclcfg = "href=\"/qos/acl/help_acl.html#aclcfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAclHelpAclVlanAclCfg = "href=\"/qos/acl/help_acl.html#vlan_acl_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkXuiQosAclHelpAclVlanAclCfg = "href=\"/help_ACLVlanConfig.html\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAclHelpIpMacAclIpMacAclCfg = "href=\"/qos/acl/help_ip_mac_acl.html#ip_mac_acl_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAclIpv6AclHelpIpv6AclIpv6aclrulecfg = "href=\"/qos/acl/ipv6_acl/help_ipv6_acl.html#ipv6aclRuleCfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAclIpv6AclHelpIpv6AclIpv6aclsum = "href=\"/qos/acl/ipv6_acl/help_ipv6_acl.html#ipv6aclSum\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAclIpv6AclHelpIpv6AclIpv6aclcfg = "href=\"/qos/acl/ipv6_acl/help_ipv6_acl.html#ipv6aclcfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAclMacAclHelpMacAclMacAclCfg = "href=\"/qos/acl/mac_acl/help_mac_acl.html#mac_acl_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAclMacAclHelpMacAclMacAclRuleCfg = "href=\"/qos/acl/mac_acl/help_mac_acl.html#mac_acl_rule_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAclMacAclHelpMacAclMacAclSumm = "href=\"/qos/acl/mac_acl/help_mac_acl.html#mac_acl_summ\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosCosHelpCosCosIntfCfg = "href=\"/qos/cos/help_cos.html#cos_intf_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosCosHelpCosCosIntfQueueCfg = "href=\"/qos/cos/help_cos.html#cos_intf_queue_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosCosHelpCosCosIntfQueueDropprecCfg = "href=\"/qos/cos/help_cos.html#cos_intf_queue_dropprec_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosCosHelpCosCosIntfQueueDropprecStatus = "href=\"/qos/cos/help_cos.html#cos_intf_queue_dropprec_status\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosCosHelpCosCosIntfQueueStatus = "href=\"/qos/cos/help_cos.html#cos_intf_queue_status\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosCosHelpCosCosIpDscpMapCfg = "href=\"/qos/cos/help_cos.html#cos_ip_dscp_map_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosCosHelpCosCosIpPrecMapCfg = "href=\"/qos/cos/help_cos.html#cos_ip_prec_map_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosCosHelpCosCosTrustModeCfg = "href=\"/qos/cos/help_cos.html#cos_trust_mode_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservDiffservCfg = "href=\"/qos/diffserv/help_diffserv.html#diffserv_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClasssumm = "href=\"/qos/diffserv/help_diffserv_class.html#classSumm\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfg = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleCos2 = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_cos2\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleCos = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_cos\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleDestPrefix = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_dest_prefix\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleDstip = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_dstip\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleDstl4port = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_dstl4port\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleDstmac = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_dstmac\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleEthertyp = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_ethertyp\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleFlowLabel = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_flow_label\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleIpdscp = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_ipdscp\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleIpprecedence = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_ipprecedence\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleIptos = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_iptos\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleProto = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_protocol\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleRefclass = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_refclass\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleSrcPrefix = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_src_prefix\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleSrcip = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_srcip\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleSrcl4port = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_srcl4port\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleSrcmac = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_srcmac\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleVlan2 = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_vlan2\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservClassClassCfgRuleVlan = "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_vlan\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyAssignQueue = "href=\"/qos/diffserv/help_diffserv_policy.html#assign_queue\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyBandwidth = "href=\"/qos/diffserv/help_diffserv_policy.html#bandwidth\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyDropPolicingAttrs = "href=\"/qos/diffserv/help_diffserv_policy.html#drop_policing_attributes\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyExpedite = "href=\"/qos/diffserv/help_diffserv_policy.html#expedite\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyMarkCos = "href=\"/qos/diffserv/help_diffserv_policy.html#mark_cos\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyMarkIpDscp = "href=\"/qos/diffserv/help_diffserv_policy.html#mark_ip_dscp\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyMarkIpPrec = "href=\"/qos/diffserv/help_diffserv_policy.html#mark_ip_prec\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyMarkSecondaryCos = "href=\"/qos/diffserv/help_diffserv_policy.html#mark_secondary_cos\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyMirrorIntf = "href=\"/qos/diffserv/help_diffserv_policy.html#mirror_interface\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyPolicingAttrs = "href=\"/qos/diffserv/help_diffserv_policy.html#policing_attributes\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyPolicingCfg = "href=\"/qos/diffserv/help_diffserv_policy.html#policing_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyPolicyattrsumm = "href=\"/qos/diffserv/help_diffserv_policy.html#policyAttrSumm\"";
L7_char8 *pStrInfo_qos_HtmlLinkXuiQosDiffservHelpDiffservPolicyPolicyattrsumm = "href=\"/help_DiffservPolicyAttrSummary.html\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyPolicysumm = "href=\"/qos/diffserv/help_diffserv_policy.html#policySumm\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyPolicyCfg = "href=\"/qos/diffserv/help_diffserv_policy.html#policy_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyPolicyDef = "href=\"/qos/diffserv/help_diffserv_policy.html#policy_def\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyRandomDrop = "href=\"/qos/diffserv/help_diffserv_policy.html#random_drop\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyRedirectIntf = "href=\"/qos/diffserv/help_diffserv_policy.html#redirect_interface\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyShapeAverage = "href=\"/qos/diffserv/help_diffserv_policy.html#shape_average\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservPolicyShapePeak = "href=\"/qos/diffserv/help_diffserv_policy.html#shape_peak\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservServiceServcfg = "href=\"/qos/diffserv/help_diffserv_service.html#servCfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservServiceServstatsdet = "href=\"/qos/diffserv/help_diffserv_service.html#servStatsDet\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservServiceServstats = "href=\"/qos/diffserv/help_diffserv_service.html#servStats\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosDiffservHelpDiffservServiceServsumm = "href=\"/qos/diffserv/help_diffserv_service.html#servSumm\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAutoVoIPHelpAutoVoIPCfg = "href=\"/qos/voip/help_autovoip.html#auto_voip_cfg\"";
L7_char8 *pStrInfo_qos_HtmlLinkQosAutoVoIPHelpAutoVoIPSumm = "href=\"/qos/voip/help_autovoip.html#auto_voip_summ\"";
L7_char8 *pStrInfo_qos_HttpWww = "http/www";
L7_char8 *pStrInfo_qos_HtmlFileIpMacAclCfg = "ip_mac_acl_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclCfg = "ipv6_acl_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfg = "ipv6_acl_rule_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgAction = "ipv6_acl_rule_cfg_action.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgAssignQId = "ipv6_acl_rule_cfg_assign_q_id.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgDestPrefix = "ipv6_acl_rule_cfg_dest_prefix.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgDscp = "ipv6_acl_rule_cfg_dscp.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgDstl4port = "ipv6_acl_rule_cfg_dstl4port.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgDstl4portrange = "ipv6_acl_rule_cfg_dstl4portrange.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgEvery = "ipv6_acl_rule_cfg_every.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgFlowlbl = "ipv6_acl_rule_cfg_flowlbl.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgLog = "ipv6_acl_rule_cfg_log.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgMirrorIntfc = "ipv6_acl_rule_cfg_mirror_intfc.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgProto = "ipv6_acl_rule_cfg_protocol.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgRedirectIntfc = "ipv6_acl_rule_cfg_redirect_intfc.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgSrcPrefix = "ipv6_acl_rule_cfg_src_prefix.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgSrcl4port = "ipv6_acl_rule_cfg_srcl4port.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclRuleCfgSrcl4portrange = "ipv6_acl_rule_cfg_srcl4portrange.html";
L7_char8 *pStrInfo_qos_HtmlFileIpv6AclSumm = "ipv6_acl_summ.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclCfg = "mac_acl_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgSecvlanrange = "mac_acl_rule_cfg_Secvlanrange.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgAction = "mac_acl_rule_cfg_action.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgCos = "mac_acl_rule_cfg_cos.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgDstmac = "mac_acl_rule_cfg_dstmac.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgEtype = "mac_acl_rule_cfg_etype.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgEvery = "mac_acl_rule_cfg_every.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgInt = "mac_acl_rule_cfg_int.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgLog = "mac_acl_rule_cfg_log.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgMirror = "mac_acl_rule_cfg_mirror.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgQid = "mac_acl_rule_cfg_qid.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgRo = "mac_acl_rule_cfg_ro.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgRw = "mac_acl_rule_cfg_rw.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgSeccos = "mac_acl_rule_cfg_seccos.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgSecvlan = "mac_acl_rule_cfg_secvlan.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgSrcmac = "mac_acl_rule_cfg_srcmac.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgVlan = "mac_acl_rule_cfg_vlan.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclRuleCfgVlanrange = "mac_acl_rule_cfg_vlanrange.html";
L7_char8 *pStrInfo_qos_HtmlFileMacAclSumm = "mac_acl_summ.html";
L7_char8 *pStrInfo_qos_HtmlFileMarkCos = "mark_cos.html";
L7_char8 *pStrInfo_qos_HtmlFileMarkCos2 = "mark_cos2.html";
L7_char8 *pStrInfo_qos_HtmlFileMarkIpDscp = "mark_ip_dscp.html";
L7_char8 *pStrInfo_qos_HtmlFileMarkIpPrec = "mark_ip_prec.html";
L7_char8 *pStrInfo_qos_Microseconds = "microseconds";
L7_char8 *pStrInfo_qos_HtmlFileMirrorIntf = "mirror_interface.html";
L7_char8 *pStrInfo_qos_HtmlFilePolicingAttrs = "policing_attributes.html";
L7_char8 *pStrInfo_qos_HtmlFilePolicingCfg = "policing_cfg.html";
L7_char8 *pStrInfo_qos_PolicyName_2 = "policy name.";
L7_char8 *pStrInfo_qos_HtmlFileRandomDrop = "random_drop.html";
L7_char8 *pStrInfo_qos_HtmlFileRedirectIntf = "redirect_interface.html";
L7_char8 *pStrInfo_qos_HtmlFileServiceCfg = "service_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileServiceStats = "service_stats.html";
L7_char8 *pStrInfo_qos_HtmlFileServiceStatsDet = "service_stats_det.html";
L7_char8 *pStrInfo_qos_HtmlFileServiceSumm = "service_summ.html";
L7_char8 *pStrInfo_qos_SetAverageShapingCommittedRateVal = "set the (average) shaping committed rate value.";
L7_char8 *pStrInfo_qos_SetPeakShapingCommittedRateVal = "set the (peak) shaping committed rate value.";
L7_char8 *pStrInfo_qos_SetPeakShapingPeakRateVal = "set the (peak) shaping peak rate value.";
L7_char8 *pStrInfo_qos_SetBandwidthCommittedRateUnitsVal = "set the bandwidth committed rate units value.";
L7_char8 *pStrInfo_qos_SetBandwidthCommittedRateVal = "set the bandwidth committed rate value.";
L7_char8 *pStrInfo_qos_SetConformingActionVal = "set the conforming action value.";
L7_char8 *pStrInfo_qos_SetExpeditedCommittedBurstSizeVal = "set the expedited committed burst size value.";
L7_char8 *pStrInfo_qos_SetExpeditedCommittedRateUnitsVal = "set the expedited committed rate units value.";
L7_char8 *pStrInfo_qos_SetExpeditedCommittedRateVal = "set the expedited committed rate value.";
L7_char8 *pStrInfo_qos_SetMarkingCosVal = "set the marking COS value.";
L7_char8 *pStrInfo_qos_SetMarkingIpDscpVal = "set the marking IP DSCP value.";
L7_char8 *pStrInfo_qos_SetMarkingIpPrecedenceVal = "set the marking IP Precedence value.";
L7_char8 *pStrInfo_qos_SetMarkingSecondaryCosVal = "set the marking Secondary COS value.";
L7_char8 *pStrInfo_qos_SetMirrorIntf = "set the mirror interface.";
L7_char8 *pStrInfo_qos_SetNonconformingActionVal = "set the nonconforming action value.";
L7_char8 *pStrInfo_qos_SetPolicingAttrColorConformClass = "set the policing attribute Color Conform Class.";
L7_char8 *pStrInfo_qos_SetPolicingAttrColorExceedClass = "set the policing attribute Color Exceed Class.";
L7_char8 *pStrInfo_qos_SetPolicingConformActionVal = "set the policing conform action value.";
L7_char8 *pStrInfo_qos_SetPolicyAttrExceedVal = "set the policy attribute exceed value.";
L7_char8 *pStrInfo_qos_SetPolicyAttrType = "set the policy attribute type.";
L7_char8 *pStrInfo_qos_SetQueueId = "set the queue id.";
L7_char8 *pStrInfo_qos_SetRandomDropDecayExponentVal = "set the random-drop decay exponent value.";
L7_char8 *pStrInfo_qos_SetRandomDropMaxDropProbabilityVal = "set the random-drop maximum drop probability value.";
L7_char8 *pStrInfo_qos_SetRandomDropMaxThreshVal = "set the random-drop maximum threshold value.";
L7_char8 *pStrInfo_qos_SetRandomDropMinThreshVal = "set the random-drop minimum threshold value.";
L7_char8 *pStrInfo_qos_SetRandomDropSamplingRateVal = "set the random-drop sampling rate value.";
L7_char8 *pStrInfo_qos_SetRedirectIntf = "set the redirect interface.";
L7_char8 *pStrInfo_qos_SetSimplePolicingCommittedBurstSizeVal = "set the simple policing committed burst size value.";
L7_char8 *pStrInfo_qos_SetSimplePolicingCommittedRateVal = "set the simple policing committed rate value.";
L7_char8 *pStrInfo_qos_SetSimplePolicingCommittedRateVal64 = "set the simple policing committed rate value. Automatically rounded to step of 64.";
L7_char8 *pStrInfo_qos_SetSingleRatePolicingCommittedBurstSizeVal = "set the single-rate policing committed burst size value.";
L7_char8 *pStrInfo_qos_SetSingleRatePolicingCommittedRateVal = "set the single-rate policing committed rate value.";
L7_char8 *pStrInfo_qos_SetSingleRatePolicingExcessBurstSizeVal = "set the single-rate policing excess burst size value.";
L7_char8 *pStrInfo_qos_SetTwoRatePolicingCommittedBurstSizeVal = "set the two-rate policing committed burst size value.";
L7_char8 *pStrInfo_qos_SetTwoRatePolicingCommittedRateVal = "set the two-rate policing committed rate value.";
L7_char8 *pStrInfo_qos_SetTwoRatePolicingPeakBurstSizeVal = "set the two-rate policing peak burst size value.";
L7_char8 *pStrInfo_qos_SetTwoRatePolicingPeakRateVal = "set the two-rate policing peak rate value.";
L7_char8 *pStrInfo_qos_HtmlFileShapeAverage = "shape_average.html";
L7_char8 *pStrInfo_qos_HtmlFileShapePeak = "shape_peak.html";
L7_char8 *pStrInfo_qos_StartPort = "start port:";
L7_char8 *pStrInfo_qos_Taildrop = "taildrop";
L7_char8 *pStrInfo_qos_DiffservAdminMode_1 = "the Diffserv Admin Mode.";
L7_char8 *pStrInfo_qos_TrustDot1p = "trust dot1p";
L7_char8 *pStrInfo_qos_TrustIpDscp = "trust ip-dscp";
L7_char8 *pStrInfo_qos_TrustIpPrecedence = "trust ip-precedence";
L7_char8 *pStrInfo_qos_HtmlFileVlanAclCfg = "vlan_acl_cfg.html";
L7_char8 *pStrInfo_qos_Weighted_1 = "weighted";
L7_char8 *pStrInfo_qos_Wred_1 = "wred";
L7_char8 *pStrErr_qos_AssignQueueID = "Assign Queue ID";
L7_char8 *pStrErr_qos_IPV6ACL = "IPv6 ACL";
L7_char8 *pStrErr_qos_IPV6ACLName = "IPv6 ACL Name";
L7_char8 *pStrErr_qos_MirrorInterface  = "Mirror Interface";
L7_char8 *pStrErr_qos_RedirectInterface = "Redirect Interface";
L7_char8 *pStrErr_qos_Protocol = "Protocol";
L7_char8 *pStrErr_qos_SourcePrefixPrefixLength = "Source Prefix/PrefixLength";
L7_char8 *pStrErr_qos_DestinationPrefixPrefixLength = "Destination Prefix/PrefixLength";
L7_char8 *pStrErr_qos_FlowLabel = "Flow Label";
L7_char8 *pStrErr_qos_IPDSCPService = "IP DSCP Service";
L7_char8 *pStrErr_qos_Inbound = "Inbound";
L7_char8 *pStrErr_qos_Outbound = "Outbound";
L7_char8 *pStrErr_qos_ACLType = "ACL Type";
L7_char8 *pStrErr_qos_SequenceNumber = "Sequence Number";
L7_char8 *pStrInfo_qos_AutoVoip_Mode="Auto VoIP Mode";
L7_char8 *pStrInfo_qos_AutoVoip_MinBandWidth="Minimum Bandwidth";
L7_char8 *pStrInfo_qos_AutoVoip_MinBandWidthKbps="Minimum Bandwidth (Kbps)";
L7_char8 *pStrInfo_qos_AutoVoIP_TrafficClass="Traffic Class"; 
L7_char8 *pStrInfo_qos_AutoVoIPCfg = "Auto VoIP Configuration";
L7_char8 *pStrInfo_qos_AutoVoIPSummary = "Auto VoIP Summary";
L7_char8 *pStrInfo_qos_HtmlFileAutoVoipCfg = "auto_voip_cfg.html";
L7_char8 *pStrInfo_qos_HtmlFileAutoVoipSummary = "auto_voip_summ.html";




