#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dnx/dnx_data subdirectory
#

LOCALDIR = src/soc/dnxc/dnxc_data

include ${SDK}/make/Make.config


include ${SDK}/make/Make.subdirs

lib = libsoc_dnxcdnxcdata

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

