/*********************************************************************
*
* (C) Copyright Broadcom Corporation 2006-2007
*
**********************************************************************
*                                                                     
* @filename   src/nls/web/bgp/strlib_bgp_web.c                                                      
*                                                                     
* @purpose    Strings Library                                                      
*                                                                     
* @component  Common Strings Library                                                      
*                                                                     
* @comments   none                                                    
*                                                                     
* @create     01/10/2007                                                      
*                                                                     
* @author     Rama Sasthri, Kristipati                                
*                                                                     
* @end                                                                
*                                                                     
*********************************************************************/

#include "strlib_bgp_web.h"

L7_char8 *pStrInfo_bgp_AsPath = "AS Path";
L7_char8 *pStrInfo_bgp_AsPathRegex = "AS Path Regex";
L7_char8 *pStrInfo_bgp_AsPathSegment = "AS Path Segment";
L7_char8 *pStrInfo_bgp_AsRoutLoop = "AS_ROUT_LOOP";
L7_char8 *pStrInfo_bgp_AtrFlagErr = "ATR_FLAG_ERR";
L7_char8 *pStrInfo_bgp_AtrLenErr = "ATR_LEN_ERR ";
L7_char8 *pStrInfo_bgp_AuthFail = "AUTH_FAIL ";
L7_char8 *pStrInfo_bgp_AccessList = "Access List";
L7_char8 *pStrInfo_bgp_AddARange = "Add A Range";
L7_char8 *pStrInfo_bgp_AddAnAction = "Add An Action";
L7_char8 *pStrInfo_bgp_AddEvent = "Add Event";
L7_char8 *pStrInfo_bgp_AddrAggregationEntry = "Address Aggregation Entry";
L7_char8 *pStrInfo_bgp_AddrFamily = "Address Family";
L7_char8 *pStrInfo_bgp_AddrFamilyCfg = "Address Family Configuration";
L7_char8 *pStrInfo_bgp_AddrFamilyId = "Address Family Identifier";
L7_char8 *pStrInfo_bgp_AddrFamilyAlreadyExists = "Address Family already exists";
L7_char8 *pStrInfo_bgp_AddrFamilyNotFound = "Address Family not found";
L7_char8 *pStrInfo_bgp_Advertise = "Advertise";
L7_char8 *pStrInfo_bgp_AdvertiseFeasibility = "Advertise Feasibility";
L7_char8 *pStrInfo_bgp_AggregateEffect = "Aggregate Effect";
L7_char8 *pStrInfo_bgp_AggregatorAs = "Aggregator AS";
L7_char8 *pStrInfo_bgp_AggregatorAddr = "Aggregator Address";
L7_char8 *pStrInfo_bgp_AggregatorId = "Aggregator ID";
L7_char8 *pStrInfo_bgp_AsPathLenBits = "As Path Length (bits)";
L7_char8 *pStrInfo_bgp_AtomicAggregate = "Atomic Aggregate";
L7_char8 *pStrInfo_bgp_BadBgpId = "BAD_BGP_ID ";
L7_char8 *pStrInfo_bgp_BadMsgLen = "BAD_MSG_LEN ";
L7_char8 *pStrInfo_bgp_BadMsgType = "BAD_MSG_TYPE";
L7_char8 *pStrInfo_bgp_BadPeerAs = "BAD_PEER_AS ";
L7_char8 *pStrInfo_bgp_Bgp4AddrAggregationCfg = "BGP4 Address Aggregation Configuration";
L7_char8 *pStrInfo_bgp_Bgp4DampenedPathsTbl = "BGP4 Dampened Paths Table";
L7_char8 *pStrInfo_bgp_Bgp4GlobalCfg = "BGP4 Global Configuration";
L7_char8 *pStrInfo_bgp_Bgp4LocalNlriCfg = "BGP4 Local NLRI Configuration";
L7_char8 *pStrInfo_bgp_Bgp4LocalOriginatedPathCfg = "BGP4 Local Originated Path Configuration";
L7_char8 *pStrInfo_bgp_Bgp4PathAttrsTbl = "BGP4 Path Attributes Table";
L7_char8 *pStrInfo_bgp_Bgp4PeerAddrFamilyCfg = "BGP4 Peer Address Family Configuration";
L7_char8 *pStrInfo_bgp_Bgp4PeerAuthCfg = "BGP4 Peer Authentication Configuration";
L7_char8 *pStrInfo_bgp_Bgp4PeerCfg = "BGP4 Peer Configuration";
L7_char8 *pStrInfo_bgp_Bgp4PeerStats = "BGP4 Peer Statistics";
L7_char8 *pStrInfo_bgp_Bgp4PolicyActionCfg = "BGP4 Policy Action Configuration";
L7_char8 *pStrInfo_bgp_Bgp4PolicyActionTypeSelection = "BGP4 Policy Action Type Selection";
L7_char8 *pStrInfo_bgp_Bgp4PolicyCfg = "BGP4 Policy Configuration";
L7_char8 *pStrInfo_bgp_Bgp4PolicyCfgSummary = "BGP4 Policy Configuration Summary";
L7_char8 *pStrInfo_bgp_Bgp4PolicyRangeCfg = "BGP4 Policy Range Configuration";
L7_char8 *pStrInfo_bgp_Bgp4PolicyRangeTypeSelection = "BGP4 Policy Range Type Selection";
L7_char8 *pStrInfo_bgp_Bgp4RouteFlapCfg = "BGP4 Route Flap Configuration";
L7_char8 *pStrInfo_bgp_Bgp4RouteRedistributionCfg = "BGP4 Route Redistribution Configuration";
L7_char8 *pStrInfo_bgp_Bgp4RouteRedistributionSummary = "BGP4 Route Redistribution Summary";
L7_char8 *pStrInfo_bgp_Bgp4RouteTblSummary = "BGP4 Route Table Summary";
L7_char8 *pStrInfo_bgp_Bgp4SnpaCfg = "BGP4 SNPA Configuration";
L7_char8 *pStrInfo_bgp_Cease = "CEASE ";
L7_char8 *pStrInfo_bgp_ConNsync = "CON_NSYNC ";
L7_char8 *pStrInfo_bgp_CalculatedLocalPref = "Calculated Local Preference";
L7_char8 *pStrInfo_bgp_ClusterIdCfg = "Cluster ID Configuration";
L7_char8 *pStrInfo_bgp_ClusterNum = "Cluster Number";
L7_char8 *pStrInfo_bgp_CommunityRegex = "Community Regex";
L7_char8 *pStrInfo_bgp_ConfederationId = "Confederation ID";
L7_char8 *pStrInfo_bgp_ConfederationIdCfg = "Confederation ID Configuration";
L7_char8 *pStrInfo_bgp_CfgureAnAction = "Configure An Action";
L7_char8 *pStrInfo_bgp_CfgureSelectedAction = "Configure Selected Action";
L7_char8 *pStrInfo_bgp_CfgureSelectedRange = "Configure Selected Range";
L7_char8 *pStrInfo_bgp_CfguredHoldTimeSecs = "Configured Hold Time (secs)";
L7_char8 *pStrInfo_bgp_CfguredKeepAliveTimeSecs = "Configured Keep Alive Time (secs)";
L7_char8 *pStrInfo_bgp_Connect_1 = "Connect";
L7_char8 *pStrInfo_bgp_ConnRetryIntvlSecs = "Connection Retry Interval (secs)";
L7_char8 *pStrInfo_bgp_CreatePolicy = "Create Policy";
L7_char8 *pStrInfo_bgp_DelPolicy = "Delete Policy";
L7_char8 *pStrInfo_bgp_DeltaTimeSecs = "Delta Time (secs)";
L7_char8 *pStrInfo_bgp_DestIpPref = "Dest IP Pref";
L7_char8 *pStrErr_bgp_DoNotSend = "Do Not Send";
L7_char8 *pStrInfo_bgp_DoNotSend_1 = "Do not send";
L7_char8 *pStrInfo_bgp_Donotadvertise = "DoNotAdvertise";
L7_char8 *pStrInfo_bgp_EnterARegularExpressionToMatch = "Enter a regular expression to match";
L7_char8 *pStrInfo_bgp_Established_1 = "Established";
L7_char8 *pStrInfo_bgp_ExternalBorderRtrsAdvertisementMode = "External Border Routers Advertisement Mode";
L7_char8 *pStrInfo_bgp_Fsm = "FSM ";
L7_char8 *pStrErr_bgp_FailedToCfgurePolicyAction = "Failed to configure policy action";
L7_char8 *pStrErr_bgp_FailedToCfgurePolicyRange = "Failed to configure policy range";
L7_char8 *pStrErr_bgp_FailedToRemoveSelectedAction = "Failed to remove the selected action";
L7_char8 *pStrInfo_bgp_FlapMaxTimeSecs = "Flap Max Time (secs)";
L7_char8 *pStrInfo_bgp_FlowSpec = "Flow Spec";
L7_char8 *pStrInfo_bgp_HoldTmr = "HOLD_TMR ";
L7_char8 *pStrInfo_bgp_InvalidOrgn = "INVALID_ORGN";
L7_char8 *pStrInfo_bgp_InvNetwFld = "INV_NETW_FLD";
L7_char8 *pStrInfo_bgp_InvNextHop = "INV_NEXT_HOP";
L7_char8 *pStrInfo_bgp_IpAddrVal1 = "IP Address Value 1";
L7_char8 *pStrInfo_bgp_IpAddrVal2 = "IP Address Value 2";
L7_char8 *pStrInfo_bgp_Illegal = "Illegal";
L7_char8 *pStrInfo_bgp_InitEvent_1 = "Init Event";
L7_char8 *pStrInfo_bgp_IntegerVal1 = "Integer Value 1";
L7_char8 *pStrInfo_bgp_IntegerVal2 = "Integer Value 2";
L7_char8 *pStrInfo_bgp_InternalIn = "Internal In";
L7_char8 *pStrInfo_bgp_InternalOut = "Internal Out";
L7_char8 *pStrErr_bgp_IpAddrEnterFourNumsSeparatedByPeriodInRangeOf0To255 = "Invalid IP address. Enter four numbers separated by period in the range of 0 to 255.";
L7_char8 *pStrErr_bgp_MetricValValidRange04294967295 = "Invalid Metric Value:  Valid Range 0 - 4294967295";
L7_char8 *pStrErr_bgp_ValForAddrAggregationMode = "Invalid Value for Address Aggregation Mode";
L7_char8 *pStrErr_bgp_ValForAdminMode = "Invalid Value for Admin Mode";
L7_char8 *pStrErr_bgp_ValForAdvertisementOfExternalBorderRtrs = "Invalid Value for Advertisement of External Border Routers";
L7_char8 *pStrErr_bgp_ValForAuthCode = "Invalid Value for Authentication Code";
L7_char8 *pStrErr_bgp_ValForAutoRestartMode = "Invalid Value for Auto Restart Mode";
L7_char8 *pStrErr_bgp_ValForCalculateMedMode = "Invalid Value for Calculate MED Mode";
L7_char8 *pStrErr_bgp_ValForClusterId = "Invalid Value for Cluster ID";
L7_char8 *pStrErr_bgp_ValForConfederationId = "Invalid Value for Confederation ID";
L7_char8 *pStrErr_bgp_ValForConfederationMbr = "Invalid Value for Confederation Member";
L7_char8 *pStrErr_bgp_ValForConnRetryIntvl = "Invalid Value for Connection Retry Interval";
L7_char8 *pStrErr_bgp_ValForDampingFactor = "Invalid Value for Damping Factor";
L7_char8 *pStrErr_bgp_ValForDeflInfoOriginate = "Invalid Value for Default Information Originate";
L7_char8 *pStrErr_bgp_ValForDeflMetricValidRange04294967295 = "Invalid Value for Default Metric..Valid Range 0 - 4294967295.";
L7_char8 *pStrErr_bgp_ValForDeltaTime = "Invalid Value for Delta Time";
L7_char8 *pStrErr_bgp_ValForFlapMaxTime = "Invalid Value for Flap Max Time";
L7_char8 *pStrErr_bgp_ValForHoldTime = "Invalid Value for Hold Time";
L7_char8 *pStrErr_bgp_ValForKeepAliveTime = "Invalid Value for Keep Alive Time";
L7_char8 *pStrErr_bgp_ValForLocalAutonomousSys = "Invalid Value for Local Autonomous System";
L7_char8 *pStrErr_bgp_ValForLocalId = "Invalid Value for Local Identifier";
L7_char8 *pStrErr_bgp_ValForMsgSendLimit = "Invalid Value for Message Send Limit";
L7_char8 *pStrErr_bgp_ValForMininumAsOriginationIntvl = "Invalid Value for Mininum AS Origination Interval";
L7_char8 *pStrErr_bgp_ValForMininumRouteAdvertisementIntvl = "Invalid Value for Mininum Route Advertisement Interval";
L7_char8 *pStrErr_bgp_ValForNextHop = "Invalid Value for Next Hop";
L7_char8 *pStrErr_bgp_ValForNextHopAddrLen = "Invalid Value for Next Hop Address Length";
L7_char8 *pStrErr_bgp_ValForNextHopSelf = "Invalid Value for Next Hop Self";
L7_char8 *pStrErr_bgp_ValForPeerAdminStatus = "Invalid Value for Peer Admin Status";
L7_char8 *pStrErr_bgp_ValForPenaltyIncrement = "Invalid Value for Penalty Increment";
L7_char8 *pStrErr_bgp_ValForPrefix = "Invalid Value for Prefix";
L7_char8 *pStrErr_bgp_ValForPrefixLen = "Invalid Value for Prefix Length";
L7_char8 *pStrErr_bgp_ValForPropagateMedMode = "Invalid Value for Propagate MED Mode";
L7_char8 *pStrErr_bgp_ValForRemoteAs = "Invalid Value for Remote AS";
L7_char8 *pStrErr_bgp_ValForRemoteAddr = "Invalid Value for Remote Address";
L7_char8 *pStrErr_bgp_ValForReuseLimit = "Invalid Value for Reuse Limit";
L7_char8 *pStrErr_bgp_ValForReuseSize = "Invalid Value for Reuse Size";
L7_char8 *pStrErr_bgp_ValForRouteCommunity = "Invalid Value for Route Community";
L7_char8 *pStrErr_bgp_ValForRouteFlapMode = "Invalid Value for Route Flap Mode";
L7_char8 *pStrErr_bgp_ValForRouteLocalPref = "Invalid Value for Route Local Preference";
L7_char8 *pStrErr_bgp_ValForRouteMed = "Invalid Value for Route MED";
L7_char8 *pStrErr_bgp_ValForRouteReflectorMode = "Invalid Value for Route Reflector Mode";
L7_char8 *pStrErr_bgp_ValForSnpaAddr = "Invalid Value for SNPA Address";
L7_char8 *pStrErr_bgp_ValForSnpaAddrLen = "Invalid Value for SNPA Address Length";
L7_char8 *pStrErr_bgp_ValForSendNow = "Invalid Value for Send Now";
L7_char8 *pStrErr_bgp_ValForSuppressLimit = "Invalid Value for Suppress Limit";
L7_char8 *pStrErr_bgp_ValForSuppressMode = "Invalid Value for Suppress Mode";
L7_char8 *pStrErr_bgp_ValForTransmissionDelayIntvl = "Invalid Value for Transmission Delay Interval";
L7_char8 *pStrErr_bgp_OptionForReadonlyUsr = "Invalid option for ReadOnly user";
L7_char8 *pStrErr_bgp_ValForPolicyIdx = "Invalid value for policy index";
L7_char8 *pStrErr_bgp_ValSEnteredForPolicyRangeCfg = "Invalid value(s) entered for policy range configuration";
L7_char8 *pStrInfo_bgp_KeepAliveTimeSecs = "Keep Alive Time (secs)";
L7_char8 *pStrInfo_bgp_LocalPref = "Local Preference";
L7_char8 *pStrInfo_bgp_MalformAtr = "MALFORM_ATR ";
L7_char8 *pStrInfo_bgp_MalfrAsPth = "MALFR_AS_PTH";
L7_char8 *pStrInfo_bgp_MisWknAtr = "MIS_WKN_ATR ";
L7_char8 *pStrInfo_bgp_MsgHdr = "MSG_HEADER";
L7_char8 *pStrInfo_bgp_MaxHoldPri = "Max Hold Priority";
L7_char8 *pStrInfo_bgp_MaxSetupPri = "Max Setup Priority";
L7_char8 *pStrInfo_bgp_MaxVal = "Maximum Value";
L7_char8 *pStrInfo_bgp_MinVal = "Minimum Value";
L7_char8 *pStrInfo_bgp_MininumAsOriginationIntvlSecs = "Mininum AS Origination Interval (secs)";
L7_char8 *pStrInfo_bgp_MininumRouteAdvertisementIntvlSecs = "Mininum Route Advertisement Interval (secs)";
L7_char8 *pStrInfo_bgp_Modifier = "Modifier";
L7_char8 *pStrInfo_bgp_ModifyARange = "Modify A Range";
L7_char8 *pStrInfo_bgp_MultiExitDisc = "Multi Exit Disc";
L7_char8 *pStrInfo_bgp_NlriEntry = "NLRI Entry";
L7_char8 *pStrInfo_bgp_NlriTblIsFull = "NLRI Table is full.";
L7_char8 *pStrInfo_bgp_NoErr = "NO_ERR ";
L7_char8 *pStrInfo_bgp_NoSberr = "NO_SBERR ";
L7_char8 *pStrInfo_bgp_NegotiatedHoldTimeSecs = "Negotiated Hold Time (secs)";
L7_char8 *pStrInfo_bgp_NextHopAddrLen = "Next Hop Address Length";
L7_char8 *pStrInfo_bgp_NoPeersAvailable = "No Peers Available";
L7_char8 *pStrInfo_bgp_NonClient = "Non_Client";
L7_char8 *pStrErr_bgp_NotSuppressed = "Not Suppressed";
L7_char8 *pStrErr_bgp_NotPresent_1 = "Not present";
L7_char8 *pStrInfo_bgp_OpenMsg = "OPEN_MSG ";
L7_char8 *pStrInfo_bgp_OptAtrErr = "OPT_ATR_ERR ";
L7_char8 *pStrInfo_bgp_OspfDestinType = "OSPF Destin Type";
L7_char8 *pStrInfo_bgp_OpenSent_1 = "Open-sent";
L7_char8 *pStrInfo_bgp_Openconfirm = "Openconfirm";
L7_char8 *pStrInfo_bgp_OutOfRangeValForConfederationId = "Out of Range Value for Confederation ID";
L7_char8 *pStrInfo_bgp_PathAttrAggregationMode = "Path Attribute Aggregation Mode";
L7_char8 *pStrInfo_bgp_PenaltyVal = "Penalty Value";
L7_char8 *pStrInfo_bgp_PolicyActionCfg = "Policy Action Configuration";
L7_char8 *pStrInfo_bgp_PolicyRangeCfg = "Policy Range Configuration";
L7_char8 *pStrInfo_bgp_PolicyString = "Policy String";
L7_char8 *pStrInfo_bgp_PrefixLenBits = "Prefix Length (bits)";
L7_char8 *pStrInfo_bgp_Present = "Present";
L7_char8 *pStrInfo_bgp_ProtoId = "Protocol ID";
L7_char8 *pStrInfo_bgp_Range_1 = "Range";
L7_char8 *pStrInfo_bgp_RangeMatch = "Range Match";
L7_char8 *pStrInfo_bgp_RemoveAnAction = "Remove An Action";
L7_char8 *pStrInfo_bgp_RemoveSelectedAction = "Remove Selected Action";
L7_char8 *pStrInfo_bgp_Reused_1 = "Reused";
L7_char8 *pStrInfo_bgp_RouteReflector = "Route Reflector";
L7_char8 *pStrInfo_bgp_SnpaAddr = "SNPA Address";
L7_char8 *pStrInfo_bgp_SnpaAddrLenBits = "SNPA Address Length (bits)";
L7_char8 *pStrInfo_bgp_SnpaTblIsFull = "SNPA Table is full.";
L7_char8 *pStrInfo_bgp_SocketErr = "SOCKET_ERR";
L7_char8 *pStrInfo_bgp_SendNow = "Send Now";
L7_char8 *pStrErr_bgp_SpecifiedAddrAggregationEntryDoesntExistOrInvalidAggregatePrefix = "Specified Address Aggregation Entry does not exist or Invalid Aggregate Prefix.";
L7_char8 *pStrInfo_bgp_Stop_1 = "Stop";
L7_char8 *pStrInfo_bgp_SubsequentAddrFamilyId = "Subsequent Address Family Identifier";
L7_char8 *pStrInfo_bgp_Suppressed = "Suppressed";
L7_char8 *pStrInfo_bgp_MinRangeEnteredIsGreaterThanMaxRangeEntered = "The minimum range entered is greater than the maximum range entered.";
L7_char8 *pStrInfo_bgp_TimeElapsedSinceLastUpdate = "Time Elapsed Since Last Update";
L7_char8 *pStrInfo_bgp_TransmissionDelayIntvlSecs = "Transmission Delay Interval (secs)";
L7_char8 *pStrInfo_bgp_UnacptHoldt = "UNACPT_HOLDT";
L7_char8 *pStrInfo_bgp_UnrcWknAtr = "UNRC_WKN_ATR";
L7_char8 *pStrInfo_bgp_UnspVer = "UNSP_VERSION";
L7_char8 *pStrInfo_bgp_UnsuppCap = "UNSUPP_CAP ";
L7_char8 *pStrInfo_bgp_UnsuppOpt = "UNSUPP_OPT ";
L7_char8 *pStrInfo_bgp_UpdateMsg = "UPDATE_MSG";
L7_char8 *pStrInfo_bgp_UnableToCreateAddrAggregationEntry = "Unable to Create Address Aggregation Entry";
L7_char8 *pStrInfo_bgp_UnableToCreatePolicy = "Unable to Create Policy";
L7_char8 *pStrInfo_bgp_UnableToUpdateAddrAggregationEntry = "Unable to Update Address Aggregation Entry.";
L7_char8 *pStrInfo_bgp_UnableToAddLocalNlriEntry = "Unable to add Local NLRI Entry";
L7_char8 *pStrInfo_bgp_UnableToAddSnpaEntry = "Unable to add the SNPA Entry";
L7_char8 *pStrInfo_bgp_UnableToDelAddrAggregationEntry = "Unable to delete Address Aggregation Entry";
L7_char8 *pStrInfo_bgp_UnableToDelLocalNlriEntry = "Unable to delete Local NLRI Entry";
L7_char8 *pStrInfo_bgp_UnableToDelPeer = "Unable to delete Peer";
L7_char8 *pStrInfo_bgp_UnableToDelPolicy = "Unable to delete policy";
L7_char8 *pStrInfo_bgp_UnableToDelSnpaEntry = "Unable to delete the SNPA entry.";
L7_char8 *pStrInfo_bgp_UnableToSetAddrAggregationMode = "Unable to set Address Aggregation Mode";
L7_char8 *pStrInfo_bgp_UnableToSetAdminMode = "Unable to set Admin Mode";
L7_char8 *pStrInfo_bgp_UnableToSetAuthCode = "Unable to set Authentication Code";
L7_char8 *pStrInfo_bgp_UnableToSetAutoRestartMode = "Unable to set Auto Restart Mode";
L7_char8 *pStrInfo_bgp_UnableToSetCalculateMedMode = "Unable to set Calculate MED Mode";
L7_char8 *pStrInfo_bgp_UnableToSetClusterId = "Unable to set Cluster ID";
L7_char8 *pStrInfo_bgp_UnableToSetConfederationId = "Unable to set Confederation ID";
L7_char8 *pStrInfo_bgp_UnableToSetConfederationMbr = "Unable to set Confederation Member";
L7_char8 *pStrInfo_bgp_UnableToSetConnRetryIntvl = "Unable to set Connection Retry Interval";
L7_char8 *pStrInfo_bgp_UnableToSetDampingFactor = "Unable to set Damping Factor";
L7_char8 *pStrInfo_bgp_UnableToSetDeltaTime = "Unable to set Delta Time";
L7_char8 *pStrInfo_bgp_UnableToSetExtBorderRtrAdvMode = "Unable to set Ext. Border Router Adv. Mode";
L7_char8 *pStrInfo_bgp_UnableToSetFlapMaxTime = "Unable to set Flap Max Time";
L7_char8 *pStrInfo_bgp_UnableToSetHoldTime = "Unable to set Hold Time";
L7_char8 *pStrInfo_bgp_UnableToSetKeepAliveTime = "Unable to set Keep Alive Time";
L7_char8 *pStrInfo_bgp_UnableToSetLocalAs = "Unable to set Local AS";
L7_char8 *pStrInfo_bgp_UnableToSetLocalId = "Unable to set Local Identifier";
L7_char8 *pStrInfo_bgp_UnableToSetMsgSendLimit = "Unable to set Message Send Limit";
L7_char8 *pStrInfo_bgp_UnableToSetMininumAsOriginationIntvl = "Unable to set Mininum AS Origination Interval";
L7_char8 *pStrInfo_bgp_UnableToSetMininumRouteAdvertisementIntvl = "Unable to set Mininum Route Advertisement Interval";
L7_char8 *pStrInfo_bgp_UnableToSetNextHopAddrLen = "Unable to set Next Hop Address Length";
L7_char8 *pStrInfo_bgp_UnableToSetNextHopSelf = "Unable to set Next Hop Self";
L7_char8 *pStrInfo_bgp_UnableToSetOptionalCapabilities = "Unable to set Optional Capabilities";
L7_char8 *pStrInfo_bgp_UnableToSetPeerAdminStatus = "Unable to set Peer Admin Status";
L7_char8 *pStrInfo_bgp_UnableToSetPenaltyIncrement = "Unable to set Penalty Increment";
L7_char8 *pStrInfo_bgp_UnableToSetPropagateMedMode = "Unable to set Propagate MED Mode";
L7_char8 *pStrInfo_bgp_UnableToSetReUseLimit = "Unable to set Re-use Limit";
L7_char8 *pStrInfo_bgp_UnableToSetReUseSize = "Unable to set Re-use Size";
L7_char8 *pStrInfo_bgp_UnableToSetRemoteAs = "Unable to set Remote AS";
L7_char8 *pStrInfo_bgp_UnableToSetRouteCommunity = "Unable to set Route Community";
L7_char8 *pStrInfo_bgp_UnableToSetRouteFlapMode = "Unable to set Route Flap Mode";
L7_char8 *pStrInfo_bgp_UnableToSetRouteLocalPref = "Unable to set Route Local Preference";
L7_char8 *pStrInfo_bgp_UnableToSetRouteMed = "Unable to set Route MED";
L7_char8 *pStrInfo_bgp_UnableToSetRouteOrigin = "Unable to set Route Origin";
L7_char8 *pStrInfo_bgp_UnableToSetRouteReflector = "Unable to set Route Reflector";
L7_char8 *pStrInfo_bgp_UnableToSetRouteReflectorMode = "Unable to set Route Reflector Mode";
L7_char8 *pStrInfo_bgp_UnableToSetSuppressLimit = "Unable to set Suppress Limit";
L7_char8 *pStrInfo_bgp_UnableToSetSuppressMode = "Unable to set Suppress Mode";
L7_char8 *pStrInfo_bgp_UnableToSetTransmissionDelayIntvl = "Unable to set Transmission Delay Interval";
L7_char8 *pStrInfo_bgp_UnknownAddrFamilySelection = "Unknown Address Family Selection";
L7_char8 *pStrInfo_bgp_UnknownModifier = "Unknown Modifier";
L7_char8 *pStrInfo_bgp_UnknownSelection = "Unknown Selection";
L7_char8 *pStrInfo_bgp_UsrDefined = "User Defined";
L7_char8 *pStrInfo_bgp_VpncosId = "VPNCOS ID";
L7_char8 *pStrInfo_bgp_Val_2 = "Value";
L7_char8 *pStrInfo_bgp_VerValInvalid = "Version value Invalid";
L7_char8 *pStrInfo_bgp_WithdrawEvent = "Withdraw Event";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4AddrAggregationCfg = "bgp4_address_aggregation_cfg.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4DampPathRo = "bgp4_damp_path_ro.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4GlobalAddrFamily = "bgp4_global_addr_family.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4GlobalCfg = "bgp4_global_cfg.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4GlobalClusterId = "bgp4_global_cluster_id.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4GlobalConfedId = "bgp4_global_confed_id.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4LocalNlriCfg = "bgp4_local_nlri_cfg.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4LocalOrig = "bgp4_local_orig.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4PathAttrCfgRo = "bgp4_path_attr_cfg_ro.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4PeerAddrFamily = "bgp4_peer_addr_family.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4PeerAuthCfg = "bgp4_peer_auth_cfg.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4PeerCfg = "bgp4_peer_cfg.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4PeerStats = "bgp4_peer_stats.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4PolicyActionCfg = "bgp4_policy_action_cfg.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4PolicyActionSelect = "bgp4_policy_action_select.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4PolicyCfg = "bgp4_policy_cfg.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4PolicyRangeCfg = "bgp4_policy_range_cfg.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4PolicyRangeSelect = "bgp4_policy_range_select.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4RouteFlapCfgRo = "bgp4_route_flap_cfg_ro.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4RouteFlapCfgRw = "bgp4_route_flap_cfg_rw.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4RouteTblRo = "bgp4_route_table_ro.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgp4SnpaCfg = "bgp4_snpa_cfg.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgpRtRdstrbtnCfgNew1 = "bgp_rt_rdstrbtn_cfg_new1.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgpRtRdstrbtnCfgNew2 = "bgp_rt_rdstrbtn_cfg_new2.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgpRtRdstrbtnCfgOld1 = "bgp_rt_rdstrbtn_cfg_old1.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgpRtRdstrbtnCfgOld2 = "bgp_rt_rdstrbtn_cfg_old2.html";
L7_char8 *pStrInfo_bgp_HtmlFileBgpRtRdstrbtnSumm = "bgp_rt_rdstrbtn_summ.html";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpBgpRtRdstrbtnCfg = "href=\"/bgp/help_bgp.html#bgp_rt_rdstrbtn_cfg\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpBgpRtRdstrbtnSumm = "href=\"/bgp/help_bgp.html#bgp_rt_rdstrbtn_summ\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpBgpaddraggrcfg = "href=\"/bgp/help_bgp.html#bgpaddraggrcfg\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpBgpdamppaths = "href=\"/bgp/help_bgp.html#bgpdamppaths\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpBgpglobalcfg = "href=\"/bgp/help_bgp.html#bgpglobalcfg\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpBgplocalcfg = "href=\"/bgp/help_bgp.html#bgplocalcfg\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpBgpnlricfg = "href=\"/bgp/help_bgp.html#bgpnlricfg\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpBgppathattrtable = "href=\"/bgp/help_bgp.html#bgppathattrtable\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpBgppeercfg = "href=\"/bgp/help_bgp.html#bgppeercfg\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpBgppolicycfg = "href=\"/bgp/help_bgp.html#bgppolicycfg\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpBgpsnpacfg = "href=\"/bgp/help_bgp.html#bgpsnpacfg\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpPeerBgppeercfg = "href=\"/bgp/help_bgp_peer.html#bgppeercfg\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpPeerBgppeerparams = "href=\"/bgp/help_bgp_peer.html#bgppeerparams\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpPolicyBgppolicyactionconfig = "href=\"/bgp/help_bgp_policy.html#bgppolicyactionconfig\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpPolicyBgppolicyactionselection = "href=\"/bgp/help_bgp_policy.html#bgppolicyactionselection\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpPolicyBgppolicycfg = "href=\"/bgp/help_bgp_policy.html#bgppolicycfg\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpPolicyBgppolicyrangeconfig = "href=\"/bgp/help_bgp_policy.html#bgppolicyrangeconfig\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpPolicyBgppolicyrangeselection = "href=\"/bgp/help_bgp_policy.html#bgppolicyrangeselection\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpPolicyBgppolicysumm = "href=\"/bgp/help_bgp_policy.html#bgppolicysumm\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpRouteBgprouteflapcfg = "href=\"/bgp/help_bgp_route.html#bgprouteflapcfg\"";
L7_char8 *pStrInfo_bgp_HtmlLinkBgpHelpBgpRouteBgproutetable = "href=\"/bgp/help_bgp_route.html#bgproutetable\"";
L7_char8 *pStrInfo_bgp_RetrievingEntry = "retrieving entry.";
L7_char8 *pStrInfo_bgp_Sec = "sec";
L7_char8 *pStrInfo_bgp_HtmlFileBgpPolicySumm = "bgp4_policy_summary.html";
L7_char8 *pStrInfo_bgp_Key_Maxlength = "Max Length";



