/** \file dnx/swstate/auto_generated/access/multicast_access.h
 *
 * sw state functions declarations
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 */
/*
 * $Copyright: (c) 2018 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */

#ifndef __MULTICAST_ACCESS_H__
#define __MULTICAST_ACCESS_H__

#include <soc/dnxc/swstate/dnxc_sw_state_h_includes.h>
#include <soc/dnx/swstate/auto_generated/types/multicast_types.h>
#include <soc/dnxc/swstate/types/sw_state_res_mngr.h>
/*
 * TYPEDEFs
 */

/**
 * implemented by: multicast_db_is_init
 */
typedef int (*multicast_db_is_init_cb)(
    int unit, uint8 *is_init);

/**
 * implemented by: multicast_db_init
 */
typedef int (*multicast_db_init_cb)(
    int unit);

/**
 * implemented by: multicast_db_mcdb_set
 */
typedef int (*multicast_db_mcdb_set_cb)(
    int unit, sw_state_algo_res_t mcdb);

/**
 * implemented by: multicast_db_mcdb_get
 */
typedef int (*multicast_db_mcdb_get_cb)(
    int unit, sw_state_algo_res_t *mcdb);

/**
 * implemented by: multicast_db_mcdb_create
 */
typedef int (*multicast_db_mcdb_create_cb)(
    int unit, sw_state_algo_res_create_data_t * data, void *extra_arguments);

/**
 * implemented by: multicast_db_mcdb_allocate_single
 */
typedef int (*multicast_db_mcdb_allocate_single_cb)(
    int unit, uint32 flags, void *extra_arguments, int *element);

/**
 * implemented by: multicast_db_mcdb_allocate_several
 */
typedef int (*multicast_db_mcdb_allocate_several_cb)(
    int unit, uint32 flags, uint32 nof_elements, void *extra_arguments, int *element);

/**
 * implemented by: multicast_db_mcdb_free_single
 */
typedef int (*multicast_db_mcdb_free_single_cb)(
    int unit, int element);

/**
 * implemented by: multicast_db_mcdb_is_allocated
 */
typedef int (*multicast_db_mcdb_is_allocated_cb)(
    int unit, int element, uint8 *is_allocated);

/**
 * implemented by: multicast_db_mcdb_nof_free_elements_get
 */
typedef int (*multicast_db_mcdb_nof_free_elements_get_cb)(
    int unit, int *nof_free_elements);

/*
 * STRUCTs
 */

/**
 * This structure holds the access functions for the variable mcdb
 */
typedef struct {
    multicast_db_mcdb_set_cb set;
    multicast_db_mcdb_get_cb get;
    multicast_db_mcdb_create_cb create;
    multicast_db_mcdb_allocate_single_cb allocate_single;
    multicast_db_mcdb_allocate_several_cb allocate_several;
    multicast_db_mcdb_free_single_cb free_single;
    multicast_db_mcdb_is_allocated_cb is_allocated;
    multicast_db_mcdb_nof_free_elements_get_cb nof_free_elements_get;
} multicast_db_mcdb_cbs;

/**
 * This structure holds the access functions for the variable multicast_sw_state_t
 */
typedef struct {
    multicast_db_is_init_cb is_init;
    multicast_db_init_cb init;
    /**
     * Access struct for mcdb
     */
    multicast_db_mcdb_cbs mcdb;
} multicast_db_cbs;

/*
 * Global Variables
 */

/*
 * Global Variables
 */

extern multicast_db_cbs multicast_db;

#endif /* __MULTICAST_ACCESS_H__ */
