/** \file dnx/swstate/auto_generated/types/algo_bfd_types.h
 *
 * sw state types (structs/enums/typedefs)
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 */
/*
 * $Copyright: (c) 2018 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */

#ifndef __ALGO_BFD_TYPES_H__
#define __ALGO_BFD_TYPES_H__

#include <soc/dnxc/swstate/dnxc_sw_state_h_includes.h>
#include <bcm_int/dnx/algo/bfd/algo_bfd.h>
#include <soc/dnxc/swstate/types/sw_state_template_mngr.h>
/*
 * STRUCTs
 */

/**
 * BFD related sw state
 */
typedef struct {
    /**
     * BFD MEP OAMA Action
     */
    sw_state_algo_template_t bfd_oama_action;
    /**
     * BFD MEP OAMB Action
     */
    sw_state_algo_template_t bfd_oamb_action;
    /**
     * BFD DIP
     */
    sw_state_algo_template_t bfd_dip;
    /**
     * BFD Your-Discr Range
     */
    sw_state_algo_template_t bfd_tyour_discr_range;
    /**
     * BFD OAMP TX Rate
     */
    sw_state_algo_template_t bfd_oamp_tx_rate;
    /**
     * BFD OAMP Required Interval
     */
    sw_state_algo_template_t bfd_oamp_req_interval;
    /**
     * BFD OAMP My-Discr Range Start
     */
    sw_state_algo_template_t bfd_oamp_my_discr_range_start;
    /**
     * BFD OAMP TOS-TTL
     */
    sw_state_algo_template_t bfd_oamp_tos_ttl;
    /**
     * BFD OAMP IPv4 Source Addr
     */
    sw_state_algo_template_t bfd_oamp_ipv4_src_addr;
    /**
     * BFD OAMP UDP SPORT
     */
    sw_state_algo_template_t bfd_oamp_udp_sport;
    /**
     * BFD OAMP MPLS SPORT
     */
    sw_state_algo_template_t bfd_oamp_mpls_sport;
    /**
     * BFD OAMP single-hop TOS
     */
    sw_state_algo_template_t bfd_oamp_single_hop_tos;
} algo_bfd_sw_state_t;


#endif /* __ALGO_BFD_TYPES_H__ */
