# $Id: Makefile,v 1.1 2017/02/9 07:46:29 csm Exp $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dnx/field/tcam_access

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/soc/dnx

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxfieldtcamaccess

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

