# $Id: Makefile Broadcom SDK $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/appl/diag/esw/techsupport/xflow-macsec

include ${SDK}/make/Make.config

lib = libtsxflowmacsec

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
