#
# $Id: Makefile,v 1.4 2012/03/08 10:43:54 rsportas Exp $
# $Copyright: (c) 2005 Broadcom Corp.
# All Rights Reserved.$
#


LOCALDIR = src/appl/diag/dnx/kleap

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/soc/dnx/kleap

subdirs = auto_generated

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxkleap

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

