#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for dbal_init 
#


LOCALDIR = src/soc/dnx/dbal/dbal_init/

include ${SDK}/make/Make.config

subdirs := auto_generated

INCDIR += -I${SDK}/include/soc/dnx

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxdbal_dbalinit

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

