# $Id: Makefile,v 1.0 2019/07/19 shaurya Exp $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM FIELD AACL Library
#

LOCALDIR = src/bcm/esw/field_compression

include ${SDK}/make/Make.config

lib = libfieldcomp

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

