/*********************************************************************
*
* (C) Copyright Broadcom Corporation 2000-2007
*
**********************************************************************
*
* @filename   cnfgr_features.h
*
* @purpose    Defines component feature support
*
* @component  cnfgr
*
* @comments   Feature support for a component can be influenced by various
* @comments   things, such as hardware platform, operating system, etc.
* @comments   The Configurator evaluates these items and provides a 
* @comments   consistent support indication to the software applications.
*
* @create     06/07/2002
*
* @author     gpaussa
* @end
*
**********************************************************************/


/*************************************************************
                    
*************************************************************/

#ifndef INCLUDE_CNFGR_FEATURES
#define INCLUDE_CNFGR_FEATURES

#include "commdefs.h"
#include "acl_exports.h"
#include "cos_exports.h"
#include "diffserv_exports.h"
#include "iscsi_exports.h"

#ifdef CNFGR_FLEX_FEATURE_SUPPORT



/*****************************************************************************/
/*          Start of QOS ACL Component's Feature Support Definitions         */
/*                                                                           */

/*-------------------------------------------------------------------
 * Must define a separate 'Features' array for each known technology
 * defined in L7_BASE_TECHNOLOGY_TYPES_t (or use the general 'Full' 
 * list if the platform supports all ACL features)
 *
 * Only list the features that are supported for a particular technology.
 * Platforms that do not support ACL do not have a list here.
 *
 * The list of features is defined in L7_ACL_FEATURE_IDS_t
 *-------------------------------------------------------------------
 */

/* Bcm Strata platform feature support list */
static L7_uchar8  cnfgrQosAclFeaturesBcm[] =
{
  L7_ACL_FEATURE_SUPPORTED,
  L7_ACL_TYPE_MAC_FEATURE_ID,

  L7_ACL_RULE_MATCH_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_EVERY_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPTOS_FEATURE_ID,
  L7_ACL_RULE_MATCH_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_SUPPORTS_MASKING_FEATURE_ID,

  L7_ACL_RULE_MATCH_COS_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_ETYPE_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID_FEATURE_ID,

  L7_ACL_ASSIGN_QUEUE_FEATURE_ID,
  L7_ACL_REDIRECT_FEATURE_ID,
  L7_ACL_LOG_DENY_FEATURE_ID,

  L7_ACL_INTF_DIRECTION_INBOUND_FEATURE_ID,
  L7_ACL_INTF_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_INTF_MIXED_INBOUND_TYPE_ACL_FEATURE_ID,
  L7_ACL_PER_RULE_ACTIVATION_ID,
  L7_ACL_INTF_LAG_SUPPORT_FEATURE_ID,
};  /* end BcmStrata */

#define CNFGR_QOS_ACL_FEATURES_BCM_LIST_ENTRIES \
  sizeof(cnfgrQosAclFeaturesBcm) / sizeof(cnfgrQosAclFeaturesBcm[0])


/* BCM XGS3 - Helix (5630x) platform feature support list */
static L7_uchar8  cnfgrQosAclFeaturesBcmXgs3Helix[] =
{
  L7_ACL_FEATURE_SUPPORTED,
  L7_ACL_TYPE_MAC_FEATURE_ID,

  L7_ACL_RULE_MATCH_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_EVERY_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPTOS_FEATURE_ID,
  L7_ACL_RULE_MATCH_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_SUPPORTS_MASKING_FEATURE_ID,

  L7_ACL_RULE_MATCH_COS_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_ETYPE_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID_FEATURE_ID,

  L7_ACL_ASSIGN_QUEUE_FEATURE_ID,
  L7_ACL_MIRROR_FEATURE_ID,
  L7_ACL_LOG_DENY_FEATURE_ID,

  L7_ACL_INTF_DIRECTION_INBOUND_FEATURE_ID,
#if L7_FEAT_EGRESS_ACL_ON_IFP
  L7_ACL_INTF_DIRECTION_OUTBOUND_FEATURE_ID,
  L7_FEAT_EGRESS_ACL_ON_IFP_ID,
#endif
  L7_ACL_INTF_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_PER_RULE_ACTIVATION_ID,
  L7_ACL_INTF_LAG_SUPPORT_FEATURE_ID

};  /* end BCM XGS3 Helix */

#define CNFGR_QOS_ACL_FEATURES_XGS3_HELIX_LIST_ENTRIES \
  sizeof(cnfgrQosAclFeaturesBcmXgs3Helix) / sizeof(cnfgrQosAclFeaturesBcmXgs3Helix[0])

/* BCM XGS3 - HelixPlus (5631x) platform feature support list */
static L7_uchar8  cnfgrQosAclFeaturesBcmXgs3HelixPlus[] =
{
  L7_ACL_FEATURE_SUPPORTED,
  L7_ACL_TYPE_MAC_FEATURE_ID,
  L7_ACL_TYPE_IPV6_FEATURE_ID,             /* IPV6 ACL support statement */

  L7_ACL_RULE_MATCH_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_EVERY_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPTOS_FEATURE_ID,
  L7_ACL_RULE_MATCH_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_SUPPORTS_MASKING_FEATURE_ID,

  L7_ACL_RULE_MATCH_COS_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_ETYPE_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID_FEATURE_ID,

  L7_ACL_RULE_MATCH_IPV6_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_SRCL4PORT_FEATURE_ID,

  L7_ACL_ASSIGN_QUEUE_FEATURE_ID,
  L7_ACL_REDIRECT_FEATURE_ID,
  L7_ACL_MIRROR_FEATURE_ID,
  L7_ACL_LOG_DENY_FEATURE_ID,

  L7_ACL_INTF_DIRECTION_INBOUND_FEATURE_ID,
#if L7_FEAT_EGRESS_ACL_ON_IFP
  L7_ACL_INTF_DIRECTION_OUTBOUND_FEATURE_ID,
  L7_FEAT_EGRESS_ACL_ON_IFP_ID,
#endif
  L7_ACL_INTF_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_INTF_MIXED_INBOUND_TYPE_ACL_FEATURE_ID,
  L7_ACL_INTF_LAG_SUPPORT_FEATURE_ID,

  L7_ACL_INTF_VLAN_SUPPORT_FEATURE_ID,     /* allow binding of ACLs to VLAN IDs */
  L7_ACL_VLAN_DIRECTION_INBOUND_FEATURE_ID,
  L7_ACL_VLAN_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_PER_RULE_ACTIVATION_ID,
  L7_ACL_VLAN_MIXED_INBOUND_TYPE_ACL_FEATURE_ID   /* use for IPv4 vs. L2 MAC combo */

};  /* end BCM XGS3 HelixPlus */

#define CNFGR_QOS_ACL_FEATURES_XGS3_HELIXPLUS_LIST_ENTRIES \
  sizeof(cnfgrQosAclFeaturesBcmXgs3HelixPlus) / sizeof(cnfgrQosAclFeaturesBcmXgs3HelixPlus[0])

/* BCM XGS3 - Firebolt (5650x) platform feature support list */
static L7_uchar8  cnfgrQosAclFeaturesBcmXgs3Firebolt[] =
{
  L7_ACL_FEATURE_SUPPORTED,
  L7_ACL_TYPE_MAC_FEATURE_ID,
  L7_ACL_TYPE_IPV6_FEATURE_ID,             /* IPV6 ACL support statement */

  L7_ACL_RULE_MATCH_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_EVERY_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPTOS_FEATURE_ID,
  L7_ACL_RULE_MATCH_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_SUPPORTS_MASKING_FEATURE_ID,

  L7_ACL_RULE_MATCH_COS_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_ETYPE_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID_FEATURE_ID,

  L7_ACL_RULE_MATCH_IPV6_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_SRCL4PORT_FEATURE_ID,

  L7_ACL_ASSIGN_QUEUE_FEATURE_ID,
  L7_ACL_REDIRECT_FEATURE_ID,
  L7_ACL_MIRROR_FEATURE_ID,
  L7_ACL_LOG_DENY_FEATURE_ID,

  L7_ACL_INTF_DIRECTION_INBOUND_FEATURE_ID,
#if L7_FEAT_EGRESS_ACL_ON_IFP
  L7_ACL_INTF_DIRECTION_OUTBOUND_FEATURE_ID,
  L7_FEAT_EGRESS_ACL_ON_IFP_ID,
#endif
  L7_ACL_INTF_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_INTF_MIXED_INBOUND_TYPE_ACL_FEATURE_ID,
  L7_ACL_INTF_MIXED_INBOUND_IPV6_IPV4_FEATURE_ID,
  L7_ACL_INTF_LAG_SUPPORT_FEATURE_ID,

  L7_ACL_INTF_VLAN_SUPPORT_FEATURE_ID,     /* allow binding of ACLs to VLAN IDs */
  L7_ACL_VLAN_DIRECTION_INBOUND_FEATURE_ID,
  L7_ACL_VLAN_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_VLAN_MIXED_INBOUND_TYPE_ACL_FEATURE_ID,   /* use for IPv4 vs. L2 MAC combo */
  L7_ACL_VLAN_MIXED_INBOUND_IPV6_IPV4_FEATURE_ID,   /* use for IPv6 vs. IPv4 combo   */
  L7_ACL_PER_RULE_ACTIVATION_ID,

};  /* end BCM XGS3 Firebolt */

#define CNFGR_QOS_ACL_FEATURES_XGS3_FIREBOLT_LIST_ENTRIES \
  sizeof(cnfgrQosAclFeaturesBcmXgs3Firebolt) / sizeof(cnfgrQosAclFeaturesBcmXgs3Firebolt[0])

/* BCM XGS3 - Firebolt2 (5651x) platform feature support list */
static L7_uchar8  cnfgrQosAclFeaturesBcmXgs3Firebolt2[] =
{
  L7_ACL_FEATURE_SUPPORTED,
  L7_ACL_TYPE_MAC_FEATURE_ID,
  L7_ACL_TYPE_IPV6_FEATURE_ID,             /* IPV6 ACL support statement */

  L7_ACL_RULE_MATCH_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_EVERY_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPTOS_FEATURE_ID,
  L7_ACL_RULE_MATCH_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_SUPPORTS_MASKING_FEATURE_ID,

  L7_ACL_RULE_MATCH_COS_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_ETYPE_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID_FEATURE_ID,

  L7_ACL_RULE_MATCH_IPV6_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_SRCL4PORT_FEATURE_ID,

  L7_ACL_ASSIGN_QUEUE_FEATURE_ID,
  L7_ACL_REDIRECT_FEATURE_ID,
  L7_ACL_MIRROR_FEATURE_ID,
  L7_ACL_LOG_DENY_FEATURE_ID,

  L7_ACL_INTF_DIRECTION_INBOUND_FEATURE_ID,
  L7_ACL_INTF_DIRECTION_OUTBOUND_FEATURE_ID,
  L7_ACL_INTF_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_INTF_MIXED_INBOUND_TYPE_ACL_FEATURE_ID,
  L7_ACL_INTF_MIXED_INBOUND_IPV6_IPV4_FEATURE_ID,
  L7_ACL_INTF_MIXED_OUTBOUND_IPV6_IPV4_FEATURE_ID,
  L7_ACL_INTF_LAG_SUPPORT_FEATURE_ID,

  L7_ACL_INTF_VLAN_SUPPORT_FEATURE_ID,     /* allow binding of ACLs to VLAN IDs */
  L7_ACL_VLAN_DIRECTION_INBOUND_FEATURE_ID,
  L7_ACL_VLAN_DIRECTION_OUTBOUND_FEATURE_ID,
  L7_ACL_VLAN_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_VLAN_MIXED_INBOUND_TYPE_ACL_FEATURE_ID,   /* use for IPv4 vs. L2 MAC combo */
  L7_ACL_VLAN_MIXED_INBOUND_IPV6_IPV4_FEATURE_ID,   /* use for IPv6 vs. IPv4 combo   */
  L7_ACL_VLAN_MIXED_OUTBOUND_IPV6_IPV4_FEATURE_ID,   /* use for IPv6 vs. IPv4 combo   */
  L7_ACL_PER_RULE_ACTIVATION_ID,
};  /* end BCM XGS3 Firebolt2 */

#define CNFGR_QOS_ACL_FEATURES_XGS3_FIREBOLT2_LIST_ENTRIES \
  sizeof(cnfgrQosAclFeaturesBcmXgs3Firebolt2) / sizeof(cnfgrQosAclFeaturesBcmXgs3Firebolt2[0])

/* BCM XGS4 - Triumph/Scorpion platform feature support list */
static L7_uchar8  cnfgrQosAclFeaturesBcmXgs4[] =
{
  L7_ACL_FEATURE_SUPPORTED,
  L7_ACL_TYPE_MAC_FEATURE_ID,
  L7_ACL_TYPE_IPV6_FEATURE_ID,             /* IPV6 ACL support statement */

  L7_ACL_RULE_MATCH_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_EVERY_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPTOS_FEATURE_ID,
  L7_ACL_RULE_MATCH_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_SUPPORTS_MASKING_FEATURE_ID,

  L7_ACL_RULE_MATCH_COS_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_ETYPE_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID_FEATURE_ID,

  L7_ACL_RULE_MATCH_IPV6_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_SRCL4PORT_FEATURE_ID,

  L7_ACL_ASSIGN_QUEUE_FEATURE_ID,
  L7_ACL_REDIRECT_FEATURE_ID,
  L7_ACL_MIRROR_FEATURE_ID,
  L7_ACL_LOG_DENY_FEATURE_ID,

  L7_ACL_INTF_DIRECTION_INBOUND_FEATURE_ID,
  L7_ACL_INTF_DIRECTION_OUTBOUND_FEATURE_ID,
  L7_ACL_INTF_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_INTF_MIXED_INBOUND_TYPE_ACL_FEATURE_ID,
  L7_ACL_INTF_MIXED_INBOUND_IPV6_IPV4_FEATURE_ID,
  L7_ACL_INTF_MIXED_OUTBOUND_IPV6_IPV4_FEATURE_ID,
  L7_ACL_INTF_LAG_SUPPORT_FEATURE_ID,

  L7_ACL_INTF_VLAN_SUPPORT_FEATURE_ID,     /* allow binding of ACLs to VLAN IDs */
  L7_ACL_VLAN_DIRECTION_INBOUND_FEATURE_ID,
  L7_ACL_VLAN_DIRECTION_OUTBOUND_FEATURE_ID,
  L7_ACL_VLAN_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_VLAN_MIXED_INBOUND_TYPE_ACL_FEATURE_ID,   /* use for IPv4 vs. L2 MAC combo */
  L7_ACL_VLAN_MIXED_INBOUND_IPV6_IPV4_FEATURE_ID,   /* use for IPv6 vs. IPv4 combo   */
  L7_ACL_VLAN_MIXED_OUTBOUND_IPV6_IPV4_FEATURE_ID,   /* use for IPv6 vs. IPv4 combo   */
  L7_ACL_PER_RULE_ACTIVATION_ID,
};  /* end BCM XGS4 */

#define CNFGR_QOS_ACL_FEATURES_XGS4_LIST_ENTRIES \
  sizeof(cnfgrQosAclFeaturesBcmXgs4) / sizeof(cnfgrQosAclFeaturesBcmXgs4[0])

/* BCM ROBO 53xx platform feature support list */
static L7_uchar8  cnfgrQosAclFeaturesBcmRobo53xx[] =
{
  L7_ACL_FEATURE_SUPPORTED,
  L7_ACL_TYPE_MAC_FEATURE_ID,

  L7_ACL_RULE_MATCH_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_EVERY_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPTOS_FEATURE_ID,
  L7_ACL_RULE_MATCH_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_SUPPORTS_MASKING_FEATURE_ID,

  L7_ACL_RULE_MATCH_COS_FEATURE_ID,
  L7_ACL_RULE_MATCH_COS2_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_ETYPE_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID2_FEATURE_ID,

  L7_ACL_ASSIGN_QUEUE_FEATURE_ID,
  L7_ACL_REDIRECT_FEATURE_ID,
  L7_ACL_LOG_DENY_FEATURE_ID,

  L7_ACL_INTF_DIRECTION_INBOUND_FEATURE_ID,
  L7_ACL_INTF_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_INTF_LAG_SUPPORT_FEATURE_ID,
  L7_ACL_PER_RULE_ACTIVATION_ID,
  
};  /* end BCM ROBO 53xx */

#define CNFGR_QOS_ACL_FEATURES_ROBO_53xx_LIST_ENTRIES \
  sizeof(cnfgrQosAclFeaturesBcmRobo53xx) / sizeof(cnfgrQosAclFeaturesBcmRobo53xx[0])

/* BCM XGS3 - Raptor (562xx, 5371x) platform feature support list for Enterprise product. */
static L7_uchar8  cnfgrQosAclFeaturesBcmXgs3RaptorEnterprise[] =
{
  L7_ACL_FEATURE_SUPPORTED,
  L7_ACL_TYPE_MAC_FEATURE_ID,

  L7_ACL_RULE_MATCH_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_EVERY_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPTOS_FEATURE_ID,
  L7_ACL_RULE_MATCH_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_SUPPORTS_MASKING_FEATURE_ID,

  L7_ACL_RULE_MATCH_COS_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_ETYPE_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID_FEATURE_ID,

  L7_ACL_ASSIGN_QUEUE_FEATURE_ID,
  L7_ACL_REDIRECT_FEATURE_ID,
  L7_ACL_MIRROR_FEATURE_ID,
  L7_ACL_LOG_DENY_FEATURE_ID,

  L7_ACL_INTF_DIRECTION_INBOUND_FEATURE_ID,
  L7_ACL_INTF_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_INTF_LAG_SUPPORT_FEATURE_ID,
  L7_ACL_INTF_MIXED_INBOUND_TYPE_ACL_FEATURE_ID,

  L7_ACL_INTF_VLAN_SUPPORT_FEATURE_ID,     /* allow binding of ACLs to VLAN IDs */
  L7_ACL_VLAN_DIRECTION_INBOUND_FEATURE_ID,
  L7_ACL_VLAN_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_VLAN_MIXED_INBOUND_TYPE_ACL_FEATURE_ID,   /* use for IPv4 vs. L2 MAC combo */
  L7_ACL_PER_RULE_ACTIVATION_ID,

};  /* end BCM XGS3 Raptor */

#define CNFGR_QOS_ACL_FEATURES_XGS3_RAPTOR_ENTERPRISE_LIST_ENTRIES \
  sizeof(cnfgrQosAclFeaturesBcmXgs3RaptorEnterprise) / sizeof(cnfgrQosAclFeaturesBcmXgs3RaptorEnterprise[0])


/* Full platform feature support list */
static L7_uchar8  cnfgrQosAclFeaturesFull[] =
{
  L7_ACL_FEATURE_SUPPORTED,
  L7_ACL_TYPE_MAC_FEATURE_ID,
  L7_ACL_TYPE_IPV6_FEATURE_ID,             /* IPV6 ACL support statement */

  L7_ACL_RULE_MATCH_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTL4PORT_RANGE_FEATURE_ID,
  L7_ACL_RULE_MATCH_EVERY_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPTOS_FEATURE_ID,
  L7_ACL_RULE_MATCH_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCL4PORT_RANGE_FEATURE_ID,
  L7_ACL_RULE_MATCH_SUPPORTS_MASKING_FEATURE_ID,

  L7_ACL_RULE_MATCH_IPV6_DSTIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_DSTL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_DSTL4PORT_RANGE_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_IPDSCP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_PROTOCOL_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_SRCIP_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_SRCL4PORT_FEATURE_ID,
  L7_ACL_RULE_MATCH_IPV6_SRCL4PORT_RANGE_FEATURE_ID,

  L7_ACL_RULE_MATCH_COS_FEATURE_ID,
  L7_ACL_RULE_MATCH_COS2_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_DSTMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_ETYPE_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_FEATURE_ID,
  L7_ACL_RULE_MATCH_SRCMAC_MASK_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID_RANGE_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID2_FEATURE_ID,
  L7_ACL_RULE_MATCH_VLANID2_RANGE_FEATURE_ID,

  L7_ACL_ASSIGN_QUEUE_FEATURE_ID,
  L7_ACL_REDIRECT_FEATURE_ID,
  L7_ACL_MIRROR_FEATURE_ID,
  L7_ACL_LOG_DENY_FEATURE_ID,
  L7_ACL_LOG_PERMIT_FEATURE_ID,

  L7_ACL_INTF_DIRECTION_INBOUND_FEATURE_ID,
  L7_ACL_INTF_DIRECTION_OUTBOUND_FEATURE_ID,
  L7_ACL_INTF_DIFFSERV_COEXIST_FEATURE_ID,
  L7_ACL_INTF_LAG_SUPPORT_FEATURE_ID,
  L7_ACL_INTF_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_INTF_MIXED_INBOUND_TYPE_ACL_FEATURE_ID,
  L7_ACL_INTF_MIXED_INBOUND_IPV6_MAC_FEATURE_ID,
  L7_ACL_INTF_MIXED_INBOUND_IPV6_IPV4_FEATURE_ID,
  L7_ACL_INTF_MIXED_OUTBOUND_TYPE_ACL_FEATURE_ID,   /* use for IPv4 vs. L2 MAC combo */
  L7_ACL_INTF_MIXED_OUTBOUND_IPV6_MAC_FEATURE_ID,   /* use for IPv6 vs. L2 MAC combo */
  L7_ACL_INTF_MIXED_OUTBOUND_IPV6_IPV4_FEATURE_ID,  /* use for IPv6 vs. IPv4 combo   */

  L7_ACL_INTF_VLAN_SUPPORT_FEATURE_ID,     /* allow binding of ACLs to VLAN IDs */
  L7_ACL_VLAN_DIRECTION_INBOUND_FEATURE_ID,
  L7_ACL_VLAN_DIRECTION_OUTBOUND_FEATURE_ID,
  L7_ACL_VLAN_MULTIPLE_ACL_FEATURE_ID,
  L7_ACL_VLAN_MIXED_INBOUND_TYPE_ACL_FEATURE_ID,   /* use for IPv4 vs. L2 MAC combo */
  L7_ACL_VLAN_MIXED_INBOUND_IPV6_MAC_FEATURE_ID,   /* use for IPv6 vs. L2 MAC combo */
  L7_ACL_VLAN_MIXED_INBOUND_IPV6_IPV4_FEATURE_ID,  /* use for IPv6 vs. IPv4 combo   */
  L7_ACL_VLAN_MIXED_OUTBOUND_TYPE_ACL_FEATURE_ID,   /* use for IPv4 vs. L2 MAC combo */
  L7_ACL_VLAN_MIXED_OUTBOUND_IPV6_MAC_FEATURE_ID,   /* use for IPv6 vs. L2 MAC combo */
  L7_ACL_VLAN_MIXED_OUTBOUND_IPV6_IPV4_FEATURE_ID,  /* use for IPv6 vs. IPv4 combo   */
  L7_ACL_PER_RULE_ACTIVATION_ID,                     

};  /* end Full */

#define CNFGR_QOS_ACL_FEATURES_FULL_LIST_ENTRIES \
  sizeof(cnfgrQosAclFeaturesFull) / sizeof(cnfgrQosAclFeaturesFull[0])

/*                                                                           */
/*          End of QOS ACL Component's Feature Support Definitions           */
/*****************************************************************************/


 


/*****************************************************************************/
/*      Start of QOS DIFFSERV Component's Feature Support Definitions        */
/*                                                                           */

/*-------------------------------------------------------------------
 * Must define a separate 'Features' array for each known technology
 * defined in L7_BASE_TECHNOLOGY_TYPES_t (or use the general 'Full' 
 * list if the platform supports all DiffServ features)
 *
 * Only list the features that are supported for a particular technology.
 * Platforms that do not support DiffServ do not have a list here.
 *
 * The list of features is defined in L7_DIFFSERV_FEATURE_IDS_t
 *-------------------------------------------------------------------
 */

/* Bcm Strata platform feature support list */
static L7_uchar8  cnfgrQosDiffServFeaturesBcmStrata[] =
{
  L7_DIFFSERV_FEATURE_SUPPORTED, 
  
  L7_DIFFSERV_CLASS_TYPE_ALL_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_MATCH_COS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_ETYPE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_EVERY_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPTOS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_PROTOCOL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_REFCLASS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_VLANID_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SUPPORTS_MASKING_FEATURE_ID,
  
  L7_DIFFSERV_POLICY_ATTR_ASSIGN_QUEUE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_DROP_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COSVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPDSCPVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPPRECEDENCEVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_SIMPLE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_COLORAWARE_FEATURE_ID,
  
  L7_DIFFSERV_SERVICE_IN_SLOTPORT_FEATURE_ID,

  L7_DIFFSERV_PHB_EF_FEATURE_ID,
  L7_DIFFSERV_PHB_AF4X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF3X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF2X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF1X_FEATURE_ID,
  L7_DIFFSERV_PHB_CS_FEATURE_ID
};  /* end BcmStrata */

#define CNFGR_QOS_DIFFSERV_FEATURES_STRATA_LIST_ENTRIES \
  sizeof(cnfgrQosDiffServFeaturesBcmStrata) / sizeof(cnfgrQosDiffServFeaturesBcmStrata[0])


/* Bcm Xgs platform feature support list */
static L7_uchar8  cnfgrQosDiffServFeaturesBcmXgs[] =
{
  L7_DIFFSERV_FEATURE_SUPPORTED, 
  
  L7_DIFFSERV_CLASS_TYPE_ALL_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_MATCH_COS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_ETYPE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_EVERY_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPTOS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_PROTOCOL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_REFCLASS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_VLANID_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SUPPORTS_MASKING_FEATURE_ID,
  
  L7_DIFFSERV_POLICY_ATTR_ASSIGN_QUEUE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_DROP_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COSVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPDSCPVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPPRECEDENCEVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_SIMPLE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_COLORAWARE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_REDIRECT_FEATURE_ID,
  
  L7_DIFFSERV_SERVICE_IN_SLOTPORT_FEATURE_ID,
  L7_DIFFSERV_SERVICE_IN_ALLPORTS_FEATURE_ID,
  L7_DIFFSERV_SERVICE_SUPPORTS_LAG_INTF_FEATURE_ID,

  L7_DIFFSERV_PHB_EF_FEATURE_ID,
  L7_DIFFSERV_PHB_AF4X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF3X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF2X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF1X_FEATURE_ID,
  L7_DIFFSERV_PHB_CS_FEATURE_ID
};  /* end BcmXgs */

#define CNFGR_QOS_DIFFSERV_FEATURES_XGS_LIST_ENTRIES \
  sizeof(cnfgrQosDiffServFeaturesBcmXgs) / sizeof(cnfgrQosDiffServFeaturesBcmXgs[0])

/* BCM XGS3 - Helix (5630x) platform feature support list */
static L7_uchar8  cnfgrQosDiffServFeaturesBcmXgs3Helix[] =
{
  L7_DIFFSERV_FEATURE_SUPPORTED, 
  
  L7_DIFFSERV_CLASS_TYPE_ALL_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_L3PROTO_IPV4_FEATURE_ID,

  L7_DIFFSERV_CLASS_MATCH_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_EVERY_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPTOS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_PROTOCOL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_REFCLASS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SUPPORTS_MASKING_FEATURE_ID,
  
  L7_DIFFSERV_POLICY_ATTR_ASSIGN_QUEUE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_DROP_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COSVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPDSCPVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPPRECEDENCEVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MIRROR_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_SIMPLE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_COLORAWARE_FEATURE_ID,

  L7_DIFFSERV_SERVICE_IN_SLOTPORT_FEATURE_ID,
  L7_DIFFSERV_SERVICE_IN_ALLPORTS_FEATURE_ID,
  L7_DIFFSERV_SERVICE_SUPPORTS_LAG_INTF_FEATURE_ID,

  L7_DIFFSERV_PHB_EF_FEATURE_ID,
  L7_DIFFSERV_PHB_AF4X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF3X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF2X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF1X_FEATURE_ID,
  L7_DIFFSERV_PHB_CS_FEATURE_ID
};  /* end BCM XGS3 - Helix */

#define CNFGR_QOS_DIFFSERV_FEATURES_XGS3_HELIX_LIST_ENTRIES \
  sizeof(cnfgrQosDiffServFeaturesBcmXgs3Helix) / sizeof(cnfgrQosDiffServFeaturesBcmXgs3Helix[0])

/* BCM XGS3 - HelixPlus (5631x) platform feature support list */
static L7_uchar8  cnfgrQosDiffServFeaturesBcmXgs3HelixPlus[] =
{
  L7_DIFFSERV_FEATURE_SUPPORTED, 
  
  L7_DIFFSERV_CLASS_TYPE_ALL_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_L3PROTO_IPV4_FEATURE_ID,
  L7_DIFFSERV_CLASS_L3PROTO_IPV6_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_MATCH_COS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_ETYPE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_EVERY_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPTOS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_PROTOCOL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_REFCLASS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_VLANID_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SUPPORTS_MASKING_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_PROTOCOL_FEATURE_ID, 
  L7_DIFFSERV_CLASS_MATCH_IPV6_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_SRCL4PORT_FEATURE_ID,
  
  L7_DIFFSERV_POLICY_ATTR_ASSIGN_QUEUE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_DROP_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COSVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPDSCPVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPPRECEDENCEVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MIRROR_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_REDIRECT_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_SIMPLE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_COLORAWARE_FEATURE_ID,

  L7_DIFFSERV_SERVICE_IN_SLOTPORT_FEATURE_ID,
  L7_DIFFSERV_SERVICE_IN_ALLPORTS_FEATURE_ID,
  L7_DIFFSERV_SERVICE_SUPPORTS_LAG_INTF_FEATURE_ID,

  L7_DIFFSERV_PHB_EF_FEATURE_ID,
  L7_DIFFSERV_PHB_AF4X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF3X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF2X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF1X_FEATURE_ID,
  L7_DIFFSERV_PHB_CS_FEATURE_ID
};  /* end BCM XGS3 - HelixPlus */

#define CNFGR_QOS_DIFFSERV_FEATURES_XGS3_HELIXPLUS_LIST_ENTRIES \
  sizeof(cnfgrQosDiffServFeaturesBcmXgs3HelixPlus) / sizeof(cnfgrQosDiffServFeaturesBcmXgs3HelixPlus[0])

/* BCM XGS3 - Firebolt (5650x) platform feature support list */
static L7_uchar8  cnfgrQosDiffServFeaturesBcmXgs3Firebolt[] =
{
  L7_DIFFSERV_FEATURE_SUPPORTED, 
  
  L7_DIFFSERV_CLASS_TYPE_ALL_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_L3PROTO_IPV4_FEATURE_ID,
  L7_DIFFSERV_CLASS_L3PROTO_IPV6_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_MATCH_COS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_ETYPE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_EVERY_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPTOS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_PROTOCOL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_REFCLASS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_VLANID_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SUPPORTS_MASKING_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_PROTOCOL_FEATURE_ID, 
  L7_DIFFSERV_CLASS_MATCH_IPV6_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_SRCL4PORT_FEATURE_ID,
  
  L7_DIFFSERV_POLICY_ATTR_ASSIGN_QUEUE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_DROP_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COSVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPDSCPVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPPRECEDENCEVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MIRROR_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_REDIRECT_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_SIMPLE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_COLORAWARE_FEATURE_ID,

  L7_DIFFSERV_SERVICE_IN_SLOTPORT_FEATURE_ID,
  L7_DIFFSERV_SERVICE_IN_ALLPORTS_FEATURE_ID,
  L7_DIFFSERV_SERVICE_SUPPORTS_LAG_INTF_FEATURE_ID,

  L7_DIFFSERV_PHB_EF_FEATURE_ID,
  L7_DIFFSERV_PHB_AF4X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF3X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF2X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF1X_FEATURE_ID,
  L7_DIFFSERV_PHB_CS_FEATURE_ID
};  /* end BCM XGS3 - Firebolt */

#define CNFGR_QOS_DIFFSERV_FEATURES_XGS3_FIREBOLT_LIST_ENTRIES \
  sizeof(cnfgrQosDiffServFeaturesBcmXgs3Firebolt) / sizeof(cnfgrQosDiffServFeaturesBcmXgs3Firebolt[0])

/* BCM XGS3 - Raptor (562xx, 5371x) platform feature support list for Enterprise product. */
static L7_uchar8  cnfgrQosDiffServFeaturesBcmXgs3Raptor[] =
{
  L7_DIFFSERV_FEATURE_SUPPORTED, 
  
  L7_DIFFSERV_CLASS_TYPE_ALL_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_L3PROTO_IPV4_FEATURE_ID,

  L7_DIFFSERV_CLASS_MATCH_COS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_ETYPE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_EVERY_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPTOS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_PROTOCOL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_REFCLASS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_VLANID_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SUPPORTS_MASKING_FEATURE_ID,
  
  L7_DIFFSERV_POLICY_ATTR_ASSIGN_QUEUE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_DROP_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COSVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPDSCPVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPPRECEDENCEVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MIRROR_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_REDIRECT_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_SIMPLE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_COLORAWARE_FEATURE_ID,

  L7_DIFFSERV_SERVICE_IN_SLOTPORT_FEATURE_ID,
  L7_DIFFSERV_SERVICE_IN_ALLPORTS_FEATURE_ID,
  L7_DIFFSERV_SERVICE_SUPPORTS_LAG_INTF_FEATURE_ID,

  L7_DIFFSERV_PHB_EF_FEATURE_ID,
  L7_DIFFSERV_PHB_AF4X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF3X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF2X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF1X_FEATURE_ID,
  L7_DIFFSERV_PHB_CS_FEATURE_ID

};  /* end BCM XGS3 - Raptor */

#define CNFGR_QOS_DIFFSERV_FEATURES_XGS3_RAPTOR_LIST_ENTRIES \
  sizeof(cnfgrQosDiffServFeaturesBcmXgs3Raptor) / sizeof(cnfgrQosDiffServFeaturesBcmXgs3Raptor[0])


/* BCM ROBO - 53xx platform feature support list */
static L7_uchar8  cnfgrQosDiffServFeaturesBcmRobo53xx[] =
{
  L7_DIFFSERV_FEATURE_SUPPORTED,

  L7_DIFFSERV_CLASS_TYPE_ALL_FEATURE_ID,

  L7_DIFFSERV_CLASS_L3PROTO_IPV4_FEATURE_ID,

  L7_DIFFSERV_CLASS_MATCH_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_EVERY_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPTOS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_PROTOCOL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_REFCLASS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_COS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_COS2_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_VLANID_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_VLANID2_FEATURE_ID,

  L7_DIFFSERV_CLASS_MATCH_SUPPORTS_MASKING_FEATURE_ID,

  L7_DIFFSERV_POLICY_ATTR_ASSIGN_QUEUE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_DROP_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COSVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPDSCPVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPPRECEDENCEVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_SIMPLE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_COLORAWARE_FEATURE_ID,

  L7_DIFFSERV_SERVICE_IN_SLOTPORT_FEATURE_ID,
  L7_DIFFSERV_SERVICE_IN_ALLPORTS_FEATURE_ID,
  L7_DIFFSERV_SERVICE_SUPPORTS_LAG_INTF_FEATURE_ID,

  L7_DIFFSERV_PHB_EF_FEATURE_ID,
  L7_DIFFSERV_PHB_AF4X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF3X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF2X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF1X_FEATURE_ID,
  L7_DIFFSERV_PHB_CS_FEATURE_ID
};  /* end BCM ROBO - 53xx */

#define CNFGR_QOS_DIFFSERV_FEATURES_ROBO_53xx_LIST_ENTRIES \
  sizeof(cnfgrQosDiffServFeaturesBcmRobo53xx) / sizeof(cnfgrQosDiffServFeaturesBcmRobo53xx[0])

/* BCM XGS3 - Firebolt2 (5651x) platform feature support list */
static L7_uchar8  cnfgrQosDiffServFeaturesBcmXgs3Firebolt2[] =
{
  L7_DIFFSERV_FEATURE_SUPPORTED, 
  
  L7_DIFFSERV_CLASS_TYPE_ALL_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_L3PROTO_IPV4_FEATURE_ID,
  L7_DIFFSERV_CLASS_L3PROTO_IPV6_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_MATCH_COS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_ETYPE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_EVERY_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPTOS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_PROTOCOL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_REFCLASS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_VLANID_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SUPPORTS_MASKING_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_PROTOCOL_FEATURE_ID, 
  L7_DIFFSERV_CLASS_MATCH_IPV6_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_SRCL4PORT_FEATURE_ID,
  
  L7_DIFFSERV_POLICY_ATTR_ASSIGN_QUEUE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_DROP_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COSVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPDSCPVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPPRECEDENCEVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MIRROR_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_REDIRECT_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_SIMPLE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_COLORAWARE_FEATURE_ID,

  L7_DIFFSERV_POLICY_OUT_CLASS_UNRESTRICTED_FEATURE_ID,

  L7_DIFFSERV_SERVICE_IN_SLOTPORT_FEATURE_ID,
  L7_DIFFSERV_SERVICE_IN_ALLPORTS_FEATURE_ID,
  L7_DIFFSERV_SERVICE_OUT_SLOTPORT_FEATURE_ID,
  L7_DIFFSERV_SERVICE_OUT_ALLPORTS_FEATURE_ID,
  L7_DIFFSERV_SERVICE_SUPPORTS_LAG_INTF_FEATURE_ID,

  L7_DIFFSERV_PHB_EF_FEATURE_ID,
  L7_DIFFSERV_PHB_AF4X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF3X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF2X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF1X_FEATURE_ID,
  L7_DIFFSERV_PHB_CS_FEATURE_ID
};  /* end BCM XGS3 - Firebolt2 */

#define CNFGR_QOS_DIFFSERV_FEATURES_XGS3_FIREBOLT2_LIST_ENTRIES \
  sizeof(cnfgrQosDiffServFeaturesBcmXgs3Firebolt2) / sizeof(cnfgrQosDiffServFeaturesBcmXgs3Firebolt2[0])

/* BCM XGS4 - Triumph/Scorpion platform feature support list */
static L7_uchar8  cnfgrQosDiffServFeaturesBcmXgs4[] =
{
  L7_DIFFSERV_FEATURE_SUPPORTED, 
  
  L7_DIFFSERV_CLASS_TYPE_ALL_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_L3PROTO_IPV4_FEATURE_ID,
  L7_DIFFSERV_CLASS_L3PROTO_IPV6_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_MATCH_COS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_COS2_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_ETYPE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_EVERY_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPTOS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_PROTOCOL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_REFCLASS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_VLANID_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_VLANID2_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SUPPORTS_MASKING_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_PROTOCOL_FEATURE_ID, 
  L7_DIFFSERV_CLASS_MATCH_IPV6_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_SRCL4PORT_FEATURE_ID,
  
  L7_DIFFSERV_POLICY_ATTR_ASSIGN_QUEUE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_DROP_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COSVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COSASCOS2_FEATURE_ID,  
  L7_DIFFSERV_POLICY_ATTR_MARK_IPDSCPVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPPRECEDENCEVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MIRROR_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_REDIRECT_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_SIMPLE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_TWORATE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_COLORAWARE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COS_POLICE_ACTION_FEATURE_ID,

  L7_DIFFSERV_POLICY_OUT_CLASS_UNRESTRICTED_FEATURE_ID,

  L7_DIFFSERV_SERVICE_IN_SLOTPORT_FEATURE_ID,
  L7_DIFFSERV_SERVICE_IN_ALLPORTS_FEATURE_ID,
  L7_DIFFSERV_SERVICE_OUT_SLOTPORT_FEATURE_ID,
  L7_DIFFSERV_SERVICE_OUT_ALLPORTS_FEATURE_ID,
  L7_DIFFSERV_SERVICE_SUPPORTS_LAG_INTF_FEATURE_ID,

  L7_DIFFSERV_PHB_EF_FEATURE_ID,
  L7_DIFFSERV_PHB_AF4X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF3X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF2X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF1X_FEATURE_ID,
  L7_DIFFSERV_PHB_CS_FEATURE_ID
};  /* end BCM XGS4 */

#define CNFGR_QOS_DIFFSERV_FEATURES_XGS4_LIST_ENTRIES \
  sizeof(cnfgrQosDiffServFeaturesBcmXgs4) / sizeof(cnfgrQosDiffServFeaturesBcmXgs4[0])


/* Full platform feature support list */
static L7_uchar8  cnfgrQosDiffServFeaturesFull[] =
{
  L7_DIFFSERV_FEATURE_SUPPORTED, 
  
  L7_DIFFSERV_CLASS_TYPE_ALL_FEATURE_ID,
  L7_DIFFSERV_CLASS_TYPE_ANY_FEATURE_ID,
  L7_DIFFSERV_CLASS_TYPE_ACL_FEATURE_ID,

  L7_DIFFSERV_CLASS_L3PROTO_IPV4_FEATURE_ID,
  L7_DIFFSERV_CLASS_L3PROTO_IPV6_FEATURE_ID,
  
  L7_DIFFSERV_CLASS_MATCH_COS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_COS2_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_DSTMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_ETYPE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_EVERY_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_DSTIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_DSTL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_DSTL4PORT_RANGE_FEATURE_ID, 
  L7_DIFFSERV_CLASS_MATCH_IPV6_FLOWLBL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_PROTOCOL_FEATURE_ID, 
  L7_DIFFSERV_CLASS_MATCH_IPV6_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_SRCL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPV6_SRCL4PORT_RANGE_FEATURE_ID, 
  L7_DIFFSERV_CLASS_MATCH_IPV6_MAC_FEATURE_ID,              /* supports IPv6 and MAC (L2) fields in same class */
  L7_DIFFSERV_CLASS_MATCH_IPDSCP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPPRECEDENCE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_IPTOS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_PROTOCOL_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_REFCLASS_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCIP_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCL4PORT_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SRCMAC_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_VLANID_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_VLANID2_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_EXCLUDE_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SUPPORTS_MASKING_FEATURE_ID,
  L7_DIFFSERV_CLASS_MATCH_SUPPORTS_RANGES_FEATURE_ID,
  
  L7_DIFFSERV_POLICY_ATTR_ASSIGN_QUEUE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_DROP_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COSVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COS2VAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COSASCOS2_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPDSCPVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_IPPRECEDENCEVAL_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MIRROR_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_SIMPLE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_SINGLERATE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_TWORATE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_POLICE_COLORAWARE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_REDIRECT_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COS_AND_ASSIGN_QUEUE_FEATURE_ID,
  L7_DIFFSERV_POLICY_ATTR_MARK_COS_POLICE_ACTION_FEATURE_ID,

  L7_DIFFSERV_POLICY_OUT_CLASS_UNRESTRICTED_FEATURE_ID,
  L7_DIFFSERV_POLICY_MIXED_IPV6_FEATURE_ID,  

  L7_DIFFSERV_SERVICE_IN_SLOTPORT_FEATURE_ID,
  L7_DIFFSERV_SERVICE_IN_ALLPORTS_FEATURE_ID,
  L7_DIFFSERV_SERVICE_OUT_SLOTPORT_FEATURE_ID,
  L7_DIFFSERV_SERVICE_OUT_ALLPORTS_FEATURE_ID,
  L7_DIFFSERV_SERVICE_SUPPORTS_LAG_INTF_FEATURE_ID,
  L7_DIFFSERV_SERVICE_ACL_COEXIST_FEATURE_ID,

  L7_DIFFSERV_PHB_EF_FEATURE_ID,
  L7_DIFFSERV_PHB_AF4X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF3X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF2X_FEATURE_ID,
  L7_DIFFSERV_PHB_AF1X_FEATURE_ID,
  L7_DIFFSERV_PHB_CS_FEATURE_ID,
  L7_DIFFSERV_PHB_OTHER_FEATURE_ID
};  /* end Full */

#define CNFGR_QOS_DIFFSERV_FEATURES_FULL_LIST_ENTRIES \
  sizeof(cnfgrQosDiffServFeaturesFull) / sizeof(cnfgrQosDiffServFeaturesFull[0])

/*                                                                           */
/*         End of QOS DIFFSERV Component's Feature Support Definitions       */
/*****************************************************************************/





/*****************************************************************************/
/*          Start of QOS COS Component's Feature Support Definitions         */
/*                                                                           */

/*-------------------------------------------------------------------
 * Must define a separate 'Features' array for each known technology
 * defined in L7_BASE_TECHNOLOGY_TYPES_t (or use the general 'Full' 
 * list if the platform supports all normal COS features)
 *
 * Only list the features that are supported for a particular technology.
 * Platforms that do not support COS do not have a list here.
 *
 * The list of features is defined in L7_COS_FEATURE_IDS_t
 *-------------------------------------------------------------------
 */

/* Bcm Strata platform feature support list */
static L7_uchar8  cnfgrQosCosFeaturesBcmStrata[] =
{
  L7_COS_FEATURE_SUPPORTED,
  L7_COS_QUEUE_CFG_PER_INTF_FEATURE_ID,
  L7_COS_QUEUE_INTF_SHAPING_FEATURE_ID

};  /* end BcmStrata */

#define CNFGR_QOS_COS_FEATURES_STRATA_LIST_ENTRIES \
  sizeof(cnfgrQosCosFeaturesBcmStrata) / sizeof(cnfgrQosCosFeaturesBcmStrata[0])


/* BCM XGS3 platform feature support list */
static L7_uchar8  cnfgrQosCosFeaturesBcmXgs3[] =
{
  L7_COS_FEATURE_SUPPORTED,
  L7_COS_LAG_INTF_SUPPORT_FEATURE_ID,

  L7_COS_MAP_IPDSCP_FEATURE_ID,
  L7_COS_MAP_TRUST_MODE_FEATURE_ID,
  L7_COS_MAP_TRUST_MODE_PER_INTF_FEATURE_ID,

  L7_COS_QUEUE_CFG_PER_INTF_FEATURE_ID,
  L7_COS_QUEUE_DROP_CFG_PER_INTF_FEATURE_ID,
  L7_COS_QUEUE_INTF_SHAPING_FEATURE_ID,
  L7_COS_QUEUE_MIN_BW_FEATURE_ID,
  L7_COS_QUEUE_MAX_BW_FEATURE_ID,             /* PTin added: COS */

  L7_COS_QUEUE_SCHED_TYPE_GLOBAL_FEATURE_ID, /* all interfaces */
  L7_COS_QUEUE_SCHED_TYPE_PER_INTF_FEATURE_ID /* per interface */


};  /* end BCM XGS3 */

#define CNFGR_QOS_COS_FEATURES_XGS3_LIST_ENTRIES \
  sizeof(cnfgrQosCosFeaturesBcmXgs3) / sizeof(cnfgrQosCosFeaturesBcmXgs3[0])

/* BCM XGS4 platform feature support list */
static L7_uchar8  cnfgrQosCosFeaturesBcmXgs4[] =
{
  L7_COS_FEATURE_SUPPORTED,
  L7_COS_LAG_INTF_SUPPORT_FEATURE_ID,

  L7_COS_MAP_IPDSCP_FEATURE_ID,
  L7_COS_MAP_IPDSCP_PER_INTF_FEATURE_ID,      /* PTin added: COS */
  L7_COS_MAP_TRUST_MODE_FEATURE_ID,
  L7_COS_MAP_TRUST_MODE_PER_INTF_FEATURE_ID,

  L7_COS_QUEUE_CFG_PER_INTF_FEATURE_ID,
  L7_COS_QUEUE_DROP_CFG_PER_INTF_FEATURE_ID,
  L7_COS_QUEUE_INTF_SHAPING_FEATURE_ID,
  L7_COS_QUEUE_MIN_BW_FEATURE_ID,
  L7_COS_QUEUE_MAX_BW_FEATURE_ID,             /* PTin added: COS */

  L7_COS_QUEUE_WRED_SUPPORT_FEATURE_ID,
  L7_COS_QUEUE_WRED_MAX_THRESH_FEATURE_ID

};  /* end BCM XGS4 */

#define CNFGR_QOS_COS_FEATURES_XGS4_LIST_ENTRIES \
  sizeof(cnfgrQosCosFeaturesBcmXgs4) / sizeof(cnfgrQosCosFeaturesBcmXgs4[0])

/* Bcm XGS platform feature support list */
static L7_uchar8  cnfgrQosCosFeaturesBcmXgs[] =
{
  L7_COS_FEATURE_SUPPORTED,

  L7_COS_MAP_IPPREC_FEATURE_ID,
  L7_COS_MAP_IPPREC_PER_INTF_FEATURE_ID,
  L7_COS_MAP_IPDSCP_FEATURE_ID,                 /* only supported on 5695 */
  L7_COS_MAP_IPDSCP_PER_INTF_FEATURE_ID,        /* only supported on 5695 */
  L7_COS_MAP_TRUST_MODE_FEATURE_ID,
  L7_COS_MAP_TRUST_MODE_PER_INTF_FEATURE_ID,

  L7_COS_QUEUE_CFG_PER_INTF_FEATURE_ID,
  L7_COS_QUEUE_INTF_SHAPING_FEATURE_ID,
  L7_COS_QUEUE_MIN_BW_FEATURE_ID

};  /* end BcmXgs */

#define CNFGR_QOS_COS_FEATURES_XGS_LIST_ENTRIES \
  sizeof(cnfgrQosCosFeaturesBcmXgs) / sizeof(cnfgrQosCosFeaturesBcmXgs[0])

/* BCM ROBO platform feature support list */
static L7_uchar8  cnfgrQosCosFeaturesBcmRobo[] =
{

  L7_COS_FEATURE_SUPPORTED,
  L7_COS_MAP_IPDSCP_FEATURE_ID,
  L7_COS_MAP_TRUST_MODE_FEATURE_ID,
  L7_COS_MAP_TRUST_MODE_PER_INTF_FEATURE_ID,
#ifndef FEAT_METRO_CPE_V1_0
  L7_COS_QUEUE_CFG_PER_INTF_FEATURE_ID,
#endif
  L7_COS_QUEUE_MIN_BW_FEATURE_ID,
  L7_COS_QUEUE_SCHED_TYPE_GLOBAL_FEATURE_ID,

}; /* end BCM ROBO */

#define CNFGR_QOS_COS_FEATURES_ROBO_LIST_ENTRIES \
  sizeof(cnfgrQosCosFeaturesBcmRobo) / sizeof(cnfgrQosCosFeaturesBcmRobo[0])


/* Full platform feature support list */
static L7_uchar8  cnfgrQosCosFeaturesFull[] =
{
  L7_COS_FEATURE_SUPPORTED,
  L7_COS_LAG_INTF_SUPPORT_FEATURE_ID,

  L7_COS_MAP_IPPREC_FEATURE_ID,
  L7_COS_MAP_IPPREC_PER_INTF_FEATURE_ID,
  L7_COS_MAP_IPDSCP_FEATURE_ID,
  L7_COS_MAP_IPDSCP_PER_INTF_FEATURE_ID,
  L7_COS_MAP_TRUST_MODE_FEATURE_ID,
  L7_COS_MAP_TRUST_MODE_PER_INTF_FEATURE_ID,

  L7_COS_QUEUE_CFG_PER_INTF_FEATURE_ID,
  L7_COS_QUEUE_DROP_CFG_PER_INTF_FEATURE_ID,
  L7_COS_QUEUE_INTF_SHAPING_FEATURE_ID,
  L7_COS_QUEUE_MIN_BW_FEATURE_ID,
  L7_COS_QUEUE_MAX_BW_FEATURE_ID,
  L7_COS_QUEUE_TDROP_THRESH_FEATURE_ID,
  L7_COS_QUEUE_WRED_SUPPORT_FEATURE_ID,
  L7_COS_QUEUE_WRED_MAX_THRESH_FEATURE_ID

};  /* end Full */

#define CNFGR_QOS_COS_FEATURES_FULL_LIST_ENTRIES \
  sizeof(cnfgrQosCosFeaturesFull) / sizeof(cnfgrQosCosFeaturesFull[0])

/*                                                                           */
/*          End of QOS COS Component's Feature Support Definitions           */
/*****************************************************************************/


 


#endif /* CNFGR_FLEX_FEATURE_SUPPORT */

#endif /* INCLUDE_CNFGR_FEATURES */
