# $Id: Makefile Exp $
#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Firebolt6 SOC driver Library
#

LOCALDIR = src/soc/esw/tdm/firebolt6/

include ${SDK}/make/Make.config

lib = libsoc_tdm_fb6

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

