#
# $Id: Makefile,v 1.4 2016/10/10
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/stat/mib
include ${SDK}/make/Make.config

#subdirs = 

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxstatmib

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend