#
# $Id:$
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC swstate subdirectory
#
LOCALDIR = src/soc/dnxf/swstate

include ${SDK}/make/Make.config
#
# Take the subdirs 'auto_generated'
#
subdirs = auto_generated

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxfswstate

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
