/** \file dnx/swstate/auto_generated/types/mdb_em_types.h
 *
 * sw state types (structs/enums/typedefs)
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 */
/*
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */

#ifndef __MDB_EM_TYPES_H__
#define __MDB_EM_TYPES_H__

#include <soc/dnxc/swstate/dnxc_sw_state_h_includes.h>
#include <soc/dnx/dbal/dbal_structures.h>
#include <soc/dnx/dnx_data/auto_generated/dnx_data_mdb.h>
#include <soc/dnxc/swstate/callbacks/sw_state_htb_callbacks.h>
#include <soc/dnxc/swstate/types/sw_state_hash_table.h>
/*
 * MACROs
 */

/**
 * The largest payload size associated with an EM table is 160 bits(LEM)
 */
#define MDB_MAX_EM_KEY_SIZE_IN_UINT32 (5)

/*
 * STRUCTs
 */

typedef struct {
    /**
     * the value of the VMV
     */
    uint8 encoding;
    /**
     * the prefix size of the VMV
     */
    uint8 size;
} vmv_value_parameters_t;

typedef struct {
    /**
     * the value of the VMV
     */
    uint8 value[DNX_DATA_MAX_MDB_EM_NOF_ENCODING_VALUES];
    /**
     * size of the VMV prefix
     */
    uint8 size[DNX_DATA_MAX_MDB_EM_NOF_ENCODING_VALUES];
    /**
     * map between the VMV value into the VMV encoding and size
     */
    vmv_value_parameters_t encoding_map[DNX_DATA_MAX_MDB_EM_VMV_NOF_VALUES];
    /**
     * the app_id size
     */
    uint8 app_id_size[DNX_DATA_MAX_MDB_EM_MAX_NOF_TIDS];
    /**
     * the max payload size associated with this app id
     */
    int max_payload_size[DNX_DATA_MAX_MDB_EM_MAX_NOF_TIDS];
} vmv_info_t;

/**
 * MDB EM (exact match) related sw state
 */
typedef struct {
    /**
     * This shadow database holds all the EM entries that are not supported by a flush machine.
     */
    sw_state_htbl_t shadow_em_db[DBAL_NOF_PHYSICAL_TABLES];
    /**
     * holds VMV information
     */
    vmv_info_t vmv_info[DBAL_NOF_PHYSICAL_TABLES];
    /**
     * MACT stamp used when issuing a host command to identify its reply
     */
    uint32 mact_stamp;
} mdb_em_sw_state_t;


#endif /* __MDB_EM_TYPES_H__ */
