# $Id$
# $Copyright: (c) 2005 Broadcom Corp.
# All Rights Reserved.$

PLATFORM=m32

include ${SDK}/make/Make.config


lib = libsoc_kbp_nlm2_diag

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

