#!/bin/sh

echo "Switch: fastpath"
/usr/local/sbin/fastpath boot &
/usr/local/sbin/fp.cli ping 10 20

# CMIC-I2C in Master mode
/sbin/devmem 0x3210234 32 0x00000036
/sbin/devmem 0x3200000 32 0x400F0C00

echo "Switch: done!"
