#
# $Id:$
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC swstate utils subdirectory
#
LOCALDIR = src/soc/dnxc/swstate/utils

include ${SDK}/make/Make.config

lib = libsoc_dnxcswstate_utils

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
