/*********************************************************************
*
* (C) Copyright Broadcom Corporation 2003-2007
*
**********************************************************************
*
* @filename web_oem_english.h
*
* @purpose OEM English language strings
*
* @component unitmgr
*
* @comments Remember to modify usmNLSLength at the bottom of this file
*           when adding or removing strings.
*
* @create 04/10/2003
*
* @author tgaunce
* @end
*
**********************************************************************/


#ifndef _OEM_ENGLISH_
#define _OEM_ENGLISH_

usmNLSString_t usmOEMEnglish[] = {

  /* ======================================================================== */
  /* Action Button Text 100-199                                               */
  /* ======================================================================== */
  {100, "Submit\0"},       /* Submit or apply the page */
  {101, "Refresh\0"},      /* Refresh the contents of the page */
  {102, "Cancel\0"},       /* Take no action */
  {103, "Delete\0"},       /* Remove the displayed item */
  {104, "Save\0"},         /* Store changes */
  {105, "Apply\0"},         /* Submit or apply the page */
  {106, "Configure Authentication\0"}, /* Configure authentication for the protocol */
  {107, "Create\0"},       /* Creation */
  {108, "Restore Defaults\0"},       /* Restore Default Settings */
  {109, "Clear\0"},                  /* Clear all the displayed values */
  {110, "Start\0"},                  /* Start processing/downloading */
  {111, "Next\0"},
  {112, "Add\0"},
  {113, "Manage\0"},
  {114, "Acknowledge\0"},
  {115, "Delete All\0"},
  {116, "Disassociate\0"},
  {117, "Allow MAC\0"},
  {118, "Deny MAC\0"},
  {119, "Edit\0"},
  {120, "Reset\0"},
  {121, "Reset All\0"},
  {122, "Delete All Neighbors\0"},

  /* ======================================================================== */
  {200, "Slot.Port\0"},
  {201, "Source Slot.Port\0"},
  {202, "VRID and Slot.Port"},
  {203, "Slot.Port(s)"},
  {204, "Forwarding Slot.Port(s)"},
  {205, "Next Hop Slot.Port"},

  /* ======================================================================== */
  /* Web Page Titles 1000-1999                                                */
  /* ======================================================================== */

  /* ------------------------------------------------------------------------ */
  /* 1000-1099  Base Web Code                                                 */
  /* ------------------------------------------------------------------------ */
  {1000, "System Description\0"},
  {1001, "Network Connectivity Configuration\0"},
  {1002, "Forwarding Database Search\0"},
  {1003, "Switch Configuration\0"},
  {1004, "Service Port Configuration\0"},
  {1005, "Download File To Switch\0"},
  {1006, "Upload File from Switch\0"},
  {1007, "Telnet Session Configuration\0"},
  {1008, "Serial Port Configuration\0"},
  {1009, "User Accounts\0"},
  {1010, "Confirm Configuration File Download\0"},
  {1011, "Reset Configuration to Defaults\0"},
  {1012, "System Reset\0"},
  {1013, "Event Log\0"},
  {1014, "Forwarding Database Configuration\0"},
  {1015, "Inventory Information\0"},
  {1016, "Message Log\0"},
  {1017, "Save All Applied Changes\0"},
  {1018, "System Reset\0"},
  {1019, "Reset Configuration to Defaults\0"},
  {1020, "Reset Passwords to Defaults\0"},
  {1021, "Ping\0"},
  {1022, "Trap Flags Configuration\0"},
  {1023, "Trap Log\0"},
  {1024, "Cable Test\0"},
  {1025, "ARP Cache\0"},
  {1026, "VLAN Configuration\0"},
  {1027, "Port Detailed Statistics\0"},
  {1028, "Port Summary Statistics\0"},
  {1029, "Switch Detailed Statistics\0"},
  {1030, "Switch Summary Statistics\0"},
  {1031, "SNMP Community Configuration\0"},
  {1032, "Port Mirroring\0"},
  {1033, "SNMP Supported MIBs\0"},
  {1034, "SNMP Trap Receiver Configuration\0"},
  {1035, "Port Configuration\0"},
  {1036, "Port Summary\0"},
  {1037, "Authentication List Configuration\0"},
  {1038, "User Login Configuration\0"},
  {1039, "Port Access Summary\0"},
  {1040, "Port User Login Configuration\0"},
  {1041, "Authentication List Summary\0"},
  {1042, "Port Access Control User Login Configuration\0"},
  {1043, "Login Sessions\0"},
  {1044, "SNMP Trap Receiver Summary\0"},
  {1045, "Network NDP Summary\0"},
  {1046, "Service Port NDP Summary\0"},
  {1047, "PoE Configuration\0"},
  {1048, "System Usage Threshold\0"},
  {1049, "DHCP Server Global Configuration\0"},
  {1050, "DHCP Server Pool Configuration\0"},
  {1051, "DHCP Server Reset Configuration\0"},
  {1052, "DHCP Server Bindings Information\0"},
  {1053, "DHCP Server Statistics\0"},
  {1054, "DHCP Server Conflicts Information\0"},
  {1055, "DHCP Server Pool Options\0"},
  {1056, "Buffered Log Configuration\0"},
  {1057, "Buffered Logs\0"},
  {1058, "Persistent Log Configuration\0"},
  {1059, "Persistent Logs\0"},
  {1060, "Console Log Configuration\0"},
  {1061, "Syslog Configuration\0"},
  {1062, "Hosts Configuration\0"},

  {1063, "SNTP Global Configuration\0"},
  {1064, "SNTP Global Status\0"},
  {1065, "SNTP Server Configuration\0"},
  {1066, "SNTP Server Status\0"},
  {1067, "LICENSE\0"},
  {1068, "Outbound Telnet Client Configuration\0"},
  {1070, "Denial of Service Configuration\0"},
  {1071, "Ping IPv6\0"},
  {1082, "Multiple Port Mirroring\0"},
  {1092, "Command Logger Configuration\0"},
  {1093, "Command Logger\0"},
  {1094, "Multiple Port Mirroring - Add Source Ports\0"},  
  {1095, "Dual Image Status\0"},
  {1096, "Dual Image Configuration\0"},
  {1097, "Port Description\0"},
  {1098, "Multiple Port Mirroring - Remove Source Ports\0"},
  {1099, "TraceRoute\0"},
  /* ------------------------------------------------------------------------ */
  /* 1100-1199  Switching                                                     */
  /* ------------------------------------------------------------------------ */
  {1102, "MFDB IGMP Snooping Table\0"},
  {1103, "Multicast Forwarding Database Statistics\0"},
  {1104, "MFDB GMRP Table\0"},
  {1105, "Multicast Forwarding Database Table\0"},
  {1106, "Port Channel Status\0"},
  {1107, "Port Channel Configuration\0"},
  {1108, "IGMP Snooping Interface Configuration\0"},
  {1109, "IGMP Snooping Global Configuration and Status\0"},
  {1110, "GARP Status\0"},
  {1111, "GARP Port Configuration\0"},
  {1112, "GARP Switch Configuration\0"},
  {1113, "MAC Filter Summary\0"},
  {1114, "MAC Filter Configuration\0"},
  {1115, "Protocol-based VLAN Summary\0"},
  {1116, "Protocol-based VLAN Configuration\0"},
  {1117, "Reset Configuration to Factory Defaults\0"},
  {1118, "VLAN Port Configuration\0"},
  {1119, "VLAN Status\0"},
  {1120, "Reset VLAN Configuration\0"},
  {1121, "Spanning Tree Switch Configuration/Status\0"},
  {1122, "Spanning Tree Port Configuration/Status\0"},
  {1123, "Spanning Tree Switch Configuration/Status\0"},
  {1124, "Spanning Tree Statistics\0"},
  {1125, "Spanning Tree CST Configuration/Status\0"},
  {1126, "Spanning Tree MST Port Configuration/Status\0"},
  {1127, "Spanning Tree MST Configuration/Status\0"},
  {1128, "Spanning Tree CST Port Configuration/Status\0"},
  {1129, "Port Access Privileges\0"},
  {1130, "RADIUS Accounting Server Configuration\0"},
  {1131, "RADIUS Accounting Server Statistics\0"},
  {1132, "RADIUS Configuration\0"},
  {1133, "RADIUS Clear Statistics\0"},
  {1134, "RADIUS Server Statistics\0"},
  {1135, "RADIUS Server Configuration\0"},
  {1136, "RADIUS Statistics\0"},
  {1137, "Port Access Control Configuration\0"},
  {1138, "Port Access Control Port Configuration\0"},
  {1139, "Port Access Control Statistics\0"},
  {1140, "Port Access Control Status\0"},
  {1141, "Port Access Control Port Summary\0"},
  {1142, "VLAN Port Summary\0"},
  {1143, "Double VLAN Tunneling\0"},
  {1144, "Double VLAN Tunneling Summary\0"},
  {1145, "Secure Shell Configuration\0"},
  {1146, "Secure HTTP Configuration\0"},
  {1147, "IGMP Snooping Querier Configuration\0"},
  {1148, "IGMP Snooping Querier VLAN Configuration\0"},
  {1149, "IGMP Snooping Querier Status\0"},
  {1150, "Port Channel Switch Configuration\0"},

  {1151, "MFDB MLD Snooping Table\0"},
  {1152, "MLD Snooping Interface Configuration\0"},
  {1153, "MLD Snooping Global Configuration and Status\0"},
  {1154, "MLD Snooping Interface Configuration\0"},
  {1155, "MLD Snooping VLAN Configuration\0"},
  {1156, "MLD Snooping VLAN Status\0"},

  {1160, "802.1p Priority Mapping\0"},
  {1161, "Multicast Router Statistics \0"},
  {1162, "Multicast Router Configuration\0"},
  {1163, "IGMP Snooping Interface Configuration\0"},
  {1164, "Multicast Router VLAN Configuration\0"},
  {1165, "Multicast Router VLAN Statistics \0"},
  {1166, "IGMP Snooping VLAN Configuration\0"},
  {1167, "IGMP Snooping VLAN Status\0"},
  {1168, "IGMP Snooping Querier VLAN Configuration Summary\0"},
  {1170, "Port Security Administration\0"},
  {1171, "Port Security Violation Status\0"},
  {1172, "Port Security Dynamically Learned MAC Addresses\0"},
  {1173, "Port Security Interface Configuration\0"},
  {1174, "Port Security Statically Configured MAC Addresses\0"},
  {1175, "MAC Based VLAN Configuration\0"},
  {1176, "IP Subnet-based VLAN Configuration\0"},
  {1177, "MAC-based VLAN Summary\0"},
  {1178, "IP Subnet-based VLAN Summary\0"},
  {1179, "DHCP Filtering Configuration\0"},
  {1180, "DHCP Filtering Interface Configuration\0"},
  {1181, "DHCP Filtering Interface Summary\0"},
  {1182, "TACACS+ Configuration\0"},  
  {1183, "TACACS+ Server Configuration\0"},
  {1185, "LLDP Global Configuration\0"},
  {1186, "LLDP Interface Configuration\0"},  
  {1187, "LLDP Statistics\0"},   
  {1188, "LLDP Local Device Information\0"},   
  {1189, "LLDP Interface Summary\0"},    
  {1190, "LLDP Remote Device Information\0"},  
  {1191, "LLDP Local Device Summary\0"},  
  {1192, "LLDP Remote Device Summary\0"},  

 /* ------------------------------------------------------------------------ */
  {1193, "Protected Ports Configuration\0"},
  {1194, "Protected Ports Summary\0"},

  {1195, "MLD Snooping Querier Configuration\0"},
  {1196, "MLD Snooping Querier VLAN Configuration\0"},
  {1197, "MLD Snooping Querier Status\0"},
  {1198, "MLD Snooping Querier VLAN Configuration Summary\0"},
  /* 1200-1299  Routing                                                       */
  {1200, "ARP Create\0"},
  {1201, "ARP Table Configuration\0"},
  {1202, "IP Interface Configuration\0"},
  {1203, "IP Configuration\0"},
  {1204, "IP Statistics\0"},
  {1205, "IP Statistics\0"},
  {1206, "Bridging Configuration\0"},
  {1207, "OSPF LSA Database\0"},
  {1208, "OSPF Area Range Configuration\0"},
  {1209, "OSPF Area Configuration\0"},
  {1210, "OSPF Interface Configuration\0"},
  {1211, "OSPF Link State Database\0"},
  {1212, "OSPF Interface Statistics\0"},
  {1213, "OSPF Stub Area Summary\0"},
  {1214, "OSPF Virtual Link Configuration\0"},
  {1215, "OSPF Virtual Link Summary\0"},
  {1216, "OSPF Configuration\0"},
  {1217, "OSPF Link State Database Detailed\0"},
  {1218, "BOOTP/DHCP Relay Agent Configuration\0"},
  {1219, "RIP Interface Configuration\0"},
  {1220, "RIP Interface Summary\0"},
  {1221, "RIP Configuration\0"},
  {1222, "Router RIP Peers\0"},
  {1223, "Router Discovery Configuration\0"},
  {1224, "Router Discovery Status\0"},
  {1225, "Virtual Router Configuration\0"},
  {1226, "Virtual Router Statistics\0"},
  {1227, "Virtual Router Status\0"},
  {1228, "VRRP Configuration\0"},
  {1229, "Router Route Entry Configuration\0"},
  {1230, "OSPF Neighbor Configuration\0"},
  {1231, "OSPF Neighbor Table\0"},
  {1232, "Router Route Preferences Configuration\0"},
  {1233, "Router Route Table\0"},
  {1234, "Router Best Routes Table\0"},
  {1235, "Trap Flags Configuration\0"},
  {1236, "Trap Log\0"},
  {1237, "VLAN Routing Configuration\0"},
  {1238, "VLAN Routing Summary\0"},
  {1239, "BOOTP/DHCP Relay Agent Status\0"},
  {1240, "RIP Interface Authentication Configuration\0"},
  {1241, "OSPF Virtual Link Authentication Configuration\0"},
  {1242, "OSPF Interface Authentication Configuration\0"},
  {1243, "RIP Route Redistribution Summary\0"},
  {1244, "OSPF Route Redistribution Summary\0"},
  {1245, "RIP Route Redistribution Configuration\0"},
  {1246, "OSPF Route Redistribution Configuration\0"},
  {1250, "Router Route Entry Create\0"},
  {1251, "IP Interface Secondary Address Configuration\0"},
  {1252, "VRRP Secondary Address Configuration\0"},
  {1253, "Configured Routes\0"},
 
 {1260,"Tunnel Configuration\0"},
 {1261,"Tunnel Summary\0"},
 {1262,"Loopback Configuration\0"},
 {1263,"Loopback Summary\0"},
 {1278, "Delete Host\0"},  
 {1279, "Delete Domain\0"},  
 {1280, "Delete Server\0"},

 /* 1281 - 1282 sFlow */
  {1281, "sFlow Configuration\0"},
  {1282, "sFlow Summery\0"},
 
 /* 1291-1349  QOS                                                           */
  /* ------------------------------------------------------------------------ */

  {1297, "Trust Mode Configuration\0"},
  {1298, "IP Precedence Mapping Configuration\0"},
  {1299, "IP DSCP Mapping Configuration\0"},
  {1300, "IP ACL Configuration\0"},
  {1301, "IP ACL Rule Configuration\0"},
  {1302, "ACL Service Type Configuration\0"},
  {1303, "IP ACL Summary"},
  {1304, "Bandwidth Profile Configuration\0"},
  {1305, "Bandwidth Profile Summary\0"},
  {1306, "Interface Allocation Summary\0"},
  {1307, "Traffic Class Configuration\0"},
  {1308, "Traffic Class Summary\0"},
  {1309, "DiffServ Configuration\0"},
  {1310, "DiffServ Class Configuration\0"},
  {1311, "DiffServ Class Summary\0"},
  {1312, "Class of Service\0"},
  {1313, "Destination IP Address\0"},
  {1314, "Destination Layer 4 Port\0"},
  {1315, "Destination MAC Address\0"},
  {1316, "IP DSCP\0"},
  {1317, "IP Precedence\0"},
  {1318, "IP TOS\0"},
  {1319, "Protocol\0"},
  {1320, "Reference Class\0"},
  {1321, "Source IP Address\0"},
  {1322, "Source Layer 4 Port\0"},
  {1323, "Source MAC Address\0"},
  {1324, "VLAN\0"},
  {1325, "DiffServ Policy Configuration\0"},
  {1326, "DiffServ Policy Summary\0"},
  {1327, "DiffServ Policy Class Definition\0"},
  {1328, "DiffServ Policy Attribute Summary\0"},
  {1329, "DiffServ Service Configuration\0"},
  {1330, "DiffServ Service Summary\0"},
  {1331, "DiffServ Service Statistics\0"},
  {1332, "DiffServ Service Detailed Statistics\0"},
  {1333, "Mark IP DSCP\0"},
  {1334, "Mark CoS\0"},
  {1335, "Mark IP Precedence\0"},
  {1336, "Policing Attributes\0"},
  {1337, "Policing Configuration\0"},
  {1338, "Bandwidth\0"},
  {1339, "Expedite\0"},
  {1340, "Random Drop\0"},
  {1341, "Shape Average\0"},
  {1342, "Shape Peak\0"},
  {1343, "CoS Mapping Table Configuration\0"},
  {1344, "CoS Interface Configuration\0"},
  {1345, "CoS Interface Queue Configuration\0"},
  {1346, "CoS Interface Queue Drop Precedence Configuration\0"},
  {1347, "CoS Interface Queue Status\0"},
  {1348, "CoS Interface Queue Drop Precedence Status\0"},
  {1349, "Interface or VLAN based ACL(s) Summary \0"},
  

  /* ------------------------------------------------------------------------ */
  /* 1350-1399  BGP                                                           */
  /* ------------------------------------------------------------------------ */

  {1350, "BGP4 Address Aggregation Configuration\0"},
  {1351, "BGP4 Dampened Paths Table\0"},
  {1352, "Address Family Configuration\0"},
  {1353, "BGP4 Global Configuration\0"},
  {1354, "Cluster ID Configuration\0"},
  {1355, "Confederation ID Configuration\0"},
  {1356, "BGP4 Local NLRI Configuration\0"},
  {1357, "BGP4 Local Originated Path Configuration\0"},
  {1358, "BGP4 Path Attributes Table\0"},
  {1359, "BGP4 Peer Address Family Configuration\0"},
  {1360, "BGP4 Peer Authentication Configuration\0"},
  {1361, "BGP4 Peer Configuration\0"},
  {1362, "BGP4 Peer Statistics\0"},
  {1363, "BGP4 Policy Action Configuration\0"},
  {1364, "BGP4 Policy Action Type Selection\0"},
  {1365, "BGP4 Policy Configuration\0"},
  {1366, "BGP4 Policy Range Configuration\0"},
  {1367, "BGP4 Policy Range Type Selection\0"},
  {1368, "BGP4 Policy Configuration Summary\0"},
  {1369, "BGP4 Route Flap Configuration\0"},
  {1370, "BGP4 Route Table Summary\0"},
  {1371, "BGP4 SNPA Configuration\0"},
  {1372, "BGP4 Route Redistribution Configuration\0"},
  {1373, "BGP4 Route Redistribution Summary\0"},
  /* ------------------------------------------------------------------------ */
  /* 1385-1399  QoS                                                           */
  /* ------------------------------------------------------------------------ */
  {1385, "MAC ACL Configuration\0"},
  {1386, "MAC ACL Summary\0"},
  {1387, "MAC ACL Rule Configuration\0"},
  {1388, "ACL Interface Configuration\0"},
  {1389, "VLAN Based ACL Configuration\0"},

  /* ------------------------------------------------------------------------ */
  /* 1390-1399  QoS                                                           */
  /* ------------------------------------------------------------------------ */
  {1391, "Mark Secondary CoS\0"},
  {1392, "Redirect Interface\0"},
  {1393, "Assign Queue\0"},
  {1394, "Drop Policy Attributes\0"},
  {1395, "Secondary Class of Service\0"},
  {1396, "Secondary VLAN\0"},
  {1397, "Ethertype\0"},
  {1398, "Mirror Interface\0"},
	

  /* ------------------------------------------------------------------------ */
  /* 1400-1449  IP Multicast                                                  */
  /* ------------------------------------------------------------------------ */

  {1400, "DVMRP Global Configuration\0"},
  {1401, "DVMRP Configuration Summary\0"},
  {1402, "DVMRP Interface Configuration\0"},
  {1403, "DVMRP Next Hop Summary\0"},
  {1404, "DVMRP Prune Summary\0"},
  {1405, "DVMRP Route Summary\0"},
  {1406, "IGMP Cache Information\0"},
  {1407, "IGMP Global Configuration\0"},
  {1408, "IGMP Configuration Summary\0"},
  {1409, "IGMP Interface Configuration\0"},
  {1410, "Multicast Admin Boundary Configuration\0"},
  {1411, "Multicast Admin Boundary Summary\0"},
  {1412, "Multicast Global Configuration\0"},
  {1413, "Multicast Global Configuration\0"},
  {1414, "Multicast Interface Configuration\0"},
  {1415, "Multicast Interface Configuration\0"},
  {1416, "Multicast MRoute Table\0"},
  {1417, "Mrinfo Run\0"},
  {1418, "Mrinfo Show\0"},
  {1419, "Mstat Run\0"},
  {1420, "Mstat Show\0"},
  {1421, "Multicast Static Routes Configuration\0"},
  {1422, "Multicast Static Routes Summary\0"},
  {1423, "Mtrace Configuration\0"},
  {1424, "Mtrace Configuration\0"},
  {1425, "Mtrace Run\0"},
  {1426, "Mtrace Show\0"},
  {1427, "PIM-DM Global Configuration\0"},
  {1428, "PIM-DM Interface Summary\0"},
  {1429, "PIM-DM Interface Configuration\0"},
  {1430, "PIM-SM Candidate RP Summary\0"},
  {1431, "PIM-SM Component Summary\0"},
  {1432, "PIM-SM Global Status\0"},
  {1433, "PIM-SM Global Configuration\0"},
  {1434, "PIM-SM Interface Summary\0"},
  {1435, "PIM-SM Interface Configuration\0"},
  {1436, "PIM-SM RP Set Summary\0"},
  {1437, "PIM-SM Static RP Configuration\0"},
  {1438, "IGMP Interface Detailed Membership Info\0"},
  {1439, "IGMP Proxy Interface Configuration\0"},
  {1440, "IGMP Proxy Configuration Summary\0"},
  {1441, "IGMP Proxy Interface Membership Info Detailed\0"},
  {1442, "IGMP Proxy Interface Membership Info\0"},
  {1443, "MLD Global Configuration\0"},
  {1444, "MLD Interface Configuration\0"},  
  {1445, "MLD Groups Summary\0"},  
  {1446, "MLD Interface Summary\0"},  
  {1447, "MLD Traffic\0"},
  {1448, "Candidate RP configuration\0"},
  {1449, "BSR Candidate configuration\0"},
  
  /* ------------------------------------------------------------------------ */
  /* 1450-1500  Stacking                                                      */
  /* ------------------------------------------------------------------------ */

  {1450, "Unit Configuration\0"},
  {1451, "Card Configuration\0"},
  {1452, "Slot Summary\0"},
  {1453, "Copy Stack Manager Configuration\0"},
  {1454, "Firmware Update\0"},
  {1455, "Stack Summary\0"},
  {1456, "Stack Manager Configuration\0"},
  {1457, "Stack Manager Confirmation\0"},
  {1458, "Supported Cards\0"},
  {1459, "Supported Switches\0"},
    /* Front Panel Stacking */
    {1460, "Stack Port Counters\0"},
    {1461, "Stack Port Configuration\0"},
    {1462, "Stack Port Diagnostics\0"},
    {1463, "Stack Port Summary\0"},
    
  /* ------------------------------------------------------------------------ */
  /* 1500-1700  IPv6                                                          */
  /* ------------------------------------------------------------------------ */

      /* IPv6 OSPFv3 */  
      {1500, "OSPFv3 Configuration\0"},
      {1501, "OSPFv3 Route Redistribution Summary\0"},
      {1502, "OSPFv3 Route Redistribution Configuration\0"},
      {1503, "OSPFv3 Neighbors\0"},
      {1504, "OSPFv3 Neighbor Table\0"},
      {1505, "OSPFv3 Virtual Link Summary\0"},
      {1506, "OSPFv3 Virtual Link Configuration\0"},
      {1507, "OSPFv3 Virtual Link Authentication Configuration\0"},
      {1508, "OSPFv3 Interface Statistics\0"},
      {1509, "OSPFv3 Interface Configuration\0"},
      {1510, "OSPFv3 Area Configuration\0"},
      {1511, "OSPFv3 Area Range Configuration\0"},
      {1512, "OSPFv3 Stub Area Summary\0"},
      {1513, "OSPFv3 Link State Database\0"},

      /* DHCPv6 */
      {1514, "DHCPv6 Global Configuration\0"},
      {1515, "DHCPv6 Statistics\0"},
      {1516, "DHCPv6 Pool Configuration\0"},
      {1517, "DHCPv6 Server Bindings Summary\0"},
      {1518, "DHCPv6 Interface Configuration\0"},
      {1519, "DHCPv6 Pool Summary\0"},
      {1520, "IPv6 Interface Summary\0"},
      {1521, "IPv6 Interface Configuration\0"},
      {1522, "IPv6 Interface Detail\0"},
      {1523, "Prefix Delegation Configuration\0"},

      /* IPv6 Core */
      {1551, "IPv6 Configuration\0"},
      {1552, "IPv6 Unicast Routing\0"},
      {1553, "IPv6 Forwarding\0"},
      {1554, "IPv6 Statistics\0"},
      {1555, "IPv6 Router Route Preferences\0"},
      {1556, "OSPFv3 Intra\0"},
      {1557, "OSPFv3 Inter\0"},
      {1558, "OSPFv3 External\0"},
      {1559, "OSPFv3 External\0"},
      {1560, "IPv6 Route Table\0"},
      {1561, "IPv6 Prefix/Prefix Length\0"},
      {1562, "All Routes\0"},
      {1563, "Best Routes Only\0"},
      {1564, "Routes Displayed\0"},
      {1565, "Number of Best Routes\0"},
      {1566, "Local\0"},
      {1567, "IPv6 Route Entry Create\0"},
      {1568, "IPv6 Route Entry Configuration\0"},
      {1570, "Configured IPv6 Routes\0"},

      /* IPv6 Statistics */
      {1571, "Total Datagrams Received\0"},
      {1572, "Received Datagrams Locally Delivered\0"},
      {1573, "Received Datagrams Discarded Due To Header Errors\0"},
      {1574, "Received Datagrams Discarded Due To MTU\0"},
      {1575, "Received Datagrams Discarded Due To No Route\0"},
      {1576, "Received Datagrams With Unknown Protocol\0"},
      {1577, "Received Datagrams Discarded Due To Invalid Address\0"},
      {1578, "Received Datagrams Discarded Dut To Truncated Data\0"},
      {1579, "Received Datagrams Discarded Other\0"},
      {1580, "Received Datagrams Reassembly Required\0"},
      {1581, "Datagrams Successfully Reassembled\0"},
      {1582, "Datagrams Failed To Reassemble\0"},
      {1583, "Datagrams Forwarded\0"},
      {1584, "Datagrams Locally Trasmitted\0"},
      {1585, "Datagrams Transmit Failed\0"},
      {1586, "Datagrams Successfully Fragmented\0"},
      {1587, "Datagrams Failed To Fragment\0"},
      {1588, "Multicast Datagrams Received\0"},
      {1589, "Multicast Datagrams Transmitted\0"},
      {1590, "Total ICMPv6 Messages Received\0"},
      {1591, "ICMPv6 Messages With Errors Received\0"},
      {1592, "ICMPv6 Destination Unreachable Messages Received\0"},
      {1593, "ICMPv6 Messages Prohibited Administratively Received\0"},
      {1594, "ICMPv6 Time Exceeded Messages Received\0"},
      {1595, "ICMPv6 Parameter Problem Messages Received\0"},
      {1596, "ICMPv6 Packet Too Big Messages Received\0"},
      {1597, "ICMPv6 Echo Request Messages Received\0"},
      {1598, "ICMPv6 Echo Reply Messages Received\0"},
      {1599, "ICMPv6 Router Solicit Messages Received\0"},
      {1600, "Datagrams Fragments Created\0"},
      {1601, "ICMPv6 Router Advertisement Messages Received\0"},
      {1602, "ICMPv6 Neighbor Solicit Messages Received\0"},
      {1603, "ICMPv6 Neighbor Advertisement Messages Received\0"},
      {1604, "ICMPv6 Redirect Messages Received\0"},
      {1605, "ICMPv6 Group Membership Query Messages Received\0"},
      {1606, "ICMPv6 Group Membership Response Messages Received\0"},
      {1607, "ICMPv6 Group Membership Reduction Messages Received\0"},
      {1608, "Total ICMPv6 Messages Transmitted\0"},
      {1609, "ICMPv6 Messages Not Transmitted Due To Error\0"},
      {1610, "ICMPv6 Destination Unreachable Messages Transmitted\0"},
      {1611, "ICMPv6 Messages Prohibited Administratively Transmitted\0"},
      {1612, "ICMPv6 Time Exceeded Messages Transmitted\0"},
      {1613, "ICMPv6 Parameter Problem Messages Transmitted\0"},
      {1614, "ICMPv6 Packet Too Big Messages Transmitted\0"},
      {1615, "ICMPv6 Echo Request Messages Transmitted\0"},
      {1616, "ICMPv6 Echo Reply Messages Transmitted\0"},
      {1617, "ICMPv6 Router Solicit Messages Transmitted\0"},
      {1618, "ICMPv6 Router Advertisement Messages Transmitted\0"},
      {1619, "ICMPv6 Neighbor Solicit Messages Transmitted\0"},
      {1620, "ICMPv6 Neighbor Advertisement Messages Transmitted\0"},
      {1621, "ICMPv6 Redirect Messages Transmitted\0"},
      {1622, "ICMPv6 Group Membership Query Messages Transmitted\0"},
      {1623, "ICMPv6 Group Membership Response Messages Transmitted\0"},
      {1624, "ICMPv6 Group Membership Reduction Messages Transmitted\0"},
      {1625, "ICMPv6 Duplicate Address Detects\0"},
      {1626, "IPv6 Statistics"},
      {1627, "IPv6 Neighbor Table"},
      {1628, "Hop Limit"},




  /* ------------------------------------------------------------------------ */  
  /* 1700-1900  Reserve for Wireless                                          */  
  /* ------------------------------------------------------------------------ */  

  /* ------------------------------------------------------------------------ */  
/* 1700-1900  Wireless                                                          */  
/* ------------------------------------------------------------------------ */  
{1701, "Wireless Global Configuration\0"},  
{1702, "Wireless Channel/Power Configuration\0"},  
{1703, "Wireless SNMP Trap Configuration\0"},  
{1704, "Wireless Global Status/Statistics\0"},  
{1705, "Wireless Global Statistics\0"},  
{1706, "Wireless Software Download\0"},  
{1707, "Wireless Software Download Status\0"},  
{1708, "Wireless Discovery Configuration\0"},  
{1711, "Wireless Discovery Status\0"},  
{1720, "Valid Access Point Configuration\0"},  
{1721, "Valid Access Point Summary\0"},  
{1722, "Wireless Switch Status/Statistics\0"}, 
{1723, "Wireless Known Client Summary\0"},
{1724, "Wireless Known Client Configuration\0"},  

/* Channel and Power Pages */
{1730, "RF Configuration\0"}, 
{1731, "Channel Plan History\0"}, 
{1732, "Manual Channel Plan\0"}, 
{1734, "Manual Power Adjustments\0"}, 

{1750, "Peer Switch Status\0"},  
{1751, "Peer Switch Client Status\0"}, 

{1761, "AP Hardware Capability\0"},
{1762, "AP Hardware Radio Capability\0"},

/* Access Point Profile Pages */
{1780, "Access Point Profile Global Configuration\0"},  
{1781, "Access Point Profile Radio Configuration\0"},  
{1782, "Access Point Profile QoS Configuration\0"},  
{1783, "Access Point Profile VAP Configuration\0"},  
{1784, "Access Point Profile Summary\0"},  

/* Wireless Setup Pages */
{1791, "Wireless Default VAP Configuration\0"},  
{1792, "Wireless Default AAA/RADIUS Configuration\0"},  
{1793, "Wireless Default Radio Configuration\0"},  
{1794, "Wireless Network Configuration\0"},  
{1795, "Wireless Network Summary\0"},  

/* ---------------------------------------------------------------- */
/* 1801-1815 Managed AP Status and Statistics                       */
/* ---------------------------------------------------------------- */
{1801, "Managed Access Point Status\0"},
{1802, "Managed Access Point Radio Status\0"},
{1803, "Managed Access Point VAP Status\0"},
{1804, "Access Point RF Scan Status\0"},
{1805, "Access Point Authentication Failure Status\0"},
{1806, "Managed Access Point Neighbor AP Status\0"},
{1807, "Managed Access Point Neighbor Client Status\0"},
{1808, "Managed Access Point Statistics\0"},
{1810, "Managed AP Reset\0"},
{1811, "Managed AP Advanced\0"},
{1812, "Managed AP Debug\0"},
{1813, "Managed AP Channel/Power Adjust\0"},
{1814, "Access Point Triangulation Status\0"},

/* ---------------------------------------------------------------- */
/* 1816-1830 Client Status and Statistics                           */
/* ---------------------------------------------------------------- */
{1816, "Associated Client Status\0"},
{1817, "Ad Hoc Client Status\0"},
{1818, "VAP Associated Client Status\0"},
{1819, "Client Authentication Failure Status\0"},
{1820, "SSID Associated Client Status\0"},
{1821, "Associated Client Neighbor AP Status\0"},
{1822, "Associated Client Statistics\0"},
{1823, "Switch Associated Client Status\0"},

/* ---------------------------------------------------------------- */
/* 1830-1900 DNS Client Configuration and Status                    */
/* ---------------------------------------------------------------- */
{1831, "DNS Global Configuration\0"},
{1832, "DNS Server Configuration\0"},
{1833, "Host Name - IP Configuration\0"},
{1834, "Host Name - IP Mapping Summary\0"},
{1835, "Domain Name List Configuration\0"},



/* ------------------------------------------------------------------------ */
/* 1900-1950  IPv6 QoS                                                      */
/* ------------------------------------------------------------------------ */
{1900, "IPv6 ACL Configuration\0"},
{1901, "IPv6 ACL Summary\0"},
{1902, "IPv6 ACL Rule Configuration\0"},
{1903, "Diffserv Source Prefix Configuration\0"},
{1904, "Diffserv Destination Prefix Configuration\0"},
{1905, "Flow Label Configuration\0"},
{1906, "Destination L4 Port Range Configuration\0"},
{1907, "Source L4 Port Range Configuration\0"},

/* ------------------------------------------------------------------------ */  
/* 1951-1999  Reserve for Captive Portal                                    */  
/* ------------------------------------------------------------------------ */  
{1951, "Global Configuration\0"},
{1952, "CP Summary\0"},
{1953, "CP WEB Customization\0"},
{1954, "Local User Configuration\0"},
{1955, "Interface Association\0"},
{1956, "Global Status\0"},
{1957, "CP Activation and Activity Status\0"},
{1958, "Interface Activation Status\0"},
{1959, "Interface Capability Status\0"},
{1960, "Client Detail\0"},
{1961, "Interface - Client Status\0"},
{1962, "CP - Client Status\0"},
{1963, "Client Statistics\0"},
{1964, "Local User Summary\0"},
{1965, "CP Configuration\0"},
{1966, "Client Summary\0"},
{1967, "SNMP Trap Configuration\0"},


/* ======================================================================== */
/* Help links 2000-2999                                                     */
/* ======================================================================== */


  /* ------------------------------------------------------------------------ */
  /* 2000-2199  Base Web Code                                                 */
  /* ------------------------------------------------------------------------ */
  {2000, "href=\"/base/system/help_sysinfo.html#sysdesc\""},
  {2001, "href=\"/base/system/help_switch_cfg.html#netcon\""},
  {2002, "href=\"/base/system/help_sysinfo.html#macaddr\""},
  {2003, "href=\"/base/system/help_switch_cfg.html#swcfg\""},
  {2004, "href=\"/base/system/help_switch_cfg.html#service\""},
  {2005, "href=\"/base/system/help_transfer.html#download\""},
  {2006, "href=\"/base/system/help_transfer.html#upload\""},
  {2007, "href=\"/base/system/help_switch_cfg.html#telnetcfg\""},
  {2008, "href=\"/base/system/help_switch_cfg.html#serport\""},
  {2009, "href=\"/base/system/help_users.html#useracct\""},
  {2010, "href=\"/base/system/help_index.html\""},
  {2011, "href=\"/base/system/help_index.html\""},
  {2012, "href=\"/base/system/help_index.html\""},
  {2013, "href=\"/base/system/help_sysinfo.html#eventlog\""},
  {2014, "href=\"/base/system/help_sysinfo.html#macaddrcfg\""},
  {2015, "href=\"/base/system/help_sysinfo.html#invinfo\""},
  {2016, "href=\"/base/system/help_sysinfo.html#msglog\""},
  {2017, "href=\"/base/system/help_switch_cfg.html#savechange\""},
  {2018, "href=\"/base/system/help_switch_cfg.html#sysrest\""},
  {2019, "href=\"/base/system/help_switch_cfg.html#rescfg\""},
  {2020, "href=\"/base/system/help_users.html#respass\""},
  {2021, "href=\"/base/system/help_switch_cfg.html#ping\""},
  {2022, "href=\"/base/system/trapmgr/help_traps.html#trapflag\""},
  {2023, "href=\"/base/system/trapmgr/help_traps.html#traplog\""},
  {2024, "href=\"/base/system/help_cable_test.html\""},
  {2025, "href=\"/base/system/help_sysinfo.html#arpcache\""},
  {2026, "href=\"/switching/dot1q/help_vlan.html#vlanconfig\""},
  {2027, "href=\"/base/system/stats/help_stats.html#portdetstat\""},
  {2028, "href=\"/base/system/stats/help_stats.html#portsumstat\""},
  {2029, "href=\"/base/system/stats/help_stats.html#swstat\""},
  {2030, "href=\"/base/system/stats/help_stats.html#swsumstat\""},
  {2031, "href=\"/base/system/snmp/help_snmp.html#snmpcomm\""},
  {2032, "href=\"/base/system/port/help_portcfg.html#portmon\""},
  {2033, "href=\"/base/system/snmp/help_snmp.html#mibsupport\""},
  {2034, "href=\"/base/system/snmp/help_snmp.html#traprcvr\""},
  {2035, "href=\"/base/system/port/help_portcfg.html#npcfg\""},
  {2036, "href=\"/base/system/port/help_portcfg.html#portstat\""},
  {2037, "href=\"/base/system/user_mgr/help_usermgr.html#logincfg\""},
  {2038, "href=\"/base/system/user_mgr/help_usermgr.html#userlogincfg\""},
  {2039, "href=\"/security/dot1x/help_dot1x.html#dot1xportaccesssummary\""},
  {2040, "href=\"/base/system/port/help_portcfg.html#portstat\""},
  {2041, "href=\"/base/system/user_mgr/help_usermgr.html#userloginsumm\""},
  {2042, "href=\"/security/dot1x/help_dot1x.html#dot1xloginconfig\""},
  {2043, "href=\"/base/system/user_mgr/help_usermgr.html#loginsessions\""},
  {2044, "href=\"/base/system/snmp/help_snmp.html#netndpsumm\""},
  {2045, "href=\"/base/system/snmp/help_snmp.html#servndpsumm\""},
  {2046, "href=\"/base/dns/help_dns_client.html#dns_client\""},
  {2049, "href=\"/base/dhcp/help_dhcp.html#dhcp_global_cfg\""},
  {2050, "href=\"/base/dhcp/help_dhcp.html#dhcp_pool_cfg\""},
  {2051, "href=\"/base/dhcp/help_dhcp.html#dhcp_reset_cfg\""},
  {2052, "href=\"/base/dhcp/help_dhcp.html#dhcp_bindings_info\""},
  {2053, "href=\"/base/dhcp/help_dhcp.html#dhcp_server_info\""},
  {2054, "href=\"/base/dhcp/help_dhcp.html#dhcp_conflicts_info\""},
  {2055, "href=\"/base/dhcp/help_dhcp.html#dhcp_pool_options\""},
  {2056, "href=\"/base/sntp/help_sntp.html#sntp_global_cfg\""},
  {2057, "href=\"/base/sntp/help_sntp.html#sntp_global_status\""},
  {2058, "href=\"/base/sntp/help_sntp.html#sntp_server_cfg\""},
  {2059, "href=\"/base/sntp/help_sntp.html#sntp_server_status\""},
  {2060, "href=\"/base/system/advancekey/help_license_advance.html#ladvance\""},

  {2061, "href=\"/base/system/log/help_syslog_cfg.html#inmem\""},
  {2062, "href=\"/base/system/log/help_syslog_cfg.html#messages\""},
  {2063, "href=\"/base/system/log/help_syslog_cfg.html#pers\""},
  {2064, "href=\"/base/system/log/help_syslog_cfg.html#messages1\""},
  {2065, "href=\"/base/system/log/help_syslog_cfg.html#console\""},
  {2066, "href=\"/base/system/log/help_syslog_cfg.html#syslog_cfg\""},
  {2067, "href=\"/base/system/log/help_syslog_cfg.html#hosts\""},
  {2068, "href=\"/base/system/help_switch_cfg.html#telnetc_cfg\""},
  {2070, "href=\"/base/system/help_dos_cfg.html\""},
  {2071, "href=\"/base/system/help_switch_cfg.html#pingipv6\""},

  {2074, "href=\"/base/system/sflow/help_sFlow.html#sFlowAgent\""},
  {2075, "href=\"/base/system/sflow/help_sFlow.html#sFlowRcvr\""},
  {2076, "href=\"/base/system/sflow/help_sFlow.html#sFlowPoller\""},
  {2077, "href=\"/base/system/sflow/help_sFlow.html#sFlowSampler\""},


  {2088, "href=\"/base/isdp/help_isdp.html#isdp_cache\""},
  {2089, "href=\"/base/isdp/help_isdp.html#isdp_intf\""},
  {2090, "href=\"/base/isdp/help_isdp.html#isdp_stat\""},  
  {2091, "href=\"/base/isdp/help_isdp.html#isdp_global_cfg\""},
  
  {2092, "href=\"/base/system/log/help_syslog_cfg.html#cmd_logger\""},
  {2094, "href=\"/base/system/port/help_portcfg.html#add_src_port\""},
  {2095, "href=\"/base/system/help_transfer.html#imagestatus\""},
  {2096, "href=\"/base/system/help_transfer.html#imagecfg\""},

  {2097, "href=\"/base/system/port/help_portcfg.html#portdes\""},
  {2098, "href=\"/base/system/port/help_portcfg.html#rmv_src_port\""}, 
  {2099, "href=\"/base/system/help_switch_cfg.html#traceroute\""},
  /* ------------------------------------------------------------------------ */
  /* 2100-2199  Switching , Security                                          */
  /* ------------------------------------------------------------------------ */
  /* 2100 - used for Radius (below) */
  {2102, "href=\"/switching/mfdb/help_mfdb.html#igmp_table\""},
  {2103, "href=\"/switching/mfdb/help_mfdb.html#mfdb_stats\""},
  {2104, "href=\"/switching/mfdb/help_mfdb.html#gmrp_table\""},
  {2105, "href=\"/switching/mfdb/help_mfdb.html#mfdb_table\""},
  {2106, "href=\"/switching/lag/help_lag.html#trunkstat\""},
  {2107, "href=\"/switching/lag/help_lag.html#trunkcfg\""},
  {2108, "href=\"/switching/igmp_snooping/help_igmp_snooping.html#igmp_interface\""},
  {2109, "href=\"/switching/igmp_snooping/help_igmp_snooping.html#switch\""},
  {2110, "href=\"/switching/garp/help_garp.html#garpstat\""},
  {2111, "href=\"/switching/garp/help_garp.html#portgarpcfg\""},
  {2112, "href=\"/switching/garp/help_garp.html#garpcfg\""},
  {2113, "href=\"/base/system/help_macfilter.html#swcfgsumm\""},
  {2114, "href=\"/base/system/help_macfilter.html#swcfg\""},
  {2115, "href=\"/switching/dot1v/help_pbvlan.html#pbvlan_summary\""},
  {2116, "href=\"/switching/dot1v/help_pbvlan.html#pbvlan_cfg\""},
  {2117, "href=\"/switching/dot1q/help_vlan.html#vlancfg\""},
  {2118, "href=\"/switching/dot1q/help_vlan.html#qnpcfg\""},
  {2119, "href=\"/switching/dot1q/help_vlan.html#vlanstat\""},
  {2120, "href=\"/switching/dot1q/help_vlan.html#resvlan\""},
  {2121, "href=\"/switching/dot1d/help_spantree.html#spantreesw\""},
  {2122, "href=\"/switching/dot1d/help_spantree.html#spantreepr\""},
  {2123, "href=\"/switching/spanning_tree/help_mstp.html#mstpswitch\""},
  {2124, "href=\"/switching/spanning_tree/help_mstp.html#stats\""},
  {2125, "href=\"/switching/spanning_tree/help_mstp.html#cistcfg\""},
  {2126, "href=\"/switching/spanning_tree/help_mstp.html#mstiportcfg\""},
  {2127, "href=\"/switching/spanning_tree/help_mstp.html#msticfg\""},
  {2128, "href=\"/switching/spanning_tree/help_mstp.html#cistportcfg\""},
  {2129, "href=\"/security/dot1x/help_dot1x.html#dot1xportaccesscfg\""},

  {2130, "href=\"/security/radius/help/radius_acct_config.html\""},
  {2131, "href=\"/security/radius/help/radius_acct_stats.html\""},
  {2132, "href=\"/security/radius/help/radius_configuration.html\""},
  {2133, "href=\"/security/radius/help/radius_clear.html\""},
  {2134, "href=\"/security/radius/help/radius_stats.html\""},
  {2135, "href=\"/security/radius/help/radius_server_config.html\""},
  {2136, "href=\"/security/radius/help/radius_status.html\""},
  {2100, "href=\"/security/radius/help/radius_acct_status.html\""},

  {2137, "href=\"/security/dot1x/help_dot1x.html#dot1xcfg\""},
  {2138, "href=\"/security/dot1x/help_dot1x.html#dot1xportcfg\""},
  {2139, "href=\"/security/dot1x/help_dot1x.html#dot1xstats\""},
  {2140, "href=\"/security/dot1x/help_dot1x.html#dot1xstatus\""},
  {2141, "href=\"/security/dot1x/help_dot1x.html#dot1xportstatus\""},
  {2142, "href=\"/switching/dot1q/help_vlan.html#qnpsumm\""},
  {2143, "href=\"/base/doublevlantag/help_dvlan.html#dvlan_tag\""},
  {2144, "href=\"/base/doublevlantag/help_dvlan.html#dvlan_tag_summ\""},
  {2145, "href=\"/security/ssh/help_ssh.html\""},
  {2146, "href=\"/security/ssl/help_https.html\""},
  {2147, "href=\"/switching/igmp_snooping/help_igmp_snooping_querier.html#querier_cfg\""},
  {2148, "href=\"/switching/igmp_snooping/help_igmp_snooping_querier.html#querier_vlan_cfg\""},
  {2149, "href=\"/switching/igmp_snooping/help_igmp_snooping_querier.html#querier_vlan_status\""},
  {2150, "href=\"/switching/lag/help_lag.html#lagswitch\""},

  {2151, "href=\"/switching/mfdb/help_mfdb.html#mld_table\""},
  {2152, "href=\"/switching/mld_snooping/help_mld_snooping.html#mld_interface\""},
  {2153, "href=\"/switching/mld_snooping/help_mld_snooping.html#switch\""},
  {2154, "href=\"/switching/mld_snooping/help_mld_snooping.html#mul_rut_stat\""},
  {2155, "href=\"/switching/mld_snooping/help_mld_snooping.html#mrcfg\""},
  {2156, "href=\"/switching/mld_snooping/help_mld_snooping.html#mul_vlan_cfg\""},
  {2157, "href=\"/switching/mld_snooping/help_mld_snooping.html#mul_vlan_stat\""},
  {2158, "href=\"/switching/mld_snooping/help_mld_snooping.html#MLD_vlan_cfg\""},
  {2159, "href=\"/switching/mld_snooping/help_mld_snooping.html#MLD_vlan_stats\""},

  {2160, "href=\"/switching/dot1p/help_dot1p.html#dot1pprioritymapping\""},
  {2161, "href=\"/switching/igmp_snooping/help_igmp_snooping.html#mul_rut_stat\""},
  {2162, "href=\"/switching/igmp_snooping/help_igmp_snooping.html#mrcfg\""},
  {2164, "href=\"/switching/igmp_snooping/help_igmp_snooping.html#mul_vlan_cfg\""},
  {2165, "href=\"/switching/igmp_snooping/help_igmp_snooping.html#mul_vlan_stat\""},
  {2166, "href=\"/switching/igmp_snooping/help_igmp_snooping.html#igmp_vlan_cfg\""},
  {2167, "href=\"/switching/igmp_snooping/help_igmp_snooping.html#igmp_vlan_stats\""},
  {2168, "href=\"/switching/igmp_snooping/help_igmp_snooping_querier.html#querier_vlan_summ\""},
  {2170, "href=\"/switching/port_mac_locking/help_portmaclocking.html#portmaclockingconfiguration\""},
  {2171, "href=\"/switching/port_mac_locking/help_portmaclocking.html#portmacviolationstatus\""},
  {2172, "href=\"/switching/port_mac_locking/help_portmaclocking.html#portmaclockingintifsetup\""},
  {2173, "href=\"/switching/port_mac_locking/help_portmaclocking.html#portmaclockingstatic\""},
  {2174, "href=\"/switching/port_mac_locking/help_portmaclocking.html#portmaclockingdynamic\""},
  {2175, "href=\"/switching/mac_vlan/help_mac_vlan.html#macvlancfg\""},
  {2176, "href=\"/switching/ipsubnetvlan/help_ipsubnet_vlan.html#subnetvlancfg\""},
  {2177, "href=\"/switching/mac_vlan/help_mac_vlan.html#macvlansumm\""},
  {2178, "href=\"/switching/ipsubnetvlan/help_ipsubnet_vlan.html#subnetvlansumm\""},
  {2179, "href=\"/switching/dhcp_filtering/help_dhcp_filtering.html#dhcpfiltercfg\""}, 
  {2180, "href=\"/switching/dhcp_filtering/help_dhcp_filtering.html#dhcpfilterintfcfg\""}, 
  {2181, "href=\"/switching/dhcp_filtering/help_dhcp_filtering.html#dhcpfilterintfsumm\""},
  {2182, "href=\"/security/tacacs/help_tacacs.html#tacacscfg\""},
  {2183, "href=\"/security/tacacs/help_tacacs.html#tacacsservercfg\""},
  {2185, "href=\"/switching/lldp/help_lldp.html#lldpcfg\""},  
  {2186, "href=\"/switching/lldp/help_lldp.html#lldpintfcfg\""},  
  {2187, "href=\"/switching/lldp/help_lldp.html#lldpstat\""},  
  {2188, "href=\"/switching/lldp/help_lldp.html#lldplocaldevice\""},  
  {2189, "href=\"/switching/lldp/help_lldp.html#lldpintfsumm\""},  
  {2190, "href=\"/switching/lldp/help_lldp.html#lldpremotedevice\""},  
  {2191, "href=\"/switching/lldp/help_lldp.html#lldplocaldevicesumm\""},  
  {2192, "href=\"/switching/lldp/help_lldp.html#lldpremotedevicesumm\""},  
  {2193, "href=\"/switching/protected_ports/help_protected_ports.html#prot_port_cfg\""},
  {2194, "href=\"/switching/protected_ports/help_protected_ports.html#prot_port_summ\""},
  {2195, "href=\"/switching/mld_snooping/help_mld_snooping_querier.html#querier_cfg\""},
  {2196, "href=\"/switching/mld_snooping/help_mld_snooping_querier.html#querier_vlan_cfg\""},
  {2197, "href=\"/switching/mld_snooping/help_mld_snooping_querier.html#querier_vlan_status\""},
  {2198, "href=\"/switching/igmp_snooping/help_igmp_snooping_querier.html#querier_vlan_summ\""},

 /* ------------------------------------------------------------------------ */
  /* 2200-2299  Routing                                                       */
  /* ------------------------------------------------------------------------ */
  {2200, "href=\"/routing/ip/help_layer3ip.html#arp_create\""},
  {2201, "href=\"/routing/ip/help_layer3ip.html#arp_table\""},
  {2202, "href=\"/routing/ip/help_layer3ip.html#intfipcfg\""},
  {2203, "href=\"/routing/ip/help_layer3ip.html#ipcfg\""},
  {2204, "href=\"/routing/ip/help_layer3ip.html#ipstats\""},
  {2205, "href=\"/routing/ip/help_layer3ip.html#ipstats\""},
  {2206, "href=\"/base/system/help_index.html\""},
  {2207, "href=\"/routing/ospf/help_ospf.html#lsadb\""},
  {2208, "href=\"/routing/ospf/help_ospf.html#area_range\""},
  {2209, "href=\"/routing/ospf/help_ospf.html#ospfarea\""},
  {2210, "href=\"/routing/ospf/help_ospf.html#ospfintfcfg\""},
  {2211, "href=\"/routing/ospf/help_ospf.html#lsdb_summ\""},
  {2212, "href=\"/routing/ospf/help_ospf.html#ospfintfstats\""},
  {2213, "href=\"/routing/ospf/help_ospf.html#stubSummary\""},
  {2214, "href=\"/routing/ospf/help_ospf.html#virt_link\""},
  {2215, "href=\"/routing/ospf/help_ospf.html#virt_link_summ\""},
  {2216, "href=\"/routing/ospf/help_ospf.html#ospfinfo\""},
  {2217, "href=\"/routing/ospf/help_ospf.html#lsdb_det\""},
  {2218, "href=\"/routing/relay/relay_help.html#cfg\""},
  {2219, "href=\"/routing/rip/help_rip.html#rip_det\""},
  {2220, "href=\"/routing/rip/help_rip.html#rip_summ\""},
  {2221, "href=\"/routing/rip/help_rip.html#rip_info\""},
  {2222, "href=\"/routing/rip/help_rip.html#rip_det\""},
  {2223, "href=\"/routing/router_discovery/help_rtr_discovery.html#rtr_discovery\""},
  {2224, "href=\"/routing/router_discovery/help_rtr_discovery.html#rtr_discovery_status\""},
  {2225, "href=\"/routing/vrrp/help_vrrp.html#vrcfg\""},
  {2226, "href=\"/routing/vrrp/help_vrrp.html#vrstats\""},
  {2227, "href=\"/routing/vrrp/help_vrrp.html#vrstatus\""},
  {2228, "href=\"/routing/vrrp/help_vrrp.html#vrrpcfg\""},
  {2229, "href=\"/routing/routing/help_router.html#rt_entry\""},
  {2230, "href=\"/routing/routing/help_layer3_nbr.html#nbr_dt\""},
  {2231, "href=\"/routing/routing/help_layer3_nbr.html#nbr_summ\""},
  {2232, "href=\"/routing/routing/help_router.html#rt_prefs\""},
  {2233, "href=\"/routing/routing/help_router.html#rt_table\""},
  {2234, "href=\"/routing/routing/help_router.html#best_rt_table\""},
  {2235, "href=\"/routing/trapmgr/help_traps.html#trapflag\""},
  {2236, "href=\"/routing/trapmgr/help_traps.html#traplog\""},
  {2237, "href=\"/routing/vlan_routing/help_vlan_routing.html#vrcfg\""},
  {2238, "href=\"/routing/vlan_routing/help_vlan_routing.html#vrsum\""},
  {2239, "href=\"/routing/relay/relay_help.html#status\""},
  {2243, "href=\"/routing/rip/help_rip.html#rip_rt_rdstrbtn_summ\""},
  {2244, "href=\"/routing/ospf/help_ospf.html#ospf_rt_rdstrbtn_summ\""},
  {2245, "href=\"/routing/rip/help_rip.html#rip_rt_rdstrbtn_cfg\""},
  {2246, "href=\"/routing/ospf/help_ospf.html#ospf_rt_rdstrbtn_cfg\""},
  {2250, "href=\"/routing/routing/help_router.html#rt_entry_create\""},
  {2251, "href=\"/routing/ip/help_layer3ip.html#sec_ip_cfg\""},
  {2252, "href=\"/routing/vrrp/help_vrrp.html#vrsecondary\""},
  {2253, "href=\"/routing/routing/help_router.html#rt_configured\""},
  {2260, "href=\"/routing/tunnel/help_tunnel.html#tunnelcfg\""},
  {2261, "href=\"/routing/tunnel/help_tunnel.html#tunnelsumm\""},
  {2262, "href=\"/routing/loopback/help_loopback.html#loopbackconfig\""},
  {2263, "href=\"/routing/loopback/help_loopback.html#loopbacksumm\""},

  /* ------------------------------------------------------------------------ */
  /* 2275-2349  QOS                                                           */
  /* ------------------------------------------------------------------------ */
  
  {2297, "href=\"/qos/cos/help_cos.html#cos_trust_mode_cfg\""},
  {2298, "href=\"/qos/cos/help_cos.html#cos_ip_prec_map_cfg\""},
  {2299, "href=\"/qos/cos/help_cos.html#cos_ip_dscp_map_cfg\""},
  {2300, "href=\"/qos/acl/help_acl.html#aclcfg\""},
  {2301, "href=\"/qos/acl/help_acl.html#aclRuleCfg\""},
  {2302, "href=\"/qos/acl/help_acl.html#aclRuleCfg\""},
  {2303, "href=\"/qos/acl/help_acl.html#aclSum\""},
  {2304, "href=\"/qos/bp/help_qos.html#bwb\""},
  {2305, "href=\"/qos/bp/help_qos.html#bw\""},
  {2306, "href=\"/qos/bp/help_qos.html#alloc\""},
  {2307, "href=\"/qos/bp/help_qos.html#tcc\""},
  {2308, "href=\"/qos/bp/help_qos.html#tcs\""},
  {2309, "href=\"/qos/diffserv/help_diffserv.html#diffserv_cfg\""},
  {2310, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg\""},
  {2311, "href=\"/qos/diffserv/help_diffserv_class.html#classSumm\""},
  {2312, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_cos\""},
  {2313, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_dstip\""},
  {2314, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_dstl4port\""},
  {2315, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_dstmac\""},
  {2316, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_ipdscp\""},
  {2317, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_ipprecedence\""},
  {2318, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_iptos\""},
  {2319, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_protocol\""},
  {2320, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_refclass\""},
  {2321, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_srcip\""},
  {2322, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_srcl4port\""},
  {2323, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_srcmac\""},
  {2324, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_vlan\""},
  {2325, "href=\"/qos/diffserv/help_diffserv_policy.html#policy_cfg\""},
  {2326, "href=\"/qos/diffserv/help_diffserv_policy.html#policySumm\""},
  {2327, "href=\"/qos/diffserv/help_diffserv_policy.html#policy_def\""},
  {2328, "href=\"/qos/diffserv/help_diffserv_policy.html#policyAttrSumm\""},
  {2329, "href=\"/qos/diffserv/help_diffserv_service.html#servCfg\""},
  {2330, "href=\"/qos/diffserv/help_diffserv_service.html#servSumm\""},
  {2331, "href=\"/qos/diffserv/help_diffserv_service.html#servStats\""},
  {2332, "href=\"/qos/diffserv/help_diffserv_service.html#servStatsDet\""},
  {2333, "href=\"/qos/diffserv/help_diffserv_policy.html#mark_ip_dscp\""},
  {2334, "href=\"/qos/diffserv/help_diffserv_policy.html#mark_cos\""},
  {2335, "href=\"/qos/diffserv/help_diffserv_policy.html#mark_ip_prec\""},
  {2336, "href=\"/qos/diffserv/help_diffserv_policy.html#policing_attributes\""},
  {2337, "href=\"/qos/diffserv/help_diffserv_policy.html#policing_cfg\""},
  {2338, "href=\"/qos/diffserv/help_diffserv_policy.html#bandwidth\""},
  {2339, "href=\"/qos/diffserv/help_diffserv_policy.html#expedite\""},
  {2340, "href=\"/qos/diffserv/help_diffserv_policy.html#random_drop\""},
  {2341, "href=\"/qos/diffserv/help_diffserv_policy.html#shape_average\""},
  {2342, "href=\"/qos/diffserv/help_diffserv_policy.html#shape_peak\""},
  {2343, "href=\"/qos/cos/help_cos.html#cos_map_table_cfg\""},
  {2344, "href=\"/qos/cos/help_cos.html#cos_intf_cfg\""},
  {2345, "href=\"/qos/cos/help_cos.html#cos_intf_queue_cfg\""},
  {2346, "href=\"/qos/cos/help_cos.html#cos_intf_queue_dropprec_cfg\""},
  {2347, "href=\"/qos/cos/help_cos.html#cos_intf_queue_status\""},
  {2348, "href=\"/qos/cos/help_cos.html#cos_intf_queue_dropprec_status\""},
  {2349, "href=\"/qos/acl/help_acl.html#aclIntIfVlanSumm\""},
  
  /* ------------------------------------------------------------------------ */
  /* 2350-2399  BGP                                                           */
  /* ------------------------------------------------------------------------ */

  {2350, "href=\"/bgp/help_bgp.html#bgpaddraggrcfg\""},
  {2351, "href=\"/bgp/help_bgp.html#bgpdamppaths\""},
  {2352, "href=\"/bgp/help_bgp.html#bgppolicycfg\""},
  {2353, "href=\"/bgp/help_bgp.html#bgpglobalcfg\""},
  {2354, "href=\"/bgp/help_bgp.html#bgpglobalcfg\""},
  {2355, "href=\"/bgp/help_bgp.html#bgpglobalcfg\""},
  {2356, "href=\"/bgp/help_bgp.html#bgpnlricfg\""},
  {2357, "href=\"/bgp/help_bgp.html#bgplocalcfg\""},
  {2358, "href=\"/bgp/help_bgp.html#bgppathattrtable\""},
  {2359, "href=\"/bgp/help_bgp.html#bgppolicycfg\""},
  {2360, "href=\"/bgp/help_bgp.html#bgppeercfg\""},
  {2361, "href=\"/bgp/help_bgp_peer.html#bgppeercfg\""},
  {2362, "href=\"/bgp/help_bgp_peer.html#bgppeerparams\""},
  {2363, "href=\"/bgp/help_bgp_policy.html#bgppolicyactionconfig\""},
  {2364, "href=\"/bgp/help_bgp_policy.html#bgppolicyactionselection\""},
  {2365, "href=\"/bgp/help_bgp_policy.html#bgppolicycfg\""},
  {2366, "href=\"/bgp/help_bgp_policy.html#bgppolicyrangeconfig\""},
  {2367, "href=\"/bgp/help_bgp_policy.html#bgppolicyrangeselection\""},
  {2368, "href=\"/bgp/help_bgp_policy.html#bgppolicysumm\""},
  {2369, "href=\"/bgp/help_bgp_route.html#bgprouteflapcfg\""},
  {2370, "href=\"/bgp/help_bgp_route.html#bgproutetable\""},
  {2371, "href=\"/bgp/help_bgp.html#bgpsnpacfg\""},
  {2372, "href=\"/bgp/help_bgp.html#bgp_rt_rdstrbtn_cfg\""},
  {2373, "href=\"/bgp/help_bgp.html#bgp_rt_rdstrbtn_summ\""},

  {2385, "href=\"/qos/acl/mac_acl/help_mac_acl.html#mac_acl_cfg\""},
  {2386, "href=\"/qos/acl/mac_acl/help_mac_acl.html#mac_acl_summ\""},
  {2387, "href=\"/qos/acl/mac_acl/help_mac_acl.html#mac_acl_rule_cfg\""},
  {2388, "href=\"/qos/acl/help_ip_mac_acl.html#ip_mac_acl_cfg\""},
  {2389, "href=\"/qos/acl/help_acl.html#vlan_acl_cfg\""},

  {2391, "href=\"/qos/diffserv/help_diffserv_policy.html#mark_secondary_cos\""},
  {2392, "href=\"/qos/diffserv/help_diffserv_policy.html#redirect_interface\""},
  {2393, "href=\"/qos/diffserv/help_diffserv_policy.html#assign_queue\""},
  {2394, "href=\"/qos/diffserv/help_diffserv_policy.html#drop_policing_attributes\""},
  {2395, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_cos2\""},
  {2396, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_vlan2\""},
  {2397, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_ethertyp\""},
  {2398, "href=\"/qos/diffserv/help_diffserv_policy.html#mirror_interface\""},

  /* ------------------------------------------------------------------------ */
  /* 2400-2449  IP Multicast                                                  */
  /* ------------------------------------------------------------------------ */

  {2400, "href=\"/ip_mcast/dvmrp/help_dvmrp.html#dvmrpglobalcfg\""},
  {2401, "href=\"/ip_mcast/dvmrp/help_dvmrp.html#dvmrpintfparams\""},
  {2402, "href=\"/ip_mcast/dvmrp/help_dvmrp.html#dvmrpintfcfg\""},
  {2403, "href=\"/ip_mcast/dvmrp/help_dvmrp.html#dvmrpnexthopparams\""},
  {2404, "href=\"/ip_mcast/dvmrp/help_dvmrp.html#dvmrppruneparams\""},
  {2405, "href=\"/ip_mcast/dvmrp/help_dvmrp.html#dvmrprouteparams\""},
  {2406, "href=\"/ip_mcast/igmp/help_igmp.html#igmpcacheinfo\""},
  {2407, "href=\"/ip_mcast/igmp/help_igmp.html#igmpglobalcfg\""},
  {2408, "href=\"/ip_mcast/igmp/help_igmp.html#igmpintfcfgparams\""},
  {2409, "href=\"/ip_mcast/igmp/help_igmp.html#igmpintfcfg\""},
  {2410, "href=\"/ip_mcast/mcast/help_mcast.html#mcastscopecfg\""},
  {2411, "href=\"/ip_mcast/mcast/help_mcast.html#mcastscopeparams\""},
  {2412, "href=\"/ip_mcast/mcast/help_mcast.html#mcastglobalcfg\""},
  {2413, "href=\"/ip_mcast/mcast/help_mcast.html#mcastglobalparams\""},
  {2414, "href=\"/ip_mcast/mcast/help_mcast.html#mcastintfcfg\""},
  {2415, "href=\"/ip_mcast/mcast/help_mcast.html#mcastintfparams\""},
  {2416, "href=\"/ip_mcast/mcast/help_mcast.html#mcastmroutecfg\""},
  {2417, "href=\"/ip_mcast/mcast/help_mcast.html#mcastmrinforun\""},
  {2418, "href=\"/ip_mcast/mcast/help_mcast.html#mcastmrinfoshow\""},
  {2419, "href=\"/ip_mcast/mcast/help_mcast.html#mcaststatrun\""},
  {2420, "href=\"/ip_mcast/mcast/help_mcast.html#mcaststatshow\""},
  {2421, "href=\"/ip_mcast/mcast/help_mcast.html#mcaststaticcfg\""},
  {2422, "href=\"/ip_mcast/mcast/help_mcast.html#mcaststaticparams\""},
  {2423, "href=\"/ip_mcast/mcast/help_mcast.html#mcasttraceconfig\""},
  {2424, "href=\"/ip_mcast/mcast/help_mcast.html#mcasttraceconfig\""},
  {2425, "href=\"/ip_mcast/mcast/help_mcast.html#mcastmtracerun\""},
  {2426, "href=\"/ip_mcast/mcast/help_mcast.html#mcastmtraceshow\""},
  {2427, "href=\"/ip_mcast/pim_dm/help_pim.html#pimglobalcfg\""},
  {2428, "href=\"/ip_mcast/pim_dm/help_pim.html#pimdmintfparams\""},
  {2429, "href=\"/ip_mcast/pim_dm/help_pim.html#pimdmintfcfg\""},
  {2430, "href=\"/ip_mcast/pim_sm/help_pim_sm.html#pimsmcandidateparams\""},
  {2431, "href=\"/ip_mcast/pim_sm/help_pim_sm.html#pimsmcomponentparams\""},
  {2432, "href=\"/ip_mcast/pim_sm/help_pim_sm.html#pimsmparams\""},
  {2433, "href=\"/ip_mcast/pim_sm/help_pim_sm.html#pimsmcfg\""},
  {2434, "href=\"/ip_mcast/pim_sm/help_pim_sm.html#pimsmifparams\""},
  {2435, "href=\"/ip_mcast/pim_sm/help_pim_sm.html#pimsmifcfg\""},
  {2436, "href=\"/ip_mcast/pim_sm/help_pim_sm.html#pimsmrpsetparams\""},
  {2437, "href=\"/ip_mcast/pim_sm/help_pim_sm.html#pimsmstaticrp\""},
  {2438, "href=\"/ip_mcast/igmp/help_igmp.html#membershipinfo\""},
  {2439,"href=\"/ip_mcast/igmp/proxy/help_igmp_proxy.html#igmpproxyintfcfg\""},
  {2440,"href=\"/ip_mcast/igmp/proxy/help_igmp_proxy.html#igmpproxyintfcfgparams\""},
  {2441,"href=\"/ip_mcast/igmp/proxy/help_igmp_proxy.html#membershipinfo\""},
  {2442,"href=\"/ip_mcast/igmp/proxy/help_igmp_proxy.html#cacheinfo\""},

  {2443,"href=\"/ip_mcast6/mld/help_mld.html#globalcfg\""},
  {2444,"href=\"/ip_mcast6/mld/help_mld.html#groupsummary\""},
  {2445,"href=\"/ip_mcast6/mld/help_mld.html#interfacecfg\""},
  {2446,"href=\"/ip_mcast6/mld/help_mld.html#interfacesummary\""},
  {2447,"href=\"/ip_mcast6/mld/help_mld.html#traffic\""},
  {2448,"href=\"/ip_mcast/ip_mcast/help_candidaterp.html\""},
  {2449,"href=\"/ip_mcast/ip_mcast/help_bsrcandidate.html\""},
  
  /* ------------------------------------------------------------------------ */
  /* 2450-2499  Stacking                                                      */
  /* ------------------------------------------------------------------------ */

  {2450, "href=\"/stacking/help_stacking.html#unitcfg\""},
  {2451, "href=\"/base/system/slot/help_slot.html#cardcfg\""},
  {2452, "href=\"/base/system/slot/help_slot.html#slotsumm\""},
  {2453, "href=\"/stacking/help_stacking.html#firmupdt\""},
  {2454, "href=\"/stacking/help_stacking.html#stackSumm\""},
  {2455, "href=\"/stacking/help_stacking.html#stackmngrrcfg\""},
  {2458, "href=\"/base/system/slot/help_slot.html#suppcard\""},
  {2459, "href=\"/stacking/help_stacking.html#suppunit\""},
  {2460, "href=\"/stacking/help_stacking.html#stackPortConfig\""},
  {2461, "href=\"/stacking/help_stacking.html#stackPort\""},
  {2462, "href=\"/stacking/help_stacking.html#stackPortCounters\""},
  {2463, "href=\"/stacking/help_stacking.html#stackPortDiag\""},
  
  /* ======================================================================== */
  /*  2500-2600    IPv6                                                       */
  /* ======================================================================== */

      /* IPv6 OSPFv3 */  
      {2500, "href=\"/routingv6/ospfv3/help_ospfv3.html#ospfv3info\""},
      {2501, "href=\"/routingv6/ospfv3/help_ospfv3.html#ospfv3_route_redistribution_summary\""},
      {2502, "href=\"/routingv6/ospfv3/help_ospfv3.html#ospv3_route_redistribution\""},
      {2503, "href=\"/routingv6/ospfv3/help_ospfv3.html#virt_link\""},
      {2504, "href=\"/routingv6/ospfv3/help_ospfv3.html#virt_link_summ\""},
      {2505, "href=\"/routingv6/ospfv3/help_ospfv3.html#ospfv3_intf_stats\""},
      {2506, "href=\"/routingv6/ospfv3/help_ospfv3.html#ospfv3_intfcfg\""},
      {2507, "href=\"/routingv6/ospfv3/help_ospfv3.html#ospfv3_area\""},
      {2508, "href=\"/routingv6/ospfv3/help_ospfv3.html#ospfv3_area_range\""},
      {2509, "href=\"/routingv6/ospfv3/help_ospfv3.html#ospfv3_stub_area\""},
      {2510, "href=\"/routingv6/ospfv3/help_ospfv3.html#ospfv3_lsdb\""},

      /*2517 for interface config */
      
      {2511, "href=\"/routingv6/dhcpv6/help_dhcpv6.html#dhcpv6globalcfg\""},
      {2512, "href=\"/routingv6/dhcpv6/help_dhcpv6.html#dhcpv6stats\""},
      {2513, "href=\"/routingv6/dhcpv6/help_dhcpv6.html#dhcpv6poolcfg\""},
      {2514, "href=\"/routingv6/dhcpv6/help_dhcpv6.html#dhcpv6poolbinding\""},
      {2515, "href=\"/routingv6/dhcpv6/help_dhcpv6.html#dhcpv6intfcfg\""},
      {2516, "href=\"/routingv6/dhcpv6/help_dhcpv6.html#dhcpv6poolsummary\""},
      {2517, "href=\"/routingv6/base/ipv6_help.html#ipv6intfsummary\""},
      {2518, "href=\"/routingv6/base/ipv6_help.html#ipv6intfcfg\""},
      {2519, "href=\"/routingv6/dhcpv6/help_dhcpv6.html#ipv6intfprefix\""},

      {2520, "href=\"/routingv6/routingv6/help_ipv6_route.html#ipv6RouterRoutePrefs\""},
      {2521, "href=\"/routingv6/routingv6/help_ipv6_route.html#ipv6RouteEntryCreate\""},
      {2524, "href=\"/routingv6/routingv6/help_ipv6_route.html#ipv6ConfiguredRoutes\""},
      {2525, "href=\"/routingv6/routingv6/help_ipv6_route.html#ipv6RouteTable\""},

      /* IPv6 Core */
      {2526, "href=\"/routingv6/base/ipv6_help.html#ipv6globalcfg\""},
      {2527, "href=\"/routingv6/base/ipv6_statistics_help.html#ipv6statistics\""},
      {2528, "href=\"/routingv6/dhcpv6/help_dhcpv6.html#ipv6prefixdeleg\""},

      {2529, "href=\"/routingv6/ospfv3/help_ospfv3.html#ospfv3_neighbor_table\""},
      {2530, "href=\"/routingv6/ospfv3/help_ospfv3.html#ospfv3_neighbors\""},

      {2535, "href=\"/routingv6/base/ipv6_help.html#ipv6Neighbor\""},

  /* ======================================================================== */
  /*  2601-2700 Wireless                                                      */
  /* ======================================================================== */

  {2601, "href=\"/wireless/help/ap_profile_summary.html\""},
  {2602, "href=\"/wireless/help/advanced_global_settings.html\""},
  {2603, "href=\"/wireless/help/snmp_traps.html\""},
  {2604, "href=\"/wireless/help/qos_config.html\""},
  {2605, "href=\"/wireless/help/known_client.html\""},

  {2606, "href=\"/wireless/help/regulatory_domain.html\""},
  {2607, "href=\"/wireless/help/managed_ap_client_switch_status.html\""},

  {2608, "href=\"/wireless/help/global_config.html\""},
  {2609, "href=\"/wireless/help/discovery.html\""},
  {2610, "href=\"/wireless/help/radio_config.html\""},
  {2611, "href=\"/wireless/help/vap_config.html\""},
  {2612, "href=\"/wireless/help/network_config.html\""},
  {2613, "href=\"/wireless/help/valid_ap_summary.html\""},
  {2614, "href=\"/wireless/help/valid_ap_config.html\""},
  {2615, "href=\"/wireless/help/hardware.html\""},

  {2616, "href=\"/wireless/help/client_detected_detail.html\""},

  {2623, "href=\"/wireless/help/client_failure_detail.html\""},
  {2624, "href=\"/wireless/help/rf_scan.html\""},
  {2625, "href=\"/wireless/help/rf_scan_detail.html\""},
  {2626, "href=\"/wireless/help/ad_hoc_client.html\""},
  {2627, "href=\"/wireless/help/ap_failure.html\""},
  {2628, "href=\"/wireless/help/ap_failure_detail.html\""},
  {2629, "href=\"/wireless/help/client_failure.html\""},

  {2630, "href=\"/wireless/help/ap_reset.html\""},
  {2631, "href=\"/wireless/help/rf_config.html\""},
  {2632, "href=\"/wireless/help/channel_history.html\""},
  {2633, "href=\"/wireless/help/manual_channel.html\""},
  {2634, "href=\"/wireless/help/manual_power.html\""},
  {2635, "href=\"/wireless/help/ap_upgrade.html\""},
  {2636, "href=\"/wireless/help/software_download.html\""},
  {2637, "href=\"/wireless/help/ap_debug.html\""},
  {2638, "href=\"/wireless/help/ap_debug2.html\""},
  {2639, "href=\"/wireless/help/power_channel_adjust.html\""},

  {2640, "href=\"/wireless/help/global_status.html\""},
  {2641, "href=\"/wireless/help/discovery_status.html\""},
  {2642, "href=\"/wireless/help/peer_switch_status.html\""},


  {2645, "href=\"/wireless/help/managed_ap_status.html\""},
  {2646, "href=\"/wireless/help/managed_ap_status_detail.html\""},
  {2647, "href=\"/wireless/help/managed_ap_radio_status.html\""},
  {2648, "href=\"/wireless/help/managed_ap_radio_detail.html\""},
  {2649, "href=\"/wireless/help/managed_ap_vap_status.html\""},
  {2650, "href=\"/wireless/help/managed_ap_neighbor_ap.html\""},
  {2651, "href=\"/wireless/help/managed_ap_neighbor_ap_client.html\""},
  {2652, "href=\"/wireless/help/managed_ap_wlan_statistics.html\""},
  {2653, "href=\"/wireless/help/managed_ap_eth_statistics.html\""},
  {2654, "href=\"/wireless/help/managed_ap_statistics_detail.html\""},
  {2655, "href=\"/wireless/help/managed_ap_radio_statistics.html\""},
  {2656, "href=\"/wireless/help/managed_ap_vap_statistics.html\""}, 

  {2657, "href=\"/wireless/help/managed_ap_client_status.html\""},
  {2658, "href=\"/wireless/help/managed_ap_client_status_detail.html\""},
  {2659, "href=\"/wireless/help/managed_ap_client_vap_status.html\""},
  {2660, "href=\"/wireless/help/managed_ap_client_ssid_status.html\""},
  {2661, "href=\"/wireless/help/managed_ap_client_neighbor_status.html\""},
  {2662, "href=\"/wireless/help/client_association_summary.html\""},
  {2663, "href=\"/wireless/help/client_association_detail.html\""},
  {2664, "href=\"/wireless/help/client_session_summary.html\""},
  {2665, "href=\"/wireless/help/client_session_detail.html\""},

  {2666, "href=\"/wireless/help/nv_download.html\""},
  {2667, "href=\"/wireless/help/nv_summary.html\""},

  {2674, "href=\"/wireless/help/wids_ap_config.html\""},
  {2676, "href=\"/wireless/help/wids_client_config.html\""},

  {2677, "href=\"/wireless/help/rfscan_triangulation.html\""},

  /* ------------------------------------------------------------------------ */
  /* 2700-2750  IPv6 QoS                                                       */
  /* ------------------------------------------------------------------------ */
  {2700, "href=\"/qos/acl/ipv6_acl/help_ipv6_acl.html#ipv6aclcfg\""},
  {2701, "href=\"/qos/acl/ipv6_acl/help_ipv6_acl.html#ipv6aclRuleCfg\""},
  {2702, "href=\"/qos/acl/ipv6_acl/help_ipv6_acl.html#ipv6aclSum\""},
  {2703, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_dest_prefix\""},
  {2704, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_src_prefix\""},
  {2705, "href=\"/qos/diffserv/help_diffserv_class.html#class_cfg_rule_flow_label\""},

  {2706, "href=\"/ip_mcast/pim_sm/help_pim_sm.html#pimsmcomponentssm\""},  
  {2707, "href=\"/ip_mcast6/pim_sm/help_pim_sm.html#pimsmcomponentparams\""},
  {2708, "href=\"/ip_mcast6/pim_sm/help_pim_sm.html#pimsmrpsetparams\""},

  /* ------------------------------------------------------------------------ */  
  /* 2751-2900  Reserve for Captive Portal                                    */  
  /* ------------------------------------------------------------------------ */  
  {2751, "href=\"/security/captive_portal/help/cp_global_config.html\""},
  {2752, "href=\"/security/captive_portal/help/cp_summary.html\""},
  {2753, "href=\"/security/captive_portal/help/cp_web_custom.html\""},
  {2754, "href=\"/security/captive_portal/help/cp_user_local_config.html\""},
  {2755, "href=\"/security/captive_portal/help/cp_if_assoc.html\""},
  {2756, "href=\"/security/captive_portal/help/cp_global_status.html\""},
  {2757, "href=\"/security/captive_portal/help/cp_act_status.html\""},
  {2758, "href=\"/security/captive_portal/help/cp_if_act_status.html\""},
  {2759, "href=\"/security/captive_portal/help/cp_if_cap_status.html\""},
  {2760, "href=\"/security/captive_portal/help/cp_client_detail.html\""},
  {2761, "href=\"/security/captive_portal/help/cp_client_if_status.html\""},
  {2762, "href=\"/security/captive_portal/help/cp_client_assoc_status.html\""},
  {2763, "href=\"/security/captive_portal/help/cp_client_stats.html\""},
  {2764, "href=\"/security/captive_portal/help/cp_user_local.html\""},
  {2765, "href=\"/security/captive_portal/help/cp_config.html\""},
  {2766, "href=\"/security/captive_portal/help/cp_client_summary.html\""},
  {2767, "href=\"/security/captive_portal/help/cp_add_local.html\""},
  {2768, "href=\"/security/captive_portal/help/cp_snmp_trap_config.html\""},

  /* ------------------------------------------------------------------------ */  
  /* 2901-2910  Reserve for ISDP                                              */  
  /* ------------------------------------------------------------------------ */  
  {2901, "ISDP Global Configuration\0"},
  {2902, "ISDP Statistics\0"},
  {2903, "ISDP Interface Configuration\0"},
  {2904, "ISDP Cache Table\0"},
  {2905, "href=\"/base/system/help_switch_cfg.html#dhcpclientOptionscfg\"},

  /* ----------------------------------------------------------------------- */
  /* 2910-2920  AutoInstall                                                  */
  /* ----------------------------------------------------------------------- */
  {2910, "href=\"/base/auto_install/help_autoinstall.html#cfg\""},

  {2920, "href=\"/base/system/help_switch_cfg.html#erase_startup_config\""},

  {99999, "The End!"}
};

unsigned int usmOEMNLSLength = (sizeof(usmOEMEnglish) / sizeof(usmOEMEnglish[0]));

#endif          /* _OEM_ENGLISH_ */

extern usmNLSString_t usmOEMEnglish[];
extern unsigned int usmOEMNLSLength;


