#
# $Id: Makefile $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/diag/dnx/meter

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/soc/dnx/meter

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxmeter

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
