#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/soc/dpp/auto_generated/

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/shared

lib = libsoc_dpp_auto_generated

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

