#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2018 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

include ${SDK}/make/Make.config

CFGFLAGS += -std=gnu99
export CFGFLAGS

subdirs = \
        algo    \
        bier    \
        bfd \
        cmn \
        cosq    \
        cosq/scheduler    \
        cosq/ingress    \
        cosq/egress    \
        dnx_unavail \
        dram \
        extender \
        fabric  \
        failover \
        field   \
        gtimer  \
        init    \
        instru  \
        ipmc    \
        kbp \
        l2  \
        l3  \
        legacy  \
        lif \
        link \
        mirror  \
        mdb     \
        mpls    \
        mpls_port   \
        mpls_l2vpn  \
        multicast   \
        oam \
        policer \
        ptp \
        port    \
        qos \
        rx  \
        sat \
        spb \
        stat \
        stat/crps   \
        stat/mib   \
        stat/stif   \
        stg \
        stk \
        srv6    \
        switch  \
        trunk   \
        tune    \
        tunnel  \
        tx  \
        vlan    \
        vswitch \
        pvt \
        vxlan \
	interrupt \
        synce \
        knet

include ${SDK}/make/Make.subdirs
