# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
#
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Maverick2 SOC driver Library
#

LOCALDIR = src/soc/esw/maverick2

include ${SDK}/make/Make.config

SUBDIR_MAVERICK2_FLEXPORT = flexport

subdirs := $(SUBDIR_MAVERICK2_FLEXPORT)

lib = libsoc_maverick2

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
