/*
 * $Id: low_level_defines.csv,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: Copyright 2016 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * This file is auto-generated by autoCoder
 * DO NOT EDIT THIS FILE!
 *
 */

#include <shared/bsl.h>
#include <soc/defs.h>
#ifdef BCM_88750_A0

#include <soc/dfe/cmn/dfe_config_imp_defs.h>
#include <soc/dfe/fe1600/fe1600_config_imp_defs.h>

#ifdef _ERR_MSG_MODULE_NAME
    #error "_ERR_MSG_MODULE_NAME redefined"
#endif /* _ERR_MSG_MODULE_NAME */

#define _ERR_MSG_MODULE_NAME BSL_SOC_INIT

CONST soc_dfe_implementation_defines_t soc_fe1600_implementation_defines= {
    SOC_FE1600_RTP_REACHABILTY_GEN_RATE_PER_LINK,
    SOC_FE1600_RTP_REACHABILTY_WATCHDOG_RATE,
    SOC_FE1600_MDIO_INT_DIVIDEND_DEFAULT,
    SOC_FE1600_MDIO_INT_FREQ_DEFAULT,
    SOC_FE1600_MDIO_INT_OUT_DELAY_DEFAULT,
    SOC_FE1600_FABRIC_CLOCK_FREQ_IN_DEFAULT,
    SOC_FE1600_FABRIC_CLOCK_FREQ_OUT_DEFAULT,
    SOC_FE1600_LCPLL_CONTROL1_125_VAL,
    SOC_FE1600_LCPLL_CONTROL1_156_25_VAL,
    SOC_FE1600_LCPLL_CONTROL3_125_VAL,
    SOC_FE1600_LCPLL_CONTROL3_156_25_VAL,
    SOC_FE1600_FIFO_DMA_NOF_CHANNELS,
};

/* defines struct init func for fe1600 */
int soc_fe1600_implementation_defines_init(int unit)
{
    SOCDNX_INIT_FUNC_DEFS;

    if ( soc_dfe_implementation_defines[unit] == NULL ) {
        soc_dfe_implementation_defines[unit] = (soc_dfe_implementation_defines_t *) sal_alloc(sizeof(soc_dfe_implementation_defines_t),"Defines struct");
        if ( soc_dfe_implementation_defines[unit] == NULL ) {
            SOCDNX_EXIT_WITH_ERR(SOC_E_MEMORY, (_BSL_SOCDNX_MSG("Failed to allocate memory for configuration defines struct")));
        }
    }
        sal_memcpy(soc_dfe_implementation_defines[unit], &soc_fe1600_implementation_defines, sizeof(soc_dfe_implementation_defines_t));

exit:
    SOCDNX_FUNC_RETURN;
}

/* defines struct deinit func for fe1600 */
int soc_fe1600_implementation_defines_deinit(int unit)
{
    if ( soc_dfe_implementation_defines[unit] != NULL ) {
        sal_free(soc_dfe_implementation_defines[unit]);
        soc_dfe_implementation_defines[unit] = NULL;
    }

    return SOC_E_NONE;
}

/**************************************/
/*  Operation mode specific logic    */
/**************************************/

#endif /* BCM_88750_A0 */
