/* $Id: arad_pp_api_trap_mgmt.h,v 1.12 Broadcom SDK $
 * $Copyright: Copyright 2016 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
*/

#ifndef __ARAD_PP_API_TRAP_MGMT_INCLUDED__
/* { */
#define __ARAD_PP_API_TRAP_MGMT_INCLUDED__

/*************
 * INCLUDES  *
 *************/
/* { */

#include <soc/dpp/SAND/Utils/sand_header.h>

#include <soc/dpp/SAND/Management/sand_general_macros.h>
#include <soc/dpp/SAND/Management/sand_error_code.h>

#include <soc/dpp/PPC/ppc_api_trap_mgmt.h>

#include <soc/dpp/ARAD/ARAD_PP/arad_pp_api_general.h>


/* } */
/*************
 * DEFINES   *
 *************/
/* { */

/*     Value used to assign discard action to trapped packet.
 *     Use as detailed in the APIs refering to this definition. */
#define  ARAD_PP_TRAP_ACTION_PKT_DISCARD_ID (SOC_PPC_TRAP_ACTION_PKT_DISCARD_ID)

/*     Value used to assign first cpu destinaion to trapped packet.
 *     Use as detailed in the APIs refering to this definition. */
#define  ARAD_PP_TRAP_ACTION_PKT_CPU_ID (SOC_PPC_TRAP_ACTION_PKT_CPU_ID)

/*     Value used to assign discard actio to trapped packet for learned cases.
 *     Used only for ARAD PLUS and below in case of egress learning
 *     Use as detailed in the APIs refering to this definition. */
#define  ARAD_PP_TRAP_ACTION_PKT_DISCARD_AND_LEARN_ID (SOC_PPC_TRAP_ACTION_PKT_DISCARD_AND_LEARN_ID)

/*     Value used to disable egress trap.
*     Use as detailed in the APIs refering to this definition. */
#define  ARAD_PP_TRAP_EG_NO_ACTION       (SOC_PPC_TRAP_EG_NO_ACTION)

/*     Maximum buffer size for events.                         */
#define  ARAD_PP_TRAP_EVENT_BUFF_MAX_SIZE (SOC_PPC_TRAP_EVENT_BUFF_MAX_SIZE)


/* } */
/*************
 * MACROS    *
 *************/
/* { */

/* } */
/*************
 * TYPE DEFS *
 *************/
/* { */

#define ARAD_PP_TRAP_SNOOP_ACTION_SIZE_64B                   SOC_PPC_TRAP_SNOOP_ACTION_SIZE_64B
#define ARAD_PP_TRAP_SNOOP_ACTION_SIZE_128B                  SOC_PPC_TRAP_SNOOP_ACTION_SIZE_128B
#define ARAD_PP_TRAP_SNOOP_ACTION_SIZE_FULL_PACKET           SOC_PPC_TRAP_SNOOP_ACTION_SIZE_FULL_PACKET
#define ARAD_PP_NOF_TRAP_SNOOP_ACTION_SIZES                  SOC_PPC_NOF_TRAP_SNOOP_ACTION_SIZES
typedef SOC_PPC_TRAP_SNOOP_ACTION_SIZE                         ARAD_PP_TRAP_SNOOP_ACTION_SIZE;

#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_NONE           SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_NONE
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_DEST           SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_DEST
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_TC             SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_TC
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_DP             SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_DP
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_POLICER        SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_POLICER
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_FRWRD_OFFSET   SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_FRWRD_OFFSET
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_CUD            SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_CUD
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_DP_METER_CMD   SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_DP_METER_CMD
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_ALL            SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_ALL
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_DEST_EEI       SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_DEST_EEI
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_DEST_OUTLIF    SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_DEST_OUTLIF
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_FRWRD_TYPE     SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_FRWRD_TYPE
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_DA_TYPE        SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_DA_TYPE
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_METER_0          SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_METER_0
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_METER_1          SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_METER_1
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_COUNTER_0        SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_COUNTER_0
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_COUNTER_1        SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_COUNTER_1
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_PP_DSP           SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_PP_DSP
#define ARAD_PP_TRAP_ACTION_PROFILE_USE_ARR                    SOC_PPC_TRAP_ACTION_PROFILE_USE_ARR
#define ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_COS_PROFILE      SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_COS_PROFILE
#define ARAD_PP_NOF_TRAP_ACTION_PROFILE_OVERWRITES             SOC_PPC_NOF_TRAP_ACTION_PROFILE_OVERWRITES_ARAD
typedef SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE                  ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE;

#define ARAD_PP_TRAP_MACT_EVENT_TYPE_NONE                    SOC_PPC_TRAP_MACT_EVENT_TYPE_NONE
#define ARAD_PP_TRAP_MACT_EVENT_TYPE_AGED_OUT                SOC_PPC_TRAP_MACT_EVENT_TYPE_AGED_OUT
#define ARAD_PP_TRAP_MACT_EVENT_TYPE_LEARN                   SOC_PPC_TRAP_MACT_EVENT_TYPE_LEARN
#define ARAD_PP_TRAP_MACT_EVENT_TYPE_TRANSPLANT              SOC_PPC_TRAP_MACT_EVENT_TYPE_TRANSPLANT
#define ARAD_PP_TRAP_MACT_EVENT_TYPE_REFRESH                 SOC_PPC_TRAP_MACT_EVENT_TYPE_REFRESH
#define ARAD_PP_TRAP_MACT_EVENT_TYPE_ACK                     SOC_PPC_TRAP_MACT_EVENT_TYPE_ACK
#define ARAD_PP_TRAP_MACT_EVENT_TYPE_RETRIEVE                SOC_PPC_TRAP_MACT_EVENT_TYPE_RETRIEVE
#define ARAD_PP_TRAP_MACT_EVENT_TYPE_LIMIT_EXCEED            SOC_PPC_TRAP_MACT_EVENT_TYPE_LIMIT_EXCEED
#define ARAD_PP_TRAP_MACT_EVENT_TYPE_CPU_REQ_FAIL            SOC_PPC_TRAP_MACT_EVENT_TYPE_CPU_REQ_FAIL
#define ARAD_PP_NOF_TRAP_MACT_EVENT_TYPES                    SOC_PPC_NOF_TRAP_MACT_EVENT_TYPES
typedef SOC_PPC_TRAP_MACT_EVENT_TYPE                           ARAD_PP_TRAP_MACT_EVENT_TYPE;


#define ARAD_PP_TRAP_CODE_PBP_SA_DROP_0                      SOC_PPC_TRAP_CODE_PBP_SA_DROP_0
#define ARAD_PP_TRAP_CODE_PBP_SA_DROP_1                      SOC_PPC_TRAP_CODE_PBP_SA_DROP_1
#define ARAD_PP_TRAP_CODE_PBP_SA_DROP_2                      SOC_PPC_TRAP_CODE_PBP_SA_DROP_2
#define ARAD_PP_TRAP_CODE_PBP_SA_DROP_3                      SOC_PPC_TRAP_CODE_PBP_SA_DROP_3
#define ARAD_PP_TRAP_CODE_PBP_TE_TRANSPLANT                  SOC_PPC_TRAP_CODE_PBP_TE_TRANSPLANT
#define ARAD_PP_TRAP_CODE_PBP_TE_UNKNOWN_TUNNEL              SOC_PPC_TRAP_CODE_PBP_TE_UNKNOWN_TUNNEL
#define ARAD_PP_TRAP_CODE_PBP_TRANSPLANT                     SOC_PPC_TRAP_CODE_PBP_TRANSPLANT
#define ARAD_PP_TRAP_CODE_PBP_LEARN_SNOOP                    SOC_PPC_TRAP_CODE_PBP_LEARN_SNOOP
#define ARAD_PP_TRAP_CODE_SA_AUTHENTICATION_FAILED           SOC_PPC_TRAP_CODE_SA_AUTHENTICATION_FAILED
#define ARAD_PP_TRAP_CODE_PORT_NOT_PERMITTED                 SOC_PPC_TRAP_CODE_PORT_NOT_PERMITTED
#define ARAD_PP_TRAP_CODE_UNEXPECTED_VID                     SOC_PPC_TRAP_CODE_UNEXPECTED_VID
#define ARAD_PP_TRAP_CODE_SA_MULTICAST                       SOC_PPC_TRAP_CODE_SA_MULTICAST
#define ARAD_PP_TRAP_CODE_SA_EQUALS_DA                       SOC_PPC_TRAP_CODE_SA_EQUALS_DA
#define ARAD_PP_TRAP_CODE_8021X                              SOC_PPC_TRAP_CODE_8021X
#define ARAD_PP_TRAP_CODE_ACCEPTABLE_FRAME_TYPE_DROP         SOC_PPC_TRAP_CODE_ACCEPTABLE_FRAME_TYPE_DROP
#define ARAD_PP_TRAP_CODE_ACCEPTABLE_FRAME_TYPE_ACCEPT       SOC_PPC_TRAP_CODE_ACCEPTABLE_FRAME_TYPE_ACCEPT
#define ARAD_PP_TRAP_CODE_ACCEPTABLE_FRAME_TYPE_CUSTOM_1     SOC_PPC_TRAP_CODE_ACCEPTABLE_FRAME_TYPE_CUSTOM_1
#define ARAD_PP_TRAP_CODE_ACCEPTABLE_FRAME_TYPE_CUSTOM_2     SOC_PPC_TRAP_CODE_ACCEPTABLE_FRAME_TYPE_CUSTOM_2
#define ARAD_PP_TRAP_CODE_MY_ARP                             SOC_PPC_TRAP_CODE_MY_ARP
#define ARAD_PP_TRAP_CODE_ARP                                SOC_PPC_TRAP_CODE_ARP
#define ARAD_PP_TRAP_CODE_IGMP_MEMBERSHIP_QUERY              SOC_PPC_TRAP_CODE_IGMP_MEMBERSHIP_QUERY
#define ARAD_PP_TRAP_CODE_IGMP_REPORT_LEAVE_MSG              SOC_PPC_TRAP_CODE_IGMP_REPORT_LEAVE_MSG
#define ARAD_PP_TRAP_CODE_IGMP_UNDEFINED                     SOC_PPC_TRAP_CODE_IGMP_UNDEFINED
#define ARAD_PP_TRAP_CODE_ICMPV6_MLD_MC_LISTENER_QUERY       SOC_PPC_TRAP_CODE_ICMPV6_MLD_MC_LISTENER_QUERY
#define ARAD_PP_TRAP_CODE_RESERVED_MC_0                      SOC_PPC_TRAP_CODE_RESERVED_MC_0
#define ARAD_PP_TRAP_CODE_RESERVED_MC_1                      SOC_PPC_TRAP_CODE_RESERVED_MC_1
#define ARAD_PP_TRAP_CODE_RESERVED_MC_2                      SOC_PPC_TRAP_CODE_RESERVED_MC_2
#define ARAD_PP_TRAP_CODE_RESERVED_MC_3                      SOC_PPC_TRAP_CODE_RESERVED_MC_3
#define ARAD_PP_TRAP_CODE_RESERVED_MC_4                      SOC_PPC_TRAP_CODE_RESERVED_MC_4
#define ARAD_PP_TRAP_CODE_RESERVED_MC_5                      SOC_PPC_TRAP_CODE_RESERVED_MC_5
#define ARAD_PP_TRAP_CODE_RESERVED_MC_6                      SOC_PPC_TRAP_CODE_RESERVED_MC_6
#define ARAD_PP_TRAP_CODE_RESERVED_MC_7                      SOC_PPC_TRAP_CODE_RESERVED_MC_7
#define ARAD_PP_TRAP_CODE_ICMPV6_MLD_REPORT_DONE_MSG         SOC_PPC_TRAP_CODE_ICMPV6_MLD_REPORT_DONE_MSG
#define ARAD_PP_TRAP_CODE_ICMPV6_MLD_UNDEFINED               SOC_PPC_TRAP_CODE_ICMPV6_MLD_UNDEFINED
#define ARAD_PP_TRAP_CODE_DHCP_SERVER                        SOC_PPC_TRAP_CODE_DHCP_SERVER
#define ARAD_PP_TRAP_CODE_DHCP_CLIENT                        SOC_PPC_TRAP_CODE_DHCP_CLIENT
#define ARAD_PP_TRAP_CODE_DHCPV6_SERVER                      SOC_PPC_TRAP_CODE_DHCPV6_SERVER
#define ARAD_PP_TRAP_CODE_DHCPV6_CLIENT                      SOC_PPC_TRAP_CODE_DHCPV6_CLIENT
#define ARAD_PP_TRAP_CODE_PROG_TRAP_0                        SOC_PPC_TRAP_CODE_PROG_TRAP_0
#define ARAD_PP_TRAP_CODE_PROG_TRAP_1                        SOC_PPC_TRAP_CODE_PROG_TRAP_1
#define ARAD_PP_TRAP_CODE_PROG_TRAP_2                        SOC_PPC_TRAP_CODE_PROG_TRAP_2
#define ARAD_PP_TRAP_CODE_PROG_TRAP_3                        SOC_PPC_TRAP_CODE_PROG_TRAP_3
#define ARAD_PP_TRAP_CODE_PORT_NOT_VLAN_MEMBER               SOC_PPC_TRAP_CODE_PORT_NOT_VLAN_MEMBER
#define ARAD_PP_TRAP_CODE_HEADER_SIZE_ERR                    SOC_PPC_TRAP_CODE_HEADER_SIZE_ERR
#define ARAD_PP_TRAP_CODE_HEADER_SIZE_ERR_O_MPLS             SOC_PPC_TRAP_CODE_HEADER_SIZE_ERR_O_MPLS
#define ARAD_PP_TRAP_CODE_MY_B_MAC_AND_LEARN_NULL            SOC_PPC_TRAP_CODE_MY_B_MAC_AND_LEARN_NULL
#define ARAD_PP_TRAP_CODE_MY_B_DA_UNKNOWN_I_SID              SOC_PPC_TRAP_CODE_MY_B_DA_UNKNOWN_I_SID
#define ARAD_PP_TRAP_CODE_STP_STATE_BLOCK                    SOC_PPC_TRAP_CODE_STP_STATE_BLOCK
#define ARAD_PP_TRAP_CODE_STP_STATE_LEARN                    SOC_PPC_TRAP_CODE_STP_STATE_LEARN
#define ARAD_PP_TRAP_CODE_IP_COMP_MC_INVALID_IP              SOC_PPC_TRAP_CODE_IP_COMP_MC_INVALID_IP
#define ARAD_PP_TRAP_CODE_MY_MAC_AND_IP_DISABLE              SOC_PPC_TRAP_CODE_MY_MAC_AND_IP_DISABLE
#define ARAD_PP_TRAP_CODE_TRILL_VERSION                      SOC_PPC_TRAP_CODE_TRILL_VERSION
#define ARAD_PP_TRAP_CODE_TRILL_INVALID_TTL                  SOC_PPC_TRAP_CODE_TRILL_INVALID_TTL
#define ARAD_PP_TRAP_CODE_TRILL_CHBH                         SOC_PPC_TRAP_CODE_TRILL_CHBH
#define ARAD_PP_TRAP_CODE_TRILL_NO_REVERSE_FEC               SOC_PPC_TRAP_CODE_TRILL_NO_REVERSE_FEC
#define ARAD_PP_TRAP_CODE_TRILL_CITE                         SOC_PPC_TRAP_CODE_TRILL_CITE
#define ARAD_PP_TRAP_CODE_TRILL_ILLEGAL_INNER_MC             SOC_PPC_TRAP_CODE_TRILL_ILLEGAL_INNER_MC
#define ARAD_PP_TRAP_CODE_MY_MAC_AND_MPLS_DISABLE            SOC_PPC_TRAP_CODE_MY_MAC_AND_MPLS_DISABLE
#define ARAD_PP_TRAP_CODE_MY_MAC_AND_ARP                     SOC_PPC_TRAP_CODE_MY_MAC_AND_ARP
#define ARAD_PP_TRAP_CODE_MY_MAC_AND_UNKNOWN_L3              SOC_PPC_TRAP_CODE_MY_MAC_AND_UNKNOWN_L3
#define ARAD_PP_TRAP_CODE_MPLS_LABEL_VALUE_0                 SOC_PPC_TRAP_CODE_MPLS_LABEL_VALUE_0
#define ARAD_PP_TRAP_CODE_MPLS_LABEL_VALUE_1                 SOC_PPC_TRAP_CODE_MPLS_LABEL_VALUE_1
#define ARAD_PP_TRAP_CODE_MPLS_LABEL_VALUE_2                 SOC_PPC_TRAP_CODE_MPLS_LABEL_VALUE_2
#define ARAD_PP_TRAP_CODE_MPLS_LABEL_VALUE_3                 SOC_PPC_TRAP_CODE_MPLS_LABEL_VALUE_3
#define ARAD_PP_TRAP_CODE_MPLS_NO_RESOURCES                  SOC_PPC_TRAP_CODE_MPLS_NO_RESOURCES
#define ARAD_PP_TRAP_CODE_INVALID_LABEL_IN_RANGE             SOC_PPC_TRAP_CODE_INVALID_LABEL_IN_RANGE
#define ARAD_PP_TRAP_CODE_MPLS_INVALID_LABEL_IN_SEM          SOC_PPC_TRAP_CODE_MPLS_INVALID_LABEL_IN_SEM
#define ARAD_PP_TRAP_CODE_MPLS_LSP_BOS                       SOC_PPC_TRAP_CODE_MPLS_LSP_BOS
#define ARAD_PP_TRAP_CODE_MPLS_PWE_NO_BOS_LABEL_14           SOC_PPC_TRAP_CODE_MPLS_PWE_NO_BOS_LABEL_14
#define ARAD_PP_TRAP_CODE_MPLS_PWE_NO_BOS                    SOC_PPC_TRAP_CODE_MPLS_PWE_NO_BOS
#define ARAD_PP_TRAP_CODE_MPLS_VRF_NO_BOS                    SOC_PPC_TRAP_CODE_MPLS_VRF_NO_BOS
#define ARAD_PP_TRAP_CODE_MPLS_TERM_TTL_0                    SOC_PPC_TRAP_CODE_MPLS_TERM_TTL_0
#define ARAD_PP_TRAP_CODE_MPLS_TERM_CONTROL_WORD_TRAP        SOC_PPC_TRAP_CODE_MPLS_TERM_CONTROL_WORD_TRAP
#define ARAD_PP_TRAP_CODE_MPLS_TERM_CONTROL_WORD_DROP        SOC_PPC_TRAP_CODE_MPLS_TERM_CONTROL_WORD_DROP
#define ARAD_PP_TRAP_CODE_IPV4_TERM_VERSION_ERROR            SOC_PPC_TRAP_CODE_IPV4_TERM_VERSION_ERROR
#define ARAD_PP_TRAP_CODE_IPV4_TERM_CHECKSUM_ERROR           SOC_PPC_TRAP_CODE_IPV4_TERM_CHECKSUM_ERROR
#define ARAD_PP_TRAP_CODE_IPV4_TERM_HEADER_LENGTH_ERROR      SOC_PPC_TRAP_CODE_IPV4_TERM_HEADER_LENGTH_ERROR
#define ARAD_PP_TRAP_CODE_IPV4_TERM_TOTAL_LENGTH_ERROR       SOC_PPC_TRAP_CODE_IPV4_TERM_TOTAL_LENGTH_ERROR
#define ARAD_PP_TRAP_CODE_IPV4_TERM_TTL0                     SOC_PPC_TRAP_CODE_IPV4_TERM_TTL0
#define ARAD_PP_TRAP_CODE_IPV4_TERM_HAS_OPTIONS              SOC_PPC_TRAP_CODE_IPV4_TERM_HAS_OPTIONS
#define ARAD_PP_TRAP_CODE_IPV4_TERM_TTL1                     SOC_PPC_TRAP_CODE_IPV4_TERM_TTL1
#define ARAD_PP_TRAP_CODE_IPV4_TERM_SIP_EQUAL_DIP            SOC_PPC_TRAP_CODE_IPV4_TERM_SIP_EQUAL_DIP
#define ARAD_PP_TRAP_CODE_IPV4_TERM_DIP_ZERO                 SOC_PPC_TRAP_CODE_IPV4_TERM_DIP_ZERO
#define ARAD_PP_TRAP_CODE_IPV4_TERM_SIP_IS_MC                SOC_PPC_TRAP_CODE_IPV4_TERM_SIP_IS_MC
#define ARAD_PP_TRAP_CODE_CFM_ACCELERATED_INGRESS            SOC_PPC_TRAP_CODE_CFM_ACCELERATED_INGRESS
#define ARAD_PP_TRAP_CODE_ILLEGEL_PFC                        SOC_PPC_TRAP_CODE_ILLEGEL_PFC
#define ARAD_PP_TRAP_CODE_SA_DROP_0                          SOC_PPC_TRAP_CODE_SA_DROP_0
#define ARAD_PP_TRAP_CODE_SA_DROP_1                          SOC_PPC_TRAP_CODE_SA_DROP_1
#define ARAD_PP_TRAP_CODE_SA_DROP_2                          SOC_PPC_TRAP_CODE_SA_DROP_2
#define ARAD_PP_TRAP_CODE_SA_DROP_3                          SOC_PPC_TRAP_CODE_SA_DROP_3
#define ARAD_PP_TRAP_CODE_SA_NOT_FOUND_0                     SOC_PPC_TRAP_CODE_SA_NOT_FOUND_0
#define ARAD_PP_TRAP_CODE_SA_NOT_FOUND_1                     SOC_PPC_TRAP_CODE_SA_NOT_FOUND_1
#define ARAD_PP_TRAP_CODE_SA_NOT_FOUND_2                     SOC_PPC_TRAP_CODE_SA_NOT_FOUND_2
#define ARAD_PP_TRAP_CODE_SA_NOT_FOUND_3                     SOC_PPC_TRAP_CODE_SA_NOT_FOUND_3
#define ARAD_PP_TRAP_CODE_UNKNOWN_DA_0                       SOC_PPC_TRAP_CODE_UNKNOWN_DA_0
#define ARAD_PP_TRAP_CODE_UNKNOWN_DA_1                       SOC_PPC_TRAP_CODE_UNKNOWN_DA_1
#define ARAD_PP_TRAP_CODE_UNKNOWN_DA_2                       SOC_PPC_TRAP_CODE_UNKNOWN_DA_2
#define ARAD_PP_TRAP_CODE_UNKNOWN_DA_3                       SOC_PPC_TRAP_CODE_UNKNOWN_DA_3
#define ARAD_PP_TRAP_CODE_UNKNOWN_DA_4                       SOC_PPC_TRAP_CODE_UNKNOWN_DA_4
#define ARAD_PP_TRAP_CODE_UNKNOWN_DA_5                       SOC_PPC_TRAP_CODE_UNKNOWN_DA_5
#define ARAD_PP_TRAP_CODE_UNKNOWN_DA_6                       SOC_PPC_TRAP_CODE_UNKNOWN_DA_6
#define ARAD_PP_TRAP_CODE_UNKNOWN_DA_7                       SOC_PPC_TRAP_CODE_UNKNOWN_DA_7
#define ARAD_PP_TRAP_CODE_ELK_ERROR                          SOC_PPC_TRAP_CODE_ELK_ERROR
#define ARAD_PP_TRAP_CODE_DA_NOT_FOUND_0                     SOC_PPC_TRAP_CODE_DA_NOT_FOUND_0
#define ARAD_PP_TRAP_CODE_DA_NOT_FOUND_1                     SOC_PPC_TRAP_CODE_DA_NOT_FOUND_1
#define ARAD_PP_TRAP_CODE_DA_NOT_FOUND_2                     SOC_PPC_TRAP_CODE_DA_NOT_FOUND_2
#define ARAD_PP_TRAP_CODE_DA_NOT_FOUND_3                     SOC_PPC_TRAP_CODE_DA_NOT_FOUND_3
#define ARAD_PP_TRAP_CODE_P2P_MISCONFIGURATION               SOC_PPC_TRAP_CODE_P2P_MISCONFIGURATION
#define ARAD_PP_TRAP_CODE_SAME_INTERFACE                     SOC_PPC_TRAP_CODE_SAME_INTERFACE
#define ARAD_PP_TRAP_CODE_TRILL_UNKNOWN_UC                   SOC_PPC_TRAP_CODE_TRILL_UNKNOWN_UC
#define ARAD_PP_TRAP_CODE_TRILL_UNKNOWN_MC                   SOC_PPC_TRAP_CODE_TRILL_UNKNOWN_MC
#define ARAD_PP_TRAP_CODE_UC_LOOSE_RPF_FAIL                  SOC_PPC_TRAP_CODE_UC_LOOSE_RPF_FAIL
#define ARAD_PP_TRAP_CODE_DEFAULT_UCV6                       SOC_PPC_TRAP_CODE_DEFAULT_UCV6
#define ARAD_PP_TRAP_CODE_DEFAULT_MCV6                       SOC_PPC_TRAP_CODE_DEFAULT_MCV6
#define ARAD_PP_TRAP_CODE_MPLS_P2P_NO_BOS                    SOC_PPC_TRAP_CODE_MPLS_P2P_NO_BOS
#define ARAD_PP_TRAP_CODE_MPLS_CONTROL_WORD_TRAP             SOC_PPC_TRAP_CODE_MPLS_CONTROL_WORD_TRAP
#define ARAD_PP_TRAP_CODE_MPLS_CONTROL_WORD_DROP             SOC_PPC_TRAP_CODE_MPLS_CONTROL_WORD_DROP
#define ARAD_PP_TRAP_CODE_MPLS_UNKNOWN_LABEL                 SOC_PPC_TRAP_CODE_MPLS_UNKNOWN_LABEL
#define ARAD_PP_TRAP_CODE_MPLS_P2P_MPLSX4                    SOC_PPC_TRAP_CODE_MPLS_P2P_MPLSX4
#define ARAD_PP_TRAP_CODE_ETH_L2CP_PEER                      SOC_PPC_TRAP_CODE_ETH_L2CP_PEER
#define ARAD_PP_TRAP_CODE_ETH_L2CP_DROP                      SOC_PPC_TRAP_CODE_ETH_L2CP_DROP
#define ARAD_PP_TRAP_CODE_ETH_FL_IGMP_MEMBERSHIP_QUERY       SOC_PPC_TRAP_CODE_ETH_FL_IGMP_MEMBERSHIP_QUERY
#define ARAD_PP_TRAP_CODE_ETH_FL_IGMP_REPORT_LEAVE_MSG       SOC_PPC_TRAP_CODE_ETH_FL_IGMP_REPORT_LEAVE_MSG
#define ARAD_PP_TRAP_CODE_ETH_FL_IGMP_UNDEFINED              SOC_PPC_TRAP_CODE_ETH_FL_IGMP_UNDEFINED
#define ARAD_PP_TRAP_CODE_ETH_FL_ICMPV6_MLD_MC_LISTENER_QUERY SOC_PPC_TRAP_CODE_ETH_FL_ICMPV6_MLD_MC_LISTENER_QUERY
#define ARAD_PP_TRAP_CODE_ETH_FL_ICMPV6_MLD_REPORT_DONE      SOC_PPC_TRAP_CODE_ETH_FL_ICMPV6_MLD_REPORT_DONE
#define ARAD_PP_TRAP_CODE_ETH_FL_ICMPV6_MLD_UNDEFINED        SOC_PPC_TRAP_CODE_ETH_FL_ICMPV6_MLD_UNDEFINED
#define ARAD_PP_TRAP_CODE_IPV4_VERSION_ERROR                 SOC_PPC_TRAP_CODE_IPV4_VERSION_ERROR
#define ARAD_PP_TRAP_CODE_IPV4_CHECKSUM_ERROR                SOC_PPC_TRAP_CODE_IPV4_CHECKSUM_ERROR
#define ARAD_PP_TRAP_CODE_IPV4_HEADER_LENGTH_ERROR           SOC_PPC_TRAP_CODE_IPV4_HEADER_LENGTH_ERROR
#define ARAD_PP_TRAP_CODE_IPV4_TOTAL_LENGTH_ERROR            SOC_PPC_TRAP_CODE_IPV4_TOTAL_LENGTH_ERROR
#define ARAD_PP_TRAP_CODE_IPV4_TTL0                          SOC_PPC_TRAP_CODE_IPV4_TTL0
#define ARAD_PP_TRAP_CODE_IPV4_HAS_OPTIONS                   SOC_PPC_TRAP_CODE_IPV4_HAS_OPTIONS
#define ARAD_PP_TRAP_CODE_IPV4_TTL1                          SOC_PPC_TRAP_CODE_IPV4_TTL1
#define ARAD_PP_TRAP_CODE_IPV4_SIP_EQUAL_DIP                 SOC_PPC_TRAP_CODE_IPV4_SIP_EQUAL_DIP
#define ARAD_PP_TRAP_CODE_IPV4_DIP_ZERO                      SOC_PPC_TRAP_CODE_IPV4_DIP_ZERO
#define ARAD_PP_TRAP_CODE_IPV4_SIP_IS_MC                     SOC_PPC_TRAP_CODE_IPV4_SIP_IS_MC
#define ARAD_PP_TRAP_CODE_IPV4_TUNNEL_TERMINATION_AND_FRAGMENTED SOC_PPC_TRAP_CODE_IPV4_TUNNEL_TERMINATION_AND_FRAGMENTED
#define ARAD_PP_TRAP_CODE_IPV6_VERSION_ERROR                 SOC_PPC_TRAP_CODE_IPV6_VERSION_ERROR
#define ARAD_PP_TRAP_CODE_IPV6_HOP_COUNT0                    SOC_PPC_TRAP_CODE_IPV6_HOP_COUNT0
#define ARAD_PP_TRAP_CODE_IPV6_HOP_COUNT1                    SOC_PPC_TRAP_CODE_IPV6_HOP_COUNT1
#define ARAD_PP_TRAP_CODE_IPV6_UNSPECIFIED_DESTINATION       SOC_PPC_TRAP_CODE_IPV6_UNSPECIFIED_DESTINATION
#define ARAD_PP_TRAP_CODE_IPV6_LOOPBACK_ADDRESS              SOC_PPC_TRAP_CODE_IPV6_LOOPBACK_ADDRESS
#define ARAD_PP_TRAP_CODE_IPV6_MULTICAST_SOURCE              SOC_PPC_TRAP_CODE_IPV6_MULTICAST_SOURCE
#define ARAD_PP_TRAP_CODE_IPV6_NEXT_HEADER_NULL              SOC_PPC_TRAP_CODE_IPV6_NEXT_HEADER_NULL
#define ARAD_PP_TRAP_CODE_IPV6_UNSPECIFIED_SOURCE            SOC_PPC_TRAP_CODE_IPV6_UNSPECIFIED_SOURCE
#define ARAD_PP_TRAP_CODE_IPV6_LOCAL_LINK_DESTINATION        SOC_PPC_TRAP_CODE_IPV6_LOCAL_LINK_DESTINATION
#define ARAD_PP_TRAP_CODE_IPV6_LOCAL_SITE_DESTINATION        SOC_PPC_TRAP_CODE_IPV6_LOCAL_SITE_DESTINATION
#define ARAD_PP_TRAP_CODE_IPV6_LOCAL_LINK_SOURCE             SOC_PPC_TRAP_CODE_IPV6_LOCAL_LINK_SOURCE
#define ARAD_PP_TRAP_CODE_IPV6_LOCAL_SITE_SOURCE             SOC_PPC_TRAP_CODE_IPV6_LOCAL_SITE_SOURCE
#define ARAD_PP_TRAP_CODE_IPV6_IPV4_COMPATIBLE_DESTINATION   SOC_PPC_TRAP_CODE_IPV6_IPV4_COMPATIBLE_DESTINATION
#define ARAD_PP_TRAP_CODE_IPV6_IPV4_MAPPED_DESTINATION       SOC_PPC_TRAP_CODE_IPV6_IPV4_MAPPED_DESTINATION
#define ARAD_PP_TRAP_CODE_IPV6_MULTICAST_DESTINATION         SOC_PPC_TRAP_CODE_IPV6_MULTICAST_DESTINATION
#define ARAD_PP_TRAP_CODE_MPLS_TTL0                          SOC_PPC_TRAP_CODE_MPLS_TTL0
#define ARAD_PP_TRAP_CODE_MPLS_TTL1                          SOC_PPC_TRAP_CODE_MPLS_TTL1
#define ARAD_PP_TRAP_CODE_TCP_SN_FLAGS_ZERO                  SOC_PPC_TRAP_CODE_TCP_SN_FLAGS_ZERO
#define ARAD_PP_TRAP_CODE_TCP_SN_ZERO_FLAGS_SET              SOC_PPC_TRAP_CODE_TCP_SN_ZERO_FLAGS_SET
#define ARAD_PP_TRAP_CODE_TCP_SYN_FIN                        SOC_PPC_TRAP_CODE_TCP_SYN_FIN
#define ARAD_PP_TRAP_CODE_TCP_EQUAL_PORTS                    SOC_PPC_TRAP_CODE_TCP_EQUAL_PORTS
#define ARAD_PP_TRAP_CODE_TCP_FRAGMENT_INCOMPLETE_HEADER     SOC_PPC_TRAP_CODE_TCP_FRAGMENT_INCOMPLETE_HEADER
#define ARAD_PP_TRAP_CODE_TCP_FRAGMENT_OFFSET_LT8            SOC_PPC_TRAP_CODE_TCP_FRAGMENT_OFFSET_LT8
#define ARAD_PP_TRAP_CODE_UDP_EQUAL_PORTS                    SOC_PPC_TRAP_CODE_UDP_EQUAL_PORTS
#define ARAD_PP_TRAP_CODE_ICMP_DATA_GT_576                   SOC_PPC_TRAP_CODE_ICMP_DATA_GT_576
#define ARAD_PP_TRAP_CODE_ICMP_FRAGMENTED                    SOC_PPC_TRAP_CODE_ICMP_FRAGMENTED
#define ARAD_PP_TRAP_CODE_GENERAL                            SOC_PPC_TRAP_CODE_GENERAL
#define ARAD_PP_TRAP_CODE_FACILITY_INVALID                   SOC_PPC_TRAP_CODE_FACILITY_INVALID
#define ARAD_PP_TRAP_CODE_FEC_ENTRY_ACCESSED                 SOC_PPC_TRAP_CODE_FEC_ENTRY_ACCESSED
#define ARAD_PP_TRAP_CODE_UC_STRICT_RPF_FAIL                 SOC_PPC_TRAP_CODE_UC_STRICT_RPF_FAIL
#define ARAD_PP_TRAP_CODE_MC_EXPLICIT_RPF_FAIL               SOC_PPC_TRAP_CODE_MC_EXPLICIT_RPF_FAIL
#define ARAD_PP_TRAP_CODE_MC_USE_SIP_AS_IS_RPF_FAIL          SOC_PPC_TRAP_CODE_MC_USE_SIP_AS_IS_RPF_FAIL
#define ARAD_PP_TRAP_CODE_MC_USE_SIP_RPF_FAIL                SOC_PPC_TRAP_CODE_MC_USE_SIP_RPF_FAIL
#define ARAD_PP_TRAP_CODE_MC_USE_SIP_ECMP                    SOC_PPC_TRAP_CODE_MC_USE_SIP_ECMP
#define ARAD_PP_TRAP_CODE_ICMP_REDIRECT                      SOC_PPC_TRAP_CODE_ICMP_REDIRECT
#define ARAD_PP_TRAP_CODE_MP_NON_ACCELERATED                 SOC_PPC_TRAP_CODE_MP_NON_ACCELERATED
#define ARAD_PP_TRAP_CODE_MORE_THAN_TWO_ING_METERS           SOC_PPC_TRAP_CODE_MORE_THAN_TWO_ING_METERS
#define ARAD_PP_TRAP_CODE_PWE_INVALID_PROTOCOL               SOC_PPC_TRAP_CODE_PWE_INVALID_PROTOCOL
#define ARAD_PP_TRAP_CODE_IP_OVER_MPLS                       SOC_PPC_TRAP_CODE_IP_OVER_MPLS
#define ARAD_PP_TRAP_CODE_TIME_SYNC                          SOC_PPC_TRAP_CODE_TIME_SYNC
#define ARAD_PP_TRAP_CODE_AC_KEY_MISS                        SOC_PPC_TRAP_CODE_AC_KEY_MISS
#define ARAD_PP_TRAP_CODE_EG_MEP_NON_ACCELERATED             SOC_PPC_TRAP_CODE_EG_MEP_NON_ACCELERATED
#define ARAD_PP_TRAP_CODE_EG_FILTER_VSI_MEMBERSHIP           SOC_PPC_TRAP_CODE_EG_FILTER_VSI_MEMBERSHIP
#define ARAD_PP_TRAP_CODE_EG_FILTER_HAIR_PIN                 SOC_PPC_TRAP_CODE_EG_FILTER_HAIR_PIN
#define ARAD_PP_TRAP_CODE_EG_FILTER_SPLIT_HORIZON            SOC_PPC_TRAP_CODE_EG_FILTER_SPLIT_HORIZON
#define ARAD_PP_TRAP_CODE_EG_FILTER_UNKNOWN_DA_UC            SOC_PPC_TRAP_CODE_EG_FILTER_UNKNOWN_DA_UC
#define ARAD_PP_TRAP_CODE_EG_FILTER_UNKNOWN_DA_MC            SOC_PPC_TRAP_CODE_EG_FILTER_UNKNOWN_DA_MC
#define ARAD_PP_TRAP_CODE_EG_FILTER_UNKNOWN_DA_BC            SOC_PPC_TRAP_CODE_EG_FILTER_UNKNOWN_DA_BC
#define ARAD_PP_TRAP_CODE_EG_FILTER_MTU_VIOLATE              SOC_PPC_TRAP_CODE_EG_FILTER_MTU_VIOLATE
#define ARAD_PP_TRAP_CODE_EG_FILTER_STP                      SOC_PPC_TRAP_CODE_EG_FILTER_STP
#define ARAD_PP_TRAP_CODE_EG_FILTER_ACCEPT_FRAME             SOC_PPC_TRAP_CODE_EG_FILTER_ACCEPT_FRAME
#define ARAD_PP_TRAP_CODE_USER_OAMP                          SOC_PPC_TRAP_CODE_USER_OAMP
#define ARAD_PP_TRAP_CODE_USER_ETH_OAM_ACCELERATED           SOC_PPC_TRAP_CODE_USER_ETH_OAM_ACCELERATED
#define ARAD_PP_TRAP_CODE_USER_MPLS_OAM_ACCELERATED          SOC_PPC_TRAP_CODE_USER_MPLS_OAM_ACCELERATED
#define ARAD_PP_TRAP_CODE_USER_BFD_IP_OAM_TUNNEL_ACCELERATED SOC_PPC_TRAP_CODE_USER_BFD_IP_OAM_TUNNEL_ACCELERATED
#define ARAD_PP_TRAP_CODE_USER_BFD_PWE_OAM_ACCELERATED       SOC_PPC_TRAP_CODE_USER_BFD_PWE_OAM_ACCELERATED
#define ARAD_PP_TRAP_CODE_USER_ETH_OAM_UP_ACCELERATED        SOC_PPC_TRAP_CODE_USER_ETH_OAM_UP_ACCELERATED
/* arad only */
#define ARAD_PP_TRAP_CODE_ETHER_IP_VERSION_ERROR                      SOC_PPC_TRAP_CODE_ETHER_IP_VERSION_ERROR
#define ARAD_PP_TRAP_CODE_LIF_PROTECT_PATH_INVALID                    SOC_PPC_TRAP_CODE_LIF_PROTECT_PATH_INVALID
#define ARAD_PP_TRAP_CODE_TRILL_NO_ADJACENT                           SOC_PPC_TRAP_CODE_TRILL_NO_ADJACENT
#define ARAD_PP_TRAP_CODE_MPLS_INVALID_LIF                            SOC_PPC_TRAP_CODE_MPLS_INVALID_LIF
#define ARAD_PP_TRAP_CODE_MPLS_TERM_ERROR                             SOC_PPC_TRAP_CODE_MPLS_TERM_ERROR
#define ARAD_PP_TRAP_CODE_MY_B_MAC_MC_CONTINUE                        SOC_PPC_TRAP_CODE_MY_B_MAC_MC_CONTINUE
#define ARAD_PP_TRAP_CODE_MPLS_UNEXPECTED_NO_BOS                      SOC_PPC_TRAP_CODE_MPLS_UNEXPECTED_NO_BOS
#define ARAD_PP_TRAP_CODE_MPLS_UNEXPECTED_BOS                         SOC_PPC_TRAP_CODE_MPLS_UNEXPECTED_BOS
#define ARAD_PP_TRAP_CODE_MPLS_TERM_TTL_1                             SOC_PPC_TRAP_CODE_MPLS_TERM_TTL_1
#define ARAD_PP_TRAP_CODE_1588_PACKET_0                               SOC_PPC_TRAP_CODE_1588_PACKET_0
#define ARAD_PP_TRAP_CODE_1588_PACKET_1                               SOC_PPC_TRAP_CODE_1588_PACKET_1
#define ARAD_PP_TRAP_CODE_1588_PACKET_2                               SOC_PPC_TRAP_CODE_1588_PACKET_2
#define ARAD_PP_TRAP_CODE_1588_PACKET_3                               SOC_PPC_TRAP_CODE_1588_PACKET_3
#define ARAD_PP_TRAP_CODE_1588_PACKET_4                               SOC_PPC_TRAP_CODE_1588_PACKET_4
#define ARAD_PP_TRAP_CODE_1588_PACKET_5                               SOC_PPC_TRAP_CODE_1588_PACKET_5
#define ARAD_PP_TRAP_CODE_1588_PACKET_6                               SOC_PPC_TRAP_CODE_1588_PACKET_6
#define ARAD_PP_TRAP_CODE_1588_PACKET_7                               SOC_PPC_TRAP_CODE_1588_PACKET_7
#define ARAD_PP_TRAP_CODE_FCOE_SRC_SA_MISMATCH                        SOC_PPC_TRAP_CODE_FCOE_SRC_SA_MISMATCH
#define ARAD_PP_TRAP_CODE_SIP_TRANSLANT                               SOC_PPC_TRAP_CODE_SIP_TRANSLANT
#define ARAD_PP_TRAP_CODE_ELK_REJECTED                                SOC_PPC_TRAP_CODE_ELK_REJECTED
#define ARAD_PP_TRAP_CODE_TRILL_DISABLE_BRIDGE_IF_DESIGNATED          SOC_PPC_TRAP_CODE_TRILL_DISABLE_BRIDGE_IF_DESIGNATED
#define ARAD_PP_TRAP_CODE_TRAP_ETH_OAM                                SOC_PPC_TRAP_CODE_TRAP_ETH_OAM
#define ARAD_PP_TRAP_CODE_TRAP_Y1731_O_MPLS_TP                        SOC_PPC_TRAP_CODE_TRAP_Y1731_O_MPLS_TP
#define ARAD_PP_TRAP_CODE_TRAP_Y1731_O_PWE                            SOC_PPC_TRAP_CODE_TRAP_Y1731_O_PWE
#define ARAD_PP_TRAP_CODE_TRAP_BFD_O_IPV4                             SOC_PPC_TRAP_CODE_TRAP_BFD_O_IPV4
#define ARAD_PP_TRAP_CODE_TRAP_BFD_O_MPLS                             SOC_PPC_TRAP_CODE_TRAP_BFD_O_MPLS
#define ARAD_PP_TRAP_CODE_TRAP_BFD_O_PWE                              SOC_PPC_TRAP_CODE_TRAP_BFD_O_PWE
#define ARAD_PP_TRAP_CODE_TRAP_BFDCC_O_MPLS_TP                        SOC_PPC_TRAP_CODE_TRAP_BFDCC_O_MPLS_TP
#define ARAD_PP_TRAP_CODE_TRAP_BFDCV_O_MPLS_TP                        SOC_PPC_TRAP_CODE_TRAP_BFDCV_O_MPLS_TP
#define ARAD_PP_TRAP_CODE_OAM_LEVEL                                   SOC_PPC_TRAP_CODE_OAM_LEVEL
#define ARAD_PP_TRAP_CODE_OAM_PASSIVE                                 SOC_PPC_TRAP_CODE_OAM_PASSIVE
#define ARAD_PP_TRAP_CODE_ARP_FLP_FAIL                                SOC_PPC_TRAP_CODE_ARP_FLP_FAIL
#define ARAD_PP_TRAP_CODE_FCOE_FCF_FLP_LOOKUP_FAIL                    SOC_PPC_TRAP_CODE_FCOE_FCF_FLP_LOOKUP_FAIL

/*Jeircho only*/
#define ARAD_PP_TRAP_CODE_INNER_IP_COMP_MC_INVALID_IP_0               SOC_PPC_TRAP_CODE_INNER_IP_COMP_MC_INVALID_IP_0
#define ARAD_PP_TRAP_CODE_MPLS_ILLEGAL_LABEL                          SOC_PPC_TRAP_CODE_MPLS_ILLEGAL_LABEL
#define ARAD_PP_TRAP_CODE_INNER_ETHERNET_MY_MAC_IP_DISABLED          SOC_PPC_TRAP_CODE_INNER_ETHERNET_MY_MAC_IP_DISABLED


/* } */
#define ARAD_PP_TRAP_CODE_USER_DEFINED_0                     SOC_PPC_TRAP_CODE_USER_DEFINED_0
#define ARAD_PP_TRAP_CODE_USER_DEFINED_1                     SOC_PPC_TRAP_CODE_USER_DEFINED_1
#define ARAD_PP_TRAP_CODE_USER_DEFINED_2                     SOC_PPC_TRAP_CODE_USER_DEFINED_2
#define ARAD_PP_TRAP_CODE_USER_DEFINED_3                     SOC_PPC_TRAP_CODE_USER_DEFINED_3
#define ARAD_PP_TRAP_CODE_USER_DEFINED_4                     SOC_PPC_TRAP_CODE_USER_DEFINED_4
#define ARAD_PP_TRAP_CODE_USER_DEFINED_5                     SOC_PPC_TRAP_CODE_USER_DEFINED_5
#define ARAD_PP_TRAP_CODE_USER_DEFINED_6                     SOC_PPC_TRAP_CODE_USER_DEFINED_6
#define ARAD_PP_TRAP_CODE_USER_DEFINED_7                     SOC_PPC_TRAP_CODE_USER_DEFINED_7
#define ARAD_PP_TRAP_CODE_USER_DEFINED_8                     SOC_PPC_TRAP_CODE_USER_DEFINED_8
#define ARAD_PP_TRAP_CODE_USER_DEFINED_9                     SOC_PPC_TRAP_CODE_USER_DEFINED_9
#define ARAD_PP_TRAP_CODE_USER_DEFINED_10                    SOC_PPC_TRAP_CODE_USER_DEFINED_10
#define ARAD_PP_TRAP_CODE_USER_DEFINED_11                    SOC_PPC_TRAP_CODE_USER_DEFINED_11
#define ARAD_PP_TRAP_CODE_USER_DEFINED_12                    SOC_PPC_TRAP_CODE_USER_DEFINED_12
#define ARAD_PP_TRAP_CODE_USER_DEFINED_13                    SOC_PPC_TRAP_CODE_USER_DEFINED_13
#define ARAD_PP_TRAP_CODE_USER_DEFINED_14                    SOC_PPC_TRAP_CODE_USER_DEFINED_14
#define ARAD_PP_TRAP_CODE_USER_DEFINED_15                    SOC_PPC_TRAP_CODE_USER_DEFINED_15
#define ARAD_PP_TRAP_CODE_USER_DEFINED_16                    SOC_PPC_TRAP_CODE_USER_DEFINED_16
#define ARAD_PP_TRAP_CODE_USER_DEFINED_17                    SOC_PPC_TRAP_CODE_USER_DEFINED_17
#define ARAD_PP_TRAP_CODE_USER_DEFINED_18                    SOC_PPC_TRAP_CODE_USER_DEFINED_18
#define ARAD_PP_TRAP_CODE_USER_DEFINED_19                    SOC_PPC_TRAP_CODE_USER_DEFINED_19
#define ARAD_PP_TRAP_CODE_USER_DEFINED_20                    SOC_PPC_TRAP_CODE_USER_DEFINED_20
#define ARAD_PP_TRAP_CODE_USER_DEFINED_21                    SOC_PPC_TRAP_CODE_USER_DEFINED_21
#define ARAD_PP_TRAP_CODE_USER_DEFINED_22                    SOC_PPC_TRAP_CODE_USER_DEFINED_22
#define ARAD_PP_TRAP_CODE_USER_DEFINED_23                    SOC_PPC_TRAP_CODE_USER_DEFINED_23
#define ARAD_PP_TRAP_CODE_USER_DEFINED_24                    SOC_PPC_TRAP_CODE_USER_DEFINED_24
#define ARAD_PP_TRAP_CODE_USER_DEFINED_25                    SOC_PPC_TRAP_CODE_USER_DEFINED_25
#define ARAD_PP_TRAP_CODE_USER_DEFINED_26                    SOC_PPC_TRAP_CODE_USER_DEFINED_26
#define ARAD_PP_TRAP_CODE_USER_DEFINED_27                    SOC_PPC_TRAP_CODE_USER_DEFINED_27
#define ARAD_PP_TRAP_CODE_USER_DEFINED_28                    SOC_PPC_TRAP_CODE_USER_DEFINED_28
#define ARAD_PP_TRAP_CODE_USER_DEFINED_29                    SOC_PPC_TRAP_CODE_USER_DEFINED_29
#define ARAD_PP_TRAP_CODE_USER_DEFINED_30                    SOC_PPC_TRAP_CODE_USER_DEFINED_30
#define ARAD_PP_TRAP_CODE_USER_DEFINED_31                    SOC_PPC_TRAP_CODE_USER_DEFINED_31
#define ARAD_PP_TRAP_CODE_USER_DEFINED_32                    SOC_PPC_TRAP_CODE_USER_DEFINED_32
#define ARAD_PP_TRAP_CODE_USER_DEFINED_33                    SOC_PPC_TRAP_CODE_USER_DEFINED_33
#define ARAD_PP_TRAP_CODE_USER_DEFINED_34                    SOC_PPC_TRAP_CODE_USER_DEFINED_34
#define ARAD_PP_TRAP_CODE_USER_DEFINED_35                    SOC_PPC_TRAP_CODE_USER_DEFINED_35
#define ARAD_PP_TRAP_CODE_USER_DEFINED_36                    SOC_PPC_TRAP_CODE_USER_DEFINED_36
#define ARAD_PP_TRAP_CODE_USER_DEFINED_37                    SOC_PPC_TRAP_CODE_USER_DEFINED_37
#define ARAD_PP_TRAP_CODE_USER_DEFINED_38                    SOC_PPC_TRAP_CODE_USER_DEFINED_38
#define ARAD_PP_TRAP_CODE_USER_DEFINED_39                    SOC_PPC_TRAP_CODE_USER_DEFINED_39
#define ARAD_PP_TRAP_CODE_USER_DEFINED_40                    SOC_PPC_TRAP_CODE_USER_DEFINED_40
#define ARAD_PP_TRAP_CODE_USER_DEFINED_41                    SOC_PPC_TRAP_CODE_USER_DEFINED_41
#define ARAD_PP_TRAP_CODE_USER_DEFINED_42                    SOC_PPC_TRAP_CODE_USER_DEFINED_42
#define ARAD_PP_TRAP_CODE_USER_DEFINED_43                    SOC_PPC_TRAP_CODE_USER_DEFINED_43
#define ARAD_PP_TRAP_CODE_USER_DEFINED_44                    SOC_PPC_TRAP_CODE_USER_DEFINED_44
#define ARAD_PP_TRAP_CODE_USER_DEFINED_45                    SOC_PPC_TRAP_CODE_USER_DEFINED_45
#define ARAD_PP_TRAP_CODE_USER_DEFINED_46                    SOC_PPC_TRAP_CODE_USER_DEFINED_46
#define ARAD_PP_TRAP_CODE_USER_DEFINED_47                    SOC_PPC_TRAP_CODE_USER_DEFINED_47
#define ARAD_PP_TRAP_CODE_USER_DEFINED_48                    SOC_PPC_TRAP_CODE_USER_DEFINED_48
#define ARAD_PP_TRAP_CODE_USER_DEFINED_49                    SOC_PPC_TRAP_CODE_USER_DEFINED_49
#define ARAD_PP_TRAP_CODE_USER_DEFINED_50                    SOC_PPC_TRAP_CODE_USER_DEFINED_50
#define ARAD_PP_TRAP_CODE_USER_DEFINED_51                    SOC_PPC_TRAP_CODE_USER_DEFINED_51
#define ARAD_PP_TRAP_CODE_USER_DEFINED_52                    SOC_PPC_TRAP_CODE_USER_DEFINED_52
#define ARAD_PP_TRAP_CODE_USER_DEFINED_53                    SOC_PPC_TRAP_CODE_USER_DEFINED_53
#define ARAD_PP_TRAP_CODE_USER_DEFINED_54                    SOC_PPC_TRAP_CODE_USER_DEFINED_54
#define ARAD_PP_TRAP_CODE_USER_DEFINED_55                    SOC_PPC_TRAP_CODE_USER_DEFINED_55
#define ARAD_PP_TRAP_CODE_USER_DEFINED_56                    SOC_PPC_TRAP_CODE_USER_DEFINED_56
#define ARAD_PP_TRAP_CODE_USER_DEFINED_57                    SOC_PPC_TRAP_CODE_USER_DEFINED_57
#define ARAD_PP_TRAP_CODE_USER_DEFINED_58                    SOC_PPC_TRAP_CODE_USER_DEFINED_58
#define ARAD_PP_TRAP_CODE_USER_DEFINED_59                    SOC_PPC_TRAP_CODE_USER_DEFINED_59
#define ARAD_PP_NOF_TRAP_CODES                               SOC_PPC_NOF_TRAP_CODES
#define ARAD_PP_NOF_TRAP_QUALIFIERS                          SOC_PPC_NOF_TRAP_QUALIFIERS
typedef SOC_PPC_TRAP_CODE                                      ARAD_PP_TRAP_CODE;


#define ARAD_PP_TRAP_EG_TYPE_NONE                            SOC_PPC_TRAP_EG_TYPE_NONE
#define ARAD_PP_TRAP_EG_TYPE_NO_VSI_TRANSLATION              SOC_PPC_TRAP_EG_TYPE_NO_VSI_TRANSLATION
#define ARAD_PP_TRAP_EG_TYPE_VSI_MEMBERSHIP                  SOC_PPC_TRAP_EG_TYPE_VSI_MEMBERSHIP
#define ARAD_PP_TRAP_EG_TYPE_ACC_FRM                         SOC_PPC_TRAP_EG_TYPE_ACC_FRM
#define ARAD_PP_TRAP_EG_TYPE_HAIR_PIN                        SOC_PPC_TRAP_EG_TYPE_HAIR_PIN
#define ARAD_PP_TRAP_EG_TYPE_UNKNOWN_DA                      SOC_PPC_TRAP_EG_TYPE_UNKNOWN_DA
#define ARAD_PP_TRAP_EG_TYPE_SPLIT_HORIZON                   SOC_PPC_TRAP_EG_TYPE_SPLIT_HORIZON
#define ARAD_PP_TRAP_EG_TYPE_PRIVATE_VLAN                    SOC_PPC_TRAP_EG_TYPE_PRIVATE_VLAN
#define ARAD_PP_TRAP_EG_TYPE_TTL_SCOPE                       SOC_PPC_TRAP_EG_TYPE_TTL_SCOPE
#define ARAD_PP_TRAP_EG_TYPE_MTU_VIOLATION                   SOC_PPC_TRAP_EG_TYPE_MTU_VIOLATION
#define ARAD_PP_TRAP_EG_TYPE_TRILL_TTL_0                     SOC_PPC_TRAP_EG_TYPE_TRILL_TTL_0
#define ARAD_PP_TRAP_EG_TYPE_TRILL_SAME_INTERFACE            SOC_PPC_TRAP_EG_TYPE_TRILL_SAME_INTERFACE
#define ARAD_PP_TRAP_EG_TYPE_TRILL_BOUNCE_BACK               SOC_PPC_TRAP_EG_TYPE_TRILL_BOUNCE_BACK
#define ARAD_PP_TRAP_EG_TYPE_DSS_STACKING                    SOC_PPC_TRAP_EG_TYPE_DSS_STACKING
#define ARAD_PP_TRAP_EG_TYPE_LAG_MULTICAST                   SOC_PPC_TRAP_EG_TYPE_LAG_MULTICAST
#define ARAD_PP_TRAP_EG_TYPE_EXCLUDE_SRC                     SOC_PPC_TRAP_EG_TYPE_EXCLUDE_SRC
#define ARAD_PP_TRAP_EG_TYPE_CFM_TRAP                        SOC_PPC_TRAP_EG_TYPE_CFM_TRAP
#define ARAD_PP_TRAP_EG_TYPE_ALL                             SOC_PPC_TRAP_EG_TYPE_ALL
#define ARAD_PP_TRAP_EG_TYPE_INVALID_OUT_PORT                  SOC_PPC_TRAP_EG_TYPE_INVALID_OUT_PORT
#define ARAD_PP_TRAP_EG_TYPE_CNM_PACKET                        SOC_PPC_TRAP_EG_TYPE_CNM_PACKET
#define ARAD_PP_TRAP_EG_TYPE_IPV4_VERSION_ERROR                SOC_PPC_TRAP_EG_TYPE_IPV4_VERSION_ERROR
#define ARAD_PP_TRAP_EG_TYPE_IPV4_CHECKSUM_ERROR               SOC_PPC_TRAP_EG_TYPE_IPV4_CHECKSUM_ERROR
#define ARAD_PP_TRAP_EG_TYPE_IPV4_HEADER_LENGTH_ERROR          SOC_PPC_TRAP_EG_TYPE_IPV4_HEADER_LENGTH_ERROR
#define ARAD_PP_TRAP_EG_TYPE_IPV4_TOTAL_LENGTH_ERROR           SOC_PPC_TRAP_EG_TYPE_IPV4_TOTAL_LENGTH_ERROR
#define ARAD_PP_TRAP_EG_TYPE_IP_TTL0                           SOC_PPC_TRAP_EG_TYPE_IP_TTL0
#define ARAD_PP_TRAP_EG_TYPE_IP_HAS_OPTIONS                    SOC_PPC_TRAP_EG_TYPE_IP_HAS_OPTIONS
#define ARAD_PP_TRAP_EG_TYPE_IP_TTL1                           SOC_PPC_TRAP_EG_TYPE_IP_TTL1
#define ARAD_PP_TRAP_EG_TYPE_IPV4_SIP_EQUAL_DIP                SOC_PPC_TRAP_EG_TYPE_IPV4_SIP_EQUAL_DIP
#define ARAD_PP_TRAP_EG_TYPE_IPV4_DIP_ZERO                     SOC_PPC_TRAP_EG_TYPE_IPV4_DIP_ZERO
#define ARAD_PP_TRAP_EG_TYPE_IPV4_SIP_IS_MC                    SOC_PPC_TRAP_EG_TYPE_IPV4_SIP_IS_MC
#define ARAD_PP_TRAP_EG_TYPE_IPV6_UNSPECIFIED_DESTINATION      SOC_PPC_TRAP_EG_TYPE_IPV6_UNSPECIFIED_DESTINATION
#define ARAD_PP_TRAP_EG_TYPE_IPV6_LOOPBACK_ADDRESS             SOC_PPC_TRAP_EG_TYPE_IPV6_LOOPBACK_ADDRESS
#define ARAD_PP_TRAP_EG_TYPE_IPV6_MULTICAST_SOURCE             SOC_PPC_TRAP_EG_TYPE_IPV6_MULTICAST_SOURCE
#define ARAD_PP_TRAP_EG_TYPE_IPV6_UNSPECIFIED_SOURCE           SOC_PPC_TRAP_EG_TYPE_IPV6_UNSPECIFIED_SOURCE
#define ARAD_PP_TRAP_EG_TYPE_IPV6_LOCAL_LINK_DESTINATION       SOC_PPC_TRAP_EG_TYPE_IPV6_LOCAL_LINK_DESTINATION
#define ARAD_PP_TRAP_EG_TYPE_IPV6_LOCAL_SITE_DESTINATION       SOC_PPC_TRAP_EG_TYPE_IPV6_LOCAL_SITE_DESTINATION
#define ARAD_PP_TRAP_EG_TYPE_IPV6_LOCAL_LINK_SOURCE            SOC_PPC_TRAP_EG_TYPE_IPV6_LOCAL_LINK_SOURCE
#define ARAD_PP_TRAP_EG_TYPE_IPV6_LOCAL_SITE_SOURCE            SOC_PPC_TRAP_EG_TYPE_IPV6_LOCAL_SITE_SOURCE
#define ARAD_PP_TRAP_EG_TYPE_IPV6_IPV4_COMPATIBLE_DESTINATION  SOC_PPC_TRAP_EG_TYPE_IPV6_IPV4_COMPATIBLE_DESTINATION
#define ARAD_PP_TRAP_EG_TYPE_IPV6_IPV4_MAPPED_DESTINATION      SOC_PPC_TRAP_EG_TYPE_IPV6_IPV4_MAPPED_DESTINATION
#define ARAD_PP_TRAP_EG_TYPE_IPV6_MULTICAST_DESTINATION        SOC_PPC_TRAP_EG_TYPE_IPV6_MULTICAST_DESTINATION
#define ARAD_PP_TRAP_EG_TYPE_IPV6_HOP_BY_HOP                   SOC_PPC_TRAP_EG_TYPE_IPV6_HOP_BY_HOP
#define ARAD_PP_NOF_TRAP_EG_TYPES                              SOC_PPC_NOF_TRAP_EG_TYPES_ARAD
typedef SOC_PPC_TRAP_EG_TYPE                                   ARAD_PP_TRAP_EG_TYPE;



#define ARAD_PP_TRAP_MGMT_PKT_FRWRD_TYPE_NORMAL                SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE_NORMAL
#define ARAD_PP_TRAP_MGMT_PKT_FRWRD_TYPE_TRAP                  SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE_TRAP
#define ARAD_PP_TRAP_MGMT_PKT_FRWRD_TYPE_SNOOP                 SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE_SNOOP
#define ARAD_PP_TRAP_MGMT_PKT_FRWRD_TYPE_IN_MIRROR             SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE_IN_MIRROR
#define ARAD_PP_NOF_TRAP_MGMT_PKT_FRWRD_TYPES                  SOC_PPC_NOF_TRAP_MGMT_PKT_FRWRD_TYPES
typedef SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE                       ARAD_PP_TRAP_MGMT_PKT_FRWRD_TYPE;


typedef SOC_PPC_TRAP_ACTION_PROFILE_DEST_INFO                  ARAD_PP_TRAP_ACTION_PROFILE_DEST_INFO;
typedef SOC_PPC_TRAP_ACTION_PROFILE_COUNT_INFO                 ARAD_PP_TRAP_ACTION_PROFILE_COUNT_INFO;
typedef SOC_PPC_TRAP_ACTION_PROFILE_METER_INFO                 ARAD_PP_TRAP_ACTION_PROFILE_METER_INFO;
typedef SOC_PPC_TRAP_ACTION_PROFILE_POLICE_INFO                ARAD_PP_TRAP_ACTION_PROFILE_POLICE_INFO;
typedef SOC_PPC_TRAP_ACTION_PROFILE_COS_INFO                   ARAD_PP_TRAP_ACTION_PROFILE_COS_INFO;
typedef SOC_PPC_TRAP_ACTION_PROFILE_PROCESS_INFO               ARAD_PP_TRAP_ACTION_PROFILE_PROCESS_INFO;
typedef SOC_PPC_TRAP_FRWRD_ACTION_PROFILE_INFO                 ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO;
typedef SOC_PPC_TRAP_SNOOP_ACTION_PROFILE_INFO                 ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO;
typedef SOC_PPC_TRAP_EG_ACTION_PROFILE_INFO                    ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO;
typedef SOC_PPC_TRAP_EG_ACTION_HDR_DATA                        ARAD_PP_TRAP_EG_ACTION_HDR_DATA;
typedef SOC_PPC_TRAP_MACT_EVENT_INFO                           ARAD_PP_TRAP_MACT_EVENT_INFO;
typedef SOC_PPC_TRAP_MGMT_PACKET_PARSE_INFO                    ARAD_PP_TRAP_MGMT_PACKET_PARSE_INFO;
typedef SOC_PPC_TRAP_PACKET_INFO                               ARAD_PP_TRAP_PACKET_INFO;

/* } */
/*************
 * GLOBALS   *
 *************/
/* { */

/* } */
/*************
 * FUNCTIONS *
 *************/
/* { */

/*********************************************************************
* NAME:
 *   arad_pp_trap_frwrd_profile_info_set
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Set forwarding action profile information.
 * INPUT:
 *   SOC_SAND_IN  int                                     unit -
 *     Identifier of the device to access.
 *   SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx -
 *     Trap code. AradB range: 0-255. T20E range: 0-255, only
 *     enumarators mentioned as supported in T20e.user can use
 *     values not in the enum for used defined values.
 *   SOC_SAND_IN  ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO          *profile_info -
 *     Information to set to the forwarding profile.
 * REMARKS:
 *   None.
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_frwrd_profile_info_set(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx,
    SOC_SAND_IN  ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO          *profile_info
  );

/*********************************************************************
*     Gets the configuration set by the
 *     "arad_pp_trap_frwrd_profile_info_set" API.
 *     Refer to "arad_pp_trap_frwrd_profile_info_set" API for
 *     details.
*********************************************************************/
uint32
  arad_pp_trap_frwrd_profile_info_get(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx,
    SOC_SAND_OUT ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO          *profile_info
  );

/*********************************************************************
* NAME:
 *   arad_pp_trap_snoop_profile_info_set
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Set snoop action profile information.
 * INPUT:
 *   SOC_SAND_IN  int                                     unit -
 *     Identifier of the device to access.
 *   SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx -
 *     Trap code. AradB range: 0-255. T20E range: 0-255, only
 *     enumarators mentioned as supported in T20E.user can use
 *     values not in the enum for used defined values.
 *   SOC_SAND_IN  ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO          *profile_info -
 *     Information to set to the snoop profile.
 * REMARKS:
 *   None.
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_snoop_profile_info_set(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx,
    SOC_SAND_IN  ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO          *profile_info
  );

/*********************************************************************
*     Gets the configuration set by the
 *     "arad_pp_trap_snoop_profile_info_set" API.
 *     Refer to "arad_pp_trap_snoop_profile_info_set" API for
 *     details.
*********************************************************************/
uint32
  arad_pp_trap_snoop_profile_info_get(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx,
    SOC_SAND_OUT ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO          *profile_info
  );

/*********************************************************************
* NAME:
 *   arad_pp_trap_to_eg_action_map_set
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Maps egress trap type to egress action profile.
 * INPUT:
 *   SOC_SAND_IN  int                                     unit -
 *     Identifier of the device to access.
 *   SOC_SAND_IN  uint32                                      trap_type_bitmap_ndx -
 *     Trap Type bitmap, the cause for trapping/filtering the packets
 *     (for example MTU). Use ARAD_PP_TRAP_EG_TYPE for bit offsets.
 *   SOC_SAND_IN  uint32                                      eg_action_profile -
 *     Egress action profile, to process/forward the packet
 *     according. To set the action pointed by this parameter
 *     use soc_ppd_trap_eg_profile_info_set(). Use
 *     SOC_PPD_TRAP_EG_NO_ACTION in order to bypass this trapping
 *     and then the packet will be processed/forwarded normal
 *     (as no trap was identified).
 * REMARKS:
 *   - Arad-B only. Error is returned if called for T20E.-
 *   In T20E: use soc_ppd_trap_snoop_profile_info_set() and
 *   soc_ppd_trap_frwrd_profile_info_set() to set action for Trap
 *   occurs in the T20E egress.- For part of the
 *   filters/traps (see SOC_PPD_EG_FILTER_PORT_ENABLE) user can
 *   set whether to perform the filter/trap per port. See
 *   soc_ppd_eg_filter_port_info_set()
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_to_eg_action_map_set(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      trap_type_bitmap_ndx,
    SOC_SAND_IN  uint32                                      eg_action_profile
  );

/*********************************************************************
*     Gets the configuration set by the
 *     "arad_pp_trap_to_eg_action_map_set" API.
 *     Refer to "arad_pp_trap_to_eg_action_map_set" API for
 *     details.
*********************************************************************/
uint32
  arad_pp_trap_to_eg_action_map_get(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      trap_type_bitmap_ndx,
    SOC_SAND_OUT uint32                                      *eg_action_profile
  );

/*********************************************************************
* NAME:
 *   arad_pp_trap_eg_profile_info_set
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Set egress action profile information.
 * INPUT:
 *   SOC_SAND_IN  int                                     unit -
 *     Identifier of the device to access.
 *   SOC_SAND_IN  uint32                                      profile_ndx -
 *     Egress action profile. Range: 0 - 8.
 *   SOC_SAND_IN  ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO             *profile_info -
 *     Information to set to the egress profile.
 * REMARKS:
 *   - Arad-B only. Error is returned if called for T20E.-
 *   In T20E: use soc_ppd_trap_snoop_profile_info_set() and
 *   soc_ppd_trap_frwrd_profile_info_set() to set action for Trap
 *   occurs in the T20E egress.- Use
 *   soc_ppd_trap_to_eg_action_map_set() to map trap (reason) to
 *   action profile
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_eg_profile_info_set(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      profile_ndx,
    SOC_SAND_IN  ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO             *profile_info
  );

/*********************************************************************
*     Gets the configuration set by the
 *     "arad_pp_trap_eg_profile_info_set" API.
 *     Refer to "arad_pp_trap_eg_profile_info_set" API for
 *     details.
*********************************************************************/
uint32
  arad_pp_trap_eg_profile_info_get(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      profile_ndx,
    SOC_SAND_OUT ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO             *profile_info
  );

/*********************************************************************
* NAME:
 *   arad_pp_trap_mact_event_get
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Read MACT event from the events FIFO into buffer.
 * INPUT:
 *   SOC_SAND_IN  int                                     unit -
 *     Identifier of the device to access.
 *   SOC_SAND_OUT uint32                                      buff -
 *     ARAD_PP_TRAP_EVENT_BUFF_MAX_SIZE]- Buffer to copy the Event
 *     to. Event is copied to buff starting from buff[0] lsb.
 *   SOC_SAND_OUT uint32                                      *buff_len -
 *     the actual length of the returned buffer (in longs)
 * REMARKS:
 *   None.
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_mact_event_get(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_OUT uint32                                      buff[ARAD_PP_TRAP_EVENT_BUFF_MAX_SIZE],
    SOC_SAND_OUT uint32                                      *buff_len
  );

/*********************************************************************
* NAME:
 *   arad_pp_trap_mact_event_parse
 * TYPE:
 *   PROC
 * FUNCTION:
 *   The MACT may report different events using the event
 *   FIFO (e.g., learn, age, transplant, and retrieve). This
 *   API Parses the event buffer into a meaningful structure.
 * INPUT:
 *   SOC_SAND_IN  int                                     unit -
 *     Identifier of the device to access.
 *   SOC_SAND_IN  uint32                                      buff -
 *     ARAD_PP_TRAP_EVENT_BUFF_MAX_SIZE]- Buffer includes MACT
 *     event
 *   SOC_SAND_IN  uint32                                      buff_len -
 *     the actual length of the given buffer (in longs)
 *   SOC_SAND_OUT ARAD_PP_TRAP_MACT_EVENT_INFO                    *mact_event -
 *     MACT Event parsed into structure
 * REMARKS:
 *   None.
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_mact_event_parse(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      buff[ARAD_PP_TRAP_EVENT_BUFF_MAX_SIZE],
    SOC_SAND_IN  uint32                                      buff_len,
    SOC_SAND_OUT ARAD_PP_TRAP_MACT_EVENT_INFO                    *mact_event
  );

void
  ARAD_PP_TRAP_ACTION_PROFILE_DEST_INFO_clear(
    SOC_SAND_OUT ARAD_PP_TRAP_ACTION_PROFILE_DEST_INFO *info
  );

void
  ARAD_PP_TRAP_ACTION_PROFILE_COUNT_INFO_clear(
    SOC_SAND_OUT ARAD_PP_TRAP_ACTION_PROFILE_COUNT_INFO *info
  );

void
  ARAD_PP_TRAP_ACTION_PROFILE_METER_INFO_clear(
    SOC_SAND_OUT ARAD_PP_TRAP_ACTION_PROFILE_METER_INFO *info
  );

void
  ARAD_PP_TRAP_ACTION_PROFILE_POLICE_INFO_clear(
    SOC_SAND_OUT ARAD_PP_TRAP_ACTION_PROFILE_POLICE_INFO *info
  );

void
  ARAD_PP_TRAP_ACTION_PROFILE_COS_INFO_clear(
    SOC_SAND_OUT ARAD_PP_TRAP_ACTION_PROFILE_COS_INFO *info
  );

void
  ARAD_PP_TRAP_ACTION_PROFILE_PROCESS_INFO_clear(
    SOC_SAND_OUT ARAD_PP_TRAP_ACTION_PROFILE_PROCESS_INFO *info
  );

void
  ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO_clear(
    SOC_SAND_OUT ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO *info
  );

void
  ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO_clear(
    SOC_SAND_OUT ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO *info
  );

void
  ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO_clear(
    SOC_SAND_OUT ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO *info
  );

void
  ARAD_PP_TRAP_MACT_EVENT_INFO_clear(
    SOC_SAND_OUT ARAD_PP_TRAP_MACT_EVENT_INFO *info
  );

void
  ARAD_PP_TRAP_PACKET_INFO_clear(
    SOC_SAND_OUT ARAD_PP_TRAP_PACKET_INFO *info
  );

#if ARAD_PP_DEBUG_IS_LVL1

const char*
  ARAD_PP_TRAP_SNOOP_ACTION_SIZE_to_string(
    SOC_SAND_IN  ARAD_PP_TRAP_SNOOP_ACTION_SIZE enum_val
  );

const char*
  ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE_to_string(
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_OVERWRITE enum_val
  );

const char*
  ARAD_PP_TRAP_MACT_EVENT_TYPE_to_string(
    SOC_SAND_IN  ARAD_PP_TRAP_MACT_EVENT_TYPE enum_val
  );

const char*
  ARAD_PP_TRAP_CODE_to_string(
    SOC_SAND_IN  ARAD_PP_TRAP_CODE enum_val
  );

const char*
  ARAD_PP_TRAP_EG_TYPE_to_string(
    SOC_SAND_IN  ARAD_PP_TRAP_EG_TYPE enum_val
  );

void
  ARAD_PP_TRAP_ACTION_PROFILE_DEST_INFO_print(
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_DEST_INFO *info
  );

void
  ARAD_PP_TRAP_ACTION_PROFILE_COUNT_INFO_print(
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_COUNT_INFO *info
  );

void
  ARAD_PP_TRAP_ACTION_PROFILE_METER_INFO_print(
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_METER_INFO *info
  );

void
  ARAD_PP_TRAP_ACTION_PROFILE_POLICE_INFO_print(
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_POLICE_INFO *info
  );

void
  ARAD_PP_TRAP_ACTION_PROFILE_COS_INFO_print(
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_COS_INFO *info
  );

void
  ARAD_PP_TRAP_ACTION_PROFILE_PROCESS_INFO_print(
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_PROCESS_INFO *info
  );

void
  ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO_print(
    SOC_SAND_IN  ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO *info
  );

void
  ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO_print(
    SOC_SAND_IN  ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO *info
  );

void
  ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO_print(
    SOC_SAND_IN  ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO *info
  );

void
  ARAD_PP_TRAP_MACT_EVENT_INFO_print(
    SOC_SAND_IN  ARAD_PP_TRAP_MACT_EVENT_INFO *info
  );

void
  ARAD_PP_TRAP_PACKET_INFO_print(
    SOC_SAND_IN  ARAD_PP_TRAP_PACKET_INFO *info
  );

#endif /* ARAD_PP_DEBUG_IS_LVL1 */

/* } */


#include <soc/dpp/SAND/Utils/sand_footer.h>

/* } __ARAD_PP_API_TRAP_MGMT_INCLUDED__*/

#endif
