/* $Id: arad_pp_trap_mgmt.h,v 1.14 Broadcom SDK $
 * $Copyright: Copyright 2016 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
*/

#ifndef __ARAD_PP_TRAP_MGMT_INCLUDED__
/* { */
#define __ARAD_PP_TRAP_MGMT_INCLUDED__

/*************
 * INCLUDES  *
 *************/
/* { */

#include <soc/dpp/pkt.h>
#include <soc/dpp/SAND/Utils/sand_header.h>
#include <soc/dpp/ARAD/arad_tbl_access.h>

#include <soc/dpp/SAND/Management/sand_general_macros.h>
#include <soc/dpp/SAND/Management/sand_error_code.h>

#include <soc/dpp/ARAD/ARAD_PP/arad_pp_api_trap_mgmt.h>
#include <soc/dpp/ARAD/ARAD_PP/arad_pp_framework.h>

#include <soc/dpp/ARAD/arad_chip_defines.h>

#include <soc/dpp/ARAD/ARAD_PP/arad_pp_api_oam.h>
/* } */
/*************
 * DEFINES   *
 *************/
/* { */

/* } */
/*************
 * MACROS    *
 *************/
/* { */

/* } */
/*************
 * TYPE DEFS *
 *************/
/* { */
typedef struct
{
  soc_reg_t      reg;
  soc_field_t      field;
} ARAD_SOC_REG_FIELD;


typedef enum
{
  /*
   * Auto generated. Do not edit following section {
   */
  ARAD_PP_TRAP_FRWRD_PROFILE_INFO_SET = ARAD_PP_PROC_DESC_BASE_TRAP_MGMT_FIRST,
  ARAD_PP_TRAP_FRWRD_PROFILE_INFO_SET_UNSAFE,
  ARAD_PP_TRAP_FRWRD_PROFILE_INFO_SET_VERIFY,
  ARAD_PP_TRAP_FRWRD_PROFILE_INFO_GET,
  ARAD_PP_TRAP_FRWRD_PROFILE_INFO_GET_PRINT,
  ARAD_PP_TRAP_FRWRD_PROFILE_INFO_GET_VERIFY,
  ARAD_PP_TRAP_FRWRD_PROFILE_INFO_GET_UNSAFE,
  ARAD_PP_TRAP_SNOOP_PROFILE_INFO_SET,
  ARAD_PP_TRAP_SNOOP_PROFILE_INFO_SET_PRINT,
  ARAD_PP_TRAP_SNOOP_PROFILE_INFO_SET_UNSAFE,
  ARAD_PP_TRAP_SNOOP_PROFILE_INFO_SET_VERIFY,
  ARAD_PP_TRAP_SNOOP_PROFILE_INFO_GET,
  ARAD_PP_TRAP_SNOOP_PROFILE_INFO_GET_PRINT,
  ARAD_PP_TRAP_SNOOP_PROFILE_INFO_GET_VERIFY,
  ARAD_PP_TRAP_SNOOP_PROFILE_INFO_GET_UNSAFE,
  ARAD_PP_TRAP_TO_EG_ACTION_MAP_SET,
  ARAD_PP_TRAP_TO_EG_ACTION_MAP_SET_PRINT,
  ARAD_PP_TRAP_TO_EG_ACTION_MAP_SET_UNSAFE,
  ARAD_PP_TRAP_TO_EG_ACTION_MAP_SET_VERIFY,
  ARAD_PP_TRAP_TO_EG_ACTION_MAP_GET,
  ARAD_PP_TRAP_TO_EG_ACTION_MAP_GET_PRINT,
  ARAD_PP_TRAP_TO_EG_ACTION_MAP_GET_VERIFY,
  ARAD_PP_TRAP_TO_EG_ACTION_MAP_GET_UNSAFE,
  ARAD_PP_TRAP_EG_PROFILE_INFO_SET,
  ARAD_PP_TRAP_EG_PROFILE_INFO_SET_PRINT,
  ARAD_PP_TRAP_EG_PROFILE_INFO_SET_UNSAFE,
  ARAD_PP_TRAP_EG_PROFILE_INFO_SET_VERIFY,
  ARAD_PP_TRAP_EG_PROFILE_INFO_GET,
  ARAD_PP_TRAP_EG_PROFILE_INFO_GET_PRINT,
  ARAD_PP_TRAP_EG_PROFILE_INFO_GET_VERIFY,
  ARAD_PP_TRAP_EG_PROFILE_INFO_GET_UNSAFE,
  ARAD_PP_TRAP_MACT_EVENT_GET,
  ARAD_PP_TRAP_MACT_EVENT_GET_PRINT,
  ARAD_PP_TRAP_MACT_EVENT_GET_UNSAFE,
  ARAD_PP_TRAP_MACT_EVENT_GET_VERIFY,
  ARAD_PP_TRAP_MACT_EVENT_PARSE,
  ARAD_PP_TRAP_MACT_EVENT_PARSE_PRINT,
  ARAD_PP_TRAP_MACT_EVENT_PARSE_UNSAFE,
  ARAD_PP_TRAP_MACT_EVENT_PARSE_VERIFY,
  ARAD_PP_TRAP_MGMT_GET_PROCS_PTR,
  ARAD_PP_TRAP_MGMT_GET_ERRS_PTR,
  /*
   * } Auto generated. Do not edit previous section.
   */

  ARAD_PP_TRAP_MGMT_TRAP_CODE_TO_INTERNAL,
  ARAD_PP_TRAP_CPU_TRAP_CODE_FROM_INTERNAL_UNSAFE,
  ARAD_PP_TRAP_PACKET_PARSE_INFO_GET_UNSAFE,
  ARAD_PP_TRAP_PACKET_PARSE_UNSAFE,
  ARAD_PP_TRAP_SB_TO_TRAP_CODE_MAP_GET,
  ARAD_PP_TRAP_SB_VTT_TO_INTERNAL_TRAP_CODE_MAP_GET,
  ARAD_PP_TRAP_PACKET_PARSE_OAM,
  /*
   * Last element. Do no touch.
   */
  ARAD_PP_TRAP_MGMT_PROCEDURE_DESC_LAST
} ARAD_PP_TRAP_MGMT_PROCEDURE_DESC;

typedef enum
{
  /*
   * Auto generated. Do not edit following section {
   */
  ARAD_PP_TRAP_MGMT_TRAP_CODE_NDX_OUT_OF_RANGE_ERR = ARAD_PP_ERR_DESC_BASE_TRAP_MGMT_FIRST,
  ARAD_PP_TRAP_MGMT_TRAP_TYPE_NDX_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_EG_ACTION_PROFILE_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_PROFILE_NDX_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_BUFF_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_BUFF_LEN_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_VSI_SHIFT_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_COUNTER_SELECT_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_COUNTER_ID_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_METER_SELECT_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_METER_ID_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_METER_COMMAND_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_ETHERNET_POLICE_ID_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_FRWRD_OFFSET_INDEX_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_DA_TYPE_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_FRWRD_OFFSET_BYTES_FIX_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_FRWRD_TYPE_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_STRENGTH_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_BITMAP_MASK_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_SIZE_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_SAMPLING_PROBABILITY_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_SNOOP_CMND_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_CUD_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_TYPE_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_CPU_TRAP_CODE_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_CPU_TRAP_QUALIFIER_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_SRC_SYS_PORT_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_LL_HEADER_PTR_OUT_OF_RANGE_ERR,
  /*
   * } Auto generated. Do not edit previous section.
   */

  ARAD_PP_TRAP_MGMT_TRAP_CODE_NOT_SUPPORTED_ERR,
  ARAD_PP_TRAP_MGMT_SNP_STRENGTH_OUT_OF_RANGE_ERR,
  ARAD_PP_TRAP_MGMT_MORE_THAN_ONE_BIT_ENABLED_ERR,

  /*
   * Last element. Do no touch.
   */
  ARAD_PP_TRAP_MGMT_ERR_LAST
} ARAD_PP_TRAP_MGMT_ERR;

/*  Prefixes */
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX  (0x0<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX  (0x1<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX  (0x2<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX  (0x3<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX  (0x4<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX  (0x5<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX  (0x6<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX  (0x7<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX  (0x8<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX  (0x9<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX  (0xa<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_PMF_PREFIX   (0xb<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_FER_PREFIX   (0xc<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_IHP_TIMNA_PREFIX (0xd<<4)
#define ARAD_PP_TRAP_CODE_INTERNAL_USER_PREFIX      ((0xf<<4) | (0x0 << 3))
#define ARAD_PP_TRAP_CODE_INTERNAL_BLOCK_PREFIX     ((0xf<<4) | (0x1 << 3))
#define ARAD_PP_TRAP_CODE_INTERNAL_OAM_PREFIX       (0xe<<4)




typedef enum
{
  /*  Link-Layer Cpu-Trap-Codes */
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_PBP_SA_DROP0                         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_PBP_SA_DROP1                         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_PBP_SA_DROP2                         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_PBP_SA_DROP3                         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_PBP_TE_TRANSPLANT                    = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_PBP_TE_UNKNOWN_TUNNEL                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_PBP_TRANSPLANT                       = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x6,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_PBP_LEARN_SNOOP                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x7,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_SA_AUTHENTICATION_FAILED             = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x8,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_PORT_NOT_PERMITTED                   = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x9,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_UNEXPECTED_VID                       = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0xa,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_SA_MULTICAST                         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0xb,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_SA_EQUALS_DA                         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0xc,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_8021X                                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0xd,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_ACCEPTABLE_FRAME_TYPE0               = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0xe,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_ACCEPTABLE_FRAME_TYPE1               = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0xf,

  ARAD_PP_TRAP_CODE_INTERNAL_LLR_ACCEPTABLE_FRAME_TYPE2               = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_ACCEPTABLE_FRAME_TYPE3               = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_MY_ARP                               = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_ARP                                  = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_IGMP_MEMBERSHIP_QUERY                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_IGMP_REPORT_LEAVE_MSG                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_IGMP_UNDEFINED                       = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x6,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_ICMPV6_MLD_MC_LISTENER_QUERY         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x7,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_PREFIX                   = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x8, /*  prefix */

  ARAD_PP_TRAP_CODE_INTERNAL_LLR_ICMPV6_MLD_REPORT_DONE_MSG           = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_ICMPV6_MLD_UNDEFINED                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_DHCP_SERVER                          = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_DHCP_CLIENT                          = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_DHCPV6_SERVER                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_DHCPV6_CLIENT                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_GENERAL_TRAP0                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x6,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_GENERAL_TRAP1                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x7,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_GENERAL_TRAP2                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x8,
  ARAD_PP_TRAP_CODE_INTERNAL_LLR_GENERAL_TRAP3                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x9,


  /* not relevant for ARAD  
    ARAD_PP_TRAP_CODE_INTERNAL_VTT_HEADER_SIZE_ERR_O_MPLS             = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x1,
  */
 /* 
  * not supported for Arad 
  * ARAD_PP_TRAP_CODE_MPLS_LABEL_VALUE_0-4 
  * ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_NO_RESOURCES 
  * ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_INVALID_LABEL_IN_RANGE 
  * ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_INVALID_LABEL_IN_SEM 
  * ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_LSP_BOS 
  * ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_PWE_NO_BOS_LABEL_14 
  * ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_PWE_NO_BOS 
  * ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_VRF_NO_BOS 
  */ 
    /*  VTT Cpu-Trap-Codes */
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_PORT_NOT_VLAN_MEMBER                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_HEADER_SIZE_ERR                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MY_B_MAC_AND_LEARN_NULL              = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MY_B_DA_UNKNOWN_I_SID                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MY_MAC_AND_IP_DISABLE                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MY_MAC_AND_MPLS_DISABLE              = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MY_MAC_AND_ARP                       = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x6,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MY_MAC_AND_UNKNOWN_L3                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x7,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IP_COMP_MC_INVALID_IP                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x8,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_TRILL_VERSION                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x9,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_TRILL_INVALID_TTL                    = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0xa,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_TRILL_CHBH                           = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0xb,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_TRILL_NO_REVERSE_FEC                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0xc,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_TRILL_CITE                           = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0xd,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_TRILL_ILLEGAL_INNER_MC               = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0xe,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_TRILL_DISABLE_BRIDGE_IF_DESIGNTAED   = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0xf,

  /* changed for ARAD */
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_INVALID_LIF_ENTRY                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_UNEXPECTED_BOS                    = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_UNEXPECTED_NO_BOS                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_TTL_0                             = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_TTL_1                             = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_CONTROL_WORD_TRAP                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_CONTROL_WORD_DROP                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x6,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_STP_STATE_BLOCK                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x7,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_STP_STATE_LEARN                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x8,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_ILLEGEL_PFC                            = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x9,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IPV4_TUNNEL_TERMINATION_AND_FRAGMENTED = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0xA,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_ETHER_IP_VERSION_ERROR                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0xB,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_PROTECTION_PATH_INVALID                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0xC,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_TRILL_NO_ADJACENT                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0xD,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MPLS_TERMINATION_ERR                   = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0xE,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_MY_B_MAC_MC_CONTINUE                   = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0xF,


  /*Jericho only*/
  ARAD_PP_TRAP_CODE_INTERNAL_MPLS_ILLEGAL_LABEL                         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_INNER_IP_COMP_MC_INVALID_IP_0              = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_INNER_ETHERNET_MY_MAC_IP_DISABLED         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x8,

    /* not in use in ARAD 
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IPV4_VERSION_ERROR                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IPV4_CHECKSUM_ERROR                     = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IPV4_HEADER_LENGTH_ERROR                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IPV4_TOTAL_LENGTH_ERROR                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IPV4_TTL0                               = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IPV4_HAS_OPTIONS                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IPV4_TTL1                               = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x6,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IPV4_SIP_EQUAL_DIP                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x7,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IPV4_DIP_ZERO                           = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x8,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IPV4_SIP_IS_MC                          = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x9,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_IPV4_TUNNEL_TERMINATION_AND_FRAGMENTED  = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0xa,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_CFM_ACCELERATED_INGRESS                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0xb,
  ARAD_PP_TRAP_CODE_INTERNAL_VTT_ILLEGEL_PFC                             = ARAD_PP_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0xc,
*/

  /*  Forwarding-Lookup Cpu-Trap-Codes */
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ETH_L2CP_PEER                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ETH_L2CP_DROP                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ETH_FL_IGMP_MEMBERSHIP_QUERY         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ETH_FL_IGMP_REPORT_LEAVE_MSG         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ETH_FL_IGMP_UNDEFINED                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ETH_FL_ICMPV6_MLD_MC_LISTENER_QUERY  = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ETH_FL_ICMPV6_MLD_REPORT_DONE        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x6,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ETH_FL_ICMPV6_MLD_UNDEFINED          = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x7,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV4_VERSION_ERROR                   = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x8,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV4_CHECKSUM_ERROR                  = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x9,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV4_HEADER_LENGTH_ERROR             = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0xa,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV4_TOTAL_LENGTH_ERROR              = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0xb,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV4_TTL0                            = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0xc,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV4_HAS_OPTIONS                     = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0xd,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV4_TTL1                            = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0xe,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV4_SIP_EQUAL_DIP                   = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0xf,

  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV4_DIP_ZERO                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV4_SIP_IS_MC                       = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_VERSION_ERROR                   = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_HOP_COUNT0                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_HOP_COUNT1                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_UNSPECIFIED_DESTINATION         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_LOOPBACK_ADDRESS                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x6,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_MULTICAST_SOURCE                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x7,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_NEXT_HEADER_NULL                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x8,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_UNSPECIFIED_SOURCE              = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x9,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_LOCAL_LINK_DESTINATION          = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0xa,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_LOCAL_SITE_DESTINATION          = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0xb,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_LOCAL_LINK_SOURCE               = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0xc,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_LOCAL_SITE_SOURCE               = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0xd,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_IPV4_COMPATIBLE_DESTINATION     = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0xe,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_IPV4_MAPPED_DESTINATION         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0xf,

  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IPV6_MULTICAST_DESTINATION           = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_MPLS_TTL0                            = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_MPLS_TTL1                            = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_TCP_SN_FLAGS_ZERO                    = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_TCP_SN_ZERO_FLAGS_SET                = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_TCP_SYN_FIN                          = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_TCP_EQUAL_PORTS                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x6,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_TCP_FRAGMENT_INCOMPLETE_HEADER       = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x7,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_TCP_FRAGMENT_OFFSET_LT8              = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x8,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_UDP_EQUAL_PORTS                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x9,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ICMP_DATA_GT_576                     = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0xa,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ICMP_FRAGMENTED                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0xb,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_SA_DROP0                             = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0xc,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_SA_DROP1                             = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0xd,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_SA_DROP2                             = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0xe,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_SA_DROP3                             = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0xf,

  ARAD_PP_TRAP_CODE_INTERNAL_FLP_SA_NOT_FOUND0                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_SA_NOT_FOUND1                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_SA_NOT_FOUND2                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_SA_NOT_FOUND3                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x3,

  ARAD_PP_TRAP_CODE_INTERNAL_FLP_MPLS_UNKNOWN_LABEL                   = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_P2P_MISCONFIGURATION                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ARP                                  = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x6,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_FCF                                  = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x7,



  ARAD_PP_TRAP_CODE_INTERNAL_FLP_IEEE_1588_PREFIX                     = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x8, /*  prefix */


  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ELK_ERROR                            = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_ELK_REJECTED                         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_OAM_LEVEL                               =  ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x2, /* used for OAM cpu trap, not configured in HW */
/*
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_P2P_MISCONFIGURATION                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x1,
  0x2 is for TRAP, out-commented
 */
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_SAME_INTERFACE                       = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_TRILL_UNKNOWN_UC                     = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_TRILL_UNKNOWN_MC                     = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_UC_LOOSE_RPF_FAIL                    = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x6,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_DEFAULT_UCV6                         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x7,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_DEFAULT_MCV6                         = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x8,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_MPLS_P2P_NO_BOS                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x9,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_MPLS_CONTROL_WORD_TRAP               = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0xa,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_MPLS_CONTROL_WORD_DROP               = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0xb,
  ARAD_PP_TRAP_CODE_INTERNAL_OAM_PASSIVE                              = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0xc, /* used for OAM cpu trap, not configured in HW */
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_MPLS_P2P_MPLSX4                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0xd,
  ARAD_PP_TRAP_CODE_INTERNAL_FLP_FABRIC_PROVIDED_SECURITY             = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0xe,


  /*  PMF Cpu-Trap-Codes */
  ARAD_PP_TRAP_CODE_INTERNAL_PMF_GENERAL                              = ARAD_PP_TRAP_CODE_INTERNAL_IHP_PMF_PREFIX + 0x0,


  /*  Fec-Resolution Cpu-Trap-Codes */
  ARAD_PP_TRAP_CODE_INTERNAL_FER_FACILITY_INVALID                     = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_FER_FEC_ENTRY_ACCESSED                   = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_FER_UC_STRICT_RPF_FAIL                   = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_FER_MC_EXPLICIT_RPF_FAIL                 = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x3,
/* not relevant for Arad
     ARAD_PP_TRAP_CODE_INTERNAL_FER_MC_USE_SIP_AS_IS_RPF_FAIL            = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_FER_MC_USE_SIP_ECMP                      = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x6,*/
  ARAD_PP_TRAP_CODE_INTERNAL_FER_MC_USE_SIP_AS_IS_RPF_FAIL            = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_FER_SIP_TRANSPLANT_DETECTION             = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_FER_ICMP_REDIRECT                        = ARAD_PP_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x6,



  /*  External device */
  ARAD_PP_TRAP_CODE_INTERNAL_USER_OAMP                                = ARAD_PP_TRAP_CODE_INTERNAL_USER_PREFIX     + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_USER_ETHERNET_OAM_ACCELERATED            = ARAD_PP_TRAP_CODE_INTERNAL_USER_PREFIX     + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_USER_MPLS_OAM_ACCELERATED                = ARAD_PP_TRAP_CODE_INTERNAL_USER_PREFIX     + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_USER_BFD_IP_OAM_TUNNEL_ACCELERATED       = ARAD_PP_TRAP_CODE_INTERNAL_USER_PREFIX     + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_USER_BFD_PWE_OAM_ACCELERATED             = ARAD_PP_TRAP_CODE_INTERNAL_USER_PREFIX     + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_USER_ETHERNET_OAM_UP_ACCELERATED         = ARAD_PP_TRAP_CODE_INTERNAL_USER_PREFIX     + 0x5,

  /* Block traps */
  ARAD_PP_TRAP_CODE_INTERNAL_BLOCK_TRAP_VTT_VT                        =  ARAD_PP_TRAP_CODE_INTERNAL_BLOCK_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_BLOCK_TRAP_VTT_TT                        =  ARAD_PP_TRAP_CODE_INTERNAL_BLOCK_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_BLOCK_TRAP_FLP                           =  ARAD_PP_TRAP_CODE_INTERNAL_BLOCK_PREFIX + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_BLOCK_TRAP_PMF_1ST_PASS                  =  ARAD_PP_TRAP_CODE_INTERNAL_BLOCK_PREFIX + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_BLOCK_TRAP_PMF_2ND_PASS                  =  ARAD_PP_TRAP_CODE_INTERNAL_BLOCK_PREFIX + 0x4,
  
  /* OAM traps */
  ARAD_PP_TRAP_CODE_INTERNAL_OAM_ETH_OAM                         =  ARAD_PP_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x0,
  ARAD_PP_TRAP_CODE_INTERNAL_OAM_Y1731_O_MPLSTP                  =  ARAD_PP_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x1,
  ARAD_PP_TRAP_CODE_INTERNAL_OAM_Y1731_O_PWE                     =  ARAD_PP_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x2,
  ARAD_PP_TRAP_CODE_INTERNAL_OAM_BFD_O_IPV4                      =  ARAD_PP_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x3,
  ARAD_PP_TRAP_CODE_INTERNAL_OAM_BFD_O_MPLS                      =  ARAD_PP_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x4,
  ARAD_PP_TRAP_CODE_INTERNAL_OAM_BFD_O_PWE                       =  ARAD_PP_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x5,
  ARAD_PP_TRAP_CODE_INTERNAL_OAM_BFDCC_O_MPLSTP                  =  ARAD_PP_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x6,
  ARAD_PP_TRAP_CODE_INTERNAL_OAM_BFDCV_O_MPLSTP                  =  ARAD_PP_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x7



} ARAD_PP_TRAP_CODE_INTERNAL;

typedef struct
{
  uint8 system_headers_mode;
  uint8 ftmh_stacking_ext_enable;
  uint8 ftmh_lb_key_ext_en;
} ARAD_PP_HEADER_DATA;


/* } */
/*************
 * GLOBALS   *
 *************/
/* { */

/* } */
/*************
 * FUNCTIONS *
 *************/
/* { */
  
uint32
  arad_pp_trap_mgmt_trap_code_to_internal(
    SOC_SAND_IN  int                                         unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                           trap_code_ndx,
    SOC_SAND_OUT ARAD_PP_TRAP_CODE_INTERNAL                  *trap_code_internal,
    SOC_SAND_OUT ARAD_SOC_REG_FIELD                          *strength_fld_fwd,
    SOC_SAND_OUT ARAD_SOC_REG_FIELD                          *strength_fld_snp
  );



uint32
  arad_pp_trap_mgmt_init_unsafe(
    SOC_SAND_IN  int                                 unit
  );

/*********************************************************************
* NAME:
 *   arad_pp_trap_frwrd_profile_info_set_unsafe
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Set forwarding action profile information.
 * INPUT:
 *   SOC_SAND_IN  int                                 unit -
 *     Identifier of the device to access.
 *   SOC_SAND_IN  ARAD_PP_TRAP_CODE                           trap_code_ndx -
 *     Trap code. AradB range: 0-255. T20E range: 0-255, only
 *     enumarators mentioned as supported in T20e.user can use
 *     values not in the enum for used defined values.
 *   SOC_SAND_IN  ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO      *profile_info -
 *     Information to set to the forwarding profile.
 * REMARKS:
 *   None.
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_frwrd_profile_info_set_unsafe(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx,
    SOC_SAND_IN  ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO          *profile_info
  );

uint32
  arad_pp_trap_frwrd_profile_info_set_verify(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx,
    SOC_SAND_IN  ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO          *profile_info
  );

uint32
  arad_pp_trap_frwrd_profile_info_get_verify(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx
  );

/*********************************************************************
*     Gets the configuration set by the
 *     "arad_pp_trap_frwrd_profile_info_set_unsafe" API.
 *     Refer to "arad_pp_trap_frwrd_profile_info_set_unsafe" API
 *     for details.
*********************************************************************/
uint32
  arad_pp_trap_frwrd_profile_info_get_unsafe(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx,
    SOC_SAND_OUT ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO          *profile_info
  );

/*********************************************************************
* NAME:
 *   arad_pp_trap_snoop_profile_info_set_unsafe
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Set snoop action profile information.
 * INPUT:
 *   SOC_SAND_IN  int                                     unit -
 *     Identifier of the device to access.
 *   SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx -
 *     Trap code. AradB range: 0-255. T20E range: 0-255, only
 *     enumarators mentioned as supported in T20E.user can use
 *     values not in the enum for used defined values.
 *   SOC_SAND_IN  ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO          *profile_info -
 *     Information to set to the snoop profile.
 * REMARKS:
 *   None.
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_snoop_profile_info_set_unsafe(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx,
    SOC_SAND_IN  ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO          *profile_info
  );

uint32
  arad_pp_trap_snoop_profile_info_set_verify(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx,
    SOC_SAND_IN  ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO          *profile_info
  );

uint32
  arad_pp_trap_snoop_profile_info_get_verify(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx
  );

/*********************************************************************
*     Gets the configuration set by the
 *     "arad_pp_trap_snoop_profile_info_set_unsafe" API.
 *     Refer to "arad_pp_trap_snoop_profile_info_set_unsafe" API
 *     for details.
*********************************************************************/
uint32
  arad_pp_trap_snoop_profile_info_get_unsafe(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  ARAD_PP_TRAP_CODE                               trap_code_ndx,
    SOC_SAND_OUT ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO          *profile_info
  );

/*********************************************************************
* NAME:
 *   arad_pp_trap_to_eg_action_map_set_unsafe
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Maps egress trap type to egress action profile.
 * INPUT:
 *   SOC_SAND_IN  int                                     unit -
 *     Identifier of the device to access.
 *   SOC_SAND_IN  uint32                                      trap_type_bitmap_ndx -
 *     Trap Type bitmap, the cause for trapping/filtering the packets
 *     (for example MTU). Use ARAD_PP_TRAP_EG_TYPE for bit offsets.
 *   SOC_SAND_IN  uint32                                      eg_action_profile -
 *     Egress action profile, to process/forward the packet
 *     according. To set the action pointed by this parameter
 *     use soc_ppd_trap_eg_profile_info_set(). Use
 *     SOC_PPD_TRAP_EG_NO_ACTION in order to bypass this trapping
 *     and then the packet will be processed/forwarded normal
 *     (as no trap was identified).
 * REMARKS:
 *   - Arad-B only. Error is returned if called for T20E.-
 *   In T20E: use soc_ppd_trap_snoop_profile_info_set() and
 *   soc_ppd_trap_frwrd_profile_info_set() to set action for Trap
 *   occurs in the T20E egress.- For part of the
 *   filters/traps (see SOC_PPD_EG_FILTER_PORT_ENABLE) user can
 *   set whether to perform the filter/trap per port. See
 *   soc_ppd_eg_filter_port_info_set()
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_to_eg_action_map_set_unsafe(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      trap_type_bitmap_ndx,
    SOC_SAND_IN  uint32                                      eg_action_profile
  );

uint32
  arad_pp_trap_to_eg_action_map_set_verify(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      trap_type_bitmap_ndx,
    SOC_SAND_IN  uint32                                      eg_action_profile
  );

uint32
  arad_pp_trap_to_eg_action_map_get_verify(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      trap_type_bitmap_ndx
  );

/*********************************************************************
*     Gets the configuration set by the
 *     "arad_pp_trap_to_eg_action_map_set_unsafe" API.
 *     Refer to "arad_pp_trap_to_eg_action_map_set_unsafe" API
 *     for details.
*********************************************************************/
uint32
  arad_pp_trap_to_eg_action_map_get_unsafe(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      trap_type_bitmap_ndx,
    SOC_SAND_OUT uint32                                      *eg_action_profile
  );

/*********************************************************************
* NAME:
 *   arad_pp_trap_eg_profile_info_set_unsafe
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Set egress action profile information.
 * INPUT:
 *   SOC_SAND_IN  int                                     unit -
 *     Identifier of the device to access.
 *   SOC_SAND_IN  uint32                                      profile_ndx -
 *     Egress action profile. Range: 0 - 8.
 *   SOC_SAND_IN  ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO             *profile_info -
 *     Information to set to the egress profile.
 * REMARKS:
 *   - Arad-B only. Error is returned if called for T20E.-
 *   In T20E: use soc_ppd_trap_snoop_profile_info_set() and
 *   soc_ppd_trap_frwrd_profile_info_set() to set action for Trap
 *   occurs in the T20E egress.- Use
 *   soc_ppd_trap_to_eg_action_map_set() to map trap (reason) to
 *   action profile
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_eg_profile_info_set_unsafe(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      profile_ndx,
    SOC_SAND_IN  ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO             *profile_info
  );

uint32
  arad_pp_trap_eg_profile_info_set_verify(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      profile_ndx,
    SOC_SAND_IN  ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO             *profile_info
  );

uint32
  arad_pp_trap_eg_profile_info_get_verify(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      profile_ndx
  );

/*********************************************************************
*     Gets the configuration set by the
 *     "arad_pp_trap_eg_profile_info_set_unsafe" API.
 *     Refer to "arad_pp_trap_eg_profile_info_set_unsafe" API for
 *     details.
*********************************************************************/
uint32
  arad_pp_trap_eg_profile_info_get_unsafe(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      profile_ndx,
    SOC_SAND_OUT ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO             *profile_info
  );

/*********************************************************************
* NAME:
 *   arad_pp_trap_mact_event_get_unsafe
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Read MACT event from the events FIFO into buffer.
 * INPUT:
 *   SOC_SAND_IN  int                                     unit -
 *     Identifier of the device to access.
 *   SOC_SAND_OUT uint32                                      buff -
 *     ARAD_PP_TRAP_EVENT_BUFF_MAX_SIZE]- Buffer to copy the Event
 *     to. Event is copied to buff starting from buff[0] lsb.
 *   SOC_SAND_OUT uint32                                      *buff_len -
 *     the actual length of the returned buffer (in longs)
 * REMARKS:
 *   None.
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_mact_event_get_unsafe(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_OUT uint32                                      buff[ARAD_PP_TRAP_EVENT_BUFF_MAX_SIZE],
    SOC_SAND_OUT uint32                                      *buff_len
  );

uint32
  arad_pp_trap_mact_event_get_verify(
    SOC_SAND_IN  int                                     unit
  );

/*********************************************************************
* NAME:
 *   arad_pp_trap_mact_event_parse_unsafe
 * TYPE:
 *   PROC
 * FUNCTION:
 *   The MACT may report different events using the event
 *   FIFO (e.g., learn, age, transplant, and retrieve). This
 *   API Parses the event buffer into a meaningful structure.
 * INPUT:
 *   SOC_SAND_IN  int                                     unit -
 *     Identifier of the device to access.
 *   SOC_SAND_IN  uint32                                      buff -
 *     ARAD_PP_TRAP_EVENT_BUFF_MAX_SIZE]- Buffer includes MACT
 *     event
 *   SOC_SAND_IN  uint32                                      buff_len -
 *     the actual length of the given buffer (in longs)
 *   SOC_SAND_OUT ARAD_PP_TRAP_MACT_EVENT_INFO                    *mact_event -
 *     MACT Event parsed into structure
 * REMARKS:
 *   None.
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_mact_event_parse_unsafe(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      buff[ARAD_PP_TRAP_EVENT_BUFF_MAX_SIZE],
    SOC_SAND_IN  uint32                                      buff_len,
    SOC_SAND_OUT ARAD_PP_TRAP_MACT_EVENT_INFO                    *mact_event
  );

uint32
  arad_pp_trap_mact_event_parse_verify(
    SOC_SAND_IN  int                                     unit,
    SOC_SAND_IN  uint32                                      buff[ARAD_PP_TRAP_EVENT_BUFF_MAX_SIZE],
    SOC_SAND_IN  uint32                                      buff_len
  );

/*********************************************************************
* NAME:
*   arad_pp_trap_packet_parse_info_get_unsafe
* TYPE:
*   PROC
* FUNCTION:
*   Fill information required to parse packet arriving to CPU.
* INPUT:
*   SOC_SAND_IN  int                                unit -
*     Identifier of the device to access.
*   SOC_SAND_IN  SOC_PPC_TRAP_MGMT_PACKET_PARSE_INFO          *packet_parse_info-
*     Information required to parse packet arriving to CPU.
* REMARKS:
*   None.
* RETURNS:
*   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_packet_parse_info_get_unsafe(
    SOC_SAND_IN  int                        unit,
    SOC_SAND_OUT ARAD_PP_TRAP_MGMT_PACKET_PARSE_INFO  *packet_parse_info
    );

uint32
  arad_pp_trap_packet_parse_unsafe(
    SOC_SAND_IN  int                               unit,
    SOC_SAND_IN  uint8                                *buff,
    SOC_SAND_IN  uint32                               buff_len,
    SOC_SAND_IN  ARAD_PP_TRAP_MGMT_PACKET_PARSE_INFO  *packet_parse_info,
    SOC_SAND_OUT ARAD_PP_TRAP_PACKET_INFO             *packet_info,
    SOC_SAND_OUT soc_pkt_t                            *dnx_pkt

  );

/*********************************************************************
* NAME:
*   arad_pp_trap_cpu_trap_code_from_internal_unsafe
* TYPE:
*   PROC
* FUNCTION:
*   Convert CPU trap code as received on packet to API enumerator.
* INPUT:
*   SOC_SAND_IN  int                                unit -
*     Identifier of the device to access.
*   SOC_SAND_IN  uint32                                internal_trap_code -
*     CPU trap code as received on packet.
*   SOC_SAND_IN  T20E_TRAP_CODE                           *trap_code-
*     Trap code enumerator.
* REMARKS:
*   None.
* RETURNS:
*   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_cpu_trap_code_from_internal_unsafe(
    SOC_SAND_IN  int                                unit,
    SOC_SAND_IN  int32                                 internal_trap_code,
    SOC_SAND_OUT ARAD_PP_TRAP_CODE                          *trap_code
  );

/*********************************************************************
* NAME:
*   arad_pp_trap_sb_to_trap_code_map_get
* TYPE:
*   PROC
* FUNCTION:
*   Convert CPU trap code Sticky bit packet to API enumerator.
* INPUT:
*   SOC_SAND_IN  int                                unit -
*     Identifier of the device to access.
*   uint32                   rng_num    -
*     which range of the sticky bit.
*   uint32                   sb_trap_indx    -
*     sticky bit trap index
*   SOC_SAND_IN  T20E_TRAP_CODE                           *trap_code-
*     Trap code enumerator.
* REMARKS:
*   None.
* RETURNS:
*   OK or ERROR indication.
*********************************************************************/
uint32
  arad_pp_trap_sb_to_trap_code_map_get(
    SOC_SAND_IN  int                   unit,
    SOC_SAND_IN   uint32                   rng_num,
    SOC_SAND_IN   uint32                   sb_trap_indx,
    SOC_SAND_OUT  ARAD_PP_TRAP_CODE           *trap_code
  );

/*********************************************************************
* NAME:
 *   arad_pp_trap_mgmt_get_procs_ptr
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Get the pointer to the list of procedures of the
 *   arad_pp_api_trap_mgmt module.
 * INPUT:
 * REMARKS:
 *
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
CONST SOC_PROCEDURE_DESC_ELEMENT*
  arad_pp_trap_mgmt_get_procs_ptr(void);

/*********************************************************************
* NAME:
 *   arad_pp_trap_mgmt_get_errs_ptr
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Get the pointer to the list of errors of the
 *   arad_pp_api_trap_mgmt module.
 * INPUT:
 * REMARKS:
 *
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
CONST SOC_ERROR_DESC_ELEMENT*
  arad_pp_trap_mgmt_get_errs_ptr(void);

uint32
  ARAD_PP_TRAP_ACTION_PROFILE_DEST_INFO_verify(
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_DEST_INFO *info
  );

uint32
  ARAD_PP_TRAP_ACTION_PROFILE_COUNT_INFO_verify(
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_COUNT_INFO *info
  );

uint32
  ARAD_PP_TRAP_ACTION_PROFILE_METER_INFO_verify(
    SOC_SAND_IN  int                                    unit,
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_METER_INFO *info
  );

uint32
  ARAD_PP_TRAP_ACTION_PROFILE_POLICE_INFO_verify(
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_POLICE_INFO *info
  );

uint32
  ARAD_PP_TRAP_ACTION_PROFILE_COS_INFO_verify(
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_COS_INFO *info
  );

uint32
  ARAD_PP_TRAP_ACTION_PROFILE_PROCESS_INFO_verify(
    SOC_SAND_IN  ARAD_PP_TRAP_ACTION_PROFILE_PROCESS_INFO *info
  );

uint32
  ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO_verify(
    SOC_SAND_IN  int                                    unit,
    SOC_SAND_IN  ARAD_PP_TRAP_FRWRD_ACTION_PROFILE_INFO *info
  );

uint32
  ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO_verify(
    SOC_SAND_IN  ARAD_PP_TRAP_SNOOP_ACTION_PROFILE_INFO *info
  );

uint32
  ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO_verify(
    SOC_SAND_IN  ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO *info
  );

uint32
  ARAD_PP_TRAP_MACT_EVENT_INFO_verify(
    SOC_SAND_IN  int                          unit,
    SOC_SAND_IN  ARAD_PP_TRAP_MACT_EVENT_INFO *info
  );

uint32
  ARAD_PP_TRAP_PACKET_INFO_verify(
    SOC_SAND_IN  ARAD_PP_TRAP_PACKET_INFO *info
  );

void
  arad_pp_trap_eg_profile_info_cud_to_hdr_data(
    SOC_SAND_IN  int                             unit,
    SOC_SAND_IN  uint32                             cud,
    SOC_SAND_OUT ARAD_PP_TRAP_EG_ACTION_HDR_DATA    *profile_hdr_data
  );
void
  arad_pp_trap_eg_profile_info_hdr_data_to_cud(
    SOC_SAND_IN  int                             unit,
    SOC_SAND_IN  ARAD_PP_TRAP_EG_ACTION_HDR_DATA    profile_hdr_data,
    SOC_SAND_OUT uint32                             *cud
  );

int
   arad_pp_trap_is_jericho_ingress_trap( 
       SOC_SAND_IN  int32 trap_code_internal,
       uint8 *is_ingress);

int
   arad_pp_trap_base_q_pair_to_port(
  /*in*/SOC_SAND_IN int unit,
   SOC_SAND_IN  int core,
   SOC_SAND_IN  uint32 base_q_pair, 
  /*out*/ SOC_SAND_OUT  uint32 *tm_port);

int
arad_pp_trap_get_first_cpu_port(
  /*in*/SOC_SAND_IN int unit,
        SOC_SAND_IN int core,
  /*out*/ SOC_SAND_OUT  uint32 *cpu_port_tm);

int
arad_pp_trap_cpu_ports_on_all_cores(
   /*in*/ SOC_SAND_IN int unit, 
   /*out*/ SOC_SAND_OUT uint8 *defined_on_all_cores);
 
int 
arad_pp_trap_action_profile_set_tm_port(
   /*in*/ SOC_SAND_IN int unit,
    SOC_SAND_IN int core,
    SOC_SAND_IN SOC_PPC_TM_PORT tm_port,
    SOC_SAND_IN ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO *profile_info, 
   /*out*/ SOC_SAND_OUT ARAD_PP_EGQ_ACTION_PROFILE_TABLE_TBL_DATA *tbl_data);

int 
arad_pp_trap_action_profile_get_tm_port_and_hdr_data(
   /*in*/ SOC_SAND_IN int unit,
   SOC_SAND_IN int core,
   SOC_SAND_IN ARAD_PP_EGQ_ACTION_PROFILE_TABLE_TBL_DATA *tbl_data,
   /*out*/  SOC_SAND_OUT SOC_PPC_TM_PORT *tm_port, 
   SOC_SAND_OUT ARAD_PP_TRAP_EG_ACTION_HDR_DATA    *profile_hdr_data,
   SOC_SAND_OUT ARAD_PP_TRAP_EG_ACTION_PROFILE_INFO *profile_info);
/* } */

#include <soc/dpp/SAND/Utils/sand_footer.h>

/* } __ARAD_PP_TRAP_MGMT_INCLUDED__*/
#endif


