#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/diag/dnx/pp/kleap

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/soc/dnx/pp/kleap

subdirs = auto_generated

include ${SDK}/make/Make.subdirs

lib = libdiag_dnx_pp_kleap

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

