# $Id: Makefile Exp $
#
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Hurricane4 SOC driver Library
#

LOCALDIR = src/soc/esw/tdm/hurricane4/

include ${SDK}/make/Make.config

lib = libsoc_tdm_hr4

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

