# $Id
#
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for Firebolt6 SOC driver Library
#

LOCALDIR = src/soc/esw/firebolt6/flexport

include ${SDK}/make/Make.config

lib = libsoc_firebolt6_flexport

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

