# $Id: $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Tomahawk2 flexport common library

LOCALDIR = src/soc/esw/tomahawk3/flexport

include ${SDK}/make/Make.config

lib = libsoc_tomahawk3_flexport

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend


