FP_BASE=../../../../../../../..

KERNLIB=kern_ubde.a

# Linux Kernel module ubde.o Makefile
#
#

# Do not change this line.
#
include $(FP_BASE)/src/l7tools/build/make.cfg

# Specify additional header directories needed by your component
COMPONENT_INCLDIR += \
	-I$(KERNEL_SRC)/include \
	$(BROADCOM_INCL) \
	-I$(BROADCOM_SRC)/../systems/bde/linux/include \
	-I$(BROADCOM_SRC)/../systems/bde/linux/user/kernel \
        -I$(BROADCOM_SRC)/../systems/linux/kernel/modules/include \
	-I../include

# Specify compile flags.
#
CFLAGSLOCAL= $(GFLAG) -D__KERNEL__ -O2 -Werror
ifeq ($(L7_CPU),raptor)
CFLAGSLOCAL+=-Wall -Wstrict-prototypes -Wno-trigraphs -O2 -fno-strict-aliasing -fno-common -fomit-frame-pointer -G 0 -mno-abicalls -fno-pic -pipe -mtune=r4600 -mips2 -Wa,--trap -mlong-calls
endif

# Specify modules that need to be compiled.
#

LIBOBJS = linux-user-bde.o

KERNEL_LIBS = ../../../../linux/kernel/modules/shared/kern_mod_shared.a \
	      ../../../../../src/sal/core/linux/kern_sal.a

bldlib: ubde.kmod
	$(STRIP) -g ubde.kmod -o $(FP_BASE)/bsp/cpu/$(L7_CPU)/$(L7_TARGETOS)/target/ubde.o 
	rm -f *.o

ubde.kmod: $(KERNLIB)($(LIBOBJS)) $(KERNEL_LIBS)
	rm -f ubde.kmod
	$(MAKE) -f Makefile.24 $(LIBOBJS)
	$(linkcmd) -o ubde.kmod -Map ubde.map -r $(LIBOBJS) $(KERNEL_LIBS)

clean::
	-$(RM) *.o
	-$(RM) *.map
	-$(RM) *.kmod
	-$(RM) $(KERNLIB)

(%.o) : %.c
	$(CC) -Wp,-MD,$(*F).d $(CFLAGS) $(CFLAGSLOCAL) -c $<
	$(AR) r $@ $*.o

# Do not change this line.
#
include $(FP_BASE)/src/l7tools/build/make.footer
