/*------------------------------------------------------------------------------
 * $Id: tscjmod_spd_ctrl_defines.h $
 *
 * $Copyright: (c) 2021 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *  Broadcom Corporation
 *  Proprietary and Confidential information
 *  All rights reserved
 *  This source file is the property of Broadcom Corporation, and
 *  may not be copied or distributed in any isomorphic form without the
 *  prior written consent of Broadcom Corporation.
 *------------------------------------------------------------------------------
 *  Description: Defines for the Speed Table, AM Table, and UM Table access APIs
 *----------------------------------------------------------------------------*/

#ifndef TSCJMOD_SPD_CTRL_DEFINES_H
#define TSCJMOD_SPD_CTRL_DEFINES_H

/*-------- Defines for table dimensions --------*/
#define TSCJMOD_SPD_CTRL_SPD_ID_TBL_SIZE 64
#define TSCJMOD_SPD_CTRL_SPD_ID_TBL_ENTRY_WIDTH 161

/*-------- Defines for fields of Speed ID Table --------*/
#define TSCJMOD_SPD_ID_TBL_AM_TABLE_INDEX_OFFSET 0
#define TSCJMOD_SPD_ID_TBL_AM_TABLE_INDEX_WIDTH 6
#define TSCJMOD_SPD_ID_TBL_AM_TABLE_INDEX_MASK ((1 << TSCJMOD_SPD_ID_TBL_AM_TABLE_INDEX_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_FEC_ARCH_OFFSET 6
#define TSCJMOD_SPD_ID_TBL_FEC_ARCH_WIDTH 3
#define TSCJMOD_SPD_ID_TBL_FEC_ARCH_MASK ((1 << TSCJMOD_SPD_ID_TBL_FEC_ARCH_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_SYMBOL_INTERLEAVE_OFFSET 9
#define TSCJMOD_SPD_ID_TBL_SYMBOL_INTERLEAVE_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_SYMBOL_INTERLEAVE_MASK ((1 << TSCJMOD_SPD_ID_TBL_SYMBOL_INTERLEAVE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_TC_XOR_CONTROL_OFFSET 10
#define TSCJMOD_SPD_ID_TBL_TC_XOR_CONTROL_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_TC_XOR_CONTROL_MASK ((1 << TSCJMOD_SPD_ID_TBL_TC_XOR_CONTROL_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_OFFSET 11
#define TSCJMOD_SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_WIDTH 2
#define TSCJMOD_SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_MASK ((1 << TSCJMOD_SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_OFFSET 13
#define TSCJMOD_SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_WIDTH 4
#define TSCJMOD_SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_MASK ((1 << TSCJMOD_SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_BASE_R_FEC_SYNC_HEADER_MODE_OFFSET 17
#define TSCJMOD_SPD_ID_TBL_BASE_R_FEC_SYNC_HEADER_MODE_WIDTH 2
#define TSCJMOD_SPD_ID_TBL_BASE_R_FEC_SYNC_HEADER_MODE_MASK ((1 << TSCJMOD_SPD_ID_TBL_BASE_R_FEC_SYNC_HEADER_MODE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_OFFSET 19
#define TSCJMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_WIDTH 2
#define TSCJMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_MASK ((1 << TSCJMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_OFFSET 21
#define TSCJMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_WIDTH 14
#define TSCJMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_MASK ((1 << TSCJMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_OFFSET 35
#define TSCJMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_WIDTH 8
#define TSCJMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_MASK ((1 << TSCJMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_OFFSET 43
#define TSCJMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_WIDTH 8
#define TSCJMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_MASK ((1 << TSCJMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_BIT_MUX_MODE_OFFSET 51
#define TSCJMOD_SPD_ID_TBL_BIT_MUX_MODE_WIDTH 2
#define TSCJMOD_SPD_ID_TBL_BIT_MUX_MODE_MASK ((1 << TSCJMOD_SPD_ID_TBL_BIT_MUX_MODE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_NUM_LANES_OFFSET 53
#define TSCJMOD_SPD_ID_TBL_NUM_LANES_WIDTH 3
#define TSCJMOD_SPD_ID_TBL_NUM_LANES_MASK ((1 << TSCJMOD_SPD_ID_TBL_NUM_LANES_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_OFFSET 56
#define TSCJMOD_SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_WIDTH 8
#define TSCJMOD_SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_MASK ((1 << TSCJMOD_SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_OFFSET 64
#define TSCJMOD_SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_WIDTH 8
#define TSCJMOD_SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_MASK ((1 << TSCJMOD_SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_OFFSET 72
#define TSCJMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_MASK ((1 << TSCJMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_OFFSET 73
#define TSCJMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_MASK ((1 << TSCJMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_BER_WINDOW_MODE_OFFSET 74
#define TSCJMOD_SPD_ID_TBL_BER_WINDOW_MODE_WIDTH 2
#define TSCJMOD_SPD_ID_TBL_BER_WINDOW_MODE_MASK ((1 << TSCJMOD_SPD_ID_TBL_BER_WINDOW_MODE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_BER_TRIGGER_COUNT_OFFSET 76
#define TSCJMOD_SPD_ID_TBL_BER_TRIGGER_COUNT_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_BER_TRIGGER_COUNT_MASK ((1 << TSCJMOD_SPD_ID_TBL_BER_TRIGGER_COUNT_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_CREDIT_QUOTIENT_OFFSET 77
#define TSCJMOD_SPD_ID_TBL_CREDIT_QUOTIENT_WIDTH 7
#define TSCJMOD_SPD_ID_TBL_CREDIT_QUOTIENT_MASK ((1 << TSCJMOD_SPD_ID_TBL_CREDIT_QUOTIENT_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_CREDIT_REMAINDER_OFFSET 84
#define TSCJMOD_SPD_ID_TBL_CREDIT_REMAINDER_WIDTH 11
#define TSCJMOD_SPD_ID_TBL_CREDIT_REMAINDER_MASK ((1 << TSCJMOD_SPD_ID_TBL_CREDIT_REMAINDER_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_CREDIT_DIVISOR_OFFSET 95
#define TSCJMOD_SPD_ID_TBL_CREDIT_DIVISOR_WIDTH 11
#define TSCJMOD_SPD_ID_TBL_CREDIT_DIVISOR_MASK ((1 << TSCJMOD_SPD_ID_TBL_CREDIT_DIVISOR_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_USE_CL49_BLOCK_SYNC_OFFSET 106
#define TSCJMOD_SPD_ID_TBL_USE_CL49_BLOCK_SYNC_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_USE_CL49_BLOCK_SYNC_MASK ((1 << TSCJMOD_SPD_ID_TBL_USE_CL49_BLOCK_SYNC_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_SCR_MODE_OFFSET 107
#define TSCJMOD_SPD_ID_TBL_SCR_MODE_WIDTH 2
#define TSCJMOD_SPD_ID_TBL_SCR_MODE_MASK ((1 << TSCJMOD_SPD_ID_TBL_SCR_MODE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_CODEC_MODE_OFFSET 109
#define TSCJMOD_SPD_ID_TBL_CODEC_MODE_WIDTH 2
#define TSCJMOD_SPD_ID_TBL_CODEC_MODE_MASK ((1 << TSCJMOD_SPD_ID_TBL_CODEC_MODE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_SPARE_1_OFFSET 111
#define TSCJMOD_SPD_ID_TBL_SPARE_1_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_SPARE_1_MASK ((1 << TSCJMOD_SPD_ID_TBL_SPARE_1_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_AN_TIMER_SELECT_OFFSET 112
#define TSCJMOD_SPD_ID_TBL_AN_TIMER_SELECT_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_AN_TIMER_SELECT_MASK ((1 << TSCJMOD_SPD_ID_TBL_AN_TIMER_SELECT_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_PMD_TRAINING_MODE_OFFSET 113
#define TSCJMOD_SPD_ID_TBL_PMD_TRAINING_MODE_WIDTH 3
#define TSCJMOD_SPD_ID_TBL_PMD_TRAINING_MODE_MASK ((1 << TSCJMOD_SPD_ID_TBL_PMD_TRAINING_MODE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_PMD_PRESET_OFFSET 116
#define TSCJMOD_SPD_ID_TBL_PMD_PRESET_WIDTH 4
#define TSCJMOD_SPD_ID_TBL_PMD_PRESET_MASK ((1 << TSCJMOD_SPD_ID_TBL_PMD_PRESET_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_T_PMA_WATERMARK_OFFSET 120
#define TSCJMOD_SPD_ID_TBL_T_PMA_WATERMARK_WIDTH 4
#define TSCJMOD_SPD_ID_TBL_T_PMA_WATERMARK_MASK ((1 << TSCJMOD_SPD_ID_TBL_T_PMA_WATERMARK_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_L_TPMA_WATERMARK_OFFSET 124
#define TSCJMOD_SPD_ID_TBL_L_TPMA_WATERMARK_WIDTH 3
#define TSCJMOD_SPD_ID_TBL_L_TPMA_WATERMARK_MASK ((1 << TSCJMOD_SPD_ID_TBL_L_TPMA_WATERMARK_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_OFFSET 127
#define TSCJMOD_SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_WIDTH 8
#define TSCJMOD_SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_MASK ((1 << TSCJMOD_SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_OFFSET 135
#define TSCJMOD_SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_WIDTH 14
#define TSCJMOD_SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_MASK ((1 << TSCJMOD_SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_AM_LOCK_FSM_MODE_OFFSET 149
#define TSCJMOD_SPD_ID_TBL_AM_LOCK_FSM_MODE_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_AM_LOCK_FSM_MODE_MASK ((1 << TSCJMOD_SPD_ID_TBL_AM_LOCK_FSM_MODE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_T_PMA_START_MODE_OFFSET 150
#define TSCJMOD_SPD_ID_TBL_T_PMA_START_MODE_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_T_PMA_START_MODE_MASK ((1 << TSCJMOD_SPD_ID_TBL_T_PMA_START_MODE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_HI_SER_ENABLE_OFFSET 151
#define TSCJMOD_SPD_ID_TBL_HI_SER_ENABLE_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_HI_SER_ENABLE_MASK ((1 <<  TSCJMOD_SPD_ID_TBL_HI_SER_ENABLE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_T_PMA_INPUT_WIDTH_MODE_OFFSET 152
#define TSCJMOD_SPD_ID_TBL_T_PMA_INPUT_WIDTH_MODE_WIDTH 2
#define TSCJMOD_SPD_ID_TBL_T_PMA_INPUT_WIDTH_MODE_MASK ((1 <<  TSCJMOD_SPD_ID_TBL_T_PMA_INPUT_WIDTH_MODE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_T_PMA_OUTPUT_WIDTH_MODE_OFFSET 154
#define TSCJMOD_SPD_ID_TBL_T_PMA_OUTPUT_WIDTH_MODE_WIDTH 2
#define TSCJMOD_SPD_ID_TBL_T_PMA_OUTPUT_WIDTH_MODE_MASK ((1 <<  TSCJMOD_SPD_ID_TBL_T_PMA_OUTPUT_WIDTH_MODE_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_BIT_MUX_MODE_MODIFIER_OFFSET 156
#define TSCJMOD_SPD_ID_TBL_BIT_MUX_MODE_MODIFIER_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_BIT_MUX_MODE_MODIFIER_MASK ((1 <<  TSCJMOD_SPD_ID_TBL_BIT_MUX_MODE_MODIFIER_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_NUM_LANES_MODIFIER_OFFSET 157
#define TSCJMOD_SPD_ID_TBL_NUM_LANES_MODIFIER_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_NUM_LANES_MODIFIER_MASK ((1 <<  TSCJMOD_SPD_ID_TBL_NUM_LANES_MODIFIER_WIDTH) - 1)
#define TSCJMOD_SPD_ID_TBL_MAPPING_SEL_OFFSET 158
#define TSCJMOD_SPD_ID_TBL_MAPPING_SEL_WIDTH 1
#define TSCJMOD_SPD_ID_TBL_MAPPING_SEL_MASK ((1 <<  TSCJMOD_SPD_ID_TBL_MAPPING_SEL_WIDTH) - 1)


#endif  /* TSCJMOD_SPD_CTRL_DEFINES_H_ */

