# $Id: Makefile,v 1.0 2016/04/18 yiwenz Exp $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for flexflow Library
#

LOCALDIR = src/bcm/esw/flexflow

include ${SDK}/make/Make.config

lib = libflexflow

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
