/*********************************************************************
*
* (C) Copyright Broadcom Corporation 2006-2007
*
**********************************************************************
*
* @filename   src/nls/web/base/strlib_base_web.c
*
* @purpose    Strings Library
*
* @component  Common Strings Library
*
* @comments   none
*
* @create     01/10/2007
*
* @author     Rama Sasthri, Kristipati
*
* @end
*
*********************************************************************/

#include "strlib_base_web.h"
L7_char8 *pStrInfo_base_Ip = "IP";
L7_char8 *pStrInfo_base_Canonical_1 = "Canonical";
L7_char8 *pStrInfo_base_DaysHMS = "%d Days %2dh:%2dm:%2ds";
L7_char8 *pStrInfo_base_DaysHoursMinutes = "%d Days %d Hours %d Minutes";
L7_char8 *pStrInfo_base_M = "%dm";
L7_char8 *pStrInfo_base_MM = "%dm - %dm";
L7_char8 *pStrErr_base_FromLessThanTo = "%s IP Address should be less than %s IP Address.";
L7_char8 *pStrErr_base_FieldAlreadySet = "%s already set.";
L7_char8 *pStrErr_base_FieldMandatory = "%s is a mandatory field.";
L7_char8 *pStrErr_base_FailedToSetOption = "%s. Option Code %d is already configured with Option Type %s.";
L7_char8 *pStrInfo_base_P = ",\"p%02d\"";
L7_char8 *pStrInfo_base_HtmlFileBaseLvl7Login = "/base/brcm_login.html";
L7_char8 *pStrInfo_base_HtmlFileBaseWebMain = "/base/web_main.html";
L7_char8 *pStrInfo_base_10GbpsFullDuplex = "10 Gbps Full Duplex";
L7_char8 *pStrInfo_base_10MbpsFullDuplex = "10 Mbps Full Duplex";
L7_char8 *pStrInfo_base_10MbpsHalfDuplex = "10 Mbps Half Duplex";
L7_char8 *pStrInfo_base_100MbpsFxFullDuplex = "100 Mbps FX Full Duplex";
L7_char8 *pStrInfo_base_100MbpsFullDuplex = "100 Mbps Full Duplex";
L7_char8 *pStrInfo_base_100MbpsHalfDuplex = "100 Mbps Half Duplex";
L7_char8 *pStrInfo_base_1000MbpsFullDuplex = "1000 Mbps Full Duplex";
L7_char8 *pStrInfo_base_Dot1xPortSecurityUsrs = "802.1x Port Security Users";
L7_char8 *pStrInfo_base_Tbl = "</TABLE>";
L7_char8 *pStrInfo_base_Error_1 = "<< Error >>";
L7_char8 *pStrInfo_base_TblAlignLeft = "<TABLE ALIGN=LEFT>";
L7_char8 *pStrInfo_base_AclAssignQueueFeat = "ACL_ASSIGN_QUEUE_FEATURE";
L7_char8 *pStrInfo_base_AclFeatSupported = "ACL_FEATURE_SUPPORTED";
L7_char8 *pStrInfo_base_AclIntfDiffservCoexistFeat = "ACL_INTF_DIFFSERV_COEXIST_FEATURE";
L7_char8 *pStrInfo_base_AclIntfDirectionInboundFeat = "ACL_INTF_DIRECTION_INBOUND_FEATURE";
L7_char8 *pStrInfo_base_AclIntfDirectionOutboundFeat = "ACL_INTF_DIRECTION_OUTBOUND_FEATURE";
L7_char8 *pStrInfo_base_AclIntfLagSupportFeat = "ACL_INTF_LAG_SUPPORT_FEATURE";
L7_char8 *pStrInfo_base_AclIntfMultipleAclFeat = "ACL_INTF_MULTIPLE_ACL_FEATURE";
L7_char8 *pStrInfo_base_AclIntfVlanSupportFeat = "ACL_INTF_VLAN_SUPPORT_FEATURE";
L7_char8 *pStrInfo_base_AclLogDenyFeat = "ACL_LOG_DENY_FEATURE";
L7_char8 *pStrInfo_base_AclLogPermitFeat = "ACL_LOG_PERMIT_FEATURE";
L7_char8 *pStrInfo_base_AclMirrorFeat = "ACL_MIRROR_FEATURE";
L7_char8 *pStrInfo_base_AclRedirectFeat = "ACL_REDIRECT_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchCos2Feat = "ACL_RULE_MATCH_COS2_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchCosFeat = "ACL_RULE_MATCH_COS_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchDstipFeat = "ACL_RULE_MATCH_DSTIP_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchDstl4portFeat = "ACL_RULE_MATCH_DSTL4PORT_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchDstl4portRangeFeat = "ACL_RULE_MATCH_DSTL4PORT_RANGE_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchDstmacFeat = "ACL_RULE_MATCH_DSTMAC_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchDstmacMaskFeat = "ACL_RULE_MATCH_DSTMAC_MASK_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchEtypeFeat = "ACL_RULE_MATCH_ETYPE_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchEveryFeat = "ACL_RULE_MATCH_EVERY_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchIpdscpFeat = "ACL_RULE_MATCH_IPDSCP_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchIpprecedenceFeat = "ACL_RULE_MATCH_IPPRECEDENCE_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchIptosFeat = "ACL_RULE_MATCH_IPTOS_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchProtoFeat = "ACL_RULE_MATCH_PROTOCOL_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchSrcipFeat = "ACL_RULE_MATCH_SRCIP_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchSrcl4portFeat = "ACL_RULE_MATCH_SRCL4PORT_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchSrcl4portRangeFeat = "ACL_RULE_MATCH_SRCL4PORT_RANGE_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchSrcmacFeat = "ACL_RULE_MATCH_SRCMAC_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchSrcmacMaskFeat = "ACL_RULE_MATCH_SRCMAC_MASK_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchSupportsMaskingFeat = "ACL_RULE_MATCH_SUPPORTS_MASKING_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchVid2Feat = "ACL_RULE_MATCH_VLANID2_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchVid2RangeFeat = "ACL_RULE_MATCH_VLANID2_RANGE_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchVidFeat = "ACL_RULE_MATCH_VLANID_FEATURE";
L7_char8 *pStrInfo_base_AclRuleMatchVidRangeFeat = "ACL_RULE_MATCH_VLANID_RANGE_FEATURE";
L7_char8 *pStrInfo_base_AclTypeMacFeat = "ACL_TYPE_MAC_FEATURE";
L7_char8 *pStrInfo_base_AclVlanDirectionInboundFeat = "ACL_VLAN_DIRECTION_INBOUND_FEATURE";
L7_char8 *pStrInfo_base_AclVlanDirectionOutboundFeat = "ACL_VLAN_DIRECTION_OUTBOUND_FEATURE";
L7_char8 *pStrInfo_base_ArpCache = "ARP Cache";
L7_char8 *pStrInfo_base_AddSrcPort = "Add Source Port";
L7_char8 *pStrInfo_base_AddrEntriesInUse = "Address Entries in Use";
L7_char8 *pStrInfo_base_AddrType = "Address Type";
L7_char8 *pStrInfo_base_AdminStatus = "Admin Status";
L7_char8 *pStrInfo_base_AgingIntvlSecs = "Aging Interval (secs)";
L7_char8 *pStrInfo_base_AllAddrConflicts = "All Address Conflicts";
L7_char8 *pStrInfo_base_AllComps = "All Components";
L7_char8 *pStrInfo_base_AllDynBindings = "All Dynamic Bindings";
L7_char8 *pStrInfo_base_ConfirmToResetSysCfg = "Are you sure you want to reset the system configuration?";
L7_char8 *pStrInfo_base_ConfirmToResetSysAllConnsWillBeLostToRegainConnYouWillHaveToLogInAgainLater = "Are you sure you want to reset the system? All connections will be lost!  To regain connection, you will have to log in again later.";
L7_char8 *pStrInfo_base_Ascii = "Ascii";
L7_char8 *pStrInfo_base_AuthListCfg = "Authentication List Configuration";
L7_char8 *pStrInfo_base_AuthListSummary = "Authentication List Summary";
L7_char8 *pStrInfo_base_AuthLoginList = "Authentication Login List.";
L7_char8 *pStrInfo_base_AuthProto = "Authentication Protocol";
L7_char8 *pStrInfo_base_BpdusRcvd = "BPDUs Received";
L7_char8 *pStrInfo_base_BaseMacAddr = "Base MAC Address";
L7_char8 *pStrInfo_base_BcastStormLvl = "Bcast Storm Level";
L7_char8 *pStrInfo_base_BcastStormMode = "Bcast Storm Mode";
L7_char8 *pStrInfo_base_Behavior = "Behavior";
L7_char8 *pStrInfo_base_BindingIpAddr = "Binding IP address";
L7_char8 *pStrInfo_base_BootFile = "Boot File";
L7_char8 *pStrInfo_base_BootpAutoMode = "Bootp Automatic Mode";
L7_char8 *pStrInfo_base_BcastPollIntvl = "Broadcast Poll Interval";
L7_char8 *pStrInfo_base_BcastStormRecoveryLvl = "Broadcast Storm Recovery Level";
L7_char8 *pStrInfo_base_BcastStormRecoveryMode = "Broadcast Storm Recovery Mode";
L7_char8 *pStrInfo_base_BufedLogCfg = "Buffered Log Configuration";
L7_char8 *pStrInfo_base_BufedLogs = "Buffered Logs";
L7_char8 *pStrInfo_base_CableTest = "CABLE_TEST";
L7_char8 *pStrInfo_base_CaptivePortal = "CAPTIVE_PORTAL";
L7_char8 *pStrInfo_base_CliWeb = "CLI_WEB";
L7_char8 *pStrInfo_base_Cos = "COS";
L7_char8 *pStrInfo_base_CosFeatSupported = "COS_FEATURE_SUPPORTED";
L7_char8 *pStrInfo_base_CosMapIpdscpFeat = "COS_MAP_IPDSCP_FEATURE";
L7_char8 *pStrInfo_base_CosMapIpdscpPerIntfFeat = "COS_MAP_IPDSCP_PER_INTF_FEATURE";
L7_char8 *pStrInfo_base_CosMapIpprecFeat = "COS_MAP_IPPREC_FEATURE";
L7_char8 *pStrInfo_base_CosMapIpprecPerIntfFeat = "COS_MAP_IPPREC_PER_INTF_FEATURE";
L7_char8 *pStrInfo_base_CosMapTrustModeFeat = "COS_MAP_TRUST_MODE_FEATURE";
L7_char8 *pStrInfo_base_CosMapTrustModePerIntfFeat = "COS_MAP_TRUST_MODE_PER_INTF_FEATURE";
L7_char8 *pStrInfo_base_CosQueueCfgPerIntfFeat = "COS_QUEUE_CFG_PER_INTF_FEATURE";
L7_char8 *pStrInfo_base_CosQueueDropCfgPerIntfFeat = "COS_QUEUE_DROP_CFG_PER_INTF_FEATURE";
L7_char8 *pStrInfo_base_CosQueueIntfShapingFeat = "COS_QUEUE_INTF_SHAPING_FEATURE";
L7_char8 *pStrInfo_base_CosQueueMaxBwFeat = "COS_QUEUE_MAX_BW_FEATURE";
L7_char8 *pStrInfo_base_CosQueueMgmtIntfOnlyFeat = "COS_QUEUE_MGMT_INTF_ONLY_FEATURE";
L7_char8 *pStrInfo_base_CosQueueMinBwFeat = "COS_QUEUE_MIN_BW_FEATURE";
L7_char8 *pStrInfo_base_CosQueueSchedStrictOnlyFeat = "COS_QUEUE_SCHED_STRICT_ONLY_FEATURE";
L7_char8 *pStrInfo_base_CosQueueTdropThreshFeat = "COS_QUEUE_TDROP_THRESH_FEATURE";
L7_char8 *pStrInfo_base_CosQueueBucketFeat = "COS_QUEUE_BUCKET_FEATURE";
L7_char8 *pStrInfo_base_CosQueueWredDecayExpSysOnlyFeat = "COS_QUEUE_WRED_DECAY_EXP_SYSTEM_ONLY_FEATURE";
L7_char8 *pStrInfo_base_CosQueueWredMaxThreshFeat = "COS_QUEUE_WRED_MAX_THRESH_FEATURE";
L7_char8 *pStrInfo_base_CosQueueWredSupportFeat = "COS_QUEUE_WRED_SUPPORT_FEATURE";
L7_char8 *pStrInfo_base_CableTest_1 = "Cable Test";
L7_char8 *pStrInfo_base_CableTestFailed = "Cable Test Failed";
L7_char8 *pStrInfo_base_CableTestResults = "Cable Test Results";
L7_char8 *pStrInfo_base_Dot3ahLanOamTestResults = "Port Loopback Test Results";
L7_char8 *pStrInfo_base_CardCfg = "Card Configuration";
L7_char8 *pStrInfo_base_ChangingProtoModeWillResetIpCfg = "Changing protocol mode will reset IP configuration.";
L7_char8 *pStrInfo_base_ClrAllCounters = "Clear All Counters";
L7_char8 *pStrInfo_base_ClrBindingIpAddr = "Clear Binding IP address";
L7_char8 *pStrInfo_base_ClrCounters = "Clear Counters";
L7_char8 *pStrInfo_base_GetRpcMethods = "Get RPC Methods";
L7_char8 *pStrInfo_base_ClrLog = "Clear Log";
L7_char8 *pStrInfo_base_ClientId = "Client ID";
L7_char8 *pStrInfo_base_ClientIdRequiresAnIdInFormAb0123456789Ab = "Client ID requires an ID in form AB:01:23:45:67:89:AB";
L7_char8 *pStrInfo_base_ClientIpAddr = "Client IP Address";
L7_char8 *pStrInfo_base_ClientIpMask = "Client IP Mask";
L7_char8 *pStrInfo_base_ClientMode = "Client Mode";
L7_char8 *pStrInfo_base_CmdLoggerCfg = "Command Logger Configuration";
L7_char8 *pStrInfo_base_CompFilter = "Component Filter";
L7_char8 *pStrInfo_base_CfgFileDownloadCancelled = "Configuration file download cancelled";
L7_char8 *pStrInfo_base_ConfirmCfgFileDownload = "Confirm Configuration File Download";
L7_char8 *pStrInfo_base_ConflictIpAddr = "Conflict IP address";
L7_char8 *pStrInfo_base_ConflictLoggingMode = "Conflict Logging Mode";
L7_char8 *pStrInfo_base_ConnFrom = "Connection From";
L7_char8 *pStrInfo_base_ConsoleLogCfg = "Console Log Configuration";
L7_char8 *pStrInfo_base_CouldntDelIpv6Addr = "Couldnt Delete IPv6 Address";
L7_char8 *pStrInfo_base_Count = "Count";
L7_char8 *pStrInfo_base_CurrentActive = "Current-active";
L7_char8 *pStrInfo_base_CustomVal = "Custom Value";
L7_char8 *pStrInfo_base_CustomerId = "Customer ID";
L7_char8 *pStrInfo_base_DhcpSrvrBindingsInfo = "DHCP Server Bindings Information";
L7_char8 *pStrInfo_base_DhcpSrvrConflictsInfo = "DHCP Server Conflicts Information";
L7_char8 *pStrInfo_base_DhcpSrvrGlobalCfg = "DHCP Server Global Configuration";
L7_char8 *pStrInfo_base_DhcpSrvrPoolCfg = "DHCP Server Pool Configuration";
L7_char8 *pStrInfo_base_DhcpSrvrPoolOptions = "DHCP Server Pool Options";
L7_char8 *pStrInfo_base_DhcpSrvrResetCfg = "DHCP Server Reset Configuration";
L7_char8 *pStrInfo_base_DhcpSrvrStats = "DHCP Server Statistics";
L7_char8 *pStrInfo_base_Dhcpv6 = "DHCPV6";
L7_char8 *pStrInfo_base_Diffserv = "DIFFSERV";
L7_char8 *pStrInfo_base_DiffservClassL3protoIpv4Feat = "DIFFSERV_CLASS_L3PROTO_IPV4_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassL3protoIpv6Feat = "DIFFSERV_CLASS_L3PROTO_IPV6_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchCos2Feat = "DIFFSERV_CLASS_MATCH_COS2_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchCosFeat = "DIFFSERV_CLASS_MATCH_COS_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchDstipFeat = "DIFFSERV_CLASS_MATCH_DSTIP_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchDstl4portFeat = "DIFFSERV_CLASS_MATCH_DSTL4PORT_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchDstmacFeat = "DIFFSERV_CLASS_MATCH_DSTMAC_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchEtypeFeat = "DIFFSERV_CLASS_MATCH_ETYPE_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchEveryFeat = "DIFFSERV_CLASS_MATCH_EVERY_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchExclFeat = "DIFFSERV_CLASS_MATCH_EXCLUDE_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIpdscpFeat = "DIFFSERV_CLASS_MATCH_IPDSCP_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIpprecedenceFeat = "DIFFSERV_CLASS_MATCH_IPPRECEDENCE_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIptosFeat = "DIFFSERV_CLASS_MATCH_IPTOS_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIpv6DstipFeat = "DIFFSERV_CLASS_MATCH_IPV6_DSTIP_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIpv6Dstl4portFeat = "DIFFSERV_CLASS_MATCH_IPV6_DSTL4PORT_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIpv6Dstl4portRangeFeat = "DIFFSERV_CLASS_MATCH_IPV6_DSTL4PORT_RANGE_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIpv6FlowlblFeat = "DIFFSERV_CLASS_MATCH_IPV6_FLOWLBL_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIpv6IpdscpFeat = "DIFFSERV_CLASS_MATCH_IPV6_IPDSCPFEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIpv6ProtoFeat = "DIFFSERV_CLASS_MATCH_IPV6_PROTOCOL_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIpv6SrcipFeat = "DIFFSERV_CLASS_MATCH_IPV6_SRCIP_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIpv6Srcl4portFeat = "DIFFSERV_CLASS_MATCH_IPV6_SRCL4PORT_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIpv6Srcl4portRangeFeat = "DIFFSERV_CLASS_MATCH_IPV6_SRCL4PORT_RANGE_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchProtoFeat = "DIFFSERV_CLASS_MATCH_PROTOCOL_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchRefclassFeat = "DIFFSERV_CLASS_MATCH_REFCLASS_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchSrcipFeat = "DIFFSERV_CLASS_MATCH_SRCIP_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchSrcl4portFeat = "DIFFSERV_CLASS_MATCH_SRCL4PORT_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchSrcmacFeat = "DIFFSERV_CLASS_MATCH_SRCMAC_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchIPv6macFeat = "DIFFSERV_CLASS_MATCH_IPV6_MAC_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchSupportsMaskingFeat = "DIFFSERV_CLASS_MATCH_SUPPORTS_MASKING_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchSupportsRangesFeat = "DIFFSERV_CLASS_MATCH_SUPPORTS_RANGES_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchVlan2Feat = "DIFFSERV_CLASS_MATCH_VLAN2_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassMatchVlanFeat = "DIFFSERV_CLASS_MATCH_VLAN_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassTypeAclFeat = "DIFFSERV_CLASS_TYPE_ACL_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassTypeAllFeat = "DIFFSERV_CLASS_TYPE_ALL_FEATURE";
L7_char8 *pStrInfo_base_DiffservClassTypeAnyFeat = "DIFFSERV_CLASS_TYPE_ANY_FEATURE";
L7_char8 *pStrInfo_base_DiffservFeatSupported = "DIFFSERV_FEATURE_SUPPORTED";
L7_char8 *pStrInfo_base_DiffservPhbAf1xFeat = "DIFFSERV_PHB_AF1X_FEATURE";
L7_char8 *pStrInfo_base_DiffservPhbAf2xFeat = "DIFFSERV_PHB_AF2X_FEATURE";
L7_char8 *pStrInfo_base_DiffservPhbAf3xFeat = "DIFFSERV_PHB_AF3X_FEATURE";
L7_char8 *pStrInfo_base_DiffservPhbAf4xFeat = "DIFFSERV_PHB_AF4X_FEATURE";
L7_char8 *pStrInfo_base_DiffservPhbCsFeat = "DIFFSERV_PHB_CS_FEATURE";
L7_char8 *pStrInfo_base_DiffservPhbEfFeat = "DIFFSERV_PHB_EF_FEATURE";
L7_char8 *pStrInfo_base_DiffservPhbOtherFeat = "DIFFSERV_PHB_OTHER_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrAssignQueueFeat = "DIFFSERV_POLICY_ATTR_ASSIGN_QUEUE_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrBandwidthFeat = "DIFFSERV_POLICY_ATTR_BANDWIDTH_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrDropFeat = "DIFFSERV_POLICY_ATTR_DROP_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrExpediteFeat = "DIFFSERV_POLICY_ATTR_EXPEDITE_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrMarkCos2valFeat = "DIFFSERV_POLICY_ATTR_MARK_COS2VAL_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrMarkCosvalFeat = "DIFFSERV_POLICY_ATTR_MARK_COSVAL_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrMarkCosAsCos2Feat = "DIFFSERV_POLICY_ATTR_MARK_COSASCOS2_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrMarkIpdscpvalFeat = "DIFFSERV_POLICY_ATTR_MARK_IPDSCPVAL_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrMarkIpprecedencevalFeat = "DIFFSERV_POLICY_ATTR_MARK_IPPRECEDENCEVAL_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrPoliceColorawareFeat = "DIFFSERV_POLICY_ATTR_POLICE_COLORAWARE_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrPoliceSimpleFeat = "DIFFSERV_POLICY_ATTR_POLICE_SIMPLE_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrPoliceSinglerateFeat = "DIFFSERV_POLICY_ATTR_POLICE_SINGLERATE_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrPoliceTworateFeat = "DIFFSERV_POLICY_ATTR_POLICE_TWORATE_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrRandomdropFeat = "DIFFSERV_POLICY_ATTR_RANDOMDROP_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrShapeAverageFeat = "DIFFSERV_POLICY_ATTR_SHAPE_AVERAGE_FEATURE";
L7_char8 *pStrInfo_base_DiffservPolicyAttrShapePeakFeat = "DIFFSERV_POLICY_ATTR_SHAPE_PEAK_FEATURE";
L7_char8 *pStrInfo_base_DiffservServiceInAllportsFeat = "DIFFSERV_SERVICE_IN_ALLPORTS_FEATURE";
L7_char8 *pStrInfo_base_DirectedPortMirroring = "DIRECTED_PORT_MIRRORING";
L7_char8 *pStrInfo_base_ProxyArp = "IPMAP_PROXY_ARP";
L7_char8 *pStrInfo_base_Multinetting = "IPMAP_MULTINETTING";
L7_char8 *pStrInfo_base_RejectRoute = "IPMAP_REJECTROUTE";
L7_char8 *pStrInfo_base_DnsSrvrAddr1 = "DNS Server Address 1";
L7_char8 *pStrInfo_base_DnsSrvrAddr2 = "DNS Server Address 2";
L7_char8 *pStrInfo_base_DnsSrvrAddr3 = "DNS Server Address 3";
L7_char8 *pStrInfo_base_DnsSrvrAddr4 = "DNS Server Address 4";
L7_char8 *pStrInfo_base_DnsSrvrAddr5 = "DNS Server Address 5";
L7_char8 *pStrInfo_base_DnsSrvrAddr6 = "DNS Server Address 6";
L7_char8 *pStrInfo_base_DnsSrvrAddr7 = "DNS Server Address 7";
L7_char8 *pStrInfo_base_DnsSrvrAddr8 = "DNS Server Address 8";
L7_char8 *pStrInfo_base_DnsSrvrAddres = "DNS Server Addresses";
L7_char8 *pStrInfo_base_DosCntrl = "DOSCONTROL";
L7_char8 *pStrInfo_base_DosCntrlFirstfragFeat = "DOSCONTROL_FIRSTFRAG_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlIcmpFeat = "DOSCONTROL_ICMP_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlIcmpv4Feat = "DOSCONTROL_ICMPV4_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlIcmpv6Feat = "DOSCONTROL_ICMPV6_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlIcmpFragFeat = "DOSCONTROL_ICMPFRAG_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlL4portFeat = "DOSCONTROL_L4PORT_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlTcpportFeat = "DOSCONTROL_TCPPORT_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlUdpportFeat = "DOSCONTROL_UDPPORT_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlSipdipFeat = "DOSCONTROL_SIPDIP_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlSmacdmacFeat = "DOSCONTROL_SMACDMAC_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlTcpflagFeat = "DOSCONTROL_TCPFLAG_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlTcpflagSeqFeat = "DOSCONTROL_TCPFLAGSEQ_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlTcpFinUrgPshFeat = "DOSCONTROL_TCPFINURGPSH_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlTcpOffsetFeat = "DOSCONTROL_TCPOFFSET_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlTcpSynFeat = "DOSCONTROL_TCPSYN_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlTcpSynFinFeat = "DOSCONTROL_TCPSYNFIN_FEATURE";
L7_char8 *pStrInfo_base_DosCntrlTcpfragFeat = "DOSCONTROL_TCPFRAG_FEATURE";
L7_char8 *pStrInfo_base_Dot1adPBFeat = "DOT1AD_PB_FEATURE";
L7_char8 *pStrInfo_base_Dot1pFeat = "DOT1P_FEATURE";
L7_char8 *pStrInfo_base_Dot1pUsrPriPerIntfFeat = "DOT1P_USER_PRIORITY_PER_INTERFACE_FEATURE";
L7_char8 *pStrInfo_base_Dot1s_1 = "DOT1S";
L7_char8 *pStrInfo_base_Dot1sFeat = "DOT1S_FEATURE";
L7_char8 *pStrInfo_base_Dot1sBPDUGuardFeat = "DOT1S_BPDUGUARD_FEATURE";
L7_char8 *pStrInfo_base_Dot1sBPDUFloodFeat = "DOT1S_BPDUFLOOD_FEATURE";
L7_char8 *pStrInfo_base_Dot1sRootGuardFeat = "DOT1S_ROOTGUARD_FEATURE";
L7_char8 *pStrInfo_base_Dot1sLoopGuardFeat = "DOT1S_LOOPGUARD_FEATURE";
L7_char8 *pStrInfo_base_Dot1sBPDUFilterFeat = "DOT1S_BPDUFILTER_FEATURE";
L7_char8 *pStrInfo_base_Dot1xSetCntrldirFeat = "DOT1X_SET_CONTROLDIR_FEATURE";
L7_char8 *pStrInfo_base_Dot1xSetKeytxenabledFeat = "DOT1X_SET_KEYTXENABLED_FEATURE";
L7_char8 *pStrInfo_base_Dot1xVlansAssignedFeat = "DOT1X_VLANS_ASSIGNED_FEATURE";
L7_char8 *pStrInfo_base_Dot1xMacBasedAuthFeat = "DOT1X_MACBASEDAUTH_FEATURE";
L7_char8 *pStrInfo_base_Dvlan = "DVLAN";
L7_char8 *pStrInfo_base_DynamicArpInspection = "DYNAMIC_ARP_INSPECTION";
L7_char8 *pStrInfo_base_Days_1 = "Days";
L7_char8 *pStrInfo_base_DeflFacility = "Default Facility";
L7_char8 *pStrInfo_base_DeflRtrAddr1 = "Default Router Address 1";
L7_char8 *pStrInfo_base_DeflRtrAddr2 = "Default Router Address 2";
L7_char8 *pStrInfo_base_DeflRtrAddr3 = "Default Router Address 3";
L7_char8 *pStrInfo_base_DeflRtrAddr4 = "Default Router Address 4";
L7_char8 *pStrInfo_base_DeflRtrAddr5 = "Default Router Address 5";
L7_char8 *pStrInfo_base_DeflRtrAddr6 = "Default Router Address 6";
L7_char8 *pStrInfo_base_DeflRtrAddr7 = "Default Router Address 7";
L7_char8 *pStrInfo_base_DeflRtrAddr8 = "Default Router Address 8";
L7_char8 *pStrInfo_base_DeflRtrAddres = "Default Router Addresses";
L7_char8 *pStrInfo_base_DelOptionCode = "Delete Option Code";
L7_char8 *pStrInfo_base_DeliveringPower = "Delivering Power";
L7_char8 *pStrInfo_base_DenialOfServiceCfg = "Denial of Service Configuration";
L7_char8 *pStrInfo_base_DenialOfServiceFirstFragment = "Denial of Service First Fragment";
L7_char8 *pStrInfo_base_DenialOfServiceIcmp = "Denial of Service ICMP";
L7_char8 *pStrInfo_base_DenialOfServiceIcmpv4 = "Denial of Service ICMPv4";
L7_char8 *pStrInfo_base_DenialOfServiceIcmpv6 = "Denial of Service ICMPv6";
L7_char8 *pStrInfo_base_DenialOfServiceIcmpfrag = "Denial of Service ICMP Fragment";
L7_char8 *pStrInfo_base_DenialOfServiceL4Port = "Denial of Service L4 Port";
L7_char8 *pStrInfo_base_DenialOfServiceTcpPort = "Denial of Service TCP Port";
L7_char8 *pStrInfo_base_DenialOfServiceUdpPort = "Denial of Service UDP Port";
L7_char8 *pStrInfo_base_DenialOfServiceMaxIcmpSize = "Denial of Service Max ICMP Size";
L7_char8 *pStrInfo_base_DenialOfServiceMaxIcmpv4Size = "Denial of Service Max ICMPv4 Size";
L7_char8 *pStrInfo_base_DenialOfServiceMaxIcmpv6Size = "Denial of Service Max ICMPv6 Size";
L7_char8 *pStrInfo_base_DenialOfServiceMinTcpHdrSize = "Denial of Service Min TCP Hdr Size";
L7_char8 *pStrInfo_base_DenialOfServiceSipDip = "Denial of Service SIP=DIP";
L7_char8 *pStrInfo_base_DenialOfServiceSmacDmac = "Denial of Service SMAC=DMAC";
L7_char8 *pStrInfo_base_DenialOfServiceTcpFlag = "Denial of Service TCP Flag";
L7_char8 *pStrInfo_base_DenialOfServiceTcpFlagSeq = "Denial of Service TCP Flag&Sequence";
L7_char8 *pStrInfo_base_DenialOfServiceTcpOffset = "Denial of Service TCP Offset";
L7_char8 *pStrInfo_base_DenialOfServiceTcpSyn = "Denial of Service TCP SYN";
L7_char8 *pStrInfo_base_DenialOfServiceTcpSynFin = "Denial of Service TCP SYN&FIN";
L7_char8 *pStrInfo_base_DenialOfServiceTcpFinUrgPsh = "Denial of Service TCP FIN&URG&PSH";
L7_char8 *pStrInfo_base_DenialOfServiceTcpFragment = "Denial of Service TCP Fragment";
L7_char8 *pStrInfo_base_DstPort = "Destination Port";
L7_char8 *pStrInfo_base_HashModeWebFeature = "DOT3AD_HASHMODE_FEATURE";
L7_char8 *pStrInfo_base_HashModeWebFeature1 = "DOT3AD_HASHMODE_SA_VLAN_ETYPE_INTF_FEATURE";
L7_char8 *pStrInfo_base_HashModeWebFeature2 = "DOT3AD_HASHMODE_DA_VLAN_ETYPE_INTF_FEATURE";
L7_char8 *pStrInfo_base_HashModeWebFeature3 = "DOT3AD_HASHMODE_SADA_VLAN_ETYPE_INTF_FEATURE";
L7_char8 *pStrInfo_base_HashModeWebFeature4 = "DOT3AD_HASHMODE_SIP_SPORT_FEATURE";
L7_char8 *pStrInfo_base_HashModeWebFeature5 = "DOT3AD_HASHMODE_DIP_DPORT_FEATURE";
L7_char8 *pStrInfo_base_HashModeWebFeature6 = "DOT3AD_HASHMODE_SIP_DIP_SPORT_DPORT_FEATURE";
L7_char8 *pStrInfo_base_DoubleVlanTunneling = "Double VLAN Tunneling";
L7_char8 *pStrInfo_base_DoubleVlanTunnelingSummary = "Double VLAN Tunneling Summary";
L7_char8 *pStrInfo_base_DownloadingCfgWillForceAResetOnCompletionConfirmToContinue = "Downloading configuration will force a reset on completion. Are you sure you want to continue?";
L7_char8 *pStrInfo_base_DualImageCfg = "Dual Image Configuration";
L7_char8 *pStrInfo_base_DualImageStatus = "Dual Image Status";
L7_char8 *pStrErr_base_FieldInvalidInput = "Either %s or %s should be specified.";
L7_char8 *pStrErr_base_FieldInvalidInput_1 = "Either/None of %s or %s should be specified but not both.";
L7_char8 *pStrInfo_base_EncryptionKey = "Encryption Key";
L7_char8 *pStrInfo_base_EncryptionProto = "Encryption Protocol";
L7_char8 *pStrInfo_base_ExcldAddres_1 = "Excluded Addresses";
L7_char8 *pStrInfo_base_ExercisingFuncWillCauseAllCfgParamsToBeResetToDeflVals = "Exercising this function will cause all configuration parameters to be reset to their default values.";
L7_char8 *pStrInfo_base_ExercisingFuncWillCauseAllSysLoginPasswdsToBeResetToDeflVals = "Exercising this function will cause all system login passwords to be reset to their default values.";
L7_char8 *pStrInfo_base_FastpathQos = "FASTPATH QoS";
L7_char8 *pStrInfo_base_FdbAgetimePerVlan = "FDB_AGETIME_PER_VLAN";
L7_char8 *pStrInfo_base_FilterDestPortFiltering = "FILTER_DEST_PORT_FILTERING";
L7_char8 *pStrInfo_base_FilterSrcPortFiltering = "FILTER_SOURCE_PORT_FILTERING";
L7_char8 *pStrErr_base_ImageAlreadyCfgured = "Failed to activate the image. Backup image already configured. Can't be modified.";
L7_char8 *pStrErr_base_FailedToClrSrvrStats = "Failed to clear Server Statistics";
L7_char8 *pStrErr_base_FailedToClrTrapLog = "Failed to clear Trap Log.";
L7_char8 *pStrErr_base_FailedToConvertSrcIntfMask = "Failed to convert source interface mask";
L7_char8 *pStrErr_base_FailedToDelCount = "Failed to delete %s. %d";
L7_char8 *pStrErr_base_Updating = "Failed to update the file.";
L7_char8 *pStrInfo_base_FailureWhileStoringInFlash = "Failure while storing in flash!";
L7_char8 *pStrInfo_base_Fault = "Fault";
L7_char8 *pStrInfo_base_FileType = "File Type";
L7_char8 *pStrInfo_base_FileFailedCrcCheck = "File failed CRC check!";
L7_char8 *pStrInfo_base_FileTransferOperationStarted = "File transfer operation started";
L7_char8 *pStrInfo_base_FlowCntrlMode = "Flow Control Mode";
L7_char8 *pStrInfo_base_FormSubmissionFailed = "Form Submission Failed!";
L7_char8 *pStrInfo_base_FwdDbase = "Forwarding Database";
L7_char8 *pStrInfo_base_FwdDbaseCfg = "Forwarding Database Configuration";
L7_char8 *pStrInfo_base_FwdDbaseSearch = "Forwarding Database Search";
L7_char8 *pStrInfo_base_FwdState = "Forwarding State";
L7_char8 *pStrInfo_base_From = "From";
L7_char8 *pStrInfo_base_GvrpPdusRcvd = "GVRP PDUs Received";
L7_char8 *pStrInfo_base_GeneralError = "General Error";
L7_char8 *pStrInfo_base_HttpAdminMode = "HTTP Admin Mode";
L7_char8 *pStrInfo_base_HttpConfiguration = "HTTP Configuration";
L7_char8 *pStrInfo_base_HttpSessionHardTimeout = "HTTP Session Hard Timeout";
L7_char8 *pStrInfo_base_HttpSessionSoftTimeout = "HTTP Session Soft Timeout";
L7_char8 *pStrInfo_base_Hex_1 = "Hex";
L7_char8 *pStrInfo_base_HostIpAddr = "Host IP Address";
L7_char8 *pStrInfo_base_HostMask = "Host Mask";
L7_char8 *pStrInfo_base_HostNum = "Host Number";
L7_char8 *pStrInfo_base_HostsCfg = "Hosts Configuration";
L7_char8 *pStrInfo_base_Hours_1 = "Hours";
L7_char8 *pStrInfo_base_IgmpSnooping_1 = "IGMP_SNOOPING";
L7_char8 *pStrInfo_base_IgmpSnoopingPerVlan = "IGMP_SNOOPING_PER_VLAN";
L7_char8 *pStrInfo_base_IpAddrAndGatewayDoNotLieOnSameSubnet = "IP address and gateway do not lie on the same subnet.";
L7_char8 *pStrInfo_base_IpAddrSubnetMaskAndGateway = "IP address, Subnet Mask, and Gateway";
L7_char8 *pStrInfo_base_IpsubnetVlan = "IPSUBNET_VLAN";
L7_char8 *pStrInfo_base_Ipv6_2 = "IPV6";
L7_char8 *pStrInfo_base_Ipv6AclDestipFeatSupport = "IPV6_ACL_RULE_MATCH_DESTIP_FEATURE";
L7_char8 *pStrInfo_base_Ipv6AclDstl4portFeatSupport = "IPV6_ACL_RULE_MATCH_DSTL4PORT_FEATURE";
L7_char8 *pStrInfo_base_Ipv6AclDstl4portRangeFeatSupport = "IPV6_ACL_RULE_MATCH_DSTL4PORT_RANGE_FEATURE";
L7_char8 *pStrInfo_base_Ipv6AclFlowlblFeatSupport = "IPV6_ACL_FLOWLBL_FEATURE_SUPPORT";
L7_char8 *pStrInfo_base_Ipv6AclSrcipFeatSupport = "IPV6_ACL_RULE_MATCH_SRCIP_FEATURE";
L7_char8 *pStrInfo_base_Ipv6AclSrcl4portFeatSupport = "IPV6_ACL_RULE_MATCH_SRCL4PORT_FEATURE";
L7_char8 *pStrInfo_base_Ipv6AclSrcl4portRangeFeatSupport = "IPV6_ACL_RULE_MATCH_SRCL4PORT_RANGE_FEATURE";
L7_char8 *pStrInfo_base_Ipv6AclIpDscpFeatSupport = "IPV6_ACL_RULE_MATCH_IPDSCP_FEATURE";
L7_char8 *pStrInfo_base_Ipv6AclTypeFeatSupport = "IPV6_ACL_TYPE_FEATURE_SUPPORT";
L7_char8 *pStrInfo_base_Ipv6Mgmt = "IPV6_MGMT";
L7_char8 *pStrInfo_base_IpMap = "IP_MAP";
L7_char8 *pStrInfo_base_IdleTime = "Idle Time";
L7_char8 *pStrInfo_base_ImageName = "Image Name";
L7_char8 *pStrInfo_base_Image1Desc = "Image1 Description";
L7_char8 *pStrInfo_base_Image1Ver = "Image1 Ver";
L7_char8 *pStrInfo_base_Image2Desc = "Image2 Description";
L7_char8 *pStrInfo_base_Image2Ver = "Image2 Ver";
L7_char8 *pStrInfo_base_InconsistentValsForMaxttlAndInitttl = "Inconsistent values for maxTTL and initTTL.";
L7_char8 *pStrInfo_base_Initttl = "InitTTL";
L7_char8 *pStrInfo_base_IntfEthertype = "Interface EtherType";
L7_char8 *pStrErr_base_InvalidHostAddr = "Invalid %s given.";
L7_char8 *pStrErr_base_Ipv6Gateway = "Invalid IPv6 Gateway";
L7_char8 *pStrErr_base_Key_2 = "Invalid Key";
L7_char8 *pStrErr_base_NameEntered = "Invalid name entered.";
L7_char8 *pStrInfo_base_InventoryInfo = "Inventory Information";
L7_char8 *pStrInfo_base_JavaAdminMode = "Java Admin Mode";
L7_char8 *pStrInfo_base_JavaMode = "Java Mode";
L7_char8 *pStrInfo_base_L7Dot1qIngressfilterFeatId = "L7_DOT1Q_INGRESSFILTER_FEATURE_ID";
L7_char8 *pStrInfo_base_L7DvlantagCustidFeatId = "L7_DVLANTAG_CUSTID_FEATURE_ID";
L7_char8 *pStrInfo_base_L7DvlantagEthertypeFeatId = "L7_DVLANTAG_ETHERTYPE_FEATURE_ID";
L7_char8 *pStrInfo_base_L7DvlantagEthertypePerIntfFeatId = "L7_DVLANTAG_ETHERTYPE_PER_INTERFACE_FEATURE_ID";
L7_char8 *pStrInfo_base_L7DvlanMultiTpidsFeatId = "L7_DVLANTAG_MULTI_TPIDS_FEATURE_ID";
L7_char8 *pStrInfo_base_L7DvlantagFeatSupported = "L7_DVLANTAG_FEATURE_SUPPORTED";
L7_char8 *pStrInfo_base_L7FpsFeat = "L7_FPS_FEATURE";
L7_char8 *pStrInfo_base_L7FpsPortModeCfgFeat = "L7_FPS_PORT_MODE_CFG_FEATURE";
L7_char8 *pStrInfo_base_L7FpsQosReplacementFeat = "L7_FPS_QOS_REPLACEMENT_FEATURE";
L7_char8 *pStrInfo_base_L7NimJumboframesFeat = "L7_NIM_JUMBOFRAMES_FEATURE";
L7_char8 *pStrInfo_base_L7NimJumboframesPerIntfFeat = "L7_NIM_JUMBOFRAMES_PER_INTERFACE_FEATURE";
L7_char8 *pStrInfo_base_LacpMode = "LACP Mode";
L7_char8 *pStrInfo_base_Layer3 = "LAYER3";
L7_char8 *pStrInfo_base_License = "LICENSE";
L7_char8 *pStrInfo_base_LinkUpDown = "Link Up/Down";
L7_char8 *pStrInfo_base_LocallyAdministered = "Locally Administered";
L7_char8 *pStrInfo_base_LocallyAdministeredMacAddrMustBeSetBeforeMacAddrTypeCanBeSelected = "Locally Administered MAC Address must be set before the MAC Address Type can be selected.";
L7_char8 *pStrInfo_base_LockoutStatus = "Lockout Status";
L7_char8 *pStrInfo_base_LoginSessions = "Login Sessions";
L7_char8 *pStrInfo_base_LoginUsrs = "Login Users";
L7_char8 *pStrInfo_base_LoginFailure = "Login failure";
L7_char8 *pStrInfo_base_Logout = "Logout";
L7_char8 *pStrInfo_base_MacAddrSearch = "MAC Address Search";
L7_char8 *pStrInfo_base_MacAddrSearchRequiresAMacAddrInForm00010123456789Ab = "MAC Address Search requires a MAC address in form 00:01:01:23:45:67:89:AB.";
L7_char8 *pStrInfo_base_MacFilter_1 = "MAC_FILTER";
L7_char8 *pStrInfo_base_MacVlan = "MAC_VLAN";
L7_char8 *pStrInfo_base_Mcast = "MCAST";
L7_char8 *pStrInfo_base_MldSnooping_1 = "MLD_SNOOPING";
L7_char8 *pStrInfo_base_MldSnoopingPerVlan = "MLD_SNOOPING_PER_VLAN";
L7_char8 *pStrInfo_base_MultipleProtPortGrps = "MULTIPLE_PROT_PORT_GROUPS";
L7_char8 *pStrInfo_base_Maxfail = "MaxFail";
L7_char8 *pStrInfo_base_Maxttl = "MaxTTL";
L7_char8 *pStrInfo_base_MaxFrameSize = "Maximum Frame Size";
L7_char8 *pStrInfo_base_MaxNumOfHttpSessions = "Maximum Number of HTTP Sessions";
L7_char8 *pStrInfo_base_MaxNumOfTelnetSessions_1 = "Maximum Number of Telnet Sessions";
L7_char8 *pStrInfo_base_MaxSessions = "Maximum Sessions";
L7_char8 *pStrInfo_base_MaxAllowableNumOfSntpSrvrsAlreadyCfgured = "Maximum allowable number of SNTP Servers already configured.";
L7_char8 *pStrInfo_base_MaxNumOfSrcPortsAlreadyCfguredForSession = "Maximum number of source ports already configured for this session.";
L7_char8 *pStrInfo_base_McastStormLvl = "Mcast Storm Level";
L7_char8 *pStrInfo_base_McastStormMode = "Mcast Storm Mode";
L7_char8 *pStrInfo_base_Method1_1 = "Method 1";
L7_char8 *pStrInfo_base_Method2_1 = "Method 2";
L7_char8 *pStrInfo_base_Method3_1 = "Method 3";
L7_char8 *pStrInfo_base_MethodList = "Method List";
L7_char8 *pStrInfo_base_Minutes_1 = "Minutes";
L7_char8 *pStrInfo_base_Mirrored = "Mirrored";
L7_char8 *pStrInfo_base_Crit = "Critical";
L7_char8 *pStrInfo_base_High = "High";
L7_char8 *pStrInfo_base_Low = "Low";
L7_char8 *pStrInfo_base_Missing16308 = "Missing 16308";
L7_char8 *pStrInfo_base_Missing16309 = "Missing 16309";
L7_char8 *pStrInfo_base_Missing16310 = "Missing 16310";
L7_char8 *pStrInfo_base_Missing16312 = "Missing 16312";
L7_char8 *pStrInfo_base_McastStormRecoveryLvl = "Multicast Storm Recovery Level";
L7_char8 *pStrInfo_base_McastStormRecoveryMode = "Multicast Storm Recovery Mode";
L7_char8 *pStrInfo_base_MultiplePortMirroring = "Multiple Port Mirroring";
L7_char8 *pStrInfo_base_MultiplePortMirroringAddSrcPorts = "Multiple Port Mirroring - Add Source Ports";
L7_char8 *pStrInfo_base_MultiplePortMirroringRemoveSrcPorts = "Multiple Port Mirroring - Remove Source Ports";
L7_char8 *pStrInfo_base_MultipleUsrs = "Multiple Users";
L7_char8 *pStrInfo_base_MustEnblOspfAdminMode = "Must enable OSPF admin mode.";
L7_char8 *pStrInfo_base_NetbiosNameSrvrAddr1 = "NetBIOS Name Server Address 1";
L7_char8 *pStrInfo_base_NetbiosNameSrvrAddr2 = "NetBIOS Name Server Address 2";
L7_char8 *pStrInfo_base_NetbiosNameSrvrAddr3 = "NetBIOS Name Server Address 3";
L7_char8 *pStrInfo_base_NetbiosNameSrvrAddr4 = "NetBIOS Name Server Address 4";
L7_char8 *pStrInfo_base_NetbiosNameSrvrAddr5 = "NetBIOS Name Server Address 5";
L7_char8 *pStrInfo_base_NetbiosNameSrvrAddr6 = "NetBIOS Name Server Address 6";
L7_char8 *pStrInfo_base_NetbiosNameSrvrAddr7 = "NetBIOS Name Server Address 7";
L7_char8 *pStrInfo_base_NetbiosNameSrvrAddr8 = "NetBIOS Name Server Address 8";
L7_char8 *pStrInfo_base_NetbiosNameSrvrAddres = "NetBIOS Name Server Addresses";
L7_char8 *pStrInfo_base_NetbiosNodeType = "NetBIOS Node Type";
L7_char8 *pStrInfo_base_NwConnectivityCfg = "Network Connectivity Configuration";
L7_char8 *pStrInfo_base_NwMask_2 = "Network Mask";
L7_char8 *pStrInfo_base_NwNdpSummary = "Network NDP Summary";
L7_char8 *pStrInfo_base_NwNum_1 = "Network Number";
L7_char8 *pStrInfo_base_NewSntpSrvr = "New SNTP Server";
L7_char8 *pStrInfo_base_NextSrvrAddr = "Next Server Address";
L7_char8 *pStrInfo_base_NextActive = "Next-active";
L7_char8 *pStrInfo_base_NoValidDvlanTunnelingIntfsFound = "No valid DVlan tunneling interfaces found";
L7_char8 *pStrInfo_base_NoValidIntfsFound = "No valid interfaces found";
L7_char8 *pStrInfo_base_NoteMaxFrameSizeWillBeAppliedSysWideAndSetForAllPorts = "Note: Maximum Frame Size will be applied system-wide and set for all ports.";
L7_char8 *pStrInfo_base_OspfTraps = "OSPF Traps";
L7_char8 *pStrInfo_base_Ospfv3 = "OSPFV3";
L7_char8 *pStrInfo_base_OctetsRcvd = "Octets Received";
L7_char8 *pStrInfo_base_OnlyOneIntfCanRunDhcpCfgureNwProtoToBootpOrNone = "Only one interface can run DHCP. Configure network protocol to bootp or none.";
L7_char8 *pStrInfo_base_OptionCode = "Option Code";
L7_char8 *pStrInfo_base_OptionCodeOptionValMustBeSpecifiedAsAsciiHexIpAddr = "Option Code. Option Value must be specified as Ascii / Hex / IP Address";
L7_char8 *pStrInfo_base_OptionCodeOptionValMustBeSpecifiedAsEitherAsciiOrHexOrIpAddrMoreThanOneTypesIsNotAllowed = "Option Code. Option Value must be specified as either Ascii or Hex or IP Address. More than one Types is not allowed";
L7_char8 *pStrInfo_base_OptionValIpAddr1 = "Option Value IP Address 1";
L7_char8 *pStrInfo_base_OptionValIpAddr2 = "Option Value IP Address 2";
L7_char8 *pStrInfo_base_OptionValIpAddr3 = "Option Value IP Address 3";
L7_char8 *pStrInfo_base_OptionValIpAddr4 = "Option Value IP Address 4";
L7_char8 *pStrInfo_base_OptionValIpAddr5 = "Option Value IP Address 5";
L7_char8 *pStrInfo_base_OptionValIpAddr6 = "Option Value IP Address 6";
L7_char8 *pStrInfo_base_OptionValIpAddr7 = "Option Value IP Address 7";
L7_char8 *pStrInfo_base_OptionValIpAddr8 = "Option Value IP Address 8";
L7_char8 *pStrInfo_base_OptionValTotalLenExceedsAllowableLen = "Option Value Total Length exceeds Allowable Length";
L7_char8 *pStrInfo_base_OtherFault = "Other Fault";
L7_char8 *pStrInfo_base_OutboundTelnet = "OUTBOUND_TELNET";
L7_char8 *pStrInfo_base_OutboundTelnetClientCfg = "Outbound Telnet Client Configuration";
L7_char8 *pStrInfo_base_PasswordManagement = "Password Management";
L7_char8 *pStrInfo_base_Pbvlan = "PBVLAN";
L7_char8 *pStrInfo_base_PolicyBcastCntrlFeat = "POLICY_BCAST_CONTROL_FEATURE";
L7_char8 *pStrInfo_base_PolicyMcastCntrlFeat = "POLICY_MCAST_CONTROL_FEATURE";
L7_char8 *pStrInfo_base_PolicyPortBcastCntrlFeat = "POLICY_PORT_BCAST_CONTROL_FEATURE";
L7_char8 *pStrInfo_base_PolicyPortFlowCntrlFeat = "POLICY_PORT_FLOW_CONTROL_FEATURE";
L7_char8 *pStrInfo_base_PolicyPortMcastCntrlFeat = "POLICY_PORT_MCAST_CONTROL_FEATURE";
L7_char8 *pStrInfo_base_PolicyPortUcastCntrlFeat = "POLICY_PORT_UCAST_CONTROL_FEATURE";
L7_char8 *pStrInfo_base_PolicyUcastCntrlFeat = "POLICY_UCAST_CONTROL_FEATURE";
L7_char8 *pStrInfo_base_PortMaclock = "PORT_MACLOCK";
L7_char8 *pStrInfo_base_ProtectedPorts = "PROTECTED_PORTS";
L7_char8 *pStrInfo_base_PasswdExpirationDate = "Password Expiration Date";
L7_char8 *pStrInfo_base_PasswdMinLen = "Password Minimum Length";
L7_char8 *pStrInfo_base_PasswdExpiredPleaseChgPasswd = "Password expired.  Please change the password.";
L7_char8 *pStrInfo_base_PasswdMustBeBetweenAndCharsInLen = "Password must be between %u and %u characters in length.";
L7_char8 *pStrInfo_base_PersistentLogCfg = "Persistent Log Configuration";
L7_char8 *pStrInfo_base_PersistentLogs = "Persistent Logs";
L7_char8 *pStrInfo_base_PhyAddr = "Physical Address";
L7_char8 *pStrInfo_base_PhyStatus = "Physical Status";
L7_char8 *pStrInfo_base_PingFailed = "Ping Failed";
L7_char8 *pStrInfo_base_PingPkts_1 = "Ping Packets";
L7_char8 *pStrInfo_base_PoeCfg = "PoE Configuration";
L7_char8 *pStrInfo_base_Pool = "Pool";
L7_char8 *pStrInfo_base_PoolTypeSetBackToUnallocatedHostSetMustForAManualPool = "Pool Type set back to Unallocated: Host set must for a Manual Pool";
L7_char8 *pStrInfo_base_Poolname = "PoolName";
L7_char8 *pStrInfo_base_PortCfg = "Port Configuration";
L7_char8 *pStrInfo_base_PortDetailedStats = "Port Detailed Statistics";
L7_char8 *pStrInfo_base_PortSummary = "Port Summary";
L7_char8 *pStrInfo_base_PortSummaryStats = "Port Summary Statistics";
L7_char8 *pStrInfo_base_PortType = "Port Type";
L7_char8 *pStrInfo_base_PortlistBitOffset = "PortList Bit Offset";
L7_char8 *pStrInfo_base_PrefixLen_2 = "Prefix Length";
L7_char8 *pStrInfo_base_PrimaryRef = "Primary Reference";
L7_char8 *pStrInfo_base_ProbesPerHop = "Probes Per Hop";
L7_char8 *pStrInfo_base_RtrDisc = "ROUTER_DISCOVERY";
L7_char8 *pStrInfo_base_RemoveSrcPort = "Remove Source Port";
L7_char8 *pStrInfo_base_ResetCfgToDefls = "Reset Configuration to Defaults";
L7_char8 *pStrInfo_base_ResetPasswdsToDefls = "Reset Passwords to Defaults";
L7_char8 *pStrInfo_base_ResetWithoutSave = "Reset without Save";
L7_char8 *pStrInfo_base_ResettingSwitchWillCauseAllOperationsOfSwitchToStopSessionWillBeBrokenAndYouWillHaveToLogInAgainAfterSwitchHasRebootedAnyUnsavedChgsWillBeLost = "Resetting the switch will cause all operations of this switch to stop.  This session will be broken and you will have to log in again after the switch has rebooted. Any unsaved changes will be lost.";
L7_char8 *pStrInfo_base_RxFcsErrs = "Rx FCS Errors";
L7_char8 *pStrInfo_base_Sid = "SID";
L7_char8 *pStrInfo_base_Sidssl = "SIDSSL";
L7_char8 *pStrInfo_base_sFlowAgentSummery = "sFlow Agent Summary";
L7_char8 *pStrInfo_base_sFlowReceiverCfg = "sFlow Receiver Configuration";
L7_char8 *pStrInfo_base_sFlowSamplerCfg = "sFlow Sampler Configuration";
L7_char8 *pStrInfo_base_sFlowPollerCfg = "sFlow Poller Configuration";
L7_char8 *pStrInfo_base_SflowInstance = " Sflow Instance ";
L7_char8 *pStrErr_base_SflowIncorrectInput = " %s Incorrect Input ";
L7_char8 *pStrErr_base_SflowSamplingRate = " Sampling Rate must be a valid integer ";
L7_char8 *pStrErr_base_SflowSamplingInterval = "Sampling Interval must be a valid integer ";
L7_char8 *pStrErr_base_SflowMaxHeaderSize = "Maximum Header must be a valid integer ";
L7_char8 *pStrErr_base_SflowMaxDatagramSize = "Maximum Datagram  must be a valid integer ";
L7_char8 *pStrErr_base_SflowCollectorPort = "Port must be a valid integer ";
L7_char8 *pStrErr_base_InvalidsFlowRcvrTime = "%s. Invalid Receiver Timeout value. Valid range is  <%u to %u>.";
L7_char8 *pStrInfo_base_Snmp2 = "SNMP";
L7_char8 *pStrInfo_base_SnmpCommunityCfg = "SNMP Community Configuration";
L7_char8 *pStrInfo_base_SnmpCommunityName = "SNMP Community Name";
L7_char8 *pStrInfo_base_SnmpSupportedMibs = "SNMP Supported MIBs";
L7_char8 *pStrInfo_base_SnmpTrapReceiverCfg = "SNMP Trap Receiver Configuration";
L7_char8 *pStrInfo_base_SnmpTrapReceiverSummary = "SNMP Trap Receiver Summary";
L7_char8 *pStrInfo_base_SnmpVer = "SNMP Version";
L7_char8 *pStrInfo_base_SnmpV1 = "SNMP v1";
L7_char8 *pStrInfo_base_SnmpV2 = "SNMP v2";
L7_char8 *pStrInfo_base_SnmpV3AccessMode = "SNMP v3 Access Mode";
L7_char8 *pStrInfo_base_SnmpV3UsrCfg = "SNMP v3 User Configuration";
L7_char8 *pStrInfo_base_SnmpUsr = "SNMP_USER";
L7_char8 *pStrInfo_base_SnmpUsrAuth = "SNMP_USER_AUTHENTICATION";
L7_char8 *pStrInfo_base_SnmpUsrEncryption = "SNMP_USER_ENCRYPTION";
L7_char8 *pStrInfo_base_Snooping = "SNOOPING";
L7_char8 *pStrInfo_base_SntpGlobalCfg = "SNTP Global Configuration";
L7_char8 *pStrInfo_base_SntpGlobalStatus = "SNTP Global Status";
L7_char8 *pStrInfo_base_SntpSrvr_1 = "SNTP Server";
L7_char8 *pStrInfo_base_SntpSrvrCfg = "SNTP Server Configuration";
L7_char8 *pStrInfo_base_SntpSrvrStatus = "SNTP Server Status";
L7_char8 *pStrInfo_base_SntpSrvrAlreadyCfguredWithSpecifiedAddr = "SNTP Server already configured with the specified address.";
L7_char8 *pStrInfo_base_Sshd = "SSHD";
L7_char8 *pStrInfo_base_SshdFeat = "SSHD_FEATURE";
L7_char8 *pStrInfo_base_Sslt = "SSLT";
L7_char8 *pStrInfo_base_SsltFeat = "SSLT_FEATURE";
L7_char8 *pStrInfo_base_SecureTransferFeat = "SECURE_TRANSFER_FEATURE";
L7_char8 *pStrInfo_base_Stacking = "STACKING";
L7_char8 *pStrInfo_base_Svl = "SVL";
L7_char8 *pStrInfo_base_Save = "Save";
L7_char8 *pStrInfo_base_SaveAllAppliedChgs = "Save All Applied Changes";
L7_char8 *pStrInfo_base_SaveAndReset = "Save and Reset";
L7_char8 *pStrInfo_base_SavingAllAppliedChgsWillCauseAllChgsToCfgPanelsThatWereAppliedButNotSavedToBeSavedThusRetainingNewValsAcrossASysReboot = "Saving all applied changes will cause all changes to configuration panels that were applied, but not saved, to be saved, thus retaining their new values across a system reboot.";
L7_char8 *pStrInfo_base_Searching = "Searching";
L7_char8 *pStrInfo_base_SecondaryRef = "Secondary Reference";
L7_char8 *pStrInfo_base_SerialPortCfg = "Serial Port Configuration";
L7_char8 *pStrInfo_base_SrvrAddrType = "Server Address Type";
L7_char8 *pStrInfo_base_SrvrPort = "Server Port";
L7_char8 *pStrInfo_base_SrvrPrecedence = "Server Precedence";
L7_char8 *pStrInfo_base_ServicePortCfg = "Service Port Configuration";
L7_char8 *pStrInfo_base_ServicePortCfgProtoCurrent = "Service Port Configuration Protocol Current";
L7_char8 *pStrInfo_base_ServicePortNdpSummary = "Service Port NDP Summary";
L7_char8 *pStrInfo_base_Session = "Session";
L7_char8 *pStrInfo_base_SessionTime = "Session Time";
L7_char8 *pStrInfo_base_SessionTimeout = "Session Timeout";
L7_char8 *pStrInfo_base_SessionType = "Session Type";
L7_char8 *pStrInfo_base_SeverityFilter = "Severity Filter";
L7_char8 *pStrInfo_base_SinceAuthIsEnbldPasswdMustBeAtLeastCharsInLen = "Since authentication is enabled, password must be at least %u characters in length.";
L7_char8 *pStrInfo_base_Size = "Size";
L7_char8 *pStrInfo_base_SlotSummary = "Slot Summary";
L7_char8 *pStrInfo_base_Slot_1 = "Slot%d";
L7_char8 *pStrInfo_base_SrcPort = "Source Port";
L7_char8 *pStrInfo_base_SrcPortS = "Source Port(s)";
L7_char8 *pStrInfo_base_SpanTree_1 = "Spanning Tree";
L7_char8 *pStrErr_base_ImageNotFound = "Specified File could not be found.";
L7_char8 *pStrInfo_base_SupportedCards = "Supported Cards";
L7_char8 *pStrInfo_base_SwitchCfg = "Switch Configuration";
L7_char8 *pStrInfo_base_SwitchDetailedStats = "Switch Detailed Statistics";
L7_char8 *pStrInfo_base_SwitchSummaryStats = "Switch Summary Statistics";
L7_char8 *pStrInfo_base_SyslogCfg = "Syslog Configuration";
L7_char8 *pStrInfo_base_SyslogHost = "Syslog Host";
L7_char8 *pStrInfo_base_SysReset = "System Reset";
L7_char8 *pStrInfo_base_SysUsageThresh = "System Usage Threshold";
L7_char8 *pStrInfo_base_TftpFileName = "Transfer File Name";
L7_char8 *pStrInfo_base_TftpFilePath = "Transfer File Path";
L7_char8 *pStrInfo_base_TftpSrvrAddrType = "Server Address Type";
L7_char8 *pStrInfo_base_TftpSrvrHostAddr = "Server Host Address";
L7_char8 *pStrInfo_base_TelnetLoginTimeout = "Telnet Login Timeout";
L7_char8 *pStrInfo_base_TelnetSessionCfg = "Telnet Session Configuration";
L7_char8 *pStrInfo_base_Test = "Test";
L7_char8 *pStrInfo_base_TestCable = "Test Cable";
L7_char8 *pStrInfo_base_AuthLoginListForAdminUsrCantBeChgd = "The Authentication Login List for the admin user can not be changed.";
L7_char8 *pStrInfo_base_IpAddrAndSubnetMaskCombinationIsNotValid = "The IP Address and subnet mask combination is not valid.";
L7_char8 *pStrInfo_base_PasswdsForSysHaveBeenResetToFactoryDefls = "The Passwords for the system have been reset to the factory defaults.";
L7_char8 *pStrInfo_base_DeflAuthLoginListCantBeChgd = "The default Authentication Login List can not be changed.";
L7_char8 *pStrInfo_base_FirstMethodInAuthLoginListMustBeDefined = "The first method in the Authentication Login List must be defined.";
L7_char8 *pStrInfo_base_FileIsNotIntendedForProduct = "This file is not intended for this product!";
L7_char8 *pStrInfo_base_NameIsAlreadyInUse = "This name is already in use";
L7_char8 *pStrInfo_base_To_4 = "To";
L7_char8 *pStrInfo_base_Traceroute = "TraceRoute";
L7_char8 *pStrInfo_base_TracerouteFailed = "TraceRoute Failed";
L7_char8 *pStrInfo_base_TxQueueLenPkts = "Transmit Queue Length (Packets)";
L7_char8 *pStrInfo_base_Trap_1 = "Trap";
L7_char8 *pStrInfo_base_TrapFlagsCfg = "Trap Flags Configuration";
L7_char8 *pStrInfo_base_TrapLog_1 = "Trap Log";
L7_char8 *pStrInfo_base_TxRxMinMaxAvgRttMsec = "Tx = %d, Rx = %d Min/Max/Avg RTT = %d/%d/%d msec";
L7_char8 *pStrInfo_base_TxFcsErrs = "Tx FCS Errors";
L7_char8 *pStrInfo_base_TxAndRx = "Tx and Rx";
L7_char8 *pStrInfo_base_UcastStormLvl = "Ucast Storm Level";
L7_char8 *pStrInfo_base_UcastStormMode = "Ucast Storm Mode";
L7_char8 *pStrInfo_base_UnableToRetrievePasswd = "Unable to retrieve password.";
L7_char8 *pStrInfo_base_Unallocated = "Unallocated";
L7_char8 *pStrInfo_base_UndersizeRcvd = "Undersize Received";
L7_char8 *pStrInfo_base_UcastPollIntvl = "Unicast Poll Interval";
L7_char8 *pStrInfo_base_UcastPollRetry = "Unicast Poll Retry";
L7_char8 *pStrInfo_base_UcastPollTimeout = "Unicast Poll Timeout";
L7_char8 *pStrInfo_base_UcastStormRecoveryLvl = "Unicast Storm Recovery Level";
L7_char8 *pStrInfo_base_UcastStormRecoveryMode = "Unicast Storm Recovery Mode";
L7_char8 *pStrInfo_base_UploadFileFromSwitch = "Upload File from Switch";
L7_char8 *pStrInfo_base_Usr_1 = "User";
L7_char8 *pStrInfo_base_UsrAccounts = "User Accounts";
L7_char8 *pStrInfo_base_UsrLoginCfg = "User Login Configuration";
L7_char8 *pStrInfo_base_UsrSPasswdMustBeCharsInLenBeforeEncryptionCanBeEnbldForThatUsr = "User's password must be %u characters in length before encryption can be\r\nenabled for that user.";
L7_char8 *pStrInfo_base_Vrrp = "VRRP";
L7_char8 *pStrErr_base_OutOfRangeDsbl = "Value (%d) is out of range for %s. The valid range is %d to %d or %d to disable.";
L7_char8 *pStrInfo_base_VerRunningOnSrvr = "Version running on Server";
L7_char8 *pStrInfo_base_WebAppletCustomizatonFeat = "WEB_APPLET_CUSTOMIZATON_FEATURE";
L7_char8 *pStrInfo_base_Ws_1 = "WIRELESS";
L7_char8 *pStrInfo_base_dhcp_snooping = "DHCP_SNOOPING";
L7_char8 *pStrInfo_base_ip_source_guard = "IPSG";
L7_char8 *pStrInfo_base_dot3ah = "DOT3AH";
L7_char8 *pStrInfo_base_DhcpFiltering = "DHCP_FILTERING";
L7_char8 *pStrInfo_base_Watchdog = "Watchdog";
L7_char8 *pStrInfo_base_WebMode = "Web Mode";
L7_char8 *pStrInfo_base_YouHaveMadeCfgsToSwitchWithoutSavingmWouldYouLikeToSaveChgsBeforeYouResetSys = "You have made configurations to the switch without saving them.  Would you like to save these changes before you reset the system?";
L7_char8 *pStrInfo_base_YouMustSelectADstPort = "You must select a destination port.";
L7_char8 *pStrInfo_base_YouMustSelectAtleastOneSrcPort = "You must select atleast one source port";
L7_char8 *pStrInfo_base_AbNewArrayAll = "ab = new Array(\"all\"";
L7_char8 *pStrInfo_base_HtmlFileAddSrcPorts = "add_source_ports.html";
L7_char8 *pStrInfo_base_And = "and";
L7_char8 *pStrInfo_base_HtmlFileAplCfg = "apl_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileAplSessions = "apl_sessions.html";
L7_char8 *pStrInfo_base_HtmlFileAplSumm = "apl_summ.html";
L7_char8 *pStrInfo_base_HtmlFileArpCache = "arp_cache.html";
L7_char8 *pStrInfo_base_AutoNegotiationAdminStatus = "auto-negotiation admin status";
L7_char8 *pStrInfo_base_BNodeBcast = "b-node Broadcast";
L7_char8 *pStrInfo_base_HtmlFileCardCfg = "card_config.html";
L7_char8 *pStrInfo_base_Case = "case \'%d\':";
L7_char8 *pStrInfo_base_HtmlFileCfrmResetCfg = "cfrm_reset_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileCmdLoggerCfg = "cmd_logger_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileConfirmReset = "confirm_reset.html";
L7_char8 *pStrInfo_base_HtmlFileConsoleCfg = "console_cfg.html";
L7_char8 *pStrInfo_base_Days_2 = "days";
L7_char8 *pStrInfo_base_DeflAbNewArrayErrorBreak = "default:\n ab = new Array( \"Error\" )";
L7_char8 *pStrInfo_base_HtmlFileDhcpBindingsInfo = "dhcp_bindings_info.html";
L7_char8 *pStrInfo_base_HtmlFileDhcpConflictsInfo = "dhcp_conflicts_info.html";
L7_char8 *pStrInfo_base_HtmlFileDhcpGlobalCfg = "dhcp_global_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileDhcpPoolCfg = "dhcp_pool_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileDhcpPoolCfgRo = "dhcp_pool_cfg_ro.html";
L7_char8 *pStrInfo_base_HtmlFileDhcpPoolOptions = "dhcp_pool_options.html";
L7_char8 *pStrInfo_base_HtmlFileDhcpResetCfg = "dhcp_reset_cfg.html";
L7_char8 *pStrInfo_base_sFlow = "SFLOW";
L7_char8 *pStrInfo_base_HtmlFilesFlowAgentSummary = "sFlow_Agent_Summary.html";
L7_char8 *pStrInfo_base_HtmlFileDhcpSrvrInfo = "dhcp_server_info.html";
L7_char8 *pStrInfo_base_HtmlFileDosCfg = "dos_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileDoubleVlanTag = "double_vlan_tag.html";
L7_char8 *pStrInfo_base_HtmlFileDoubleVlanTagSumm = "double_vlan_tag_summ.html";
L7_char8 *pStrInfo_base_HtmlFileVlanInfo = "vlan_info.html";
L7_char8 *pStrInfo_base_HtmlFileDualImageCfg = "dual_image_cfg.html";
L7_char8 *pStrInfo_base_EnblAuthPasswdIsShorterThanChars = "enable authentication, password is shorter than %u characters.";
L7_char8 *pStrInfo_base_EnblEncryptionPasswdIsLessThanChars = "enable encryption, password is less than %u characters.";
L7_char8 *pStrInfo_base_HtmlFileEventLog = "event_log.html";
L7_char8 *pStrInfo_base_HtmlFileFileDownload = "file_download.html";
L7_char8 *pStrInfo_base_HtmlFileFileUpload = "file_upload.html";
L7_char8 *pStrInfo_base_HtmlFileFwdDbCfg = "fwd_db_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileFwdDbSearch = "fwd_db_search.html";
L7_char8 *pStrInfo_base_HNodeHybrid = "h-node Hybrid";
L7_char8 *pStrInfo_base_HtmlFileHostsCfg = "hosts_cfg.html";
L7_char8 *pStrInfo_base_HtmlLinkBaseDhcpHelpDhcpDhcpBindingsInfo = "href=\"/base/dhcp/help_dhcp.html#dhcp_bindings_info\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseDhcpHelpDhcpDhcpConflictsInfo = "href=\"/base/dhcp/help_dhcp.html#dhcp_conflicts_info\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseDhcpHelpDhcpDhcpGlobalCfg = "href=\"/base/dhcp/help_dhcp.html#dhcp_global_cfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseDhcpHelpDhcpDhcpPoolCfg = "href=\"/base/dhcp/help_dhcp.html#dhcp_pool_cfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseDhcpHelpDhcpDhcpPoolOptions = "href=\"/base/dhcp/help_dhcp.html#dhcp_pool_options\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseDhcpHelpDhcpDhcpResetCfg = "href=\"/base/dhcp/help_dhcp.html#dhcp_reset_cfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseDhcpHelpDhcpDhcpSrvrInfo = "href=\"/base/dhcp/help_dhcp.html#dhcp_server_info\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSntpHelpSntpSntpGlobalCfg = "href=\"/base/sntp/help_sntp.html#sntp_global_cfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSntpHelpSntpSntpGlobalStatus = "href=\"/base/sntp/help_sntp.html#sntp_global_status\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSntpHelpSntpSntpSrvrCfg = "href=\"/base/sntp/help_sntp.html#sntp_server_cfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSntpHelpSntpSntpSrvrStatus = "href=\"/base/sntp/help_sntp.html#sntp_server_status\"";
L7_char8 *pStrInfo_base_HtmlFileBaseSysHelpCableTest = "href=\"/base/system/help_cable_test.html\"";
L7_char8 *pStrInfo_base_HtmlFileBaseSysHelpDosCfg = "href=\"/base/system/help_dos_cfg.html\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpsFlowAgent = "href=\"/base/sflow/help_sFlow.html#sFlowAgent\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpsFlowRcvr = "href=\"/base/sflow/help_sFlow.html#sFlowRcvr\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpsFlowPoller = "href=\"/base/sflow/help_sFlow.html#sFlowPoller\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpsFlowSampler = "href=\"/base/sflow/help_sFlow.html#sFlowSampler\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgNetcon = "href=\"/base/system/help_switch_cfg.html#netcon\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgNetndpsumm = "href=\"/base/system/help_switch_cfg.html#netndpsumm\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgPing = "href=\"/base/system/help_switch_cfg.html#ping\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgRescfg = "href=\"/base/system/help_switch_cfg.html#rescfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgSavechange = "href=\"/base/system/help_switch_cfg.html#savechange\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgSerport = "href=\"/base/system/help_switch_cfg.html#serport\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgServndpsumm = "href=\"/base/system/help_switch_cfg.html#servndpsumm\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgService = "href=\"/base/system/help_switch_cfg.html#service\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgSwcfg = "href=\"/base/system/help_switch_cfg.html#swcfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgSysrest = "href=\"/base/system/help_switch_cfg.html#sysrest\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgTelnetcCfg = "href=\"/base/system/help_switch_cfg.html#telnetc_cfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgTelnetcfg = "href=\"/base/system/help_switch_cfg.html#telnetcfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSwitchCfgTraceroute = "href=\"/base/system/help_switch_cfg.html#traceroute\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSysinfoArpcache = "href=\"/base/system/help_sysinfo.html#arpcache\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSysinfoEventlog = "href=\"/base/system/help_sysinfo.html#eventlog\"";
L7_char8 *pStrInfo_base_HtmlLinkXuiBaseSysHelpSysinfoEventlog = "href=\"/help_EventLog.html\"";
L7_char8 *pStrInfo_base_HtmlLinkXuiBaseSysHelpSysinfoFDBSearch = "href=\"/help_FDBSearch.html\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSysinfoInvinfo = "href=\"/base/system/help_sysinfo.html#invinfo\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSysinfoMacaddr = "href=\"/base/system/help_sysinfo.html#macaddr\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSysinfoMacaddrcfg = "href=\"/base/system/help_sysinfo.html#macaddrcfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpSysinfoSysdesc = "href=\"/base/system/help_sysinfo.html#sysdesc\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpTransferDownload = "href=\"/base/system/help_transfer.html#download\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpTransferImagecfg = "href=\"/base/system/help_transfer.html#imagecfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpTransferImagestatus = "href=\"/base/system/help_transfer.html#imagestatus\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpTransferUpload = "href=\"/base/system/help_transfer.html#upload\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpUsrsRespass = "href=\"/base/system/help_users.html#respass\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpUsrsUsracct = "href=\"/base/system/help_users.html#useracct\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysHelpHttpConfiguration = "href=\"/base/system/help_http.html\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysUsrMgrHelpPasswordManagement = "href=\"/base/system/user_mgr/help_usermgr.html#passmgmt\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysLogHelpSyslogCfgCmdLogger = "href=\"/base/system/log/help_syslog_cfg.html#cmd_logger\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysLogHelpSyslogCfgConsole = "href=\"/base/system/log/help_syslog_cfg.html#console\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysLogHelpSyslogCfgHosts = "href=\"/base/system/log/help_syslog_cfg.html#hosts\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysLogHelpSyslogCfgInmem = "href=\"/base/system/log/help_syslog_cfg.html#inmem\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysLogHelpSyslogCfgMsgs1 = "href=\"/base/system/log/help_syslog_cfg.html#messages1\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysLogHelpSyslogCfgMsgs = "href=\"/base/system/log/help_syslog_cfg.html#messages\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysLogHelpSyslogCfgPers = "href=\"/base/system/log/help_syslog_cfg.html#pers\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysLogHelpSyslogCfgSyslogCfg = "href=\"/base/system/log/help_syslog_cfg.html#syslog_cfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysPortHelpDvlanDvlanTag = "href=\"/base/doublevlantag/help_dvlan.html#dvlan_tag\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysPortHelpDvlanDvlanTagSumm = "href=\"/base/doublevlantag/help_dvlan.html#dvlan_tag_summ\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysPortHelpPortcfgAddSrcPort = "href=\"/base/system/port/help_portcfg.html#add_src_port\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysPortHelpPortcfgNpcfg = "href=\"/base/system/port/help_portcfg.html#npcfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysPortHelpPortcfgPortdes = "href=\"/base/system/port/help_portcfg.html#portdes\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysPortHelpPortcfgPortmon = "href=\"/base/system/port/help_portcfg.html#portmon\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysPortHelpPortcfgPortstat = "href=\"/base/system/port/help_portcfg.html#portstat\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysPortHelpPortcfgRmvSrcPort = "href=\"/base/system/port/help_portcfg.html#rmv_src_port\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysSlotHelpSlotCardcfg = "href=\"/base/system/slot/help_slot.html#cardcfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysSlotHelpSlotSlotsumm = "href=\"/base/system/slot/help_slot.html#slotsumm\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysSlotHelpSlotSuppcard = "href=\"/base/system/slot/help_slot.html#suppcard\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysSnmpHelpSnmpMibsupport = "href=\"/base/system/snmp/help_snmp.html#mibsupport\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysSnmpHelpSnmpSnmpcomm = "href=\"/base/system/snmp/help_snmp.html#snmpcomm\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysSnmpHelpSnmpTraprcvr = "href=\"/base/system/snmp/help_snmp.html#traprcvr\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysStatsHelpStatsPortdetstat = "href=\"/base/system/stats/help_stats.html#portdetstat\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysStatsHelpStatsPortsumstat = "href=\"/base/system/stats/help_stats.html#portsumstat\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysStatsHelpStatsSwstat = "href=\"/base/system/stats/help_stats.html#swstat\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysStatsHelpStatsSwsumstat = "href=\"/base/system/stats/help_stats.html#swsumstat\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysTrapmgrHelpTrapsTrapflag = "href=\"/base/system/trapmgr/help_traps.html#trapflag\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysTrapmgrHelpTrapsTraplog = "href=\"/base/system/trapmgr/help_traps.html#traplog\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysUsrMgrHelpUsrmgrLogincfg = "href=\"/base/system/user_mgr/help_usermgr.html#logincfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysUsrMgrHelpUsrmgrLoginsessions = "href=\"/base/system/user_mgr/help_usermgr.html#loginsessions\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysUsrMgrHelpUsrmgrUsrlogincfg = "href=\"/base/system/user_mgr/help_usermgr.html#userlogincfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysUsrMgrHelpUsrmgrUsrloginsumm = "href=\"/base/system/user_mgr/help_usermgr.html#userloginsumm\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseDnsClientHelpGblCfg = "href=\"/base/dns/help_dns_client.html#dnsgblcfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseDnsClientHelpSrvCfg = "href=\"/base/dns/help_dns_client.html#dnsservcfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseDnsClientHelpHostIpCfg = "href=\"/base/dns/help_dns_client.html#dnshostipcfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseDnsClientHelpDlCfg = "href=\"/base/dns/help_dns_client.html#dnsdlcreatecfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseDnsClientHelpHostIpSum = "href=\"/base/dns/help_dns_client.html#dnshostipsummary\"";
L7_char8 *pStrInfo_base_HtmlLinkBasePoeCfg = "href=\"/base/poe/help_poe.html#poecfg\"";
L7_char8 *pStrInfo_base_HtmlLinkBasePoeStatus = "href=\"/base/poe/help_poe.html#poestatus\"";
L7_char8 *pStrInfo_base_HttpHardTimeout_1 = "http Hard Timeout";
L7_char8 *pStrInfo_base_HttpSoftTimeout_1 = "http Soft Timeout";
L7_char8 *pStrInfo_base_HtmlFileHttpCfg = "http_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileHwInfo = "hw_info.html";
L7_char8 *pStrInfo_base_HtmlFileImageStatus = "image_status.html";
L7_char8 *pStrInfo_base_HtmlFileInmemoryCfg = "inmemory_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileInmemoryLog = "inmemory_log.html";
L7_char8 *pStrInfo_base_HtmlFileLicenseAdvance = "license_advance.html";
L7_char8 *pStrInfo_base_MNodeMixed = "m-node Mixed";
L7_char8 *pStrInfo_base_MethodsInAuthLoginList = "methods in the Authentication Login List.";
L7_char8 *pStrInfo_base_Mins = "mins";
L7_char8 *pStrInfo_base_HtmlFileMultiplePortMirror = "multiple_port_mirror.html";
L7_char8 *pStrInfo_base_HtmlFileNetConnCfg = "net_conn_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileNdpSumm = "ndp_summ.html";
L7_char8 *pStrInfo_base_PNodePeerToPeer = "p-node Peer-to-Peer";
L7_char8 *pStrInfo_base_PasConpass = "pas_conpass";
L7_char8 *pStrInfo_base_PasEnalog = "pas_enalog";
L7_char8 *pStrInfo_base_PasEnapass = "pas_enapass";
L7_char8 *pStrInfo_base_PasMinpass = "pas_minpass";
L7_char8 *pStrInfo_base_HtmlFilePassMgmt = "pass_mgmt.html";
L7_char8 *pStrInfo_base_HtmlFilePersistentCfg = "persistent_cfg.html";
L7_char8 *pStrInfo_base_HtmlFilePersistentLog = "persistent_log.html";
L7_char8 *pStrInfo_base_HtmlFilePing = "ping.html";
L7_char8 *pStrInfo_base_HtmlFilePoeCfgRo = "poe_cfg_ro.html";
L7_char8 *pStrInfo_base_HtmlFilePoeCfgRw = "poe_cfg_rw.html";
L7_char8 *pStrInfo_base_HtmlFilePoeStatus = "poe_status.html";
L7_char8 *pStrInfo_base_HtmlFilePortCfg = "port_cfg.html";
L7_char8 *pStrInfo_base_HtmlFilePortCfgRo = "port_cfg_ro.html";
L7_char8 *pStrInfo_base_HtmlFilePortDesRo = "port_des_ro.html";
L7_char8 *pStrInfo_base_HtmlFileRemoveSrcPorts = "remove_source_ports.html";
L7_char8 *pStrInfo_base_HtmlFileResetPwds = "reset_pwds.html";
L7_char8 *pStrInfo_base_HtmlFileSaveChgs = "save_changes.html";
L7_char8 *pStrInfo_base_HtmlFileSaveCheck = "save_check.html";
L7_char8 *pStrInfo_base_SecondsForFdbId = "seconds for FDB ID";
L7_char8 *pStrInfo_base_HtmlFileSerialCfg = "serial_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileServPortCfg = "serv_port_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileServNdpSumm = "serv_ndp_summ.html";
L7_char8 *pStrInfo_base_SettingAuthLoginListForUsr = "setting Authentication Login List for this user.";
L7_char8 *pStrInfo_base_HtmlFileSlotSummary = "slot_summary.html";
L7_char8 *pStrInfo_base_HtmlFileSnmpCommCfgRw = "snmp_comm_cfg_rw.html";
L7_char8 *pStrInfo_base_HtmlFileSnmpMibSupport = "snmp_mib_support.html";
L7_char8 *pStrInfo_base_HtmlFileSntpGlobalCfg = "sntp_global_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileSntpSrvrCfg = "sntp_server_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileSntpSrvrCfgRo = "sntp_server_cfg_ro.html";
L7_char8 *pStrInfo_base_HtmlFileSntpSrvrStatus = "sntp_server_status.html";
L7_char8 *pStrInfo_base_SpecifiedAddrConflict = "specified Address Conflict";
L7_char8 *pStrInfo_base_SpecifiedDynBinding = "specified Dynamic Binding";
L7_char8 *pStrInfo_base_HtmlFileStatsPort = "stats_port.html";
L7_char8 *pStrInfo_base_HtmlFileStatsPortSumm = "stats_port_summ.html";
L7_char8 *pStrInfo_base_HtmlFileStatsSwitch = "stats_switch.html";
L7_char8 *pStrInfo_base_HtmlFileStatsSwitchSumm = "stats_switch_summ.html";
L7_char8 *pStrInfo_base_HtmlFileSuppCard = "supp_card.html";
L7_char8 *pStrInfo_base_HtmlFileSwitchCfg = "switch_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileSysDescr = "sys_descr.html";
L7_char8 *pStrInfo_base_HtmlFileSysReset = "sys_reset.html";
L7_char8 *pStrInfo_base_HtmlFileSyslogCfg = "syslog_cfg.html";
L7_char8 *pStrInfo_base_Tacacs_1 = "tacacs+";
L7_char8 *pStrInfo_base_HtmlFileTelnetCfg = "telnet_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileTelnetcCfg = "telnetc_cfg.html";
L7_char8 *pStrInfo_base_SnmpCommunityName_1 = "the SNMP Community Name";
L7_char8 *pStrInfo_base_PhyModeForLagMbrsChangingSpeedOfLagMbrsRequiresRemovalFromLag = "the physical mode for Port Channel members.\r\nChanging the speed of Port Channel members requires removal from the Port Channel";
L7_char8 *pStrInfo_base_HtmlFileTraceroute = "traceroute.html";
L7_char8 *pStrInfo_base_HtmlFileTrapFlagsCfg = "trap_flags_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileTrapLog = "trap_log.html";
L7_char8 *pStrInfo_base_HtmlFileTrapRecvrCfg = "trap_recvr_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileUsrAccounts = "user_accounts.html";
L7_char8 *pStrInfo_base_HtmlFileUsrAplCfg = "user_apl_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileVirtualCableTest = "virtual_cable_test.html";
L7_char8 *pStrInfo_base_HtmlFileSntpGlobalStatus = "sntp_global_status.html";
L7_char8 *pStrInfo_base_PoeStatus = "PoE Status";
L7_char8 *pStrInfo_base_power_limit = "Power Limit";
L7_char8 *pStrInfo_base_MaxSysPower = "Max System Power Available";
L7_char8 *pStrInfo_base_CurrSysPower = "Current System Power Used";

L7_char8 *pStrInfo_base_dnsglobalcfg = "DNS Global Configuration";
L7_char8 *pStrInfo_base_dnsservercfg = "DNS Server Configuration";
L7_char8 *pStrInfo_base_dnshostnameipmapcfg = "DNS HostName IP Mapping Configuration";
L7_char8 *pStrInfo_base_dnshostnameipmapsummary = "DNS HostName IP Mapping Summary";
L7_char8 *pStrInfo_base_dnsdomainlistcfg = "DNS Domain List Configuration";
L7_char8 *pStrInfo_base_DnsDomainName = "Defalut Domain Name";
L7_char8 *pStrInfo_base_DnsRetryNumber = "Retry Number";
L7_char8 *pStrInfo_base_DnsResponseTimeout = "Response Timeout";
L7_char8 *pStrInfo_base_DnsDomainList = "Default Domain List";
L7_char8 *pStrInfo_base_DnsServerAddress = "DNS Server Address";
L7_char8 *pStrInfo_base_HtmlDnsGlobalDlCreate = "dns_global_dl_create_rw.html";
L7_char8 *pStrInfo_base_HtmlDnsGlobalCfg = "dns_global_cfg_rw.html";
L7_char8 *pStrInfo_base_HtmlDnsServerCfg = "dns_server_cfg_rw.html";
L7_char8 *pStrInfo_base_DnsServerList = "DNS Server List";
L7_char8 *pStrInfo_base_DnsHostName_1 = "Host Name";
L7_char8 *pStrInfo_base_SubString="Error! Each substring must be less than 64 characters in length,separated by a dot ";
L7_char8 *pStrInfo_base_SubString_1="\r\n       and length of the whole string must not exceed 255 characters";
L7_char8 *pStrInfo_base_DnsIPAddr = "IP Address";
L7_char8 *pStrInfo_base_HtmlDnsHostCfg = "dns_host_cfg_rw.html";
L7_char8 *pStrInfo_base_HtmlDnsHostSummary = "dns_host_summary_rw.html";
L7_char8 *pStrInfo_base_DnsDomainName_1 = "Domain Name";
L7_char8 *pStrInfo_base_HtmlDnsGlobalDlCfg = "dns_global_dl_create_rw.html";
L7_char8 *pStrInfo_base_HttpFileDownload = "HTTP File Download";
L7_char8 *pStrInfo_base_HttpFileDownloadHelp = "href=\"/base/system/help_http_file_download.html\"";
L7_char8 *pStrInfo_base_httpDownloadFeature = "HTTP_FILE_DOWNLOAD";
L7_char8 *pStrInfo_base_WebAutoInstallLink = "autoinstall.html";
L7_char8 *pStrInfo_base_WebAutoInstall = "AutoInstall";
L7_char8 *pStrInfo_base_WebAutoInstallMode = "AutoInstall Mode";
L7_char8 *pStrInfo_base_WebAutoInstallAutoSaveMode = "AutoSave Mode";
L7_char8 *pStrInfo_base_WebAutoInstallRetryCount = "Retry Count";
L7_char8 *pStrInfo_base_WebAutoInstallState = "AutoInstall State";
L7_char8 *pStrInfo_base_WebAutoInstallAutoSaveState = "AutoSave State";
L7_char8 *pStrInfo_base_WebAutoInstallRetryInfiniteState = "Retry Infinite State";
L7_char8 *pStrInfo_base_WebAutoInstallErase = "Erase Startup-config File";
L7_char8 *pStrInfo_base_WebAutoInstallStart = "Start";
L7_char8 *pStrInfo_base_WebAutoInstallStop =  "Stop";
L7_char8 *pStrErr_base_WebAutoInstallMode =  " AutoInstall Mode.";
L7_char8 *pStrErr_base_WebAutoInstallSaveMode =  " AutoSave Mode.";
L7_char8 *pStrInfo_base_AutoInstallFeature = "WEB_AUTOINSTALL_FEATURE";
L7_char8 *pStrInfo_base_HttpAutoInstallHelp = "href=\"/base/auto_install/help_autoinstall.html#cfg\"";
L7_char8 *pStrInfo_base_HttpEraseStartupConfigScript = "Exercising this function will erase startup-config file.";
L7_char8 *pStrInfo_base_HttpErase = "Erase";
L7_char8 *pStrInfo_base_HttpErasehelp = "href=\"/base/system/help_switch_cfg.html#erase_startup_config\"";
L7_char8 *pStrInfo_base_WebEraseStartupConfigLink = "erase_startup_config.html";
L7_char8 *pStrInfo_base_WebEraseStartupConfigFail = "Erase startup-config file failed.";
L7_char8 *pStrInfo_base_DhcpVendorClassIdOptions = "DHCP Client Options";
L7_char8 *pStrInfo_base_DhcpVendorClassIdMode = "DHCP Vendor Class Id Mode";
L7_char8 *pStrInfo_base_DhcpVendorClassIdStr = "DHCP Vendor Class Id String";
L7_char8 *pStrInfo_base_HtmlFileDhcpOptionsCfg = "net_conn_dhcp_options.html";
/* ISDP */
L7_char8 *pStrInfo_base_IsdpMode = "ISDP Mode";
L7_char8 *pStrInfo_base_IsdpV2Mode = "ISDP V2 Mode";
L7_char8 *pStrInfo_base_IsdpMessageInterval = "Message Interval(secs)";
L7_char8 *pStrInfo_base_IsdpHoldtimeInterval = "Hold Time Interval(secs)";
L7_char8 *pStrInfo_base_HtmlFileIsdpCfg = "isdp_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileIsdpStat = "isdp_stat.html";
L7_char8 *pStrInfo_base_HtmlFileIsdpIntfCfg = "isdp_intf_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileIsdpCache = "isdp_cache.html";
L7_char8 *pStrInfo_base_IsdpCounters = "ISDP Counters.";
L7_char8 *pStrInfo_base_IsdpNeighborTable = "ISDP Neighbors Table.";
L7_char8 *pStrInfo_base_IsdpGlobConfHeader = "ISDP Global Configuration";
L7_char8 *pStrInfo_base_IsdpStatsHeader= "ISDP Statistics";
L7_char8 *pStrInfo_base_IsdpIntfHeader = "ISDP Interface Configuration";
L7_char8 *pStrInfo_base_IsdpCacheHeader = "ISDP Cache Table";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysIsdpCache = "href=\"/base/isdp/help_isdp.html#isdp_cache\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysIsdpIntf = "href=\"/base/isdp/help_isdp.html#isdp_intf\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysIsdpStat = "href=\"/base/isdp/help_isdp.html#isdp_stat\"";
L7_char8 *pStrInfo_base_HtmlLinkBaseSysIsdpGlobalConf = "href=\"/base/isdp/help_isdp.html#isdp_global_cfg\"";
L7_char8 *pStrInfo_base_HtmlDhcpVendorClassIdOptions = "href=\"/base/system/help_switch_cfg.html#dhcpclientOptionscfg\"";
L7_char8 *pStrInfo_base_IsdpDevIdTitle = "Device ID";
L7_char8 *pStrInfo_base_IsdpDevIdFormatCpbTitle = "Device ID Format Capability";
L7_char8 *pStrInfo_base_IsdpDevIdFormatTitle = "Device ID Format";
L7_char8 *pStrInfo_base_StatIsdpPduRx = "Packets Received";
L7_char8 *pStrInfo_base_StatIsdpPduTx = "Packets Transmitted";
L7_char8 *pStrInfo_base_StatIsdpV1PduRx = "ISDPv1 Packets Received";
L7_char8 *pStrInfo_base_StatIsdpV1PduTx = "ISDPv1 Packets Transmitted";
L7_char8 *pStrInfo_base_StatIsdpV2PduRx = "ISDPv2 Packets Received";
L7_char8 *pStrInfo_base_StatIsdpV2PduTx = "ISDPv2 Packets Transmitted";
L7_char8 *pStrInfo_base_StatIsdpBadHeader = "Bad Header";
L7_char8 *pStrInfo_base_StatIsdpChecksumErr = "Checksum Error";
L7_char8 *pStrInfo_base_StatIsdpTransmissionFailure = "Transmission Failure";
L7_char8 *pStrInfo_base_StatIsdpInvalidPduFormat = "Invalid Format Packets Received";
L7_char8 *pStrInfo_base_StatIsdpIPAddressTableFull = "ISDP IP Address Table Full";
L7_char8 *pStrInfo_base_StatIsdpTableFull = "Table Full";
L7_char8 *pStrInfo_base_IsdpHoldtimeTitle = "Holdtime (secs)";
L7_char8 *pStrInfo_base_IsdpCpbTitle = "Capability";
L7_char8 *pStrInfo_base_IsdpPlatformTitle = "Platform";
L7_char8 *pStrInfo_base_IsdpPortIdTitle = "Port ID";
L7_char8 *pStrInfo_base_IsdpTitleHlp = "Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge, S - Switch, H - Host, I - IGMP, r - Repeater";
L7_char8 *pStrInfo_base_IsdpIpAddrTitle = "IP Address";
L7_char8 *pStrInfo_base_IsdpVersionTitle = "Version";
L7_char8 *pStrInfo_base_IsdpLastTimeChanged = "Last Time Changed";
L7_char8 *pStrInfo_base_IsdpProtVer = "Protocol Version";
L7_char8 *pStrInfo_base_ISDP = "ISDP";
L7_char8 *pStrInfo_base_Dot1adComponent = "DOT1AD";




L7_char8 *pStrInfo_base_tr069 = "TR069";
L7_uchar8 *pStrInfo_base_TR069Configuration = " TR-069 Configuration";
L7_uchar8 *pStrInfo_base_TR069AcsUrl = " ACS URL";
L7_uchar8 *pStrInfo_base_TR069AcsUser = " ACS User";
L7_uchar8 *pStrInfo_base_TR069AcsUserPasswd = " ACS User Password";
L7_uchar8 *pStrInfo_base_TR069AcsUserPasswdConfirm = " Confirm ACS User Password";
L7_uchar8 *pStrInfo_base_TR069AcsPeriodicInformMode = " Periodic Inform Mode";
L7_uchar8 *pStrInfo_base_TR069AcsPeriodicInformInterval = " Periodic Inform Interval";
L7_uchar8 *pStrInfo_base_TR069AcsPeriodicInformTime = " Periodic Inform Time";
L7_uchar8 *pStrInfo_base_TR069AcsUpgradesManaged = " ACS Upgrades Managed";
L7_uchar8 *pStrInfo_base_TR069AcsConnectionRequestUser = " Connection Request User";
L7_uchar8 *pStrInfo_base_TR069AcsConnReqUserPasswd = " Connection request User Password";
L7_uchar8 *pStrInfo_base_TR069AcsConnReqUserPasswdConfirm = " Confirm Connection request User Password";
L7_uchar8 *pStrInfo_base_TR069AcsConnectionRequestUrl= " Connection Request URL";
L7_uchar8 *pStrInfo_base_TR069AcsParameterKey = " Parameter Key";

L7_char8 *pStrInfo_base_HtmlFileTr069Cfg = "tr069_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileTr069Stats = "tr069_stats.html";
L7_char8 *pStrInfo_base_HtmlFileTr069Rpc = "tr069_rpc.html";
L7_char8 *pStrInfo_base_TR069Statistics = " TR-069 Statistics";
L7_char8 *pStrInfo_base_TR069RpcMethods = " TR-069 RPC Methods";

L7_char8 *pStrInfo_base_TR069StatsInformMsgsSent = " Total Inform Messages Sent";
L7_char8 *pStrInfo_base_TR069StatsConnReqRxed = "Total Connection Request Received";
L7_char8 *pStrInfo_base_TR069StatsTotalFaults ="Total Faults";
L7_char8 *pStrInfo_base_TR069StatsMethoNotSuppFaults = "Method Not-Supported Faults";
L7_char8 *pStrInfo_base_TR069StatsReqDeniedFaults ="Request Denied Faults";
L7_char8 *pStrInfo_base_TR069StatsInternalErrors = "Internal Errors";
L7_char8 *pStrInfo_base_TR069StatsInvalidArgFaults = "Invalid Argument Faults";
L7_char8 *pStrInfo_base_TR069StatsResrcsExceededFaults = "Resources Exceeded Faults";
L7_char8 *pStrInfo_base_TR069StatsInvalidParamNameFaults = "Invalid Parameter Name Faults";
L7_char8 *pStrInfo_base_TR069StatsInvalidParamTypeFaults = "Invalid Parameter Type Faults";
L7_char8 *pStrInfo_base_TR069StatsInvalidParamValueFaults = "Invalid Parameter Value Faults";
L7_char8 *pStrInfo_base_TR069StatsInvalidWriteAttemptFaults = "Invalid Write Attempt Faults";
L7_char8 *pStrInfo_base_TR069StatsNotificationReqRejections = "Notification Request Rejections";
L7_char8 *pStrInfo_base_TR069StatsDnloadFailures = "Download Failures";
L7_char8 *pStrInfo_base_TR069StatsUploadFailures = "Upload Failures";
L7_char8 *pStrInfo_base_TR069StatsFileTransferServerAuthFailures = "File Transfer Server Authentication Failures";
L7_char8 *pStrInfo_base_TR069StatsVendorDefaultFaults = "Vendor Default Faults";
L7_char8 *pStrInfo_base_TR069AcsRpcMethods = "ACS RPC Methods";
L7_char8 *pStrErr_base_Tr069ParamsAcsGetRpcMethodsFail = "trigger TR-069 CPE to get RPC methods from ACS.";

