#
# $Id: Makefile Exp $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/ctest/dnx/kbp

include ${SDK}/make/Make.config

lib = libctest_dnxkbp

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend


