#
# $Id: Makefile Exp $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/ctest/dnx/kaps/verifier

include ${SDK}/make/Make.config
INCDIR += -I${SDK}/src/appl/ctest/dnx/kaps/
INCDIR += -I${SDK}/libs/kaps/include
INCDIR += -I${SDK}/libs/kaps
INCDIR += -I${SDK}/include
INCDIR += -I${SDK}/include/shared

lib = libctest_dnxkaps_verifier

include ${SDK}/make/Make.subdirs
include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
