# $Id: Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2018 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
LOCALDIR = src/soc/dnx/legacy/SAND/Management

include ${SDK}/make/Make.config

lib = libsoc_dnxlegacysandmanagement

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
