#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/ctest/dnx/trap

include ${SDK}/make/Make.config

lib = libctest_dnxtrap

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

