#!/usr/bin/expect
   set timeout 20 
   set arg0  [lindex $argv 0] 
   set arg1  [lindex $argv 1] 
   set arg2  [lindex $argv 2]
   set arg3  [lindex $argv 3]
   set arg4  [lindex $argv 4]
   set Username "root" 
   set Password "lampada"
   
   #se houver só 3 argumentos, ftp para o 1º, o ficheiro é o segundo, o path 0 terceiro
   if {$arg3 == ""} {
   spawn ftp $arg0
   expect "Name"
   send "$Username\n"
   expect "Password"
   send "$Password\n"
   expect "ftp>"
   send "cd $arg2 \n"
   expect "ftp>"
   send "put $arg1 \n"
   expect "ftp>"
   send "chmod 777 $arg1 \n"
   expect "ftp>"
   send "bye \n"
   exit
   }

   #se houver 4 argumentos, telnet para o primeiro, ftp para o 2º, o 3º é o ficheiro, o 4º o path


   if {$arg3 != ""} {
   spawn ftp 10.112.42.$arg0
   expect "Name"
   send "$Username\n"
   expect "Password"
   send "$Password\n"
   expect "ftp>"
   send "cd / \n"
   expect "ftp>"
   send "put $arg2 \n"
   expect "ftp>"
   send "bye \n"
   
   #o ficheiro está no primeiro ponto
     
   spawn telnet 10.112.42.$arg0
   expect "login:" 
   send "$Username\n"
   expect "Password:"
   send "$Password\n"
   expect "#"
   send "cd / \n"
   expect "#"
   send "ftp 192.168.200.$arg1\n"
   expect "Name"
   send "$Username\n"
   expect "Password"
   send "$Password\n"
   expect "ftp>"
   send "cd $arg3 \n"
   expect "ftp>"
   send "put $arg2 \n"
   expect "ftp>"
   send "chmod 777 $arg2 \n"
   expect "ftp>"
   send "bye \n"
   
   #estamos de volta na sessão telnet no primeiro ponto, apagar o ficheiro temporário
   
   send "rm $arg2 \n"
   expect "#"
   send "exit"
   exit
   }

   
