# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Trident3 SOC driver Library
#

LOCALDIR = src/soc/esw/trident3

include ${SDK}/make/Make.config

SUBDIR_TRIDENT3_FLEXPORT = flexport

subdirs := $(SUBDIR_TRIDENT3_FLEXPORT)

lib = libsoc_trident3

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

