#
# $Id$
# $Copyright: (c) 2018 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dpp subdirectory
#

LOCALDIR = src/appl/diag/dnx/swstate/auto_generated

include ${SDK}/make/Make.config

#
# Take the subdir 'diagnostic'
#
subdirs = diagnostic

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxswstate_auto_generated

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

