# $Id: Makefile,v 1.4 2007/10/08 22:27:33 iakramov Exp $
# $Copyright: (c) 2005 Broadcom Corp.
# All Rights Reserved.$
#
#
PLATFORM=m32

include ${SDK}/make/Make.config


lib = libsoc_kbp_nlm2_ftm_refapp

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

