/* $Id: $
 * 
 * $Copyright: Copyright 2015 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#include <sal/core/libc.h>
#include <shared/swstate/sw_state.h>
#include <shared/error.h>
#include <shared/swstate/sw_state_defs.h>
#include <shared/bsl.h>
#include <shared/swstate/access/sw_state_access.h>
#include <shared/swstate/access/sw_state_dpp_bcm_l2_access.h>


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_set(int _unit, CONST l2_data_t *l2){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.bcm.l2.verify( _unit);
    sal_memcpy(&(sw_state[_unit]->dpp.bcm.l2[0]), l2, sizeof(l2_data_t));
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.bcm.l2[0]), sizeof(l2_data_t));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_get(int _unit, l2_data_t *l2){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.verify( _unit);
    *l2 = sw_state[_unit]->dpp.bcm.l2[0];
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_alloc(int _unit){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    SW_STATE_IS_ALREADY_ALLOCATED_CHECK(sw_state[_unit]->dpp.bcm.l2);
    rv = shr_sw_state_alloc(_unit, (uint8 **) &sw_state[_unit]->dpp.bcm.l2, sizeof(l2_data_t));
    return rv;
}

/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_is_allocated(int _unit, uint8 *is_allocated){
    int rv = _SHR_E_NONE;
    *is_allocated = (sw_state[_unit]->dpp.bcm.l2) ? 1 : 0;
    rv = _SHR_E_NONE;
    return rv;
}

/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_free(int _unit){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    SW_STATE_NULL_CHECK(sw_state[_unit]->dpp.bcm.l2);
    rv = shr_sw_state_free(_unit, (uint8 *) sw_state[_unit]->dpp.bcm.l2);
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    SW_STATE_NULL_ACCESS_CHECK(sw_state[_unit]->dpp.bcm.l2);
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.bcm.l2);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mymac_msb_is_set_set(int _unit, uint8 mymac_msb_is_set){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.bcm.l2.mymac_msb_is_set.verify( _unit);
    sw_state[_unit]->dpp.bcm.l2->mymac_msb_is_set = mymac_msb_is_set;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.bcm.l2->mymac_msb_is_set), sizeof(uint8));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mymac_msb_is_set_get(int _unit, uint8 *mymac_msb_is_set){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.mymac_msb_is_set.verify( _unit);
    *mymac_msb_is_set = sw_state[_unit]->dpp.bcm.l2->mymac_msb_is_set;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mymac_msb_is_set_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mymac_msb_is_set_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.bcm.l2->mymac_msb_is_set);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_l2_initialized_set(int _unit, int l2_initialized){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.bcm.l2.l2_initialized.verify( _unit);
    sw_state[_unit]->dpp.bcm.l2->l2_initialized = l2_initialized;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.bcm.l2->l2_initialized), sizeof(int));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_l2_initialized_get(int _unit, int *l2_initialized){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.l2_initialized.verify( _unit);
    *l2_initialized = sw_state[_unit]->dpp.bcm.l2->l2_initialized;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_l2_initialized_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_l2_initialized_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.bcm.l2->l2_initialized);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_set(int _unit, CONST _bcm_petra_l2_freeze_t *bcm_petra_l2_freeze_state){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.verify( _unit);
    sal_memcpy(&(sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state), bcm_petra_l2_freeze_state, sizeof(_bcm_petra_l2_freeze_t));
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state), sizeof(_bcm_petra_l2_freeze_t));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_get(int _unit, _bcm_petra_l2_freeze_t *bcm_petra_l2_freeze_state){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.verify( _unit);
    *bcm_petra_l2_freeze_state = sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_set(int _unit, int frozen){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.frozen.verify( _unit);
    sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.frozen = frozen;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.frozen), sizeof(int));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_get(int _unit, int *frozen){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.frozen.verify( _unit);
    *frozen = sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.frozen;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.frozen);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_set(int _unit, int save_age_ena){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_age_ena.verify( _unit);
    sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.save_age_ena = save_age_ena;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.save_age_ena), sizeof(int));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_get(int _unit, int *save_age_ena){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_age_ena.verify( _unit);
    *save_age_ena = sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.save_age_ena;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.save_age_ena);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_set(int _unit, int save_learn_ena){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_learn_ena.verify( _unit);
    sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.save_learn_ena = save_learn_ena;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.save_learn_ena), sizeof(int));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_get(int _unit, int *save_learn_ena){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_learn_ena.verify( _unit);
    *save_learn_ena = sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.save_learn_ena;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.save_learn_ena);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_set(int _unit, uint16 mpls_extended_label_ether_type_index_table_is_set){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.bcm.l2.mpls_extended_label_ether_type_index_table_is_set.verify( _unit);
    sw_state[_unit]->dpp.bcm.l2->mpls_extended_label_ether_type_index_table_is_set = mpls_extended_label_ether_type_index_table_is_set;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.bcm.l2->mpls_extended_label_ether_type_index_table_is_set), sizeof(uint16));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_get(int _unit, uint16 *mpls_extended_label_ether_type_index_table_is_set){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.mpls_extended_label_ether_type_index_table_is_set.verify( _unit);
    *mpls_extended_label_ether_type_index_table_is_set = sw_state[_unit]->dpp.bcm.l2->mpls_extended_label_ether_type_index_table_is_set;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.bcm.l2.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.bcm.l2->mpls_extended_label_ether_type_index_table_is_set);
    *ret_size = size;
    return rv;
}



int
sw_state_dpp_bcm_l2_access_cb_init(int _unit){
    sw_state_access[_unit].dpp.bcm.l2.set = sw_state_dpp_bcm_l2_set;
    sw_state_access[_unit].dpp.bcm.l2.get = sw_state_dpp_bcm_l2_get;
    sw_state_access[_unit].dpp.bcm.l2.alloc = sw_state_dpp_bcm_l2_alloc;
    sw_state_access[_unit].dpp.bcm.l2.is_allocated = sw_state_dpp_bcm_l2_is_allocated;
    sw_state_access[_unit].dpp.bcm.l2.free = sw_state_dpp_bcm_l2_free;
    sw_state_access[_unit].dpp.bcm.l2.verify = sw_state_dpp_bcm_l2_verify;
    sw_state_access[_unit].dpp.bcm.l2.get_size = sw_state_dpp_bcm_l2_get_size;
    sw_state_access[_unit].dpp.bcm.l2.mymac_msb_is_set.set = sw_state_dpp_bcm_l2_mymac_msb_is_set_set;
    sw_state_access[_unit].dpp.bcm.l2.mymac_msb_is_set.get = sw_state_dpp_bcm_l2_mymac_msb_is_set_get;
    sw_state_access[_unit].dpp.bcm.l2.mymac_msb_is_set.verify = sw_state_dpp_bcm_l2_mymac_msb_is_set_verify;
    sw_state_access[_unit].dpp.bcm.l2.mymac_msb_is_set.get_size = sw_state_dpp_bcm_l2_mymac_msb_is_set_get_size;
    sw_state_access[_unit].dpp.bcm.l2.l2_initialized.set = sw_state_dpp_bcm_l2_l2_initialized_set;
    sw_state_access[_unit].dpp.bcm.l2.l2_initialized.get = sw_state_dpp_bcm_l2_l2_initialized_get;
    sw_state_access[_unit].dpp.bcm.l2.l2_initialized.verify = sw_state_dpp_bcm_l2_l2_initialized_verify;
    sw_state_access[_unit].dpp.bcm.l2.l2_initialized.get_size = sw_state_dpp_bcm_l2_l2_initialized_get_size;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.set = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_set;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.get = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_get;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.verify = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_verify;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.get_size = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_get_size;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.frozen.set = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_set;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.frozen.get = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_get;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.frozen.verify = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_verify;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.frozen.get_size = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_get_size;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_age_ena.set = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_set;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_age_ena.get = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_get;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_age_ena.verify = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_verify;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_age_ena.get_size = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_get_size;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_learn_ena.set = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_set;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_learn_ena.get = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_get;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_learn_ena.verify = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_verify;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_learn_ena.get_size = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_get_size;
    sw_state_access[_unit].dpp.bcm.l2.mpls_extended_label_ether_type_index_table_is_set.set = sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_set;
    sw_state_access[_unit].dpp.bcm.l2.mpls_extended_label_ether_type_index_table_is_set.get = sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_get;
    sw_state_access[_unit].dpp.bcm.l2.mpls_extended_label_ether_type_index_table_is_set.verify = sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_verify;
    sw_state_access[_unit].dpp.bcm.l2.mpls_extended_label_ether_type_index_table_is_set.get_size = sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_get_size;
    return _SHR_E_NONE;
}
