/* $Id: $
 * 
 * $Copyright: Copyright 2015 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#include <sal/core/libc.h>
#include <shared/swstate/sw_state.h>
#include <shared/error.h>
#include <shared/swstate/sw_state_defs.h>
#include <shared/bsl.h>
#include <shared/swstate/access/sw_state_access.h>
#include <shared/swstate/access/sw_state_dpp_soc_arad_pp_oam_access.h>


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_set(int _unit, CONST ARAD_PP_OAM_SW_STATE *oam){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    sal_memcpy(&(sw_state[_unit]->dpp.soc.arad.pp->oam[0]), oam, sizeof(ARAD_PP_OAM_SW_STATE));
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.pp->oam[0]), sizeof(ARAD_PP_OAM_SW_STATE));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_get(int _unit, ARAD_PP_OAM_SW_STATE *oam){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    *oam = sw_state[_unit]->dpp.soc.arad.pp->oam[0];
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_alloc(int _unit){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    SW_STATE_IS_ALREADY_ALLOCATED_CHECK(sw_state[_unit]->dpp.soc.arad.pp->oam);
    rv = shr_sw_state_alloc(_unit, (uint8 **) &sw_state[_unit]->dpp.soc.arad.pp->oam, sizeof(ARAD_PP_OAM_SW_STATE));
    return rv;
}

/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_is_allocated(int _unit, uint8 *is_allocated){
    int rv = _SHR_E_NONE;
    *is_allocated = (sw_state[_unit]->dpp.soc.arad.pp->oam) ? 1 : 0;
    rv = _SHR_E_NONE;
    return rv;
}

/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_free(int _unit){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    SW_STATE_NULL_CHECK(sw_state[_unit]->dpp.soc.arad.pp->oam);
    rv = shr_sw_state_free(_unit, (uint8 *) sw_state[_unit]->dpp.soc.arad.pp->oam);
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    SW_STATE_NULL_ACCESS_CHECK(sw_state[_unit]->dpp.soc.arad.pp->oam);
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.pp->oam);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_recycle_set(int _unit, uint32 trap_code_recycle){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_recycle.verify( _unit);
    sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_recycle = trap_code_recycle;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_recycle), sizeof(uint32));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_recycle_get(int _unit, uint32 *trap_code_recycle){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_recycle.verify( _unit);
    *trap_code_recycle = sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_recycle;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_recycle_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_recycle_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_recycle);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_snoop_set(int _unit, uint32 trap_code_snoop){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_snoop.verify( _unit);
    sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_snoop = trap_code_snoop;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_snoop), sizeof(uint32));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_snoop_get(int _unit, uint32 *trap_code_snoop){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_snoop.verify( _unit);
    *trap_code_snoop = sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_snoop;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_snoop_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_snoop_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_snoop);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_frwrd_set(int _unit, uint32 trap_code_frwrd){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_frwrd.verify( _unit);
    sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_frwrd = trap_code_frwrd;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_frwrd), sizeof(uint32));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_frwrd_get(int _unit, uint32 *trap_code_frwrd){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_frwrd.verify( _unit);
    *trap_code_frwrd = sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_frwrd;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_frwrd_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_frwrd_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_frwrd);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_drop_set(int _unit, uint32 trap_code_drop){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_drop.verify( _unit);
    sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_drop = trap_code_drop;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_drop), sizeof(uint32));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_drop_get(int _unit, uint32 *trap_code_drop){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_drop.verify( _unit);
    *trap_code_drop = sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_drop;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_drop_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_drop_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_drop);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_level_set(int _unit, uint32 trap_code_trap_to_cpu_level){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_trap_to_cpu_level.verify( _unit);
    sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_trap_to_cpu_level = trap_code_trap_to_cpu_level;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_trap_to_cpu_level), sizeof(uint32));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_level_get(int _unit, uint32 *trap_code_trap_to_cpu_level){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_trap_to_cpu_level.verify( _unit);
    *trap_code_trap_to_cpu_level = sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_trap_to_cpu_level;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_level_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_level_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_trap_to_cpu_level);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_passive_set(int _unit, uint32 trap_code_trap_to_cpu_passive){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_trap_to_cpu_passive.verify( _unit);
    sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_trap_to_cpu_passive = trap_code_trap_to_cpu_passive;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_trap_to_cpu_passive), sizeof(uint32));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_passive_get(int _unit, uint32 *trap_code_trap_to_cpu_passive){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_trap_to_cpu_passive.verify( _unit);
    *trap_code_trap_to_cpu_passive = sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_trap_to_cpu_passive;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_passive_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_passive_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.pp->oam->trap_code_trap_to_cpu_passive);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_snoop_to_cpu_set(int _unit, uint32 mirror_profile_snoop_to_cpu){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_snoop_to_cpu.verify( _unit);
    sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_snoop_to_cpu = mirror_profile_snoop_to_cpu;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_snoop_to_cpu), sizeof(uint32));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_snoop_to_cpu_get(int _unit, uint32 *mirror_profile_snoop_to_cpu){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_snoop_to_cpu.verify( _unit);
    *mirror_profile_snoop_to_cpu = sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_snoop_to_cpu;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_snoop_to_cpu_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_snoop_to_cpu_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_snoop_to_cpu);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_recycle_set(int _unit, uint32 mirror_profile_recycle){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_recycle.verify( _unit);
    sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_recycle = mirror_profile_recycle;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_recycle), sizeof(uint32));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_recycle_get(int _unit, uint32 *mirror_profile_recycle){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_recycle.verify( _unit);
    *mirror_profile_recycle = sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_recycle;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_recycle_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_recycle_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_recycle);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_level_set(int _unit, uint32 mirror_profile_err_level){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_err_level.verify( _unit);
    sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_err_level = mirror_profile_err_level;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_err_level), sizeof(uint32));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_level_get(int _unit, uint32 *mirror_profile_err_level){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_err_level.verify( _unit);
    *mirror_profile_err_level = sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_err_level;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_level_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_level_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_err_level);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_passive_set(int _unit, uint32 mirror_profile_err_passive){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_err_passive.verify( _unit);
    sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_err_passive = mirror_profile_err_passive;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_err_passive), sizeof(uint32));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_passive_get(int _unit, uint32 *mirror_profile_err_passive){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_err_passive.verify( _unit);
    *mirror_profile_err_passive = sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_err_passive;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_passive_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_passive_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.pp->oam->mirror_profile_err_passive);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_tcam_last_entry_id_set(int _unit, uint32 tcam_last_entry_id){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.tcam_last_entry_id.verify( _unit);
    sw_state[_unit]->dpp.soc.arad.pp->oam->tcam_last_entry_id = tcam_last_entry_id;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.pp->oam->tcam_last_entry_id), sizeof(uint32));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_tcam_last_entry_id_get(int _unit, uint32 *tcam_last_entry_id){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.tcam_last_entry_id.verify( _unit);
    *tcam_last_entry_id = sw_state[_unit]->dpp.soc.arad.pp->oam->tcam_last_entry_id;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_tcam_last_entry_id_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.pp.oam.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_pp_oam_tcam_last_entry_id_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.pp->oam->tcam_last_entry_id);
    *ret_size = size;
    return rv;
}



int
sw_state_dpp_soc_arad_pp_oam_access_cb_init(int _unit){
    sw_state_access[_unit].dpp.soc.arad.pp.oam.set = sw_state_dpp_soc_arad_pp_oam_set;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.get = sw_state_dpp_soc_arad_pp_oam_get;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.alloc = sw_state_dpp_soc_arad_pp_oam_alloc;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.is_allocated = sw_state_dpp_soc_arad_pp_oam_is_allocated;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.free = sw_state_dpp_soc_arad_pp_oam_free;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.verify = sw_state_dpp_soc_arad_pp_oam_verify;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.get_size = sw_state_dpp_soc_arad_pp_oam_get_size;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_recycle.set = sw_state_dpp_soc_arad_pp_oam_trap_code_recycle_set;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_recycle.get = sw_state_dpp_soc_arad_pp_oam_trap_code_recycle_get;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_recycle.verify = sw_state_dpp_soc_arad_pp_oam_trap_code_recycle_verify;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_recycle.get_size = sw_state_dpp_soc_arad_pp_oam_trap_code_recycle_get_size;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_snoop.set = sw_state_dpp_soc_arad_pp_oam_trap_code_snoop_set;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_snoop.get = sw_state_dpp_soc_arad_pp_oam_trap_code_snoop_get;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_snoop.verify = sw_state_dpp_soc_arad_pp_oam_trap_code_snoop_verify;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_snoop.get_size = sw_state_dpp_soc_arad_pp_oam_trap_code_snoop_get_size;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_frwrd.set = sw_state_dpp_soc_arad_pp_oam_trap_code_frwrd_set;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_frwrd.get = sw_state_dpp_soc_arad_pp_oam_trap_code_frwrd_get;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_frwrd.verify = sw_state_dpp_soc_arad_pp_oam_trap_code_frwrd_verify;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_frwrd.get_size = sw_state_dpp_soc_arad_pp_oam_trap_code_frwrd_get_size;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_drop.set = sw_state_dpp_soc_arad_pp_oam_trap_code_drop_set;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_drop.get = sw_state_dpp_soc_arad_pp_oam_trap_code_drop_get;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_drop.verify = sw_state_dpp_soc_arad_pp_oam_trap_code_drop_verify;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_drop.get_size = sw_state_dpp_soc_arad_pp_oam_trap_code_drop_get_size;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_trap_to_cpu_level.set = sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_level_set;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_trap_to_cpu_level.get = sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_level_get;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_trap_to_cpu_level.verify = sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_level_verify;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_trap_to_cpu_level.get_size = sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_level_get_size;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_trap_to_cpu_passive.set = sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_passive_set;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_trap_to_cpu_passive.get = sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_passive_get;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_trap_to_cpu_passive.verify = sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_passive_verify;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.trap_code_trap_to_cpu_passive.get_size = sw_state_dpp_soc_arad_pp_oam_trap_code_trap_to_cpu_passive_get_size;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_snoop_to_cpu.set = sw_state_dpp_soc_arad_pp_oam_mirror_profile_snoop_to_cpu_set;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_snoop_to_cpu.get = sw_state_dpp_soc_arad_pp_oam_mirror_profile_snoop_to_cpu_get;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_snoop_to_cpu.verify = sw_state_dpp_soc_arad_pp_oam_mirror_profile_snoop_to_cpu_verify;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_snoop_to_cpu.get_size = sw_state_dpp_soc_arad_pp_oam_mirror_profile_snoop_to_cpu_get_size;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_recycle.set = sw_state_dpp_soc_arad_pp_oam_mirror_profile_recycle_set;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_recycle.get = sw_state_dpp_soc_arad_pp_oam_mirror_profile_recycle_get;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_recycle.verify = sw_state_dpp_soc_arad_pp_oam_mirror_profile_recycle_verify;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_recycle.get_size = sw_state_dpp_soc_arad_pp_oam_mirror_profile_recycle_get_size;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_err_level.set = sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_level_set;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_err_level.get = sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_level_get;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_err_level.verify = sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_level_verify;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_err_level.get_size = sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_level_get_size;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_err_passive.set = sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_passive_set;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_err_passive.get = sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_passive_get;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_err_passive.verify = sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_passive_verify;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.mirror_profile_err_passive.get_size = sw_state_dpp_soc_arad_pp_oam_mirror_profile_err_passive_get_size;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.tcam_last_entry_id.set = sw_state_dpp_soc_arad_pp_oam_tcam_last_entry_id_set;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.tcam_last_entry_id.get = sw_state_dpp_soc_arad_pp_oam_tcam_last_entry_id_get;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.tcam_last_entry_id.verify = sw_state_dpp_soc_arad_pp_oam_tcam_last_entry_id_verify;
    sw_state_access[_unit].dpp.soc.arad.pp.oam.tcam_last_entry_id.get_size = sw_state_dpp_soc_arad_pp_oam_tcam_last_entry_id_get_size;
    return _SHR_E_NONE;
}
