#
# $Copyright: (c) 2018 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
LOCALDIR = src/appl/ctest/dnx

include ${SDK}/make/Make.config

lib = libctest_dnx

subdirs+= algo dbal field l3 lif switch tm trap vlan mpls oamp infra crps kbp

include ${SDK}/make/Make.subdirs
include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
