#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/appl/diag/dnx/l3

include ${SDK}/make/Make.config

lib = libdiag_dnxl3

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

