#
#
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dnx/pemladrv

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/shared

lib = libsoc_dnxpemladrv

subdirs = auto_generated

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
