# $Id: $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Hurricane4 flexport common library

LOCALDIR = src/soc/esw/hurricane4/flexport

include ${SDK}/make/Make.config

lib = libsoc_hurricane4_flexport

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
