/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: $
 * $Copyright: (c) 2021 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 * File:        dnxf_tx_dispatch.h
 * Purpose:     dnxf tx driver BCM API dispatch table
 * Generator:   modules_dispatch.py
 */

#ifndef _BCM_INT_DNXF_TX_DISPATCH_H
#define _BCM_INT_DNXF_TX_DISPATCH_H

#include <bcm/types.h>
#include <bcm_int/dispatch.h>

#ifdef BCM_DNXF_SUPPORT

extern int bcm_dnxf_tx(int,bcm_pkt_t *,void *);

#endif /* BCM_DNXF_SUPPORT */
#endif /* !_BCM_INT_DNXF_TX_DISPATCH_H */
