#
# $Id: Makefile Exp $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/bcm/dnx/tdm

include ${SDK}/make/Make.config

lib = libbcm_dnxtdm

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
