# $Id:  Exp $
#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for MONTEREy SOC driver Library
#

LOCALDIR = src/soc/esw/monterey/

include ${SDK}/make/Make.config

lib = libsoc_monterey

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend


