#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/soc/dnx/arr/auto_generated

include ${SDK}/make/Make.config

#subdirs =

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxarr_auto_generated

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

