#
# $Id: Makefile,v 1.4 
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/bcm/dnx/algo/sch

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/bcm_int/dnx/algo/sch

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxalgosch

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
