#
# $Id: Makefile,v 1.4 2017/11/11
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/ptp

include ${SDK}/make/Make.config

#subdirs =

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxptp

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

