# $Id: $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Trident3 flexport common library

LOCALDIR = src/soc/esw/trident3/flexport

include ${SDK}/make/Make.config

lib = libsoc_trident3_flexport

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
