# $Id$
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM Helix5 driver Library
#

LOCALDIR = src/bcm/esw/helix5

include ${SDK}/make/Make.config

lib = libhelix5

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
