

ifeq (1,$(BLD_L7_PRODUCT_ENTERPRISE))
include $(FP_ROOT)/src/mgmt/broadcom/web/fastpath/make/Makefile
endif

ifeq (1,$(BLD_L7_PRODUCT_SMB))
include $(FP_ROOT)/src/mgmt/broadcom/web/fastpath/make/Makefile
endif

ifeq (1,$(BLD_L7_PRODUCT_NETWORKAPPLIANCE))
include $(FP_ROOT)/src/mgmt/broadcom/web/fastpath/make/Makefile
endif

