#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/field/map

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/bcm/dnx/field

lib = libbcm_dnxfieldmap

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

