#
# $Id: Makefile,v 1.4 2016/10/10
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/bcm/dnx/stat

include ${SDK}/make/Make.config

#subdirs = stat
subdirs += crps
subdirs += stif
subdirs += mib

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxstat

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

