# $Id: Makefile Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/appl/diag/esw/techsupport/flowtracker

include ${SDK}/make/Make.config

lib = libtsflowtracker

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
