# -*- Makefile -*-
# $Id: $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM compat driver Library
#

LOCALDIR = src/bcm/dnx/algo/ppmc

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/bcm_int/dnx/algo/ppmc

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxalgoppmc

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
