#!/bin/bash

version=3.9
patch=0
svnUpdate=1
compile=1

if [ $# -ge 1 ]; then
  # Show help 
  if [ $1 == "h" -o $1 == "help" ]; then
    echo "Syntax: $0 [version] [patch] [update_svn(0/1)] [compile(0/1)]"
    exit 0;
  fi
  version=$1
fi
if [ $# -ge 2 ]; then
  patch=$2
fi
if [ $# -ge 3 ]; then
  svnUpdate=$3
  if  [ $updateSvn -ne 1 -a $updateSvn -ne 0 ]; then
    echo "Invalid Input Parameter: updateSvn=$updateSvn"
    exit -1
  fi
fi
if [ $# -ge 4 ]; then
  compile=$4
  if  [ $compile -ne 1 -a $compile -ne 0 ]; then
    echo "Invalid Input Parameter: compile=$compile"
    exit -1
  fi
fi

# Update SVN
if [ $svnUpdate -eq 1 ]; then
  echo "Updating svn..."
  cd ..
  svn update
  cd -
fi

echo "Preparing build version $version.$patch in background..."
#echo "Do you wish to proceed? (type 'yes' to continue) "
read -p "Do you wish to proceed? (type 'yes' to continue) " answer
if [ $answer != 'yes' ]; then
  echo "Aborting procedure. Good bye!"
  exit 0;
fi

echo "Build procedure have started..."
sh buildFpAllInOne $version $patch 0 $compile > output.txt &
echo "You can monitor the results at 'output.txt'. See you."

