# $Id: Makefile Exp $
#
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Maverick2 SOC driver Library
#

LOCALDIR = src/soc/esw/tdm/maverick2/

include ${SDK}/make/Make.config

lib = libsoc_tdm_mv2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

