#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/diag/dnx/kbp

include ${SDK}/make/Make.config

#INCDIR += -I${SDK}/include/soc/dnx/kbp

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxkbp

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

