# $Id$
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM Hurricane4 driver Library
#

LOCALDIR = src/bcm/esw/hurricane4

include ${SDK}/make/Make.config

lib = libhurricane4

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
