/** \file dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition.c
 * Logical DB enums \n 
 * DO NOT EDIT THIS FILE!\n 
 * This file is auto-generated.\n 
 * Edits to this file will be lost when it is regenerated.\n 
 * \n 
 */
/*
 * $Id: $
 $Copyright: (c) 2018 Broadcom.
 Broadcom Proprietary and Confidential. All rights reserved.$
 * 
 */
#ifdef BSL_LOG_MODULE
#  error "BSL_LOG_MODULE redefined"
#endif
#define BSL_LOG_MODULE BSL_LS_SOCDNX_DBALDNX

#include <src/soc/dnx/dbal/dbal_internal.h>

shr_error_e
_dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_failover_ingress_path_select_init(
int unit,
table_db_struct_t * cur_table_param,
dbal_logical_table_t * table_info)
{
    table_db_field_params_struct_t * db_field;
    SHR_FUNC_INIT_VARS(unit);
    dbal_init_table_db_struct_clear(cur_table_param);
    SHR_IF_ERR_EXIT(dbal_db_init_general_info_set(unit, cur_table_param, "FAILOVER_INGRESS_PATH_SELECT" /* name*/, NULL /* is valid*/, DBAL_ACCESS_METHOD_HARD_LOGIC /* access method*/));
    /** maturity level  */
    /** default maturity level  */
    SHR_IF_ERR_EXIT(dbal_db_init_maturity_level_set(unit, cur_table_param, DBAL_MATURITY_HIGH));
    /** *************  */
    /** set interface  */
    /** *************  */
    SHR_IF_ERR_EXIT(dbal_db_init_app_db_set_interface(unit, cur_table_param, "DIRECT" /* type*/, "FAILOVER" /* labels*/));
    /** interface keys  */
    {
        int key_field_counter = 0;
        db_field = &cur_table_param->key_fields[key_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "PROTECTION_POINTER" /* name*/, NULL /* Valid*/, "14" /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, NULL /* Type*/));
        key_field_counter++;
        cur_table_param->nof_key_fields = key_field_counter;
    }
    /** interface results  */
    {
        int result_field_counter = 0;
        int result_type_counter = 0;
        /** interface single result  */
        sal_memset(&(cur_table_param->results_set[result_type_counter]), 0x0, sizeof(table_db_results_field_set_struct_t));
        db_field = &cur_table_param->results_set[result_type_counter].result_fields[result_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "PROTECTION_PATH" /* name*/, NULL /* Valid*/, NULL /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, NULL /* Type*/));
        result_field_counter++;
        cur_table_param->results_set[result_type_counter].nof_res_fields = result_field_counter;
        result_type_counter++;
        cur_table_param->result_type_exists = FALSE;
        cur_table_param->num_of_results_sets = result_type_counter;
    }
    /** *************  */
    /** app to phy db  */
    /** *************  */
    /** clear access section  */
    dbal_db_init_table_db_struct_access_clear(cur_table_param);
    /** set app to phy db general information  */
    /** core mode  */
    sal_strncpy(cur_table_param->core_mode, "SBC", sizeof(cur_table_param->core_mode));
    /** reference field  */
    sal_strncpy(cur_table_param->reference_field_name, EMPTY /* reference field*/, sizeof(cur_table_param->reference_field_name));
    /** build access hl direct  */
    {
        int map_idx;
        int access_counter;
        map_idx = 0;
        access_counter = 0;
        sal_strncpy(cur_table_param->hl_access[map_idx].mapping_result_name, EMPTY /* result type*/, sizeof(cur_table_param->hl_access[map_idx].mapping_result_name));
        /** set (hl direct) accesses for field: PROTECTION_PATH  */
        {
            table_db_access_params_struct_t * access_params;
            /** set access  */
            {
                int instance_index = 0;
                access_params = &cur_table_param->hl_access[map_idx].access[access_counter];
                access_counter++;
                /** set hard logic access type  */
                SHR_IF_ERR_EXIT(dbal_db_init_hard_logic_direct_set_access_type(unit, access_params, FALSE /* is register*/, TRUE /* is memory*/););
                /** set access information  */
                SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_field(unit, access_params, "PROTECTION_PATH" /* field name*/, instance_index /* instance index*/, NULL /* field size*/, NULL /* field offset*/, 0 /* is tcam*/, EMPTY /* encode type*/, NULL /* encode value*/));
                /** set register/memory information for current access  */
                {
                    int regMemHwEntityId = INVALIDm;
                    int fieldHwEntityId = INVALIDf;
                    /** set reg/mem hw Entity id  */
                    regMemHwEntityId = IPPA_VTT_PATH_SELECTm;
                    /** set field hw Entity id  */
                    fieldHwEntityId = INVALIDf;
                    SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_register_memory(unit, access_params, EMPTY /* group name*/, regMemHwEntityId /* reg/mem hw entity id*/, EMPTY /* group offset*/, DBAL_DB_INVALID /* group offset int*/, EMPTY /* array offset*/, DBAL_DB_INVALID /* array offset int*/, "PROTECTION_POINTER/4" /* entry offset*/, DBAL_DB_INVALID /* entry offset int*/, EMPTY /* block index*/, DBAL_DB_INVALID /* block index int*/, "PROTECTION_POINTER%4" /* data offset*/, DBAL_DB_INVALID /* data offset int*/, fieldHwEntityId /* field hw entity id*/, EMPTY /* alias name*/, EMPTY /* alias offset*/, DBAL_DB_INVALID /* alias offset int*/));
                }
            }
        }
        /** set nof access for field mapping  */
        cur_table_param->hl_access[map_idx].nof_access = access_counter;
        /** update field mapping index  */
        map_idx++;
    }
    SHR_IF_ERR_EXIT(dbal_db_init_table_add(unit, cur_table_param, table_info));
exit:
    SHR_FUNC_EXIT;
}

shr_error_e
_dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_failover_egress_path_select_init(
int unit,
table_db_struct_t * cur_table_param,
dbal_logical_table_t * table_info)
{
    table_db_field_params_struct_t * db_field;
    SHR_FUNC_INIT_VARS(unit);
    dbal_init_table_db_struct_clear(cur_table_param);
    SHR_IF_ERR_EXIT(dbal_db_init_general_info_set(unit, cur_table_param, "FAILOVER_EGRESS_PATH_SELECT" /* name*/, NULL /* is valid*/, DBAL_ACCESS_METHOD_HARD_LOGIC /* access method*/));
    /** maturity level  */
    /** default maturity level  */
    SHR_IF_ERR_EXIT(dbal_db_init_maturity_level_set(unit, cur_table_param, DBAL_MATURITY_HIGH));
    /** *************  */
    /** set interface  */
    /** *************  */
    SHR_IF_ERR_EXIT(dbal_db_init_app_db_set_interface(unit, cur_table_param, "DIRECT" /* type*/, "FAILOVER" /* labels*/));
    /** interface keys  */
    {
        int key_field_counter = 0;
        db_field = &cur_table_param->key_fields[key_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "PROTECTION_POINTER" /* name*/, NULL /* Valid*/, "18" /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, NULL /* Type*/));
        key_field_counter++;
        cur_table_param->nof_key_fields = key_field_counter;
    }
    /** interface results  */
    {
        int result_field_counter = 0;
        int result_type_counter = 0;
        /** interface single result  */
        sal_memset(&(cur_table_param->results_set[result_type_counter]), 0x0, sizeof(table_db_results_field_set_struct_t));
        db_field = &cur_table_param->results_set[result_type_counter].result_fields[result_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "PROTECTION_PATH" /* name*/, NULL /* Valid*/, NULL /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, NULL /* Type*/));
        result_field_counter++;
        cur_table_param->results_set[result_type_counter].nof_res_fields = result_field_counter;
        result_type_counter++;
        cur_table_param->result_type_exists = FALSE;
        cur_table_param->num_of_results_sets = result_type_counter;
    }
    /** *************  */
    /** app to phy db  */
    /** *************  */
    /** clear access section  */
    dbal_db_init_table_db_struct_access_clear(cur_table_param);
    /** set app to phy db general information  */
    /** core mode  */
    sal_strncpy(cur_table_param->core_mode, "SBC", sizeof(cur_table_param->core_mode));
    /** reference field  */
    sal_strncpy(cur_table_param->reference_field_name, EMPTY /* reference field*/, sizeof(cur_table_param->reference_field_name));
    /** build access hl direct  */
    {
        int map_idx;
        int access_counter;
        map_idx = 0;
        access_counter = 0;
        sal_strncpy(cur_table_param->hl_access[map_idx].mapping_result_name, EMPTY /* result type*/, sizeof(cur_table_param->hl_access[map_idx].mapping_result_name));
        /** set (hl direct) accesses for field: PROTECTION_PATH  */
        {
            table_db_access_params_struct_t * access_params;
            /** set access  */
            {
                int instance_index = 0;
                access_params = &cur_table_param->hl_access[map_idx].access[access_counter];
                access_counter++;
                /** set hard logic access type  */
                SHR_IF_ERR_EXIT(dbal_db_init_hard_logic_direct_set_access_type(unit, access_params, FALSE /* is register*/, TRUE /* is memory*/););
                /** set access information  */
                SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_field(unit, access_params, "PROTECTION_PATH" /* field name*/, instance_index /* instance index*/, NULL /* field size*/, NULL /* field offset*/, 0 /* is tcam*/, EMPTY /* encode type*/, NULL /* encode value*/));
                /** set register/memory information for current access  */
                {
                    int regMemHwEntityId = INVALIDm;
                    int fieldHwEntityId = INVALIDf;
                    /** set reg/mem hw Entity id  */
                    regMemHwEntityId = ETPPC_PROTECTION_TABLEm;
                    /** set field hw Entity id  */
                    fieldHwEntityId = INVALIDf;
                    SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_register_memory(unit, access_params, EMPTY /* group name*/, regMemHwEntityId /* reg/mem hw entity id*/, EMPTY /* group offset*/, DBAL_DB_INVALID /* group offset int*/, EMPTY /* array offset*/, DBAL_DB_INVALID /* array offset int*/, "PROTECTION_POINTER/32" /* entry offset*/, DBAL_DB_INVALID /* entry offset int*/, EMPTY /* block index*/, DBAL_DB_INVALID /* block index int*/, "PROTECTION_POINTER%32" /* data offset*/, DBAL_DB_INVALID /* data offset int*/, fieldHwEntityId /* field hw entity id*/, EMPTY /* alias name*/, EMPTY /* alias offset*/, DBAL_DB_INVALID /* alias offset int*/));
                }
            }
        }
        /** set nof access for field mapping  */
        cur_table_param->hl_access[map_idx].nof_access = access_counter;
        /** update field mapping index  */
        map_idx++;
    }
    SHR_IF_ERR_EXIT(dbal_db_init_table_add(unit, cur_table_param, table_info));
exit:
    SHR_FUNC_EXIT;
}

shr_error_e
_dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_failover_fec_path_select_init(
int unit,
table_db_struct_t * cur_table_param,
dbal_logical_table_t * table_info)
{
    table_db_field_params_struct_t * db_field;
    SHR_FUNC_INIT_VARS(unit);
    dbal_init_table_db_struct_clear(cur_table_param);
    SHR_IF_ERR_EXIT(dbal_db_init_general_info_set(unit, cur_table_param, "FAILOVER_FEC_PATH_SELECT" /* name*/, NULL /* is valid*/, DBAL_ACCESS_METHOD_HARD_LOGIC /* access method*/));
    /** maturity level  */
    /** default maturity level  */
    SHR_IF_ERR_EXIT(dbal_db_init_maturity_level_set(unit, cur_table_param, DBAL_MATURITY_HIGH));
    /** *************  */
    /** set interface  */
    /** *************  */
    SHR_IF_ERR_EXIT(dbal_db_init_app_db_set_interface(unit, cur_table_param, "DIRECT" /* type*/, "FAILOVER" /* labels*/));
    /** interface keys  */
    {
        int key_field_counter = 0;
        db_field = &cur_table_param->key_fields[key_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "PROTECTION_POINTER" /* name*/, NULL /* Valid*/, "18" /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, NULL /* Type*/));
        key_field_counter++;
        cur_table_param->nof_key_fields = key_field_counter;
    }
    /** interface results  */
    {
        int result_field_counter = 0;
        int result_type_counter = 0;
        /** interface single result  */
        sal_memset(&(cur_table_param->results_set[result_type_counter]), 0x0, sizeof(table_db_results_field_set_struct_t));
        db_field = &cur_table_param->results_set[result_type_counter].result_fields[result_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "PROTECTION_PATH" /* name*/, NULL /* Valid*/, NULL /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, NULL /* Type*/));
        result_field_counter++;
        cur_table_param->results_set[result_type_counter].nof_res_fields = result_field_counter;
        result_type_counter++;
        cur_table_param->result_type_exists = FALSE;
        cur_table_param->num_of_results_sets = result_type_counter;
    }
    /** *************  */
    /** app to phy db  */
    /** *************  */
    /** clear access section  */
    dbal_db_init_table_db_struct_access_clear(cur_table_param);
    /** set app to phy db general information  */
    /** core mode  */
    sal_strncpy(cur_table_param->core_mode, "SBC", sizeof(cur_table_param->core_mode));
    /** reference field  */
    sal_strncpy(cur_table_param->reference_field_name, EMPTY /* reference field*/, sizeof(cur_table_param->reference_field_name));
    /** build access hl direct  */
    {
        int map_idx;
        int access_counter;
        map_idx = 0;
        access_counter = 0;
        sal_strncpy(cur_table_param->hl_access[map_idx].mapping_result_name, EMPTY /* result type*/, sizeof(cur_table_param->hl_access[map_idx].mapping_result_name));
        /** set (hl direct) accesses for field: PROTECTION_PATH  */
        {
            table_db_access_params_struct_t * access_params;
            /** set access  */
            {
                int instance_index = 0;
                access_params = &cur_table_param->hl_access[map_idx].access[access_counter];
                access_counter++;
                /** set hard logic access type  */
                SHR_IF_ERR_EXIT(dbal_db_init_hard_logic_direct_set_access_type(unit, access_params, FALSE /* is register*/, TRUE /* is memory*/););
                /** set access information  */
                SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_field(unit, access_params, "PROTECTION_PATH" /* field name*/, instance_index /* instance index*/, NULL /* field size*/, NULL /* field offset*/, 0 /* is tcam*/, EMPTY /* encode type*/, NULL /* encode value*/));
                /** set register/memory information for current access  */
                {
                    int regMemHwEntityId = INVALIDm;
                    int fieldHwEntityId = INVALIDf;
                    /** set reg/mem hw Entity id  */
                    regMemHwEntityId = IPPD_FEC_PATH_SELECTm;
                    /** set field hw Entity id  */
                    fieldHwEntityId = INVALIDf;
                    SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_register_memory(unit, access_params, EMPTY /* group name*/, regMemHwEntityId /* reg/mem hw entity id*/, EMPTY /* group offset*/, DBAL_DB_INVALID /* group offset int*/, "PROTECTION_POINTER/16384" /* array offset*/, DBAL_DB_INVALID /* array offset int*/, "PROTECTION_POINTER%16384/32" /* entry offset*/, DBAL_DB_INVALID /* entry offset int*/, EMPTY /* block index*/, DBAL_DB_INVALID /* block index int*/, "PROTECTION_POINTER%32" /* data offset*/, DBAL_DB_INVALID /* data offset int*/, fieldHwEntityId /* field hw entity id*/, EMPTY /* alias name*/, EMPTY /* alias offset*/, DBAL_DB_INVALID /* alias offset int*/));
                }
            }
            /** set access  */
            {
                int instance_index = 0;
                access_params = &cur_table_param->hl_access[map_idx].access[access_counter];
                access_counter++;
                /** set hard logic access type  */
                SHR_IF_ERR_EXIT(dbal_db_init_hard_logic_direct_set_access_type(unit, access_params, FALSE /* is register*/, TRUE /* is memory*/););
                /** set access information  */
                SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_field(unit, access_params, "PROTECTION_PATH" /* field name*/, instance_index /* instance index*/, NULL /* field size*/, NULL /* field offset*/, 0 /* is tcam*/, EMPTY /* encode type*/, NULL /* encode value*/));
                /** set register/memory information for current access  */
                {
                    int regMemHwEntityId = INVALIDm;
                    int fieldHwEntityId = INVALIDf;
                    /** set reg/mem hw Entity id  */
                    regMemHwEntityId = IPPD_FEC_PATH_SELECTm;
                    /** set field hw Entity id  */
                    fieldHwEntityId = INVALIDf;
                    SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_register_memory(unit, access_params, EMPTY /* group name*/, regMemHwEntityId /* reg/mem hw entity id*/, EMPTY /* group offset*/, DBAL_DB_INVALID /* group offset int*/, "PROTECTION_POINTER/16384+DNX_DATA.failover.path_select.nof_fec_path_select_banks" /* array offset*/, DBAL_DB_INVALID /* array offset int*/, "PROTECTION_POINTER%16384/32" /* entry offset*/, DBAL_DB_INVALID /* entry offset int*/, EMPTY /* block index*/, DBAL_DB_INVALID /* block index int*/, "PROTECTION_POINTER%32" /* data offset*/, DBAL_DB_INVALID /* data offset int*/, fieldHwEntityId /* field hw entity id*/, EMPTY /* alias name*/, EMPTY /* alias offset*/, DBAL_DB_INVALID /* alias offset int*/));
                }
            }
        }
        /** set nof access for field mapping  */
        cur_table_param->hl_access[map_idx].nof_access = access_counter;
        /** update field mapping index  */
        map_idx++;
    }
    SHR_IF_ERR_EXIT(dbal_db_init_table_add(unit, cur_table_param, table_info));
exit:
    SHR_FUNC_EXIT;
}

shr_error_e
_dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_failover_fec_path_select_bank_config_init(
int unit,
table_db_struct_t * cur_table_param,
dbal_logical_table_t * table_info)
{
    table_db_field_params_struct_t * db_field;
    SHR_FUNC_INIT_VARS(unit);
    dbal_init_table_db_struct_clear(cur_table_param);
    SHR_IF_ERR_EXIT(dbal_db_init_general_info_set(unit, cur_table_param, "FAILOVER_FEC_PATH_SELECT_BANK_CONFIG" /* name*/, NULL /* is valid*/, DBAL_ACCESS_METHOD_HARD_LOGIC /* access method*/));
    /** maturity level  */
    /** default maturity level  */
    SHR_IF_ERR_EXIT(dbal_db_init_maturity_level_set(unit, cur_table_param, DBAL_MATURITY_HIGH));
    /** *************  */
    /** set interface  */
    /** *************  */
    SHR_IF_ERR_EXIT(dbal_db_init_app_db_set_interface(unit, cur_table_param, "DIRECT" /* type*/, "FAILOVER" /* labels*/));
    /** interface keys  */
    {
        int key_field_counter = 0;
        db_field = &cur_table_param->key_fields[key_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "BANK_ID" /* name*/, NULL /* Valid*/, "4" /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, "UINT" /* Type*/));
        key_field_counter++;
        cur_table_param->nof_key_fields = key_field_counter;
    }
    /** interface results  */
    {
        int result_field_counter = 0;
        int result_type_counter = 0;
        /** interface single result  */
        sal_memset(&(cur_table_param->results_set[result_type_counter]), 0x0, sizeof(table_db_results_field_set_struct_t));
        db_field = &cur_table_param->results_set[result_type_counter].result_fields[result_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "HIERARCHY_LEVEL" /* name*/, NULL /* Valid*/, NULL /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, NULL /* Type*/));
        result_field_counter++;
        cur_table_param->results_set[result_type_counter].nof_res_fields = result_field_counter;
        result_type_counter++;
        cur_table_param->result_type_exists = FALSE;
        cur_table_param->num_of_results_sets = result_type_counter;
    }
    /** *************  */
    /** app to phy db  */
    /** *************  */
    /** clear access section  */
    dbal_db_init_table_db_struct_access_clear(cur_table_param);
    /** set app to phy db general information  */
    /** core mode  */
    sal_strncpy(cur_table_param->core_mode, "SBC", sizeof(cur_table_param->core_mode));
    /** reference field  */
    sal_strncpy(cur_table_param->reference_field_name, EMPTY /* reference field*/, sizeof(cur_table_param->reference_field_name));
    /** build access hl direct  */
    {
        int map_idx;
        int access_counter;
        map_idx = 0;
        access_counter = 0;
        sal_strncpy(cur_table_param->hl_access[map_idx].mapping_result_name, EMPTY /* result type*/, sizeof(cur_table_param->hl_access[map_idx].mapping_result_name));
        /** set (hl direct) accesses for field: HIERARCHY_LEVEL  */
        {
            table_db_access_params_struct_t * access_params;
            /** set access  */
            {
                int instance_index = 0;
                access_params = &cur_table_param->hl_access[map_idx].access[access_counter];
                access_counter++;
                /** set hard logic access type  */
                SHR_IF_ERR_EXIT(dbal_db_init_hard_logic_direct_set_access_type(unit, access_params, TRUE /* is register*/, FALSE /* is memory*/););
                /** set access information  */
                SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_field(unit, access_params, "HIERARCHY_LEVEL" /* field name*/, instance_index /* instance index*/, NULL /* field size*/, NULL /* field offset*/, 0 /* is tcam*/, EMPTY /* encode type*/, NULL /* encode value*/));
                /** set register/memory information for current access  */
                {
                    int regMemHwEntityId = INVALIDr;
                    int fieldHwEntityId = INVALIDf;
                    /** set reg/mem hw Entity id  */
                    regMemHwEntityId = IPPD_FER_POINTER_CONSRUCTIONr;
                    /** set field hw Entity id  */
                    fieldHwEntityId = PROTECTION_TO_STAGE_MAP_FWDf;
                    SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_register_memory(unit, access_params, EMPTY /* group name*/, regMemHwEntityId /* reg/mem hw entity id*/, EMPTY /* group offset*/, DBAL_DB_INVALID /* group offset int*/, EMPTY /* array offset*/, DBAL_DB_INVALID /* array offset int*/, EMPTY /* entry offset*/, DBAL_DB_INVALID /* entry offset int*/, EMPTY /* block index*/, DBAL_DB_INVALID /* block index int*/, "BANK_ID*2" /* data offset*/, DBAL_DB_INVALID /* data offset int*/, fieldHwEntityId /* field hw entity id*/, EMPTY /* alias name*/, EMPTY /* alias offset*/, DBAL_DB_INVALID /* alias offset int*/));
                }
            }
            /** set access  */
            {
                int instance_index = 0;
                access_params = &cur_table_param->hl_access[map_idx].access[access_counter];
                access_counter++;
                /** set hard logic access type  */
                SHR_IF_ERR_EXIT(dbal_db_init_hard_logic_direct_set_access_type(unit, access_params, TRUE /* is register*/, FALSE /* is memory*/););
                /** set access information  */
                SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_field(unit, access_params, "HIERARCHY_LEVEL" /* field name*/, instance_index /* instance index*/, NULL /* field size*/, NULL /* field offset*/, 0 /* is tcam*/, EMPTY /* encode type*/, NULL /* encode value*/));
                /** set register/memory information for current access  */
                {
                    int regMemHwEntityId = INVALIDr;
                    int fieldHwEntityId = INVALIDf;
                    /** set reg/mem hw Entity id  */
                    regMemHwEntityId = IPPD_FER_POINTER_CONSRUCTIONr;
                    /** set field hw Entity id  */
                    fieldHwEntityId = PROTECTION_TO_STAGE_MAP_RPFf;
                    SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_register_memory(unit, access_params, EMPTY /* group name*/, regMemHwEntityId /* reg/mem hw entity id*/, EMPTY /* group offset*/, DBAL_DB_INVALID /* group offset int*/, EMPTY /* array offset*/, DBAL_DB_INVALID /* array offset int*/, EMPTY /* entry offset*/, DBAL_DB_INVALID /* entry offset int*/, EMPTY /* block index*/, DBAL_DB_INVALID /* block index int*/, "BANK_ID*2" /* data offset*/, DBAL_DB_INVALID /* data offset int*/, fieldHwEntityId /* field hw entity id*/, EMPTY /* alias name*/, EMPTY /* alias offset*/, DBAL_DB_INVALID /* alias offset int*/));
                }
            }
        }
        /** set nof access for field mapping  */
        cur_table_param->hl_access[map_idx].nof_access = access_counter;
        /** update field mapping index  */
        map_idx++;
    }
    SHR_IF_ERR_EXIT(dbal_db_init_table_add(unit, cur_table_param, table_info));
exit:
    SHR_FUNC_EXIT;
}

shr_error_e
_dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_failover_fec_path_select_config_init(
int unit,
table_db_struct_t * cur_table_param,
dbal_logical_table_t * table_info)
{
    table_db_field_params_struct_t * db_field;
    SHR_FUNC_INIT_VARS(unit);
    dbal_init_table_db_struct_clear(cur_table_param);
    SHR_IF_ERR_EXIT(dbal_db_init_general_info_set(unit, cur_table_param, "FAILOVER_FEC_PATH_SELECT_CONFIG" /* name*/, NULL /* is valid*/, DBAL_ACCESS_METHOD_HARD_LOGIC /* access method*/));
    /** maturity level  */
    /** default maturity level  */
    SHR_IF_ERR_EXIT(dbal_db_init_maturity_level_set(unit, cur_table_param, DBAL_MATURITY_HIGH));
    /** *************  */
    /** set interface  */
    /** *************  */
    SHR_IF_ERR_EXIT(dbal_db_init_app_db_set_interface(unit, cur_table_param, "DIRECT" /* type*/, "FAILOVER" /* labels*/));
    /** interface keys  */
    {
        int key_field_counter = 0;
        cur_table_param->nof_key_fields = key_field_counter;
    }
    /** interface results  */
    {
        int result_field_counter = 0;
        int result_type_counter = 0;
        /** interface single result  */
        sal_memset(&(cur_table_param->results_set[result_type_counter]), 0x0, sizeof(table_db_results_field_set_struct_t));
        db_field = &cur_table_param->results_set[result_type_counter].result_fields[result_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "NO_PROTECTION_PTR" /* name*/, NULL /* Valid*/, "18" /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, "PROTECTION_POINTER" /* Type*/));
        result_field_counter++;
        db_field = &cur_table_param->results_set[result_type_counter].result_fields[result_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "FACILITY_PROTECTION_PTR" /* name*/, NULL /* Valid*/, "18" /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, "PROTECTION_POINTER" /* Type*/));
        result_field_counter++;
        db_field = &cur_table_param->results_set[result_type_counter].result_fields[result_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "FACILITY_ACCELERATED_MODE_ENABLE" /* name*/, NULL /* Valid*/, NULL /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, "BOOL" /* Type*/));
        result_field_counter++;
        db_field = &cur_table_param->results_set[result_type_counter].result_fields[result_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "FACILITY_LOGIC" /* name*/, NULL /* Valid*/, "512" /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, "ARRAY32" /* Type*/));
        result_field_counter++;
        db_field = &cur_table_param->results_set[result_type_counter].result_fields[result_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "FACILITY_TRAP_LOGIC" /* name*/, NULL /* Valid*/, "512" /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, "ARRAY32" /* Type*/));
        result_field_counter++;
        cur_table_param->results_set[result_type_counter].nof_res_fields = result_field_counter;
        result_type_counter++;
        cur_table_param->result_type_exists = FALSE;
        cur_table_param->num_of_results_sets = result_type_counter;
    }
    /** *************  */
    /** app to phy db  */
    /** *************  */
    /** clear access section  */
    dbal_db_init_table_db_struct_access_clear(cur_table_param);
    /** set app to phy db general information  */
    /** core mode  */
    sal_strncpy(cur_table_param->core_mode, "SBC", sizeof(cur_table_param->core_mode));
    /** reference field  */
    sal_strncpy(cur_table_param->reference_field_name, EMPTY /* reference field*/, sizeof(cur_table_param->reference_field_name));
    /** build access hl direct  */
    {
        int map_idx;
        int access_counter;
        map_idx = 0;
        access_counter = 0;
        sal_strncpy(cur_table_param->hl_access[map_idx].mapping_result_name, EMPTY /* result type*/, sizeof(cur_table_param->hl_access[map_idx].mapping_result_name));
        /** set (hl direct) accesses for field: NO_PROTECTION_PTR  */
        {
            table_db_access_params_struct_t * access_params;
            /** set access  */
            {
                int instance_index = 0;
                access_params = &cur_table_param->hl_access[map_idx].access[access_counter];
                access_counter++;
                /** set hard logic access type  */
                SHR_IF_ERR_EXIT(dbal_db_init_hard_logic_direct_set_access_type(unit, access_params, TRUE /* is register*/, FALSE /* is memory*/););
                /** set access information  */
                SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_field(unit, access_params, "NO_PROTECTION_PTR" /* field name*/, instance_index /* instance index*/, NULL /* field size*/, NULL /* field offset*/, 0 /* is tcam*/, EMPTY /* encode type*/, NULL /* encode value*/));
                /** set register/memory information for current access  */
                {
                    int regMemHwEntityId = INVALIDr;
                    int fieldHwEntityId = INVALIDf;
                    /** set reg/mem hw Entity id  */
                    regMemHwEntityId = IPPD_RESOLUTION_CFGr;
                    /** set field hw Entity id  */
                    fieldHwEntityId = NOT_PROTECTED_CODEf;
                    SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_register_memory(unit, access_params, EMPTY /* group name*/, regMemHwEntityId /* reg/mem hw entity id*/, EMPTY /* group offset*/, DBAL_DB_INVALID /* group offset int*/, EMPTY /* array offset*/, DBAL_DB_INVALID /* array offset int*/, EMPTY /* entry offset*/, DBAL_DB_INVALID /* entry offset int*/, EMPTY /* block index*/, DBAL_DB_INVALID /* block index int*/, EMPTY /* data offset*/, DBAL_DB_INVALID /* data offset int*/, fieldHwEntityId /* field hw entity id*/, EMPTY /* alias name*/, EMPTY /* alias offset*/, DBAL_DB_INVALID /* alias offset int*/));
                }
            }
        }
        /** set (hl direct) accesses for field: FACILITY_PROTECTION_PTR  */
        {
            table_db_access_params_struct_t * access_params;
            /** set access  */
            {
                int instance_index = 0;
                access_params = &cur_table_param->hl_access[map_idx].access[access_counter];
                access_counter++;
                /** set hard logic access type  */
                SHR_IF_ERR_EXIT(dbal_db_init_hard_logic_direct_set_access_type(unit, access_params, TRUE /* is register*/, FALSE /* is memory*/););
                /** set access information  */
                SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_field(unit, access_params, "FACILITY_PROTECTION_PTR" /* field name*/, instance_index /* instance index*/, NULL /* field size*/, NULL /* field offset*/, 0 /* is tcam*/, EMPTY /* encode type*/, NULL /* encode value*/));
                /** set register/memory information for current access  */
                {
                    int regMemHwEntityId = INVALIDr;
                    int fieldHwEntityId = INVALIDf;
                    /** set reg/mem hw Entity id  */
                    regMemHwEntityId = IPPD_RESOLUTION_CFGr;
                    /** set field hw Entity id  */
                    fieldHwEntityId = FACILITY_PROTECTED_CODEf;
                    SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_register_memory(unit, access_params, EMPTY /* group name*/, regMemHwEntityId /* reg/mem hw entity id*/, EMPTY /* group offset*/, DBAL_DB_INVALID /* group offset int*/, EMPTY /* array offset*/, DBAL_DB_INVALID /* array offset int*/, EMPTY /* entry offset*/, DBAL_DB_INVALID /* entry offset int*/, EMPTY /* block index*/, DBAL_DB_INVALID /* block index int*/, EMPTY /* data offset*/, DBAL_DB_INVALID /* data offset int*/, fieldHwEntityId /* field hw entity id*/, EMPTY /* alias name*/, EMPTY /* alias offset*/, DBAL_DB_INVALID /* alias offset int*/));
                }
            }
        }
        /** set (hl direct) accesses for field: FACILITY_ACCELERATED_MODE_ENABLE  */
        {
            table_db_access_params_struct_t * access_params;
            /** set access  */
            {
                int instance_index = 0;
                access_params = &cur_table_param->hl_access[map_idx].access[access_counter];
                access_counter++;
                /** set hard logic access type  */
                SHR_IF_ERR_EXIT(dbal_db_init_hard_logic_direct_set_access_type(unit, access_params, TRUE /* is register*/, FALSE /* is memory*/););
                /** set access information  */
                SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_field(unit, access_params, "FACILITY_ACCELERATED_MODE_ENABLE" /* field name*/, instance_index /* instance index*/, NULL /* field size*/, NULL /* field offset*/, 0 /* is tcam*/, EMPTY /* encode type*/, NULL /* encode value*/));
                /** set register/memory information for current access  */
                {
                    int regMemHwEntityId = INVALIDr;
                    int fieldHwEntityId = INVALIDf;
                    /** set reg/mem hw Entity id  */
                    regMemHwEntityId = IPPD_RESOLUTION_CFGr;
                    /** set field hw Entity id  */
                    fieldHwEntityId = ENABLE_PATH_AND_FACILITIY_PROTECTIONf;
                    SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_register_memory(unit, access_params, EMPTY /* group name*/, regMemHwEntityId /* reg/mem hw entity id*/, EMPTY /* group offset*/, DBAL_DB_INVALID /* group offset int*/, EMPTY /* array offset*/, DBAL_DB_INVALID /* array offset int*/, EMPTY /* entry offset*/, DBAL_DB_INVALID /* entry offset int*/, EMPTY /* block index*/, DBAL_DB_INVALID /* block index int*/, EMPTY /* data offset*/, DBAL_DB_INVALID /* data offset int*/, fieldHwEntityId /* field hw entity id*/, EMPTY /* alias name*/, EMPTY /* alias offset*/, DBAL_DB_INVALID /* alias offset int*/));
                }
            }
        }
        /** set (hl direct) accesses for field: FACILITY_LOGIC  */
        {
            table_db_access_params_struct_t * access_params;
            /** set access  */
            {
                int instance_index = 0;
                access_params = &cur_table_param->hl_access[map_idx].access[access_counter];
                access_counter++;
                /** set hard logic access type  */
                SHR_IF_ERR_EXIT(dbal_db_init_hard_logic_direct_set_access_type(unit, access_params, TRUE /* is register*/, FALSE /* is memory*/););
                /** set access information  */
                SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_field(unit, access_params, "FACILITY_LOGIC" /* field name*/, instance_index /* instance index*/, NULL /* field size*/, NULL /* field offset*/, 0 /* is tcam*/, EMPTY /* encode type*/, NULL /* encode value*/));
                /** set register/memory information for current access  */
                {
                    int regMemHwEntityId = INVALIDr;
                    int fieldHwEntityId = INVALIDf;
                    /** set reg/mem hw Entity id  */
                    regMemHwEntityId = IPPD_RESOLUTION_FACILITY_PROTECTION_LOGICr;
                    /** set field hw Entity id  */
                    fieldHwEntityId = FACILITY_PROTECTION_LOGICf;
                    SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_register_memory(unit, access_params, EMPTY /* group name*/, regMemHwEntityId /* reg/mem hw entity id*/, EMPTY /* group offset*/, DBAL_DB_INVALID /* group offset int*/, EMPTY /* array offset*/, DBAL_DB_INVALID /* array offset int*/, EMPTY /* entry offset*/, DBAL_DB_INVALID /* entry offset int*/, EMPTY /* block index*/, DBAL_DB_INVALID /* block index int*/, EMPTY /* data offset*/, DBAL_DB_INVALID /* data offset int*/, fieldHwEntityId /* field hw entity id*/, EMPTY /* alias name*/, EMPTY /* alias offset*/, DBAL_DB_INVALID /* alias offset int*/));
                }
            }
        }
        /** set (hl direct) accesses for field: FACILITY_TRAP_LOGIC  */
        {
            table_db_access_params_struct_t * access_params;
            /** set access  */
            {
                int instance_index = 0;
                access_params = &cur_table_param->hl_access[map_idx].access[access_counter];
                access_counter++;
                /** set hard logic access type  */
                SHR_IF_ERR_EXIT(dbal_db_init_hard_logic_direct_set_access_type(unit, access_params, TRUE /* is register*/, FALSE /* is memory*/););
                /** set access information  */
                SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_field(unit, access_params, "FACILITY_TRAP_LOGIC" /* field name*/, instance_index /* instance index*/, NULL /* field size*/, NULL /* field offset*/, 0 /* is tcam*/, EMPTY /* encode type*/, NULL /* encode value*/));
                /** set register/memory information for current access  */
                {
                    int regMemHwEntityId = INVALIDr;
                    int fieldHwEntityId = INVALIDf;
                    /** set reg/mem hw Entity id  */
                    regMemHwEntityId = IPPD_RESOLUTION_FACILITY_TRAP_LOGICr;
                    /** set field hw Entity id  */
                    fieldHwEntityId = FACILITY_TRAP_LOGICf;
                    SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_register_memory(unit, access_params, EMPTY /* group name*/, regMemHwEntityId /* reg/mem hw entity id*/, EMPTY /* group offset*/, DBAL_DB_INVALID /* group offset int*/, EMPTY /* array offset*/, DBAL_DB_INVALID /* array offset int*/, EMPTY /* entry offset*/, DBAL_DB_INVALID /* entry offset int*/, EMPTY /* block index*/, DBAL_DB_INVALID /* block index int*/, EMPTY /* data offset*/, DBAL_DB_INVALID /* data offset int*/, fieldHwEntityId /* field hw entity id*/, EMPTY /* alias name*/, EMPTY /* alias offset*/, DBAL_DB_INVALID /* alias offset int*/));
                }
            }
        }
        /** set nof access for field mapping  */
        cur_table_param->hl_access[map_idx].nof_access = access_counter;
        /** update field mapping index  */
        map_idx++;
    }
    SHR_IF_ERR_EXIT(dbal_db_init_table_add(unit, cur_table_param, table_info));
exit:
    SHR_FUNC_EXIT;
}

shr_error_e
_dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_failover_facility_destination_status_init(
int unit,
table_db_struct_t * cur_table_param,
dbal_logical_table_t * table_info)
{
    table_db_field_params_struct_t * db_field;
    SHR_FUNC_INIT_VARS(unit);
    dbal_init_table_db_struct_clear(cur_table_param);
    SHR_IF_ERR_EXIT(dbal_db_init_general_info_set(unit, cur_table_param, "FAILOVER_FACILITY_DESTINATION_STATUS" /* name*/, NULL /* is valid*/, DBAL_ACCESS_METHOD_HARD_LOGIC /* access method*/));
    /** maturity level  */
    /** default maturity level  */
    SHR_IF_ERR_EXIT(dbal_db_init_maturity_level_set(unit, cur_table_param, DBAL_MATURITY_HIGH));
    /** *************  */
    /** set interface  */
    /** *************  */
    SHR_IF_ERR_EXIT(dbal_db_init_app_db_set_interface(unit, cur_table_param, "DIRECT" /* type*/, "L3" /* labels*/));
    /** interface keys  */
    {
        int key_field_counter = 0;
        db_field = &cur_table_param->key_fields[key_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "SYSTEM_PORT" /* name*/, NULL /* Valid*/, NULL /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, NULL /* Type*/));
        key_field_counter++;
        cur_table_param->nof_key_fields = key_field_counter;
    }
    /** interface results  */
    {
        int result_field_counter = 0;
        int result_type_counter = 0;
        /** interface single result  */
        sal_memset(&(cur_table_param->results_set[result_type_counter]), 0x0, sizeof(table_db_results_field_set_struct_t));
        db_field = &cur_table_param->results_set[result_type_counter].result_fields[result_field_counter];
        SHR_IF_ERR_EXIT(dbal_db_init_table_set_field(unit, db_field, "ENABLE" /* name*/, NULL /* Valid*/, NULL /* Size*/, NULL /* Offset*/, NULL /* MaxValue*/, NULL /* MinValue*/, NULL /* ConstValue*/, NULL /* NofInstance*/, DBAL_PERMISSION_ALL /* Permission*/, FALSE /* ReverseOrder*/, "BOOL" /* Type*/));
        result_field_counter++;
        cur_table_param->results_set[result_type_counter].nof_res_fields = result_field_counter;
        result_type_counter++;
        cur_table_param->result_type_exists = FALSE;
        cur_table_param->num_of_results_sets = result_type_counter;
    }
    /** *************  */
    /** app to phy db  */
    /** *************  */
    /** clear access section  */
    dbal_db_init_table_db_struct_access_clear(cur_table_param);
    /** set app to phy db general information  */
    /** core mode  */
    sal_strncpy(cur_table_param->core_mode, "SBC", sizeof(cur_table_param->core_mode));
    /** reference field  */
    sal_strncpy(cur_table_param->reference_field_name, EMPTY /* reference field*/, sizeof(cur_table_param->reference_field_name));
    /** build access hl direct  */
    {
        int map_idx;
        int access_counter;
        map_idx = 0;
        access_counter = 0;
        sal_strncpy(cur_table_param->hl_access[map_idx].mapping_result_name, EMPTY /* result type*/, sizeof(cur_table_param->hl_access[map_idx].mapping_result_name));
        /** set (hl direct) accesses for field: ENABLE  */
        {
            table_db_access_params_struct_t * access_params;
            /** set access  */
            {
                int instance_index = 0;
                access_params = &cur_table_param->hl_access[map_idx].access[access_counter];
                access_counter++;
                /** set hard logic access type  */
                SHR_IF_ERR_EXIT(dbal_db_init_hard_logic_direct_set_access_type(unit, access_params, FALSE /* is register*/, TRUE /* is memory*/););
                /** set access information  */
                SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_field(unit, access_params, "ENABLE" /* field name*/, instance_index /* instance index*/, NULL /* field size*/, NULL /* field offset*/, 0 /* is tcam*/, EMPTY /* encode type*/, NULL /* encode value*/));
                /** set register/memory information for current access  */
                {
                    int regMemHwEntityId = INVALIDm;
                    int fieldHwEntityId = INVALIDf;
                    /** set reg/mem hw Entity id  */
                    regMemHwEntityId = IPPD_DESTINATION_STATUSm;
                    /** set field hw Entity id  */
                    fieldHwEntityId = INVALIDf;
                    SHR_IF_ERR_EXIT(dbal_db_init_table_set_access_register_memory(unit, access_params, EMPTY /* group name*/, regMemHwEntityId /* reg/mem hw entity id*/, EMPTY /* group offset*/, DBAL_DB_INVALID /* group offset int*/, EMPTY /* array offset*/, DBAL_DB_INVALID /* array offset int*/, "SYSTEM_PORT/8" /* entry offset*/, DBAL_DB_INVALID /* entry offset int*/, EMPTY /* block index*/, DBAL_DB_INVALID /* block index int*/, "SYSTEM_PORT%8" /* data offset*/, DBAL_DB_INVALID /* data offset int*/, fieldHwEntityId /* field hw entity id*/, EMPTY /* alias name*/, EMPTY /* alias offset*/, DBAL_DB_INVALID /* alias offset int*/));
                }
            }
        }
        /** set nof access for field mapping  */
        cur_table_param->hl_access[map_idx].nof_access = access_counter;
        /** update field mapping index  */
        map_idx++;
    }
    SHR_IF_ERR_EXIT(dbal_db_init_table_add(unit, cur_table_param, table_info));
exit:
    SHR_FUNC_EXIT;
}

shr_error_e
dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_init(
int unit,
table_db_struct_t* cur_table_param,
dbal_logical_table_t * table_info)
{
    SHR_FUNC_INIT_VARS(unit);
    SHR_IF_ERR_EXIT(_dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_failover_ingress_path_select_init(unit, cur_table_param, table_info));
    SHR_IF_ERR_EXIT(_dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_failover_egress_path_select_init(unit, cur_table_param, table_info));
    SHR_IF_ERR_EXIT(_dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_failover_fec_path_select_init(unit, cur_table_param, table_info));
    SHR_IF_ERR_EXIT(_dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_failover_fec_path_select_bank_config_init(unit, cur_table_param, table_info));
    SHR_IF_ERR_EXIT(_dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_failover_fec_path_select_config_init(unit, cur_table_param, table_info));
    SHR_IF_ERR_EXIT(_dbal_init_tables_hard_logic_pp_failover_hl_pp_failover_definition_failover_facility_destination_status_init(unit, cur_table_param, table_info));
exit:
    SHR_FUNC_EXIT;
}
