# $Id: $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Maverick2 flexport common library

LOCALDIR = src/soc/esw/maverick2/flexport

include ${SDK}/make/Make.config

lib = libsoc_maverick2_flexport

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
