#
# $Id:$
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC swstate subdirectory
#
LOCALDIR = src/appl/diag/dnxf/swstate

include ${SDK}/make/Make.config
#
# Take the subdir 'auto_generated'
#
subdirs = auto_generated

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxfswstate

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
