#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/soc/dnx/field/tcam

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/soc/dnx/field

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxfieldtcam

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

