/*********************************************************************
*
* (C) Copyright Broadcom Corporation 2000-2007
*
**********************************************************************
*
* @filename platform_counters.h
*
* @purpose defines for the counter section of this hardware platform
*
* @component hardware
*
* @comments tba
*
* @create 12/07/2000
*
* @author bmutz
* @end
*
**********************************************************************/

#ifndef PLATFORM_COUNTERS_H
#define PLATFORM_COUNTERS_H

/* Use the following to define a counter ID that is not supported on a
 * particular hardware platform (don't just delete the counter ID definition!)
 */
#define L7_PLATFORM_CTR_NOT_SUPPORTED   0

#define L7_PLATFORM_CTR_RX_TOTAL_BYTES              ((L7_NIM_COMPONENT_ID << 16) | 0x0000)
#define L7_PLATFORM_CTR_RX_64                       ((L7_NIM_COMPONENT_ID << 16) | 0x0001)
#define L7_PLATFORM_CTR_RX_65_127                   ((L7_NIM_COMPONENT_ID << 16) | 0x0002)
#define L7_PLATFORM_CTR_RX_128_255                  ((L7_NIM_COMPONENT_ID << 16) | 0x0003)
#define L7_PLATFORM_CTR_RX_256_511                  ((L7_NIM_COMPONENT_ID << 16) | 0x0004)
#define L7_PLATFORM_CTR_RX_512_1023                 ((L7_NIM_COMPONENT_ID << 16) | 0x0005)
#define L7_PLATFORM_CTR_RX_1024_1518                ((L7_NIM_COMPONENT_ID << 16) | 0x0006)
#define L7_PLATFORM_CTR_RX_1519_1530                L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_RX_GOOD_OVERSIZE            ((L7_NIM_COMPONENT_ID << 16) | 0x0008)
#define L7_PLATFORM_CTR_RX_ERROR_OVERSIZE           ((L7_NIM_COMPONENT_ID << 16) | 0x0009)
#define L7_PLATFORM_CTR_RX_GOOD_UNDERSIZE           ((L7_NIM_COMPONENT_ID << 16) | 0x000a)
#define L7_PLATFORM_CTR_RX_ERROR_UNDERSIZE          ((L7_NIM_COMPONENT_ID << 16) | 0x000b)
#define L7_PLATFORM_CTR_RX_UCAST_FRAMES             ((L7_NIM_COMPONENT_ID << 16) | 0x000c)
#define L7_PLATFORM_CTR_RX_MCAST_FRAMES             ((L7_NIM_COMPONENT_ID << 16) | 0x000d)
#define L7_PLATFORM_CTR_RX_BCAST_FRAMES             ((L7_NIM_COMPONENT_ID << 16) | 0x000e)
#define L7_PLATFORM_CTR_RX_ALIGN_ERRORS             ((L7_NIM_COMPONENT_ID << 16) | 0x000f)
#define L7_PLATFORM_CTR_RX_FCS_ERRORS               ((L7_NIM_COMPONENT_ID << 16) | 0x0010)
#define L7_PLATFORM_CTR_RX_OVERRUNS                 ((L7_NIM_COMPONENT_ID << 16) | 0x0011)
#define L7_PLATFORM_CTR_RX_FRAME_TOO_LONG           ((L7_NIM_COMPONENT_ID << 16) | 0x0012)

#define L7_PLATFORM_CTR_TX_TOTAL_BYTES              ((L7_NIM_COMPONENT_ID << 16) | 0x0100)
#define L7_PLATFORM_CTR_TX_64                       ((L7_NIM_COMPONENT_ID << 16) | 0x0101)
#define L7_PLATFORM_CTR_TX_65_127                   ((L7_NIM_COMPONENT_ID << 16) | 0x0102)
#define L7_PLATFORM_CTR_TX_128_255                  ((L7_NIM_COMPONENT_ID << 16) | 0x0103)
#define L7_PLATFORM_CTR_TX_256_511                  ((L7_NIM_COMPONENT_ID << 16) | 0x0104)
#define L7_PLATFORM_CTR_TX_512_1023                 ((L7_NIM_COMPONENT_ID << 16) | 0x0105)
#define L7_PLATFORM_CTR_TX_1024_1518                ((L7_NIM_COMPONENT_ID << 16) | 0x0106)
#define L7_PLATFORM_CTR_TX_1519_1530                L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_TX_UCAST_FRAMES             ((L7_NIM_COMPONENT_ID << 16) | 0x0108)
#define L7_PLATFORM_CTR_TX_MCAST_FRAMES             ((L7_NIM_COMPONENT_ID << 16) | 0x0109)
#define L7_PLATFORM_CTR_TX_BCAST_FRAMES             ((L7_NIM_COMPONENT_ID << 16) | 0x010a)
#define L7_PLATFORM_CTR_TX_FCS_ERRORS               L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_TX_OVERSIZED                ((L7_NIM_COMPONENT_ID << 16) | 0x010c)
#define L7_PLATFORM_CTR_TX_UNDERRUN_ERRORS          L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_TX_ONE_COLLISION            ((L7_NIM_COMPONENT_ID << 16) | 0x010e)
#define L7_PLATFORM_CTR_TX_MULTIPLE_COLLISION       ((L7_NIM_COMPONENT_ID << 16) | 0x010f)
#define L7_PLATFORM_CTR_TX_EXCESSIVE_COLLISION      ((L7_NIM_COMPONENT_ID << 16) | 0x0110)
#define L7_PLATFORM_CTR_TX_LATE_COLLISION           ((L7_NIM_COMPONENT_ID << 16) | 0x0111)

#define L7_PLATFORM_CTR_TX_RX_64                    ((L7_NIM_COMPONENT_ID << 16) | 0x0112)
#define L7_PLATFORM_CTR_TX_RX_65_127                ((L7_NIM_COMPONENT_ID << 16) | 0x0113)
#define L7_PLATFORM_CTR_TX_RX_128_255               ((L7_NIM_COMPONENT_ID << 16) | 0x0114)
#define L7_PLATFORM_CTR_TX_RX_256_511               ((L7_NIM_COMPONENT_ID << 16) | 0x0115)
#define L7_PLATFORM_CTR_TX_RX_512_1023              ((L7_NIM_COMPONENT_ID << 16) | 0x0116)
#define L7_PLATFORM_CTR_TX_RX_1024_1518             ((L7_NIM_COMPONENT_ID << 16) | 0x0117)
#define L7_PLATFORM_CTR_TX_RX_1519_1522              L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_TX_RX_1523_2047             ((L7_NIM_COMPONENT_ID << 16) | 0x0119)
#define L7_PLATFORM_CTR_TX_RX_2048_4095             ((L7_NIM_COMPONENT_ID << 16) | 0x011a)
#define L7_PLATFORM_CTR_TX_RX_4096_9216             ((L7_NIM_COMPONENT_ID << 16) | 0x011b)
#define L7_PLATFORM_CTR_ETHER_STATS_DROP_EVENTS     ((L7_NIM_COMPONENT_ID << 16) | 0x011c)
#define L7_PLATFORM_CTR_SNMPIFOUTDISCARD_FRAMES     ((L7_NIM_COMPONENT_ID << 16) | 0x011d)
#define L7_PLATFORM_CTR_SNMPIFINDISCARD_FRAMES      ((L7_NIM_COMPONENT_ID << 16) | 0x011e)

/* Switch - Receive Routing Function Counters */

#define L7_PLATFORM_CTR_RX_IP_IN_RECEIVES           ((L7_LAYER3_COMPONENT_ID << 16) | 0x0000)
#define L7_PLATFORM_CTR_RX_IP_IN_HDR_ERRORS         ((L7_LAYER3_COMPONENT_ID << 16) | 0x0001)
#define L7_PLATFORM_CTR_RX_IP_IN_ADDR_ERRORS        ((L7_LAYER3_COMPONENT_ID << 16) | 0x0002)
#define L7_PLATFORM_CTR_RX_IP_FORW_DATAGRAMS        ((L7_LAYER3_COMPONENT_ID << 16) | 0x0003)
#define L7_PLATFORM_CTR_RX_IP_IN_UNKNOWN_PROTOS     ((L7_LAYER3_COMPONENT_ID << 16) | 0x0004)
#define L7_PLATFORM_CTR_RX_IP_IN_DISCARDS           ((L7_LAYER3_COMPONENT_ID << 16) | 0x0005)
#define L7_PLATFORM_CTR_RX_IP_IN_DELIVERS           ((L7_LAYER3_COMPONENT_ID << 16) | 0x0006)
#define L7_PLATFORM_CTR_RX_IP_REASM_REQDS           ((L7_LAYER3_COMPONENT_ID << 16) | 0x0007)
#define L7_PLATFORM_CTR_RX_IP_REASM_OKS             ((L7_LAYER3_COMPONENT_ID << 16) | 0x0008)
#define L7_PLATFORM_CTR_RX_IP_REASM_FAILS           ((L7_LAYER3_COMPONENT_ID << 16) | 0x0009)
#define L7_PLATFORM_CTR_RX_IP_FRAG_OKS              ((L7_LAYER3_COMPONENT_ID << 16) | 0x000a)
#define L7_PLATFORM_CTR_RX_IP_FRAG_FAILS            ((L7_LAYER3_COMPONENT_ID << 16) | 0x000b)
#define L7_PLATFORM_CTR_RX_IP_FRAG_CREATES          ((L7_LAYER3_COMPONENT_ID << 16) | 0x000c)
#define L7_PLATFORM_CTR_RX_ICMP_IN_MSGS             ((L7_LAYER3_COMPONENT_ID << 16) | 0x000d)
#define L7_PLATFORM_CTR_RX_ICMP_IN_ERRORS           ((L7_LAYER3_COMPONENT_ID << 16) | 0x000e)
#define L7_PLATFORM_CTR_RX_ICMP_IN_DEST_UNREACHS    ((L7_LAYER3_COMPONENT_ID << 16) | 0x000f)
#define L7_PLATFORM_CTR_RX_ICMP_IN_TIME_EXCDS       ((L7_LAYER3_COMPONENT_ID << 16) | 0x0010)
#define L7_PLATFORM_CTR_RX_ICMP_IN_PARM_PROBS       ((L7_LAYER3_COMPONENT_ID << 16) | 0x0011)
#define L7_PLATFORM_CTR_RX_ICMP_IN_SRC_QUENCHS      ((L7_LAYER3_COMPONENT_ID << 16) | 0x0012)
#define L7_PLATFORM_CTR_RX_ICMP_IN_REDIRECTS        ((L7_LAYER3_COMPONENT_ID << 16) | 0x0013)
#define L7_PLATFORM_CTR_RX_ICMP_IN_ECHOS            ((L7_LAYER3_COMPONENT_ID << 16) | 0x0014)
#define L7_PLATFORM_CTR_RX_ICMP_IN_ECHO_REPS        ((L7_LAYER3_COMPONENT_ID << 16) | 0x0015)
#define L7_PLATFORM_CTR_RX_ICMP_IN_TIMESTAMPS       ((L7_LAYER3_COMPONENT_ID << 16) | 0x0016)
#define L7_PLATFORM_CTR_RX_ICMP_IN_TIMESTAMP_REPS   ((L7_LAYER3_COMPONENT_ID << 16) | 0x0017)
#define L7_PLATFORM_CTR_RX_ICMP_IN_ADDR_MASKS       ((L7_LAYER3_COMPONENT_ID << 16) | 0x0018)
#define L7_PLATFORM_CTR_RX_ICMP_IN_ADDR_MASK_REPS   ((L7_LAYER3_COMPONENT_ID << 16) | 0x0019)
#define L7_PLATFORM_CTR_RX_TCP_IN_SEGS              ((L7_LAYER3_COMPONENT_ID << 16) | 0x001a)
#define L7_PLATFORM_CTR_RX_TCP_IN_ERRS              ((L7_LAYER3_COMPONENT_ID << 16) | 0x001b)
#define L7_PLATFORM_CTR_RX_UDP_IN_DATAGRAMS         ((L7_LAYER3_COMPONENT_ID << 16) | 0x001c)
#define L7_PLATFORM_CTR_RX_UDP_IN_ERRORS            ((L7_LAYER3_COMPONENT_ID << 16) | 0x001d)
#define L7_PLATFORM_CTR_RX_EGP_IN_MSGS              ((L7_LAYER3_COMPONENT_ID << 16) | 0x001e)
#define L7_PLATFORM_CTR_RX_EGP_IN_ERRORS            ((L7_LAYER3_COMPONENT_ID << 16) | 0x001f)
#define L7_PLATFORM_CTR_RX_EGP_NEIGH_IN_MSGS        ((L7_LAYER3_COMPONENT_ID << 16) | 0x0020)
#define L7_PLATFORM_CTR_RX_EGP_NEIGH_IN_ERRS        ((L7_LAYER3_COMPONENT_ID << 16) | 0x0021)
#define L7_PLATFORM_CTR_RX_EGP_NEIGH_IN_ERR_MSGS    ((L7_LAYER3_COMPONENT_ID << 16) | 0x0022)


/* Switch - Transmit Routing Function Counters */

#define L7_PLATFORM_CTR_TX_IP_OUT_REQUESTS          ((L7_LAYER3_COMPONENT_ID << 16) | 0x0100)          
#define L7_PLATFORM_CTR_TX_IP_OUT_DISCARDS          ((L7_LAYER3_COMPONENT_ID << 16) | 0x0101)
#define L7_PLATFORM_CTR_TX_IP_OUT_NO_ROUTES         ((L7_LAYER3_COMPONENT_ID << 16) | 0x0102)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_MSGS            ((L7_LAYER3_COMPONENT_ID << 16) | 0x0103)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_ERRORS          ((L7_LAYER3_COMPONENT_ID << 16) | 0x0104)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_DEST_UNREACHS   ((L7_LAYER3_COMPONENT_ID << 16) | 0x0105)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_TIME_EXCDS      ((L7_LAYER3_COMPONENT_ID << 16) | 0x0106)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_PARM_PROBS      ((L7_LAYER3_COMPONENT_ID << 16) | 0x0107)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_SRC_QUENCHS     ((L7_LAYER3_COMPONENT_ID << 16) | 0x0108)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_REDIRECTS       ((L7_LAYER3_COMPONENT_ID << 16) | 0x0109)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_ECHOS           ((L7_LAYER3_COMPONENT_ID << 16) | 0x010a)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_ECHO_REPS       ((L7_LAYER3_COMPONENT_ID << 16) | 0x010b)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_TIMESTAMPS      ((L7_LAYER3_COMPONENT_ID << 16) | 0x010c)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_TIMESTAMP_REPS  ((L7_LAYER3_COMPONENT_ID << 16) | 0x010d)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_ADDR_MASKS      ((L7_LAYER3_COMPONENT_ID << 16) | 0x010e)
#define L7_PLATFORM_CTR_TX_ICMP_OUT_ADDR_MASK_REPS  ((L7_LAYER3_COMPONENT_ID << 16) | 0x010f)
#define L7_PLATFORM_CTR_TX_TCP_OUT_SEGS             ((L7_LAYER3_COMPONENT_ID << 16) | 0x0110)
#define L7_PLATFORM_CTR_TX_TCP_OUT_RSTS             ((L7_LAYER3_COMPONENT_ID << 16) | 0x0111)
#define L7_PLATFORM_CTR_TX_UDP_OUT_DATAGRAMS        ((L7_LAYER3_COMPONENT_ID << 16) | 0x0112)
#define L7_PLATFORM_CTR_TX_EGP_OUT_MSGS             ((L7_LAYER3_COMPONENT_ID << 16) | 0x0113)
#define L7_PLATFORM_CTR_TX_EGP_OUT_ERRORS           ((L7_LAYER3_COMPONENT_ID << 16) | 0x0114)
#define L7_PLATFORM_CTR_TX_EGP_NEIGH_OUT_MSGS       ((L7_LAYER3_COMPONENT_ID << 16) | 0x0115)
#define L7_PLATFORM_CTR_TX_EGP_NEIGH_OUT_ERRS       ((L7_LAYER3_COMPONENT_ID << 16) | 0x0116)
#define L7_PLATFORM_CTR_TX_EGP_NEIGH_OUT_ERR_MSGS   ((L7_LAYER3_COMPONENT_ID << 16) | 0x0117)

/* Switch - Miscellaneous counters */

#define L7_PLATFORM_CTR_IP_ROUTING_DISCARDS         ((L7_LAYER3_COMPONENT_ID << 16) | 0x0200)
#define L7_PLATFORM_CTR_IP_REASM_TIMEOUTS           ((L7_LAYER3_COMPONENT_ID << 16) | 0X0201)
#define L7_PLATFORM_CTR_TCP_ACTIVE_OPENS            ((L7_LAYER3_COMPONENT_ID << 16) | 0x0202)
#define L7_PLATFORM_CTR_TCP_PASSIVE_OPENS           ((L7_LAYER3_COMPONENT_ID << 16) | 0x0203)
#define L7_PLATFORM_CTR_TCP_ATTEMPT_FAILS           ((L7_LAYER3_COMPONENT_ID << 16) | 0x0204)
#define L7_PLATFORM_CTR_TCP_ESTAB_RESETS            ((L7_LAYER3_COMPONENT_ID << 16) | 0x0205)
#define L7_PLATFORM_CTR_TCP_RETRANS_SEGS            ((L7_LAYER3_COMPONENT_ID << 16) | 0x0206)
#define L7_PLATFORM_CTR_UDP_NO_PORTS                ((L7_LAYER3_COMPONENT_ID << 16) | 0x0207)
#define L7_PLATFORM_CTR_EGP_NEIGH_STATE_UPS         ((L7_LAYER3_COMPONENT_ID << 16) | 0x0208)
#define L7_PLATFORM_CTR_EGP_NEIGH_STATE_DOWNS       ((L7_LAYER3_COMPONENT_ID << 16) | 0x0209)

/* Layer3 driver specific counters */
#define L7_PLATFORM_CTR_RECEIVED_L3_MAC_MCAST_DISCARDS  L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_RECEIVED_L3_ARP_TO_CPU          L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_RECEIVED_L3_IP_TO_CPU           L7_PLATFORM_CTR_NOT_SUPPORTED

/* Switch - LAG Counters */
#define L7_PLATFORM_CTR_LAG_RX_TOTAL_BYTES          ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0000)
#define L7_PLATFORM_CTR_LAG_RX_64                   L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_RX_65_127               L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_RX_128_255              L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_RX_256_511              L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_RX_512_1023             L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_RX_1024_1518            L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_RX_1519_1530            L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_RX_GOOD_OVERSIZE        ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0008)
#define L7_PLATFORM_CTR_LAG_RX_ERROR_OVERSIZE       ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0009)
#define L7_PLATFORM_CTR_LAG_RX_GOOD_UNDERSIZE       ((L7_DOT3AD_COMPONENT_ID << 16) | 0x000a)
#define L7_PLATFORM_CTR_LAG_RX_ERROR_UNDERSIZE      ((L7_DOT3AD_COMPONENT_ID << 16) | 0x000b)
#define L7_PLATFORM_CTR_LAG_RX_UCAST_FRAMES         ((L7_DOT3AD_COMPONENT_ID << 16) | 0x000c)
#define L7_PLATFORM_CTR_LAG_RX_MCAST_FRAMES         ((L7_DOT3AD_COMPONENT_ID << 16) | 0x000d)
#define L7_PLATFORM_CTR_LAG_RX_BCAST_FRAMES         ((L7_DOT3AD_COMPONENT_ID << 16) | 0x000e)
#define L7_PLATFORM_CTR_LAG_RX_ALIGN_ERRORS         ((L7_DOT3AD_COMPONENT_ID << 16) | 0x000f)
#define L7_PLATFORM_CTR_LAG_RX_FCS_ERRORS           ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0010)
#define L7_PLATFORM_CTR_LAG_RX_OVERRUNS             ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0011)
#define L7_PLATFORM_CTR_LAG_RX_FRAME_TOO_LONG       ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0012)

#define L7_PLATFORM_CTR_LAG_TX_TOTAL_BYTES          ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0100)
#define L7_PLATFORM_CTR_LAG_TX_64                   L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_TX_65_127               L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_TX_128_255              L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_TX_256_511              L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_TX_512_1023             L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_TX_1024_1518            L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_TX_1519_1530            L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_LAG_TX_UCAST_FRAMES         ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0108)
#define L7_PLATFORM_CTR_LAG_TX_MCAST_FRAMES         ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0109)
#define L7_PLATFORM_CTR_LAG_TX_BCAST_FRAMES         ((L7_DOT3AD_COMPONENT_ID << 16) | 0x010a)
#define L7_PLATFORM_CTR_LAG_TX_FCS_ERRORS           ((L7_DOT3AD_COMPONENT_ID << 16) | 0x010b)
#define L7_PLATFORM_CTR_LAG_TX_OVERSIZED            ((L7_DOT3AD_COMPONENT_ID << 16) | 0x010c)
#define L7_PLATFORM_CTR_LAG_TX_UNDERRUN_ERRORS      ((L7_DOT3AD_COMPONENT_ID << 16) | 0x010d)
#define L7_PLATFORM_CTR_LAG_TX_ONE_COLLISION        ((L7_DOT3AD_COMPONENT_ID << 16) | 0x010e)
#define L7_PLATFORM_CTR_LAG_TX_MULTIPLE_COLLISION   ((L7_DOT3AD_COMPONENT_ID << 16) | 0x010f)
#define L7_PLATFORM_CTR_LAG_TX_EXCESSIVE_COLLISION  ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0110)
#define L7_PLATFORM_CTR_LAG_TX_LATE_COLLISION       ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0111)


#define L7_PLATFORM_CTR_LAG_TX_RX_64                    ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0112)
#define L7_PLATFORM_CTR_LAG_TX_RX_65_127                ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0113)
#define L7_PLATFORM_CTR_LAG_TX_RX_128_255               ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0114)
#define L7_PLATFORM_CTR_LAG_TX_RX_256_511               ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0115)
#define L7_PLATFORM_CTR_LAG_TX_RX_512_1023              ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0116)
#define L7_PLATFORM_CTR_LAG_TX_RX_1024_1518             ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0117)
#define L7_PLATFORM_CTR_LAG_TX_RX_1519_1522             ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0118)
#define L7_PLATFORM_CTR_LAG_TX_RX_1523_2047             ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0119)
#define L7_PLATFORM_CTR_LAG_TX_RX_2048_4095             ((L7_DOT3AD_COMPONENT_ID << 16) | 0x011a)
#define L7_PLATFORM_CTR_LAG_TX_RX_4096_9216             ((L7_DOT3AD_COMPONENT_ID << 16) | 0x011b)
#define L7_PLATFORM_CTR_LAG_ETHER_STATS_DROP_EVENTS     ((L7_DOT3AD_COMPONENT_ID << 16) | 0x011c)
#define L7_PLATFORM_CTR_LAG_SNMPIFOUTDISCARD_FRAMES     ((L7_DOT3AD_COMPONENT_ID  << 16)| 0x011d)
#define L7_PLATFORM_CTR_LAG_SNMPIFINDISCARD_FRAMES      ((L7_DOT3AD_COMPONENT_ID  << 16)| 0x011e)

#define L7_PLATFORM_CTR_LAG_NUM_MEMBERS             ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0200)
#define L7_PLATFORM_CTR_LAG_NUM_ACTIVE_MEMBERS      ((L7_DOT3AD_COMPONENT_ID << 16) | 0x0201)

/* VLAN Statistics */
#define L7_PLATFORM_CTR_DYNAMIC_VLAN_COUNT          ((L7_DOT1Q_COMPONENT_ID << 16) | 0x0000)
#define L7_PLATFORM_CTR_MOST_VLAN_COUNT             ((L7_DOT1Q_COMPONENT_ID << 16) | 0x0001)
#define L7_PLATFORM_CTR_FAILED_VLAN_CREATIONS       ((L7_DOT1Q_COMPONENT_ID << 16) | 0x0002)
#define L7_PLATFORM_CTR_VLAN_DELETION_COUNT         ((L7_DOT1Q_COMPONENT_ID << 16) | 0x0003)

/* GVRP counters*/
#define L7_PLATFORM_CTR_GVRP_PDU_RCV_COUNT          (L7_GARP_COMPONENT_ID << 16) | 0x0001
#define L7_PLATFORM_CTR_GVRP_PDU_SND_COUNT          (L7_GARP_COMPONENT_ID << 16) | 0x0002
#define L7_PLATFORM_CTR_GVRP_FAILED_REGISTRATIONS   (L7_GARP_COMPONENT_ID << 16) | 0x0003

/* GMRP counters*/
#define L7_PLATFORM_CTR_GMRP_PDU_RCV_COUNT          ((L7_GARP_COMPONENT_ID << 16) | 0x0004)
#define L7_PLATFORM_CTR_GMRP_PDU_SND_COUNT          ((L7_GARP_COMPONENT_ID << 16) | 0x0005)
#define L7_PLATFORM_CTR_GMRP_FAILED_REGISTRATIONS   ((L7_GARP_COMPONENT_ID << 16) | 0x0006)
/* dot1d counters - unused*/
#define L7_PLATFORM_CTR_BPDU_RCV_COUNT              ((L7_RESERVED_3_COMPONENT_ID << 16) | 0x0001)
#define L7_PLATFORM_CTR_BPDU_SND_COUNT              ((L7_RESERVED_3_COMPONENT_ID << 16) | 0x0002)
#define L7_PLATFORM_CTR_BPDU_RCV_DISCARD_COUNT      ((L7_RESERVED_3_COMPONENT_ID << 16) | 0x0003)
#define L7_PLATFORM_CTR_BPDU_SND_DISCARD_COUNT      ((L7_RESERVED_3_COMPONENT_ID << 16) | 0x0004)

/* VLAN Ingress Statistics */

#define L7_PLATFORM_CTR_LOCAL_TRAFFIC_DISCARDS              L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_RX_PAUSE_FRAMES                     ((L7_DOT1Q_COMPONENT_ID << 16) | 0x0005)
#define L7_PLATFORM_CTR_UNACCEPTABLE_FRAME_TYPE_DISCARDS    ((L7_DOT1Q_COMPONENT_ID << 16) | 0x0006)

#define L7_PLATFORM_CTR_INGRESS_FILTER_DISCARDS             L7_PLATFORM_CTR_NOT_SUPPORTED 
#define L7_PLATFORM_CTR_INGRESS_VLAN_VIABLE_DISCARDS        L7_PLATFORM_CTR_NOT_SUPPORTED 

#define L7_PLATFORM_CTR_MULTICAST_TREE_VIABLE_DISCARDS      L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_RESERVED_ADDRESS_DISCARDS           L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_BCAST_STORM_RECOVERY_DISCARDS       L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_CFI_DISCARDS                        L7_PLATFORM_CTR_NOT_SUPPORTED
#define L7_PLATFORM_CTR_UPSTREAM_THRESHOLD_DISCARDS         L7_PLATFORM_CTR_NOT_SUPPORTED

/* VLAN Egress Statistics */ 
#define L7_PLATFORM_CTR_TX_PAUSE_FRAMES                     ((L7_DOT1Q_COMPONENT_ID << 16) | 0x000e)
#define L7_PLATFORM_CTR_PORT_MEMBERSHIP_DISCARDS            L7_PLATFORM_CTR_NOT_SUPPORTED

#define L7_PLATFORM_CTR_EGRESS_VLAN_VIABLE_DISCARDS         L7_PLATFORM_CTR_NOT_SUPPORTED                                                

/* DTL Discards Statistics*/
#define L7_PLATFORM_CTR_RX_DISCARDS                         ((L7_DTL_COMPONENT_ID << 16) | 0x0001)
#define L7_PLATFORM_CTR_TX_DISCARDS                         ((L7_DTL_COMPONENT_ID << 16) | 0x0002)

/* Policy Statistics */
#define L7_PLATFORM_CTR_RX_TOTAL_DISCARDS                   ((L7_POLICY_COMPONENT_ID << 16) | 0x0000)

/* LIF per vlan per interface stats */
#define L7_PLATFORM_CTR_IN_FRAMES                           0x80000001  /* the following counters are  */
#define L7_PLATFORM_CTR_IN_DISCARD_FRAMES                   0x80000002  /* per vlan per inetrface      */
#define L7_PLATFORM_CTR_OUT_FRAMES                          0x80000004  /* the map shall be as follow: */
/*  ---- ---- ---- ---- -------- --------  */

/*-------------------------------------*/
/* TRAFFIC SERVICES FLEX PACKAGE STATS */
/*-------------------------------------*/

/* MPLS Application Statistics */

#define L7_PLATFORM_CTR_MPLS_FTN_MATCHED_PACKETS           ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0101)
#define L7_PLATFORM_CTR_MPLS_FTN_MATCHED_OCTETS            ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0102)
#define L7_PLATFORM_CTR_MPLS_FTN_MATCHED_HC_PACKETS        ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0103)
#define L7_PLATFORM_CTR_MPLS_FTN_MATCHED_HC_OCTETS         ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0104)

#define L7_PLATFORM_CTR_MPLS_LSR_INTF_IN_LABELS_USED       ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0201)
#define L7_PLATFORM_CTR_MPLS_LSR_INTF_FAILED_LABEL_LOOKUP  ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0202)
#define L7_PLATFORM_CTR_MPLS_LSR_INTF_OUT_LABELS_USED      ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0203)
#define L7_PLATFORM_CTR_MPLS_LSR_INTF_OUT_FRAGMENTS        ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0204)

#define L7_PLATFORM_CTR_MPLS_LSR_IN_SEG_OCTETS             ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0301)     
#define L7_PLATFORM_CTR_MPLS_LSR_IN_SEG_PACKETS            ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0302)     
#define L7_PLATFORM_CTR_MPLS_LSR_IN_SEG_ERRORS             ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0303)     
#define L7_PLATFORM_CTR_MPLS_LSR_IN_SEG_DISCARDS           ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0304)     
#define L7_PLATFORM_CTR_MPLS_LSR_IN_SEG_HC_OCTETS          ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0305)     
#define L7_PLATFORM_CTR_MPLS_LSR_IN_SEG_PERF_DISCONTINUITY_TIME  ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0306)

#define L7_PLATFORM_CTR_MPLS_LSR_OUT_SEG_OCTETS            ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0401)
#define L7_PLATFORM_CTR_MPLS_LSR_OUT_SEG_PACKETS           ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0402)
#define L7_PLATFORM_CTR_MPLS_LSR_OUT_SEG_ERRORS            ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0403)
#define L7_PLATFORM_CTR_MPLS_LSR_OUT_SEG_DISCARDS          ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0404)
#define L7_PLATFORM_CTR_MPLS_LSR_OUT_SEG_HC_OCTETS         ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0405)
#define L7_PLATFORM_CTR_MPLS_LSR_OUT_SEG_PERF_DISCONTINUITY_TIME  ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0406)

#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_PATH                ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0501)
#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_RESV                ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0502)
#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_PATH_ERR            ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0503)
#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_RESV_ERR            ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0504)
#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_PATH_TEAR           ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0505)
#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_RESV_TEAR           ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0506)
#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_RESV_CONF           ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0507)
#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_BUNDLE              ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0508)
#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_ACK                 ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0509)
#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_HELLO               ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x050A)
#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_SREFRESH            ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x050B)
#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_FR_NOTIFICATION     ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x050C)
#define L7_PLATFORM_CTR_MPLS_RSVP_SENT_GEN_NOTIFY          ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x050D)

#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_PATH                ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0601)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_RESV                ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0602)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_PATH_ERR            ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0603)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_RESV_ERR            ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0604)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_PATH_TEAR           ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0605)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_RESV_TEAR           ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0606)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_RESV_CONF           ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0607)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_BUNDLE              ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0608)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_ACK                 ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0609)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_HELLO               ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x060A)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_SREFRESH            ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x060B)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_FR_NOTIFICATION     ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x060C)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_GEN_NOTIFY          ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x060D)
#define L7_PLATFORM_CTR_MPLS_RSVP_RCVD_BAD_PACKET          ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x060E)

/* MPLS Driver-Based Statistics */

#define L7_PLATFORM_CTR_MPLS_DRVR_INTF_IN_FAILED_LOOKUP    ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F01)
#define L7_PLATFORM_CTR_MPLS_DRVR_INTF_OUT_FRAGMENTED      ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F02)

#define L7_PLATFORM_CTR_MPLS_DRVR_FTN_MATCHED_PACKETS      ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F11)
#define L7_PLATFORM_CTR_MPLS_DRVR_FTN_MATCHED_OCTETS       ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F12)
#define L7_PLATFORM_CTR_MPLS_DRVR_FTN_IN_SEG_OCTETS        ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F13)
#define L7_PLATFORM_CTR_MPLS_DRVR_FTN_IN_SEG_PACKETS       ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F14)
#define L7_PLATFORM_CTR_MPLS_DRVR_FTN_IN_SEG_ERRORS        ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F15)
#define L7_PLATFORM_CTR_MPLS_DRVR_FTN_IN_SEG_DISCARDS      ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F16)
#define L7_PLATFORM_CTR_MPLS_DRVR_FTN_OUT_SEG_OCTETS       ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F17)
#define L7_PLATFORM_CTR_MPLS_DRVR_FTN_OUT_SEG_PACKETS      ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F18)
#define L7_PLATFORM_CTR_MPLS_DRVR_FTN_OUT_SEG_ERRORS       ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F19)
#define L7_PLATFORM_CTR_MPLS_DRVR_FTN_OUT_SEG_DISCARDS     ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F1A)

#define L7_PLATFORM_CTR_MPLS_DRVR_ILM_IN_SEG_OCTETS        ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F21)
#define L7_PLATFORM_CTR_MPLS_DRVR_ILM_IN_SEG_PACKETS       ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F22)
#define L7_PLATFORM_CTR_MPLS_DRVR_ILM_IN_SEG_ERRORS        ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F23)
#define L7_PLATFORM_CTR_MPLS_DRVR_ILM_IN_SEG_DISCARDS      ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F24)
#define L7_PLATFORM_CTR_MPLS_DRVR_ILM_OUT_SEG_OCTETS       ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F25)
#define L7_PLATFORM_CTR_MPLS_DRVR_ILM_OUT_SEG_PACKETS      ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F26)
#define L7_PLATFORM_CTR_MPLS_DRVR_ILM_OUT_SEG_ERRORS       ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F27)
#define L7_PLATFORM_CTR_MPLS_DRVR_ILM_OUT_SEG_DISCARDS     ((L7_FLEX_MPLS_MAP_COMPONENT_ID << 16) | 0x0F28)

/* traffic Class counters */
#define L7_PLATFORM_CTR_TC_ACCEPT_PACKET_COUNT            (L7_PLATFORM_CTR_NOT_SUPPORTED)

/* Diffserv counters */                                                                                         
#define L7_PLATFORM_CTR_DIFFSERV_POLICY_PERF_IN_OFFERED_OCTETS          L7_PLATFORM_CTR_NOT_SUPPORTED              /*0x0000*/
#define L7_PLATFORM_CTR_DIFFSERV_POLICY_PERF_IN_OFFERED_PACKETS         ((L7_FLEX_QOS_DIFFSERV_COMPONENT_ID << 16) | 0x0001)
#define L7_PLATFORM_CTR_DIFFSERV_POLICY_PERF_IN_DISCARDED_OCTETS        L7_PLATFORM_CTR_NOT_SUPPORTED              /*0x0002*/
#define L7_PLATFORM_CTR_DIFFSERV_POLICY_PERF_IN_DISCARDED_PACKETS       ((L7_FLEX_QOS_DIFFSERV_COMPONENT_ID << 16) | 0x0003)
                                 
#define L7_PLATFORM_CTR_DIFFSERV_POLICY_PERF_OUT_OFFERED_OCTETS         L7_PLATFORM_CTR_NOT_SUPPORTED              /*0x0004*/
#define L7_PLATFORM_CTR_DIFFSERV_POLICY_PERF_OUT_OFFERED_PACKETS        (cnfgrIsFeaturePresent(L7_FLEX_QOS_DIFFSERV_COMPONENT_ID,\
                                                                                               L7_DIFFSERV_SERVICE_OUT_SLOTPORT_FEATURE_ID) ? \
                                                                         ((L7_FLEX_QOS_DIFFSERV_COMPONENT_ID << 16) | 0x0005) :\
                                                                          L7_PLATFORM_CTR_NOT_SUPPORTED)            /*0x0005*/
#define L7_PLATFORM_CTR_DIFFSERV_POLICY_PERF_OUT_DISCARDED_OCTETS       L7_PLATFORM_CTR_NOT_SUPPORTED              /*0x0006*/
#define L7_PLATFORM_CTR_DIFFSERV_POLICY_PERF_OUT_DISCARDED_PACKETS      L7_PLATFORM_CTR_NOT_SUPPORTED              /*0x0007*/

#define L7_PLATFORM_CTR_DIFFSERV_SERVICE_PERF_OFFERED_OCTETS            L7_PLATFORM_CTR_NOT_SUPPORTED              /*0x0008*/
#define L7_PLATFORM_CTR_DIFFSERV_SERVICE_PERF_OFFERED_PACKETS           L7_PLATFORM_CTR_NOT_SUPPORTED              /*0x0009*/
#define L7_PLATFORM_CTR_DIFFSERV_SERVICE_PERF_DISCARDED_OCTETS          L7_PLATFORM_CTR_NOT_SUPPORTED              /*0x000A*/
#define L7_PLATFORM_CTR_DIFFSERV_SERVICE_PERF_DISCARDED_PACKETS         L7_PLATFORM_CTR_NOT_SUPPORTED              /*0x000B*/
#define L7_PLATFORM_CTR_DIFFSERV_SERVICE_PERF_SENT_OCTETS               L7_PLATFORM_CTR_NOT_SUPPORTED              /*0x000C*/
#define L7_PLATFORM_CTR_DIFFSERV_SERVICE_PERF_SENT_PACKETS              L7_PLATFORM_CTR_NOT_SUPPORTED              /*0x000D*/


/*--------------*/
/* 802.1X STATS */
/*--------------*/

/* Authenticator Stats (9.4.2) */
#define L7_PLATFORM_CTR_DOT1X_AUTH_EAPOL_FRAMES_RX                        (L7_DOT1X_COMPONENT_ID << 16) | 0x0001
#define L7_PLATFORM_CTR_DOT1X_AUTH_EAPOL_FRAMES_TX                        (L7_DOT1X_COMPONENT_ID << 16) | 0x0002
#define L7_PLATFORM_CTR_DOT1X_AUTH_EAPOL_START_FRAMES_RX                  (L7_DOT1X_COMPONENT_ID << 16) | 0x0003
#define L7_PLATFORM_CTR_DOT1X_AUTH_EAPOL_LOGOFF_FRAMES_RX                 (L7_DOT1X_COMPONENT_ID << 16) | 0x0004
#define L7_PLATFORM_CTR_DOT1X_AUTH_EAP_RESP_ID_FRAMES_RX                  (L7_DOT1X_COMPONENT_ID << 16) | 0x0005
#define L7_PLATFORM_CTR_DOT1X_AUTH_EAP_RESPONSE_FRAMES_RX                 (L7_DOT1X_COMPONENT_ID << 16) | 0x0006
#define L7_PLATFORM_CTR_DOT1X_AUTH_EAP_REQ_ID_FRAMES_TX                   (L7_DOT1X_COMPONENT_ID << 16) | 0x0007
#define L7_PLATFORM_CTR_DOT1X_AUTH_EAP_REQ_FRAMES_TX                      (L7_DOT1X_COMPONENT_ID << 16) | 0x0008
#define L7_PLATFORM_CTR_DOT1X_AUTH_INVALID_EAPOL_FRAMES_RX                (L7_DOT1X_COMPONENT_ID << 16) | 0x0009
#define L7_PLATFORM_CTR_DOT1X_AUTH_EAP_LENGTH_ERROR_FRAMES_RX             (L7_DOT1X_COMPONENT_ID << 16) | 0x000a

/* Authenticator Diagnostics (9.4.3) */
#define L7_PLATFORM_CTR_DOT1X_AUTH_ENTERS_CONNECTING                      (L7_DOT1X_COMPONENT_ID << 16) | 0x000b
#define L7_PLATFORM_CTR_DOT1X_AUTH_LOGOFFS_WHILE_CONNECTING               (L7_DOT1X_COMPONENT_ID << 16) | 0x000c
#define L7_PLATFORM_CTR_DOT1X_AUTH_ENTERS_AUTHENTICATING                  (L7_DOT1X_COMPONENT_ID << 16) | 0x000d
#define L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_SUCCESS_WHILE_AUTHENTICATING      (L7_DOT1X_COMPONENT_ID << 16) | 0x000e
#define L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_TIMEOUTS_WHILE_AUTHENTICATING     (L7_DOT1X_COMPONENT_ID << 16) | 0x000f
#define L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_FAIL_WHILE_AUTHENTICATING         (L7_DOT1X_COMPONENT_ID << 16) | 0x0010
#define L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_REAUTHS_WHILE_AUTHENTICATING      (L7_DOT1X_COMPONENT_ID << 16) | 0x0011
#define L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_EAP_STARTS_WHILE_AUTHENTICATING   (L7_DOT1X_COMPONENT_ID << 16) | 0x0012
#define L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_EAP_LOGOFF_WHILE_AUTHENTICATING   (L7_DOT1X_COMPONENT_ID << 16) | 0x0013
#define L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_REAUTHS_WHILE_AUTHENTICATED       (L7_DOT1X_COMPONENT_ID << 16) | 0x0014
#define L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_EAP_STARTS_WHILE_AUTHENTICATED    (L7_DOT1X_COMPONENT_ID << 16) | 0x0015
#define L7_PLATFORM_CTR_DOT1X_AUTH_AUTH_EAP_LOGOFF_WHILE_AUTHENTICATED    (L7_DOT1X_COMPONENT_ID << 16) | 0x0016
#define L7_PLATFORM_CTR_DOT1X_AUTH_BACKEND_RESPONSES                      (L7_DOT1X_COMPONENT_ID << 16) | 0x0017
#define L7_PLATFORM_CTR_DOT1X_AUTH_BACKEND_ACCESS_CHALLENGES_COUNT        (L7_DOT1X_COMPONENT_ID << 16) | 0x0018
#define L7_PLATFORM_CTR_DOT1X_AUTH_BACKEND_OTHER_REQUESTS_TO_SUPPLICANT   (L7_DOT1X_COMPONENT_ID << 16) | 0x0019
#define L7_PLATFORM_CTR_DOT1X_AUTH_BACKEND_NON_NAK_RESPONSES_FROM_SUPPLICANT (L7_DOT1X_COMPONENT_ID << 16) | 0x001a
#define L7_PLATFORM_CTR_DOT1X_AUTH_BACKEND_AUTH_SUCCESSES                 (L7_DOT1X_COMPONENT_ID << 16) | 0x001b
#define L7_PLATFORM_CTR_DOT1X_AUTH_BACKEND_AUTH_FAILS                     (L7_DOT1X_COMPONENT_ID << 16) | 0x001c

#endif
