PHONY: all clean cleanall

help h:
	@echo ""
	@echo "Makefile Help "
	@echo ""
	@echo " make all     "
	@echo " make clean   "
	@echo " make cleanall"
	@echo ""

all clean cleanall:
	@$(MAKE) -f fp.cli-cxo640g.make $@
	@$(MAKE) -f fp.cli-cxo160g.make $@
	@$(MAKE) -f fp.cli-ta48ge.make $@
	@$(MAKE) -f fp.cli-tg16g.make $@
	@$(MAKE) -f fp.cli-tg16gf.make $@
	@$(MAKE) -f fp.cli-olt1t0.make $@
	@$(MAKE) -f fp.cli-olt1t0f.make $@
	@$(MAKE) -f fp.cli-tt04sxg.make $@

