/** \file dnx/swstate/auto_generated/diagnostic/dnx_mirror_diagnostic.h
 *
 * sw state functions declarations
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 */
/*
 * $Copyright: (c) 2018 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */

#ifndef __DNX_MIRROR_DIAGNOSTIC_H__
#define __DNX_MIRROR_DIAGNOSTIC_H__

#include <soc/dnxc/swstate/dnxc_sw_state_h_includes.h>
#include <soc/dnxc/swstate/dnx_sw_state_dump.h>
#include <soc/dnxc/swstate/dnx_sw_state_size.h>
#include <soc/dnxc/swstate/dnx_sw_state_diagnostic_operation_counters.h>
#include <soc/dnx/swstate/auto_generated/types/dnx_mirror_types.h>
#include <bcm_int/dnx/algo/port/algo_port_mgmt.h>
#include <bcm_int/dnx/mirror/mirror.h>
#include <bcm_int/dnx/mirror/mirror_rcy.h>
#include <soc/dnx/dnx_data/auto_generated/dnx_data_device.h>
#include <soc/dnx/dnx_data/auto_generated/dnx_data_port.h>
#include <soc/dnxc/swstate/types/sw_state_pbmp.h>
#include <soc/dnxc/swstate/types/sw_state_res_mngr.h>
#include <soc/dnxc/swstate/types/sw_state_template_mngr.h>
#if defined(DNX_SW_STATE_DIAGNOSTIC)
typedef enum {
    DNX_MIRROR_DB_INFO,
    DNX_MIRROR_DB_CHANNEL_TO_EGRESS_IF_INFO,
    DNX_MIRROR_DB_EGRESS_MIRROR_PRIORITY_INFO,
    DNX_MIRROR_DB_SNIF_INGRESS_PROFILES_MIRROR_INFO,
    DNX_MIRROR_DB_SNIF_INGRESS_PROFILES_SNOOP_INFO,
    DNX_MIRROR_DB_SNIF_INGRESS_PROFILES_STAT_SAMPLING_INFO,
    DNX_MIRROR_DB_SNIF_EGRESS_VLAN_PROFILES_MIRROR_INFO,
    DNX_MIRROR_DB_SNIF_INGRESS_VLAN_PROFILES_MIRROR_INFO,
    DNX_MIRROR_DB_INFO_NOF_ENTRIES
} sw_state_dnx_mirror_db_layout_e;


extern dnx_sw_state_diagnostic_info_t dnx_mirror_db_info[SOC_MAX_NUM_DEVICES][DNX_MIRROR_DB_INFO_NOF_ENTRIES];

extern const char* dnx_mirror_db_layout_str[DNX_MIRROR_DB_INFO_NOF_ENTRIES];
int dnx_mirror_db_dump(
    int unit);

int dnx_mirror_db_channel_to_egress_if_dump(
    int unit, int channel_to_egress_if_idx_0, int channel_to_egress_if_idx_1);

int dnx_mirror_db_egress_mirror_priority_dump(
    int unit, int egress_mirror_priority_idx_0);

int dnx_mirror_db_snif_ingress_profiles_mirror_dump(
    int unit);

int dnx_mirror_db_snif_ingress_profiles_snoop_dump(
    int unit);

int dnx_mirror_db_snif_ingress_profiles_stat_sampling_dump(
    int unit);

int dnx_mirror_db_snif_egress_vlan_profiles_mirror_dump(
    int unit);

int dnx_mirror_db_snif_ingress_vlan_profiles_mirror_dump(
    int unit);

#endif /* DNX_SW_STATE_DIAGNOSTIC */

#endif /* __DNX_MIRROR_DIAGNOSTIC_H__ */
