#
# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/cprimod/cpms

include ${SDK}/make/Make.config

lib = libsoc_cprimod_cpms

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
