#
# $Id: Makefile,v 1.2 Broadcom SDK $
#
# $Copyright: Copyright 2015 Broadcom Corporation.
# This program is the proprietary software of Broadcom Corporation
# and/or its licensors, and may only be used, duplicated, modified
# or distributed pursuant to the terms and conditions of a separate,
# written license agreement executed between you and Broadcom
# (an "Authorized License").  Except as set forth in an Authorized
# License, Broadcom grants no license (express or implied), right
# to use, or waiver of any kind with respect to the Software, and
# Broadcom expressly reserves all rights in and to the Software
# and all intellectual property rights therein.  IF YOU HAVE
# NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
# IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
# ALL USE OF THE SOFTWARE.  
#  
# Except as expressly set forth in the Authorized License,
#  
# 1.     This program, including its structure, sequence and organization,
# constitutes the valuable trade secrets of Broadcom, and you shall use
# all reasonable efforts to protect the confidentiality thereof,
# and to use this information only in connection with your use of
# Broadcom integrated circuit products.
#  
# 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
# PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
# REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
# OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
# DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
# NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
# ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
# CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
# OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
# 
# 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
# BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
# INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
# ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
# TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
# THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
# WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
# ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$

# make -f Makefile -C $(PATH_TO_KERNEL) M=$(CURR_DIR) CROSS_COMPILE=$(CROSS_COMPILER) $(EXTRA_FLAGS) V=1 


# /tools/oss/packages/x86_64-rhel5/make/default/bin/make -C /projects/ntsw-sw/linux/wrslinux_2.0/gto/glibc_std/build/linux-2.6.21-standard CROSS_COMPILE=powerpc-wrs-linux-gnu-ppc_e500v2-glibc_std- M=/projects/NTSW_SW_USRS/eliad/cvs/sdk/systems/linux/kernel/modules/bcm-pcp-net modules


CURR_DIR= $(shell pwd)
#PATH_TO_KERNEL=/projects/ntsw-sw/linux/wrslinux_2.0/gto/glibc_std/build/linux-2.6.21-standard
PATH_TO_KERNEL=/projects/ntsw-tools/linux/wrslinux_2.0/gto/glibc_std/build/linux-2.6.21-standard
CROSS_COMPILER=/projects/ntsw-sw3/linux/wrslinux_2.0/gto/glibc_std/host-cross/powerpc-wrs-linux-gnu/x86-linux2/powerpc-wrs-linux-gnu-ppc_e500v2-glibc_std-

EXTRA_FLAGS += -I$(PATH_TO_KERNEL)/arch/ppc/
EXTRA_FLAGS += ARCH=ppc


all: modls libs bins
modls:
bins:



MAKE_CMD = make -f Makefile -C $(PATH_TO_KERNEL) M=$(CURR_DIR) \
  CROSS_COMPILE=$(CROSS_COMPILER) $(EXTRA_FLAGS) V=1\
  
  
libs:
	$(MAKE_CMD) modules

clean_all:
	$(MAKE_CMD) clean



obj-m := bcm-pcp-dma.o
#bcm_pcp_dma-objs := bcm-pcp-dma.o
