# $Id: Makefile Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/appl/diag/esw/techsupport/ledup

include ${SDK}/make/Make.config

lib = libtsledup

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
