# $Id: $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for streamlined packet I/O drivers
#

include ${SDK}/make/Make.config

subdirs := cmicx
include ${SDK}/make/Make.subdirs
