#
# $Id: Makefile,v 1.0 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/cosq/global_voq

include ${SDK}/make/Make.config

#subdirs = port

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxcosqglobalvoq

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend


