#
#
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dnx/arr

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/soc/dnx

subdirs = auto_generated

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxarr

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
