#
# $Id: Makefile,v 1.3 Broadcom SDK $
#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dpp/QAX/PEM

include ${SDK}/make/Make.config

lib = libsoc_dpp_pem

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
