#
# $Id$
# $Copyright: (c) 2017 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dpp subdirectory
#

LOCALDIR = src/soc/dnxc/swstate/auto_generated

include ${SDK}/make/Make.config

#
# Take the subdirs 'access diagnostic'
#
subdirs = access diagnostic

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxcswstate_auto_generated

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

