#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dnxf/dnxf_data subdirectory
#

LOCALDIR = src/soc/dnxf/dnxf_data

include ${SDK}/make/Make.config

lib = libsoc_dnxfdnxfdata

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

