#
# $Id: Makefile Exp $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/ctest/dnx/kaps

include ${SDK}/make/Make.config

lib = libctest_dnxkaps

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend


