#
# $Id: Makefile $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/appl/diag/dnx/pp

include ${SDK}/make/Make.config

subdirs+= kleap
include ${SDK}/make/Make.subdirs

lib = libdiag_dnxpp

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend


