#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
LOCALDIR = src/appl/ctest/dnxf

include ${SDK}/make/Make.config

lib = libctest_dnxf

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
