/*********************************************************************
*
* (C) Copyright Broadcom Corporation 2006-2007
*
**********************************************************************
*                                                                     
* @filename   src/nls/web/switching/strlib_switching_web.c                                                      
*                                                                     
* @purpose    Strings Library                                                      
*                                                                     
* @component  Common Strings Library                                                      
*                                                                     
* @comments   none                                                    
*                                                                     
* @create     01/10/2007                                                      
*                                                                     
* @author     Rama Sasthri, Kristipati                                
*                                                                     
* @end                                                                
*                                                                     
*********************************************************************/

#include "strlib_switching_web.h"
#include "usmdb_dot1q_api.h"

L7_char8 *pStrInfo_switching_Days = "%d Days %02d:%02d:%02d";
L7_char8 *pStrErr_switching_FieldIeeeMacVlan = "%s requires an 8 byte MAC address in form 00:01:01:23:45:67:89:AB, where the first 2 bytes represent a VLAN ID. The VLAN ID can be 0.";
L7_char8 *pStrErr_switching_AdminModeGet = "%s.Cannot obtain IGMP snooping Admin Mode.";
L7_char8 *pStrErr_switching_AdminModeDsbl = "%s.IGMP snooping is not enabled on switch.";
L7_char8 *pStrInfo_switching_0Auto = "0 = Auto";
L7_char8 *pStrInfo_switching_Dot1pPriMapping = "802.1p Priority Mapping";
L7_char8 *pStrInfo_switching_BrBNumOfDynMacAddresLearnedB = "<br><b>Number of Dynamic MAC addresses learned:</b> %d";
L7_char8 *pStrInfo_switching_AcceptableFrameTypes = "Acceptable Frame Types";
L7_char8 *pStrInfo_switching_ActivePorts = "Active Ports";
L7_char8 *pStrInfo_switching_AdminEdgePort = "Admin Edge Port";
L7_char8 *pStrInfo_switching_Ageouts = "Ageouts";
L7_char8 *pStrInfo_switching_AreYouSureYouWishToResetAllVlanCfg = "Are you sure you wish to reset all VLAN configuration?";
L7_char8 *pStrInfo_switching_AtLeastOneVlanNowAssociatedWithInstWasPreviouslyAssociatedWithAnotherInst = "At least one VLAN now associated with this instance was previously associated with another instance";
L7_char8 *pStrInfo_switching_BpduFilter = "BPDU Filter";
L7_char8 *pStrInfo_switching_BpduFlood = "BPDU Flood";
L7_char8 *pStrInfo_switching_BpduGuardEffect = "BPDU Guard Effect";
L7_char8 *pStrInfo_switching_BpduGuard = "BPDU Guard";
L7_char8 *pStrInfo_switching_BpduMigrationCheck = "BPDU Migration Check";
L7_char8 *pStrInfo_switching_BridgeForwardDelaySecs = "Bridge Forward Delay (secs)";
L7_char8 *pStrInfo_switching_BridgeHelloTimeSecs = "Bridge Hello Time (secs)";
L7_char8 *pStrInfo_switching_BridgeMaxAgeSecs = "Bridge Max Age (secs)";
L7_char8 *pStrInfo_switching_BridgeParamsCond2ForwardDelay1MaxAge2HelloTime1Failed = "Bridge parameters condition 2*(forward_delay-1)>=max_age>=2*(hello_time+1) Failed";
L7_char8 *pStrInfo_switching_CstCfgStatus = "CST Configuration/Status";
L7_char8 *pStrInfo_switching_CstPathCost_1 = "CST Path Cost";
L7_char8 *pStrInfo_switching_ChassisId_1 = "Chassis ID";
L7_char8 *pStrInfo_switching_ChassisIdSubtype_1 = "Chassis ID Subtype";
L7_char8 *pStrInfo_switching_ClrEntries = "Clear Entries";
L7_char8 *pStrInfo_switching_CfguredPorts = "Configured Ports";
L7_char8 *pStrInfo_switching_CreateFilter = "Create Filter";
L7_char8 *pStrInfo_switching_CreateNewGrp = "Create New Group";
L7_char8 *pStrErr_switching_CreatedLagAsStaticCantSetToDyn = "Created lag as static.Could not set %s to dynamic.%s";
L7_char8 *pStrInfo_switching_DhcpFilteringCfg = "DHCP Filtering Configuration";
L7_char8 *pStrInfo_switching_DhcpFilteringIntfCfg = "DHCP Filtering Interface Configuration";
L7_char8 *pStrInfo_switching_DhcpFilteringIntfSummary = "DHCP Filtering Interface Summary";
L7_char8 *pStrInfo_switching_DataFramesForwardedByCpu = "Data Frames Forwarded by the CPU";
L7_char8 *pStrInfo_switching_DelGrp = "Delete Group";
L7_char8 *pStrInfo_switching_DesignatedCost = "Designated Cost";
L7_char8 *pStrInfo_switching_DesignatedPort_1 = "Designated Port";
L7_char8 *pStrInfo_switching_DstPortMask = "Destination Port Mask";
L7_char8 *pStrInfo_switching_DstPortMbrs = "Destination Port Members";
L7_char8 *pStrInfo_switching_HashModeDaVlan = "Dest MAC, VLAN, EType, incoming port";
L7_char8 *pStrInfo_switching_HashModeDa = "Dest MAC";
L7_char8 *pStrInfo_switching_HashModeDestIP = "Dest IP and Dest TCP/UDP Port fields";
L7_char8 *pStrInfo_switching_DynLimit = "Dynamic Limit";
L7_char8 *pStrInfo_switching_Errs = "Errors";
L7_char8 *pStrInfo_switching_ExercisingFuncWillCauseAllVlanCfgParamsToBeResetToDeflVals = "Exercising this function will cause all VLAN configuration parameters to be reset to their default values.";
L7_char8 *pStrInfo_switching_Fid = "FID";
L7_char8 *pStrErr_switching_FailedToSetExternalPathCost = "Failed to Set External Path Cost";
L7_char8 *pStrErr_switching_FailedToSetHelloTimer = "Failed to Set Hello Timer";
L7_char8 *pStrErr_switching_FailedToAddAllMbrsToLagMbrLimitExceeded = "Failed to add all members to Port Channel. Member limit exceeded.";
L7_char8 *pStrErr_switching_FailedToAttachIntfToGrpidIntfAlreadyCfguredWithAnotherGrpUsingSameProto = "Failed to attach interface to GroupID. Interface already configured with another group using the same protocol.";
L7_char8 *pStrErr_switching_FailedToMove = "Failed to move %s to %s";
L7_char8 *pStrErr_switching_FailedToSetFor = "Failed to set %s for %s %d";
L7_char8 *pStrInfo_switching_FastLeaveAdminMode = "Fast Leave Admin Mode";
L7_char8 *pStrInfo_switching_FilterAlreadyExists = "Filter already exists";
L7_char8 *pStrInfo_switching_Force = "Force";
L7_char8 *pStrInfo_switching_ForceProtoVer = "Force Protocol Version";
L7_char8 *pStrInfo_switching_ForwardDelaySecs = "Forward Delay (secs)";
L7_char8 *pStrInfo_switching_Garp = "GARP";
L7_char8 *pStrInfo_switching_GarpPortCfg = "GARP Port Configuration";
L7_char8 *pStrInfo_switching_GarpStatus = "GARP Status";
L7_char8 *pStrInfo_switching_GarpSwitchCfg = "GARP Switch Configuration";
L7_char8 *pStrInfo_switching_GarpTimers = "GARP Timers";
L7_char8 *pStrInfo_switching_GmrpMode = "GMRP Mode";
L7_char8 *pStrInfo_switching_GvrpMode = "GVRP Mode";
L7_char8 *pStrInfo_switching_GvrpMustFirstBeEnbldOnSwitchBeforeYouCanPerformGarpCfgOnPortreIsAlsoUpToA10SecondDelayOnCfgIfYouHaveAlreadyEnbldGvrpOnSwitchTryGoingToPageAgain = "GVRP must first be enabled on the switch before you can perform Garp configuration on a port. There is also up to a 10 second delay on the configuration. If you have already enabled GVRP on the switch, try going to the page again.";
L7_char8 *pStrInfo_switching_GrpId = "Group ID";
L7_char8 *pStrInfo_switching_GrpMbrshipIntvlSecs = "Group Membership Interval (secs)";
L7_char8 *pStrInfo_switching_GrpName = "Group Name";
L7_char8 *pStrInfo_switching_HelloTimeSecs = "Hello Time (secs)";
L7_char8 *pStrInfo_switching_HelloTimerOutOfRange = "Hello Timer out of Range";
L7_char8 *pStrInfo_switching_IgmpSnooping = "IGMP Snooping";
L7_char8 *pStrInfo_switching_IgmpSnoopingGlobalCfgAndStatus = "IGMP Snooping Global Configuration and Status";
L7_char8 *pStrInfo_switching_IgmpSnoopingQuerierCfg = "IGMP Snooping Querier Configuration";
L7_char8 *pStrInfo_switching_IgmpSnoopingQuerierStatus = "IGMP Snooping Querier VLAN Status";
L7_char8 *pStrInfo_switching_IgmpSnoopingQuerierVlanCfg = "IGMP Snooping Querier VLAN Configuration";
L7_char8 *pStrInfo_switching_IgmpSnoopingQuerierVlanCfgSummary = "IGMP Snooping Querier VLAN Configuration Summary";
L7_char8 *pStrInfo_switching_IgmpSnoopingVlanCfg = "IGMP Snooping VLAN Configuration";
L7_char8 *pStrInfo_switching_IgmpSnoopingVlanStatus = "IGMP Snooping VLAN Status";
L7_char8 *pStrInfo_switching_IpSubnetBasedVlan = "IP Subnet-based VLAN";
L7_char8 *pStrInfo_switching_IpSubnetBasedVlanCfg = "IP Subnet-based VLAN Configuration";
L7_char8 *pStrInfo_switching_IpSubnetBasedVlanSummary = "IP Subnet-based VLAN Summary";
L7_char8 *pStrInfo_switching_IngressFiltering = "Ingress Filtering";
L7_char8 *pStrInfo_switching_IngressFilteringCfgured = "Ingress Filtering Configured";
L7_char8 *pStrInfo_switching_IngressFilteringCurrent = "Ingress Filtering Current";
L7_char8 *pStrInfo_switching_Intfs = "Interfaces";
L7_char8 *pStrErr_switching_CombinationOfValsForGrpMbrshipIntvlAndMaxRespTime = "Invalid combination of values for Group Membership Interval and Maximum Response Time.";
L7_char8 *pStrErr_switching_FmtInHelloTimer = "Invalid format in the Hello Timer";
L7_char8 *pStrErr_switching_FmtInExternalPathCost = "Invalid format in the external path cost";
L7_char8 *pStrInfo_switching_ItIsAlreadyCfguredWithAnotherGrpSWhichAreSharingPortsOfGrp = "It is already configured with another group(s) which are sharing ports of this group.";
L7_char8 *pStrInfo_switching_JoinTimerCentisecs = "Join Timer (centisecs)";
L7_char8 *pStrInfo_switching_LacpModeMustBeEnbldOnMbrPortsBeforeyCanBeAddedToALag = "LACP Mode must be enabled on member ports before they can be added to a Port Channel";
L7_char8 *pStrInfo_switching_LldpIntfSummary = "LLDP Interface Summary";
L7_char8 *pStrInfo_switching_LldpLocalDeviceInfo = "LLDP Local Device Information";
L7_char8 *pStrInfo_switching_LldpRemoteDeviceInfo = "LLDP Remote Device Information";
L7_char8 *pStrInfo_switching_LldpStats = "LLDP Statistics";
/* dot3ah */
L7_char8 *pStrInfo_switching_Dot3ah="Enable/Disable DOT3AH for this interface";
L7_char8 *pStrInfo_switching_Dot3ahIntfSummary = "DOT3AH Interface Summary";
L7_char8 *pStrInfo_switching_Dot3ahLocalDeviceInfo = "DOT3AH Local Device Information";
L7_char8 *pStrInfo_switching_Dot3ahRemoteDeviceInfo = "DOT3AH Remote Device Information";
L7_char8 *pStrInfo_switching_Dot3ahLocalDeviceOui="Local OUI";
L7_char8 *pStrInfo_switching_Dot3ahLocalDeviceState="Local State";
L7_char8 *pStrInfo_switching_Dot3ahLocalDeviceMACAddr="Local MAC";
L7_char8 *pStrInfo_switching_Dot3ahRemoteDeviceMACAddr="Remote MAC";
L7_char8 *pStrInfo_switching_Dot3ahRemoteDeviceOui="Remote OUI";
L7_char8 *pStrInfo_switching_Dot3ahLocalDeviceVSInfo="Local VSI";
L7_char8 *pStrInfo_switching_Dot3ahRemoteDeviceVSInfo="Remote VSI";
L7_char8 *pStrInfo_switching_Dot3ahRemoteDeviceState="Remote State";
L7_char8 *pStrInfo_switching_Dot3ahStats = "DOT3AH Statistics";
L7_char8 *pStrInfo_switching_LanOamStats = "Lan OAM Statistics";
L7_char8 *pStrInfo_switching_Dot3ahStatus ="DOT3AH Status";
L7_char8 *pStrInfo_switching_Dot3ahIntfStatus ="DOT3AH Intf Status";
L7_char8 *pStrInfo_switching_Dot3ahLocalRevision="Local Revision";
L7_char8 *pStrInfo_switching_Dot3ahLocalMode="Local Mode";
L7_char8 *pStrInfo_switching_Dot3ahRemoteMode="Remote Mode";
L7_char8 *pStrInfo_switching_Dot3ahRemRevision="Remote Revision";
L7_char8 *pStrInfo_switching_Dot3ahTxNumOAMPDUS="Total Tx OAMPDUs";
L7_char8 *pStrInfo_switching_Dot3ahRxNumOAMPDUS="Total Rx OAMPDUs";
L7_char8 *pStrInfo_switching_Dot3ahTxNumErrOAMPDUS="Errored Tx OAMPDUs";
L7_char8 *pStrInfo_switching_Dot3ahRxNumErrOAMPDUS="Errored Rx OAMPDUs";
L7_char8 *pStrInfo_switching_Dot3ahNumTimesNodesAdded="Number Times Nodes Added";
L7_char8 *pStrInfo_switching_Dot3ahCurrNumNodes="Discovered Nodes";
L7_char8 *pStrInfo_switching_Dot3ahNumTimesNodesDeleted="Number Times Nodes Deleted";

L7_char8 *pStrInfo_switching_Dot3ahNumTxInfoPdu="INFO PDUs TX";
L7_char8 *pStrInfo_switching_Dot3ahNumTxRemLbPdu="RemLB PDUs TX";
L7_char8 *pStrInfo_switching_Dot3ahNumTxEventPdu="Event PDUs TX";
L7_char8 *pStrInfo_switching_Dot3ahNumTxOrgSpecPdu="Org Spec PDUs TX";

L7_char8 *pStrInfo_switching_Dot3ahNumRxInfoPdu="INFO PDUs RX";
L7_char8 *pStrInfo_switching_Dot3ahNumRxRemLbPdu="RemLB PDUs RX";
L7_char8 *pStrInfo_switching_Dot3ahNumRxEventPdu="Event PDUs RX";
L7_char8 *pStrInfo_switching_Dot3ahNumRxOrgSpecPdu="Org Spec PDUs RX";

L7_char8 *pStrInfo_switching_PortLANOAMLbMACMode="MAC";
L7_char8 *pStrInfo_switching_PortLANOAMLbPHYMode="PHY";
L7_char8 *pStrInfo_switching_PortLANOAMLbNoneType="NONE";
L7_char8 *pStrInfo_metro_ErrorFramePeriodThreshold="Error Frame Period Threshold";
L7_char8 *pStrInfo_metro_ErrorFrameSummThreshold="Error Frame-Summary Seconds Threshold";

/* dot3ah */
L7_char8 *pStrInfo_switching_LeaveAllTimerCentisecs = "Leave All Timer (centisecs)";
L7_char8 *pStrInfo_switching_LeaveTimerCentisecs = "Leave Timer (centisecs)";
L7_char8 *pStrInfo_switching_ListingOfAllPortsOnSwitch = "Listing of all Ports on the Switch";
L7_char8 *pStrInfo_switching_LoadBalance = "Load Balance";
L7_char8 *pStrInfo_switching_LoadBalanceVal = "Load Balance value";
L7_char8 *pStrInfo_switching_LocalIntf_1 = "Local Interface";
L7_char8 *pStrInfo_switching_LoopGuardError = "Loop Guard cannot be enabled on interface %d with enabled Root Guard";
L7_char8 *pStrInfo_switching_RemoteId = "Remote ID";
L7_char8 *pStrInfo_switching_MacBasedVlanCfg = "MAC-based VLAN Configuration";
L7_char8 *pStrInfo_switching_MacFilter = "MAC Filter";
L7_char8 *pStrInfo_switching_MacFilterCfg = "MAC Filter Configuration";
L7_char8 *pStrInfo_switching_MacFilterSummary = "MAC Filter Summary";
L7_char8 *pStrInfo_switching_MacBasedVlan = "MAC-based VLAN";
L7_char8 *pStrInfo_switching_MacBasedVlanSummary = "MAC-based VLAN Summary";
L7_char8 *pStrInfo_switching_MfdbGmrpTbl = "MFDB GMRP Table";
L7_char8 *pStrInfo_switching_MfdbIgmpSnoopingTbl = "MFDB IGMP Snooping Table";
L7_char8 *pStrInfo_switching_MfdbMldSnoopingTbl = "MFDB MLD Snooping Table";
L7_char8 *pStrInfo_switching_MldSnooping = "MLD Snooping";
L7_char8 *pStrInfo_switching_MldSnoopingGlobalCfgAndStatus = "MLD Snooping Global Configuration and Status";
L7_char8 *pStrInfo_switching_MldSnoopingQuerierCfg = "MLD Snooping Querier Configuration";
L7_char8 *pStrInfo_switching_MldSnoopingQuerierStatus = "MLD Snooping Querier Status";
L7_char8 *pStrInfo_switching_MldSnoopingQuerierVlanStatus = "MLD Snooping Querier VLAN Status";
L7_char8 *pStrInfo_switching_MldSnoopingQuerierVlanCfg = "MLD Snooping Querier VLAN Configuration";
L7_char8 *pStrInfo_switching_MldSnoopingQuerierVlanCfgSummary = "MLD Snooping Querier VLAN Configuration Summary";
L7_char8 *pStrInfo_switching_MldSnoopingVlanCfg = "MLD Snooping VLAN Configuration";
L7_char8 *pStrInfo_switching_MldSnoopingVlanStatus = "MLD Snooping VLAN Status";
L7_char8 *pStrInfo_switching_Mst = "MST";
L7_char8 *pStrInfo_switching_MakeStatic = "Make Static";
L7_char8 *pStrInfo_switching_MgmtAddr = "Management Address";
L7_char8 *pStrInfo_switching_MaxAgeSecs = "Max Age (secs)";
L7_char8 *pStrInfo_switching_MaxRespTimeSecs = "Max Response Time (secs)";
L7_char8 *pStrInfo_switching_MaxNumOfDynLagsAlreadyExists = "Maximum number of dynamic lags (%d) already exists";
L7_char8 *pStrInfo_switching_MaxNumOfLagsReached = "Maximum number of port-channels (%d) reached.";
L7_char8 *pStrInfo_switching_MbrOf = "Member of %d/%d";
L7_char8 *pStrInfo_switching_MbrOf_1 = "Member of %d/%d/%d";
L7_char8 *pStrInfo_switching_MbrshipConflicts = "Membership Conflicts";
L7_char8 *pStrInfo_switching_Missing18002 = "Missing 18002";
L7_char8 *pStrInfo_switching_Missing7522 = "Missing 7522";
L7_char8 *pStrInfo_switching_McastFwdDbaseStats = "Multicast Forwarding Database Statistics";
L7_char8 *pStrInfo_switching_McastFwdDbaseTbl = "Multicast Forwarding Database Table";
L7_char8 *pStrInfo_switching_McastRtr = "Multicast Router";
L7_char8 *pStrInfo_switching_McastRtrCfg = "Multicast Router Configuration";
L7_char8 *pStrInfo_switching_McastRtrPresentExpirationTimeSecs = "Multicast Router Present Expiration Time (secs)";
L7_char8 *pStrInfo_switching_McastRtrStats = "Multicast Router Status";
L7_char8 *pStrInfo_switching_McastRtrVlanCfg = "Multicast Router VLAN Configuration";
L7_char8 *pStrInfo_switching_McastRtrVlanStats = "Multicast Router VLAN Status";
L7_char8 *pStrInfo_switching_NewEntry = "New Entry";
L7_char8 *pStrInfo_switching_NoIpSubnetBasedVlanCfgured = "No IP Subnet-based VLAN Configured";
L7_char8 *pStrInfo_switching_NoMacBasedVlanCfgured = "No MAC-based VLAN Configured";
L7_char8 *pStrInfo_switching_NoMstsAvailable = "No MSTs Available";
L7_char8 *pStrWarn_switching_NoticeCouldTakeUpTo10SecondsToBecomeEffective = "Notice: This could take up to 10 seconds to become effective.";
L7_char8 *pStrInfo_switching_Notify = "Notify";
L7_char8 *pStrInfo_switching_NumOfDeclines = "Number of Declines";
L7_char8 *pStrInfo_switching_NumOfMalformedPkts = "Number of Malformed Packets";
L7_char8 *pStrInfo_switching_OperationalMaxRespTime = "Operational Max Response Time (secs)";
L7_char8 *pStrInfo_switching_OperationalVer = "Operational Version";
L7_char8 *pStrInfo_switching_OptionalTlvS = "Optional TLV(s)";
L7_char8 *pStrInfo_switching_PvidOfIntfToSpecifiedVlan = "PVID of interface to specified VLAN";
L7_char8 *pStrInfo_switching_Participation = "Participation";
L7_char8 *pStrInfo_switching_PointToPointMac = "Point-to-point MAC";
L7_char8 *pStrInfo_switching_PortIsAlreadyAMbrOfAnotherLag = "Port %s is already a member of another LAG.";
L7_char8 *pStrInfo_switching_LagCfg = "Port Channel Configuration";
L7_char8 *pStrInfo_switching_LagMbrs = "Port Channel Members";
L7_char8 *pStrInfo_switching_LagName = "Port Channel Name";
L7_char8 *pStrInfo_switching_LagStatus = "Port Channel Status";
L7_char8 *pStrInfo_switching_LagSwitchCfg = "Port Channel Switch Configuration";
L7_char8 *pStrInfo_switching_LagType = "Port Channel Type";
L7_char8 *pStrInfo_switching_PortGmrpMode = "Port GMRP Mode";
L7_char8 *pStrInfo_switching_PortGvrpMode = "Port GVRP Mode";
L7_char8 *pStrInfo_switching_PortId_2 = "Port ID";
L7_char8 *pStrInfo_switching_PortIdSubtype_1 = "Port ID Subtype";
L7_char8 *pStrInfo_switching_PortSecurityAdministration = "Port Security Administration";
L7_char8 *pStrInfo_switching_PortSecurityDynEntries = "Port Security Dynamic Entries";
L7_char8 *pStrInfo_switching_PortSecurityDynLimit = "Port Security Dynamic Limit";
L7_char8 *pStrInfo_switching_PortSecurityDynallyLearnedMacAddres = "Port Security Dynamically Learned MAC Addresses";
L7_char8 *pStrInfo_switching_PortSecurityGlobalAdminMode = "Port Security Global Admin Mode";
L7_char8 *pStrInfo_switching_PortSecurityIntfCfg = "Port Security Interface Configuration";
L7_char8 *pStrInfo_switching_PortSecurityStaticEntries = "Port Security Static Entries";
L7_char8 *pStrInfo_switching_PortSecurityStaticLimit = "Port Security Static Limit";
L7_char8 *pStrInfo_switching_PortSecurityStaticMacAddr = "Port Security Static MAC Address";
L7_char8 *pStrInfo_switching_PortSecurityStaticallyCfguredMacAddres = "Port Security Statically Configured MAC Addresses";
L7_char8 *pStrInfo_switching_PortSecurityViolationStatus = "Port Security Violation Status";
L7_char8 *pStrInfo_switching_PortSecurityViolationTraps = "Port Security Violation Traps";
L7_char8 *pStrInfo_switching_PortVlanId = "Port VLAN ID";
L7_char8 *pStrInfo_switching_PortVlanIdCfgured = "Port VLAN ID Configured";
L7_char8 *pStrInfo_switching_PortVlanIdCurrent = "Port VLAN ID Current";
L7_char8 *pStrInfo_switching_PriWasSetSuccessfullyToAValInAccordanceWithIeee8021sSpecifications = "Priority was set successfully to a value in accordance with IEEE 802.1s specifications.";
L7_char8 *pStrInfo_switching_ProtectedPortS = "Protected Port(s)";
L7_char8 *pStrInfo_switching_ProtectedPortsCfg = "Protected Ports Configuration";
L7_char8 *pStrInfo_switching_ProtectedPortsSummary = "Protected Ports Summary";
L7_char8 *pStrInfo_switching_ProtoBasedVlanCfg = "Protocol-based VLAN Configuration";
L7_char8 *pStrInfo_switching_ProtoBasedVlanSummary = "Protocol-based VLAN Summary";
L7_char8 *pStrInfo_switching_Protos = "Protocols";
L7_char8 *pStrInfo_switching_QueryIntvl = "Query Interval";
L7_char8 *pStrInfo_switching_ReInitializationDelay = "Re- Initialization Delay";
L7_char8 *pStrInfo_switching_Receive = "Receive";
L7_char8 *pStrInfo_switching_ReceiveTotal = "Receive Total";
L7_char8 *pStrInfo_switching_RemoteData = "Remote Data";
L7_char8 *pStrInfo_switching_RemoteDevice = "Remote Device";
L7_char8 *pStrInfo_switching_ResetCfgToFactoryDefls = "Reset Configuration to Factory Defaults";
L7_char8 *pStrInfo_switching_ResetVlanCfg = "Reset VLAN Configuration";
L7_char8 *pStrInfo_switching_RootGuardError = "Root Guard cannot be enabled on interface %d with enabled Loop Guard";
L7_char8 *pStrInfo_switching_RootPort_1 = "Root Port";
L7_char8 *pStrInfo_switching_StpPortState = "STP Port State";
L7_char8 *pStrInfo_switching_SnoopingQuerierAddr = "Snooping Querier Address";
L7_char8 *pStrInfo_switching_SnoopingQuerierAdminMode = "Snooping Querier Admin Mode";
L7_char8 *pStrInfo_switching_SnoopingQuerierVlanAddr = "Snooping Querier VLAN Address";
L7_char8 *pStrInfo_switching_SnoopingQuerierVlanMode = "Snooping Querier VLAN Mode";
L7_char8 *pStrInfo_switching_SrcPortMask = "Source Port Mask";
L7_char8 *pStrInfo_switching_SrcPortMbrs = "Source Port Members";
L7_char8 *pStrInfo_switching_SpanTreeAdminMode = "Spanning Tree Admin Mode";
L7_char8 *pStrInfo_switching_SpanTreeCstCfgStatus = "Spanning Tree CST Configuration/Status";
L7_char8 *pStrInfo_switching_SpanTreeCstPortCfgStatus = "Spanning Tree CST Port Configuration/Status";
L7_char8 *pStrInfo_switching_SpanTreeMstCfgStatus = "Spanning Tree MST Configuration/Status";
L7_char8 *pStrInfo_switching_SpanTreeMstPortCfgStatus = "Spanning Tree MST Port Configuration/Status";
L7_char8 *pStrInfo_switching_SpanTreeStats = "Spanning Tree Statistics";
L7_char8 *pStrInfo_switching_SpanTreeSwitchCfgStatus = "Spanning Tree Switch Configuration/Status";
L7_char8 *pStrInfo_switching_HashModeSaVlan = "Src MAC, VLAN, EType, incoming port";
L7_char8 *pStrInfo_switching_HashModeSaDaVlan = "Src/Dest MAC, VLAN, EType, incoming port";
L7_char8 *pStrInfo_switching_HashModeSa = "Src MAC";
L7_char8 *pStrInfo_switching_HashModeSaDa = "Src/Dest MAC";
L7_char8 *pStrInfo_switching_HashModeSrcIP = "Src IP and Src TCP/UDP Port fields";
L7_char8 *pStrInfo_switching_HashModeSrcDestIP = "Src/Dest IP and TCP/UDP Port fields";
L7_char8 *pStrInfo_switching_StaticMode = "Static Mode";
L7_char8 *pStrInfo_switching_SwitchGmrp = "Switch GMRP";
L7_char8 *pStrInfo_switching_SwitchGvrp = "Switch GVRP";
L7_char8 *pStrInfo_switching_SysCapabilities = "System Capabilities";
L7_char8 *pStrInfo_switching_RemLbCapabilities = "Remote Loopback Capabilities";
L7_char8 *pStrInfo_switching_LinkEventCapabilities = "Link Event Capabilities";
L7_char8 *pStrInfo_switching_OrgSpecInfoCapabilities = "Org Specific PDU Capabilities";
L7_char8 *pStrInfo_switching_OrgSpecEventCapabilities = "Org Specific Event Capabilities";
L7_char8 *pStrInfo_switching_OrgSpecTLVCapabilities = "Org Specific TLV Capabilities";
L7_char8 *pStrInfo_switching_SysCapabilitiesEnbld_1 = "System Capabilities Enabled";
L7_char8 *pStrInfo_switching_SysCapabilitiesSupported_1 = "System Capabilities Supported";
L7_char8 *pStrInfo_switching_TlvDiscards = "TLV Discards";
L7_char8 *pStrInfo_switching_TlvUnknowns = "TLV Unknowns";
L7_char8 *pStrInfo_switching_Tagging = "Tagging";
L7_char8 *pStrInfo_switching_TimeToLive_1 = "Time to Live";
L7_char8 *pStrInfo_switching_TopologyChg = "Topology Change";
L7_char8 *pStrInfo_switching_Tx = "Transmit";
L7_char8 *pStrInfo_switching_TxMgmtInfo = "Transmit Management Information";
L7_char8 *pStrInfo_switching_TxTotal = "Transmit Total";
L7_char8 *pStrInfo_switching_TrustMode = "Trust Mode";
L7_char8 *pStrInfo_switching_Vid_1 = "VID";
L7_char8 *pStrInfo_switching_VlanCfg = "VLAN Configuration";
L7_char8 *pStrInfo_switching_VlanIdAndName = "VLAN ID and Name";
L7_char8 *pStrInfo_switching_VlanIdsEnbldForIgmpSnooping = "VLAN Ids Enabled for IGMP Snooping";
L7_char8 *pStrInfo_switching_VlanIdsEnbldForMldSnooping = "VLAN Ids Enabled for MLD Snooping";
L7_char8 *pStrInfo_switching_VlanName_1 = "VLAN Name";
L7_char8 *pStrInfo_switching_VlanPortCfg = "VLAN Port Configuration";
L7_char8 *pStrInfo_switching_VlanPortSummary = "VLAN Port Summary";
L7_char8 *pStrInfo_switching_VlanStatus = "VLAN Status";
L7_char8 *pStrInfo_switching_VlanType = "VLAN Type";
L7_char8 *pStrInfo_switching_VlanParticipationOfIntfToSpecifiedVlan = "VLAN participation of interface to specified VLAN";
L7_char8 *pStrInfo_switching_ValidNameNotSpecified = "Valid name not specified.";
L7_char8 *pStrInfo_switching_VlanNameMustContainAlnumCharsOnly = "VLAN name must contain alphaNumeric characters only.";
L7_char8 *pStrInfo_switching_None_2 = "[None]";
L7_char8 *pStrInfo_switching_AllocateMemoryToPerformOperation = "allocate memory to perform the operation";
L7_char8 *pStrInfo_switching_HtmlFileCfrmResetVlan = "cfrm_reset_vlan.html";
L7_char8 *pStrInfo_switching_HtmlFileCistPortCfg = "cist_port_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpFilteringIntfMode = "dhcp_filtering_intf_mode.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpFilteringSumm = "dhcp_filtering_summ.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpModeCfg = "dhcp_mode_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDot1pPriMapping = "dot1p_priority_mapping.html";
L7_char8 *pStrInfo_switching_ForceBpduMigrationCheck = "force BPDU migration check.";
L7_char8 *pStrInfo_switching_HtmlFileGarpCfg = "garp_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileGarpPortCfg = "garp_port_cfg.html";
L7_char8 *pStrInfo_switching_HtmlLinkBaseSysHelpMacfilterSwcfg = "href=\"/base/system/help_macfilter.html#swcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkBaseSysHelpMacfilterSwcfgsumm = "href=\"/base/system/help_macfilter.html#swcfgsumm\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpFilteringHelpDhcpFilteringDhcpfiltercfg = "href=\"/switching/dhcp_filtering/help_dhcp_filtering.html#dhcpfiltercfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpFilteringHelpDhcpFilteringDhcpfilterintfcfg = "href=\"/switching/dhcp_filtering/help_dhcp_filtering.html#dhcpfilterintfcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpFilteringHelpDhcpFilteringDhcpfilterintfsumm = "href=\"/switching/dhcp_filtering/help_dhcp_filtering.html#dhcpfilterintfsumm\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot1pHelpDot1pDot1pprioritymapping = "href=\"/switching/dot1p/help_dot1p.html#dot1pprioritymapping\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot1qHelpVlanQnpcfg = "href=\"/switching/dot1q/help_vlan.html#qnpcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot1qHelpVlanQnpsumm = "href=\"/switching/dot1q/help_vlan.html#qnpsumm\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot1qHelpVlanResvlan = "href=\"/switching/dot1q/help_vlan.html#resvlan\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot1qHelpVlanVlanconfig = "href=\"/switching/dot1q/help_vlan.html#vlanconfig\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot1qHelpVlanVlanstat = "href=\"/switching/dot1q/help_vlan.html#vlanstat\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot1vHelpPbvlanPbvlanCfg = "href=\"/switching/dot1v/help_pbvlan.html#pbvlan_cfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot1vHelpPbvlanPbvlanSummary = "href=\"/switching/dot1v/help_pbvlan.html#pbvlan_summary\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingGarpHelpGarpGarpcfg = "href=\"/switching/garp/help_garp.html#garpcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingGarpHelpGarpGarpstat = "href=\"/switching/garp/help_garp.html#garpstat\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingGarpHelpGarpPortgarpcfg = "href=\"/switching/garp/help_garp.html#portgarpcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIgmpSnoopingHelpIgmpSnoopingIgmpIntf = "href=\"/switching/igmp_snooping/help_igmp_snooping.html#igmp_interface\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIgmpSnoopingHelpIgmpSnoopingIgmpVlanCfg = "href=\"/switching/igmp_snooping/help_igmp_snooping.html#igmp_vlan_cfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIgmpSnoopingHelpIgmpSnoopingIgmpVlanStats = "href=\"/switching/igmp_snooping/help_igmp_snooping.html#igmp_vlan_stats\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIgmpSnoopingHelpIgmpSnoopingMrcfg = "href=\"/switching/igmp_snooping/help_igmp_snooping.html#mrcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIgmpSnoopingHelpIgmpSnoopingMulRutStat = "href=\"/switching/igmp_snooping/help_igmp_snooping.html#mul_rut_stat\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIgmpSnoopingHelpIgmpSnoopingMulVlanCfg = "href=\"/switching/igmp_snooping/help_igmp_snooping.html#mul_vlan_cfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIgmpSnoopingHelpIgmpSnoopingMulVlanStat = "href=\"/switching/igmp_snooping/help_igmp_snooping.html#mul_vlan_stat\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIgmpSnoopingHelpIgmpSnoopingSwitch = "href=\"/switching/igmp_snooping/help_igmp_snooping.html#switch\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIgmpSnoopingHelpIgmpSnoopingQuerierQuerierCfg = "href=\"/switching/igmp_snooping/help_igmp_snooping_querier.html#querier_cfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIgmpSnoopingHelpIgmpSnoopingQuerierQuerierVlanCfg = "href=\"/switching/igmp_snooping/help_igmp_snooping_querier.html#querier_vlan_cfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIgmpSnoopingHelpIgmpSnoopingQuerierQuerierVlanStatus = "href=\"/switching/igmp_snooping/help_igmp_snooping_querier.html#querier_vlan_status\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIgmpSnoopingHelpIgmpSnoopingQuerierQuerierVlanSumm = "href=\"/switching/igmp_snooping/help_igmp_snooping_querier.html#querier_vlan_summ\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIpsubnetvlanHelpIpsubnetVlanSubnetvlancfg = "href=\"/switching/ipsubnetvlan/help_ipsubnet_vlan.html#subnetvlancfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingIpsubnetvlanHelpIpsubnetVlanSubnetvlansumm = "href=\"/switching/ipsubnetvlan/help_ipsubnet_vlan.html#subnetvlansumm\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingLagHelpLagTrunkcfg = "href=\"/switching/lag/help_lag.html#trunkcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingLagHelpLagTrunkstat = "href=\"/switching/lag/help_lag.html#trunkstat\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingLldpHelpLldpLldpcfg = "href=\"/switching/lldp/help_lldp.html#lldpcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingLldpHelpLldpLldpintfcfg = "href=\"/switching/lldp/help_lldp.html#lldpintfcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingLldpHelpLldpLldpintfsumm = "href=\"/switching/lldp/help_lldp.html#lldpintfsumm\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingLldpHelpLldpLldplocaldevice = "href=\"/switching/lldp/help_lldp.html#lldplocaldevice\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingLldpHelpLldpLldplocaldevicesumm = "href=\"/switching/lldp/help_lldp.html#lldplocaldevicesumm\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingLldpHelpLldpLldpremotedevice = "href=\"/switching/lldp/help_lldp.html#lldpremotedevice\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingLldpHelpLldpLldpremotedevicesumm = "href=\"/switching/lldp/help_lldp.html#lldpremotedevicesumm\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingLldpHelpLldpLldpstat = "href=\"/switching/lldp/help_lldp.html#lldpstat\"";
/* start of dot3ah */
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot3ahHelpDot3ahDot3ahcfg = "href=\"/switching/dot3ah/help_dot3ah.html#dot3ahcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot3ahHelpDot3ahDot3ahintfcfg = "href=\"/switching/dot3ah/help_dot3ah.html#dot3ahintfcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot3ahHelpDot3ahLanOamintfcfg = "href=\"/switching/dot3ah/help_dot3ah.html#lanoamintfcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot3ahHelpDot3ahDot3ahintfsumm = "href=\"/switching/dot3ah/help_dot3ah.html#dot3ahintfsumm\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot3ahHelpDot3ahDot3ahlocaldevice = "href=\"/switching/dot3ah/help_dot3ah.html#dot3ahlocaldevice\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot3ahHelpDot3ahDot3ahlocaldevicesumm = "href=\"/switching/dot3ah/help_dot3ah.html#dot3ahlocaldevicesumm\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot3ahHelpDot3ahDot3ahremotedevice = "href=\"/switching/dot3ah/help_dot3ah.html#dot3ahremotedevice\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot3ahHelpDot3ahDot3ahremotedevicesumm = "href=\"/switching/dot3ah/help_dot3ah.html#dot3ahremotedevicesumm\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot3ahHelpDot3ahDot3ahstat = "href=\"/switching/dot3ah/help_dot3ah.html#dot3ahstat\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot3ahHelpDot3ahDot3ahstatus = "href=\"/switching/dot3ah/help_dot3ah.html#dot3ahstatus\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot3ahHelpDot3ahDot3ahLocalstatus = "href=\"/switching/dot3ah/help_dot3ah.html#dot3ahlocalstatus\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDot3ahHelpDot3ahLanOamstat = "href=\"/switching/dot3ah/help_dot3ah.html#lanOamstat\"";

/* end of dot3ah */
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMacVlanHelpMacVlanMacvlancfg = "href=\"/switching/mac_vlan/help_mac_vlan.html#macvlancfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMacVlanHelpMacVlanMacvlansumm = "href=\"/switching/mac_vlan/help_mac_vlan.html#macvlansumm\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMfdbHelpMfdbGmrpTbl = "href=\"/switching/mfdb/help_mfdb.html#gmrp_table\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMfdbHelpMfdbIgmpTbl = "href=\"/switching/mfdb/help_mfdb.html#igmp_table\"";
L7_char8 *pStrInfo_switching_HtmlLinkXuiSwitchingMfdbHelpMfdbGmrpTbl = "href=\"/help_MFDBGMRPTable.html\"";
L7_char8 *pStrInfo_switching_HtmlLinkXuiSwitchingMfdbHelpMfdbIgmpTbl = "href=\"/help_IGMPSnoopingTable.html\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMfdbHelpMfdbMldTbl = "href=\"/switching/mfdb/help_mfdb.html#mld_table\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMfdbHelpMfdbMfdbStats = "href=\"/switching/mfdb/help_mfdb.html#mfdb_stats\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMfdbHelpMfdbMfdbTbl = "href=\"/switching/mfdb/help_mfdb.html#mfdb_table\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMldSnoopingHelpMldSnoopingMldVlanCfg = "href=\"/switching/mld_snooping/help_mld_snooping.html#MLD_vlan_cfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMldSnoopingHelpMldSnoopingMldVlanStats = "href=\"/switching/mld_snooping/help_mld_snooping.html#MLD_vlan_stats\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMldSnoopingHelpMldSnoopingMldIntf = "href=\"/switching/mld_snooping/help_mld_snooping.html#mld_interface\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMldSnoopingHelpMldSnoopingMrcfg = "href=\"/switching/mld_snooping/help_mld_snooping.html#mrcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMldSnoopingHelpMldSnoopingMulRutStat = "href=\"/switching/mld_snooping/help_mld_snooping.html#mul_rut_stat\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMldSnoopingHelpMldSnoopingMulVlanCfg = "href=\"/switching/mld_snooping/help_mld_snooping.html#mul_vlan_cfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMldSnoopingHelpMldSnoopingMulVlanStat = "href=\"/switching/mld_snooping/help_mld_snooping.html#mul_vlan_stat\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMldSnoopingHelpMldSnoopingSwitch = "href=\"/switching/mld_snooping/help_mld_snooping.html#switch\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMldSnoopingHelpMldSnoopingQuerierQuerierCfg = "href=\"/switching/mld_snooping/help_mld_snooping_querier.html#querier_cfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMldSnoopingHelpMldSnoopingQuerierQuerierVlanCfg = "href=\"/switching/mld_snooping/help_mld_snooping_querier.html#querier_vlan_cfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMldSnoopingHelpMldSnoopingQuerierQuerierVlanStatus = "href=\"/switching/mld_snooping/help_mld_snooping_querier.html#querier_vlan_status\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingMldSnoopingHelpMldSnoopingQuerierQuerierVlanSumm = "href=\"/switching/mld_snooping/help_mld_snooping_querier.html#querier_vlan_summ\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingPmlHelpPortmaclockingPortmaclockingconfiguration = "href=\"/switching/port_mac_locking/help_portmaclocking.html#portmaclockingconfiguration\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingPmlHelpPortmaclockingPortmaclockingdynamic = "href=\"/switching/port_mac_locking/help_portmaclocking.html#portmaclockingdynamic\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingPmlHelpPortmaclockingPortmaclockingintifsetup = "href=\"/switching/port_mac_locking/help_portmaclocking.html#portmaclockingintifsetup\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingPmlHelpPortmaclockingPortmaclockingstatic = "href=\"/switching/port_mac_locking/help_portmaclocking.html#portmaclockingstatic\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingPmlHelpPortmaclockingPortmacviolationstatus = "href=\"/switching/port_mac_locking/help_portmaclocking.html#portmacviolationstatus\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingProtectedPortsHelpProtectedPortsProtPortCfg = "href=\"/switching/protected_ports/help_protected_ports.html#prot_port_cfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingProtectedPortsHelpProtectedPortsProtPortSumm = "href=\"/switching/protected_ports/help_protected_ports.html#prot_port_summ\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingSpanTreeHelpMstpCistcfg = "href=\"/switching/spanning_tree/help_mstp.html#cistcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingSpanTreeHelpMstpCistportcfg = "href=\"/switching/spanning_tree/help_mstp.html#cistportcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingSpanTreeHelpMstpMsticfg = "href=\"/switching/spanning_tree/help_mstp.html#msticfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingSpanTreeHelpMstpMstiportcfg = "href=\"/switching/spanning_tree/help_mstp.html#mstiportcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingSpanTreeHelpMstpMstpswitch = "href=\"/switching/spanning_tree/help_mstp.html#mstpswitch\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingSpanTreeHelpMstpStats = "href=\"/switching/spanning_tree/help_mstp.html#stats\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDaiHelpDaiVlanCfg = "href=\"/switching/dynamic_arp_inspection/help_dai.html#daivlancfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDaiHelpDaiIntfCfg = "href=\"/switching/dynamic_arp_inspection/help_dai.html#daiintfcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDaiHelpDaiArpCfg = "href=\"/switching/dynamic_arp_inspection/help_dai.html#daiarpaclcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDaiHelpDaiCfg = "href=\"/switching/dynamic_arp_inspection/help_dai.html#daicfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDaiHelpDaiArpAclRuleCfg = "href=\"/switching/dynamic_arp_inspection/help_dai.html#daiarpaclrulecfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDaiHelpDaiStats = "href=\"/switching/dynamic_arp_inspection/help_dai.html#daistats\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpSnoopingHelpBindngCfg = "href=\"/switching/dhcp_snooping/help_dhcp_snooping.html#dhcpsnoopbindingCfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkXuiSwitchingDhcpSnoopingHelpBindngCfg = "href=\"/help_DHCPSnoopingBindingsConfig.html\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpSnoopingHelpCfg = "href=\"/switching/dhcp_snooping/help_dhcp_snooping.html#dhcpsnoopcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpSnoopingHelpIntfCfg = "href=\"/switching/dhcp_snooping/help_dhcp_snooping.html#dhcpsnoopintfcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpSnoopingHelpPersistCfg = "href=\"/switching/dhcp_snooping/help_dhcp_snooping.html#dhcpsnooppersistcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpSnoopingHelpStats = "href=\"/switching/dhcp_snooping/help_dhcp_snooping.html#dhcpsnoopstats\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpSnoopingHelpVlanCfg = "href=\"/switching/dhcp_snooping/help_dhcp_snooping.html#dhcpsnoopvlancfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkXuiSwitchingDhcpSnoopingHelpVlanCfg = "href=\"/help_DHCPSnoopingVLANConfig.html\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpSnoopingHelpIpsgBindingCfg = "href=\"/switching/dhcp_snooping/help_dhcp_snooping.html#ipsgbindingcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkXuiSwitchingDhcpSnoopingHelpIpsgBindingCfg = "href=\"/help_IPSGBindingConfig.html\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpSnoopingHelpIpsgIntfCfg = "href=\"/switching/dhcp_snooping/help_dhcp_snooping.html#ipsgintfcfg\"";
L7_char8 *pStrInfo_switching_DynamicArpInspectionXUIVlanCfg = "href=\"/help_DAIVlanCfg.html\"";
L7_char8 *pStrInfo_switching_DynamicArpInspectionXUIStatistics = "href=\"/help_DAIStatistics.html\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingXUIDhcpL2RelayVlanCfg = "href=\"/help_DHCPL2RelayVLANConfiguration.html\"";

L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpL2RelayHelpCfg = "href=\"/switching/dhcp_snooping/help_dhcp_l2relay.html#dhcpl2relaycfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpL2RelayHelpIntfCfg = "href=\"/switching/dhcp_snooping/help_dhcp_l2relay.html#dhcpl2relayintfcfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpL2RelayHelpVlanCfg = "href=\"/switching/dhcp_snooping/help_dhcp_l2relay.html#dhcpl2relayvlancfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpL2RelayHelpIntfStats = "href=\"/switching/dhcp_snooping/help_dhcp_l2relay.html#dhcpl2relayintfstats\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpL2RelayHelpSubscCfg = "href=\"/switching/dhcp_snooping/help_dhcp_l2relay.html#dhcpl2relaysubsccfg\"";
L7_char8 *pStrInfo_switching_HtmlLinkSwitchingDhcpL2RelayHelpSubscSumm = "href=\"/switching/dhcp_snooping/help_dhcp_l2relay.html#dhcpl2relaysubscsumm\"";

L7_char8 *pStrInfo_switching_HtmlFileIgmpIntfCfg = "igmp_intf_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileIgmpQuerierVlanCfg = "igmp_querier_vlan_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileIgmpSnupingCfg = "igmp_snuping_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileIgmpSnupingQuerier = "igmp_snuping_querier.html";
L7_char8 *pStrInfo_switching_HtmlFileIgmpVlanCfg = "igmp_vlan_cfg.html";
L7_char8 *pStrInfo_switching_IgmpVlanId = "igmp_vlan_id";
L7_char8 *pStrInfo_switching_InSettingAdminMode = "in Setting Admin Mode";
L7_char8 *pStrInfo_switching_HtmlFileIpsubnetVlanCfg = "ipsubnet_vlan_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileIpsubnetVlanSumm = "ipsubnet_vlan_summ.html";
L7_char8 *pStrInfo_switching_Lag_3 = "lag";
L7_char8 *pStrInfo_switching_HtmlFileLldpCfg = "lldp_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileLldpIntfAcc = "lldp_intf_acc.html";
L7_char8 *pStrInfo_switching_HtmlFileLldpIntfSumm = "lldp_intf_summ.html";
L7_char8 *pStrInfo_switching_HtmlFileLldpLocaldevice = "lldp_localdevice.html";
L7_char8 *pStrInfo_switching_HtmlFileLldpLocaldeviceSumm = "lldp_localdevice_summ.html";
L7_char8 *pStrInfo_switching_HtmlFileLldpRemotedevice = "lldp_remotedevice.html";
L7_char8 *pStrInfo_switching_HtmlFileLldpRemotedeviceSumm = "lldp_remotedevice_summ.html";
L7_char8 *pStrInfo_switching_HtmlFileLldpStat = "lldp_stat.html";
L7_char8 *pStrInfo_switching_HtmlFileMacFilterCfg1 = "mac_filter_cfg1.html";
L7_char8 *pStrInfo_switching_HtmlFileMacvlanCfg = "macvlan_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileMacvlanSumm = "macvlan_summ.html";
L7_char8 *pStrInfo_switching_ManuallyCfgureADynVlan = "manually configure a dynamic VLAN.";
L7_char8 *pStrInfo_switching_HtmlFileMfdbGmrp = "mfdb_gmrp.html";
L7_char8 *pStrInfo_switching_HtmlFileMfdbIgmp = "mfdb_igmp.html";
L7_char8 *pStrInfo_switching_HtmlFileMfdbMld = "mfdb_mld.html";
L7_char8 *pStrInfo_switching_HtmlFileMfdbStats = "mfdb_stats.html";
L7_char8 *pStrInfo_switching_HtmlFileMfdbTbl = "mfdb_table.html";
L7_char8 *pStrInfo_switching_HtmlFileMldIntfCfg_1 = "mld_intf_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileMldMulRtrCfg = "mld_mul_router_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileMldMulRtrStats = "mld_mul_router_stats.html";
L7_char8 *pStrInfo_switching_HtmlFileMldMulVlanCfg = "mld_mul_vlan_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileMldMulVlanStats = "mld_mul_vlan_stats.html";
L7_char8 *pStrInfo_switching_HtmlFileMldQuerierVlanCfg = "mld_querier_vlan_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileMldSnupingCfg = "mld_snuping_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileMldSnupingQuerier = "mld_snuping_querier.html";
L7_char8 *pStrInfo_switching_HtmlFileMldVlanCfg = "mld_vlan_cfg.html";
L7_char8 *pStrInfo_switching_MldVlanId = "mld_vlan_id";
L7_char8 *pStrInfo_switching_HtmlFileMstiCfg = "msti_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileMstiPortCfg = "msti_port_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileMstpCistCfg = "mstp_cist_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileMstpStats = "mstp_stats.html";
L7_char8 *pStrInfo_switching_HtmlFileMstpSwitch = "mstp_switch.html";
L7_char8 *pStrInfo_switching_HtmlFileMulRtrCfg = "mul_router_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileMulRtrStats = "mul_router_stats.html";
L7_char8 *pStrInfo_switching_HtmlFileMulVlanCfg = "mul_vlan_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileMulVlanStats = "mul_vlan_stats.html";
L7_char8 *pStrInfo_switching_HtmlFilePbvlan = "pbvlan.html";
L7_char8 *pStrInfo_switching_HtmlFilePbvlanSumm = "pbvlan_summ.html";
L7_char8 *pStrInfo_switching_HtmlFilePmlCfg = "port_mac_locking_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFilePmlDyn = "port_mac_locking_dynamic.html";
L7_char8 *pStrInfo_switching_HtmlFilePmlSetup = "port_mac_locking_setup.html";
L7_char8 *pStrInfo_switching_HtmlFilePmlStatic = "port_mac_locking_static.html";
L7_char8 *pStrInfo_switching_HtmlFilePmlStatus = "port_mac_locking_status.html";
L7_char8 *pStrInfo_switching_HtmlFileProtectedPorts = "protected_ports.html";
L7_char8 *pStrInfo_switching_HtmlFileProtectedPortsSumm = "protected_ports_summ.html";
L7_char8 *pStrInfo_switching_HtmlFileQnpPortCfg = "qnp_port_cfg.html";
L7_char8 *pStrInfo_switching_QuerierExpiryIntvl = "querier_expiry_interval";
L7_char8 *pStrInfo_switching_QueryIntvl_2 = "query_interval";
L7_char8 *pStrInfo_switching_SettingValOfHelloTimer = "setting the value of hello timer";
L7_char8 *pStrInfo_switching_HtmlFileTrunkCfg = "trunk_cfg.html";
L7_char8 *pStrInfo_switching_Usmdbvlantypeget = "usmDbVlanTypeGet";
L7_char8 *pStrInfo_switching_HtmlFileVlanCfg1 = "vlan_cfg1.html";
L7_char8 *pStrInfo_switching_HtmlFileVlanInfo = "vlan_info.html";
L7_char8 *pStrInfo_switching_HtmlFileVoiceVlanCfg = "voice_vlan_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDaiVlanCfg = "dai_vlan_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDaiIntfCfg = "dai_intf_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDaiArpAclCfg = "dai_arp_acl_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDaiArpAclRuleCfg = "dai_arp_acl_rule_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDaiStats = "dai_stats.html";
L7_char8 *pStrInfo_switching_HtmlFileLldpMedCfg = "lldp_med_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileLldpMedIntfSumm = "lldp_med_intf_summ.html";
L7_char8 *pStrInfo_switching_HtmlFileLldpMedLocalDeviceSumm = "lldp_med_local_device_info.html";
L7_char8 *pStrInfo_switching_HtmlFileLldpMedRemoteDeviceSumm = "lldp_med_remote_device_info.html";
L7_char8 *pStrInfo_switching_HtmlFileLldpMedIntfCfg = "lldp_med_intf_cfg.html";
L7_char8 *pStrInfo_switching_LLDPMed = "LLDP Media End-point Discovery mode";
L7_char8 *pStrInfo_switching_LLDPMedNotification = "LLDP-MED Notification mode";
L7_char8 *pStrInfo_switching_LLDPMedTransTLVs = "LLDP-MED Transmit TLVs";
L7_char8 *pStrInfo_switching_LLDPMedMode = "LLDP-MED Mode";
/* dot3ah */
L7_char8 *pStrInfo_switching_SwitchDot3ah = "Metro DOT3AH";
L7_char8 *pStrInfo_switching_HtmlFileDot3ahIntfSumm="dot3ah_intf_summ.html";
L7_char8 *pStrInfo_switching_HtmlFileDot3ahIntfCfg="dot3ah_intf_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDot3ahIntfStatus="dot3ah_status.html";
L7_char8 *pStrInfo_switching_HtmlFileDot3ahIntfStat="dot3ah_stat.html";
L7_char8 *pStrInfo_switching_HtmlFileDot3ahSwitchStatus="dot3ah_local_status.html";
L7_char8 *pStrInfo_switching_HtmlFileDot3ahLocalDeviceSumm="dot3ah_localdevice_summ.html";
L7_char8 *pStrInfo_switching_HtmlFileDot3ahRemoteDeviceSumm="dot3ah_remotedevice_summ.html";
L7_char8 *pStrInfo_switching_HtmlFileDot3ahIntfAcc="dot3ah_intf_acc.html";
L7_char8 *pStrInfo_switching_HtmlFileDot3ahLanOamCfg = "lan_oam_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDot3ahLanOamIntfSumm = "lan_oam_intf_summ.html";
L7_char8 *pStrInfo_switching_HtmlFileDot3ahLanOamLocalDeviceStat = "lan_oam_stat.html";
L7_char8 *pStrInfo_switching_HtmlFileDot3ahLanOamIntfCfg = "lan_oam_intf_cfg.html";
L7_char8 *pStrInfo_switching_PortDot3ahMode = "Port DOT3AH Mode";
L7_char8 *pStrInfo_switching_PortLANOAMMode = "Port LAN-OAM Mode";
L7_char8 *pStrInfo_switching_Dot3ahLanOamMode = "LAN OAM Mode";
L7_char8 *pStrInfo_switching_PortLANOAMLbType = "LAN OAM LB Type";
L7_char8 *pStrInfo_switching_Dot3ahOptionalCapS = "Optional Cap(s) or TLVs";
/* dot3ah */
L7_char8 *pStrInfo_switching_ConfigNotifyMode = "Config Notification Mode";
L7_char8 *pStrInfo_switching_LocalinterfacesarenotenabledtotransmitLLDPMEDdata = "Local interfaces are not enabled to transmit LLDP-MED data";
L7_char8 *pStrInfo_switching_LocalinterfacesarenotenabledtoRecieveLLDPMEDdata = "Local interfaces are not enabled to recieve LLDP-MED ";
L7_char8 *pStrInfo_switching_NoLLDPMEDLocaldatapresentonthisinterface = "No LLDP-MED local data present on this interface";
L7_char8 *pStrInfo_switching_NoLLDPMEDremotedatarecievedonthisinterface = "No LLDP-MED remote data recieved on this interface";
L7_char8 *pStrInfo_switching_LldpMedGlobalConfiguration = "LLDP-MED Global Configuration";
L7_char8 *pStrInfo_switching_LLDPMEDInterfaceConfiguration = "LLDP-MED Interface Configuration";
L7_char8 *pStrInfo_switching_LLDPMEDInterfaceSummary = "LLDP-MED Interface Summary";
L7_char8 *pStrInfo_switching_LLDPMEDLocalDeviceInformation = "LLDP-MED Local Device Information";
L7_char8 *pStrInfo_switching_LLDPMEDRemoteDeviceInformation = "LLDP-MED Remote Device Information";
L7_char8 *pStrInfo_switching_LldpMedGlobalConfigurationHelp = "href=\"/switching/lldp/lldp_med/help_lldp_med.html#lldp_med_cfg\"";
L7_char8 *pStrInfo_switching_LLDPMEDInterfaceConfigurationHelp = "href=\"/switching/lldp/lldp_med/help_lldp_med.html#lldp_med_intf_cfg\"";
L7_char8 *pStrInfo_switching_LLDPMEDInterfaceSummaryHelp = "href=\"/switching/lldp/lldp_med/help_lldp_med.html#lldp_med_intf_summ\"";
L7_char8 *pStrInfo_switching_LLDPMEDLocalDeviceInformationHelp = "href=\"/switching/lldp/lldp_med/help_lldp_med.html#lldp_med_local_device_info\"";
L7_char8 *pStrInfo_switching_LLDPMEDRemoteDeviceInformationHelp = "href=\"/switching/lldp/lldp_med/help_lldp_med.html#lldp_med_remote_device_info\"";

L7_char8 *pStrInfo_switching_FastStartRepeatCount = "Fast Start Repeat Count";
L7_char8 *pStrInfo_switching_DeviceClass = "Device Class";
L7_char8 *pStrInfo_switching_TransmittedTLVs = "Transmit TLVs";
L7_char8 *pStrInfo_switching_MEDCapabilities = "MED Capabilities";
L7_char8 *pStrInfo_switching_NetworkPolicy = "Network Policy";
L7_char8 *pStrInfo_switching_LocationIdentification = "Location Identification";
L7_char8 *pStrInfo_switching_ExtendedPowerViaMDIPSE = "Extended Power via MDI - PSE";
L7_char8 *pStrInfo_switching_ExtendedPowerViaMDIPD = "Extended Power via MDI - PD";
L7_char8 *pStrInfo_switching_Inventory = "Inventory";
L7_char8 *pStrInfo_switching_MEDStatus = "MED Status";
L7_char8 *pStrInfo_switching_NotificationStatus = "Notification Status";
L7_char8 *pStrInfo_switching_NetworkPoliciesInformation = "Network Policy Information";
L7_char8 *pStrInfo_switching_MediaApplicationType = "Media Application Type";
L7_char8 *pStrInfo_switching_UnknownBitStatus = "Unknown Bit Status";
L7_char8 *pStrInfo_switching_DSCP = "DSCP";
L7_char8 *pStrInfo_switching_TaggedBitStatus = "Tagged Bit Status";
L7_char8 *pStrInfo_switching_InventoryInformation = "Inventory Information";
L7_char8 *pStrInfo_switching_HardwareRevision = "Hardware Revision";
L7_char8 *pStrInfo_switching_FirmwareRevision = "Firmware Revision";
L7_char8 *pStrInfo_switching_SoftwareRevision = "Software Revision";
L7_char8 *pStrInfo_switching_ManufacturerName = "Manufacturer Name";
L7_char8 *pStrInfo_switching_ModelName = "ModelName";
L7_char8 *pStrInfo_switching_AssetID = "Asset ID";
L7_char8 *pStrInfo_switching_LocationInformation_1 = "Location Information";
L7_char8 *pStrInfo_switching_SubType = "Sub Type";
L7_char8 *pStrInfo_switching_LocationInformation = "Location Information";
L7_char8 *pStrInfo_switching_ExtendedPoE = "Extended PoE";
L7_char8 *pStrInfo_switching_DeviceType = "Device Type";
L7_char8 *pStrInfo_switching_ExtendedPoEPSE = "Extended PoE PSE";
L7_char8 *pStrInfo_switching_Available = "Available";
L7_char8 *pStrInfo_switching_Source = "Source";
L7_char8 *pStrInfo_switching_ExtendedPoEPD  = "Extended PoE PD ";
L7_char8 *pStrInfo_switching_Required = "Required";
L7_char8 *pStrInfo_switching_CapabilityInformation  = "Capability Information";
L7_char8 *pStrInfo_switching_CapabilitiesSupported  = "Capabilities Supported";
L7_char8 *pStrInfo_switching_CababilitiesEnabled  = "Cababilities Enabled";
L7_char8 *pStrInfo_switching_Remoteclientsarenotavaiableonthisinterface = "Remote clients are not available on this interface";
L7_char8 *pStrInfo_switching_voiceVlanCfg = "Voice VLAN Configuration";
L7_char8 *pStrInfo_switching_DynamicArpInspVlanCfg = "Dynamic ARP Inspection VLAN Configuration";
L7_char8 *pStrInfo_switching_DynamicArpInspIntfCfg = "Dynamic ARP Inspection Interface Configuration";
L7_char8 *pStrInfo_switching_DynamicArpInspArpAclCfg = "Dynamic ARP Inspection ACL Configuration";
L7_char8 *pStrInfo_switching_DynamicArpInspArpAclRuleCfg = "Dynamic ARP Inspection ACL Rule Configuration";
L7_char8 *pStrInfo_switching_DynamicArpInspCfg = "Dynamic ARP Inspection Global Configuration";
L7_char8 *pStrInfo_switching_DynamicArpInspStats = "Dynamic ARP Inspection Statistics";
L7_char8 *pStrInfo_switching_VoiceVlanCfgHelp = "href=\"/switching/voice_vlan/help_voice_vlan.html#voice_vlan_cfg\"";
L7_char8 *pStrInfo_switching_VoiceVlanAdminModeDisplay = "Voice VLAN Admin Mode";
L7_char8 *pStrInfo_switching_VoiceVlanIntfMode = "Voice VLAN Interface Mode";
L7_char8 *pStrInfo_switching_VoiceVlanCosOverRideMode = "CoS Override Mode";
L7_char8 *pStrInfo_switching_DynamicArpInspection = "Dynamic ARP Inspection";
L7_char8 *pStrInfo_switching_LoggingInvalidPackets = "Logging Invalid Packets";
L7_char8 *pStrInfo_switching_ArpACLName = "ARP ACL Name";
L7_char8 *pStrInfo_switching_StaticFalg = "Static Flag";
L7_char8 *pStrInfo_switching_SenderIPAddress = "Sender IP Address";
L7_char8 *pStrInfo_switching_SenderMACAddress = "Sender MAC Address";
L7_char8 *pStrInfo_switching_TrustedState = "Trust State";
L7_char8 *pStrInfo_switching_RateLimit = "Rate Limit";
L7_char8 *pStrInfo_switching_BurstInterval = "Burst Interval";
L7_char8 *pStrInfo_switching_SrcMacValidate = "Validate Source MAC";
L7_char8 *pStrInfo_switching_DestMacValidate = "Validate Destination MAC";
L7_char8 *pStrInfo_switching_IpAddrValidate = "Validate IP";
L7_char8 *pStrInfo_switching_DhcpDrops = "DHCP Drops";
L7_char8 *pStrInfo_switching_AclDrops = "ACL Drops";
L7_char8 *pStrInfo_switching_DhcpPermits = "DHCP Permits";
L7_char8 *pStrInfo_switching_AclPermits = "ACL Permits";
L7_char8 *pStrInfo_switching_BadSrcMac = "Bad Source MAC";
L7_char8 *pStrInfo_switching_BadDestMac = "Bad Dest MAC";
L7_char8 *pStrInfo_switching_InvalidIP = "Invalid IP";
L7_char8 *pStrInfo_switching_Forwarded = "Forwarded";
L7_char8 *pStrInfo_switching_Dropped  = "Dropped";
L7_char8 *pStrInfo_switching_NoDaiVlansFound = "No DAI enabled VLANs found";
L7_char8 *pStrInfo_switching_NoArpAclsFound = "No ARP ACLs Found";
L7_char8 *pStrInfo_switching_HtmlFileDaiGlobCfg = "dai_global_cfg.html";
L7_char8 *pStrInfo_base_HtmlFileQnpPortCfgRo = "qnp_port_cfg_ro.html";
L7_char8 *pStrInfo_base_HtmlFileMacFilterSumm = "mac_filter_summ.html";
L7_char8 *pStrInfo_base_HtmlFileGarpStatus = "garp_status.html";
L7_char8 *pStrInfo_base_HtmlFileIgmpVlanStat = "igmp_vlan_stats.html";
L7_char8 *pStrInfo_base_HtmlFileIgmpQuerierVlanCfgSumm = "igmp_querier_vlan_cfg_summ.html";
L7_char8 *pStrInfo_base_HtmlFileIgmpVlanQuerierStatus = "igmp_querier_vlan_status.html";
L7_char8 *pStrInfo_base_HtmlFileTrunkInfo = "trunk_info.html";
L7_char8 *pStrErr_switching_InvalidSrcMacAddr_1 = "Failed to associate %s. Only Unicast MAC Address can be associated to a VLAN";
L7_char8 *pStrInfo_switching_DhcpSnoopBindngCfg = "DHCP Snooping Binding Configuration";
L7_char8 *pStrInfo_switching_DhcpSnoopCfg = "DHCP Snooping Configuration";
L7_char8 *pStrInfo_switching_DhcpSnoopIntfCfg = "DHCP Snooping Interface Configuration";
L7_char8 *pStrInfo_switching_DhcpSnoopPersistCfg = "DHCP Snooping Persistent Configuration";
L7_char8 *pStrInfo_switching_DhcpSnoopStats = "DHCP Snooping Statistics";
L7_char8 *pStrInfo_switching_DhcpSnoopVlanCfg = "DHCP Snooping VLAN Configuration";
L7_char8 *pStrInfo_switching_IpsgBindingCfg = "IPSG Static Binding Configuration";
L7_char8 *pStrInfo_switching_IpsgIntfCfg = "IPSG Interface Configuration";
L7_char8 *pStrInfo_switching_DhcpSnoopingMode = "DHCP Snooping Mode";
L7_char8 *pStrInfo_switching_VerifyMacAddress = "MAC Address Validation";
L7_char8 *pStrInfo_switching_StoreLocally = "Store Locally";
L7_char8 *pStrInfo_switching_RemoteFileName = "Remote File Name";
L7_char8 *pStrInfo_switching_RemoteIpAddress = "Remote IP Address";
L7_char8 *pStrInfo_switching_WriteDelay = "Write Delay";
L7_char8 *pStrInfo_switching_MacFails = "MAC Verify Failures";
L7_char8 *pStrInfo_switching_ClientIfcMismatch = "Client Ifc Mismatch";
L7_char8 *pStrInfo_switching_DHCPServerMsgsRcvd = "DHCP Server Msgs Received";
L7_char8 *pStrInfo_switching_NoDHCPEnabledIntfFound = "No DHCP SNOOPING Enabled Interfaces Found"; 
L7_char8 *pStrInfo_switching_Expiry = "Expiry";
L7_char8 *pStrInfo_switching_LeaseTime = "Lease Time";
L7_char8 *pStrInfo_switching_IPSG = "IPSG";
L7_char8 *pStrInfo_switching_PortSecurity = "IPSG Port Security";
L7_char8 *pStrInfo_switching_FilterType = "Filter Type";
L7_char8 *pStrErr_switching_CouldNotAddBinding = "Couldn't Add binding";
L7_char8 *pStrInfo_switching_HtmlFileDhcpSnoopingCfg = "dhcp_snooping_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpSnoopingIntfCfg = "dhcp_snooping_intf_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpSnoopingVlanCfg = "dhcp_snooping_vlan_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpSnoopingStats = "dhcp_snooping_stats.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpSnoopingPersistCfg = "dhcp_snooping_persist_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpSnoopingBindingCfg = "dhcp_snooping_binding_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileIpsgIntfCfg = "ipsg_intf_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileIpsgBindingCfg = "ipsg_binding_cfg.html";

L7_char8 *pStrInfo_switching_DhcpL2RelayIntfMode = "DHCP L2 Relay interface mode.";
L7_char8 *pStrInfo_switching_DhcpL2RelayRemoteIdMode = "DHCP Remote-Id Mode";
L7_char8 *pStrInfo_switching_HtmlFileDhcpL2RelayCfg = "dhcp_l2relay_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpL2RelayIntfCfg = "dhcp_l2relay_intf_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpL2RelayVlanCfg = "dhcp_l2relay_vlan_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpL2RelayIntfStats = "dhcp_l2relay_intf_stats.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpL2RelaySubscriptionCfg = "dhcp_l2relay_subsc_cfg.html";
L7_char8 *pStrInfo_switching_HtmlFileDhcpL2RelaySubscriptionSumm = "dhcp_l2relay_subsc_summ.html";
L7_char8 *pStrInfo_switching_DhcpL2RelayCfg = "DHCP L2 Relay Configuration";
L7_char8 *pStrInfo_switching_DhcpL2RelayIntfCfg = "DHCP L2 Relay Interface Configuration";
L7_char8 *pStrInfo_switching_DhcpL2RelayVlanCfg = "DHCP L2 Relay VLAN Configuration";
L7_char8 *pStrInfo_switching_DhcpL2RelayIntfStats = "DHCP L2 Relay Interface Statistics";
L7_char8 *pStrInfo_switching_DhcpL2RelayIntfSubscriptionCfg = "DHCP L2 Relay Interface Subscription Configuration";
L7_char8 *pStrInfo_switching_DhcpL2RelayIntfSubscriptionSummary = "DHCP L2 Relay Interface Subscription Summary";
L7_char8 *pStrInfo_switching_DhcpL2RelayIntfStatsDisp= "Listing all DHCP enabled interface Statistics.";
L7_char8 *pStrInfo_switching_DhcpL2RelayMode = "DHCP L2 Relay Mode";
L7_char8 *pStrInfo_switching_DhcpL2RelayTrustedState= "DHCP L2 Relay Trust Mode";
L7_char8 *pStrInfo_switching_DhcpL2RelayCircuitIdMode= "DHCP L2 Relay Circuit-Id";
L7_char8 *pStrInfo_switching_DhcpL2RelayRemoteIdString = "DHCP L2 Relay Remote-Id";
L7_char8 *pStrInfo_switching_DhcpL2RelaySubscriptionString = "Subscription";
L7_char8 *pStrInfo_switching_DhcpL2RelaySubscriptionEntry = "Subscription Entry";
L7_char8 *pStrInfo_switching_DhcpL2RelaySubscriptionName = "Subscription Name";

L7_char8 *pStrInfo_switching_DhcpL2RelayUntrustedSrvMsgsWithOpt82 = "Untrusted Server Msgs With Option-82";
L7_char8 *pStrInfo_switching_DhcpL2RelayUntrustedCliMsgsWithOpt82 = "Untrusted Client Msgs With Option-82";
L7_char8 *pStrInfo_switching_DhcpL2RelayTrustedSrvMsgsWithoutOpt82 = "Trusted Server Msgs Without Option-82";
L7_char8 *pStrInfo_switching_DhcpL2RelayTrustedliMsgsWithoutOpt82 = "Trusted Client Msgs Without Option-82";

L7_char8 *pStrInfo_switching_Dot3ahIntfStatsDisp="Listing all DOT3AH enabled interface Statistics.";

L7_char8 *pStrInfo_switching_Dot1adServiceConfig="Service Configuration";
L7_char8 *pStrInfo_switching_Dot1adServiceSumm ="Service Summary";
L7_char8 *pStrInfo_switching_Dot1adSubCfg ="Subscription Configuration";
L7_char8 *pStrInfo_switching_Dot1adSubSumm ="Subscription Summary";


L7_char8 *pStrInfo_switching_Dot1adHelpServiceConfig="href=\"/metro/dot1ad/help_dot1ad.html#service_cfg\"";
L7_char8 *pStrInfo_switching_Dot1adHelpServiceSumm ="href=\"/metro/dot1ad/help_dot1ad.html#service_summ\"";
L7_char8 *pStrInfo_switching_Dot1adHelpSubCfg ="href=\"/metro/dot1ad/help_dot1ad.html#subscrip_cfg\"";
L7_char8 *pStrInfo_switching_Dot1adHelpSubSumm ="href=\"/metro/dot1ad/help_dot1ad.html#subscrip_summ\"";

L7_char8 *pStrInfo_switching_Dot1adIntfType = "Interface Type Configuration";
L7_char8 *pStrInfo_switching_Dot1adTunnelCfg = "Tunnel Action Configuration";
L7_char8 *pStrInfo_switching_Dot1adHelpIntfTypeCfg = "href=\"/metro/dot1ad/help_dot1ad.html#interface_type_cfg\"";
L7_char8 *pStrInfo_switching_Dot1adHelpTunnelCfg = "href=\"/metro/dot1ad/help_dot1ad.html#tunnel_action_cfg\"";

