# $Id: Makefile,v 1.5.40.1 2013/05/10 04:08:39 kirankum Exp $
# $Copyright: (c) 2005 Broadcom Corp.
# All Rights Reserved.$

LOCALDIR = src/soc/kbp/alg_kbp

include ${SDK}/make/Make.config

subdirs += portability

include ${SDK}/make/Make.subdirs
include ${SDK}/make/Make.depend
