#
# $Id: Makefile,v 1.4 2016/10/10
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/trunk
include ${SDK}/make/Make.config

#subdirs = 

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxtrunk

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

