/*********************************************************************
*
* (C) Copyright Broadcom Corporation 2006-2007
*
**********************************************************************
*                                                                     
* @filename   src/nls/web/wireless/strlib_wireless_web.c                                                      
*                                                                     
* @purpose    Strings Library                                                      
*                                                                     
* @component  Common Strings Library                                                      
*                                                                     
* @comments   none                                                    
*                                                                     
* @create     03/22/2007                                                      
*                                                                     
* @author     Rama Sasthri, Kristipati                                
*                                                                     
* @end                                                                
*                                                                     
*********************************************************************/

#include "strlib_wireless_web.h"

L7_char8 *pStrErr_wireless_FailedToSetQueueVal = "%s, %s, %s.";
L7_char8 *pStrInfo_wireless_msec_1 = "%u msec";
L7_char8 *pStrInfo_wireless_HtmlFileWsApLocalApDbaseSumm = "/wireless/ap/local_ap_database_summ.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsApManagedApAdvanced = "/wireless/ap/managed_ap_advanced.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsApprofileNwCfgRw = "/wireless/approfile/network_cfg_rw.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsApprofileNwSumm = "/wireless/approfile/network_summ.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsApprofileProfileMgmtCfgRw = "/wireless/approfile/profile_management_cfg_rw.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsApprofileProfileVapSumm = "/wireless/approfile/profile_vap_summ.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsDiscDiscCfg = "/wireless/discovery/discovery_cfg.html";
L7_char8 *pStrInfo_wireless_Br_3 = "<BR>%s";
L7_char8 *pStrInfo_wireless_AKeyOfAlnumCharsMustBeSpecifiedForSelectedKeyIdx = "A key of %d alphanumeric characters must be specified for the selected key index %d.";
L7_char8 *pStrInfo_wireless_AifsMsecs = "AIFS (msecs)";
L7_char8 *pStrInfo_wireless_ApAuth = "Require Authentication Passphrase";
L7_char8 *pStrInfo_wireless_ApEdcaParams = "AP EDCA Parameters";
L7_char8 *pStrInfo_wireless_ApFailureStatusHours = "AP Failure Status Timeout (hours)";
L7_char8 *pStrInfo_wireless_ApIpAddr = "AP IP Address";
L7_char8 *pStrInfo_wireless_ApProfileNwCfg = "AP Profile/Network Configuration";
L7_char8 *pStrInfo_wireless_ApProfiles = "AP Profiles";
L7_char8 *pStrInfo_wireless_KnownClient = "Known Client";
L7_char8 *pStrInfo_wireless_ApValidation = "AP Validation Method";
L7_char8 *pStrInfo_wireless_ApReset = "AP reset.";
L7_char8 *pStrInfo_wireless_AccessPointAuthFailureStatus = "Access Point Authentication Failure Status";
L7_char8 *pStrInfo_wireless_AccessPointProfileGlobalCfg = "Access Point Profile Global Configuration";
L7_char8 *pStrInfo_wireless_AccessPointProfileQosCfg = "Access Point Profile QoS Configuration";
L7_char8 *pStrInfo_wireless_AccessPointProfileRadioCfg = "Access Point Profile Radio Configuration";
L7_char8 *pStrInfo_wireless_AccessPointProfileSummary = "Access Point Profile List";
L7_char8 *pStrInfo_wireless_AccessPointProfileVapCfg = "Access Point Profile VAP Configuration";
L7_char8 *pStrInfo_wireless_ApProfileRadioAntennaDiv = "Antenna Diversity";
L7_char8 *pStrInfo_wireless_ApProfileRadioAntennaSel = "Antenna Selection";
L7_char8 *pStrInfo_wireless_ApProfileRadioAntennaSelLeftMiddle = "left-middle";
L7_char8 *pStrInfo_wireless_ApProfileRadioAntennaSelLeftRight = "left-right";
L7_char8 *pStrInfo_wireless_ApProfileRadioAntennaSelMiddleRight = "middle-right";
L7_char8 *pStrInfo_wireless_AccessPointRfScanStatus = "Access Point RF Scan Status";
L7_char8 *pStrInfo_wireless_AccessPoint = "Access Point.";
L7_char8 *pStrInfo_wireless_Ack = "Acknowledge";
L7_char8 *pStrInfo_wireless_AckAll = "Acknowledge All Rogues";
L7_char8 *pStrInfo_wireless_AdHocClientStatus = "Ad Hoc Client Status";
L7_char8 *pStrInfo_wireless_AdHocClientStatusHours = "Ad Hoc Client Status Timeout (hours)";
L7_char8 *pStrInfo_wireless_AdHocClientEntries = "Ad Hoc client entries.";
L7_char8 *pStrInfo_wireless_AdminModeOperationalStatus = "Admin Mode - Operational Status";
L7_char8 *pStrInfo_wireless_AlgorithmComplete = "Algorithm Complete";
L7_char8 *pStrInfo_wireless_AlgorithmCompleteNoChange = "Algorithm Complete : No Change Required";
L7_char8 *pStrInfo_wireless_AlgorithmInProgress = "Algorithm in Progress";
L7_char8 *pStrInfo_wireless_AllowMac = "Allow MAC";
L7_char8 *pStrInfo_wireless_Apply = "Apply";
L7_char8 *pStrInfo_wireless_ApplyInProgress = "Apply in Progress";
L7_char8 *pStrInfo_wireless_ApplyingApProfileCfg = "Applying AP Profile Configuration";
L7_char8 *pStrInfo_wireless_AssociatedClientNeighborApStatus = "Associated Client Neighbor AP Status";
L7_char8 *pStrInfo_wireless_AssociatedClientQosStatus = "Associated Client QoS Status";
L7_char8 *pStrInfo_wireless_AssociatedClientStats = "Associated Client Statistics";
L7_char8 *pStrInfo_wireless_AssociatedClientStatus = "Associated Client Status";
L7_char8 *pStrInfo_wireless_AssociatedToManagedAp = "Associated to Managed AP";
L7_char8 *pStrInfo_wireless_AssociatedToPeerAp = "Associated to Peer AP.";
L7_char8 *pStrInfo_wireless_AssociatedToAp = "Associated to this AP";
L7_char8 *pStrInfo_wireless_AssociationFailures = "Association Failures";
L7_char8 *pStrInfo_wireless_AuthFailures = "Authentication Failures";
L7_char8 *pStrInfo_wireless_AuthPasswd = "Authentication Password";
L7_char8 *pStrInfo_wireless_AutoChannel = "Automatic Channel";
L7_char8 *pStrInfo_wireless_AutoEligible = "Auto Eligible";
L7_char8 *pStrInfo_wireless_AutoPower = "Automatic Power";
L7_char8 *pStrInfo_wireless_Basic = "Basic";
L7_char8 *pStrInfo_wireless_BeaconFrame = "Beacon Frame";
L7_char8 *pStrInfo_wireless_CcmpAes = "CCMP(AES)";
L7_char8 *pStrInfo_wireless_ChannelPlanModeNotManual = "The configured channel plan mode is %s.  Manual channel plan status is unavailable.";
L7_char8 *pStrInfo_wireless_PowerPlanModeNotManual = "The configured power adjustment mode is %s. Manual power adjustment status is unavailable.";
L7_char8 *pStrInfo_wireless_Manual = "Manual";
L7_char8 *pStrInfo_wireless_Interval = "Interval";
L7_char8 *pStrInfo_wireless_FixedTime = "Fixed Time";
L7_char8 *pStrInfo_wireless_ChannelPlanHistory = "Channel Plan History";
L7_char8 *pStrInfo_wireless_ChannelStatus = "Channel Status";
L7_char8 *pStrInfo_wireless_ChannelPower = "Channel/Power";
L7_char8 *pStrInfo_wireless_ChannelPowerCfg = "Channel/Power Configuration";
L7_char8 *pStrInfo_wireless_ClientAuthFailureStatus = "Client Authentication Failure Status";
L7_char8 *pStrInfo_wireless_ClientFailureStatusHours = "Client Failure Status Timeout (hours)";
L7_char8 *pStrInfo_wireless_ClientIsNotAssociated = "Client is not associated.";
L7_char8 *pStrInfo_wireless_ClientsNotDisassociated = "Clients could not be disassociated.";
L7_char8 *pStrInfo_wireless_Clients = "Clients";
L7_char8 *pStrInfo_wireless_CfgFailureElement = "Configuration Failure Element";
L7_char8 *pStrInfo_wireless_ConnFailed = "Conn Failed";
L7_char8 *pStrInfo_wireless_Copy = "Copy";
L7_char8 *pStrInfo_wireless_WsModeReasonCountryCodeChg = "Country code change in progress";
L7_char8 *pStrInfo_wireless_CurrentChannel = "Current Channel";
L7_char8 *pStrInfo_wireless_CurrentIteration = "Current Iteration";
L7_char8 *pStrInfo_wireless_CurrentPower = "Current Power";
L7_char8 *pStrInfo_wireless_CurrentReceiveStatus = "Current Receive Status";
L7_char8 *pStrInfo_wireless_DtimPeriodBeacons = "DTIM Period (# beacons)";
L7_char8 *pStrInfo_wireless_Data0Voice = "Data 0 (Voice)";
L7_char8 *pStrInfo_wireless_Data1Video = "Data 1 (Video)";
L7_char8 *pStrInfo_wireless_Data2BestEffort = "Data 2 (Best Effort)";
L7_char8 *pStrInfo_wireless_Data3Background = "Data 3 (Background)";
L7_char8 *pStrInfo_wireless_DataFrame = "Data Frame";
L7_char8 *pStrInfo_wireless_Debug_1 = "Debug";
L7_char8 *pStrErr_wireless_CantDelDefl = "Default AP Profile cannot be deleted.";
L7_char8 *pStrInfo_wireless_DelAllNeighbors = "Delete All Neighbors";
L7_char8 *pStrInfo_wireless_Deld = "Deleted";
L7_char8 *pStrInfo_wireless_DenyMac = "Deny MAC";
L7_char8 *pStrInfo_wireless_Disassociate = "Disassociate";
L7_char8 *pStrInfo_wireless_DisassociateAll = "Disassociate All";
L7_char8 *pStrInfo_wireless_GlobalCfg = "Global Configuration";
L7_char8 *pStrInfo_wireless_DiscCfg = "Discovery Configuration";
L7_char8 *pStrInfo_wireless_RadiusCfg = "RADIUS Client Configuration";
L7_char8 *pStrInfo_wireless_DiscBrReason = "Discovery<BR>Reason";
L7_char8 *pStrInfo_wireless_DownloadCount = "Download Count";
L7_char8 *pStrInfo_wireless_DetectedClientStatus = "Detected Client Status";
L7_char8 *pStrInfo_wireless_DuplicatesRcvd = "Duplicates Received";
L7_char8 *pStrInfo_wireless_Edit = "Edit";
L7_char8 *pStrInfo_wireless_Enabled = "Enabled";
L7_char8 *pStrInfo_wireless_EnblDebug = "Enable Debug";
L7_char8 *pStrInfo_wireless_EnblWlanSwitch = "Enable WLAN Switch";
L7_char8 *pStrErr_wireless_FailedToApply = "Failed to apply %s";
L7_char8 *pStrErr_wireless_FailedToStartConfigPush = "Failed to start configuration push for peer switch %s.";
L7_char8 *pStrErr_wireless_FailedToStartConfigPushMultiple = "Failed to start configuration push for one or more peer switches.";
L7_char8 *pStrErr_wireless_FailedAlreadyInProgress = "Failed - already in progress";
L7_char8 *pStrErr_wireless_FailedInternal = "Failed - internal";
L7_char8 *pStrErr_wireless_FailedManualModeNotCfgured = "Failed - manual mode not configured";
L7_char8 *pStrErr_wireless_FailedTimedOut = "Failed - timed out";
L7_char8 *pStrErr_wireless_FailedApEntries = "Failed AP entries.";
L7_char8 *pStrErr_wireless_FailedClientEntries = "Failed Client entries.";
L7_char8 *pStrErr_wireless_FailedToApplyManualChannelPlanLocallyApplyReqsAreSentToOtherPeerSwitchesInPeerGrp = "Failed to apply manual channel plan locally. Apply requests are sent to other peer switches in the Peer Group";
L7_char8 *pStrErr_wireless_FailedToApplyManualChannelPlan = "Failed to apply manual channel plan.";
L7_char8 *pStrErr_wireless_FailedToApplyManualPowerAdjustments = "Failed to apply manual power adjustments.";
L7_char8 *pStrErr_wireless_FailedToApplyManualPowerPlanLocallyApplyReqsAreSentToOtherPeerSwitchesInPeerGrp = "Failed to apply manual power plan locally. Apply requests are sent to other peer switches in the Peer Group";
L7_char8 *pStrErr_wireless_FailedToApplyPeerGrpChannelPlan = "Failed to apply peer group channel plan.";
L7_char8 *pStrErr_wireless_FailedToClrManualChannelPlan = "Failed to clear manual channel plan.";
L7_char8 *pStrErr_wireless_FailedToClrProposedPowerAdjustments = "Failed to clear proposed power adjustments.";
L7_char8 *pStrErr_wireless_FailedToDisassociate = "Failed to disassociate %s associated to %s.";
L7_char8 *pStrErr_wireless_FailedToGetLocalIpAddr = "Failed to get local IP Address.";
L7_char8 *pStrErr_wireless_FailedToStartManualChannelPlanLocallyStartReqsAreSentToOtherPeerSwitchesInPeerGrp = "Failed to start manual channel plan locally. Start requests are sent to other peer switches in the Peer Group";
L7_char8 *pStrErr_wireless_FailedToStartManualChannelPlan = "Failed to start manual channel plan.";
L7_char8 *pStrErr_wireless_FailedToStartManualPowerPlanLocallyStartReqsAreSentToOtherPeerSwitchesInPeerGrp = "Failed to start manual power plan locally. Start requests are sent to other peer switches in the Peer Group";
L7_char8 *pStrErr_wireless_FailedToStartPeerGrpChannelPlan = "Failed to start peer group channel plan.";
L7_char8 *pStrErr_wireless_FailedToStartPeerGrpPowerPlan = "Failed to start peer group power plan.";
L7_char8 *pStrErr_wireless_FailedToStartProposedPowerAdjustments = "Failed to start proposed power adjustments.";
L7_char8 *pStrErr_wireless_FailedToStartUpgrade = "Failed to start the upgrade.";
L7_char8 *pStrInfo_wireless_FailureGeneric = "Failure : Generic";
L7_char8 *pStrErr_wireless_FailureInvalidCodeVer = "Failure : Invalid Code Version";
L7_char8 *pStrErr_wireless_FailureInvalidCfgRcvd = "Failure : Invalid Configuration Received";
L7_char8 *pStrErr_wireless_FailureInvalidHardwareVer = "Failure : Invalid Hardware Version";
L7_char8 *pStrErr_wireless_FailureInvalidPktFmt = "Failure : Invalid Packet Format";
L7_char8 *pStrInfo_wireless_FailureOperationInProgress = "Failure : Operation In Progress";
L7_char8 *pStrInfo_wireless_FailureOperationTimedOut = "Failure : Operation Timed Out";
L7_char8 *pStrInfo_wireless_FileTypeInvalidOrErrorProcessingFile = "File type invalid or error processing file.";
L7_char8 *pStrInfo_wireless_FragThreshBytes = "Frag Threshold (bytes)";
L7_char8 *pStrInfo_wireless_GlobalRoutingDsbld = "Global Routing Disabled";
L7_char8 *pStrInfo_wireless_Ieee80211a = "IEEE 802.11a";
L7_char8 *pStrInfo_wireless_Ieee80211b = "IEEE 802.11b";
L7_char8 *pStrInfo_wireless_Ieee80211bg = "IEEE 802.11b/g";
L7_char8 *pStrInfo_wireless_Ieee80211an = "IEEE 802.11a/n";
L7_char8 *pStrInfo_wireless_Ieee80211bgn = "IEEE 802.11b/g/n";
L7_char8 *pStrInfo_wireless_Ieee80211_5_GHZ_N = "5GHz IEEE 802.11n";
L7_char8 *pStrInfo_wireless_Ieee80211_2_4_GHZ_N = "2.4GHz IEEE 802.11n";
L7_char8 *pStrInfo_wireless_IgnoreBcast = "Ignore Broadcast";
L7_char8 *pStrErr_wireless_WepKeyAsciiWepKeyForKeyIdxMayOnlyContainAlnumChars = "Invalid WEP Key, ASCII WEP Key for key index %d may only contain alphanumeric characters.";
L7_char8 *pStrErr_wireless_WepKeyAsciiKeyLenForKeyIdxShldBeEqualToChars = "Invalid WEP Key, ASCII key length for key index %d should be equal to %d characters.";
L7_char8 *pStrErr_wireless_WepKeyHexKeyLenForKeyIdxShldBeEqualToChars = "Invalid WEP Key, HEX key length for key index %d should be equal to %d characters.";
L7_char8 *pStrErr_wireless_WepKeyWepKeyForKeyIdxMayOnlyContainHexadecimalChars = "Invalid WEP Key, WEP Key for key index %d may only contain hexadecimal characters.";
L7_char8 *pStrErr_wireless_WpaKeyAsciiWpaKeyMayOnlyContainAlnumChars = "Invalid WPA Key, ASCII WPA Key may only contain alphanumeric characters.";
L7_char8 *pStrErr_wireless_FileTransferPleaseVerifyInputFile = "Invalid file transfer! Please verify input file.";
L7_char8 *pStrInfo_wireless_Iteration = "Iteration";
L7_char8 *pStrInfo_wireless_KeyCachingHoldTime = "Key Caching Hold Time";
L7_char8 *pStrInfo_wireless_KeyFwd = "Key Forwarding";
L7_char8 *pStrInfo_wireless_L2VlanDisc = "L2/VLAN Discovery";
L7_char8 *pStrInfo_wireless_L3Tunnel = "L3 Tunnel";
L7_char8 *pStrInfo_wireless_L3TunnelMask = "L3 Tunnel Mask";
L7_char8 *pStrInfo_wireless_L3TunnelSubnet = "L3 Tunnel Subnet";
L7_char8 *pStrErr_wireless_L3IpDisc = "L3/IP Discovery";
L7_char8 *pStrInfo_wireless_LongRetries = "Long Retries";
L7_char8 *pStrInfo_wireless_Manage = "Manage";
L7_char8 *pStrInfo_wireless_ManagedAp = "Managed AP";
L7_char8 *pStrInfo_wireless_ManagedApAdvanced = "Managed AP Advanced Settings";
L7_char8 *pStrInfo_wireless_ManagedApChannelPowerAdjust = "Managed AP Channel/Power Adjust";
L7_char8 *pStrInfo_wireless_ManagedApDebug = "Managed AP Debug";
L7_char8 *pStrInfo_wireless_ManagedApReset = "Managed AP Reset";
L7_char8 *pStrInfo_wireless_ManagedApBrCount = "Managed AP<BR>Count";
L7_char8 *pStrInfo_wireless_ManagedAccessPointNeighborApStatus = "Managed Access Point Neighbor AP Status";
L7_char8 *pStrInfo_wireless_ManagedAccessPointNeighborClientStatus = "Managed Access Point Neighbor Client Status";
L7_char8 *pStrInfo_wireless_ManagedAccessPointRadioStatus = "Managed Access Point Radio Status";
L7_char8 *pStrInfo_wireless_ManagedAccessPointStats = "Managed Access Point Statistics";
L7_char8 *pStrInfo_wireless_ManagedAccessPointStatus = "Managed Access Point Status";
L7_char8 *pStrInfo_wireless_ManagedAccessPointVapStatus = "Managed Access Point VAP Status";
L7_char8 *pStrInfo_wireless_ManagedMode = "AP Mode";
L7_char8 *pStrInfo_wireless_ManualChannelPlan = "Manual Channel Plan";
L7_char8 *pStrInfo_wireless_ManualPowerAdjustments = "Manual Power Adjustments";
L7_char8 *pStrInfo_wireless_MaxBurstMicroSecs = "Max. Burst (&micro";
L7_char8 *pStrInfo_wireless_MaxBurstMicroSecs_1 = "Max. Burst (&micro;secs)";
L7_char8 *pStrInfo_wireless_NoChannelsAreCurrentlySupported = "No channels are currently supported.";
L7_char8 *pStrInfo_wireless_StartAll = "Start All";
L7_char8 *pStrInfo_wireless_RegulatoryDomain = "Regulatory Domain";
L7_char8 *pStrInfo_wireless_PeerSwitchConfigurationReceiveStatus = "Peer Switch Configuration Receive Status";
L7_char8 *pStrInfo_wireless_PeerSwitchConfigurationRequestStatus = "Peer Switch Configuration Request Status";
L7_char8 *pStrInfo_wireless_PeerSwitchConfigurationEnableDisable = "Peer Switch Configuration Enable/Disable";
L7_char8 *pStrInfo_wireless_PeerSwitchManagedAPStatus = "Peer Switch Managed AP Status";
L7_char8 *pStrInfo_wireless_PeerSwitchConfigurationStatus = "Peer Switch Configuration Status";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpConfigurationReceiveStatus = "href=\"/wireless/help/cp_recv_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpConfigurationSendStatus = "href=\"/wireless/help/cp_send_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpConfigurationConfig = "href=\"/wireless/help/cp_config.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpPeerManagedAPStatus = "href=\"/wireless/help/peer_managed_ap_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiPeerManagedAPStatus = "href=\"/help_PeerSwitchManagedAPStatus.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpConfigurationPeerReceiveStatus = "href=\"/wireless/help/cp_peer_recv_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiConfigurationPeerReceiveStatus = "href=\"/help_PeerSwitchConfigStatus.html\"";
L7_char8 *pStrInfo_wireless_NewChannel = "New Channel";
L7_char8 *pStrInfo_wireless_NewPower = "New Power";
L7_char8 *pStrInfo_wireless_Next = "Next";
L7_char8 *pStrInfo_wireless_NoActiveIntf = "No Active Interface for Statically Configured IP";
L7_char8 *pStrInfo_wireless_NoApProfileEntryExistsCfgureAnApProfile = "No AP Profile entry exists. Configure an AP Profile.";
L7_char8 *pStrInfo_wireless_NoApAuthFailureEntriesExist = "No AP authentication failure entries exist.";
L7_char8 *pStrInfo_wireless_NoApSShldBeSelectedWithAllOption = "No AP(s) should be selected with the 'All' option.";
L7_char8 *pStrInfo_wireless_NoAdHocClientsDetected = "No Ad Hoc clients detected.";
L7_char8 *pStrInfo_wireless_NoDetectedClientEntries = "No Detected Clients.";
L7_char8 *pStrInfo_wireless_NoKnownClientEntries = "No Known Client entries exist.";
L7_char8 *pStrInfo_wireless_BcastKeyRefreshRate="Bcast Key Refresh Rate";
L7_char8 *pStrInfo_wireless_SessionKeyRefreshRate="Session Key Refresh Rate";
L7_char8 *pStrInfo_wireless_NoLoopbackIntf = "No Loopback Interface";
L7_char8 *pStrInfo_wireless_NoNeighborApsExist = "No Neighbor APs exist.";
L7_char8 *pStrInfo_wireless_NoNeighborClientsExist = "No Neighbor clients exist.";
L7_char8 *pStrInfo_wireless_NoPeerManagedApsExist = "No Peer Managed APs exist.";
L7_char8 *pStrInfo_wireless_NoRfScanEntriesExist = "No RF Scan entries exist.";
L7_char8 *pStrInfo_wireless_NoRfScanEntryNotExist = "Selected RF Scan entry does not exist.";
L7_char8 *pStrInfo_wireless_NoAssociatedClients = "No associated clients.";
L7_char8 *pStrInfo_wireless_NoChannelPlanHistoryEntriesExist = "No channel plan history entries exist.";
L7_char8 *pStrInfo_wireless_NoClientManagedApAssociations = "No client Managed AP associations.";
L7_char8 *pStrInfo_wireless_NoClientAuthFailureEntriesExist = "No client authentication failure entries exist.";
L7_char8 *pStrInfo_wireless_NoDataAvailableForPeerSwitchStatus = "No data available for peer switch status.";
L7_char8 *pStrInfo_wireless_NoEntriesCfguredInIpPollingList = "No entries configured in the IP Polling List.";
L7_char8 *pStrInfo_wireless_NoManagedAccessPointsExist = "No managed access points exist.";
L7_char8 *pStrInfo_wireless_NoProposedChannelPlanEntriesExist = "No proposed channel plan entries exist.";
L7_char8 *pStrInfo_wireless_NoProposedPowerAdjustmentEntriesExist = "No proposed power adjustment entries exist.";
L7_char8 *pStrInfo_wireless_PeerIpAddr = "Peer IP Address";
L7_char8 *pStrInfo_wireless_PeerManagedApMac = "Peer Managed AP MAC";
L7_char8 *pStrInfo_wireless_PeerSwitchStatus = "Peer Switch Status";
L7_char8 *pStrInfo_wireless_Pending = "Pending";
L7_char8 *pStrInfo_wireless_PleaseMakeSelectionByClickingOnCheckBox = "Please make a selection by clicking on one or more of the check boxes.";
L7_char8 *pStrInfo_wireless_Power = "Power";
L7_char8 *pStrInfo_wireless_Power_1 = "Power (%)";
L7_char8 *pStrInfo_wireless_PowerAdjustmentIntvlMinutes = "Power Adjustment Interval (minutes)";
L7_char8 *pStrInfo_wireless_PowerAdjustmentMode = "Power Adjustment Mode";
L7_char8 *pStrInfo_wireless_PowerStatus = "Power Status";
L7_char8 *pStrInfo_wireless_PreAuth = "Pre-Authentication";
L7_char8 *pStrInfo_wireless_PreAuthLimit = "Pre-Authentication Limit";
L7_char8 *pStrInfo_wireless_ProbeReq = "Probe Request";
L7_char8 *pStrInfo_wireless_ProfileNameMustContainAlnumCharsOnly = "Profile Name must contain alphaNumeric characters only.";
L7_char8 *pStrInfo_wireless_ProtoBrVer = "Protocol<BR>Version";
L7_char8 *pStrInfo_wireless_Queue = "Queue";
L7_char8 *pStrInfo_wireless_RadiusIpAddr = "RADIUS IP Address";
L7_char8 *pStrInfo_wireless_RadiusSecret = "RADIUS Secret";
L7_char8 *pStrInfo_wireless_RadiusSrvrSecret = "RADIUS Server Secret";
L7_char8 *pStrInfo_wireless_RfCfg = "RF Configuration";
L7_char8 *pStrInfo_wireless_RfScanDiscovered = "RF Scan";
L7_char8 *pStrInfo_wireless_RfScanDurationMsecs = "RF Scan Duration (msecs)";
L7_char8 *pStrInfo_wireless_RfScanIntvlSecs = "RF Scan Interval (secs)";
L7_char8 *pStrInfo_wireless_RfScanOtherChannels = "RF Scan Other Channels";
L7_char8 *pStrInfo_wireless_RfScanSentry = "RF Scan Sentry";
L7_char8 *pStrInfo_wireless_RfScanSentryChannels = "RF Scan Sentry Channels";
L7_char8 *pStrInfo_wireless_RfScanStatusHours = "RF Scan Status Timeout (hours)";
L7_char8 *pStrInfo_wireless_RfScanEntries = "RF Scan entries.";
L7_char8 *pStrInfo_wireless_RadarDetected = "Radar Detected";
L7_char8 *pStrInfo_wireless_RadarDetectionRequired = "Radar Detection Required";
L7_char8 *pStrInfo_wireless_RateLimitPktsSec = "Rate Limit (pkts/sec)";
L7_char8 *pStrInfo_wireless_RateLimitBurstPktsSec = "Rate Limit Burst (pkts/sec)";
L7_char8 *pStrInfo_wireless_RateLimiting = "Rate Limiting";
L7_char8 *pStrInfo_wireless_RateSetsMbps = "Rate Sets (Mbps)";
L7_char8 *pStrInfo_wireless_ReceiveLifetimeMsecs = "Receive Lifetime (msecs)";
L7_char8 *pStrInfo_wireless_ReceivingCfg = "Receiving Configuration";
L7_char8 *pStrInfo_wireless_ResetAll = "Reset All";
L7_char8 *pStrInfo_wireless_SsidAssociatedClientStatus = "SSID Associated Client Status";
L7_char8 *pStrInfo_wireless_SsidNotSpecified = "SSID not specified.";
L7_char8 *pStrInfo_wireless_SavingCfg = "Saving Configuration";
L7_char8 *pStrInfo_wireless_Redirect = "Redirect";
L7_char8 *pStrInfo_wireless_Security = "Security";
L7_char8 *pStrInfo_wireless_SendReqed = "Send Requested";
L7_char8 *pStrInfo_wireless_SendInProgress = "Send in Progress";
L7_char8 *pStrInfo_wireless_SendingCfg = "Sending Configuration";
L7_char8 *pStrInfo_wireless_SentDisassociateReqToManagedApForFollowingClients = "Sent disassociate request to the managed AP for the following clients:";
L7_char8 *pStrInfo_wireless_SetComplete = "Set Complete";
L7_char8 *pStrInfo_wireless_SetFailed = "Set Failed";
L7_char8 *pStrInfo_wireless_SetReqed = "Set Requested";
L7_char8 *pStrInfo_wireless_SetInProgress = "Set in Progress";
L7_char8 *pStrInfo_wireless_ShortRetries = "Short Retries";
L7_char8 *pStrInfo_wireless_SoftwareBrVer = "Software<BR>Version";
L7_char8 *pStrInfo_wireless_StartReqed = "Start Requested";
L7_char8 *pStrInfo_wireless_StationEdcaParams = "Station EDCA Parameters";
L7_char8 *pStrInfo_wireless_SuccessfullyDeldAllAdHocClientEntries = "Successfully deleted all Ad Hoc client entries.";
L7_char8 *pStrErr_wireless_SuccessfullyDeldAllFailedApEntries = "Successfully deleted all Failed AP entries.";
L7_char8 *pStrInfo_wireless_SuccessfullyDeldAllRfScanEntries = "Successfully deleted all RF Scan Entries.";
L7_char8 *pStrInfo_wireless_SuccessfullyDeldAllFailedClientEntries = "Successfully deleted all failed client entries.";
L7_char8 *pStrErr_wireless_SuccessfullyDeldFollowingFailedAps = "Successfully deleted following Failed APs:";
L7_char8 *pStrInfo_wireless_SuccessfullyDisassociatedClient = "Successfully disassociated the client.";
L7_char8 *pStrInfo_wireless_SuccessfullyDeldAllDetectedClientEntries = "Successfully deleted all non-authenticated Detected Client Entries.";
L7_char8 *pStrInfo_wireless_SuccessfullyDeldAllKnownClientEntries = "Successfully deleted all Known Client Entries.";
L7_char8 *pStrErr_wireless_SuccessfullyDelFollowingDetectedClients = "Successfully deleted following Detected Clients:";
L7_char8 *pStrErr_wireless_SuccessfullyResetManagedAps = "Successfully reset the following managed APs:";
L7_char8 *pStrErr_wireless_SuccessfullyDelFollowingLocalAps = "Successfully deleted following local APs:";
L7_char8 *pStrErr_wireless_NonAuthDetectedClientEntries = "Non-authenticated Detected Client entries.";
L7_char8 *pStrErr_wireless_KnownClientEntries = "Known Client entries.";
L7_char8 *pStrErr_wireless_DetectedRogueClientEntries = "Detected Rogue Client entry(s}.";
L7_char8 *pStrErr_wireless_FailedToAck = "Failed to Acknowledge %s.";
L7_char8 *pStrInfo_wireless_SuccessfullyAckedDetectedRogueClientEntries = "Successfully acknowledged all Detected Rogue Client Entries.";
L7_char8 *pStrInfo_wireless_Supported = "Supported";
L7_char8 *pStrInfo_wireless_SupportedChannel = "Supported Channel";
L7_char8 *pStrInfo_wireless_SupportedChannels = "Supported Channels";
L7_char8 *pStrInfo_wireless_ChannelBandwidth = "Channel Bandwidth";
L7_char8 *pStrInfo_wireless_PrimaryChannel   = "Primary Channel";
L7_char8 *pStrInfo_wireless_Lower            = "Lower";
L7_char8 *pStrInfo_wireless_Upper            = "Upper";
L7_char8 *pStrInfo_wireless_TxopLimitMsecs = "TXOP Limit (msecs)";
L7_char8 *pStrInfo_wireless_FollowingApMacAddrEsWereCfguredAsValidApSManagedWithDeflProfileApSWillBeManagedAtNextDisc = "The following AP MAC address(es) were configured as Valid AP(s) managed with the default profile, the AP(s) will be managed at next discovery:";
L7_char8 *pStrInfo_wireless_FollowingApMacAddrEsWereCfguredAsValidApSWithAnAckdRogueStatusApSWillNotBeDetectedAsRogueAtNextDisc = "The initially detected AP state has been restored for the following AP MAC address(es):";
L7_char8 *pStrInfo_wireless_SubnetIsAlreadyAssignedToAnotherNw = "This subnet is already assigned to another network.";
L7_char8 *pStrInfo_wireless_TimeSinceRadarLastDetected = "Time Since Radar Last Detected";
L7_char8 *pStrInfo_wireless_TxLifetimeMsecs = "Transmit Lifetime (msecs)";
L7_char8 *pStrInfo_wireless_TxRate_1 = "Transmit Rate";
L7_char8 *pStrInfo_wireless_TxRetries = "Transmit Retries";
L7_char8 *pStrInfo_wireless_TxRetriesFailed = "Transmit Retries Failed";
L7_char8 *pStrInfo_wireless_TunnelIpMtuSize = "Tunnel IP MTU Size";
L7_char8 *pStrInfo_wireless_MACAuthMode_1 = "MAC Authentication Mode";
L7_char8 *pStrInfo_wireless_UnableToCfgureFollowingApMacAddrEsAsValidApSManagedWithDeflProfileCurrentStatusOfApSIsManaged = "Unable to configure the following AP MAC address(es) as Valid AP(s) managed with the default profile (the current status of AP(s) is Managed)";
L7_char8 *pStrInfo_wireless_UnableToCfgureFollowingApMacAddrEsAsValidApSManagedWithDeflProfileCurrentStatusOfApSIsManaged_1 = "Unable to configure the following AP MAC address(es) as Valid AP(s) managed with the default profile (the current status of AP(s) is Managed):";
L7_char8 *pStrInfo_wireless_UnableToCfgureFollowingApMacAddrEsAsValidApSManagedWithDeflProfile = "Unable to configure the following AP MAC address(es) as Valid AP(s) managed with the default profile:";
L7_char8 *pStrInfo_wireless_UnableToCfgureFollowingApMacAddrEsAsValidApSWithAnAckdRogueStatusCurrentStatusOfApSIsAck = "Unable to restore the initial state for the following AP MAC address(es):";
L7_char8 *pStrInfo_wireless_UseProfile = "Use Profile";
L7_char8 *pStrInfo_wireless_VapAssociatedClientStatus = "VAP Associated Client Status";
L7_char8 *pStrInfo_wireless_VapMode = "VAP Mode";
L7_char8 *pStrInfo_wireless_Vlan14094 = "VLAN (1-4094)";
L7_char8 *pStrInfo_wireless_ValidApDbaseCfg = "Valid AP Database Configuration";
L7_char8 *pStrInfo_wireless_ValidAccessPointCfg = "Valid Access Point Configuration";
L7_char8 *pStrInfo_wireless_ValidAccessPointSummary = "Valid Access Point Summary";
L7_char8 *pStrInfo_wireless_OUIDataBaseSummary= "Local OUI Database Summary";
L7_char8 *pStrInfo_wireless_ValidationFailures = "Validation Failures";
L7_char8 *pStrInfo_wireless_VendorBrId = "Vendor<BR>ID";
L7_char8 *pStrInfo_wireless_Wep = "WEP";
L7_char8 *pStrInfo_wireless_WepIeee8021x = "WEP IEEE802.1x";
L7_char8 *pStrInfo_wireless_WepKeys = "WEP Keys";
L7_char8 *pStrInfo_wireless_WlanSwitchOperationalStatus = "WLAN Switch Operational Status";
L7_char8 *pStrInfo_wireless_WsCentTnnlCfg = "Centralized L2 Tunnel Configuration";
L7_char8 *pStrInfo_wireless_WsCentTnnlStatus = "Centralized L2 Tunnel Status";
L7_char8 *pStrInfo_wireless_WsDeflProfileCfg = "Wireless Default Profile Configuration";
L7_char8 *pStrInfo_wireless_WsDeflRadioCfg = "Wireless Default Radio Configuration";
L7_char8 *pStrInfo_wireless_WsDeflVapCfg = "Wireless Default VAP Configuration";
L7_char8 *pStrInfo_wireless_WsDiscCfg = "Wireless Discovery Configuration";
L7_char8 *pStrInfo_wireless_WsDiscStatus = "Wireless Discovery Status";
L7_char8 *pStrInfo_wireless_WsGlobalCfg = "Wireless Global Configuration";
L7_char8 *pStrInfo_wireless_WsGlobalStatusStats = "Wireless Global Status/Statistics";
L7_char8 *pStrInfo_wireless_WsNwCfg = "Wireless Network Configuration";
L7_char8 *pStrInfo_wireless_WsNwSummary = "Wireless Network List";
L7_char8 *pStrInfo_wireless_WsSnmpTrapCfg = "Wireless SNMP Trap Configuration";
L7_char8 *pStrInfo_wireless_WsSoftwareDownload = "Access Point Software Download";
L7_char8 *pStrInfo_wireless_APImageVersion = "Integrated AP Image Availability";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpAPImageVersion = "href=\"/wireless/help/ap_image_version.html\"";
L7_char8 *pStrInfo_wireless_WsStats = "Wireless Statistics";
L7_char8 *pStrInfo_wireless_Age = "age:\"%s\"}";
L7_char8 *pStrInfo_wireless_NwTime = "nwtime:\"%s\"}";
L7_char8 *pStrInfo_wireless_Age_1 = "age:\"%s\",";
L7_char8 *pStrInfo_wireless_AgeError = "age:\"error\"}";
L7_char8 *pStrInfo_wireless_NwTimeError = "Network Time:\"error\"}";
L7_char8 *pStrInfo_wireless_CreateTime = "createTime:\"%s\"}";
L7_char8 *pStrInfo_wireless_CreateTimeError = "createTime:\"error\"}";
L7_char8 *pStrInfo_wireless_Ap_1 = "ap:\"%02x:%02x:%02x:%02x:%02x:%02x\",";
L7_char8 *pStrInfo_wireless_ApImage1Filename = "ap_image1_filename";
L7_char8 *pStrInfo_wireless_ApImage1Filepath = "ap_image1_filepath";
L7_char8 *pStrInfo_wireless_ApImage2Filename = "ap_image2_filename";
L7_char8 *pStrInfo_wireless_ApImage2Filepath = "ap_image2_filepath";
L7_char8 *pStrInfo_wireless_ApImage3Filename = "ap_image3_filename";
L7_char8 *pStrInfo_wireless_ApImage3Filepath = "ap_image3_filepath";
L7_char8 *pStrInfo_wireless_ApImage4Filename = "ap_image4_filename";
L7_char8 *pStrInfo_wireless_ApImage4Filepath = "ap_image4_filepath";
L7_char8 *pStrInfo_wireless_Apmac = "apmac:\"%02x:%02x:%02x:%02x:%02x:%02x\",";
L7_char8 *pStrInfo_wireless_Authclients2 = "authclients2:\"%d\"}";
L7_char8 *pStrInfo_wireless_Authclients2_1 = "authclients2:\"%s\"}";
L7_char8 *pStrInfo_wireless_Authclients2Error = "authclients2:\"error\"}";
L7_char8 *pStrInfo_wireless_Authclients = "authclients:\"%d\"}";
L7_char8 *pStrInfo_wireless_Authclients_1 = "authclients:\"%s\"}";
L7_char8 *pStrInfo_wireless_AuthclientsError = "authclients:\"error\"}";
L7_char8 *pStrInfo_wireless_Bssid_1 = "bssid:\"%02x:%02x:%02x:%02x:%02x:%02x\",";
L7_char8 *pStrInfo_wireless_BssidError = "bssid:\"error\",";
L7_char8 *pStrInfo_wireless_Bytesrx = "bytesRx:\"%llu\",";
L7_char8 *pStrInfo_wireless_Bytestx = "bytesTx:\"%llu\"}";
L7_char8 *pStrInfo_wireless_Cfgstate = "cfgstate:\"%s\",";
L7_char8 *pStrInfo_wireless_Cfgstate_1 = "cfgstate:\"%s\"}";
L7_char8 *pStrInfo_wireless_CfgstateError = "cfgstate:\"error\"";
L7_char8 *pStrInfo_wireless_Chan = "chan:\"%d\",";
L7_char8 *pStrInfo_wireless_Chan_1 = "chan:\"%u\",";
L7_char8 *pStrInfo_wireless_ChanError = "chan:\"error\",";
L7_char8 *pStrInfo_wireless_Channel2 = "channel2:\"%s\",";
L7_char8 *pStrInfo_wireless_Channel2_1 = "channel2:\"%u\",";
L7_char8 *pStrInfo_wireless_Channel2Error = "channel2:\"error\",";
L7_char8 *pStrInfo_wireless_Channel_2 = "channel:\"%s\",";
L7_char8 *pStrInfo_wireless_Channel_3 = "channel:\"%u\",";
L7_char8 *pStrInfo_wireless_ChannelError = "channel:\"error\",";
L7_char8 *pStrInfo_wireless_ChannelIntvl = "channel_interval";
L7_char8 *pStrInfo_wireless_HtmlFileChannelPlanStatus = "channel_plan_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileChannelPwrAdjust = "channel_pwr_adjust.html";
L7_char8 *pStrInfo_wireless_HtmlFileChannelPwrCfg = "channel_pwr_cfg.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientAdhocStatus = "client_adhoc_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientAdhocStatusSumm = "client_adhoc_status_summ.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientFailureStatus = "client_failure_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientFailureStatusSumm = "client_failure_status_summ.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientNbrapStatus = "client_nbrap_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientQosStatus = "client_qos_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientSsidStatus = "client_ssid_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientStats = "client_statistics.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientStatus = "client_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientStatusDetail = "client_status_detail.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientVapStatus = "client_vap_status.html";
L7_char8 *pStrInfo_wireless_Clientmac = "clientmac:\"%02x:%02x:%02x:%02x:%02x:%02x\"}";
L7_char8 *pStrInfo_wireless_Clients2 = "clients2:\"%d\",";
L7_char8 *pStrInfo_wireless_Clients2_1 = "clients2:\"%s\",";
L7_char8 *pStrInfo_wireless_Clients2Error = "clients2:\"error\",";
L7_char8 *pStrInfo_wireless_Clients_1 = "clients:\"%d\",";
L7_char8 *pStrInfo_wireless_Clients_2 = "clients:\"%s\",";
L7_char8 *pStrInfo_wireless_ClientsError = "clients:\"error\",";
L7_char8 *pStrInfo_wireless_HtmlFileCpCfg = "cp_config.html";
L7_char8 *pStrInfo_wireless_HtmlFileCpPeerRecvStatus = "cp_peer_recv_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileCpRecvStatus = "cp_recv_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileCpSendStatus = "cp_send_status.html";
L7_char8 *pStrInfo_wireless_CwmaxMsecs = "cwMax (msecs)";
L7_char8 *pStrInfo_wireless_CwminMsecs = "cwMin (msecs)";
L7_char8 *pStrErr_wireless_DelFailedAp = "delete the Failed AP.";
L7_char8 *pStrErr_wireless_DelFailedManagedAp = "Could not delete the following AP(s), as they become managed.";
L7_char8 *pStrErr_wireless_FailedDelAp = "Failed to delete the AP.";
L7_char8 *pStrErr_wireless_FailedDelOui = "Failed to delete the OUI.";
L7_char8 *pStrErr_wireless_ApResetNeed = "Reset managed AP(s) deleted from the AP database.";
L7_char8 *pStrInfo_wireless_DelNonAuthClient = "Delete";
L7_char8 *pStrInfo_wireless_DisassociateClientsFromSsidS = "disassociate clients from SSID(s).";
L7_char8 *pStrInfo_wireless_DisassociateClientsFromVapS = "disassociate clients from VAP(s).";
L7_char8 *pStrInfo_wireless_HtmlFileCentTnnlCfg = "cent_tnnl_cfg.html";
L7_char8 *pStrInfo_wireless_HtmlFileCentTnnlStatus = "cent_tnnl_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileDiscCfg = "discovery_cfg.html";
L7_char8 *pStrInfo_wireless_HtmlFileDiscStatus = "discovery_status.html";
L7_char8 *pStrInfo_wireless_DownloadGrpSize = "download_group_size";
L7_char8 *pStrInfo_wireless_DnldType = "download_type";
L7_char8 *pStrInfo_wireless_HtmlFileGlobal = "global.html";
L7_char8 *pStrInfo_wireless_HistoryDepth_2 = "history_depth";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpAaaRadius = "href=\"/wireless/help/hardware.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpAdHocClient = "href=\"/wireless/help/ad_hoc_client.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiAdHocClient = "href=\"/help_AdhocClients.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpAdvancedGlobalSettings = "href=\"/wireless/help/advanced_global_settings.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpApDebug = "href=\"/wireless/help/ap_debug.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiApDebug = "href=\"/help_ManagedAPAdvanced.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpApDebug2 = "href=\"/wireless/help/ap_debug2.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpApFailure = "href=\"/wireless/help/ap_failure.html\"";
 L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiApFailure = "href=\"/help_APAuthFailures.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpApFailureDetail = "href=\"/wireless/help/ap_failure_detail.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpApProfileSummary = "href=\"/wireless/help/ap_profile_summary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpApReset = "href=\"/wireless/help/ap_reset.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiApReset = "href=\"/help_ManagedAPReset.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpApUpgrade = "href=\"/wireless/help/ap_upgrade.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiApUpgrade = "href=\"/help_SoftwareDownload.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpCentTnnlCfg = "href=\"/wireless/help/cent_tnnl_cfg.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpCentTnnlStatus = "href=\"/wireless/help/cent_tnnl_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpChannelHistory = "href=\"/wireless/help/channel_history.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpClientAssociationDetail = "href=\"/wireless/help/client_association_detail.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpClientAssociationSummary = "href=\"/wireless/help/client_association_summary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiClientAssociationSummary = "href=\"/help_AssocClientsStatisticsAssocSummary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpClientFailure = "href=\"/wireless/help/client_failure.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpClientFailureDetail = "href=\"/wireless/help/client_failure_detail.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpClientSessionDetail = "href=\"/wireless/help/client_session_detail.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpClientSessionSummary = "href=\"/wireless/help/client_session_summary.html\"";
 L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiClientSessionSummary = "href=\"/help_AssocClientStatisticsSessionSummary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpDisc = "href=\"/wireless/help/discovery.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpDiscStatus = "href=\"/wireless/help/discovery_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpGlobalCfg = "href=\"/wireless/help/global_config.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpGlobalStatus = "href=\"/wireless/help/global_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApClientNeighborStatus = "href=\"/wireless/help/managed_ap_client_neighbor_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiManagedApClientNeighborStatus = "href=\"/help_AssocClientNeighborAPs.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApClientQosStatus = "href=\"/wireless/help/managed_ap_client_qos_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiManagedApClientQosStatus = "href=\"/help_AssocClientStatusClientQoS.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApClientSsidStatus = "href=\"/wireless/help/managed_ap_client_ssid_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiManagedApClientSsidStatus = "href=\"/help_AssocClientSSIDStatus.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApClientStatus = "href=\"/wireless/help/managed_ap_client_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiManagedApClientStatus = "href=\"/help_AssocClientStatusSummary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApClientStatusDetail = "href=\"/wireless/help/managed_ap_client_status_detail.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiManagedApClientStatusDetail = "href=\"/help_AssocClientStatusDetail.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApClientVapStatus = "href=\"/wireless/help/managed_ap_client_vap_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiManagedApClientVapStatus = "href=\"/help_AssocClientVAPStatus.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApEthStats = "href=\"/wireless/help/managed_ap_eth_statistics.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiManagedApEthStats = "href=\"/help_ManagedAPstatisticsEthernetSummary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApNeighborAp = "href=\"/wireless/help/managed_ap_neighbor_ap.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiManagedApNeighborAp = "href=\"/help_ManagedAPStatusNeighborAPs.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApNeighborApClient = "href=\"/wireless/help/managed_ap_neighbor_ap_client.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiManagedApNeighborApClient = "href=\"/help_ManagedAPStatusNeighborClients.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApRadioDetail = "href=\"/wireless/help/managed_ap_radio_detail.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApRadioStats = "href=\"/wireless/help/managed_ap_radio_statistics.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApRadioStatus = "href=\"/wireless/help/managed_ap_radio_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiManagedApRadioStatus = "href=\"/help_ManagedAPStatusRadioSummary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApStatsDetail = "href=\"/wireless/help/managed_ap_statistics_detail.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApStatus = "href=\"/wireless/help/managed_ap_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiManagedApStatus = "href=\"/help_ManagedAPStatusSummary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApStatusDetail = "href=\"/wireless/help/managed_ap_status_detail.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApVapStats = "href=\"/wireless/help/managed_ap_vap_statistics.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApVapStatus = "href=\"/wireless/help/managed_ap_vap_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManagedApWlanStats = "href=\"/wireless/help/managed_ap_wlan_statistics.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiManagedApWlanStats = "href=\"/help_ManagedAPStatisticsWLANSummary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManualChannel = "href=\"/wireless/help/manual_channel.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpManualPower = "href=\"/wireless/help/manual_power.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpNetworkList = "href=\"/wireless/help/network_list.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpNwCfg = "href=\"/wireless/help/network_config.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpNvDownload = "href=\"/wireless/help/nv_download.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpPeerSwitchStatus = "href=\"/wireless/help/peer_switch_status.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiPeerSwitchStatus = "href=\"/help_PeerSwitchStatus.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpPowerChannelAdjust = "href=\"/wireless/help/power_channel_adjust.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpQosCfg = "href=\"/wireless/help/qos_config.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpKnownClientCfg = "href=\"/wireless/help/known_client.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiKnownClientCfg = "href=\"/help_KnownClientSummary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpKnownClientCfgDetail = "href=\"/wireless/help/known_client_config.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpRadioCfg = "href=\"/wireless/help/radio_config.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpRfCfg = "href=\"/wireless/help/rf_config.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpRfScan = "href=\"/wireless/help/rf_scan.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiRfScan = "href=\"/help_IntrusionDetectionRogueRFScan.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpRfScanDetail = "href=\"/wireless/help/rf_scan_detail.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiRfScanDetail = "href=\"/help_RogueRFScanStatus.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpSnmpTraps = "href=\"/wireless/help/snmp_traps.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpValidApCfg = "href=\"/wireless/help/valid_ap_config.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpValidApSummary = "href=\"/wireless/help/valid_ap_summary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiValidApSummary = "href=\"/help_ValidAccessPointSummary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpOUIDataBase = "href=\"/wireless/help/oui.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiOUIDataBase = "href=\"/help_WirelessOUI.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpVapCfg = "href=\"/wireless/help/vap_config.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpDetectedClientStatus = "href=\"/wireless/help/client_detected.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiDetectedClientStatus  = "href=\"/help_DetectedClientSummary.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpRegDomain = "href=\"/wireless/help/regulatory_domain.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpClientSwitchStatus = "href=\"/wireless/help/managed_ap_client_switch_status.html\"";
 L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiClientSwitchStatus = "href=\"/help_AssocClientSwitchStatus.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpDetectedClientDetailStatus = "href=\"/wireless/help/client_detected_detail.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiDetectedClientDetailStatus = "href=\"/help_DetectedClientStatus.html\"";

L7_char8 *pStrInfo_wireless_Ip_1 = "ip:\"%s\",";
L7_char8 *pStrInfo_wireless_IpError = "ip:\"error\",";
L7_char8 *pStrInfo_wireless_JsdataPeerAP = "jsData[%d] = {peerAP:\"%s\",";
L7_char8 *pStrInfo_wireless_JsdataPeerClient = "jsData[%d] = {peerClient:\"%s\",";
L7_char8 *pStrInfo_wireless_JsdataBssid = "jsData[%d]  = {bssid:\"%02x:%02x:%02x:%02x:%02x:%02x\",";
L7_char8 *pStrInfo_wireless_JsdataMac = "jsData[%d]  = {mac:\"%02x:%02x:%02x:%02x:%02x:%02x\",";
L7_char8 *pStrInfo_wireless_JsdataSsid = "jsData[%d]  = {ssid:\"%s\",";
L7_char8 *pStrInfo_wireless_JsdataMac_1 = "jsData[%d] = {mac:\"%02x:%02x:%02x:%02x:%02x:%02x\",";
L7_char8 *pStrInfo_wireless_JsdataOUI_1 = "jsData[%d] = {ouiVal:\"%02x:%02x:%02x\",";
L7_char8 *pStrInfo_wireless_JsdataMac_2 = "mac:\"%02x:%02x:%02x:%02x:%02x:%02x\",";
L7_char8 *pStrInfo_wireless_MacNull = "mac:\" \",";
L7_char8 *pStrInfo_wireless_Loc_1 = "loc:\" \",";
L7_char8 *pStrInfo_wireless_Loc_2 = "loc:\"%s\",";
L7_char8 *pStrInfo_wireless_LocError = "loc:\"error\",";
L7_char8 *pStrInfo_wireless_Name = "name:\"%s\",";
L7_char8 *pStrInfo_wireless_NameError = "name:\"error\",";
L7_char8 *pStrInfo_wireless_HtmlFileLocalApDbaseCfgRw = "local_ap_database_cfg_rw.html";
L7_char8 *pStrInfo_wireless_HtmlFileLocalApDbaseSumm = "local_ap_database_summ.html";
L7_char8 *pStrInfo_wireless_HtmlFileLocalOuiDbaseCfgRw = "local_oui_database_cfg_rw.html";
L7_char8 *pStrInfo_wireless_HtmlFileLocalOuiDbaseSumm = "local_oui_database_summ.html";
L7_char8 *pStrInfo_wireless_Mac_3 = "mac:\"%02x:%02x:%02x:%02x:%02x:%02x\",";
L7_char8 *pStrInfo_wireless_Mac_4 = "mac:\"%02x:%02x:%02x:%02x:%02x:%02x\"}";
L7_char8 *pStrInfo_wireless_Oui_1 = "oui:\"%s\"}";
L7_char8 *pStrInfo_wireless_OuiError = "oui:\"error\"}";
L7_char8 *pStrInfo_wireless_HtmlFileManChannelStatus = "man_channel_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileManPwrStatus = "man_pwr_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedApAdvanced = "managed_ap_advanced.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedApDebug = "managed_ap_debug.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedApDownload = "managed_ap_download.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedApReset = "managed_ap_reset.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedApStats = "managed_ap_statistics.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedApStatus = "managed_ap_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedApfailureStatus = "managed_apfailure_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedApfailureStatusSumm = "managed_apfailure_status_summ.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedApnbrapStatus = "managed_apnbrap_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedApnbrcltStatus = "managed_apnbrclt_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedApradioStatus = "managed_apradio_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedApradiovapStatus = "managed_apradiovap_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedAprfscanStatus = "managed_aprfscan_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileManagedAprfscanStatusSumm = "managed_aprfscan_status_summ.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientDetectedStatus = "client_detected_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileClientDetectedStatusSumm = "client_detected_status_summ.html";
L7_char8 *pStrInfo_wireless_Minutes_2 = "minutes";
L7_char8 *pStrInfo_wireless_Mode_3 = "mode:\"%s\",";
L7_char8 *pStrInfo_wireless_ModeError = "mode:\"error\",";
L7_char8 *pStrInfo_wireless_HtmlFileNwCfgRw = "network_cfg_rw.html";
L7_char8 *pStrInfo_wireless_HtmlFileNvImageMgmt = "nv_image_mgmt.html";
L7_char8 *pStrInfo_wireless_HtmlFilePeerManagedApStatus = "peer_managed_ap_status.html";
L7_char8 *pStrInfo_wireless_HtmlFilePeerWsStatus = "peer_ws_status.html";
L7_char8 *pStrInfo_wireless_Pktsrx = "pktsRx:\"%llu\",";
L7_char8 *pStrInfo_wireless_Pktstx = "pktsTx:\"%llu\",";
L7_char8 *pStrInfo_wireless_PowerIntvl = "power_interval";
L7_char8 *pStrInfo_wireless_Profile = "profile:\"%s\",";
L7_char8 *pStrInfo_wireless_Profile_1 = "profile:\"%u-%s\",";
L7_char8 *pStrInfo_wireless_Profile_2 = "profile:\"%u-%s\"}";
L7_char8 *pStrInfo_wireless_Profile_3 = "profile:\"%s\"}";
L7_char8 *pStrInfo_wireless_ProfileId_1 = "profile_id:\"%u\",";
L7_char8 *pStrInfo_wireless_ProfileError = "profile:\"error\",";
L7_char8 *pStrInfo_wireless_HtmlFileProfileMgmtCfgRw = "profile_management_cfg_rw.html";
L7_char8 *pStrInfo_wireless_HtmlFileProfileQosCfgRw = "profile_qos_cfg_rw.html";
L7_char8 *pStrInfo_wireless_HtmlFileProfileRadioCfgRw = "profile_radio_cfg_rw.html";
L7_char8 *pStrInfo_wireless_HtmlFileProfileSumm = "profile_summ.html";
L7_char8 *pStrInfo_wireless_Radio2 = "radio2:\"%u-%s\",";
L7_char8 *pStrInfo_wireless_Radio2Error = "radio2:\"error\",";
L7_char8 *pStrInfo_wireless_Radio = "radio:\"%d - %s\",";
L7_char8 *pStrInfo_wireless_Radio_1 = "radio:\"%d\",";
L7_char8 *pStrInfo_wireless_Radio_2 = "radio:\"%u-%s\",";
L7_char8 *pStrInfo_wireless_Radio_3 = "radio:\"%u\",";
L7_char8 *pStrInfo_wireless_RadioError = "radio:\"error\",";
L7_char8 *pStrInfo_wireless_Rssi = "rssi:\"%d\",";
L7_char8 *pStrInfo_wireless_SrvrAddr_1 = "server_addr";
L7_char8 *pStrInfo_wireless_Ssid_3 = "ssid:\"%s\",";
L7_char8 *pStrInfo_wireless_Oui= "oui:\"%s\",";
L7_char8 *pStrInfo_wireless_SsidError = "ssid:\"error\",";
L7_char8 *pStrInfo_wireless_Stat_1 = "stat:\"";
L7_char8 *pStrInfo_wireless_Stat_2 = "stat:\"%s\"}";
L7_char8 *pStrInfo_wireless_State_2 = "state:\"%s\",";
L7_char8 *pStrInfo_wireless_StateError = "state:\"error\"";
L7_char8 *pStrInfo_wireless_SwVersion_2 = "swversion:\"%s\",";
L7_char8 *pStrInfo_wireless_SwVersionError_2 = "swversion:\"error\"";
L7_char8 *pStrInfo_wireless_Status = "status:\"";
L7_char8 *pStrInfo_wireless_Status_1 = "status:\"%s\",";
L7_char8 *pStrInfo_wireless_StatusError = "status:\"error\",";
L7_char8 *pStrInfo_wireless_Txpower2 = "txpower2:\"%s\",";
L7_char8 *pStrInfo_wireless_Txpower2_1 = "txpower2:\"%u\",";
L7_char8 *pStrInfo_wireless_Txpower2Error = "txpower2:\"error\",";
L7_char8 *pStrInfo_wireless_Txpower = "txpower:\"%s\",";
L7_char8 *pStrInfo_wireless_Txpower_1 = "txpower:\"%u\",";
L7_char8 *pStrInfo_wireless_TxpowerError = "txpower:\"error\",";
L7_char8 *pStrInfo_wireless_Type_3 = "type:\"%s\",";
L7_char8 *pStrInfo_wireless_TypeError = "type:\"error\"";
L7_char8 *pStrInfo_wireless_TypeError_1 = "type:\"error\",";
L7_char8 *pStrInfo_wireless_HtmlFileWsCfg = "wireless_cfg.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsRadarChannel = "wireless_radar_channel.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsStatus = "wireless_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsTrapsCfg = "wireless_traps_cfg.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsAPHWCapability = "wireless_ap_hw_capability.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpAPHWCapability = "href=\"/wireless/help/ap_hw_capability.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsAPHWRadioCapability = "wireless_ap_hw_radio_capability.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpAPHWRadioCapability = "href=\"/wireless/help/ap_hw_radio_capability.html\"";
L7_char8 *pStrInfo_wireless_APHWCapability = "AP Hardware Capability";
L7_char8 *pStrInfo_wireless_APHWRadioCapability = "AP Hardware Radio Capability";
L7_char8 *pStrInfo_wireless_APHWTypeID = "Hardware Type ID";
L7_char8 *pStrInfo_wireless_APHWTypeDescription = "Hardware Type Description";
L7_char8 *pStrInfo_wireless_APHWTypeNumRadios = "Radio Count";
L7_char8 *pStrInfo_wireless_APHWTypeImageID = "Image Type";
L7_char8 *pStrInfo_wireless_APHWDualBootSupport = "Dual Boot";
L7_char8 *pStrInfo_wireless_APHWTypeRadioIndex = "Radio";
L7_char8 *pStrInfo_wireless_APHWTypeRadioTypeDescription = "Radio Type Description";
L7_char8 *pStrInfo_wireless_APHWTypeRadioVAPCount = "VAP Count";
L7_char8 *pStrInfo_wireless_APHWTypeRadio80211aSupport = "802.11a Support";
L7_char8 *pStrInfo_wireless_APHWTypeRadio80211bgSupport = "802.11bg Support";
L7_char8 *pStrInfo_wireless_APHWTypeRadio80211nSupport = "802.11n Support";
L7_char8 *pStrInfo_wireless_APHWTypeRadioInvalid = "Invalid radio for the selected hardware type.";
L7_char8 *pStrInfo_wireless_APImageCapability = "AP Image Capability";
L7_char8 *pStrInfo_wireless_HtmlFileWsAPImageCapability = "wireless_ap_image_capability.html";
L7_char8 *pStrInfo_wireless_WidsApConfiguration = "WIDS AP Configuration";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpWidsApConfiguration = "href=\"/wireless/help/wids_ap_config.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpAPImageCapability = "href=\"/wireless/help/ap_image_capability.html\"";
L7_char8 *pStrInfo_wireless_JsdataSwitch = "jsData[%d]  = {switchIPAddr:\"%s\",";
L7_char8 *pStrInfo_wireless_SwitchAssociatedClientStatus = "Switch Associated Client Status";      
L7_char8 *pStrInfo_wireless_HtmlFileClientSwitchStatus = "client_switch_status.html";
L7_char8 *pStrInfo_wireless_HtmlFileSwitchStatus = "wireless_switch_status.html";
L7_char8 *pStrInfo_wireless_SwitchStats = "Switch Status/Statistics";      
L7_char8 *pStrInfo_wireless_NoDataAvailableForSwitchStats =  "No data available for switch status/statistics.";
L7_char8 *pStrInfo_wireless_HtmlFileHelpSwitchStats = "href=\"/wireless/help/switch_status.html\"";

L7_char8 *pStrInfo_wireless_APTriangulationStatus = "Access Point Triangulation Status";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpAPTriangulationStatus = "href=\"/wireless/help/rfscan_triangulation.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiAPTriangulationStatus = "href=\"/help_APTriangulationStatus.html\"";
L7_char8 *pStrInfo_wireless_WidsAPRogueClassification = "WIDS AP Rogue Classification";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpWidsAPRogueClassification = "href=\"/wireless/help/wids_ap_rogue_classification.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiWidsAPRogueClassification = "href=\"/help_APRogueClassification.html\"";
L7_char8 *pStrInfo_wireless_WidsAPDeAuthenticationAttackStatus = "WIDS AP De-Authentication Attack Status";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpWidsAPDeAuthenticationAttackStatus = "href=\"/wireless/help/wids_ap_de_auth_attack.html\"";
L7_char8 *pStrInfo_wireless_radio_index = "radioIdx:\"%d\",";

L7_char8 *pStrInfo_wireless_WidsClientConfiguration = "WIDS Client Configuration";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpWidsClientConfiguration = "href=\"/wireless/help/wids_client_config.html\"";
L7_char8 *pStrInfo_wireless_WidsClientRogueClassification = "WIDS Client Rogue Classification";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpWidsClientRogueClassification = "href=\"/wireless/help/wids_client_rogue_classification.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiWidsClientRogueClassification = "href=\"/help_DetectedClientRogueClassification.html\"";
L7_char8 *pStrInfo_wireless_OUI= "OUI Description";
L7_char8 *pStrInfo_wireless_OUIValue= "OUI Value ";
L7_char8 *pStrInfo_wireless_DetectedClientPreAuth = "Detected Client Pre-Authentication History";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpDetectedClientPreAuth = "href=\"/wireless/help/detected_client_pre_auth.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiDetectedClientPreAuth = "href=\"/help_PreAuthentication.html\"";
L7_char8 *pStrInfo_wireless_DetectedClientTriangulation = "Detected Client Triangulation";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpDetectedClientTriangulation = "href=\"/wireless/help/detected_client_triangulation.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiDetectedClientTriangulation = "href=\"/help_ClientTriangulation.html\"";
L7_char8 *pStrInfo_wireless_DetectedClientPreAuthSumm = "Detected Client Pre-Authentication History Summary";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpDetectedClientPreAuthSumm = "href=\"/wireless/help/detected_client_pre_auth_summ.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiDetectedClientPreAuthSumm = "href=\"/help_PreAuthenticationSummary.html\"";
L7_char8 *pStrInfo_wireless_DetectedClientRoamHistorySumm = "Detected Client Roam History Summary";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpDetectedClientRoamHistorySumm = "href=\"/wireless/help/detected_client_roam_hist_summ.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiDetectedClientRoamHistorySumm = "href=\"/help_RoamHistorySummary.html\"";
L7_char8 *pStrInfo_wireless_DetectedClientRoamHistory = "Detected Client Roam History";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpDetectedClientRoamHistory = "href=\"/wireless/help/detected_client_roam_hist.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiDetectedClientRoamHistory = "href=\"/help_RoamHistory.html\"";
L7_char8 *pStrInfo_wireless_KnownClientSumm = "Known Client Summary";
L7_char8 *pStrInfo_wireless_KnownClientConfiguration = "Known Client Configuration";
L7_char8 *pStrInfo_wireless_HtmlFileKnownClientSumm= "/wireless_kc_summ.html";
L7_char8 *pStrInfo_wireless_HtmlFileKnownClientCfg= "/wireless/wireless_kc_cfg.html";
L7_char8 *pStrInfo_wireless_HtmlFileKnownClientCfgNew ="/KnownClientConfig.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpKnownClientConfiguration = "href=\"/wireless/help/known_client.html\"";
L7_char8 *pStrInfo_wireless_Action = "action:\"%s\"}";
L7_char8 *pStrInfo_wireless_ActionError = "action:\"error\"}";
L7_char8 *pStrInfo_wireless_MACNotEntered = "MAC address not entered.";
L7_char8 *pStrInfo_wireless_distTunnel_globalCfg = "Distributed Tunneling Configuration";
L7_char8 *pStrInfo_wireless_HtmlFilewsHelpdistTunnel_globalCfg = "href=\"/wireless/help/dist_tunnel_globalcfg.html\"";
L7_char8 *pStrInfo_wireless_distTunnel_clientStatus = "Associated Client Distributed Tunneling Status";
L7_char8 *pStrInfo_wireless_HtmlFilewsHelpdistTunnel_clientStatus = "href=\"/wireless/help/dist_tunnel_clientstatus.html\"";
L7_char8 *pStrInfo_wireless_distTunnel_managedapStatus = "Managed Access Point Distributed Tunneling Status";
L7_char8 *pStrInfo_wireless_HtmlFilewsHelpdistTunnel_managedapStatus = "href=\"/wireless/help/dist_tunnel_managedapstatus.html\"";
L7_char8 *pStrInfo_wireless_distTunnel_managedapStats = "Managed Access Point Distributed Tunneling Statistics";
L7_char8 *pStrInfo_wireless_HtmlFilewsHelpdistTunnel_managedapStats = "href=\"/wireless/help/dist_tunnel_managedapstats.html\"";
L7_char8 *pStrInfo_wireless_DetectedClientsStatusHours = "Detected Clients Status Timeout (hours)";
L7_char8 *pStrErr_wireless_DelDetectedClients = "delete the Detected Client.";
L7_char8 *pStrErr_wireless_AddDiscIP = "Enter valid Unicast IP Address(es). Failed to add the following IP Address(es)."; 
L7_char8 *pStrInfo_wireless_FilePath1 = "File Path";
L7_char8 *pStrInfo_wireless_FileName1 = "File Name";
L7_char8 *pStrInfo_wireless_xmlFileLocalApDbaseCfgRw = "/ValidAccessPointConfig.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiAssocClientStatisticsAssocDetail = "href=\"/help_AssocClientStatisticsAssocDetail.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiAssocClientStatisticsSessionDetail = "href=\"/help_AssocClientStatisticsSessionDetail.html\"";
L7_char8 *pStrInfo_wireless_PrimaryIp_1 = "primaryip:\"%s\",";
L7_char8 *pStrInfo_wireless_PrimaryIpError = "primaryip:\"error\",";
L7_char8 *pStrInfo_wireless_BackupIp_1 = "backupip:\"%s\",";
L7_char8 *pStrInfo_wireless_BackupIpError = "backupip:\"error\",";
L7_char8 *pStrInfo_wireless_NewPrimaryIp_1 = "newprimaryip:\"%s\",";
L7_char8 *pStrInfo_wireless_NewPrimaryIpError = "newprimaryip:\"error\",";
L7_char8 *pStrInfo_wireless_NewBackupIp_1 = "newbackupip:\"%s\",";
L7_char8 *pStrInfo_wireless_NewBackupIpError = "newbackupip:\"error\",";
L7_char8 *pStrErr_wireless_SuccessfullyDeldAllApEntries = "Successfully deleted all Unmanaged AP Provisioning entries.";
L7_char8 *pStrErr_wireless_SuccessfullyProvisionedAPEntries = "Successfully start provisioning for all the selescted APs.";
L7_char8 *pStrErr_wireless_SuccessfullyDeldAllRrmNeighborEntries = "Successfully deleted all RRM Neighbor Entries";
L7_char8 *pStrErr_wireless_DelAPProv = "delete the AP from the AP Provisioning list";
L7_char8 *pStrErr_wireless_APProv = "start the provisioning for the AP";
L7_char8 *pStrInfo_wireless_Provisioning = "Provision";
L7_char8 *pStrInfo_wireless_APProvisioningSummary = "AP Provisioning Summary Status";
L7_char8 *pStrInfo_wireless_RRMChLoadHistory = "RRM Channel Load History Summary";
L7_char8 *pStrInfo_wireless_RRMNeighborsSummary = "RRM Neighbors Summary";
L7_char8 *pStrInfo_wireless_HtmlFileRrmNeighborSummary = "rrm_neighbors_summ.html";
L7_char8 *pStrInfo_wireless_HtmlFileApProvSumm = "ap_provisioning_summ.html";
L7_char8 *pStrInfo_wireless_HtmlFileRrmHistorySumm = "rrm_chload_history_summ.html";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpAPProvisioningSummary = "href=\"/wireless/help/ap_provisioning_summ.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpRrmNeighborsSummary = "href=\"/wireless/help/rrm_neighbors_summ.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpRRMChLoadHistorySummary = "href=\"/wireless/help/rrm_chload_history_summ.html\"";
L7_char8 *pStrErr_wireless_RrmNeighborEntries = "RRM Neighbor Entries";
L7_char8 *pStrErr_wireless_RrmHistoryEntries = "RRM History Entries";
L7_char8 *pStrErr_wireless_SuccessfullyDeldAllHistoryEntries = "Successfully deleted all Channel Load History entries.";
L7_char8 *pStrInfo_wireless_NoAPProvisioningEntries = "No AP provisioning entries exist.";
L7_char8 *pStrInfo_wireless_NoRrmNeighborsExist = "No RRM Neighbors exist.";
L7_char8 *pStrInfo_wireless_NoRRMChLoadHistoryEntries = "No RRM Channel Load History Entries exist.";
L7_char8 *pStrInfo_wireless_Duration_1 = "duration:\"%u\",";
L7_char8 *pStrInfo_wireless_DurationError = "duration:\"error\",";
L7_char8 *pStrInfo_wireless_Load_1 = "load:\"%u\",";
L7_char8 *pStrInfo_wireless_LoadError = "load:\"error\",";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiApDebug1 = "href=\"/help_ManagedAPAdvancedDebug.html\"";
L7_char8 *pStrInfo_wireless_HtmlFileWsHelpXuiApChannelPowerAdjust = "href=\"/help_ManagedAPAdvancedChannelPower.html\"";
