/** \file jer2_a0_data_ingr_reassembly.c
 * 
 * DEVICE DATA - INGR_REASSEMBLY
 * 
 * Device Data
 * SW component that maintains per device data
 * For additional details about Device Data Component goto 'dnxc_data_mgmt.h'
 *        
 *     
 * 
 * AUTO-GENERATED BY AUTOCODER!
 * DO NOT EDIT THIS FILE!
 */
/* *INDENT-OFF* */
/*
 * $Copyright: (c) 2018 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */
#ifdef BSL_LOG_MODULE
#error "BSL_LOG_MODULE redefined"
#endif
#define BSL_LOG_MODULE BSL_LS_BCMDNX_PORT
/**
 * \brief
 * Mark this file as device data internal file
 */
#define DNX_DATA_INTERNAL
/*
 * INCLUDE FILES:
 * {
 */
#include <soc/dnx/dnx_data/auto_generated/dnx_data_internal_ingr_reassembly.h>
#include <shared/utilex/utilex_integer_arithmetic.h>
/*
 * }
 */

/*
 * EXTERN FUNCTIONS:
 * {
 */
/*
 * FUNCTIONS:
 * {
 */
/*
 * Submodule: context
 */

/*
 * Features
 */
/*
 * Defines
 */
/**
 * \brief device level function which set define nof_contexts
 * define info:
 * Number of ingress reassembly contexts per core
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_context_nof_contexts_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_context;
    int define_index = dnx_data_ingr_reassembly_context_define_nof_contexts;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = 256;

    /* Set value */
    define->data = 256;

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/**
 * \brief device level function which set define invalid_context
 * define info:
 * Invalid reassembly context
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_context_invalid_context_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_context;
    int define_index = dnx_data_ingr_reassembly_context_define_invalid_context;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = dnx_data_ingr_reassembly.context.nof_contexts_get(unit) - 1;

    /* Set value */
    define->data = dnx_data_ingr_reassembly.context.nof_contexts_get(unit) - 1;

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/*
 * Tables
 */
/**
 * \brief device level function which set values for table context_map
 * Module - 'ingr_reassembly', Submodule - 'context', table - 'context_map'
 * Context Map configuration information per port type 
 * The function set relevant table structure in _dnx_data
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - See shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_context_context_map_set(
    int unit)
{
    int port_type_index;
    dnx_data_ingr_reassembly_context_context_map_t *data, *default_data;
    dnxc_data_table_t *table;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_context;
    int table_index = dnx_data_ingr_reassembly_context_table_context_map;
    SHR_FUNC_INIT_VARS(unit);

    table = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].tables[table_index];
    /* Set data flags as supported */
    table->flags |= DNXC_DATA_F_SUPPORTED;

    /*
     * Set key sizes
     */
    table->keys[0].size = DNX_ALGO_PORT_TYPE_NOF;
    table->info_get.key_size[0] = DNX_ALGO_PORT_TYPE_NOF;

    /* Info - default values */
    table->values[0].default_val = "SAL_UINT32_MAX";
    /* Allocate data buffer */
    DNXC_DATA_ALLOC(table->data, dnx_data_ingr_reassembly_context_context_map_t, (1 * (table->keys[0].size) + 1 /* to store default value */ ), "data of dnx_data_ingr_reassembly_context_table_context_map");

    /* Store Default Values */
    default_data = (dnx_data_ingr_reassembly_context_context_map_t *) dnxc_data_mgmt_table_data_get(unit, table, -1, -1);
    default_data->start_index = SAL_UINT32_MAX;
    /* Set Default Values */
    for (port_type_index = 0; port_type_index < table->keys[0].size; port_type_index++)
    {
        data = (dnx_data_ingr_reassembly_context_context_map_t *) dnxc_data_mgmt_table_data_get(unit, table, port_type_index, 0);
        sal_memcpy(data, default_data, table->size_of_values);
    }
    /*
     * Set Values - Entries
     */
    data = (dnx_data_ingr_reassembly_context_context_map_t *) dnxc_data_mgmt_table_data_get(unit, table, DNX_ALGO_PORT_TYPE_NIF_ETH, 0);
    data->start_index = 0x0;
    data = (dnx_data_ingr_reassembly_context_context_map_t *) dnxc_data_mgmt_table_data_get(unit, table, DNX_ALGO_PORT_TYPE_RCY, 0);
    data->start_index = 0x200;
    data = (dnx_data_ingr_reassembly_context_context_map_t *) dnxc_data_mgmt_table_data_get(unit, table, DNX_ALGO_PORT_TYPE_RCY_MIRROR, 0);
    data->start_index = 0x300;
    data = (dnx_data_ingr_reassembly_context_context_map_t *) dnxc_data_mgmt_table_data_get(unit, table, DNX_ALGO_PORT_TYPE_CPU, 0);
    data->start_index = 0x600;
    data = (dnx_data_ingr_reassembly_context_context_map_t *) dnxc_data_mgmt_table_data_get(unit, table, DNX_ALGO_PORT_TYPE_SAT, 0);
    data->start_index = 0x700;
    data = (dnx_data_ingr_reassembly_context_context_map_t *) dnxc_data_mgmt_table_data_get(unit, table, DNX_ALGO_PORT_TYPE_OLP, 0);
    data->start_index = 0x1000;
    data = (dnx_data_ingr_reassembly_context_context_map_t *) dnxc_data_mgmt_table_data_get(unit, table, DNX_ALGO_PORT_TYPE_OAMP, 0);
    data->start_index = 0x1001;
    data = (dnx_data_ingr_reassembly_context_context_map_t *) dnxc_data_mgmt_table_data_get(unit, table, DNX_ALGO_PORT_TYPE_EVENTOR, 0);
    data->start_index = 0x1002;

exit:
    SHR_FUNC_EXIT;
}

/*
 * Submodule: ilkn
 */

/*
 * Features
 */
/*
 * Defines
 */
/*
 * Tables
 */
/**
 * \brief device level function which set values for table dedicated_tdm_context
 * Module - 'ingr_reassembly', Submodule - 'ilkn', table - 'dedicated_tdm_context'
 * Is this interface works in dedicated TDM context mode
 * The function set relevant table structure in _dnx_data
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - See shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_ilkn_dedicated_tdm_context_set(
    int unit)
{
    int ilkn_id_index;
    dnx_data_ingr_reassembly_ilkn_dedicated_tdm_context_t *data, *default_data;
    dnxc_data_table_t *table;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_ilkn;
    int table_index = dnx_data_ingr_reassembly_ilkn_table_dedicated_tdm_context;
    SHR_FUNC_INIT_VARS(unit);

    table = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].tables[table_index];
    /* Set data flags as supported */
    table->flags |= DNXC_DATA_F_SUPPORTED;

    /*
     * Set key sizes
     */
    table->keys[0].size = 16;
    table->info_get.key_size[0] = 16;

    /* Info - default values */
    table->values[0].default_val = "0";
    /* Allocate data buffer */
    DNXC_DATA_ALLOC(table->data, dnx_data_ingr_reassembly_ilkn_dedicated_tdm_context_t, (1 * (table->keys[0].size) + 1 /* to store default value */ ), "data of dnx_data_ingr_reassembly_ilkn_table_dedicated_tdm_context");

    /* Store Default Values */
    default_data = (dnx_data_ingr_reassembly_ilkn_dedicated_tdm_context_t *) dnxc_data_mgmt_table_data_get(unit, table, -1, -1);
    default_data->is_dedicated = 0;
    /* Set Default Values */
    for (ilkn_id_index = 0; ilkn_id_index < table->keys[0].size; ilkn_id_index++)
    {
        data = (dnx_data_ingr_reassembly_ilkn_dedicated_tdm_context_t *) dnxc_data_mgmt_table_data_get(unit, table, ilkn_id_index, 0);
        sal_memcpy(data, default_data, table->size_of_values);
    }
    /*
     * Property
     */
    table->property.name = spn_CUSTOM_FEATURE;
    table->property.doc = NULL;
    table->property.method = dnxc_data_property_method_suffix_enable;
    table->property.method_str = "suffix_enable";
    table->property.suffix = "ilkn_dedicated_tdm_context";
    for (ilkn_id_index = 0; ilkn_id_index < table->keys[0].size; ilkn_id_index++)
    {
        data = (dnx_data_ingr_reassembly_ilkn_dedicated_tdm_context_t *) dnxc_data_mgmt_table_data_get(unit, table, ilkn_id_index, 0);
        SHR_IF_ERR_EXIT(dnxc_data_mgmt_property_read(unit, &table->property, ilkn_id_index, &data->is_dedicated));
    }
    /* Set data flags as property */
    table->flags |= (DNXC_DATA_F_PROPERTY);

exit:
    SHR_FUNC_EXIT;
}

/*
 * Submodule: priority
 */

/*
 * Features
 */
/*
 * Defines
 */
/**
 * \brief device level function which set define nif_eth_priorities_nof
 * define info:
 * Number of priorities for NIF ETH port
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_priority_nif_eth_priorities_nof_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_priority;
    int define_index = dnx_data_ingr_reassembly_priority_define_nif_eth_priorities_nof;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = 2;

    /* Set value */
    define->data = 2;

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/**
 * \brief device level function which set define mirror_priorities_nof
 * define info:
 * Number of priorities for mirror channel
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_priority_mirror_priorities_nof_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_priority;
    int define_index = dnx_data_ingr_reassembly_priority_define_mirror_priorities_nof;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = 2;

    /* Set value */
    define->data = 2;

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/**
 * \brief device level function which set define rcy_priorities_nof
 * define info:
 * Number of priorities (groups) for RCY interface
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_priority_rcy_priorities_nof_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_priority;
    int define_index = dnx_data_ingr_reassembly_priority_define_rcy_priorities_nof;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = 2;

    /* Set value */
    define->data = 2;

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/**
 * \brief device level function which set define priorities_nof
 * define info:
 * Number of priorities (groups) for any interface type
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_priority_priorities_nof_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_priority;
    int define_index = dnx_data_ingr_reassembly_priority_define_priorities_nof;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = UTILEX_MAX(dnx_data_ingr_reassembly.priority.nif_eth_priorities_nof_get(unit), dnx_data_ingr_reassembly.priority.mirror_priorities_nof_get(unit));

    /* Set value */
    define->data = UTILEX_MAX(dnx_data_ingr_reassembly.priority.nif_eth_priorities_nof_get(unit), dnx_data_ingr_reassembly.priority.mirror_priorities_nof_get(unit));

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/**
 * \brief device level function which set define cgm_priorities_nof
 * define info:
 * Number of priorities (groups) for any interface type as considered by CGM module
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_priority_cgm_priorities_nof_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_priority;
    int define_index = dnx_data_ingr_reassembly_priority_define_cgm_priorities_nof;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = UTILEX_MAX(dnx_data_ingr_reassembly.priority.priorities_nof_get(unit), dnx_data_ingr_reassembly.priority.rcy_priorities_nof_get(unit));

    /* Set value */
    define->data = UTILEX_MAX(dnx_data_ingr_reassembly.priority.priorities_nof_get(unit), dnx_data_ingr_reassembly.priority.rcy_priorities_nof_get(unit));

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/*
 * Tables
 */
/*
 * Submodule: dbal
 */

/*
 * Features
 */
/*
 * Defines
 */
/**
 * \brief device level function which set define reassembly_context_bits
 * define info:
 * number of bits in reassembly context
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_dbal_reassembly_context_bits_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_dbal;
    int define_index = dnx_data_ingr_reassembly_dbal_define_reassembly_context_bits;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = 8;

    /* Set value */
    define->data = 8;

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/**
 * \brief device level function which set define interface_bits
 * define info:
 * number of bits in ingress reassembly interface ID
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_dbal_interface_bits_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_dbal;
    int define_index = dnx_data_ingr_reassembly_dbal_define_interface_bits;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = 6;

    /* Set value */
    define->data = 6;

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/**
 * \brief device level function which set define interface_max
 * define info:
 * maximal ingress reassembly interface ID
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_dbal_interface_max_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_dbal;
    int define_index = dnx_data_ingr_reassembly_dbal_define_interface_max;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = 63;

    /* Set value */
    define->data = 63;

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/**
 * \brief device level function which set define context_map_base_address_bits
 * define info:
 * number of bits in context_map_base_address
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_dbal_context_map_base_address_bits_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_dbal;
    int define_index = dnx_data_ingr_reassembly_dbal_define_context_map_base_address_bits;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = 12;

    /* Set value */
    define->data = 12;

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/**
 * \brief device level function which set define context_map_base_address_max
 * define info:
 * maximal value of context_map_base_address
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_dbal_context_map_base_address_max_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_dbal;
    int define_index = dnx_data_ingr_reassembly_dbal_define_context_map_base_address_max;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = 4*1024-1;

    /* Set value */
    define->data = 4*1024-1;

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/**
 * \brief device level function which set define interleaved_interface_bits
 * define info:
 * number of bits in interleaved interface ID
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_dbal_interleaved_interface_bits_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_dbal;
    int define_index = dnx_data_ingr_reassembly_dbal_define_interleaved_interface_bits;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = 3;

    /* Set value */
    define->data = 3;

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/**
 * \brief device level function which set define interleaved_interface_max
 * define info:
 * maximal interleaved interface ID
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - see shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
jer2_a0_dnx_data_ingr_reassembly_dbal_interleaved_interface_max_set(
    int unit)
{
    dnxc_data_define_t *define;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = dnx_data_ingr_reassembly_submodule_dbal;
    int define_index = dnx_data_ingr_reassembly_dbal_define_interleaved_interface_max;
    SHR_FUNC_INIT_VARS(unit);

    define = &_dnxc_data[unit].modules[module_index].submodules[submodule_index].defines[define_index];
    /* Set default value */
    define->default_data = 5;

    /* Set value */
    define->data = 5;

    /* Set data flags as supported */
    define->flags |= DNXC_DATA_F_SUPPORTED;

    SHR_FUNC_EXIT;
}

/*
 * Tables
 */
/*
 * Device attach func
 */
/**
 * \brief Attach device to module - attach set function to data structure
 * 
 * \param [in] unit - Unit #
 * 
 * \return
 *     err - 
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
shr_error_e
jer2_a0_data_ingr_reassembly_attach(
    int unit)
{
    dnxc_data_module_t *module = NULL;
    dnxc_data_submodule_t *submodule = NULL;
    dnxc_data_define_t *define = NULL;
    dnxc_data_feature_t *feature = NULL;
    dnxc_data_table_t *table = NULL;
    int module_index = dnx_data_module_ingr_reassembly;
    int submodule_index = -1, data_index = -1;
    SHR_FUNC_INIT_VARS(unit);

    COMPILER_REFERENCE(define);
    COMPILER_REFERENCE(feature);
    COMPILER_REFERENCE(table);
    COMPILER_REFERENCE(submodule);
    COMPILER_REFERENCE(data_index);
    COMPILER_REFERENCE(submodule_index);
    module = &_dnxc_data[unit].modules[module_index];
    /*
     * Attach submodule: context
     */
    submodule_index = dnx_data_ingr_reassembly_submodule_context;
    submodule = &module->submodules[submodule_index];

    /*
     * Attach defines: 
     */
    data_index = dnx_data_ingr_reassembly_context_define_nof_contexts;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_context_nof_contexts_set;
    data_index = dnx_data_ingr_reassembly_context_define_invalid_context;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_context_invalid_context_set;

    /*
     * Attach features: 
     */

    /*
     * Attach tables: 
     */
    data_index = dnx_data_ingr_reassembly_context_table_context_map;
    table = &submodule->tables[data_index];
    table->set = jer2_a0_dnx_data_ingr_reassembly_context_context_map_set;
    /*
     * Attach submodule: ilkn
     */
    submodule_index = dnx_data_ingr_reassembly_submodule_ilkn;
    submodule = &module->submodules[submodule_index];

    /*
     * Attach defines: 
     */

    /*
     * Attach features: 
     */

    /*
     * Attach tables: 
     */
    data_index = dnx_data_ingr_reassembly_ilkn_table_dedicated_tdm_context;
    table = &submodule->tables[data_index];
    table->set = jer2_a0_dnx_data_ingr_reassembly_ilkn_dedicated_tdm_context_set;
    /*
     * Attach submodule: priority
     */
    submodule_index = dnx_data_ingr_reassembly_submodule_priority;
    submodule = &module->submodules[submodule_index];

    /*
     * Attach defines: 
     */
    data_index = dnx_data_ingr_reassembly_priority_define_nif_eth_priorities_nof;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_priority_nif_eth_priorities_nof_set;
    data_index = dnx_data_ingr_reassembly_priority_define_mirror_priorities_nof;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_priority_mirror_priorities_nof_set;
    data_index = dnx_data_ingr_reassembly_priority_define_rcy_priorities_nof;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_priority_rcy_priorities_nof_set;
    data_index = dnx_data_ingr_reassembly_priority_define_priorities_nof;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_priority_priorities_nof_set;
    data_index = dnx_data_ingr_reassembly_priority_define_cgm_priorities_nof;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_priority_cgm_priorities_nof_set;

    /*
     * Attach features: 
     */

    /*
     * Attach tables: 
     */
    /*
     * Attach submodule: dbal
     */
    submodule_index = dnx_data_ingr_reassembly_submodule_dbal;
    submodule = &module->submodules[submodule_index];

    /*
     * Attach defines: 
     */
    data_index = dnx_data_ingr_reassembly_dbal_define_reassembly_context_bits;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_dbal_reassembly_context_bits_set;
    data_index = dnx_data_ingr_reassembly_dbal_define_interface_bits;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_dbal_interface_bits_set;
    data_index = dnx_data_ingr_reassembly_dbal_define_interface_max;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_dbal_interface_max_set;
    data_index = dnx_data_ingr_reassembly_dbal_define_context_map_base_address_bits;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_dbal_context_map_base_address_bits_set;
    data_index = dnx_data_ingr_reassembly_dbal_define_context_map_base_address_max;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_dbal_context_map_base_address_max_set;
    data_index = dnx_data_ingr_reassembly_dbal_define_interleaved_interface_bits;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_dbal_interleaved_interface_bits_set;
    data_index = dnx_data_ingr_reassembly_dbal_define_interleaved_interface_max;
    define = &submodule->defines[data_index];
    define->set = jer2_a0_dnx_data_ingr_reassembly_dbal_interleaved_interface_max_set;

    /*
     * Attach features: 
     */

    /*
     * Attach tables: 
     */

    SHR_FUNC_EXIT;
}
/* *INDENT-ON* */
