#
# $Id:$
# $Copyright: (c) 2018 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC swstate subdirectory
#
LOCALDIR = src/soc/dnx/swstate/auto_generated

include ${SDK}/make/Make.config
#
# Take the subdirs 'access diagnostic'
#
subdirs = access diagnostic

include ${SDK}/make/Make.subdirs

lib = libsoc_swstate_auto_generated

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
