# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Tomahawk SOC driver Library
#

LOCALDIR = src/soc/esw/tomahawk3/traffic_manager

include ${SDK}/make/Make.config

lib = libsoc_tomahawk3_trafficmanager

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

