# $Id$
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM Firebolt6 driver Library
#

LOCALDIR = src/bcm/esw/firebolt6

include ${SDK}/make/Make.config

lib = libfirebolt6

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
