#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2017 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dnxf/dnxf_data/auto_generated subdirectory
#

LOCALDIR = src/soc/dnxf/dnxf_data/auto_generated/auto_generated

include ${SDK}/make/Make.config


include ${SDK}/make/Make.subdirs

lib = libsoc_dnxfdnxfdataag

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

