#
# $Id: Makefile Exp $
#
# $Copyright: (c) 2017 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dpp/QAX/

include ${SDK}/make/Make.config

subdirs := QAX_PP

# do no remove line below, it is used by auto VENDOR code removal script (remdef.sh)
#endif

include ${SDK}/make/Make.subdirs

lib = libsoc_dpp_qax

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
