/** \file dnx/swstate/auto_generated/diagnostic/algo_oamp_diagnostic.c
 *
 * sw state functions definitions
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 */
/*
 * $Copyright: (c) 2018 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */

#ifdef BSL_LOG_MODULE
#error "BSL_LOG_MODULE redefined"
#endif
#define BSL_LOG_MODULE BSL_LS_SWSTATEDNX_GENERAL

typedef int make_iso_compilers_happy_swstatednx;

#include <soc/dnxc/swstate/dnxc_sw_state_c_includes.h>
#include <soc/dnx/swstate/auto_generated/diagnostic/algo_oamp_diagnostic.h>
#if defined(DNX_SW_STATE_DIAGNOSTIC)
/*
 * Global Variables
 */

extern algo_oamp_sw_state_t * algo_oamp_db_data[SOC_MAX_NUM_DEVICES];
/*
 * FUNCTIONs
 */

/*
 *
 * dump function for the variable algo_oamp_db
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
algo_oamp_db_dump(int  unit)
{
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    SHR_IF_ERR_EXIT(algo_oamp_db_oamp_2b_maid_full_mep_id_dump(unit));
    SHR_IF_ERR_EXIT(algo_oamp_db_oamp_2b_maid_short_mep_id_dump(unit));
    SHR_IF_ERR_EXIT(algo_oamp_db_oamp_icc_maid_full_mep_id_dump(unit));
    SHR_IF_ERR_EXIT(algo_oamp_db_oamp_icc_maid_short_mep_id_dump(unit));
    SHR_IF_ERR_EXIT(algo_oamp_db_oamp_extra_mep_id_dump(unit));
    SHR_IF_ERR_EXIT(algo_oamp_db_oamp_mep_db_entry_dump(unit));
    SHR_IF_ERR_EXIT(algo_oamp_db_oamp_pp_port_2_sys_port_dump(unit));
    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable oamp_2b_maid_full_mep_id
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
algo_oamp_db_oamp_2b_maid_full_mep_id_dump(int  unit)
{
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "algo_oamp_db/oamp_2b_maid_full_mep_id.txt",
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_2b_maid_full_mep_id: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID]));

    DNX_SW_STATE_PRINT_MONITOR(
        unit,
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_2b_maid_full_mep_id: ");

    DNX_SW_STATE_PRINT_FILE(
        unit,
        " ");

    SW_STATE_RES_MNGR_PRINT(
        unit,
        ALGO_OAMP_MODULE_ID,
        &((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID])->oamp_2b_maid_full_mep_id);

    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable oamp_2b_maid_short_mep_id
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
algo_oamp_db_oamp_2b_maid_short_mep_id_dump(int  unit)
{
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "algo_oamp_db/oamp_2b_maid_short_mep_id.txt",
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_2b_maid_short_mep_id: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID]));

    DNX_SW_STATE_PRINT_MONITOR(
        unit,
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_2b_maid_short_mep_id: ");

    DNX_SW_STATE_PRINT_FILE(
        unit,
        " ");

    SW_STATE_RES_MNGR_PRINT(
        unit,
        ALGO_OAMP_MODULE_ID,
        &((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID])->oamp_2b_maid_short_mep_id);

    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable oamp_icc_maid_full_mep_id
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
algo_oamp_db_oamp_icc_maid_full_mep_id_dump(int  unit)
{
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "algo_oamp_db/oamp_icc_maid_full_mep_id.txt",
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_icc_maid_full_mep_id: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID]));

    DNX_SW_STATE_PRINT_MONITOR(
        unit,
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_icc_maid_full_mep_id: ");

    DNX_SW_STATE_PRINT_FILE(
        unit,
        " ");

    SW_STATE_RES_MNGR_PRINT(
        unit,
        ALGO_OAMP_MODULE_ID,
        &((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID])->oamp_icc_maid_full_mep_id);

    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable oamp_icc_maid_short_mep_id
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
algo_oamp_db_oamp_icc_maid_short_mep_id_dump(int  unit)
{
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "algo_oamp_db/oamp_icc_maid_short_mep_id.txt",
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_icc_maid_short_mep_id: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID]));

    DNX_SW_STATE_PRINT_MONITOR(
        unit,
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_icc_maid_short_mep_id: ");

    DNX_SW_STATE_PRINT_FILE(
        unit,
        " ");

    SW_STATE_RES_MNGR_PRINT(
        unit,
        ALGO_OAMP_MODULE_ID,
        &((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID])->oamp_icc_maid_short_mep_id);

    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable oamp_extra_mep_id
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
algo_oamp_db_oamp_extra_mep_id_dump(int  unit)
{
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "algo_oamp_db/oamp_extra_mep_id.txt",
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_extra_mep_id: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID]));

    DNX_SW_STATE_PRINT_MONITOR(
        unit,
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_extra_mep_id: ");

    DNX_SW_STATE_PRINT_FILE(
        unit,
        " ");

    SW_STATE_RES_MNGR_PRINT(
        unit,
        ALGO_OAMP_MODULE_ID,
        &((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID])->oamp_extra_mep_id);

    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable oamp_mep_db_entry
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
algo_oamp_db_oamp_mep_db_entry_dump(int  unit)
{
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "algo_oamp_db/oamp_mep_db_entry.txt",
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_mep_db_entry: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID]));

    DNX_SW_STATE_PRINT_MONITOR(
        unit,
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_mep_db_entry: ");

    DNX_SW_STATE_PRINT_FILE(
        unit,
        " ");

    SW_STATE_RES_MNGR_PRINT(
        unit,
        ALGO_OAMP_MODULE_ID,
        &((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID])->oamp_mep_db_entry);

    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable oamp_pp_port_2_sys_port
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
algo_oamp_db_oamp_pp_port_2_sys_port_dump(int  unit)
{
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "algo_oamp_db/oamp_pp_port_2_sys_port.txt",
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_pp_port_2_sys_port: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID]));

    DNX_SW_STATE_PRINT_MONITOR(
        unit,
        "algo_oamp_db[%d]->","((algo_oamp_sw_state_t*)sw_state_roots_array[%d][ALGO_OAMP_MODULE_ID])->","oamp_pp_port_2_sys_port: ");

    DNX_SW_STATE_PRINT_FILE(
        unit,
        " ");

    SW_STATE_TEMP_MNGR_PRINT(
        unit,
        ALGO_OAMP_MODULE_ID,
        &((algo_oamp_sw_state_t*)sw_state_roots_array[unit][ALGO_OAMP_MODULE_ID])->oamp_pp_port_2_sys_port,
        dnx_oamp_pp_port_profile_print_cb);

    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 * Global Variables
 */

dnx_sw_state_diagnostic_info_t algo_oamp_db_info[SOC_MAX_NUM_DEVICES][ALGO_OAMP_DB_INFO_NOF_ENTRIES];
const char* algo_oamp_db_layout_str[ALGO_OAMP_DB_INFO_NOF_ENTRIES] = {
    "ALGO_OAMP_DB~",
    "ALGO_OAMP_DB~OAMP_2B_MAID_FULL_MEP_ID~",
    "ALGO_OAMP_DB~OAMP_2B_MAID_SHORT_MEP_ID~",
    "ALGO_OAMP_DB~OAMP_ICC_MAID_FULL_MEP_ID~",
    "ALGO_OAMP_DB~OAMP_ICC_MAID_SHORT_MEP_ID~",
    "ALGO_OAMP_DB~OAMP_EXTRA_MEP_ID~",
    "ALGO_OAMP_DB~OAMP_MEP_DB_ENTRY~",
    "ALGO_OAMP_DB~OAMP_PP_PORT_2_SYS_PORT~",
};
#undef _ERR_MSG_MODULE_NAME
#endif /* DNX_SW_STATE_DIAGNOSTIC */
