/** \file dnx/swstate/auto_generated/diagnostic/dnx_field_tcam_access_diagnostic.c
 *
 * sw state functions definitions
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 */
/*
 * $Copyright: (c) 2018 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */

#ifdef BSL_LOG_MODULE
#error "BSL_LOG_MODULE redefined"
#endif
#define BSL_LOG_MODULE BSL_LS_SWSTATEDNX_GENERAL

typedef int make_iso_compilers_happy_swstatednx;

#include <soc/dnxc/swstate/dnxc_sw_state_c_includes.h>
#include <soc/dnx/swstate/auto_generated/diagnostic/dnx_field_tcam_access_diagnostic.h>
#if defined(DNX_SW_STATE_DIAGNOSTIC)
/*
 * Global Variables
 */

extern dnx_field_tcam_access_t * dnx_field_tcam_access_sw_data[SOC_MAX_NUM_DEVICES];
/*
 * FUNCTIONs
 */

/*
 *
 * dump function for the variable dnx_field_tcam_access_sw
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
dnx_field_tcam_access_sw_dump(int  unit)
{
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    SHR_IF_ERR_EXIT(dnx_field_tcam_access_sw_entry_location_hash_dump(unit, -1));
    SHR_IF_ERR_EXIT(dnx_field_tcam_access_sw_fg_params_dump(unit, -1));
    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable entry_location_hash
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
dnx_field_tcam_access_sw_entry_location_hash_dump(int  unit,  int  entry_location_hash_idx_0)
{
    int i0 = entry_location_hash_idx_0, I0 = entry_location_hash_idx_0 + 1;
    char *s0 = "";
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "dnx_field_tcam_access_sw/entry_location_hash.txt",
        "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","entry_location_hash[]: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID]));

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->entry_location_hash);

    if (i0 == -1) {
        I0 = dnx_sw_state_get_nof_elements(unit,
            DNX_FIELD_TCAM_ACCESS_MODULE_ID,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->entry_location_hash);
        i0 = dnx_sw_state_dump_check_all_the_same(unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->entry_location_hash
            , sizeof(*((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->entry_location_hash), I0, &s0) ? I0 - 1 : 0;
    }
    for(; i0 < I0; i0++) {
        dnx_sw_state_dump_update_current_idx(unit, i0);
        DNX_SW_STATE_PRINT_MONITOR(
            unit,
            "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","entry_location_hash[%s%d]: ", s0, i0);

        DNX_SW_STATE_PRINT_FILE(
            unit,
            "[%s%d]: ", s0, i0);

        SW_STATE_HTB_DEFAULT_PRINT(
            unit,
            DNX_FIELD_TCAM_ACCESS_MODULE_ID,
            &((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->entry_location_hash[i0]);

    }
    dnx_sw_state_dump_end_of_stride(unit);
    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable fg_params
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
dnx_field_tcam_access_sw_fg_params_dump(int  unit,  int  fg_params_idx_0)
{
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    SHR_IF_ERR_EXIT(dnx_field_tcam_access_sw_fg_params_key_size_dump(unit, fg_params_idx_0));
    SHR_IF_ERR_EXIT(dnx_field_tcam_access_sw_fg_params_action_size_dump(unit, fg_params_idx_0));
    SHR_IF_ERR_EXIT(dnx_field_tcam_access_sw_fg_params_actual_action_size_dump(unit, fg_params_idx_0));
    SHR_IF_ERR_EXIT(dnx_field_tcam_access_sw_fg_params_stage_dump(unit, fg_params_idx_0));
    SHR_IF_ERR_EXIT(dnx_field_tcam_access_sw_fg_params_prefix_size_dump(unit, fg_params_idx_0));
    SHR_IF_ERR_EXIT(dnx_field_tcam_access_sw_fg_params_prefix_value_dump(unit, fg_params_idx_0));
    SHR_IF_ERR_EXIT(dnx_field_tcam_access_sw_fg_params_direct_table_dump(unit, fg_params_idx_0));
    SHR_IF_ERR_EXIT(dnx_field_tcam_access_sw_fg_params_dt_bank_id_dump(unit, fg_params_idx_0));
    SHR_IF_ERR_EXIT(dnx_field_tcam_access_sw_fg_params_bank_allocation_mode_dump(unit, fg_params_idx_0));
    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable key_size
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
dnx_field_tcam_access_sw_fg_params_key_size_dump(int  unit,  int  fg_params_idx_0)
{
    int i0 = fg_params_idx_0, I0 = fg_params_idx_0 + 1;
    char *s0 = "";
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "dnx_field_tcam_access_sw/fg_params/key_size.txt",
        "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[].key_size: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID]));

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);

    if (i0 == -1) {
        I0 = dnx_sw_state_get_nof_elements(unit,
            DNX_FIELD_TCAM_ACCESS_MODULE_ID,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);
        i0 = dnx_sw_state_dump_check_all_the_same(unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params
            , sizeof(*((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params), I0, &s0) ? I0 - 1 : 0;
    }
    for(; i0 < I0; i0++) {
        dnx_sw_state_dump_update_current_idx(unit, i0);
        DNX_SW_STATE_PRINT_MONITOR(
            unit,
            "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[%s%d].key_size: ", s0, i0);

        DNX_SW_STATE_PRINT_FILE(
            unit,
            "[%s%d]: ", s0, i0);

        dnx_sw_state_print_uint32(
            unit,
            &((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params[i0].key_size);

    }
    dnx_sw_state_dump_end_of_stride(unit);
    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable action_size
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
dnx_field_tcam_access_sw_fg_params_action_size_dump(int  unit,  int  fg_params_idx_0)
{
    int i0 = fg_params_idx_0, I0 = fg_params_idx_0 + 1;
    char *s0 = "";
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "dnx_field_tcam_access_sw/fg_params/action_size.txt",
        "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[].action_size: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID]));

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);

    if (i0 == -1) {
        I0 = dnx_sw_state_get_nof_elements(unit,
            DNX_FIELD_TCAM_ACCESS_MODULE_ID,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);
        i0 = dnx_sw_state_dump_check_all_the_same(unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params
            , sizeof(*((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params), I0, &s0) ? I0 - 1 : 0;
    }
    for(; i0 < I0; i0++) {
        dnx_sw_state_dump_update_current_idx(unit, i0);
        DNX_SW_STATE_PRINT_MONITOR(
            unit,
            "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[%s%d].action_size: ", s0, i0);

        DNX_SW_STATE_PRINT_FILE(
            unit,
            "[%s%d]: ", s0, i0);

        dnx_sw_state_print_uint32(
            unit,
            &((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params[i0].action_size);

    }
    dnx_sw_state_dump_end_of_stride(unit);
    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable actual_action_size
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
dnx_field_tcam_access_sw_fg_params_actual_action_size_dump(int  unit,  int  fg_params_idx_0)
{
    int i0 = fg_params_idx_0, I0 = fg_params_idx_0 + 1;
    char *s0 = "";
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "dnx_field_tcam_access_sw/fg_params/actual_action_size.txt",
        "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[].actual_action_size: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID]));

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);

    if (i0 == -1) {
        I0 = dnx_sw_state_get_nof_elements(unit,
            DNX_FIELD_TCAM_ACCESS_MODULE_ID,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);
        i0 = dnx_sw_state_dump_check_all_the_same(unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params
            , sizeof(*((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params), I0, &s0) ? I0 - 1 : 0;
    }
    for(; i0 < I0; i0++) {
        dnx_sw_state_dump_update_current_idx(unit, i0);
        DNX_SW_STATE_PRINT_MONITOR(
            unit,
            "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[%s%d].actual_action_size: ", s0, i0);

        DNX_SW_STATE_PRINT_FILE(
            unit,
            "[%s%d]: ", s0, i0);

        dnx_sw_state_print_uint32(
            unit,
            &((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params[i0].actual_action_size);

    }
    dnx_sw_state_dump_end_of_stride(unit);
    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable stage
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
dnx_field_tcam_access_sw_fg_params_stage_dump(int  unit,  int  fg_params_idx_0)
{
    int i0 = fg_params_idx_0, I0 = fg_params_idx_0 + 1;
    char *s0 = "";
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "dnx_field_tcam_access_sw/fg_params/stage.txt",
        "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[].stage: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID]));

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);

    if (i0 == -1) {
        I0 = dnx_sw_state_get_nof_elements(unit,
            DNX_FIELD_TCAM_ACCESS_MODULE_ID,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);
        i0 = dnx_sw_state_dump_check_all_the_same(unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params
            , sizeof(*((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params), I0, &s0) ? I0 - 1 : 0;
    }
    for(; i0 < I0; i0++) {
        dnx_sw_state_dump_update_current_idx(unit, i0);
        DNX_SW_STATE_PRINT_OPAQUE_MONITOR(
            unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params[i0].stage,
            "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[%s%d].stage: ", s0, i0);

        DNX_SW_STATE_PRINT_OPAQUE_FILE(
            unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params[i0].stage,
                "[%s%d]: ", s0, i0);

    }
    dnx_sw_state_dump_end_of_stride(unit);
    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable prefix_size
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
dnx_field_tcam_access_sw_fg_params_prefix_size_dump(int  unit,  int  fg_params_idx_0)
{
    int i0 = fg_params_idx_0, I0 = fg_params_idx_0 + 1;
    char *s0 = "";
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "dnx_field_tcam_access_sw/fg_params/prefix_size.txt",
        "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[].prefix_size: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID]));

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);

    if (i0 == -1) {
        I0 = dnx_sw_state_get_nof_elements(unit,
            DNX_FIELD_TCAM_ACCESS_MODULE_ID,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);
        i0 = dnx_sw_state_dump_check_all_the_same(unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params
            , sizeof(*((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params), I0, &s0) ? I0 - 1 : 0;
    }
    for(; i0 < I0; i0++) {
        dnx_sw_state_dump_update_current_idx(unit, i0);
        DNX_SW_STATE_PRINT_MONITOR(
            unit,
            "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[%s%d].prefix_size: ", s0, i0);

        DNX_SW_STATE_PRINT_FILE(
            unit,
            "[%s%d]: ", s0, i0);

        dnx_sw_state_print_uint32(
            unit,
            &((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params[i0].prefix_size);

    }
    dnx_sw_state_dump_end_of_stride(unit);
    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable prefix_value
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
dnx_field_tcam_access_sw_fg_params_prefix_value_dump(int  unit,  int  fg_params_idx_0)
{
    int i0 = fg_params_idx_0, I0 = fg_params_idx_0 + 1;
    char *s0 = "";
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "dnx_field_tcam_access_sw/fg_params/prefix_value.txt",
        "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[].prefix_value: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID]));

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);

    if (i0 == -1) {
        I0 = dnx_sw_state_get_nof_elements(unit,
            DNX_FIELD_TCAM_ACCESS_MODULE_ID,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);
        i0 = dnx_sw_state_dump_check_all_the_same(unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params
            , sizeof(*((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params), I0, &s0) ? I0 - 1 : 0;
    }
    for(; i0 < I0; i0++) {
        dnx_sw_state_dump_update_current_idx(unit, i0);
        DNX_SW_STATE_PRINT_MONITOR(
            unit,
            "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[%s%d].prefix_value: ", s0, i0);

        DNX_SW_STATE_PRINT_FILE(
            unit,
            "[%s%d]: ", s0, i0);

        dnx_sw_state_print_uint32(
            unit,
            &((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params[i0].prefix_value);

    }
    dnx_sw_state_dump_end_of_stride(unit);
    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable direct_table
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
dnx_field_tcam_access_sw_fg_params_direct_table_dump(int  unit,  int  fg_params_idx_0)
{
    int i0 = fg_params_idx_0, I0 = fg_params_idx_0 + 1;
    char *s0 = "";
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "dnx_field_tcam_access_sw/fg_params/direct_table.txt",
        "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[].direct_table: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID]));

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);

    if (i0 == -1) {
        I0 = dnx_sw_state_get_nof_elements(unit,
            DNX_FIELD_TCAM_ACCESS_MODULE_ID,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);
        i0 = dnx_sw_state_dump_check_all_the_same(unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params
            , sizeof(*((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params), I0, &s0) ? I0 - 1 : 0;
    }
    for(; i0 < I0; i0++) {
        dnx_sw_state_dump_update_current_idx(unit, i0);
        DNX_SW_STATE_PRINT_MONITOR(
            unit,
            "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[%s%d].direct_table: ", s0, i0);

        DNX_SW_STATE_PRINT_FILE(
            unit,
            "[%s%d]: ", s0, i0);

        dnx_sw_state_print_uint8(
            unit,
            &((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params[i0].direct_table);

    }
    dnx_sw_state_dump_end_of_stride(unit);
    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable dt_bank_id
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
dnx_field_tcam_access_sw_fg_params_dt_bank_id_dump(int  unit,  int  fg_params_idx_0)
{
    int i0 = fg_params_idx_0, I0 = fg_params_idx_0 + 1;
    char *s0 = "";
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "dnx_field_tcam_access_sw/fg_params/dt_bank_id.txt",
        "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[].dt_bank_id: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID]));

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);

    if (i0 == -1) {
        I0 = dnx_sw_state_get_nof_elements(unit,
            DNX_FIELD_TCAM_ACCESS_MODULE_ID,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);
        i0 = dnx_sw_state_dump_check_all_the_same(unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params
            , sizeof(*((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params), I0, &s0) ? I0 - 1 : 0;
    }
    for(; i0 < I0; i0++) {
        dnx_sw_state_dump_update_current_idx(unit, i0);
        DNX_SW_STATE_PRINT_MONITOR(
            unit,
            "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[%s%d].dt_bank_id: ", s0, i0);

        DNX_SW_STATE_PRINT_FILE(
            unit,
            "[%s%d]: ", s0, i0);

        dnx_sw_state_print_int(
            unit,
            &((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params[i0].dt_bank_id);

    }
    dnx_sw_state_dump_end_of_stride(unit);
    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable bank_allocation_mode
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
dnx_field_tcam_access_sw_fg_params_bank_allocation_mode_dump(int  unit,  int  fg_params_idx_0)
{
    int i0 = fg_params_idx_0, I0 = fg_params_idx_0 + 1;
    char *s0 = "";
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "dnx_field_tcam_access_sw/fg_params/bank_allocation_mode.txt",
        "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[].bank_allocation_mode: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID]));

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);

    if (i0 == -1) {
        I0 = dnx_sw_state_get_nof_elements(unit,
            DNX_FIELD_TCAM_ACCESS_MODULE_ID,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params);
        i0 = dnx_sw_state_dump_check_all_the_same(unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params
            , sizeof(*((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params), I0, &s0) ? I0 - 1 : 0;
    }
    for(; i0 < I0; i0++) {
        dnx_sw_state_dump_update_current_idx(unit, i0);
        DNX_SW_STATE_PRINT_OPAQUE_MONITOR(
            unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params[i0].bank_allocation_mode,
            "dnx_field_tcam_access_sw[%d]->","((dnx_field_tcam_access_t*)sw_state_roots_array[%d][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->","fg_params[%s%d].bank_allocation_mode: ", s0, i0);

        DNX_SW_STATE_PRINT_OPAQUE_FILE(
            unit,
            ((dnx_field_tcam_access_t*)sw_state_roots_array[unit][DNX_FIELD_TCAM_ACCESS_MODULE_ID])->fg_params[i0].bank_allocation_mode,
                "[%s%d]: ", s0, i0);

    }
    dnx_sw_state_dump_end_of_stride(unit);
    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 * Global Variables
 */

dnx_sw_state_diagnostic_info_t dnx_field_tcam_access_sw_info[SOC_MAX_NUM_DEVICES][DNX_FIELD_TCAM_ACCESS_SW_INFO_NOF_ENTRIES];
const char* dnx_field_tcam_access_sw_layout_str[DNX_FIELD_TCAM_ACCESS_SW_INFO_NOF_ENTRIES] = {
    "DNX_FIELD_TCAM_ACCESS_SW~",
    "DNX_FIELD_TCAM_ACCESS_SW~ENTRY_LOCATION_HASH~",
    "DNX_FIELD_TCAM_ACCESS_SW~FG_PARAMS~",
    "DNX_FIELD_TCAM_ACCESS_SW~FG_PARAMS~KEY_SIZE~",
    "DNX_FIELD_TCAM_ACCESS_SW~FG_PARAMS~ACTION_SIZE~",
    "DNX_FIELD_TCAM_ACCESS_SW~FG_PARAMS~ACTUAL_ACTION_SIZE~",
    "DNX_FIELD_TCAM_ACCESS_SW~FG_PARAMS~STAGE~",
    "DNX_FIELD_TCAM_ACCESS_SW~FG_PARAMS~PREFIX_SIZE~",
    "DNX_FIELD_TCAM_ACCESS_SW~FG_PARAMS~PREFIX_VALUE~",
    "DNX_FIELD_TCAM_ACCESS_SW~FG_PARAMS~DIRECT_TABLE~",
    "DNX_FIELD_TCAM_ACCESS_SW~FG_PARAMS~DT_BANK_ID~",
    "DNX_FIELD_TCAM_ACCESS_SW~FG_PARAMS~BANK_ALLOCATION_MODE~",
};
#undef _ERR_MSG_MODULE_NAME
#endif /* DNX_SW_STATE_DIAGNOSTIC */
