/** \file dnx/swstate/auto_generated/diagnostic/lag_diagnostic.c
 *
 * sw state functions definitions
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 */
/*
 * $Copyright: (c) 2018 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */

#ifdef BSL_LOG_MODULE
#error "BSL_LOG_MODULE redefined"
#endif
#define BSL_LOG_MODULE BSL_LS_SWSTATEDNX_GENERAL

typedef int make_iso_compilers_happy_swstatednx;

#include <soc/dnxc/swstate/dnxc_sw_state_c_includes.h>
#include <soc/dnx/swstate/auto_generated/diagnostic/lag_diagnostic.h>
#if defined(DNX_SW_STATE_DIAGNOSTIC)
/*
 * Global Variables
 */

extern JER2_ARAD_LAGS_INFO * lag_state_data[SOC_MAX_NUM_DEVICES];
/*
 * FUNCTIONs
 */

/*
 *
 * dump function for the variable lag_state
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
lag_state_dump(int  unit)
{
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    SHR_IF_ERR_EXIT(lag_state_in_use_dump(unit, -1));
    SHR_IF_ERR_EXIT(lag_state_local_to_reassembly_context_dump(unit, -1));
    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable in_use
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
lag_state_in_use_dump(int  unit,  int  in_use_idx_0)
{
    int i0 = in_use_idx_0, I0 = in_use_idx_0 + 1;
    char *s0 = "";
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "lag_state/in_use.txt",
        "lag_state[%d]->","((JER2_ARAD_LAGS_INFO*)sw_state_roots_array[%d][LAG_MODULE_ID])->","in_use[]: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((JER2_ARAD_LAGS_INFO*)sw_state_roots_array[unit][LAG_MODULE_ID]));

    if (i0 == -1) {
        I0 = JER2_ARAD_NOF_LAG_GROUPS_MAX;
        i0 = dnx_sw_state_dump_check_all_the_same(unit,
            ((JER2_ARAD_LAGS_INFO*)sw_state_roots_array[unit][LAG_MODULE_ID])->in_use
            , sizeof(*((JER2_ARAD_LAGS_INFO*)sw_state_roots_array[unit][LAG_MODULE_ID])->in_use), I0, &s0) ? I0 - 1 : 0;
    }
    for(; i0 < I0; i0++) {
        dnx_sw_state_dump_update_current_idx(unit, i0);
        DNX_SW_STATE_PRINT_MONITOR(
            unit,
            "lag_state[%d]->","((JER2_ARAD_LAGS_INFO*)sw_state_roots_array[%d][LAG_MODULE_ID])->","in_use[%s%d]: ", s0, i0);

        DNX_SW_STATE_PRINT_FILE(
            unit,
            "[%s%d]: ", s0, i0);

        dnx_sw_state_print_uint8(
            unit,
            &((JER2_ARAD_LAGS_INFO*)sw_state_roots_array[unit][LAG_MODULE_ID])->in_use[i0]);

    }
    dnx_sw_state_dump_end_of_stride(unit);
    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 *
 * dump function for the variable local_to_reassembly_context
 * AUTO-GENERATED - DO NOT MODIFY
 *
 */
int
lag_state_local_to_reassembly_context_dump(int  unit,  int  local_to_reassembly_context_idx_0)
{
    int i0 = local_to_reassembly_context_idx_0, I0 = local_to_reassembly_context_idx_0 + 1;
    char *s0 = "";
    DNXC_SW_STATE_INIT_FUNC_DEFS;
    dnx_sw_state_dump_attach_file(
        unit,
        "lag_state/local_to_reassembly_context.txt",
        "lag_state[%d]->","((JER2_ARAD_LAGS_INFO*)sw_state_roots_array[%d][LAG_MODULE_ID])->","local_to_reassembly_context[]: ");

    DNX_SW_STATE_DUMP_PTR_NULL_CHECK(
        unit,
        ((JER2_ARAD_LAGS_INFO*)sw_state_roots_array[unit][LAG_MODULE_ID]));

    if (i0 == -1) {
        I0 = JER2_ARAD_NOF_LOCAL_PORTS_MAX;
        i0 = dnx_sw_state_dump_check_all_the_same(unit,
            ((JER2_ARAD_LAGS_INFO*)sw_state_roots_array[unit][LAG_MODULE_ID])->local_to_reassembly_context
            , sizeof(*((JER2_ARAD_LAGS_INFO*)sw_state_roots_array[unit][LAG_MODULE_ID])->local_to_reassembly_context), I0, &s0) ? I0 - 1 : 0;
    }
    for(; i0 < I0; i0++) {
        dnx_sw_state_dump_update_current_idx(unit, i0);
        DNX_SW_STATE_PRINT_MONITOR(
            unit,
            "lag_state[%d]->","((JER2_ARAD_LAGS_INFO*)sw_state_roots_array[%d][LAG_MODULE_ID])->","local_to_reassembly_context[%s%d]: ", s0, i0);

        DNX_SW_STATE_PRINT_FILE(
            unit,
            "[%s%d]: ", s0, i0);

        dnx_sw_state_print_uint32(
            unit,
            &((JER2_ARAD_LAGS_INFO*)sw_state_roots_array[unit][LAG_MODULE_ID])->local_to_reassembly_context[i0]);

    }
    dnx_sw_state_dump_end_of_stride(unit);
    dnx_sw_state_dump_detach_file(
        unit);

    DNXC_SW_STATE_FUNC_RETURN;
}



/*
 * Global Variables
 */

dnx_sw_state_diagnostic_info_t lag_state_info[SOC_MAX_NUM_DEVICES][LAG_STATE_INFO_NOF_ENTRIES];
const char* lag_state_layout_str[LAG_STATE_INFO_NOF_ENTRIES] = {
    "LAG_STATE~",
    "LAG_STATE~IN_USE~",
    "LAG_STATE~LOCAL_TO_REASSEMBLY_CONTEXT~",
};
#undef _ERR_MSG_MODULE_NAME
#endif /* DNX_SW_STATE_DIAGNOSTIC */
