# $Id: $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for streamlined packet I/O drivers
#

LOCALDIR = src/bcm/esw/pktio/chip/bcm56980_a0

PKTIO_IMPL = 1
CFLAGS =
include ${SDK}/make/Make.config

lib = libesw_pktio_bcm56980_a0

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

