/* $Id: $
 * 
 * $Copyright: Copyright 2016 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#include <sal/core/libc.h>
#include <shared/swstate/sw_state.h>
#include <shared/error.h>
#include <shared/swstate/sw_state_defs.h>
#include <shared/bsl.h>
#include <shared/swstate/access/sw_state_access.h>
#include <shared/swstate/access/sw_state_dpp_bcm_l2_access.h>

#ifdef _ERR_MSG_MODULE_NAME
    #error "_ERR_MSG_MODULE_NAME redefined"
#endif

#define _ERR_MSG_MODULE_NAME BSL_LS_SHARED_SWSTATE

extern shr_sw_state_t *sw_state[BCM_MAX_NUM_UNITS];

/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_set(int _unit, CONST l2_data_t *l2){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.verify( _unit));
    SHR_SW_STATE_MEMSET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2[0],
        l2,
        l2_data_t,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_get(int _unit, l2_data_t *l2){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.verify( _unit));
    *l2 = sw_state[_unit]->dpp.bcm.l2[0];
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_alloc(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_ALLOC(
        _unit,
        sw_state[_unit]->dpp.bcm.l2,
        sizeof(l2_data_t),
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_alloc");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_is_allocated(int _unit, uint8 *is_allocated){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_IS_ALLOC(
        _unit,
        sw_state[_unit]->dpp.bcm.l2,
        is_allocated,
        SW_STATE_NONE,
        "sw_state_dpp_bcm_l2_alloc");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_free(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_FREE(
        _unit,
        sw_state[_unit]->dpp.bcm.l2,
        SW_STATE_NONE,
        "sw_state_dpp_bcm_l2_alloc");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_NULL_ACCESS_CHECK(sw_state[_unit]->dpp.bcm.l2);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mymac_msb_is_set_set(int _unit, uint8 mymac_msb_is_set){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.mymac_msb_is_set.verify( _unit));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->mymac_msb_is_set,
        mymac_msb_is_set,
        uint8,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_mymac_msb_is_set_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mymac_msb_is_set_get(int _unit, uint8 *mymac_msb_is_set){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.mymac_msb_is_set.verify( _unit));
    *mymac_msb_is_set = sw_state[_unit]->dpp.bcm.l2->mymac_msb_is_set;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mymac_msb_is_set_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_l2_initialized_set(int _unit, int l2_initialized){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.l2_initialized.verify( _unit));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->l2_initialized,
        l2_initialized,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_l2_initialized_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_l2_initialized_get(int _unit, int *l2_initialized){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.l2_initialized.verify( _unit));
    *l2_initialized = sw_state[_unit]->dpp.bcm.l2->l2_initialized;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_l2_initialized_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_set(int _unit, CONST _bcm_petra_l2_freeze_t *bcm_petra_l2_freeze_state){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.verify( _unit));
    SHR_SW_STATE_MEMSET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state,
        bcm_petra_l2_freeze_state,
        _bcm_petra_l2_freeze_t,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_get(int _unit, _bcm_petra_l2_freeze_t *bcm_petra_l2_freeze_state){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.verify( _unit));
    *bcm_petra_l2_freeze_state = sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_set(int _unit, int frozen){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.frozen.verify( _unit));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.frozen,
        frozen,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_get(int _unit, int *frozen){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.frozen.verify( _unit));
    *frozen = sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.frozen;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_set(int _unit, int save_age_ena){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_age_ena.verify( _unit));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.save_age_ena,
        save_age_ena,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_get(int _unit, int *save_age_ena){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_age_ena.verify( _unit));
    *save_age_ena = sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.save_age_ena;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_set(int _unit, int save_learn_ena){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_learn_ena.verify( _unit));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.save_learn_ena,
        save_learn_ena,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_get(int _unit, int *save_learn_ena){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_learn_ena.verify( _unit));
    *save_learn_ena = sw_state[_unit]->dpp.bcm.l2->bcm_petra_l2_freeze_state.save_learn_ena;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_set(int _unit, uint16 mpls_extended_label_ether_type_index_table_is_set){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.mpls_extended_label_ether_type_index_table_is_set.verify( _unit));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->mpls_extended_label_ether_type_index_table_is_set,
        mpls_extended_label_ether_type_index_table_is_set,
        uint16,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_get(int _unit, uint16 *mpls_extended_label_ether_type_index_table_is_set){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.mpls_extended_label_ether_type_index_table_is_set.verify( _unit));
    *mpls_extended_label_ether_type_index_table_is_set = sw_state[_unit]->dpp.bcm.l2->mpls_extended_label_ether_type_index_table_is_set;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_set(int _unit, CONST _bcm_l2_cache_index_t *index_control){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.index_control.verify( _unit));
    SHR_SW_STATE_MEMSET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->index_control,
        index_control,
        _bcm_l2_cache_index_t,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_index_control_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_get(int _unit, _bcm_l2_cache_index_t *index_control){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.index_control.verify( _unit));
    *index_control = sw_state[_unit]->dpp.bcm.l2->index_control;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_set(int _unit, int index_entry_idx_0, CONST _bcm_l2_cache_index_control_t *index_entry){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.verify( _unit, index_entry_idx_0));
    SHR_SW_STATE_MEMSET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->index_control.index_entry[index_entry_idx_0],
        index_entry,
        _bcm_l2_cache_index_control_t,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_index_control_index_entry_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_get(int _unit, int index_entry_idx_0, _bcm_l2_cache_index_control_t *index_entry){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.verify( _unit, index_entry_idx_0));
    *index_entry = sw_state[_unit]->dpp.bcm.l2->index_control.index_entry[index_entry_idx_0];
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_verify(int _unit, int index_entry_idx_0){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.index_control.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_OUT_OF_BOUND_CHECK( index_entry_idx_0, _BCM_NUMBER_OF_L2_CACHE_INDEX_CONTROL, "index_entry");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_index_type_set(int _unit, int index_entry_idx_0, _bcm_l2_cache_index_type_e index_type){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.index_type.verify( _unit, index_entry_idx_0));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->index_control.index_entry[index_entry_idx_0].index_type,
        index_type,
        _bcm_l2_cache_index_type_e,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_index_control_index_entry_index_type_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_index_type_get(int _unit, int index_entry_idx_0, _bcm_l2_cache_index_type_e *index_type){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.index_type.verify( _unit, index_entry_idx_0));
    *index_type = sw_state[_unit]->dpp.bcm.l2->index_control.index_entry[index_entry_idx_0].index_type;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_index_type_verify(int _unit, int index_entry_idx_0){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.verify( _unit, index_entry_idx_0);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_mac_lsb_set(int _unit, int index_entry_idx_0, int mac_lsb){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.mac_lsb.verify( _unit, index_entry_idx_0));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->index_control.index_entry[index_entry_idx_0].mac_lsb,
        mac_lsb,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_index_control_index_entry_mac_lsb_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_mac_lsb_get(int _unit, int index_entry_idx_0, int *mac_lsb){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.mac_lsb.verify( _unit, index_entry_idx_0));
    *mac_lsb = sw_state[_unit]->dpp.bcm.l2->index_control.index_entry[index_entry_idx_0].mac_lsb;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_mac_lsb_verify(int _unit, int index_entry_idx_0){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.verify( _unit, index_entry_idx_0);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_port_set(int _unit, int index_entry_idx_0, int port){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.port.verify( _unit, index_entry_idx_0));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->index_control.index_entry[index_entry_idx_0].port,
        port,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_index_control_index_entry_port_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_port_get(int _unit, int index_entry_idx_0, int *port){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.port.verify( _unit, index_entry_idx_0));
    *port = sw_state[_unit]->dpp.bcm.l2->index_control.index_entry[index_entry_idx_0].port;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_port_verify(int _unit, int index_entry_idx_0){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.verify( _unit, index_entry_idx_0);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_prog_profile_set(int _unit, int index_entry_idx_0, int prog_profile){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.prog_profile.verify( _unit, index_entry_idx_0));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.l2->index_control.index_entry[index_entry_idx_0].prog_profile,
        prog_profile,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_l2_index_control_index_entry_prog_profile_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_prog_profile_get(int _unit, int index_entry_idx_0, int *prog_profile){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.prog_profile.verify( _unit, index_entry_idx_0));
    *prog_profile = sw_state[_unit]->dpp.bcm.l2->index_control.index_entry[index_entry_idx_0].prog_profile;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_l2_index_control_index_entry_prog_profile_verify(int _unit, int index_entry_idx_0){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.verify( _unit, index_entry_idx_0);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}



int
sw_state_dpp_bcm_l2_access_cb_init(int _unit){
    sw_state_access[_unit].dpp.bcm.l2.set = sw_state_dpp_bcm_l2_set;
    sw_state_access[_unit].dpp.bcm.l2.get = sw_state_dpp_bcm_l2_get;
    sw_state_access[_unit].dpp.bcm.l2.alloc = sw_state_dpp_bcm_l2_alloc;
    sw_state_access[_unit].dpp.bcm.l2.is_allocated = sw_state_dpp_bcm_l2_is_allocated;
    sw_state_access[_unit].dpp.bcm.l2.free = sw_state_dpp_bcm_l2_free;
    sw_state_access[_unit].dpp.bcm.l2.verify = sw_state_dpp_bcm_l2_verify;
    sw_state_access[_unit].dpp.bcm.l2.mymac_msb_is_set.set = sw_state_dpp_bcm_l2_mymac_msb_is_set_set;
    sw_state_access[_unit].dpp.bcm.l2.mymac_msb_is_set.get = sw_state_dpp_bcm_l2_mymac_msb_is_set_get;
    sw_state_access[_unit].dpp.bcm.l2.mymac_msb_is_set.verify = sw_state_dpp_bcm_l2_mymac_msb_is_set_verify;
    sw_state_access[_unit].dpp.bcm.l2.l2_initialized.set = sw_state_dpp_bcm_l2_l2_initialized_set;
    sw_state_access[_unit].dpp.bcm.l2.l2_initialized.get = sw_state_dpp_bcm_l2_l2_initialized_get;
    sw_state_access[_unit].dpp.bcm.l2.l2_initialized.verify = sw_state_dpp_bcm_l2_l2_initialized_verify;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.set = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_set;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.get = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_get;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.verify = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_verify;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.frozen.set = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_set;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.frozen.get = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_get;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.frozen.verify = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_frozen_verify;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_age_ena.set = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_set;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_age_ena.get = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_get;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_age_ena.verify = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_age_ena_verify;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_learn_ena.set = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_set;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_learn_ena.get = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_get;
    sw_state_access[_unit].dpp.bcm.l2.bcm_petra_l2_freeze_state.save_learn_ena.verify = sw_state_dpp_bcm_l2_bcm_petra_l2_freeze_state_save_learn_ena_verify;
    sw_state_access[_unit].dpp.bcm.l2.mpls_extended_label_ether_type_index_table_is_set.set = sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_set;
    sw_state_access[_unit].dpp.bcm.l2.mpls_extended_label_ether_type_index_table_is_set.get = sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_get;
    sw_state_access[_unit].dpp.bcm.l2.mpls_extended_label_ether_type_index_table_is_set.verify = sw_state_dpp_bcm_l2_mpls_extended_label_ether_type_index_table_is_set_verify;
    sw_state_access[_unit].dpp.bcm.l2.index_control.set = sw_state_dpp_bcm_l2_index_control_set;
    sw_state_access[_unit].dpp.bcm.l2.index_control.get = sw_state_dpp_bcm_l2_index_control_get;
    sw_state_access[_unit].dpp.bcm.l2.index_control.verify = sw_state_dpp_bcm_l2_index_control_verify;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.set = sw_state_dpp_bcm_l2_index_control_index_entry_set;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.get = sw_state_dpp_bcm_l2_index_control_index_entry_get;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.verify = sw_state_dpp_bcm_l2_index_control_index_entry_verify;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.index_type.set = sw_state_dpp_bcm_l2_index_control_index_entry_index_type_set;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.index_type.get = sw_state_dpp_bcm_l2_index_control_index_entry_index_type_get;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.index_type.verify = sw_state_dpp_bcm_l2_index_control_index_entry_index_type_verify;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.mac_lsb.set = sw_state_dpp_bcm_l2_index_control_index_entry_mac_lsb_set;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.mac_lsb.get = sw_state_dpp_bcm_l2_index_control_index_entry_mac_lsb_get;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.mac_lsb.verify = sw_state_dpp_bcm_l2_index_control_index_entry_mac_lsb_verify;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.port.set = sw_state_dpp_bcm_l2_index_control_index_entry_port_set;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.port.get = sw_state_dpp_bcm_l2_index_control_index_entry_port_get;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.port.verify = sw_state_dpp_bcm_l2_index_control_index_entry_port_verify;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.prog_profile.set = sw_state_dpp_bcm_l2_index_control_index_entry_prog_profile_set;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.prog_profile.get = sw_state_dpp_bcm_l2_index_control_index_entry_prog_profile_get;
    sw_state_access[_unit].dpp.bcm.l2.index_control.index_entry.prog_profile.verify = sw_state_dpp_bcm_l2_index_control_index_entry_prog_profile_verify;
    return _SHR_E_NONE;
}

#undef _ERR_MSG_MODULE_NAME
