/* $Id: $
 * 
 * $Copyright: Copyright 2016 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#include <sal/core/libc.h>
#include <shared/swstate/sw_state.h>
#include <shared/error.h>
#include <shared/swstate/sw_state_defs.h>
#include <shared/bsl.h>
#include <shared/swstate/access/sw_state_access.h>
#include <shared/swstate/access/sw_state_dpp_bcm_alloc_mngr_glif_access.h>

#ifdef _ERR_MSG_MODULE_NAME
    #error "_ERR_MSG_MODULE_NAME redefined"
#endif

#define _ERR_MSG_MODULE_NAME BSL_LS_SHARED_SWSTATE

extern shr_sw_state_t *sw_state[BCM_MAX_NUM_UNITS];

/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_alloc(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_ALLOC(
        _unit,
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif,
        sizeof(bcm_dpp_alloc_mngr_glif_info_t),
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_alloc_mngr_glif_alloc");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_is_allocated(int _unit, uint8 *is_allocated){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_IS_ALLOC(
        _unit,
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif,
        is_allocated,
        SW_STATE_NONE,
        "sw_state_dpp_bcm_alloc_mngr_glif_alloc");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_free(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_FREE(
        _unit,
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif,
        SW_STATE_NONE,
        "sw_state_dpp_bcm_alloc_mngr_glif_alloc");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_NULL_ACCESS_CHECK(sw_state[_unit]->dpp.bcm.alloc_mngr_glif);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_egress_lif_to_global_lif_set(int _unit, int egress_lif_to_global_lif_idx_0, int egress_lif_to_global_lif){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.egress_lif_to_global_lif.verify( _unit, egress_lif_to_global_lif_idx_0));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->egress_lif_to_global_lif[egress_lif_to_global_lif_idx_0],
        egress_lif_to_global_lif,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_alloc_mngr_glif_egress_lif_to_global_lif_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_egress_lif_to_global_lif_get(int _unit, int egress_lif_to_global_lif_idx_0, int *egress_lif_to_global_lif){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.egress_lif_to_global_lif.verify( _unit, egress_lif_to_global_lif_idx_0));
    *egress_lif_to_global_lif = sw_state[_unit]->dpp.bcm.alloc_mngr_glif->egress_lif_to_global_lif[egress_lif_to_global_lif_idx_0];
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_egress_lif_to_global_lif_verify(int _unit, int egress_lif_to_global_lif_idx_0){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_OUT_OF_BOUND_CHECK( egress_lif_to_global_lif_idx_0, SOC_DPP_DEFS_MAX(NOF_OUT_LIFS), "egress_lif_to_global_lif");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_ingress_lif_to_global_lif_set(int _unit, int ingress_lif_to_global_lif_idx_0, int ingress_lif_to_global_lif){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.ingress_lif_to_global_lif.verify( _unit, ingress_lif_to_global_lif_idx_0));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->ingress_lif_to_global_lif[ingress_lif_to_global_lif_idx_0],
        ingress_lif_to_global_lif,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_alloc_mngr_glif_ingress_lif_to_global_lif_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_ingress_lif_to_global_lif_get(int _unit, int ingress_lif_to_global_lif_idx_0, int *ingress_lif_to_global_lif){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.ingress_lif_to_global_lif.verify( _unit, ingress_lif_to_global_lif_idx_0));
    *ingress_lif_to_global_lif = sw_state[_unit]->dpp.bcm.alloc_mngr_glif->ingress_lif_to_global_lif[ingress_lif_to_global_lif_idx_0];
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_ingress_lif_to_global_lif_verify(int _unit, int ingress_lif_to_global_lif_idx_0){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_OUT_OF_BOUND_CHECK( ingress_lif_to_global_lif_idx_0, SOC_DPP_DEFS_MAX(NOF_LOCAL_LIFS), "ingress_lif_to_global_lif");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_ingress_global_lif_to_lif_htb_handle_set(int _unit, int ingress_global_lif_to_lif_htb_handle){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.ingress_global_lif_to_lif_htb_handle.verify( _unit));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->ingress_global_lif_to_lif_htb_handle,
        ingress_global_lif_to_lif_htb_handle,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_alloc_mngr_glif_ingress_global_lif_to_lif_htb_handle_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_ingress_global_lif_to_lif_htb_handle_get(int _unit, int *ingress_global_lif_to_lif_htb_handle){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.ingress_global_lif_to_lif_htb_handle.verify( _unit));
    *ingress_global_lif_to_lif_htb_handle = sw_state[_unit]->dpp.bcm.alloc_mngr_glif->ingress_global_lif_to_lif_htb_handle;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_ingress_global_lif_to_lif_htb_handle_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_egress_global_lif_to_lif_htb_handle_set(int _unit, int egress_global_lif_to_lif_htb_handle){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.egress_global_lif_to_lif_htb_handle.verify( _unit));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->egress_global_lif_to_lif_htb_handle,
        egress_global_lif_to_lif_htb_handle,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_alloc_mngr_glif_egress_global_lif_to_lif_htb_handle_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_egress_global_lif_to_lif_htb_handle_get(int _unit, int *egress_global_lif_to_lif_htb_handle){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.egress_global_lif_to_lif_htb_handle.verify( _unit));
    *egress_global_lif_to_lif_htb_handle = sw_state[_unit]->dpp.bcm.alloc_mngr_glif->egress_global_lif_to_lif_htb_handle;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_egress_global_lif_to_lif_htb_handle_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_alloc_bitmap(int _unit, int _nof_bits_to_alloc){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_ALLOC_BITMAP(
        _unit,
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
        _nof_bits_to_alloc,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_alloc");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_free(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_FREE(
        _unit,
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
        SW_STATE_NONE,
        "sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_alloc");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_set(int _unit, int _bit_num){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _bit_num, _bit_num, "global_lif_bank_status");
        SHR_SW_STATE_BIT_SET(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         _bit_num);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_clear(int _unit, int _bit_num){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _bit_num, _bit_num, "global_lif_bank_status");
        SHR_SW_STATE_BIT_CLEAR(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         _bit_num);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_get(int _unit, int _bit_num, uint8* result){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _bit_num, _bit_num, "global_lif_bank_status");
        SHR_SW_STATE_BIT_GET(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         _bit_num,
         result);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_read(int _unit, int sw_state_bmp_first, int result_first, int _range, SHR_BITDCL *result){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, sw_state_bmp_first, sw_state_bmp_first + _range - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_READ(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         sw_state_bmp_first,
         result_first,
         _range,
         result);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_write(int _unit, int sw_state_bmp_first, int input_bmp_first, int _range, SHR_BITDCL *input_bmp){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, sw_state_bmp_first, sw_state_bmp_first + _range - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_WRITE(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         sw_state_bmp_first,
         input_bmp_first,
          _range,
         input_bmp);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_and(int _unit, int _first, int _count, SHR_BITDCL *input_bmp){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _first, _first + _count - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_AND(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         input_bmp,
         _first,
         _count);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_or(int _unit, int _first, int _count, SHR_BITDCL *input_bmp){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _first, _first + _count - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_OR(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         input_bmp,
         _first,
         _count);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_xor(int _unit, int _first, int _count, SHR_BITDCL *input_bmp){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _first, _first + _count - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_XOR(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         input_bmp,
         _first,
         _count);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_remove(int _unit, int _first, int _count, SHR_BITDCL *input_bmp){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _first, _first + _count - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_REMOVE(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         input_bmp,
         _first,
         _count);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_negate(int _unit, int _first, int _count){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _first, _first + _count - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_NEGATE(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         _first,
         _count);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_clear(int _unit, int _first, int _count){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _first, _first + _count - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_CLEAR(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         _first,
         _count);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_set(int _unit, int _first, int _count){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _first, _first + _count - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_SET(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         _first,
         _count);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_null(int _unit, int _first, int _count, uint8 *result){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _first, _first + _count - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_NULL(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         _first,
         _count,
         result);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_test(int _unit, int _first, int _count, uint8 *result){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _first, _first + _count - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_TEST(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         _first,
         _count,
         result);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_eq(int _unit, SHR_BITDCL *input_bmp, int _first, int _count, uint8 *result){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _first, _first + _count - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_EQ(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         _first,
         _count,
         input_bmp,
         result);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_count(int _unit, int _first, int _range, int *result){
    SW_STATE_INIT_FUNC_DEFS;
    SW_STATE_BITDCL_VERIFY(sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify(_unit),
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status, _first, _first + _range - 1, "global_lif_bank_status");
        SHR_SW_STATE_BIT_RANGE_COUNT(
        _unit,
         SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
         sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_bank_status,
         _first,
         _range,
         result);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_egress_count_set(int _unit, int global_lif_egress_count){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_egress_count.verify( _unit));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_egress_count,
        global_lif_egress_count,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_alloc_mngr_glif_global_lif_egress_count_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_egress_count_get(int _unit, int *global_lif_egress_count){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_egress_count.verify( _unit));
    *global_lif_egress_count = sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_egress_count;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_egress_count_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_ingress_count_set(int _unit, int global_lif_ingress_count){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_ingress_count.verify( _unit));
    SHR_SW_STATE_SET(
        _unit,
        sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_ingress_count,
        global_lif_ingress_count,
        int,
        SW_STATE_IS_WB_CHECK | SW_STATE_ALLOW_AUTOSYNC,
        "sw_state_dpp_bcm_alloc_mngr_glif_global_lif_ingress_count_set");
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_ingress_count_get(int _unit, int *global_lif_ingress_count){
    SW_STATE_INIT_FUNC_DEFS;
    SHR_SW_STATE_VERIFY( sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_ingress_count.verify( _unit));
    *global_lif_ingress_count = sw_state[_unit]->dpp.bcm.alloc_mngr_glif->global_lif_ingress_count;
    SW_STATE_FUNC_RETURN;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_bcm_alloc_mngr_glif_global_lif_ingress_count_verify(int _unit){
    SW_STATE_INIT_FUNC_DEFS;
    _rv = sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify( _unit);
    _SOC_IF_ERR_EXIT(_rv);
    SW_STATE_FUNC_RETURN;
}



int
sw_state_dpp_bcm_alloc_mngr_glif_access_cb_init(int _unit){
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.alloc = sw_state_dpp_bcm_alloc_mngr_glif_alloc;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.is_allocated = sw_state_dpp_bcm_alloc_mngr_glif_is_allocated;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.free = sw_state_dpp_bcm_alloc_mngr_glif_free;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.verify = sw_state_dpp_bcm_alloc_mngr_glif_verify;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.egress_lif_to_global_lif.set = sw_state_dpp_bcm_alloc_mngr_glif_egress_lif_to_global_lif_set;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.egress_lif_to_global_lif.get = sw_state_dpp_bcm_alloc_mngr_glif_egress_lif_to_global_lif_get;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.egress_lif_to_global_lif.verify = sw_state_dpp_bcm_alloc_mngr_glif_egress_lif_to_global_lif_verify;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.ingress_lif_to_global_lif.set = sw_state_dpp_bcm_alloc_mngr_glif_ingress_lif_to_global_lif_set;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.ingress_lif_to_global_lif.get = sw_state_dpp_bcm_alloc_mngr_glif_ingress_lif_to_global_lif_get;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.ingress_lif_to_global_lif.verify = sw_state_dpp_bcm_alloc_mngr_glif_ingress_lif_to_global_lif_verify;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.ingress_global_lif_to_lif_htb_handle.set = sw_state_dpp_bcm_alloc_mngr_glif_ingress_global_lif_to_lif_htb_handle_set;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.ingress_global_lif_to_lif_htb_handle.get = sw_state_dpp_bcm_alloc_mngr_glif_ingress_global_lif_to_lif_htb_handle_get;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.ingress_global_lif_to_lif_htb_handle.verify = sw_state_dpp_bcm_alloc_mngr_glif_ingress_global_lif_to_lif_htb_handle_verify;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.egress_global_lif_to_lif_htb_handle.set = sw_state_dpp_bcm_alloc_mngr_glif_egress_global_lif_to_lif_htb_handle_set;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.egress_global_lif_to_lif_htb_handle.get = sw_state_dpp_bcm_alloc_mngr_glif_egress_global_lif_to_lif_htb_handle_get;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.egress_global_lif_to_lif_htb_handle.verify = sw_state_dpp_bcm_alloc_mngr_glif_egress_global_lif_to_lif_htb_handle_verify;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.alloc_bitmap = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_alloc_bitmap;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.free = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_free;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_set = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_set;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_clear = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_clear;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_get = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_get;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_read = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_read;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_write = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_write;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_and = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_and;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_or = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_or;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_xor = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_xor;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_remove = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_remove;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_negate = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_negate;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_clear = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_clear;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_set = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_set;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_null = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_null;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_test = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_test;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_eq = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_eq;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_bank_status.bit_range_count = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_bank_status_bit_range_count;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_egress_count.set = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_egress_count_set;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_egress_count.get = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_egress_count_get;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_egress_count.verify = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_egress_count_verify;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_ingress_count.set = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_ingress_count_set;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_ingress_count.get = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_ingress_count_get;
    sw_state_access[_unit].dpp.bcm.alloc_mngr_glif.global_lif_ingress_count.verify = sw_state_dpp_bcm_alloc_mngr_glif_global_lif_ingress_count_verify;
    return _SHR_E_NONE;
}

#undef _ERR_MSG_MODULE_NAME
