# $Id: Makefile,v 1.2 2013/01/02 14:11:45 assaf Exp $
# $Copyright: (c) 2005 Broadcom Corp.
# All Rights Reserved.$

PLATFORM=m32

include ${SDK}/make/Make.config


lib = libsoc_kbp_nlm2_gtmftm_refapp

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

