#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dnx/synce

include ${SDK}/make/Make.config
include ${SDK}/make/Make.subdirs

lib = libsoc_dnxsynce

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
