#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/ctest/dnx/field

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libctest_dnxfield

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

