#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = libs/flexe_core/std

include ${SDK}/make/Make.config
include ${SDK}/make/Make.subdirs

lib = libflexe_core_std

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
