# makefile generated for /home/lvl7build/build/RELEASE_610_FP_6.1.0.5-FastPath-Ent-esw-xgs3-bmw-LR-CSxw-IQH
# Common top-level makefile to get things started.
#
include make_configure
-include $(OUTPATH)/Makefile
include src/l7tools/build/make.configure
