# $Id: Makefile,v 1.0 2017/05/18 vashisht Exp $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for Flowtracker Library
#

LOCALDIR = src/bcm/esw/flowtracker

include ${SDK}/make/Make.config

lib = libflowtracker

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

