#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/port

include ${SDK}/make/Make.config

subdirs = imb 
subdirs += flexe

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxport

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

