/** \file dnx_data_max_instru.h
 * 
 * MODULE DATA MAX - 
 * Maintain max value (of all devices) per define
 * 
 * Device Data
 * SW component that maintains per device data
 * For additional details about Device Data Component goto 'dnxc_data_mgmt.h'
 *        
 *     
 * 
 * AUTO-GENERATED BY AUTOCODER!
 * DO NOT EDIT THIS FILE!
 */
/* *INDENT-OFF* */
/*
 * $Copyright: (c) 2019 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */
#ifndef _DNX_DATA_MAX_INSTRU_H_
/*{*/
#define _DNX_DATA_MAX_INSTRU_H_
/*
 * INCLUDE FILES:
 * {
 */
/*
 * }
 */

/*!
* \brief This file is only used by DNX (JR2 family). Including it by
* software that is not specific to DNX is an error.
*/
#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif

/*
 * MAX DEFINES:
 * {
 */
/**
 * \brief
 * Maximum number of possible sFlow encap entries
 */
#define DNX_DATA_MAX_INSTRU_SFLOW_MAX_NOF_SFLOW_ENCAPS (16)

/**
 * \brief
 * Number of RAW entries used per sFlow ETPS stack
 */
#define DNX_DATA_MAX_INSTRU_SFLOW_NOF_SFLOW_RAW_ENTRIES_PER_STACK (2)

/**
 * \brief
 * rx packet eventor header size in bytes (generated by PP)
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_RX_EVPCK_HEADER_SIZE (16)

/**
 * \brief
 * Eventor Transmit header MAX size in bytes
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_TX_BUILDER_MAX_HEADER_SIZE (124)

/**
 * \brief
 * rx channels, tx contexts
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_NOF_CONTEXTS (16)

/**
 * \brief
 * nof bits in nof_contexts
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_NOF_CONTEXTS_BITS (4)

/**
 * \brief
 * packet generators (builders)
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_NOF_BUILDERS (16)

/**
 * \brief
 * nof bits in packet generators (builders)
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_NOF_BUILDERS_BITS (4)

/**
 * \brief
 * Number of SRAM banks
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_NOF_SRAM_BANKS (8)

/**
 * \brief
 * Number of bits in sram bank
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_SRAM_BANK_BITS (3)

/**
 * \brief
 * sram size in bytes including ECC
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_SRAM_BANKS_FULL_SIZE (16384)

/**
 * \brief
 * sram size in bytes excluding ECC
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_SRAM_BANKS_NET_SIZE (13312)

/**
 * \brief
 * builder max buffer size in bytes
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_BUILDER_MAX_BUFFER_SIZE (1600)

/**
 * \brief
 * builder max buffer size in bytes
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_RX_MAX_BUFFER_SIZE (1600)

/**
 * \brief
 * axi address of eventor sram
 */
#define DNX_DATA_MAX_INSTRU_EVENTOR_AXI_SRAM_OFFSET (3892314112)

/**
 * \brief
 * The number of intervals in one round of the Synced counters instrumentation logic
 */
#define DNX_DATA_MAX_INSTRU_SYNCED_COUNTERS_MAX_NOF_INTERVALS (16)

/*
 * }
 */

/*}*/
#endif /*_DNX_DATA_MAX_INSTRU_H_*/
/* *INDENT-ON* */
