FEATURE_LIST := CINT ATPTRANS_SOCKET L3 I2C MEM_SCAN EDITLINE CHASSIS TEST BCM_SAL_PROFILE RCPU INTR APIMODE PTP CUSTOMER MSTP DUNE_UI KBP

DEBUG_OPTIMIZE=FALSE

BCM_PTL_SPT=1

ALL_DNX_CHIPS = 1
ALL_DNXF_CHIPS = 1
#ALL_DPP_CHIPS = 1
#ALL_DFE_CHIPS = 1
override SBX_CHIPS=

VENDOR_LIST = BROADCOM

#VALGRIND_DIR = /projects/NTSW_SW_USRS/common/tools/valgrind-3.11.0

CFGFLAGS += -D__DUNE_LINUX_BCM_CPU_PCIE__
CFGFLAGS += -D_SIMPLE_MEMORY_ALLOCATION_=9
CFGFLAGS += -DUSE_LINUX_BDE_MMAP=1
#CFGFLAGS += -DUSE_EXTERNAL_MEM_CHECKING=1
CFGFLAGS += -DBCM_WARM_BOOT_SUPPORT
CFGFLAGS += -DBCM_WARM_BOOT_SUPPORT_SW_DUMP
CFGFLAGS += -DBCM_EASY_RELOAD_WB_COMPAT_SUPPORT
CFGFLAGS += -DBCM_CONTROL_API_TRACKING
#CFGFLAGS += -DUSE_VALGRIND_CLIENT_REQUESTS -I$(VALGRIND_DIR) -I$(VALGRIND_DIR)/include
CFGFLAGS += -DDNX_INTERNAL

#Flags to prevent gcc 8.1.0 new warnings to appear as errors.
DEBUG_CFLAGS=-Wno-error=stringop-overflow -Wno-error=stringop-truncation -Wno-error=sizeof-pointer-memaccess -Wno-error=misleading-indentation -Wno-error=unused-const-variable -Wno-error=sizeof-array-argument

#LINK_STATIC := 0
KBP_DEVICE := KBP_ALG

VENDOR_LIST=CUSTOMER78 BROADCOM DNX
