#
# $Id: Makefile,v 1.4 2017/11/21 10:43:54 Exp $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/mdb

include ${SDK}/make/Make.config

#subdirs =

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxmdb

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

