#
# $Id:$
# $Copyright: (c) 2017 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC swstate access subdirectory
#
LOCALDIR = src/soc/dnxc/swstate/auto_generated/access

include ${SDK}/make/Make.config

lib = libsoc_dnxcswstate_auto_generated_access

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
