#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/srv6

include ${SDK}/make/Make.config

#subdirs = srv6

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxsrv6

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

