/* $Id: $
 * 
 * $Copyright: Copyright 2015 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#include <sal/core/libc.h>
#include <shared/swstate/sw_state.h>
#include <shared/error.h>
#include <shared/swstate/sw_state_defs.h>
#include <shared/bsl.h>
#include <shared/swstate/access/sw_state_access.h>
#include <shared/swstate/access/sw_state_dpp_soc_arad_tm_reassembly_ctxt_access.h>


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_tm_reassembly_ctxt_set(int _unit, CONST ARAD_REASSBMEBLY_CTXT *reassembly_ctxt){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.verify( _unit);
    sal_memcpy(&(sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt[0]), reassembly_ctxt, sizeof(ARAD_REASSBMEBLY_CTXT));
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt[0]), sizeof(ARAD_REASSBMEBLY_CTXT));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_tm_reassembly_ctxt_get(int _unit, ARAD_REASSBMEBLY_CTXT *reassembly_ctxt){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.verify( _unit);
    *reassembly_ctxt = sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt[0];
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_tm_reassembly_ctxt_alloc(int _unit){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    SW_STATE_IS_ALREADY_ALLOCATED_CHECK(sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt);
    rv = shr_sw_state_alloc(_unit, (uint8 **) &sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt, sizeof(ARAD_REASSBMEBLY_CTXT));
    return rv;
}

/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_tm_reassembly_ctxt_is_allocated(int _unit, uint8 *is_allocated){
    int rv = _SHR_E_NONE;
    *is_allocated = (sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt) ? 1 : 0;
    rv = _SHR_E_NONE;
    return rv;
}

/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_tm_reassembly_ctxt_free(int _unit){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    SW_STATE_NULL_CHECK(sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt);
    rv = shr_sw_state_free(_unit, (uint8 *) sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt);
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_tm_reassembly_ctxt_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.tm.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    SW_STATE_NULL_ACCESS_CHECK(sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt);
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_tm_reassembly_ctxt_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt);
    *ret_size = size;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_tm_reassembly_ctxt_reassembly_ctxt_occ_set(int _unit, SOC_SAND_OCC_BM_PTR reassembly_ctxt_occ){
    int rv = _SHR_E_NONE;
    SW_STATE_IS_WARM_BOOT_CHECK();
    SW_STATE_IS_DEINIT_CHECK();
    rv = sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.reassembly_ctxt_occ.verify( _unit);
    sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt->reassembly_ctxt_occ = reassembly_ctxt_occ;
    shr_sw_state_auto_sync(_unit, ((uint8*) &sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt->reassembly_ctxt_occ), sizeof(SOC_SAND_OCC_BM_PTR));
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_tm_reassembly_ctxt_reassembly_ctxt_occ_get(int _unit, SOC_SAND_OCC_BM_PTR *reassembly_ctxt_occ){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.reassembly_ctxt_occ.verify( _unit);
    *reassembly_ctxt_occ = sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt->reassembly_ctxt_occ;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_tm_reassembly_ctxt_reassembly_ctxt_occ_verify(int _unit){
    int rv = _SHR_E_NONE;
    rv = sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.verify( _unit);
    if (rv != _SHR_E_NONE) return rv;
    return rv;
}


/* AUTO-GENERATED - DO NOT MODIFY */
int sw_state_dpp_soc_arad_tm_reassembly_ctxt_reassembly_ctxt_occ_get_size(int _unit, int *ret_size){
    int rv = _SHR_E_NONE;
    int size = 0;
    INIT_INDEXES();
    size = size + sizeof(sw_state[_unit]->dpp.soc.arad.tm->reassembly_ctxt->reassembly_ctxt_occ);
    *ret_size = size;
    return rv;
}



int
sw_state_dpp_soc_arad_tm_reassembly_ctxt_access_cb_init(int _unit){
    sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.set = sw_state_dpp_soc_arad_tm_reassembly_ctxt_set;
    sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.get = sw_state_dpp_soc_arad_tm_reassembly_ctxt_get;
    sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.alloc = sw_state_dpp_soc_arad_tm_reassembly_ctxt_alloc;
    sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.is_allocated = sw_state_dpp_soc_arad_tm_reassembly_ctxt_is_allocated;
    sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.free = sw_state_dpp_soc_arad_tm_reassembly_ctxt_free;
    sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.verify = sw_state_dpp_soc_arad_tm_reassembly_ctxt_verify;
    sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.get_size = sw_state_dpp_soc_arad_tm_reassembly_ctxt_get_size;
    sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.reassembly_ctxt_occ.set = sw_state_dpp_soc_arad_tm_reassembly_ctxt_reassembly_ctxt_occ_set;
    sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.reassembly_ctxt_occ.get = sw_state_dpp_soc_arad_tm_reassembly_ctxt_reassembly_ctxt_occ_get;
    sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.reassembly_ctxt_occ.verify = sw_state_dpp_soc_arad_tm_reassembly_ctxt_reassembly_ctxt_occ_verify;
    sw_state_access[_unit].dpp.soc.arad.tm.reassembly_ctxt.reassembly_ctxt_occ.get_size = sw_state_dpp_soc_arad_tm_reassembly_ctxt_reassembly_ctxt_occ_get_size;
    return _SHR_E_NONE;
}
