# $Id: Makefile,v 1.2 2012/12/21 10:17:54 kirankum Exp $
# $Copyright: (c) 2011 Broadcom Corp.
# All Rights Reserved.$

LOCALDIR = src/soc/kbp/alg_kbp/portability

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/soc/kbp/alg_kbp/include

lib = libsoc_alg_kbp_portable

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
