/* $Id: ui_pure_defi_gsa_petra_api.h,v 1.2 Broadcom SDK $
 * $Copyright: Copyright 2016 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
*/


#ifndef __UI_PURE_DEFI_GSA_PETRA_API_INCLUDED__
/* { */
#define __UI_PURE_DEFI_GSA_PETRA_API_INCLUDED__

#include <soc/dpp/SAND/Utils/sand_header.h>

#define UI_MC_GRP_MEMBERS_MAX   10


/*
 * Note:
 * the following definitions must range between PARAM_GSA_PETRA_API_START_RANGE_ID
 * and PARAM_GSA_PETRA_API_END_RANGE_ID.
 * See ui_pure_defi.h
 */
typedef enum
{
  PARAM_GSA_PETRA_MC_GRP_OPEN_MC_GRP_OPEN_ID = PARAM_GSA_PETRA_START_RANGE_ID,
  PARAM_GSA_PETRA_MC_GRP_OPEN_MC_GRP_OPEN_MC_ID_ID,
  PARAM_GSA_PETRA_MC_GRP_OPEN_MC_GRP_OPEN_MC_TYPE_ID,
  PARAM_GSA_PETRA_MC_GRP_OPEN_MC_GRP_OPEN_MC_GRP_MEMBERS_ID,
  PARAM_GSA_PETRA_MC_GRP_OPEN_MC_GRP_OPEN_PER_MEMBER_CUD_ID,
  PARAM_GSA_PETRA_MC_GRP_CLOSE_MC_GRP_CLOSE_ID,
  PARAM_GSA_PETRA_MC_GRP_CLOSE_MC_GRP_CLOSE_MC_TYPE_ID,
  PARAM_GSA_PETRA_MC_GRP_CLOSE_MC_GRP_CLOSE_MC_ID_ID,
  PARAM_GSA_PETRA_MC_GRP_GET_MC_GRP_GET_ID,
  PARAM_GSA_PETRA_MC_GRP_GET_MC_GRP_GET_MC_ID_ID,
  PARAM_GSA_PETRA_MC_GRP_GET_MC_GRP_GET_MC_TYPE_ID,
  PARAM_GSA_PETRA_API_MULTICAST_ID,
  PARAM_GSA_PETRA_SCH_SCHEMES_GENERAL_UPDATE_WEIGHT_ID,
  PARAM_GSA_PETRA_SCH_SCHEMES_GENERAL_UPDATE_SWP_P_TM_SCH_HR_CLASS_ID,
  PARAM_GSA_PETRA_SCH_SCHEMES_GENERAL_UPDATE_MAX_ID,
  PARAM_GSA_PETRA_SCH_SCHEMES_GENERAL_UPDATE_MIN_ID,
  PARAM_GSA_PETRA_SCH_SCHEMES_GENERAL_UPDATE_CLASS_NDX_ID,
  PARAM_GSA_PETRA_SCH_SCHEMES_GENERAL_UPDATE_PORT_NDX_ID,
  PARAM_GSA_PETRA_SCH_SCHEMES_GENERAL_UPDATE_ID,
  PARAM_GSA_PETRA_SCH_SCHEMES_GENERAL_GET_ID,
  PARAM_GSA_PETRA_SCH_SCHEMES_GENERAL_GET_CLASS_NDX_ID,
  PARAM_GSA_PETRA_SCH_SCHEMES_GENERAL_GET_PORT_NDX_ID,
  PARAM_GSA_PETRA_SCH_SCHEMES_ID,
  PARAM_GSA_PETRA_CONNECTIVITY_MAP_GET_ID,
  PARAM_GSA_PETRA_CONNECTIVITY_MAP_GET_FAP_NDX_ID,
  PARAM_GSA_PETRA_CONNECTIVITY_MAP_GET_ALL_FAPS_ID,
  PARAM_GSA_PETRA_SERDES_POWER_ID,
  PARAM_GSA_PETRA_SERDES_POWER_DOWN_ID,
  PARAM_GSA_PETRA_SERDES_POWER_DOWN_FE_NDX_ID,
  PARAM_GSA_PETRA_SERDES_POWER_DOWN_SERDES_NDX_ID,
  PARAM_GSA_PETRA_SERDES_POWER_UP_ID,
  PARAM_GSA_PETRA_SERDES_POWER_UP_FE_NDX_ID,
  PARAM_GSA_PETRA_SERDES_POWER_UP_SERDES_NDX_ID,
  PARAM_GSA_PETRA_LINKS_ID,
}
PARAM_GSA_PETRA_API_IDS;

/* } */

#include <soc/dpp/SAND/Utils/sand_footer.h>
/* } __UI_PURE_DEFI_GSA_PETRA_API_INCLUDED__*/
#endif
