/* $Id: ui_pure_defi_sweep_app.h,v 1.2 Broadcom SDK $
 * $Copyright: Copyright 2015 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
*/
#ifndef UI_PURE_DEFI_SWEEP_APP_INCLUDED
/* { */
#define UI_PURE_DEFI_SWEEP_APP_INCLUDED
/*
 * Note:
 * the following definitions must range between PARAM_SWEEP_APP_START_RANGE_ID (2100)
 * and PARAM_SWEEP_APP_END_RANGE_ID (2299).
 * See ui_pure_defi.h
 */
/* for the 'subject' "sweep" (fap20v sweep application). */
#define PARAM_SWEEP_APP_SET_QOS_PARAMS_ID            (PARAM_SWEEP_APP_START_RANGE_ID+0)
#define PARAM_SWEEP_APP_GET_QOS_PARAMS_ID            (PARAM_SWEEP_APP_START_RANGE_ID+1)
#define PARAM_SWEEP_APP_POWER_UP_SERDES_ID           (PARAM_SWEEP_APP_START_RANGE_ID+2)
#define PARAM_SWEEP_APP_POWER_DOWN_SERDES_ID         (PARAM_SWEEP_APP_START_RANGE_ID+3)
#define PARAM_SWEEP_APP_GET_CONNECTIVITY_MAP_ID      (PARAM_SWEEP_APP_START_RANGE_ID+4)
#define PARAM_SWEEP_APP_GRACEFUL_SHUTDOWN_FE_ID      (PARAM_SWEEP_APP_START_RANGE_ID+5)
#define PARAM_SWEEP_APP_SOURCE_FAP_DEVICE_ID         (PARAM_SWEEP_APP_START_RANGE_ID+12)
#define PARAM_SWEEP_APP_DESTINATION_FAP_DEVICE_ID    (PARAM_SWEEP_APP_START_RANGE_ID+13)
#define PARAM_SWEEP_APP_DESTINATION_PORT_ID          (PARAM_SWEEP_APP_START_RANGE_ID+14)
#define PARAM_SWEEP_APP_DESTINATION_CLASS_ID         (PARAM_SWEEP_APP_START_RANGE_ID+15)
#define PARAM_SWEEP_APP_SUB_FLOW_1_VALUE_ID          (PARAM_SWEEP_APP_START_RANGE_ID+16)
#define PARAM_SWEEP_APP_SUB_FLOW_1_TYPE_ID           (PARAM_SWEEP_APP_START_RANGE_ID+17)
#define PARAM_SWEEP_APP_SUB_FLOW_0_VALUE_ID          (PARAM_SWEEP_APP_START_RANGE_ID+18)
#define PARAM_SWEEP_APP_SUB_FLOW_0_TYPE_ID           (PARAM_SWEEP_APP_START_RANGE_ID+19)
#define PARAM_SWEEP_APP_SERDES_ID                    (PARAM_SWEEP_APP_START_RANGE_ID+20)
#define PARAM_SWEEP_APP_FE_DEVICE_ID                 (PARAM_SWEEP_APP_START_RANGE_ID+21)
#define PARAM_SWEEP_APP_FAP_DEVICE_ID                (PARAM_SWEEP_APP_START_RANGE_ID+22)
#define PARAM_SWEEP_APP_QUEUE_ON_MSG_INTERVAL_ID     (PARAM_SWEEP_APP_START_RANGE_ID+23)
#define PARAM_SWEEP_APP_AGGR_ON_MSG_INTERVAL_ID      (PARAM_SWEEP_APP_START_RANGE_ID+24)
#define PARAM_SWEEP_APP_SET_INTERVAL_ID              (PARAM_SWEEP_APP_START_RANGE_ID+25)
#define PARAM_SWEEP_APP_GET_INTERVAL_ID              (PARAM_SWEEP_APP_START_RANGE_ID+26)
#define PARAM_SWEEP_APP_REFRESH_ALL_AGGRS            (PARAM_SWEEP_APP_START_RANGE_ID+27)
#define PARAM_SWEEP_QOS_ID                           (PARAM_SWEEP_APP_START_RANGE_ID+28)
#define PARAM_SWEEP_QOS_GET_ID                       (PARAM_SWEEP_APP_START_RANGE_ID+29)
#define PARAM_SWEEP_QOS_SET_ID                       (PARAM_SWEEP_APP_START_RANGE_ID+30)
#define PARAM_SWEEP_QOS_SCH_ID                       (PARAM_SWEEP_APP_START_RANGE_ID+31)
#define PARAM_SWEEP_VERBOSE_ID                       (PARAM_SWEEP_APP_START_RANGE_ID+33)
#define PARAM_SWEEP_APP_GRACEFUL_RESTORE_FE_ID       (PARAM_SWEEP_APP_START_RANGE_ID+34)
#define PARAM_SWEEP_QOS_MIN_RATE_ID                  (PARAM_SWEEP_APP_START_RANGE_ID+35)
#define PARAM_SWEEP_QOS_MAX_RATE_ID                  (PARAM_SWEEP_APP_START_RANGE_ID+36)
#define PARAM_SWEEP_QOS_LOW_LATENCY_ID               (PARAM_SWEEP_APP_START_RANGE_ID+37)


/* } */
#endif
