#
# $Id: Makefile $
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/appl/diag/dnx/allocation_mngr

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxallocationmngr

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
