# $Id
#
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for Helix5 SOC driver Library
#

LOCALDIR = src/soc/esw/helix5

include ${SDK}/make/Make.config

SUBDIR_HELIX5_FLEXPORT = flexport

subdirs := $(SUBDIR_HELIX5_FLEXPORT)

lib = libsoc_helix5

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

