# $Id: Makefile,v 1.3 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC SAL support (UNIX/POSIX)
#
LOCALDIR = src/sal/core/unix

include ${SDK}/make/Make.config

lib = libsal_core_plat
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
