/* $Id: pb_pp_framework.h,v 1.11 Broadcom SDK $
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
*/
/******************************************************************
*
* FILENAME:       DuneDriver/Soc_petra/SOC_PB_PP/include/soc_pb_pp_framework.h
*
* MODULE PREFIX:  soc_pb_pp
*
* FILE DESCRIPTION:
*
* REMARKS:
* SW License Agreement: Dune Networks (c). CONFIDENTIAL PROPRIETARY INFORMATION.
* Any use of this Software is subject to Software License Agreement
* included in the Driver User Manual of this device.
* Any use of this Software constitutes an agreement to the terms
* of the above Software License Agreement.
******************************************************************/

#ifndef __SOC_PB_PP_FRAMEWORK_INCLUDED__
/* { */
#define __SOC_PB_PP_FRAMEWORK_INCLUDED__

/*************
 * INCLUDES  *
 *************/
/* { */

#include <soc/dpp/SAND/Utils/sand_header.h>

#include <soc/dpp/SAND/Management/sand_general_macros.h>
#include <soc/dpp/SAND/Management/sand_error_code.h>

#include <soc/dpp/Petra/PB_PP/pb_pp_api_framework.h>

/* } */
/*************
 * DEFINES   *
 *************/
/* { */

/************************************************************************/
/* Procedure Descriptors                                                */
/************************************************************************/
#define SOC_PB_PP_PROC_DESC_BASE_GENERAL_FIRST                (SOC_PB_PP_PROC_BITS)
#define SOC_PB_PP_PROC_DESC_BASE_GENERAL_LAST                 (SOC_PB_PP_PROC_DESC_BASE_GENERAL_FIRST + 20)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_PARSE_FIRST              (SOC_PB_PP_PROC_DESC_BASE_GENERAL_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_PARSE_LAST               (SOC_PB_PP_PROC_DESC_BASE_LLP_PARSE_FIRST + 44)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_SA_AUTH_FIRST            (SOC_PB_PP_PROC_DESC_BASE_LLP_PARSE_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_SA_AUTH_LAST             (SOC_PB_PP_PROC_DESC_BASE_LLP_SA_AUTH_FIRST + 28)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_VID_ASSIGN_FIRST         (SOC_PB_PP_PROC_DESC_BASE_LLP_SA_AUTH_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_VID_ASSIGN_LAST          (SOC_PB_PP_PROC_DESC_BASE_LLP_VID_ASSIGN_FIRST + 44)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_FILTER_FIRST             (SOC_PB_PP_PROC_DESC_BASE_LLP_VID_ASSIGN_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_FILTER_LAST              (SOC_PB_PP_PROC_DESC_BASE_LLP_FILTER_FIRST + 44)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_COS_FIRST                (SOC_PB_PP_PROC_DESC_BASE_LLP_FILTER_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_COS_LAST                 (SOC_PB_PP_PROC_DESC_BASE_LLP_COS_FIRST + 68)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_TRAP_FIRST               (SOC_PB_PP_PROC_DESC_BASE_LLP_COS_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_TRAP_LAST                (SOC_PB_PP_PROC_DESC_BASE_LLP_TRAP_FIRST + 44)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_MIRROR_FIRST             (SOC_PB_PP_PROC_DESC_BASE_LLP_TRAP_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LLP_MIRROR_LAST              (SOC_PB_PP_PROC_DESC_BASE_LLP_MIRROR_FIRST + 32)
#define SOC_PB_PP_PROC_DESC_BASE_MYMAC_FIRST                  (SOC_PB_PP_PROC_DESC_BASE_LLP_MIRROR_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_MYMAC_LAST                   (SOC_PB_PP_PROC_DESC_BASE_MYMAC_FIRST + 68)
#define SOC_PB_PP_PROC_DESC_BASE_MPLS_TERM_FIRST              (SOC_PB_PP_PROC_DESC_BASE_MYMAC_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_MPLS_TERM_LAST               (SOC_PB_PP_PROC_DESC_BASE_MPLS_TERM_FIRST + 64)
#define SOC_PB_PP_PROC_DESC_BASE_VSI_FIRST                    (SOC_PB_PP_PROC_DESC_BASE_MPLS_TERM_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_VSI_LAST                     (SOC_PB_PP_PROC_DESC_BASE_VSI_FIRST + 36)
#define SOC_PB_PP_PROC_DESC_BASE_LIF_FIRST                    (SOC_PB_PP_PROC_DESC_BASE_VSI_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LIF_LAST                     (SOC_PB_PP_PROC_DESC_BASE_LIF_FIRST + 104)
#define SOC_PB_PP_PROC_DESC_BASE_RIF_FIRST                    (SOC_PB_PP_PROC_DESC_BASE_LIF_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_RIF_LAST                     (SOC_PB_PP_PROC_DESC_BASE_RIF_FIRST + 70)
#define SOC_PB_PP_PROC_DESC_BASE_LIF_ING_VLAN_EDIT_FIRST      (SOC_PB_PP_PROC_DESC_BASE_RIF_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LIF_ING_VLAN_EDIT_LAST       (SOC_PB_PP_PROC_DESC_BASE_LIF_ING_VLAN_EDIT_FIRST + 52)
#define SOC_PB_PP_PROC_DESC_BASE_LIF_COS_FIRST                (SOC_PB_PP_PROC_DESC_BASE_LIF_ING_VLAN_EDIT_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LIF_COS_LAST                 (SOC_PB_PP_PROC_DESC_BASE_LIF_COS_FIRST + 108)
#define SOC_PB_PP_PROC_DESC_BASE_LIF_TABLE_FIRST              (SOC_PB_PP_PROC_DESC_BASE_LIF_COS_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LIF_TABLE_LAST               (SOC_PB_PP_PROC_DESC_BASE_LIF_TABLE_FIRST + 24)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_MACT_FIRST             (SOC_PB_PP_PROC_DESC_BASE_LIF_TABLE_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_MACT_LAST              (SOC_PB_PP_PROC_DESC_BASE_FRWRD_MACT_FIRST + 45)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_MACT_MGMT_FIRST        (SOC_PB_PP_PROC_DESC_BASE_FRWRD_MACT_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_MACT_MGMT_LAST         (SOC_PB_PP_PROC_DESC_BASE_FRWRD_MACT_MGMT_FIRST + 140)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_IPV4_FIRST             (SOC_PB_PP_PROC_DESC_BASE_FRWRD_MACT_MGMT_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_IPV4_LAST              (SOC_PB_PP_PROC_DESC_BASE_FRWRD_IPV4_FIRST + 150)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_IPV6_FIRST             (SOC_PB_PP_PROC_DESC_BASE_FRWRD_IPV4_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_IPV6_LAST              (SOC_PB_PP_PROC_DESC_BASE_FRWRD_IPV6_FIRST + 92)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_ILM_FIRST              (SOC_PB_PP_PROC_DESC_BASE_FRWRD_IPV6_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_ILM_LAST               (SOC_PB_PP_PROC_DESC_BASE_FRWRD_ILM_FIRST + 40)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_BMACT_FIRST            (SOC_PB_PP_PROC_DESC_BASE_FRWRD_ILM_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_BMACT_LAST             (SOC_PB_PP_PROC_DESC_BASE_FRWRD_BMACT_FIRST + 60)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_TRILL_FIRST            (SOC_PB_PP_PROC_DESC_BASE_FRWRD_BMACT_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_TRILL_LAST             (SOC_PB_PP_PROC_DESC_BASE_FRWRD_TRILL_FIRST + 60)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_EXTEND_P2P_FIRST       (SOC_PB_PP_PROC_DESC_BASE_FRWRD_TRILL_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_EXTEND_P2P_LAST        (SOC_PB_PP_PROC_DESC_BASE_FRWRD_EXTEND_P2P_FIRST + 100)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_FEC_FIRST              (SOC_PB_PP_PROC_DESC_BASE_FRWRD_EXTEND_P2P_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_FRWRD_FEC_LAST               (SOC_PB_PP_PROC_DESC_BASE_FRWRD_FEC_FIRST + 92)
#define SOC_PB_PP_PROC_DESC_BASE_EG_FILTER_FIRST              (SOC_PB_PP_PROC_DESC_BASE_FRWRD_FEC_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_EG_FILTER_LAST               (SOC_PB_PP_PROC_DESC_BASE_EG_FILTER_FIRST + 85)
#define SOC_PB_PP_PROC_DESC_BASE_EG_QOS_FIRST                 (SOC_PB_PP_PROC_DESC_BASE_EG_FILTER_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_EG_QOS_LAST                  (SOC_PB_PP_PROC_DESC_BASE_EG_QOS_FIRST + 36)
#define SOC_PB_PP_PROC_DESC_BASE_EG_ENCAP_FIRST               (SOC_PB_PP_PROC_DESC_BASE_EG_QOS_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_EG_ENCAP_LAST                (SOC_PB_PP_PROC_DESC_BASE_EG_ENCAP_FIRST + 112)
#define SOC_PB_PP_PROC_DESC_BASE_EG_AC_FIRST                  (SOC_PB_PP_PROC_DESC_BASE_EG_ENCAP_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_EG_AC_LAST                   (SOC_PB_PP_PROC_DESC_BASE_EG_AC_FIRST + 52)
#define SOC_PB_PP_PROC_DESC_BASE_EG_VLAN_EDIT_FIRST           (SOC_PB_PP_PROC_DESC_BASE_EG_AC_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_EG_VLAN_EDIT_LAST            (SOC_PB_PP_PROC_DESC_BASE_EG_VLAN_EDIT_FIRST + 68)
#define SOC_PB_PP_PROC_DESC_BASE_EG_MIRROR_FIRST              (SOC_PB_PP_PROC_DESC_BASE_EG_VLAN_EDIT_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_EG_MIRROR_LAST               (SOC_PB_PP_PROC_DESC_BASE_EG_MIRROR_FIRST + 32)
#define SOC_PB_PP_PROC_DESC_BASE_PORT_FIRST                   (SOC_PB_PP_PROC_DESC_BASE_EG_MIRROR_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_PORT_LAST                    (SOC_PB_PP_PROC_DESC_BASE_PORT_FIRST + 44)
#define SOC_PB_PP_PROC_DESC_BASE_LAG_FIRST                    (SOC_PB_PP_PROC_DESC_BASE_PORT_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LAG_LAST                     (SOC_PB_PP_PROC_DESC_BASE_LAG_FIRST + 52)
#define SOC_PB_PP_PROC_DESC_BASE_TRAP_MGMT_FIRST              (SOC_PB_PP_PROC_DESC_BASE_LAG_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_TRAP_MGMT_LAST               (SOC_PB_PP_PROC_DESC_BASE_TRAP_MGMT_FIRST + 56)
#define SOC_PB_PP_PROC_DESC_BASE_METERING_FIRST               (SOC_PB_PP_PROC_DESC_BASE_TRAP_MGMT_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_METERING_LAST                (SOC_PB_PP_PROC_DESC_BASE_METERING_FIRST + 80)
#define SOC_PB_PP_PROC_DESC_BASE_COUNTING_FIRST               (SOC_PB_PP_PROC_DESC_BASE_METERING_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_COUNTING_LAST                (SOC_PB_PP_PROC_DESC_BASE_COUNTING_FIRST + 40)
#define SOC_PB_PP_PROC_DESC_BASE_FP_FIRST                     (SOC_PB_PP_PROC_DESC_BASE_COUNTING_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_FP_LAST                      (SOC_PB_PP_PROC_DESC_BASE_FP_FIRST + 110)
#define SOC_PB_PP_PROC_DESC_BASE_FP_KEY_FIRST                 (SOC_PB_PP_PROC_DESC_BASE_FP_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_FP_KEY_LAST                  (SOC_PB_PP_PROC_DESC_BASE_FP_KEY_FIRST + 100)
#define SOC_PB_PP_PROC_DESC_BASE_DIAG_FIRST                   (SOC_PB_PP_PROC_DESC_BASE_FP_KEY_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_DIAG_LAST                    (SOC_PB_PP_PROC_DESC_BASE_DIAG_FIRST + 95)
#define SOC_PB_PP_PROC_DESC_BASE_SW_DB_FIRST                  (SOC_PB_PP_PROC_DESC_BASE_DIAG_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_SW_DB_LAST                   (SOC_PB_PP_PROC_DESC_BASE_SW_DB_FIRST + 12)
#define SOC_PB_PP_PROC_DESC_BASE_TBL_ACCESS_FIRST             (SOC_PB_PP_PROC_DESC_BASE_SW_DB_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_TBL_ACCESS_LAST              (SOC_PB_PP_PROC_DESC_BASE_TBL_ACCESS_FIRST + 350)
#define SOC_PB_PP_PROC_DESC_BASE_LEM_ACCESS_FIRST             (SOC_PB_PP_PROC_DESC_BASE_TBL_ACCESS_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_LEM_ACCESS_LAST              (SOC_PB_PP_PROC_DESC_BASE_LEM_ACCESS_FIRST + 28)
#define SOC_PB_PP_PROC_DESC_BASE_FRAMEWORK_FIRST              (SOC_PB_PP_PROC_DESC_BASE_LEM_ACCESS_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_FRAMEWORK_LAST               (SOC_PB_PP_PROC_DESC_BASE_FRAMEWORK_FIRST + 14)
#define SOC_PB_PP_PROC_DESC_BASE_ISEM_ACCESS_FIRST            (SOC_PB_PP_PROC_DESC_BASE_FRAMEWORK_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_ISEM_ACCESS_LAST             (SOC_PB_PP_PROC_DESC_BASE_ISEM_ACCESS_FIRST + 12)
#define SOC_PB_PP_PROC_DESC_BASE_MGMT_FIRST                   (SOC_PB_PP_PROC_DESC_BASE_ISEM_ACCESS_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_MGMT_LAST                    (SOC_PB_PP_PROC_DESC_BASE_MGMT_FIRST + 40)
#define SOC_PB_PP_PROC_DESC_BASE_TCAM_FIRST                   (SOC_PB_PP_PROC_DESC_BASE_MGMT_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_TCAM_LAST                    (SOC_PB_PP_PROC_DESC_BASE_TCAM_FIRST + 25)
#define SOC_PB_PP_PROC_DESC_BASE_TCAM_MGMT_FIRST              (SOC_PB_PP_PROC_DESC_BASE_TCAM_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_TCAM_MGMT_LAST               (SOC_PB_PP_PROC_DESC_BASE_TCAM_MGMT_FIRST + 10)
#define SOC_PB_PP_PROC_DESC_BASE_INIT_FIRST                   (SOC_PB_PP_PROC_DESC_BASE_TCAM_MGMT_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_INIT_LAST                    (SOC_PB_PP_PROC_DESC_BASE_INIT_FIRST + 80)
#define SOC_PB_PP_PROC_DESC_BASE_SVEM_ACCESS_FIRST            (SOC_PB_PP_PROC_DESC_BASE_TCAM_LAST)
#define SOC_PB_PP_PROC_DESC_BASE_SVEM_ACCESS_LAST             (SOC_PB_PP_PROC_DESC_BASE_SVEM_ACCESS_FIRST + 80)
#define SOC_PB_PP_PROC_DESC_BASE_ESEM_FIRST                   (SOC_PB_PP_PROC_DESC_BASE_SVEM_ACCESS_LAST + 1)
#define SOC_PB_PP_PROC_DESC_BASE_ESEM_LAST                    (SOC_PB_PP_PROC_DESC_BASE_ESEM_FIRST + 12)
#define SOC_PB_PP_PROC_DESC_BASE_FP_EGR_FIRST                 (SOC_PB_PP_PROC_DESC_BASE_ESEM_LAST + 1)
#define SOC_PB_PP_PROC_DESC_BASE_FP_EGR_LAST                  (SOC_PB_PP_PROC_DESC_BASE_FP_EGR_FIRST + 12)
#define SOC_PB_PP_PROC_DESC_BASE_FP_FEM_FIRST                 (SOC_PB_PP_PROC_DESC_BASE_FP_EGR_LAST + 1)
#define SOC_PB_PP_PROC_DESC_BASE_FP_FEM_LAST                  (SOC_PB_PP_PROC_DESC_BASE_FP_FEM_FIRST + 12)
#define SOC_PB_PP_PROC_DESC_BASE_SSR_FIRST                    (SOC_PB_PP_PROC_DESC_BASE_FP_FEM_LAST + 1)
#define SOC_PB_PP_PROC_DESC_BASE_SSR_LAST                     (SOC_PB_PP_PROC_DESC_BASE_SSR_FIRST + 15)


/************************************************************************/
/* Error Descriptors                                                    */
/************************************************************************/
#define SOC_PB_PP_ERR_DESC_BASE_GENERAL_FIRST                 (SOC_SAND_PB_PP_START_ERR_NUMBER)
#define SOC_PB_PP_ERR_DESC_BASE_GENERAL_LAST                  (SOC_PB_PP_ERR_DESC_BASE_GENERAL_FIRST + 70)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_PARSE_FIRST               (SOC_PB_PP_ERR_DESC_BASE_GENERAL_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_PARSE_LAST                (SOC_PB_PP_ERR_DESC_BASE_LLP_PARSE_FIRST + 20)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_SA_AUTH_FIRST             (SOC_PB_PP_ERR_DESC_BASE_LLP_PARSE_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_SA_AUTH_LAST              (SOC_PB_PP_ERR_DESC_BASE_LLP_SA_AUTH_FIRST + 9)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_VID_ASSIGN_FIRST          (SOC_PB_PP_ERR_DESC_BASE_LLP_SA_AUTH_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_VID_ASSIGN_LAST           (SOC_PB_PP_ERR_DESC_BASE_LLP_VID_ASSIGN_FIRST + 12)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_FILTER_FIRST              (SOC_PB_PP_ERR_DESC_BASE_LLP_VID_ASSIGN_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_FILTER_LAST               (SOC_PB_PP_ERR_DESC_BASE_LLP_FILTER_FIRST + 13)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_COS_FIRST                 (SOC_PB_PP_ERR_DESC_BASE_LLP_FILTER_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_COS_LAST                  (SOC_PB_PP_ERR_DESC_BASE_LLP_COS_FIRST + 30)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_TRAP_FIRST                (SOC_PB_PP_ERR_DESC_BASE_LLP_COS_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_TRAP_LAST                 (SOC_PB_PP_ERR_DESC_BASE_LLP_TRAP_FIRST + 25)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_MIRROR_FIRST              (SOC_PB_PP_ERR_DESC_BASE_LLP_TRAP_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LLP_MIRROR_LAST               (SOC_PB_PP_ERR_DESC_BASE_LLP_MIRROR_FIRST + 11)
#define SOC_PB_PP_ERR_DESC_BASE_MYMAC_FIRST                   (SOC_PB_PP_ERR_DESC_BASE_LLP_MIRROR_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_MYMAC_LAST                    (SOC_PB_PP_ERR_DESC_BASE_MYMAC_FIRST + 25)
#define SOC_PB_PP_ERR_DESC_BASE_MPLS_TERM_FIRST               (SOC_PB_PP_ERR_DESC_BASE_MYMAC_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_MPLS_TERM_LAST                (SOC_PB_PP_ERR_DESC_BASE_MPLS_TERM_FIRST + 17)
#define SOC_PB_PP_ERR_DESC_BASE_VSI_FIRST                     (SOC_PB_PP_ERR_DESC_BASE_MPLS_TERM_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_VSI_LAST                      (SOC_PB_PP_ERR_DESC_BASE_VSI_FIRST + 15)
#define SOC_PB_PP_ERR_DESC_BASE_LIF_FIRST                     (SOC_PB_PP_ERR_DESC_BASE_VSI_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LIF_LAST                      (SOC_PB_PP_ERR_DESC_BASE_LIF_FIRST + 45)
#define SOC_PB_PP_ERR_DESC_BASE_RIF_FIRST                     (SOC_PB_PP_ERR_DESC_BASE_LIF_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_RIF_LAST                      (SOC_PB_PP_ERR_DESC_BASE_RIF_FIRST + 35)
#define SOC_PB_PP_ERR_DESC_BASE_LIF_ING_VLAN_EDIT_FIRST       (SOC_PB_PP_ERR_DESC_BASE_RIF_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LIF_ING_VLAN_EDIT_LAST        (SOC_PB_PP_ERR_DESC_BASE_LIF_ING_VLAN_EDIT_FIRST + 19)
#define SOC_PB_PP_ERR_DESC_BASE_LIF_COS_FIRST                 (SOC_PB_PP_ERR_DESC_BASE_LIF_ING_VLAN_EDIT_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LIF_COS_LAST                  (SOC_PB_PP_ERR_DESC_BASE_LIF_COS_FIRST + 29)
#define SOC_PB_PP_ERR_DESC_BASE_LIF_TABLE_FIRST               (SOC_PB_PP_ERR_DESC_BASE_LIF_COS_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LIF_TABLE_LAST                (SOC_PB_PP_ERR_DESC_BASE_LIF_TABLE_FIRST + 15)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_MACT_FIRST              (SOC_PB_PP_ERR_DESC_BASE_LIF_TABLE_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_MACT_LAST               (SOC_PB_PP_ERR_DESC_BASE_FRWRD_MACT_FIRST + 25)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_MACT_MGMT_FIRST         (SOC_PB_PP_ERR_DESC_BASE_FRWRD_MACT_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_MACT_MGMT_LAST          (SOC_PB_PP_ERR_DESC_BASE_FRWRD_MACT_MGMT_FIRST + 30)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_IPV4_FIRST              (SOC_PB_PP_ERR_DESC_BASE_FRWRD_MACT_MGMT_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_IPV4_LAST               (SOC_PB_PP_ERR_DESC_BASE_FRWRD_IPV4_FIRST + 40)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_IPV6_FIRST              (SOC_PB_PP_ERR_DESC_BASE_FRWRD_IPV4_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_IPV6_LAST               (SOC_PB_PP_ERR_DESC_BASE_FRWRD_IPV6_FIRST + 17)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_ILM_FIRST               (SOC_PB_PP_ERR_DESC_BASE_FRWRD_IPV6_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_ILM_LAST                (SOC_PB_PP_ERR_DESC_BASE_FRWRD_ILM_FIRST + 10)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_BMACT_FIRST             (SOC_PB_PP_ERR_DESC_BASE_FRWRD_ILM_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_BMACT_LAST              (SOC_PB_PP_ERR_DESC_BASE_FRWRD_BMACT_FIRST + 40)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_TRILL_FIRST             (SOC_PB_PP_ERR_DESC_BASE_FRWRD_BMACT_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_TRILL_LAST              (SOC_PB_PP_ERR_DESC_BASE_FRWRD_TRILL_FIRST + 14)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_EXTEND_P2P_FIRST        (SOC_PB_PP_ERR_DESC_BASE_FRWRD_TRILL_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_EXTEND_P2P_LAST         (SOC_PB_PP_ERR_DESC_BASE_FRWRD_EXTEND_P2P_FIRST + 13)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_FEC_FIRST               (SOC_PB_PP_ERR_DESC_BASE_FRWRD_EXTEND_P2P_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_FRWRD_FEC_LAST                (SOC_PB_PP_ERR_DESC_BASE_FRWRD_FEC_FIRST + 40)
#define SOC_PB_PP_ERR_DESC_BASE_EG_FILTER_FIRST               (SOC_PB_PP_ERR_DESC_BASE_FRWRD_FEC_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_EG_FILTER_LAST                (SOC_PB_PP_ERR_DESC_BASE_EG_FILTER_FIRST + 19)
#define SOC_PB_PP_ERR_DESC_BASE_EG_QOS_FIRST                  (SOC_PB_PP_ERR_DESC_BASE_EG_FILTER_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_EG_QOS_LAST                   (SOC_PB_PP_ERR_DESC_BASE_EG_QOS_FIRST + 15)
#define SOC_PB_PP_ERR_DESC_BASE_EG_ENCAP_FIRST                (SOC_PB_PP_ERR_DESC_BASE_EG_QOS_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_EG_ENCAP_LAST                 (SOC_PB_PP_ERR_DESC_BASE_EG_ENCAP_FIRST + 49)
#define SOC_PB_PP_ERR_DESC_BASE_EG_AC_FIRST                   (SOC_PB_PP_ERR_DESC_BASE_EG_ENCAP_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_EG_AC_LAST                    (SOC_PB_PP_ERR_DESC_BASE_EG_AC_FIRST + 18)
#define SOC_PB_PP_ERR_DESC_BASE_EG_VLAN_EDIT_FIRST            (SOC_PB_PP_ERR_DESC_BASE_EG_AC_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_EG_VLAN_EDIT_LAST             (SOC_PB_PP_ERR_DESC_BASE_EG_VLAN_EDIT_FIRST + 23)
#define SOC_PB_PP_ERR_DESC_BASE_EG_MIRROR_FIRST               (SOC_PB_PP_ERR_DESC_BASE_EG_VLAN_EDIT_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_EG_MIRROR_LAST                (SOC_PB_PP_ERR_DESC_BASE_EG_MIRROR_FIRST + 10)
#define SOC_PB_PP_ERR_DESC_BASE_PORT_FIRST                    (SOC_PB_PP_ERR_DESC_BASE_EG_MIRROR_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_PORT_LAST                     (SOC_PB_PP_ERR_DESC_BASE_PORT_FIRST + 19)
#define SOC_PB_PP_ERR_DESC_BASE_LAG_FIRST                     (SOC_PB_PP_ERR_DESC_BASE_PORT_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LAG_LAST                      (SOC_PB_PP_ERR_DESC_BASE_LAG_FIRST + 18)
#define SOC_PB_PP_ERR_DESC_BASE_TRAP_MGMT_FIRST               (SOC_PB_PP_ERR_DESC_BASE_LAG_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_TRAP_MGMT_LAST                (SOC_PB_PP_ERR_DESC_BASE_TRAP_MGMT_FIRST + 33)
#define SOC_PB_PP_ERR_DESC_BASE_METERING_FIRST                (SOC_PB_PP_ERR_DESC_BASE_TRAP_MGMT_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_METERING_LAST                 (SOC_PB_PP_ERR_DESC_BASE_METERING_FIRST + 45)
#define SOC_PB_PP_ERR_DESC_BASE_COUNTING_FIRST                (SOC_PB_PP_ERR_DESC_BASE_METERING_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_COUNTING_LAST                 (SOC_PB_PP_ERR_DESC_BASE_COUNTING_FIRST + 14)
#define SOC_PB_PP_ERR_DESC_BASE_FP_FIRST                      (SOC_PB_PP_ERR_DESC_BASE_COUNTING_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_FP_LAST                       (SOC_PB_PP_ERR_DESC_BASE_FP_FIRST + 50)
#define SOC_PB_PP_ERR_DESC_BASE_FP_KEY_FIRST                  (SOC_PB_PP_ERR_DESC_BASE_FP_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_FP_KEY_LAST                   (SOC_PB_PP_ERR_DESC_BASE_FP_KEY_FIRST + 40)
#define SOC_PB_PP_ERR_DESC_BASE_DIAG_FIRST                    (SOC_PB_PP_ERR_DESC_BASE_FP_KEY_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_DIAG_LAST                     (SOC_PB_PP_ERR_DESC_BASE_DIAG_FIRST + 50)
#define SOC_PB_PP_ERR_DESC_BASE_SW_DB_FIRST                   (SOC_PB_PP_ERR_DESC_BASE_DIAG_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_SW_DB_LAST                    (SOC_PB_PP_ERR_DESC_BASE_SW_DB_FIRST + 5)
#define SOC_PB_PP_ERR_DESC_BASE_TBL_ACCESS_FIRST              (SOC_PB_PP_ERR_DESC_BASE_SW_DB_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_TBL_ACCESS_LAST               (SOC_PB_PP_ERR_DESC_BASE_TBL_ACCESS_FIRST + 5)
#define SOC_PB_PP_ERR_DESC_BASE_LEM_ACCESS_FIRST              (SOC_PB_PP_ERR_DESC_BASE_TBL_ACCESS_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_LEM_ACCESS_LAST               (SOC_PB_PP_ERR_DESC_BASE_LEM_ACCESS_FIRST + 25)
#define SOC_PB_PP_ERR_DESC_BASE_FRAMEWORK_FIRST               (SOC_PB_PP_ERR_DESC_BASE_LEM_ACCESS_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_FRAMEWORK_LAST                (SOC_PB_PP_ERR_DESC_BASE_FRAMEWORK_FIRST + 5)
#define SOC_PB_PP_ERR_DESC_BASE_ISEM_ACCESS_FIRST             (SOC_PB_PP_ERR_DESC_BASE_FRAMEWORK_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_ISEM_ACCESS_LAST              (SOC_PB_PP_ERR_DESC_BASE_ISEM_ACCESS_FIRST + 5)
#define SOC_PB_PP_ERR_DESC_BASE_MGMT_FIRST                    (SOC_PB_PP_ERR_DESC_BASE_ISEM_ACCESS_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_MGMT_LAST                     (SOC_PB_PP_ERR_DESC_BASE_MGMT_FIRST + 10)
#define SOC_PB_PP_ERR_DESC_BASE_PMF_LOW_LEVEL_FIRST           (SOC_PB_PP_ERR_DESC_BASE_MGMT_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_PMF_LOW_LEVEL_LAST            (SOC_PB_PP_ERR_DESC_BASE_PMF_LOW_LEVEL_FIRST + 80)
#define SOC_PB_PP_ERR_DESC_BASE_TCAM_FIRST                    (SOC_PB_PP_ERR_DESC_BASE_PMF_LOW_LEVEL_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_TCAM_LAST                     (SOC_PB_PP_ERR_DESC_BASE_TCAM_FIRST + 10)
#define SOC_PB_PP_ERR_DESC_BASE_TCAM_MGMT_FIRST               (SOC_PB_PP_ERR_DESC_BASE_TCAM_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_TCAM_MGMT_LAST                (SOC_PB_PP_ERR_DESC_BASE_TCAM_MGMT_FIRST + 5)
#define SOC_PB_PP_ERR_DESC_BASE_INIT_FIRST                    (SOC_PB_PP_ERR_DESC_BASE_TCAM_MGMT_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_INIT_LAST                     (SOC_PB_PP_ERR_DESC_BASE_INIT_FIRST + 10)
#define SOC_PB_PP_ERR_DESC_BASE_SVEM_ACCESS_FIRST             (SOC_PB_PP_ERR_DESC_BASE_INIT_LAST)
#define SOC_PB_PP_ERR_DESC_BASE_SVEM_ACCESS_LAST              (SOC_PB_PP_ERR_DESC_BASE_SVEM_ACCESS_FIRST + 10)
#define SOC_PB_PP_ERR_DESC_BASE_ESEM_FIRST                    (SOC_PB_PP_ERR_DESC_BASE_SVEM_ACCESS_LAST + 1)
#define SOC_PB_PP_ERR_DESC_BASE_FP_EGR_FIRST                  (SOC_PB_PP_ERR_DESC_BASE_SVEM_ACCESS_LAST + 1)
#define SOC_PB_PP_ERR_DESC_BASE_FP_EGR_LAST                   (SOC_PB_PP_ERR_DESC_BASE_FP_EGR_FIRST + 10)
#define SOC_PB_PP_ERR_DESC_BASE_FP_FEM_FIRST                  (SOC_PB_PP_ERR_DESC_BASE_FP_EGR_LAST + 1)
#define SOC_PB_PP_ERR_DESC_BASE_FP_FEM_LAST                   (SOC_PB_PP_ERR_DESC_BASE_FP_FEM_FIRST + 10)
#define SOC_PB_PP_ERR_DESC_BASE_SSR_FIRST                     (SOC_PB_PP_ERR_DESC_BASE_FP_FEM_LAST + 1)
#define SOC_PB_PP_ERR_DESC_BASE_SSR_LAST                      (SOC_PB_PP_ERR_DESC_BASE_SSR_FIRST + 10)

/* } */
/*************
 * MACROS    *
 *************/
/* { */

/* } */
/*************
 * TYPE DEFS *
 *************/
/* { */

typedef enum
{
  /*
   * Auto generated. Do not edit following section {
   */
  SOC_PB_PP_PROCEDURE_DESC_ADD = SOC_PB_PP_PROC_DESC_BASE_FRAMEWORK_FIRST,
  SOC_PB_PP_ERRORS_DESC_ADD,
  SOC_PB_PP_FRAMEWORK_GET_PROCS_PTR,
  SOC_PB_PP_FRAMEWORK_GET_ERRS_PTR,
  /*
   * } Auto generated. Do not edit previous section.
   */

  /*
   * Last element. Do no touch.
   */
  SOC_PB_PP_FRAMEWORK_PROCEDURE_DESC_LAST
} SOC_PB_PP_FRAMEWORK_PROCEDURE_DESC;

typedef enum
{
  /*
   * Auto generated. Do not edit following section {
   */
  /*
   * } Auto generated. Do not edit previous section.
   */


  /*
   * Last element. Do no touch.
   */
  SOC_PB_PP_FRAMEWORK_ERR_LAST
} SOC_PB_PP_FRAMEWORK_ERR;

/* } */
/*************
 * GLOBALS   *
 *************/
/* { */

/* } */
/*************
 * FUNCTIONS *
 *************/
/* { */

/*********************************************************************
* NAME:
 *   soc_pb_pp_framework_get_procs_ptr
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Get the pointer to the list of procedures of the
 *   soc_pb_pp_api_framework module.
 * INPUT:
 * REMARKS:
 *
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
SOC_PROCEDURE_DESC_ELEMENT*
  soc_pb_pp_framework_get_procs_ptr(void);

/*********************************************************************
* NAME:
 *   soc_pb_pp_framework_get_errs_ptr
 * TYPE:
 *   PROC
 * FUNCTION:
 *   Get the pointer to the list of errors of the
 *   soc_pb_pp_api_framework module.
 * INPUT:
 * REMARKS:
 *
 * RETURNS:
 *   OK or ERROR indication.
*********************************************************************/
SOC_ERROR_DESC_ELEMENT*
  soc_pb_pp_framework_get_errs_ptr(void);

/* } */

#include <soc/dpp/SAND/Utils/sand_footer.h>

/* } __SOC_PB_PP_FRAMEWORK_INCLUDED__*/
#endif

