/** \file dbal_init_internal_tables_hard_logic_pp_context.h
 * Logical DB enums \n 
 * DO NOT EDIT THIS FILE!\n 
 * This file is auto-generated.\n 
 * Edits to this file will be lost when it is regenerated.\n 
 * \n 
 */
/*
 * $Id: $
 $Copyright: (c) 2020 Broadcom.
 Broadcom Proprietary and Confidential. All rights reserved.$
 * 
 */
#include <src/soc/dnx/dbal/dbal_internal.h>

shr_error_e
dbal_init_tables_hard_logic_pp_context_hl_pp_egress_context_init(
int unit,
table_db_struct_t * cur_table_param,
dbal_logical_table_t * table_info);
shr_error_e
dbal_init_tables_hard_logic_pp_context_hl_pp_egress_etps_init(
int unit,
table_db_struct_t * cur_table_param,
dbal_logical_table_t * table_info);
shr_error_e
dbal_init_tables_hard_logic_pp_context_hl_pp_ingress_context_init(
int unit,
table_db_struct_t * cur_table_param,
dbal_logical_table_t * table_info);
