#
# $Id: Makefile $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/appl/diag/dnx/gpm

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxgpm

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
