#
# $Id: Makefile $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/appl/diag/dnx/lif

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxlif

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
