#
# $Id: Makefile Exp $
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/ctest/dnx/apt

include ${SDK}/make/Make.config

lib = libctest_dnxapt

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend


