#!/bin/bash

if [ $# -ne 1 ]; then
    echo 'Usage: $0 <mkboards_path>'
    exit 1
fi

cd output/FastPath-Ent-esw-xgs4-pq3-LR-CSxw-IQH_CXO640G
cp ipl/switchdrvr ipl/devshell_symbols.gz $1/CXO640G-MX/rootfs/usr/local/ptin/sbin
#cp target/linux-kernel-bde.ko target/linux-user-bde.ko $0/CXO640G-MX/rootfs/usr/local/ptin/sbin
cd -

#cd target
#lc_put $1 $2 linux-kernel-bde.ko /usr/local/ptin/sbin
#lc_put $1 $2 linux-user-bde.ko /usr/local/ptin/sbin

#cp ../../../../../fastpath.shell/bin/fastpath.shell .
#lc_put $1 $2 fastpath.shell /usr/local/ptin/sbin .

#cp ../../../../../fastpath.cli/bin/fastpath.cli .
#lc_put $1 $2 fastpath.cli /usr/local/ptin/sbin .

#cd -
 
