#!/bin/bash

if [ $# -ne 2 ]; then
    echo 'Usage: $0 <cxp ip (last octet)> <lc ip (last octet)>'
    exit 1
fi

cd output/FastPath-Ent-esw-xgs4-e500-LR-CSxw-IQH_TA48GE/ipl
lc_put $1 $2 switchdrvr /usr/local/ptin/sbin
lc_put $1 $2 devshell_symbols.gz /usr/local/ptin/sbin
cd -

cd output/FastPath-Ent-esw-xgs4-e500-LR-CSxw-IQH_TA48GE/target
lc_put $1 $2 linux-kernel-bde /usr/local/ptin/sbin
lc_put $1 $2 linux-user-bde /usr/local/ptin/sbin
cd -

cd output/FastPath-Ent-esw-xgs4-e500-LR-CSxw-IQH_TA48GE
lc_put $1 $2 tg16g /usr/local/ptin/sbin
cd -

#cd target
#lc_put $1 $2 linux-kernel-bde.ko /usr/local/ptin/sbin
#lc_put $1 $2 linux-user-bde.ko /usr/local/ptin/sbin

#cp ../../../../../fastpath.shell/bin/fastpath.shell .
#lc_put $1 $2 fastpath.shell /usr/local/ptin/sbin .

#cp ../../../../../fastpath.cli/bin/fastpath.cli .
#lc_put $1 $2 fastpath.cli /usr/local/ptin/sbin .

#cd -
 
