/** \file dnx_data_egr_queuing.c
 * 
 * MODULE DEVICE DATA - EGR_QUEUING
 * 
 * Device Data
 * SW component that maintains per device data
 * For additional details about Device Data Component goto 'dnxc_data_mgmt.h'
 *        
 *     
 * 
 * AUTO-GENERATED BY AUTOCODER!
 * DO NOT EDIT THIS FILE!
 */
/* *INDENT-OFF* */
/*
 * $Copyright: (c) 2018 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */
#ifdef BSL_LOG_MODULE
#error "BSL_LOG_MODULE redefined"
#endif
#define BSL_LOG_MODULE BSL_LS_BCMDNX_EGRESSDNX
/**
 * \brief
 * Mark this file as device data internal file
 */
#define DNX_DATA_INTERNAL
/*
 * INCLUDE FILES:
 * {
 */
#include <soc/dnx/dnx_data/auto_generated/dnx_data_internal_egr_queuing.h>
/*
 * }
 */

/*
 * Extern per device attach function
 */
extern shr_error_e jer2_a0_data_egr_queuing_attach(
    int unit);
extern shr_error_e jer2_b0_data_egr_queuing_attach(
    int unit);
/*
 * SUBMODULE - PARAMS:
 * {
 */
/*
 * params init
 */
/**
 * \brief Set submodule data to default value per device type
 * 
 * \param [in] unit - Unit #
 * \param [out] submodule_data - pointer to submodule data
 * 
 * \return
 *     rv - see 'shr_error_e
 * \remark
 *   * Auto-generated using device data autocoder
 * \see
 *   * None
 */
static shr_error_e
dnx_data_egr_queuing_params_init(
    int unit,
    dnxc_data_submodule_t *submodule_data)
{
    SHR_FUNC_INIT_VARS(unit);

    submodule_data->name = "params";
    submodule_data->doc = "default values for egr_queuing module";
    /*
     * Features
     */
    submodule_data->nof_features = _dnx_data_egr_queuing_params_feature_nof;
    DNXC_DATA_ALLOC(submodule_data->features, dnxc_data_feature_t,  submodule_data->nof_features, "_dnxc_data egr_queuing params features");

    submodule_data->features[dnx_data_egr_queuing_params_conditional_crdt_table_access].name = "conditional_crdt_table_access";
    submodule_data->features[dnx_data_egr_queuing_params_conditional_crdt_table_access].doc = "Is 'port_read_enable' required before accessing OTM_CALENDAR_CRDT_TABLE? (temporary HW issue)";
    submodule_data->features[dnx_data_egr_queuing_params_conditional_crdt_table_access].flags |= DNXC_DATA_F_FEATURE;

    /*
     * Defines
     */
    submodule_data->nof_defines = _dnx_data_egr_queuing_params_define_nof;
    DNXC_DATA_ALLOC(submodule_data->defines, dnxc_data_define_t, submodule_data->nof_defines, "_dnxc_data egr_queuing params defines");

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_tcg_weight].name = "nof_bits_in_tcg_weight";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_tcg_weight].doc = "number of bits in 'weight' representation of a TCG. See EPS_DWM_8P";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_tcg_weight].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_q_pairs_in_ps].name = "nof_bits_in_nof_q_pairs_in_ps";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_q_pairs_in_ps].doc = "number of bits in 'nof_q_pairs_in_ps' representation. Essentially, log2(nof_q_pairs_in_ps)";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_q_pairs_in_ps].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_q_pairs_in_ps].name = "nof_q_pairs_in_ps";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_q_pairs_in_ps].doc = "Number of qpairs per one port scheduler";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_q_pairs_in_ps].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_q_pair].name = "nof_bits_in_q_pair";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_q_pair].doc = "number of bits in 'queue pair' representation. Essentially, log2(nof_q_pairs)";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_q_pair].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_q_pairs].name = "nof_q_pairs";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_q_pairs].doc = "Number of q_pairs per core";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_q_pairs].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_port_schedulers].name = "nof_bits_in_nof_port_schedulers";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_port_schedulers].doc = "number of bits in 'nof_port_schedulers' representation. Essentially, log2(nof_port_schedulers)";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_port_schedulers].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_port_schedulers].name = "nof_port_schedulers";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_port_schedulers].doc = "Number of port schedulers per core";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_port_schedulers].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_calendar_size].name = "nof_bits_in_calendar_size";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_calendar_size].doc = "number of bits in 'num. of entries in calendar' representation. Essentially, log2(calendar_size)";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_calendar_size].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_calendar_size].name = "calendar_size";
    submodule_data->defines[dnx_data_egr_queuing_params_define_calendar_size].doc = "number of entries in calendar";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_calendar_size].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_calendars].name = "nof_bits_in_nof_calendars";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_calendars].doc = "number of bits in 'egr nof_calendars' representation. Essentially, log2(nof_calendars)";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_calendars].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_calendars].name = "nof_calendars";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_calendars].doc = "Number of calendar-pairs per core. Total number of calendars is twice this value.";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_calendars].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_egr_interface].name = "nof_bits_in_egr_interface";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_egr_interface].doc = "number of bits in 'egr interface' representation. Essentially, log2(nof_egr_interfaces)";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_egr_interface].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_egr_interfaces].name = "nof_egr_interfaces";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_egr_interfaces].doc = "Number of egr interfaces, per core";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_egr_interfaces].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_reserved_if].name = "reserved_if";
    submodule_data->defines[dnx_data_egr_queuing_params_define_reserved_if].doc = "reserved interface (used for dummy flow control mapping in LAG SCH)";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_reserved_if].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_cpu].name = "egr_if_cpu";
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_cpu].doc = "cpu interface at egr";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_cpu].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_sat].name = "egr_if_sat";
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_sat].doc = "sat interface at egr";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_sat].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_oam].name = "egr_if_oam";
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_oam].doc = "oam interface at egr";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_oam].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_olp].name = "egr_if_olp";
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_olp].doc = "olp interface at egr";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_olp].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_rcy].name = "egr_if_rcy";
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_rcy].doc = "recycle interface at egr";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_rcy].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_txi_rcy].name = "egr_if_txi_rcy";
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_txi_rcy].doc = "txi recycle interface at egr";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_txi_rcy].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_eventor].name = "egr_if_eventor";
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_eventor].doc = "eventor interface at egr";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_egr_if_eventor].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_cal_res].name = "cal_res";
    submodule_data->defines[dnx_data_egr_queuing_params_define_cal_res].doc = "calendar resolution";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_cal_res].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_cal_burst_res].name = "cal_burst_res";
    submodule_data->defines[dnx_data_egr_queuing_params_define_cal_burst_res].doc = "calendar resolution";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_cal_burst_res].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_cal_cal_len].name = "nof_bits_in_cal_cal_len";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_cal_cal_len].doc = "Number of bits in representation of cal_cal_len (log2)";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_cal_cal_len].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_cal_cal_len].name = "cal_cal_len";
    submodule_data->defines[dnx_data_egr_queuing_params_define_cal_cal_len].doc = "calcal calendar length";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_cal_cal_len].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nif_cal_len].name = "nof_bits_in_nif_cal_len";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nif_cal_len].doc = "Number of bits in representation of nif_cal_len (log2)";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nif_cal_len].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nif_cal_len].name = "nif_cal_len";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nif_cal_len].doc = "nif calendar length";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nif_cal_len].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_tcg].name = "nof_bits_in_nof_tcg";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_tcg].doc = "Number of bits in representation of nof_tcg (log2)";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_tcg].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_tcg].name = "nof_tcg";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_tcg].doc = "Number of TC groups supported by this system";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_tcg].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_egr_q_prio].name = "nof_bits_in_nof_egr_q_prio";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_egr_q_prio].doc = "Number of bits in representation of nof_egr_q_prio (log2)";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_bits_in_nof_egr_q_prio].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_egr_q_prio].name = "nof_egr_q_prio";
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_egr_q_prio].doc = "Number of egress priorities for unscheduled traffic";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_nof_egr_q_prio].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_tcg_min_priorities].name = "tcg_min_priorities";
    submodule_data->defines[dnx_data_egr_queuing_params_define_tcg_min_priorities].doc = "minimum number of priorities supported by tcg";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_tcg_min_priorities].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_max_credit_number].name = "max_credit_number";
    submodule_data->defines[dnx_data_egr_queuing_params_define_max_credit_number].doc = "the maximum number of credits supported";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_max_credit_number].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_max_gbps_rate_egq].name = "max_gbps_rate_egq";
    submodule_data->defines[dnx_data_egr_queuing_params_define_max_gbps_rate_egq].doc = "EGQ Maximum Gb/s rate. This is the upper boundary, it can be lower depending on the credit size";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_max_gbps_rate_egq].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_txq_iready_th].name = "txq_iready_th";
    submodule_data->defines[dnx_data_egr_queuing_params_define_txq_iready_th].doc = "Define ready TXQ treshold in PDs for non TDM queues, when Q is above this treshold FQP block relevant interface in EPS";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_txq_iready_th].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_txq_tdm_iready_th].name = "txq_tdm_iready_th";
    submodule_data->defines[dnx_data_egr_queuing_params_define_txq_tdm_iready_th].doc = "Define ready TXQ treshold in PDs for TDM queues, when Q is above this treshold FQP block relevant interface in EPS";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_txq_tdm_iready_th].flags |= DNXC_DATA_F_DEFINE;

    submodule_data->defines[dnx_data_egr_queuing_params_define_tdm_interleve].name = "tdm_interleve";
    submodule_data->defines[dnx_data_egr_queuing_params_define_tdm_interleve].doc = "Boolean. TDM interleaved queuing";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_tdm_interleve].flags |= DNXC_DATA_F_NUMERIC;

    submodule_data->defines[dnx_data_egr_queuing_params_define_tdm_tc].name = "tdm_tc";
    submodule_data->defines[dnx_data_egr_queuing_params_define_tdm_tc].doc = "TDM traffic class";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_tdm_tc].flags |= DNXC_DATA_F_NUMERIC;

    submodule_data->defines[dnx_data_egr_queuing_params_define_tdm_dp].name = "tdm_dp";
    submodule_data->defines[dnx_data_egr_queuing_params_define_tdm_dp].doc = "TDM drop precident";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_tdm_dp].flags |= DNXC_DATA_F_NUMERIC;

    submodule_data->defines[dnx_data_egr_queuing_params_define_tdm_exist].name = "tdm_exist";
    submodule_data->defines[dnx_data_egr_queuing_params_define_tdm_exist].doc = "Boolean. is TDM exist in the system";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_tdm_exist].flags |= DNXC_DATA_F_NUMERIC;

    submodule_data->defines[dnx_data_egr_queuing_params_define_invalid_otm_port].name = "invalid_otm_port";
    submodule_data->defines[dnx_data_egr_queuing_params_define_invalid_otm_port].doc = "tm port that is marked as invalid (per core)";
    /* Set data type flag */
    submodule_data->defines[dnx_data_egr_queuing_params_define_invalid_otm_port].flags |= DNXC_DATA_F_NUMERIC;

    /*
     * Tables
     */
    submodule_data->nof_tables = _dnx_data_egr_queuing_params_table_nof;
    DNXC_DATA_ALLOC(submodule_data->tables, dnxc_data_table_t, submodule_data->nof_tables, "_dnxc_data egr_queuing params tables");

    /*
     * Table - if_speed_params
     */
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].name = "if_speed_params";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].doc = "per port speed thresholds";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].flags |= DNXC_DATA_F_TABLE;
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].size_of_values = sizeof(dnx_data_egr_queuing_params_if_speed_params_t);
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].entry_get = dnx_data_egr_queuing_params_if_speed_params_entry_str_get;

    /* Keys */
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].nof_keys = 1;
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].keys[0].name = "idx";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].keys[0].doc = "table index";

    /* Values */
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].nof_values = 6;
    DNXC_DATA_ALLOC(submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values, dnxc_data_value_t, submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].nof_values, "_dnx_data_egr_queuing_params_table_if_speed_params table values");
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[0].name = "speed";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[0].type = "int";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[0].doc = "port speed in GHz";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[0].offset = UTILEX_OFFSETOF(dnx_data_egr_queuing_params_if_speed_params_t, speed);
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[1].name = "if_id";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[1].type = "int";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[1].doc = "port egq interface ID";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[1].offset = UTILEX_OFFSETOF(dnx_data_egr_queuing_params_if_speed_params_t, if_id);
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[2].name = "crdt_size";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[2].type = "int";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[2].doc = "TXI credits";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[2].offset = UTILEX_OFFSETOF(dnx_data_egr_queuing_params_if_speed_params_t, crdt_size);
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[3].name = "irdy_thr";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[3].type = "int";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[3].doc = "NRDY threshold";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[3].offset = UTILEX_OFFSETOF(dnx_data_egr_queuing_params_if_speed_params_t, irdy_thr);
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[4].name = "txq_max_bytes";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[4].type = "int";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[4].doc = "TXQ max bytes threshold";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[4].offset = UTILEX_OFFSETOF(dnx_data_egr_queuing_params_if_speed_params_t, txq_max_bytes);
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[5].name = "min_gap_hp";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[5].type = "int";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[5].doc = "minimum gap between consecutive access to same interface if serving HP Q";
    submodule_data->tables[dnx_data_egr_queuing_params_table_if_speed_params].values[5].offset = UTILEX_OFFSETOF(dnx_data_egr_queuing_params_if_speed_params_t, min_gap_hp);

    /*
     * Table - emr_fifo
     */
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].name = "emr_fifo";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].doc = "emr fifo parameters";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].flags |= DNXC_DATA_F_TABLE;
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].size_of_values = sizeof(dnx_data_egr_queuing_params_emr_fifo_t);
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].entry_get = dnx_data_egr_queuing_params_emr_fifo_entry_str_get;

    /* Keys */
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].nof_keys = 2;
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].keys[0].name = "idx";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].keys[0].doc = "table index";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].keys[1].name = "tdm";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].keys[1].doc = "tdm exist in the system";

    /* Values */
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].nof_values = 3;
    DNXC_DATA_ALLOC(submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values, dnxc_data_value_t, submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].nof_values, "_dnx_data_egr_queuing_params_table_emr_fifo table values");
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values[0].name = "depth";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values[0].type = "int";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values[0].doc = "depth configuration for each FIFO";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values[0].offset = UTILEX_OFFSETOF(dnx_data_egr_queuing_params_emr_fifo_t, depth);
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values[1].name = "almost_full";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values[1].type = "int";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values[1].doc = "configuration of almost full threshold";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values[1].offset = UTILEX_OFFSETOF(dnx_data_egr_queuing_params_emr_fifo_t, almost_full);
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values[2].name = "full";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values[2].type = "int";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values[2].doc = "configuration of full threshold";
    submodule_data->tables[dnx_data_egr_queuing_params_table_emr_fifo].values[2].offset = UTILEX_OFFSETOF(dnx_data_egr_queuing_params_emr_fifo_t, full);

    /*
     * Table - port_spr_pkt_mode
     */
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].name = "port_spr_pkt_mode";
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].doc = "is shaper working at packet mode";
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].flags |= DNXC_DATA_F_TABLE;
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].size_of_values = sizeof(dnx_data_egr_queuing_params_port_spr_pkt_mode_t);
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].entry_get = dnx_data_egr_queuing_params_port_spr_pkt_mode_entry_str_get;

    /* Keys */
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].nof_keys = 1;
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].keys[0].name = "port";
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].keys[0].doc = "logical port number";

    /* Values */
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].nof_values = 1;
    DNXC_DATA_ALLOC(submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].values, dnxc_data_value_t, submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].nof_values, "_dnx_data_egr_queuing_params_table_port_spr_pkt_mode table values");
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].values[0].name = "val";
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].values[0].type = "int";
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].values[0].doc = "Boolean. is shaper working at packet mode";
    submodule_data->tables[dnx_data_egr_queuing_params_table_port_spr_pkt_mode].values[0].offset = UTILEX_OFFSETOF(dnx_data_egr_queuing_params_port_spr_pkt_mode_t, val);


exit:
    SHR_FUNC_EXIT;
}

/*
 * params features
 */
int
dnx_data_egr_queuing_params_feature_get(
    int unit,
    dnx_data_egr_queuing_params_feature_e feature)
{
    return dnxc_data_mgmt_feature_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, feature);
}

/*
 * params defines
 */
uint32
dnx_data_egr_queuing_params_nof_bits_in_tcg_weight_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_bits_in_tcg_weight);
}

uint32
dnx_data_egr_queuing_params_nof_bits_in_nof_q_pairs_in_ps_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_bits_in_nof_q_pairs_in_ps);
}

uint32
dnx_data_egr_queuing_params_nof_q_pairs_in_ps_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_q_pairs_in_ps);
}

uint32
dnx_data_egr_queuing_params_nof_bits_in_q_pair_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_bits_in_q_pair);
}

uint32
dnx_data_egr_queuing_params_nof_q_pairs_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_q_pairs);
}

uint32
dnx_data_egr_queuing_params_nof_bits_in_nof_port_schedulers_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_bits_in_nof_port_schedulers);
}

uint32
dnx_data_egr_queuing_params_nof_port_schedulers_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_port_schedulers);
}

uint32
dnx_data_egr_queuing_params_nof_bits_in_calendar_size_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_bits_in_calendar_size);
}

uint32
dnx_data_egr_queuing_params_calendar_size_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_calendar_size);
}

uint32
dnx_data_egr_queuing_params_nof_bits_in_nof_calendars_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_bits_in_nof_calendars);
}

uint32
dnx_data_egr_queuing_params_nof_calendars_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_calendars);
}

uint32
dnx_data_egr_queuing_params_nof_bits_in_egr_interface_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_bits_in_egr_interface);
}

uint32
dnx_data_egr_queuing_params_nof_egr_interfaces_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_egr_interfaces);
}

uint32
dnx_data_egr_queuing_params_reserved_if_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_reserved_if);
}

uint32
dnx_data_egr_queuing_params_egr_if_cpu_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_egr_if_cpu);
}

uint32
dnx_data_egr_queuing_params_egr_if_sat_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_egr_if_sat);
}

uint32
dnx_data_egr_queuing_params_egr_if_oam_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_egr_if_oam);
}

uint32
dnx_data_egr_queuing_params_egr_if_olp_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_egr_if_olp);
}

uint32
dnx_data_egr_queuing_params_egr_if_rcy_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_egr_if_rcy);
}

uint32
dnx_data_egr_queuing_params_egr_if_txi_rcy_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_egr_if_txi_rcy);
}

uint32
dnx_data_egr_queuing_params_egr_if_eventor_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_egr_if_eventor);
}

uint32
dnx_data_egr_queuing_params_cal_res_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_cal_res);
}

uint32
dnx_data_egr_queuing_params_cal_burst_res_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_cal_burst_res);
}

uint32
dnx_data_egr_queuing_params_nof_bits_in_cal_cal_len_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_bits_in_cal_cal_len);
}

uint32
dnx_data_egr_queuing_params_cal_cal_len_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_cal_cal_len);
}

uint32
dnx_data_egr_queuing_params_nof_bits_in_nif_cal_len_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_bits_in_nif_cal_len);
}

uint32
dnx_data_egr_queuing_params_nif_cal_len_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nif_cal_len);
}

uint32
dnx_data_egr_queuing_params_nof_bits_in_nof_tcg_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_bits_in_nof_tcg);
}

uint32
dnx_data_egr_queuing_params_nof_tcg_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_tcg);
}

uint32
dnx_data_egr_queuing_params_nof_bits_in_nof_egr_q_prio_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_bits_in_nof_egr_q_prio);
}

uint32
dnx_data_egr_queuing_params_nof_egr_q_prio_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_nof_egr_q_prio);
}

uint32
dnx_data_egr_queuing_params_tcg_min_priorities_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_tcg_min_priorities);
}

uint32
dnx_data_egr_queuing_params_max_credit_number_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_max_credit_number);
}

uint32
dnx_data_egr_queuing_params_max_gbps_rate_egq_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_max_gbps_rate_egq);
}

uint32
dnx_data_egr_queuing_params_txq_iready_th_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_txq_iready_th);
}

uint32
dnx_data_egr_queuing_params_txq_tdm_iready_th_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_txq_tdm_iready_th);
}

uint32
dnx_data_egr_queuing_params_tdm_interleve_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_tdm_interleve);
}

uint32
dnx_data_egr_queuing_params_tdm_tc_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_tdm_tc);
}

uint32
dnx_data_egr_queuing_params_tdm_dp_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_tdm_dp);
}

uint32
dnx_data_egr_queuing_params_tdm_exist_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_tdm_exist);
}

uint32
dnx_data_egr_queuing_params_invalid_otm_port_get(
    int unit)
{
    return dnxc_data_mgmt_define_data_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_define_invalid_otm_port);
}

/*
 * params tables
 */
/* Table Get */
const dnx_data_egr_queuing_params_if_speed_params_t *
dnx_data_egr_queuing_params_if_speed_params_get(
    int unit,
    int idx)
{
    char *data;
    dnxc_data_table_t *table;

    /* Get table */
    table = dnxc_data_mgmt_table_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_table_if_speed_params);
    /* Get data */
    data = dnxc_data_mgmt_table_data_get(unit, table, idx, 0);
    return (const dnx_data_egr_queuing_params_if_speed_params_t *) data;

}

const dnx_data_egr_queuing_params_emr_fifo_t *
dnx_data_egr_queuing_params_emr_fifo_get(
    int unit,
    int idx,
    int tdm)
{
    char *data;
    dnxc_data_table_t *table;

    /* Get table */
    table = dnxc_data_mgmt_table_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_table_emr_fifo);
    /* Get data */
    data = dnxc_data_mgmt_table_data_get(unit, table, idx, tdm);
    return (const dnx_data_egr_queuing_params_emr_fifo_t *) data;

}

const dnx_data_egr_queuing_params_port_spr_pkt_mode_t *
dnx_data_egr_queuing_params_port_spr_pkt_mode_get(
    int unit,
    int port)
{
    char *data;
    dnxc_data_table_t *table;

    /* Get table */
    table = dnxc_data_mgmt_table_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_table_port_spr_pkt_mode);
    /* Get data */
    data = dnxc_data_mgmt_table_data_get(unit, table, port, 0);
    return (const dnx_data_egr_queuing_params_port_spr_pkt_mode_t *) data;

}

/* Get value as str */
shr_error_e
dnx_data_egr_queuing_params_if_speed_params_entry_str_get(
    int unit,
    char *buffer,
    int key0,
    int key1,
    int value_index)
{
    dnxc_data_table_t *table;
    const dnx_data_egr_queuing_params_if_speed_params_t *data;
    SHR_FUNC_INIT_VARS(unit);

    /* Get table */
    table = dnxc_data_mgmt_table_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_table_if_speed_params);
    data = (const dnx_data_egr_queuing_params_if_speed_params_t *) dnxc_data_mgmt_table_data_diag_get(unit, table, key0, 0);
    switch (value_index)
    {
        case 0:
            sal_snprintf(buffer, DNXC_DATA_MGMT_MAX_TABLE_VALUE_LENGTH, "%d", data->speed);
            break;
        case 1:
            sal_snprintf(buffer, DNXC_DATA_MGMT_MAX_TABLE_VALUE_LENGTH, "%d", data->if_id);
            break;
        case 2:
            sal_snprintf(buffer, DNXC_DATA_MGMT_MAX_TABLE_VALUE_LENGTH, "%d", data->crdt_size);
            break;
        case 3:
            sal_snprintf(buffer, DNXC_DATA_MGMT_MAX_TABLE_VALUE_LENGTH, "%d", data->irdy_thr);
            break;
        case 4:
            sal_snprintf(buffer, DNXC_DATA_MGMT_MAX_TABLE_VALUE_LENGTH, "%d", data->txq_max_bytes);
            break;
        case 5:
            sal_snprintf(buffer, DNXC_DATA_MGMT_MAX_TABLE_VALUE_LENGTH, "%d", data->min_gap_hp);
            break;
    }

    SHR_FUNC_EXIT;
}

shr_error_e
dnx_data_egr_queuing_params_emr_fifo_entry_str_get(
    int unit,
    char *buffer,
    int key0,
    int key1,
    int value_index)
{
    dnxc_data_table_t *table;
    const dnx_data_egr_queuing_params_emr_fifo_t *data;
    SHR_FUNC_INIT_VARS(unit);

    /* Get table */
    table = dnxc_data_mgmt_table_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_table_emr_fifo);
    data = (const dnx_data_egr_queuing_params_emr_fifo_t *) dnxc_data_mgmt_table_data_diag_get(unit, table, key0, key1);
    switch (value_index)
    {
        case 0:
            sal_snprintf(buffer, DNXC_DATA_MGMT_MAX_TABLE_VALUE_LENGTH, "%d", data->depth);
            break;
        case 1:
            sal_snprintf(buffer, DNXC_DATA_MGMT_MAX_TABLE_VALUE_LENGTH, "%d", data->almost_full);
            break;
        case 2:
            sal_snprintf(buffer, DNXC_DATA_MGMT_MAX_TABLE_VALUE_LENGTH, "%d", data->full);
            break;
    }

    SHR_FUNC_EXIT;
}

shr_error_e
dnx_data_egr_queuing_params_port_spr_pkt_mode_entry_str_get(
    int unit,
    char *buffer,
    int key0,
    int key1,
    int value_index)
{
    dnxc_data_table_t *table;
    const dnx_data_egr_queuing_params_port_spr_pkt_mode_t *data;
    SHR_FUNC_INIT_VARS(unit);

    /* Get table */
    table = dnxc_data_mgmt_table_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_table_port_spr_pkt_mode);
    data = (const dnx_data_egr_queuing_params_port_spr_pkt_mode_t *) dnxc_data_mgmt_table_data_diag_get(unit, table, key0, 0);
    switch (value_index)
    {
        case 0:
            sal_snprintf(buffer, DNXC_DATA_MGMT_MAX_TABLE_VALUE_LENGTH, "%d", data->val);
            break;
    }

    SHR_FUNC_EXIT;
}

/* Table Info Get */
const dnxc_data_table_info_t *
dnx_data_egr_queuing_params_if_speed_params_info_get(
    int unit)
{

    /* Return table info */
    return dnxc_data_mgmt_table_info_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_table_if_speed_params);

}

const dnxc_data_table_info_t *
dnx_data_egr_queuing_params_emr_fifo_info_get(
    int unit)
{

    /* Return table info */
    return dnxc_data_mgmt_table_info_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_table_emr_fifo);

}

const dnxc_data_table_info_t *
dnx_data_egr_queuing_params_port_spr_pkt_mode_info_get(
    int unit)
{

    /* Return table info */
    return dnxc_data_mgmt_table_info_get(unit, dnx_data_module_egr_queuing, dnx_data_egr_queuing_submodule_params, dnx_data_egr_queuing_params_table_port_spr_pkt_mode);

}

/*
 * }
 */

shr_error_e
dnx_data_egr_queuing_init(
    int unit,
    dnxc_data_module_t *module_data)
{
    SHR_FUNC_INIT_VARS(unit);

    /* Data Struct Init */
    module_data->name = "egr_queuing";
    module_data->nof_submodules = _dnx_data_egr_queuing_submodule_nof;
    DNXC_DATA_ALLOC(module_data->submodules, dnxc_data_submodule_t, module_data->nof_submodules, "_dnxc_data egr_queuing submodules");

    /*
     * Init Submodule data
     */
    SHR_IF_ERR_EXIT(dnx_data_egr_queuing_params_init(unit, &module_data->submodules[dnx_data_egr_queuing_submodule_params]));
    /*
     * Attach device module
     */
    if (dnxc_data_mgmt_is_jer2_a0(unit))
    {
        SHR_IF_ERR_EXIT(jer2_a0_data_egr_queuing_attach(unit));
    }
    else
    if (dnxc_data_mgmt_is_jer2_b0(unit))
    {
        SHR_IF_ERR_EXIT(jer2_a0_data_egr_queuing_attach(unit));
        SHR_IF_ERR_EXIT(jer2_b0_data_egr_queuing_attach(unit));
    }

exit:
    SHR_FUNC_EXIT;
}
/* *INDENT-ON* */
