#
#
# $Copyright: (c) 2021 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dnx/pll

include ${SDK}/make/Make.config
include ${SDK}/make/Make.subdirs

lib = libsoc_dnxpll

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
