#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/tunnel

include ${SDK}/make/Make.config

#subdirs = tunnel

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxtunnel

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

