#
# $Id:$
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC swstate utils subdirectory
#
LOCALDIR = src/shared/swstate/utils

# enable optimization & disable debugging for this lib
DEBUG_OPTIMIZE = TRUE
DEBUG_CFLAGS += -g0
include ${SDK}/make/Make.config

lib = libshared_swstate_utils

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
