/* $Id: $
 * 
 * $Copyright: Copyright 2016 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * search for 'sw_state_cbs_t' for the root of the struct
 */

#ifndef _SHR_SW_STATE_DPP_SOC_ARAD_TM_INTERRUPTS_ACCESS_H_
#define _SHR_SW_STATE_DPP_SOC_ARAD_TM_INTERRUPTS_ACCESS_H_

/********************************* access calbacks definitions *************************************/
/* this set of callbacks, are the callbacks used in the access calbacks struct 'sw_state_cbs_t' to */
/* access the data in 'sw_state_t'.                                                                */
/* the calbacks are inserted into the access struct by 'sw_state_access_cb_init'.                  */
/***************************************************************************************************/

/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_alloc */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_alloc_cb)(
    int unit);

/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_is_allocated */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_is_allocated_cb)(
    int unit, uint8 *is_allocated);

/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_free */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_free_cb)(
    int unit);

/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_verify */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_verify_cb)(
    int unit);

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_cmc_irq2_mask_set */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_cmc_irq2_mask_set_cb)(
    int unit, int cmc_irq2_mask_idx_0, uint32 cmc_irq2_mask);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_cmc_irq2_mask_get */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_cmc_irq2_mask_get_cb)(
    int unit, int cmc_irq2_mask_idx_0, uint32 *cmc_irq2_mask);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_cmc_irq2_mask_verify */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_cmc_irq2_mask_verify_cb)(
    int unit, int cmc_irq2_mask_idx_0);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_cmc_irq3_mask_set */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_cmc_irq3_mask_set_cb)(
    int unit, int cmc_irq3_mask_idx_0, uint32 cmc_irq3_mask);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_cmc_irq3_mask_get */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_cmc_irq3_mask_get_cb)(
    int unit, int cmc_irq3_mask_idx_0, uint32 *cmc_irq3_mask);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_cmc_irq3_mask_verify */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_cmc_irq3_mask_verify_cb)(
    int unit, int cmc_irq3_mask_idx_0);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_cmc_irq4_mask_set */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_cmc_irq4_mask_set_cb)(
    int unit, int cmc_irq4_mask_idx_0, uint32 cmc_irq4_mask);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_cmc_irq4_mask_get */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_cmc_irq4_mask_get_cb)(
    int unit, int cmc_irq4_mask_idx_0, uint32 *cmc_irq4_mask);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_cmc_irq4_mask_verify */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_cmc_irq4_mask_verify_cb)(
    int unit, int cmc_irq4_mask_idx_0);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_set */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_set_cb)(
    int unit, int interrupt_data_idx_0, CONST ARAD_INTERRUPT_DATA *interrupt_data);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_get */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_get_cb)(
    int unit, int interrupt_data_idx_0, ARAD_INTERRUPT_DATA *interrupt_data);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_alloc */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_alloc_cb)(
    int unit, int nof_instances_to_alloc);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_is_allocated */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_is_allocated_cb)(
    int unit, uint8 *is_allocated);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_free */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_free_cb)(
    int unit);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_verify */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_verify_cb)(
    int unit, int interrupt_data_idx_0);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_flags_set */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_flags_set_cb)(
    int unit, int interrupt_data_idx_0, uint32 flags);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_flags_get */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_flags_get_cb)(
    int unit, int interrupt_data_idx_0, uint32 *flags);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_flags_verify */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_flags_verify_cb)(
    int unit, int interrupt_data_idx_0);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_count_set */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_count_set_cb)(
    int unit, int interrupt_data_idx_0, uint32 storm_timed_count);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_count_get */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_count_get_cb)(
    int unit, int interrupt_data_idx_0, uint32 *storm_timed_count);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_count_verify */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_count_verify_cb)(
    int unit, int interrupt_data_idx_0);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_period_set */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_period_set_cb)(
    int unit, int interrupt_data_idx_0, uint32 storm_timed_period);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_period_get */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_period_get_cb)(
    int unit, int interrupt_data_idx_0, uint32 *storm_timed_period);
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
/* implemented by: sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_period_verify */
typedef int (*sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_period_verify_cb)(
    int unit, int interrupt_data_idx_0);
#endif /* BCM_ARAD_SUPPORT*/ 

/*********************************** access calbacks struct ****************************************/
/* this set of structs, rooted at 'sw_state_cbs_t' define the access layer for the entire SW state.*/
/* use this tree to alloc/free/set/get fields in the sw state rooted at 'sw_state_t'.              */
/* NOTE: 'sw_state_t' data should not be accessed directly.                                        */
/***************************************************************************************************/

#ifdef BCM_ARAD_SUPPORT
typedef struct sw_state_dpp_soc_arad_tm_interrupts_cmc_irq2_mask_cbs_s {
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_cmc_irq2_mask_set_cb set;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_cmc_irq2_mask_get_cb get;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_cmc_irq2_mask_verify_cb verify;
#endif /* BCM_ARAD_SUPPORT*/ 
} sw_state_dpp_soc_arad_tm_interrupts_cmc_irq2_mask_cbs_t;
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
typedef struct sw_state_dpp_soc_arad_tm_interrupts_cmc_irq3_mask_cbs_s {
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_cmc_irq3_mask_set_cb set;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_cmc_irq3_mask_get_cb get;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_cmc_irq3_mask_verify_cb verify;
#endif /* BCM_ARAD_SUPPORT*/ 
} sw_state_dpp_soc_arad_tm_interrupts_cmc_irq3_mask_cbs_t;
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
typedef struct sw_state_dpp_soc_arad_tm_interrupts_cmc_irq4_mask_cbs_s {
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_cmc_irq4_mask_set_cb set;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_cmc_irq4_mask_get_cb get;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_cmc_irq4_mask_verify_cb verify;
#endif /* BCM_ARAD_SUPPORT*/ 
} sw_state_dpp_soc_arad_tm_interrupts_cmc_irq4_mask_cbs_t;
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
typedef struct sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_flags_cbs_s {
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_flags_set_cb set;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_flags_get_cb get;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_flags_verify_cb verify;
#endif /* BCM_ARAD_SUPPORT*/ 
} sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_flags_cbs_t;
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
typedef struct sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_count_cbs_s {
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_count_set_cb set;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_count_get_cb get;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_count_verify_cb verify;
#endif /* BCM_ARAD_SUPPORT*/ 
} sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_count_cbs_t;
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
typedef struct sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_period_cbs_s {
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_period_set_cb set;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_period_get_cb get;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_period_verify_cb verify;
#endif /* BCM_ARAD_SUPPORT*/ 
} sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_period_cbs_t;
#endif /* BCM_ARAD_SUPPORT*/ 

#ifdef BCM_ARAD_SUPPORT
typedef struct sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_cbs_s {
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_set_cb set;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_get_cb get;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_alloc_cb alloc;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_is_allocated_cb is_allocated;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_free_cb free;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_verify_cb verify;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_flags_cbs_t flags;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_count_cbs_t storm_timed_count;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_storm_timed_period_cbs_t storm_timed_period;
#endif /* BCM_ARAD_SUPPORT*/ 
} sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_cbs_t;

#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
typedef struct sw_state_dpp_soc_arad_tm_interrupts_cbs_s {
    sw_state_dpp_soc_arad_tm_interrupts_alloc_cb alloc;
    sw_state_dpp_soc_arad_tm_interrupts_is_allocated_cb is_allocated;
    sw_state_dpp_soc_arad_tm_interrupts_free_cb free;
    sw_state_dpp_soc_arad_tm_interrupts_verify_cb verify;
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_cmc_irq2_mask_cbs_t cmc_irq2_mask;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_cmc_irq3_mask_cbs_t cmc_irq3_mask;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_cmc_irq4_mask_cbs_t cmc_irq4_mask;
#endif /* BCM_ARAD_SUPPORT*/ 
#ifdef BCM_ARAD_SUPPORT
    sw_state_dpp_soc_arad_tm_interrupts_interrupt_data_cbs_t interrupt_data;
#endif /* BCM_ARAD_SUPPORT*/ 
} sw_state_dpp_soc_arad_tm_interrupts_cbs_t;

#endif /* BCM_ARAD_SUPPORT*/ 

int sw_state_dpp_soc_arad_tm_interrupts_access_cb_init(int unit);

#endif /* _SHR_SW_STATE_DPP_SOC_ARAD_TM_INTERRUPTS_ACCESS_H_ */
