# $Id$
# $Copyright: (c) 2011 Broadcom Corp.
# All Rights Reserved.$

LOCALDIR = src/soc/kbp/nlm3

include ${SDK}/make/Make.config

KBP_SRCS += ../common nlmdevmgr nlmgenerictblmgr nlmrangemgr blackholexpt xpt

subdirs := $(KBP_SRCS)

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.depend
